### ISSUE TITLE
[Feature Request]Error while creating VPC Network ACL with generation parameter set to 2

### ISSUE THREAD

**Issue by VaishnaviGopal** [IBM-Cloud/terraform-provider-ibm#1000]
While declaring an ACL with just a name, and its failing in the apply plan.  

"resource "ibm_is_network_acl" "isExampleACL" { name = "is-example-acl"   } to create a blank ACL in a VPC.
2020/01/08 16:13:40 Terraform apply | 	* module.vpc_infrastructure.ibm_is_network_acl.isExampleACL: 1 error occurred:
 2020/01/08 16:13:40 Terraform apply | 	* ibm_is_network_acl.isExampleACL: {"errors":[{"code":"bad_field","message":"Invalid json payload provided","target":{"name":"network_acls.network_acls.vpc","type":"field"}}],"trace":"826f953a-5530-450b-826f-d8c0aafc8dcd"}

Generating the plan for this ACL does not fail.

**Comment by hkantare** [comment]
The ibm_is_network_acl support is available only for Gen1 . The support for Gen2 is added recently.
We are working on updating Terraform provider to support network_acl support for Gen2.

**Comment by hkantare** [comment]
Support for  network_Acl for gen2 is available in latest releases v0.23.0 and v1.1.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases
