### ISSUE TITLE
[Feature request] Provide update support for ibm_container_vpc_cluster resource

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#1004]
Provide Update support to 

Upgrade kube version of master and workers nodes
Add support to resize the worker_pools(worker_count) for ibm_container_vpc_cluster

**Comment by hkantare** [comment]
Fixed in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.0

**Comment by somaya10** [comment]
@hkantare thanks for the update. Could you point me to the documentation that details how one can use this feature? Terraform IBM provider git repo points to --> https://ibm-cloud.github.io/tf-ibm-docs/v1.1.0/ which is behind on these updates.

**Comment by hkantare** [comment]
https://ibm-cloud.github.io/tf-ibm-docs/v1.2.0/
