### ISSUE TITLE
Add tag support  Load Balancer, Volume & Image resources

### ISSUE THREAD

**Issue by mkmrah** [IBM-Cloud/terraform-provider-ibm#1027]
Please add Tag support for the below resources

| Gen2 Resource        | UI Tag           | TerraformTag  |
| ------------- |:-------------:| -----:|
| Load Balancer      | Yes| No|
| VSI    | Yes      |   No |
| Import Custom Image | Yes      |    No |
| Volume | Yes      |    No |

**Comment by hkantare** [comment]
Available in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.0
