### ISSUE TITLE
Hardware Firewall Shared is getting failed while creating.

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#1031]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_firewall_shared

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "ibm_firewall_shared" "hardwarefirewall" {
        firewall_type = "100MBPS_HARDWARE_FIREWALL"
    hardware_instance_id = "id"
}
```

### Debug Output
ibm_firewall_shared.hardwarefirewall: Still creating... (10s elapsed)
ibm_firewall_shared.hardwarefirewall: Still creating... (20s elapsed)
ibm_firewall_shared.hardwarefirewall: Still creating... (30s elapsed)
Error: Error applying plan:
1 error(s) occurred:
* ibm_firewall_shared.hardwarefirewall: 1 error(s) occurred:
* ibm_firewall_shared.hardwarefirewall: unexpected EOF

### Panic Output
Attaching logs from terraform
[abc.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/4115602/abc.txt)

### Expected Behavior
Should create harware firewall successfully

### Actual Behavior
It fails 
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

**Comment by M-Rushabh** [comment]
@hkantare  As discuss with you need to add wait before the status is approved.
It fails to get id.
``idd2 := *resultNew.FirewallServiceComponent.Id```

**Comment by hkantare** [comment]
Fixed in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.0

**Comment by SukeshPrabhakar** [comment]
Closing issue since it is resolved.
