### ISSUE TITLE
Terraform for classic IKS + block storage helm chart

### ISSUE THREAD

**Issue by bennythejudge** [IBM-Cloud/terraform-provider-ibm#1036]
Is there a preferred way to add the block storage helm chart to an IKS cluster provisioned using the Tf provider?

The Tf docs contains examples of using a `ibm_storage_block` resource (https://ibm-cloud.github.io/tf-ibm-docs/v1.0.0/r/storage_block.html), but there is no mention of how one would get the helm chart installed in the cluster within the terraform files.

I can provision a multi-zone IKS cluster using the terraform provider, what can I do to get the block storage add-on helm chart installed to the cluster? 

Do I need to use a script or can I do something within my Tf files?

Thanks

**Comment by hkantare** [comment]
You can other providers like kubernetes and helm to install helm chart and create respective secrets
https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-storage-cos
Here we automated some requirment to create COS, install cos plugin and create PVC

**Comment by bennythejudge** [comment]
@hkantare thanks!
