### ISSUE TITLE
[feature request] Register IBM provider in Hashicorp's repository

### ISSUE THREAD

**Issue by omgapuppy** [IBM-Cloud/terraform-provider-ibm#1052]
Essentially [regurgitating an old issue](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/272#issuecomment-469343057) that got no response in relation to the below. Having to manually install a provider is rather poor user experience, especially from a major provider like IBM when a ton of much smaller SaaS/PaaS providers have their providers officially listed in Hashicorp repo.
Many others even contribute well maintained modules to accelerate common workflows / resource sets.

Would it be possible to register the IBM provider with the Terraform provider repository?

**Expected Behavior**
I would expect terraform init to be able to automatically download the IBM provider when it is referenced in a Terraform configuration.

**Actual Behavior**
```
$ terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "ibm" not available for installation.

A provider named "ibm" could not be found in the official repository.
[...]
```

**Steps to Reproduce**
Have `~/.terraform.d/plugins/` NOT contain `terraform-provider-ibm_*`
Have a file `main.tf` with contents `provider "ibm" {}`
Run `terraform init`

**Comment by davetropeano** [comment]
Thank you for the request. As you noted, this has come up a number of times. IBM and Hashicorp do not have a business partner relationship. This blocks IBM from fully participating in the opensource Terraform project's governance model and from being considered a major cloud provider.

As a result, the IBM Cloud Provider for Terraform is considered a community provider by Hashicorp and is not directly installable via a `terraform init`, does not have its resource definitions represented on `terraform.io`, etc.

Unfortunately, at this time it is not likely this situation will change. For the forseeable future you will have to manually install the terraform plugin or use the (no charge) IBM Cloud Schematics service (https://cloud.ibm.com/schematics)

**Comment by SukeshPrabhakar** [comment]
Based on @davetropeano  response, closing the issue.
