### ISSUE TITLE
[Feature Request]: Adding iam_auth_token support for IBM provider 

### ISSUE THREAD

**Issue by indirakalagara** [IBM-Cloud/terraform-provider-ibm#1062]
Hi Team,

Currently IBM provider takes only ibmcloud_api_key in provider definition as 
provider "ibm" {
  ibmcloud_api_key      = var.ibm_bmx_api_key
  iaas_classic_username = var.ibm_sl_username
  iaas_classic_api_key  = var.ibm_sl_api_key
}
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/new

Instead of sharing this unique API key in the script, we should have  a provision to use token (  ibm_iam_auth_token  ) as it has validity so that we can have more control on the provisioning resources.

**Comment by hkantare** [comment]
Its not a valid scenario to generate the tokens using ibm_iam_auth_token also you need a API key to login to ibm cloud . Once you have successfull login only you can generate tokens

**Comment by hkantare** [comment]
closing this issue
