### ISSUE TITLE
Feature Request: VPC_Compute Autoscaling group

### ISSUE THREAD

**Issue by braddison** [IBM-Cloud/terraform-provider-ibm#1072]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
.12

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_compute_instance
- is_vpc

There is currently no way to provision an autoscaling group within a VPC. I'm not sure if this is on the provider side however as I don't see a way in the UI.

**Comment by stevestrutt** [comment]
Auto-scale groups are not yet available. Last I saw was likely to be Q2. Note they will only be available in Gen2.

**Comment by hkantare** [comment]
We support VPC Autoscale in latest releases
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#vpc-is-instance-grp
