### ISSUE TITLE
Associate existing FloatingIP to VSI 

### ISSUE THREAD

**Issue by indirakalagara** [IBM-Cloud/terraform-provider-ibm#1075]
Hi there,

Currently  the terraform resource "ibm_is_floating_ip" is creating the new floating IP and attaching to the target VSI primary network interface. 
However, if we already have the floating IP, there is no option to associate with the VSI.  This is currently achievable through API ( 
https://cloud.ibm.com/apidocs/vpc#associate-a-floating-ip-with-a-network-interface  ) 

Request the same feature to be available with terraform provider.

### Terraform Version
IBM Cloud Provider - 1.2.0 
Terraform v0.12.19

**Comment by powellquiring** [comment]
There is no import capability documented here: https://ibm-cloud.github.io/tf-ibm-docs/v1.2.1/r/is_floating_ip.html

There is also no existing data sources for is_floating_ip documented.

**Comment by VaishnaviGopal** [comment]
Hi @powellquiring @indirakalagara 

Use the latest [provider](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.18.0) which has Data source support for `floating_ip` and it is documented [here](https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-data-sources#floating-ip-g2-ds)

Import Capability for `floating_ip` was always existing, but the documentation is recently updated.
FYR: https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#floating-ip-import


As the requirements are satisfied with the latest provider, Closing this issue.
