### ISSUE TITLE
Changing security group on vpc next gen instance does not apply change

### ISSUE THREAD

**Issue by argeiger** [IBM-Cloud/terraform-provider-ibm#1078]
I am trying to add another security group to an interface of an instance.  The plan shows the change and shows that the resource was changed after apply but in the end the change never was applied.  If I run the apply again, it shows that the change still needs to take place so the action never occurred. 

### Terraform Version
Terraform v0.12.16
+ provider.ibm v1.2.0
+ provider.template v2.1.2

### Affected Resource(s)
- ibm_is_instance

### Terraform Configuration Plan
```hcl
      .....
      primary_network_interface {
            id                   = "0717-049259f0-a563-4423-aedf-e73047ce7bd3"
            name                 = "default"
            port_speed           = 0
            primary_ipv4_address = "172.21.0.4"
          ~ security_groups      = [
              + "r006-33261313-4ab6-4f3f-8bae-17a1e6f0baab",
                "r006-c19cf599-da44-4e50-84ae-42b7297c35bf",
            ]
            subnet               = "0717-2a30f637-a914-48eb-a98c-2db0ba75029b"
        }
```

### Expected Behavior
The security group should have been added to the interface

### Actual Behavior
Security group was not added to the interface

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an instance with the default security group
2. Apply the plan: `terraform apply`
3. Modify the terraform plan to add another security group and add it to the interface of the instance
4. Apply the plan: `terraform apply`
5. Verify that the security groups were added to the interface

**Comment by hkantare** [comment]
We don't see from UI or cli to change the security groups for an n/w interface

In our terraform resource we can add a parameter to force-new when we see change in security groups

**Comment by hkantare** [comment]
Fix available in master..It will be part of next release(early next week)

**Comment by hkantare** [comment]
Fix a available in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.2
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.2
