### ISSUE TITLE
ibm_is_network_acl does not have attributes to specify the source port(s)

### ISSUE THREAD

**Issue by alainmitry** [IBM-Cloud/terraform-provider-ibm#1080]
Hi there,

### Terraform Version
Using terraform version v0.11.14 with provider.ibm v1.1.0 and there are some problems working with VPC gen 1.

### Affected Resource(s)
The resource “ibm_is_network_acl” does not have attributes to specify the source port(s)

### Actual Behaviour
The only attributes for ports are limited to destination port(s) only and there is no way to specify the source port(s).
Considering that ACL works in stateless if one want’s to only open SSH flow from outside to inside and limit it, one should do the following rules:
Inbound rule 1: allow from <client public address> port any to <any or internal network cidr> port 22
Inbound rule 2: deny from any to any
Outbound rule 1 (allow the reply of inbound rule 1): allow from <any or network cidr> port 22 to <client public address> port any
Outbound rule 2: deny from any to any

### Steps to Reproduce
resource "ibm_is_network_acl" "test-acl" {
  name = "test-acl"
  #This rule is wrong (Attempt to create Outbound rule 1). I want to make the reply rule for the one bellow (in_ssh)
  #I cannot specify the source port, because the tcp attribute only specifies the destination ports
  #INTENTION: from 0.0.0.0/0 port 22 to 210.90.77.125 (internet) port any in outbound
  #what this actualy do is: from 0.0.0.0/0 port any to 210.90.77.125 (internet) port 22 in outbound
  rules {
    name        = "out_ssh"
    action      = "allow"
    source      = "0.0.0.0/0"
    destination = "20.9.77.125"
    direction   = "outbound"
    #This is not source port(s) but destination port(s)
    tcp {
      port_min = 22
      port_max = 22
    }
  }
  #Allow access from 210.90.77.125 (internet) to SSH (port 22) (Inbound rule 1)
  rules {
    name        = "in_ssh"
    action      = "allow"
    source      = "20.9.77.125"
    destination = "0.0.0.0/0"
    direction   = "inbound"
    tcp {
      port_min = 22
      port_max = 22
    }
  }
}

**Comment by hkantare** [comment]
We are looking into this . Available as part of next release

**Comment by hkantare** [comment]
Available in
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.1
