### ISSUE TITLE
ibm_is_vpc ignores attribute “default_network_acl”

### ISSUE THREAD

**Issue by alainmitry** [IBM-Cloud/terraform-provider-ibm#1081]
Hi there,

### Terraform Version
Using terraform version v0.11.14 with provider.ibm v1.1.0 and there are some problems working with VPC gen 1.

### Affected Resource(s)
 The resource “ibm_is_vpc” ignores attribute “default_network_acl”.

### Actual Behaviour
When this resource is created it waits for the resource specified in the attribute “default_network_acl”, then ignores it and creates another network_acl.
If one tries to do another “terraform apply” it tries to change to the correct value, it reports success, but does not change at all (and we stuck with an “extra” network_acl).
Forcing terraform to create this resource only after the network acl creation does not change the results.

### Steps to Reproduce
resource "ibm_is_vpc" "test-vpc" {
  name                      = "test-vpc"
  resource_group            = "resource_group_id"
  # ignores this part
  default_network_acl       = "${ibm_is_network_acl.test-acl.id}"
  depends_on                = ["ibm_is_network_acl.test-acl"]
}

**Comment by hkantare** [comment]
We don't have this default_network_acl now..Its been removed in VPC for gen1 and gen2.
https://cloud.ibm.com/apidocs/vpc-on-classic#create-a-vpc
https://cloud.ibm.com/apidocs/vpc#create-a-vpc
In Terraform we will deprecate the field

**Comment by hkantare** [comment]
Available in
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.1

**Comment by tkorrapati1** [comment]
@hkantare But why is this being deprecated?

So now is there any way to deterministically create VPC with default security groups and ACL and attaching them to VPC at the same time while creating VPC ?

**Comment by tkorrapati1** [comment]
@stevestrutt Thanks for clarification.
