### ISSUE TITLE
Cluster create of OpenShift 4.3 beta fails with ALB error

### ISSUE THREAD

**Issue by seansund** [IBM-Cloud/terraform-provider-ibm#1083]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.20

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_cluster

### Terraform Configuration Files

https://www.dropbox.com/s/jug61hdf7du160r/iteration-zero-openshift-4.3.tar.gz?dl=0

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/seansund/2233fe2b74deafb40666d65a59ee4d98

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

N/A

### Expected Behavior
What should have happened?

The cluster should be created and the script should complete successfully

### Actual Behavior
What actually happened?

The cluster is created but the an error occurs in the process of applying the `ibm_container_cluster` resource so that subsequent steps cannot be run -
```
Error: Error retrieving alb's of the cluster XXX: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"5618b1af1614ec7e-DFW","code":"E3918","description":"This operation is not supported for your cluster's version.","type":"General"}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

This script has been run successfully many times against this account. I have been given access to the OpenShift 4.3 beta and this is the first time we are using this script with the `4.3.0_openshift` version.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here?

N/A

**Comment by hkantare** [comment]
Yes after internal discussion with team ALB's are not present for openshift 4.3
We will fix the error

**Comment by hkantare** [comment]
Available in
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.1

**Comment by seansund** [comment]
> Available in
> https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.1

We just re-ran our scripts with v1.2.1 and were able to create the cluster without issue. Thank you for the quick turnaround.
