### ISSUE TITLE
Add Tags argument for ibm_is_ssh_key

### ISSUE THREAD

**Issue by IAmFrench** [IBM-Cloud/terraform-provider-ibm#1091]
### Terraform Version
```
λ terraform -v
Terraform v0.12.20
+ provider.ibm v1.2.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_ssh_key

### Terraform Configuration Files
```hcl
resource "ibm_is_ssh_key" "isExampleKey" {
  name       = "test_key"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKVmnMOlHKcZK8tpt3MP1lqOLAcqcJzhsvJcjscgVERRN7/9484SOBJ3HSKxxNG5JN8owAjy5f9yYwcUg+JaUVuytn5Pv3aeYROHGGg+5G346xaq3DAwX6Y5ykr2fvjObgncQBnuU5KHWCECO/4h8uWuwh/kfniXPVjFToc+gnkqA+3RKpAecZhFXwfalQ9mMuYGFxn+fwn8cYEApsJbsEmb0iJwPiZ5hjFC8wREuiTlhPHDgkBLOiycd20op2nXzDbHfCHInquEe/gYxEitALONxm0swBOwJZwlTDOB7C6y2dzlrtxr1L59m7pCkWI4EtTRLvleehBoj3u7jB4usR"
  tags       = ["env:dev"]
}
```

### Debug Output
```
λ terraform plan

Error: Unsupported argument

  on main.tf line 43, in resource "ibm_is_ssh_key" "isExampleKey":
  43:   tags = ["env:test"]

An argument named "tags" is not expected here.
```

### Expected Behavior
Add tag argument for this resource as it it already supported on the GUI (https://cloud.ibm.com/vpc-ext/compute/sshKeys)

### Actual Behavior
Tags argument  not supported

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
https://cloud.ibm.com/vpc-ext/compute/sshKeys

![image](https://user-images.githubusercontent.com/10818450/74271233-d1060380-4d0c-11ea-84e8-c0a0b4882b77.png)

**Comment by hkantare** [comment]
Fix a available in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.2
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.2
