### ISSUE TITLE
ERROR: rpc error: code = Unavailable desc = transport is closing. When importing resources

### ISSUE THREAD

**Issue by ojayx** [IBM-Cloud/terraform-provider-ibm#1092]
Hi,

I am trying to import some infrastructure from my IBM Cloud into terraform.

### Terraform Version
Terraform 0.12.20
Provider.ibm v1.2.0

### Terraform Configuration Files
```hcl
# import_resources.tf
resource "ibm_compute_vm_instance" "demo-11" {

}
```
Ran "terraform import ibm_compute_vm_instance.demo-11 12345 and it finds the resource but then produces this error and then terraform crashes.

[error.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/4188604/error.txt)

### Expected Behavior

Terraform should import resource.

### Actual Behavior

Terraform crashes.

**Comment by hkantare** [comment]
Available in 
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.1
