### ISSUE TITLE
Using IBM provider in env disconnected from internet

### ISSUE THREAD

**Issue by jlerm** [IBM-Cloud/terraform-provider-ibm#1093]
The IBM terraform provider seems to always try to reach out to api.softlayer.com, which is mapped to a public IP.

I would like to be able to use the IBM terraform provider from within a private environment on the IBM Cloud. In other words, to use it from a VSI that only has a private network interface (IP 10.*.*.*) and has no routing to the internet.

Is there a property available that would allow the IBM provider to communicate with a private endpoint within the IBM Cloud?

(I'm still using release 0.11.14 of the IBM provider, due to compatibility w/ the IBM Cloud Automation Manager that I'm still using.)

Thanks.

**Comment by hkantare** [comment]
We support iaas_classic_endpoint_url in provider..May be this attribute can be use to set to private endpoint of classic infrastructure API.
provider "ibm" {
iaas_classic_endpoint_url = "Point to private endpoint be default it points to https://api.softlayer.com/rest/v3" 
}

**Comment by umarali-nagoor** [comment]
Closing the issue as there is no response from the issue reporter. Please re-open the same if issue is re-producible.
