### ISSUE TITLE
ibm_is_network_acl wrong rules order creation and terraform crash

### ISSUE THREAD

**Issue by santosrui** [IBM-Cloud/terraform-provider-ibm#1117]
Hi there,

### Terraform Version
Using terraform version v0.12.21 with provider.ibm v1.2.1 and there are some problems working with ACL in VPC gen 1.

### Affected Resource(s)
- ibm_is_network_acl

### Problem(s):
- Problem 1: does not have a way of specify the order of the rules.
- Problem 2: try to modify, add or remove an rule and terraform plugin crash.

### Actual Behaviour
Problem 1: When creating an ACL the order is not repected (in the example to reproduce it will create the deny rules with priority 1)
Problem 2: Change any value, remove or add an rule on a existing ACL and terraform crash.

### Steps to Reproduce
Problem 1: just create the following ACL
Problem 2: modify, add or remove an rule

```
resource "ibm_is_network_acl" "test-acl" {
  name = "test-acl"

  rules {
    name        = "out_ssh_reply"
    action      = "allow"
    source      = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    direction   = "outbound"
    tcp {
      source_port_min = 22
      source_port_max = 22
    }
  }
  rules {
    name        = "out_dns_requests"
    action      = "allow"
    source      = "0.0.0.0/0"
    destination = "161.26.0.10/31"
    direction   = "outbound"
    udp {
      port_min = 53
      port_max = 53
    }
  }
  rules {
    name        = "out_deny_all"
    action      = "deny"
    source      = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    direction   = "outbound"
  }
  rules {
    name        = "in_ssh"
    action      = "allow"
    source      = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    direction   = "inbound"
    tcp {
      port_min = 22
      port_max = 22
    }
  }
  rules {
    name        = "in_dns_requests_reply"
    action      = "allow"
    source      = "161.26.0.10/31"
    destination = "0.0.0.0/0"
    direction   = "inbound"
    udp {
      port_min = 53
      port_max = 53
    }
  }
  rules {
    name        = "in_deny_all"
    action      = "deny"
    source      = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    direction   = "inbound"
  }
}
```

### Panic Output
[crash.log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/4231440/crash.log)
.

**Comment by hkantare** [comment]
We are looking into the issues...Will update the fix

**Comment by hkantare** [comment]
Fix a available in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.2
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.2

**Comment by john32443** [comment]
Hey! So it looks like Terraform doesn't crash anymore but the order is still not respected.

**Comment by hkantare** [comment]
Can you please try with latest releases 
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.4
or
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.5
