### ISSUE TITLE
IKS Cluster for VPC ends up before ingress and VPC ALB is provisionned

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1143]
Hi there,

### Terraform Version
Terraform v0.12.21
IBMCloud Terraform Provider v1.2.2

### Affected Resource(s)

- ibm_container_vpc_cluster

### Terraform Configuration Files
From example

### Expected Behavior
The IKS cluster resource ends up when alb and ingress are both provisionned

### Actual Behavior
The IKS cluster resource ends up before alb and ingress provisionned.

**Comment by hkantare** [comment]
Fixed as part of
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.4
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.4
