### ISSUE TITLE
Documentation for iam_user_invite for classic_infra_roles is incorrect

### ISSUE THREAD

**Issue by msilverm-web** [IBM-Cloud/terraform-provider-ibm#1144]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.12.21
+ provider.ibm v1.2.2

### Affected Resource(s)
Please list the resources as a list, for example:
ibm_iam_user_invite

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "ibm_iam_user_invite" "invite_user_prov" {
    users = var.prov_accounts
    classic_infra_roles {
      permission_set = "superuser"
    }
    access_groups = [ibm_iam_access_group.prov_grp.id]
}

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

n.a.

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
DOCUMENTATION ISSUE

Documentation says

https://cloud.ibm.com/docs/terraform?topic=terraform-iam-resources

resource "ibm_iam_user_invite" "invite_user" {
    users = ["test@in.ibm.com"]
    classic_infra_roles **=** {
      permission_set = "superuser"
    }
}

But the "=" sign is not correct, the documentation should says

resource "ibm_iam_user_invite" "invite_user" {
    users = ["test@in.ibm.com"]
    classic_infra_roles {
      permission_set = "superuser"
    }
}

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

No

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

No

**Comment by hkantare** [comment]
Fixed in latest docs
