### ISSUE TITLE
K8s VPC Cluster fails when specifying kubernetes version

### ISSUE THREAD

**Issue by Mallear** [IBM-Cloud/terraform-provider-ibm#1157]
### Terraform Version
```$ terraform -v
Terraform v0.12.21
+ provider.ibm v1.2.3```


### Affected Resource(s)
- ibm_container_vpc_cluster

### Terraform Configuration Files
```hcl

resource "ibm_container_vpc_cluster" "k8s_cluster" {
  resource_group_id = data.ibm_resource_group.resource_group.id
  name              = "k8s-${var.environment}-${var.project_name}"
  vpc_id            = var.vpc
  flavor            = "c2.2x4"

  worker_count = var.worker_count
  kube_version = var.kube_version

  dynamic "zones" {
    for_each = var.subnets
    content {
      name      = zones.key
      subnet_id = zones.value
    }
  }
}
```

### Debug Output
Terraform logs with TF_LOG=TRACE:
https://gist.github.com/Mallear/ffd1ac44874d97733da8e9d080a49548

### Expected Behavior
Kubernetes cluster well deployed

### Actual Behavior
Terraform fails with error:
```Request failed with status code: 400, ServerErrorResponse: {"incidentID":"56f3433db078ee4c-CDG","code":"Ef9cc","description":"The cluster could not be updated. The master must be in the deployed state to perform and update.","type":"BadRequest"```

At this time of the deployment, the master is in state `VPN server configuration update in progress.` and at least 2 of the 3 nodes of the default worker pool are healthy.

### Steps to Reproduce

1. `terraform apply -auto-approve`

Notes:
I tried to deploy version 1.15.10, 1.16.7 and 1.17.3 all failed. Only works when not specifying the version.

Am I doing something wrong ?

**Comment by jgarcows** [comment]
Try specifying only the first two parts of the version, i.e:  1.15, 1.16, 1.17.  This is a limitation in the IKS API.  You can only specify Major dot Minor.

**Comment by Mallear** [comment]
Hi @jgarcows , I've tried deploying my cluster with version="1.17", my cluster is created with version 1.17.3 but terraform fails with the same error:

```Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"57234fa01437ee44-CDG","code":"Ef9cc","description":"The cluster could not be updated. The master must be in the deployed state to perform and update.","type":"BadRequest"}
  on ../../../modules/k8s/main.tf line 1, in resource "ibm_container_vpc_cluster" "k8s_cluster":
   1: resource "ibm_container_vpc_cluster" "k8s_cluster" {```

I will test with PR  #1172 new code.

**Comment by hkantare** [comment]
Please test with new release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.4
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.4

**Comment by Mallear** [comment]
It seems to work with provider 1.2.4 and kube_version using major.minor format.
Thank you guys 👍
