### ISSUE TITLE
feature request: support for netscaler vpx versions 11.0 and 11.1

### ISSUE THREAD

**Issue by tomwganem** [IBM-Cloud/terraform-provider-ibm#116]
Currently,  only 10.0 and 10.5 are supported

**Comment by sakshiag** [comment]
@tomwganem : I guess our current configuration supports 11.0 and 11.1 vpx versions. Can you please try and confirm it ..? **(you can give the version as 11 and 11.1 in your tf file**.)

The only issue is when we give version 11 it returns 11.0 that we will fix and will update the doc also with the same info.

Will wait for your confirmation.

**Comment by sakshiag** [comment]
Fix has been pushed as a part of the following PR
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/161

**Comment by tomwganem** [comment]
Sorry, yes. It seems to work fine.
