### ISSUE TITLE
Terraform plan fails for resource access policy if destroyed manually

### ISSUE THREAD

**Issue by Praveengostu** [IBM-Cloud/terraform-provider-ibm#1162]
terraform plan is not able to proceed as the resource was manually destroyed. And a subsequent plan gives the below error
2020/03/06 23:02:41 Terraform plan | Error: Error refreshing state: 1 error occurred:
 2020/03/06 23:02:41 Terraform plan | 	* ibm_iam_access_group_policy.developer_rg_svc_policy: 1 error occurred:
 2020/03/06 23:02:41 Terraform plan | 	* ibm_iam_access_group_policy.developer_rg_svc_policy: ibm_iam_access_group_policy.developer_rg_svc_policy: Error retrieving access group policy: Request failed with status code: 404, ServerErrorResponse: {"trace":"5fd76d48f32d4230aa925c769106151b","errors":[{"code":"policy_not_found","message":"Policy with Id dc86193e-5347-4665-9472-95531dbbf2fa not found."}],"status_code":404}

**Comment by hkantare** [comment]
Fix available in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.4
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.4
