### ISSUE TITLE
Create Terraform Data blocks for Retrieving ICD Whitelists & COS Bucket IP Whitelists

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#1170]
Already we support this databse gives back list of whitlists

**Comment by hkantare** [comment]
https://internal-ibmcloud.ideas.aha.io/ideas/IDEAINT-I-2984

**Comment by umarali-nagoor** [comment]
Retrieving ICD Whitelists is already supported. And COS bucket IP whitelist functionality is supported as part of following issue

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1168

Hence closing the issue.
