### ISSUE TITLE
VPC Cluster version update using rolling update

### ISSUE THREAD

**Issue by Mallear** [IBM-Cloud/terraform-provider-ibm#1175]
Hello there,

Is there a way to upgrade a VPC Cluster version without down time ?
Today if I upgrade my cluster by changing `kube_version` parameter, master will be upgrade and then ALL worker will upgrade and be shutdown at the same time, resulting in down time.

I've tryied playing with worker nodes and lifecycle, but I cannot avoid downtime. 

I've found this [exemple for container_cluster resource](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-cluster-update/main.tf) but it's not reproductible with vpc_cluster resources. It could be great to be able to manage worker version node by node or changing default update process, but that's behind the scope or this provider I guess.

**Comment by hkantare** [comment]
Its behinf the scope of the provider may be need to raise issue on respective API's
