### ISSUE TITLE
Feature Request: Support IBM Cloud Resource Groups

### ISSUE THREAD

**Issue by greyhoundforty** [IBM-Cloud/terraform-provider-ibm#118]
I would like to see Resource groups be part of the IBM Cloud Platform provider. I am currently seeing an issue trying to spin up a ICOS instance via Terraform and I believe the issue is that Terraform provider plugin is getting set to the `default` resource group and not the one my user had access to/control of. If I use the `bx` CLI and target the appropriate Resource Group the order can go through but I have no way in the Provider Plugin to target the right resource group:

```
* ibm_service_instance.cos: Error creating service: Request failed with status code: 502, ServerErrorResponse: {
  "description": "Service broker error: You do not have the required permission to create an instance. You must be assigned the IAM Editor role or higher. Contact your account owner to update your access.",
```

[Resource Groups](https://console.bluemix.net/docs/account/resourcegroups.html#rgs)

**Comment by hkantare** [comment]
@greyhoundforty  Can you let us know what commands you used to create ICOS using cli 
```
bx cf create-service
or 
bx resource service-instance-create
```

**Comment by greyhoundforty** [comment]
I used

`bx resource service-instance-create tfcostesting cloud-object-storage standard global --parameters @hmac.json`

**Comment by hkantare** [comment]
@greyhoundforty - Thanks for information.

**Comment by greyhoundforty** [comment]
This was due to permissions issues on the account I was using. I switched to my own account that I am the sole owner of and I can deploy via terraform
