### ISSUE TITLE
ibm_cis_dns_record not updated

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1180]
### Terraform Version
```bash
Terraform v0.12.23
+ provider.ibm v1.2.4
```

### Affected Resource(s)

- ibm_cis_dns_record

### Panic Output

N/A

### Expected Behavior
When updating the ibm_cis_dns_record, especially the name property, the change is applied to the resource.

### Actual Behavior
No update performed. State become inconsistent

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create ibm_cis_dns_record
2. Update the name property
3. Apply
4. See no changes in CIS

**Comment by rbustami** [comment]
Hi @hkantare Can we make sure this is a priority in the team's upcoming sprint.

**Comment by kavya498** [comment]
Available in
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.4.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.26.0

**Comment by ifs-pauljegouic** [comment]
Fixed
