### ISSUE TITLE
Cannot assign static internal ip address

### ISSUE THREAD

**Issue by bert2002** [IBM-Cloud/terraform-provider-ibm#1182]
### Terraform Version
```terraform -v
Terraform v0.11.14
+ provider.ibm (unversioned)
```

### Affected Resource(s)
- ibm_is_instance

### Terraform Configuration Files
```hcl
resource ibm_is_instance "ibm-server-1" {
  name    = "ibm-server-1"
  vpc     = "${ibm_is_vpc.vpc.id}"
  zone    = "${var.region}-1"
  keys    = ["${var.sshkeyid}"]
  image   = "${data.ibm_is_image.debian.id}"
  profile = "bc1-2x8"

  primary_network_interface = {
    name            = "eth0"
    subnet          = "${ibm_is_subnet.subnet1.id}"
    security_groups = ["${ibm_is_security_group.sg1.id}"]
  }
}
```

### Problem

I am trying to create a compute instance with a static internal ip address that I can assign myself. So far I have not find any way how to do it. Is it even possible?
I tried parameters like `primary_ipv4_addres` for `primary_network_interface`, but no luck and the documentation is not pointing me in the right direction. 
Assigning a floating ip (public) is no problem, but internal? 

Please let me know if this is possible and may be put me in the right direction.

Thanks,
bert

**Comment by hkantare** [comment]
Here primary_ipv4_addres is the computed  variable which means user can't assign any value. From UI also I don't see a way to attach IP
<img width="711" alt="Screen Shot 2020-03-12 at 9 51 45 AM" src="https://user-images.githubusercontent.com/24930306/76487088-3e5d9f00-6447-11ea-9f64-12b5c8fd4891.png">

But let me confirm from respective team and update

**Comment by bert2002** [comment]
Yeah I dont think its possible in the UI, hopping it would be possible using the API.

**Comment by hkantare** [comment]
From VPC team
```
we can’t assign static IPs currently. We’re waiting for the reserved IPs feature to come in and that should solve the problem.
```

**Comment by irmiller22** [comment]
Odd, because their Terraform provider documentation shows an example saying that this should be possible: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_floating_ip
