### ISSUE TITLE
Feature request: support the smart tier storage class for ibm_cos_bucket

### ISSUE THREAD

**Issue by maristgeek** [IBM-Cloud/terraform-provider-ibm#1184]
The _Flex_ storage class for Cloud Object Store buckets is being replaced by the _Smart Tier_ class. For now (12 March) the latest provider can still create a _flex_ bucket but it has been removed from the UI for new buckets.

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_cos_bucket

### References
- https://cloud.ibm.com/docs/services/cloud-object-storage/basics?topic=cloud-object-storage-classes#use-storage-classes

**Comment by umarali-nagoor** [comment]
Supported new storage class "smart" for COS bucket and released the same both in master and terraform_v0.11.x branches

Master branch :  https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.6

terraform_0.11.x :  https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.6

**Comment by maristgeek** [comment]
![Selection_005](https://user-images.githubusercontent.com/418321/77796170-2e4bdf00-7045-11ea-8a89-9e6b830f7bd7.png)

Confirmed it works in 1.2.6.
