### ISSUE TITLE
Terraform binary - unknown publisher

### ISSUE THREAD

**Issue by argeiger** [IBM-Cloud/terraform-provider-ibm#1185]
When executing the binary for both mac and windows, the user is prompted with a message that it can not be opened because the developer cannot be verified (unknown publisher).  Due to this, this provider plugin can not be utilized due to security.  Can we please have these binaries signed so the user is not prompted with this?

**Comment by hkantare** [comment]
We are closing this issue since now we are doing both code sign on windows and mac notaraization on binaries
