### ISSUE TITLE
support for pod-subnet and service-subnet

### ISSUE THREAD

**Issue by krakel** [IBM-Cloud/terraform-provider-ibm#1196]
At the command line ibmcloud support the --pod-subnet and --service-subnet option.

https://www.ibm.com/cloud/blog/using-custom-subnet-ranges-with-ibm-cloud-kubernetes-service
https://cloud.ibm.com/docs/containers?topic=containers-cli-plugin-kubernetes-service-cli#pod-subnet

Does this option also exist in the cloud provider?

**Comment by gregswift** [comment]
Do we have any idea what this would take to implement? Its a requirement for a cluster we were getting ready to deploy with terraform.

**Comment by bradbehle** [comment]
@gregswift I talked to @hkantare via slack (hkantare@in.ibm.com) and he said they would work on this in their next sprint

**Comment by hkantare** [comment]
Released in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.20.0
Cloud docs will be updated soon
Registry docs:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs

**Comment by kavya498** [comment]
Closing this issue.
