### ISSUE TITLE
Provider "ibm" not available for installation on Windows 10

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#120]
Hi there,

### Terraform Version
Terraform v0.11.2

### Affected Resource(s)

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior

Terrafom should have initialized by detecting `IBM` as a provider

### Actual Behavior
I am seeing an error as mentioned below

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

Error: 

> Provider "ibm" not available for installation.
> 
> A provider named "ibm" could not be found in the official repository.
> 
> This may result from mistyping the provider name, or the given provider may
> be a third-party provider that cannot be installed automatically.
> 
> In the latter case, the plugin must be installed manually by locating and
> downloading a suitable distribution package and placing the plugin's executable
> file in the following directory:
>     terraform.d/plugins/windows_386
> 
> Terraform detects necessary plugins by inspecting the configuration and state.
> To view the provider versions requested by each module, run
> "terraform providers".

**Comment by VidyasagarMSC** [comment]
I think the issue is with me running this on Windows 32-bit.

**Comment by ashishth09** [comment]
Hi @VidyasagarMSC ,

IBM provider is not yet part of the Hashicorp delivery vehicle for example by being in its repo.
So you won't get it from the usual `terraform init`.

Please follow `Using Terraform with the IBM Cloud Provider` section at https://ibm-cloud.github.io/tf-ibm-docs

Thanks

**Comment by VidyasagarMSC** [comment]
@ashishth09 Will this work with version 0.7.0? We are using the same for our solution tutorial here - https://console.bluemix.net/docs/tutorials/infrastructure-as-code-terraform.html#automate-deployment-of-environments-using-terraform

**Comment by ashishth09** [comment]
Yes it should. Let me know if you face any issues. We try to maintain the backward compatibility  across the releases.

**Comment by VidyasagarMSC** [comment]
@ashishth09 As discussed over the call, the issue is we don't have executable for Windows 32-bit. Error seen running the binary on Windows 32-bit is

> This version of C:\Users\VMac\AppData\terraform.d\plugins\terraform-provider-ibm.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by vkalangu** [comment]
@VidyasagarMSC You could build yourself. Pull in the code and give it a try.
We will plan for an official binary in future

**Comment by VidyasagarMSC** [comment]
@vkalangu  I worked with @ashishth09 and received a 32-bit windows executable which along with few additionals steps worked as expected. 

**Details updated in the below links**
- [Solution Tutorial](https://console.bluemix.net/docs/tutorials/infrastructure-as-code-terraform.html#automate-deployment-of-environments-using-terraform)
- [Blog Post](https://vmacwrites.wordpress.com/2018/02/01/infrastructure-as-code-with-terraform-on-windows/)

**Comment by vkalangu** [comment]
Sure....Strictly that is an unsupported binary for your experiments and not to be distributed, used in production envs. I am sure @ashishth09 woudl have given a heads up...but making sure.
