### ISSUE TITLE
Add support for lockdowns in CIS resource

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1201]
Hi there,

We would like to be able to manage CIS lockdowns rules through Terraform instead of using null_resource and bash scripts.

Thanks in advance

**Comment by hkantare** [comment]
Can you provide me some links to understand this feature and can you also provider us the null resource/bash script

**Comment by ifs-pauljegouic** [comment]
Yep for sure.

Here is the IBM documentation: https://cloud.ibm.com/docs/cis?topic=cis-how-cis-keeps-your-work-secure

Here is a snippet we have made:

```hcl
resource "local_file" "lockdown" {
  content  = jsonencode(local.lockdown_payload)
  filename = "${path.module}/lockdown.json"
}
resource "null_resource" "ip_filtering_lockdown" {
  depends_on = [local_file.lockdown]
  triggers = {
    build_number = "${timestamp()}"
  }
  provisioner "local-exec" {
    command = <<EOT
 ibmcloud login -r ${var.region} -g ${var.resource_group_id}
 existing_rules=$(ibmcloud cis firewalls -t lockdowns -i ${var.cis_id}  -d ${element(split(":", var.domain_id), 0)} --output json)
 for row in $(echo "$existing_rules" | jq -r '.[] | @base64'); do
 _jq() {
 echo $row | base64 -d | jq -r $1
 }
 if [ $(_jq '.urls[0]') == ${local.full_domain} ];then
 ibmcloud cis firewall-delete $(_jq '.id') -t lockdowns -d ${element(split(":", var.domain_id), 0)} -i ${var.cis_id}
 fi
 done
 ibmcloud cis firewall-create -t lockdowns -d ${element(split(":", var.domain_id), 0)} -i ${var.cis_id} -j "${path.module}/lockdown.json"
 EOT
  }
}
```

**Comment by ifs-pauljegouic** [comment]
We would like to achieve the CRUD actions on cis_lockdown !

**Comment by ifs-pauljegouic** [comment]
@hkantare seeing a lot of commit :) :) 

When can we expect this feature to be released ?

**Comment by ifs-pauljegouic** [comment]
![image](https://user-images.githubusercontent.com/50360031/79430374-25f21e80-7fc9-11ea-919b-7eec3c870085.png)

**Comment by ifs-pauljegouic** [comment]
@hkantare we definetly need the documentation !

**Comment by hkantare** [comment]
Docs will be update in couple of days....I'm rasining request against doc team

**Comment by ifs-saraqasmi** [comment]
@hkantare while waiting for the doc, can you give an example of using ibm_cis_firewall with lockdown param please

**Comment by hkantare** [comment]
doc file: https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/cis_firewall.html.markdown

**Comment by kavya498** [comment]
Available in
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.4.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.26.0

**Comment by ifs-pauljegouic** [comment]
@hkantare  & @kavya498 thanks for the update.

There is something that lead us to some 404 errors which is the inconsistency of usage of the GUID or the ID, in document `id`.

In that case:

- for `ibm_cis_dns_record`: The ID of the domain for which you want to add a DNS record.
- for `ibm_cis_firewall`: The ID of the domain where you want to apply the firewall rules.

But in fact, the syntax of the expected ID is not the same. 
 
- `ibm_cis_dns_record.domain_id` expect this form of ID: `19364270fc6XXXXXX7f940fd292e:crn:v1:bluemix:public:internet-svcs:global:a/9e87f2cde0feXXXXXX056bdad79d285d:ad5b006d-0c7a-40ff-94e6-0f6a9a77ef7c::` (barely the domain_id:cis_id)
- `ibm_cis_firewall`: expect this for of ID of this type : `19364270fc6XXXXXX7f940fd292e`

I would suggest, since IBM Cloud has multiple IDs syntax for resource, to provide a more accurated information/examples to the end-user.

I will close this issue after you see my message and suggest an enhancement.

**Comment by hkantare** [comment]
We will make changes to be inline with other CIS resources..as enhancement

**Comment by ifs-pauljegouic** [comment]
Is it possible to have non-regression that you both support those two types of syntax ? @hkantare

**Comment by ifs-pauljegouic** [comment]
I will create another case for this domain_id inconsistency between TF resources/datasources and the CLI.

**Comment by hkantare** [comment]
We will have inconsistency issues if we support both types...because we need to set back all the schema attributes to store in a statefile...If we support both types we will not be aware if user has passed which type ...
