### ISSUE TITLE
Please add @uk.ibm.com email addresses to the slack channel signup page

### ISSUE THREAD

**Issue by snowch** [IBM-Cloud/terraform-provider-ibm#121]
Hi team, I’m not sure how else I can communicate with you so my apologies for raising an issue for this question.

I’d like to signup to the slack channel, but the signup page doesn’t support @uk.ibm.com email addresses.

- https://ibm-cloud-schematics.slack.com/signup

**Comment by vkalangu** [comment]
I shall as cloud schematics team to add you.
Mean while I have added you to the internal slack channel, where you can contact us.

**Comment by snowch** [comment]
Thank you!
