### ISSUE TITLE
How to create multizone openshift 4 cluster

### ISSUE THREAD

**Issue by csantanapr** [IBM-Cloud/terraform-provider-ibm#1215]
I was not able to figure out from the documentation how to create a multizone cluster using the terraform module.

I'm able to login into the IBM Cloud UI Console and create a cluster with the default specifications
- type: openshift 4.3
- Location: multizone
  - dal10 vlan id public, vlan id private
  - dal12 vlan id public, vlan id private
  - dal13 vlan id public, vlan id private
- cluster name: carlos
- resource group: carlos_group
- tags: carlos
- Default worker pool machines
  - VM b3c.8x32
- Worker Nodes per zone: 3
- Total workers: 9

How can I achieve the same with the terraform module?
Thank you in advance, this is an effort to be able to provide this support in the IBM Garage Cloud Native Toolkit https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/

cc @seansund

**Comment by hkantare** [comment]
From terraform When we create a multi-zone cluster we have a cluster with default worker pool.
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/900 In this issue you can refer to the example of creating a cluster with multiple worker pools and deleting the default worker pool

**Comment by csantanapr** [comment]
Can we take the example of #900 and make it in the docs?
 I feel is a common use case and people would looking for an example in the docs very often.

**Comment by csantanapr** [comment]
Cross linking with end user issue https://github.com/ibm-garage-cloud/planning/issues/184

**Comment by svennam92** [comment]
@csantanapr thanks for raising this issue - i agree that we should document this. our docs engineer is working on it actively.

**Comment by csantanapr** [comment]
Thanks !!

**Comment by seansund** [comment]
Any progress on this. The documentation for a classic multi-zone cluster is missing/hard to piece together

**Comment by hkantare** [comment]
@seansund Still the documentation changes are in progress ...They are working to provide the links to the different example in cloud docs...
We plan to add the multizone cluster for IKS to example under https://github.com/IBM-Cloud/terraform-provider-ibm

**Comment by hkantare** [comment]
We created a documentaiton for
https://cloud.ibm.com/docs/terraform?topic=terraform-tutorial-tf-clusters

**Comment by yassermoreno2013** [comment]
Hello! I am follow the steps in https://cloud.ibm.com/docs/terraform?topic=terraform-tutorial-tf-clusters, but I am receiving the follow error :

Error: Error waiting for ALBs in zone (dal12) of cluster (c2477dad0n6gr5gdbpl0) to 
 become ready: Error retrieving ALBs for cluster: Request failed with status code: 400, 
 ServerErrorResponse: {"incidentID":"646b3c68a1af0eda-DFW","code":"E3918","description":
 "This operation is not supported for your cluster's version.","type":"General"}

 on main.tf line 19, in resource "ibm_container_worker_pool_zone_attachment" "dal12":
Terraform apply |   19: resource "ibm_container_worker_pool_zone_attachment" "dal12" 

I am using OpenShift 4.5.37_1536,.

Thank you

**Comment by yassermoreno2013** [comment]
> Creamos una documentación para
> https://cloud.ibm.com/docs/terraform?topic=terraform-tutorial-tf-clusters

¡Hola! Sigo los pasos en https://cloud.ibm.com/docs/terraform?topic=terraform-tutorial-tf-clusters , pero recibo el siguiente error:

Error: Error al esperar que los ALB en la zona (dal12) del clúster (c2477dad0n6gr5gdbpl0)
estén listos: Error al recuperar los ALB para el clúster: La solicitud falló con el código de estado: 400,
ServerErrorResponse: {"ID de incidente": "646b3c68a1af0eda-DFW", "código" : "E3918", "description":
"Esta operación no es compatible con la versión de su clúster.", "Type": "General"}

en main.tf línea 19, en el recurso "ibm_container_worker_pool_zone_attachment" "dal12":
Terraform apply | 19: recurso "ibm_container_worker_pool_zone_attachment" "dal12"

Estoy usando OpenShift 4.5.37_1536.

Gracias
