### ISSUE TITLE
How to get involved with this project?

### ISSUE THREAD

**Issue by snowch** [IBM-Cloud/terraform-provider-ibm#122]
There are some new resources that I would like to implement such as MessageHub and IBM Analytics Engine (however, it will take a while because I’ll need to learn golang first).

I would like to get involved with this project.  Will you consider pull-requests? What is your contribution process?

**Comment by ashishth09** [comment]
>Will you consider pull-requests?
Absolutely 👍 

>What is your contribution process?
We will add the formal doc soon. To get you started though, you could refer to the relevant sections of https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md. We will align closely with the community. In particular,
`Pull Request Lifecycle`. Feel free to ask any questions you might have before we add the official contributing guide.

**Comment by hkantare** [comment]
Closing the issue.
