### ISSUE TITLE
Add support to create VPC Gen2 Kubernetes cluster

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#1222]
### Terraform Version
Terraform v0.12.23

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_vpc_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.12.23"
}

provider "ibm" {
  version          = ">= 1.2.4"
  ibmcloud_api_key = var.ibmcloud_api_key
  region           = var.region
  ibmcloud_timeout = 300
  generation       = var.generation
}

data "ibm_resource_group" "group" {
  name = var.resource_group
}

resource "ibm_container_vpc_cluster" "cluster" {
  name = "${var.resources_prefix}-cluster"

  vpc_id            = var.vpc_id
  flavor            = var.flavor
  worker_count      = var.worker_count
  resource_group_id = data.ibm_resource_group.group.id
  kube_version      = var.kube_version

  zones {
    subnet_id = var.vpc_subnets["zone-1"]
    name      = var.vpc_zones["${var.region}-availability-zone-1"]
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
1. Set the generation to value `2`
3. Cluster is created in VPC Gen 2 

### Actual Behavior
```
ibm_container_vpc_cluster.cluster: Creating...
Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"579108a500160e8a-PHL","code":"P4102","description":"The subnet '0717-66ee2727-c0e6-490d-b7f1-b4033130183d' cannot be found.","type":"BadRequest","recoveryCLI":"To list available subnets, run 'ibmcloud ks subnets --provider \u003cprovider\u003e --vpc-id \u003cvpc-id\u003e --zone \u003czone-id\u003e'."}
```

Looking at the incident id 579108a500160e8a-PHL … Terraform is specifying the vpc-classic provider when attempting to create the cluster. The request will fail as you are providing vpc-gen2 resources.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. use the above provided template 
2. fill in the values as needed
3. terraform plan and terraform apply

### Important Factoids
N/A

### References
N/A

**Comment by dprosper** [comment]
I took a crack at implementing a solution to confirm it is doable, see here: 
https://github.com/dprosper/terraform-provider-ibm/commit/f87358155a8b5f44fe0aa36cb89431793fb10f19

I did not test all scenarios, i.e. only tested Create, and Delete, I did not test Update.

**Comment by hkantare** [comment]
Supported as part of latest release v1.4.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.4.0
