### ISSUE TITLE
Add a data source for VPC Security Groups and ACLs

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#1223]
We need a data source for VPC Gen 1 and VPC Gen 2 security groups and ACLs.  It is needed in order to retrieve and modify the default security group and default ACL that are created. It might be useful as well to get a full list of all security groups and ACLs

**Comment by condescendent** [comment]
Is it resolved? how could I add new rules to the default security group created with my vpc ?

**Comment by ileneruth** [comment]
You can reference the default_security_group of a newly created VPC using 'default_security_group' as in the example below, where I have added a rule to the default security group.   (Ref: https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#vpc-output)

resource "ibm_is_security_group_rule" "allow_ssh_traffic" {

  group      = ibm_is_vpc.main_vpc.default_security_group
  direction  = "inbound"

  tcp {
    port_min = 22
    port_max = 22
  }
}

That said, I need to be able to **delete** a security group rule from the default security group and I cannot find any way to do that!

**Comment by hkantare** [comment]
We developed support for datasource for security groups..
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-data-sources#sec-group-datasource
