### ISSUE TITLE
ICD databases-for-postgresql - Error getting database config 

### ISSUE THREAD

**Issue by soliverprofesional** [IBM-Cloud/terraform-provider-ibm#1224]
### Terraform Version
Terraform v0.12.24
+ provider.ibm v1.2.5

### Affected Resource(s)
ibm_database (service = "databases-for-postgresql")

### Terraform Configuration Files
Nothing exceptional. Easy direct use case.
```hcl
resource "ibm_database" "dev_icd" {
  name     = var.icd_instance_name
  plan     = "standard"
  location = var.icd_location
  service  = "databases-for-postgresql"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Create a database and give me the status after it.

### Actual Behavior
Creates the database in the cloud. I verify it's correct with either:
- terraform state list | xargs terraform state show
- ibmcloud resource service-instances --long

But at terrform level fails. At apply with the error:

```log
ibm_database.bnpp_dev_icd: Still creating... [10m50s elapsed]
ibm_database.bnpp_dev_icd: Still creating... [11m0s elapsed]

Error: Error getting database config for: crn:v1:bluemix:public:databases-for-postgresql:eu-de:a%2F5e1bccd8a0244861be6321efabfedd21:60a7d480-9677-4db0-b8c0-899dff00c0e5:: with error Request failed with status code: 500, ServerErrorResponse: {"status":500,"error":"Internal Server Error"}


  on main.tf line 1, in resource "ibm_database" "dev_icd":
   1: resource "ibm_database" "dev_icd" {
```
And after that, `terraform plan`, `terraform state` or  `terraform refresh` fails with the same type of error 500.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Simplest use case possible. 
Plugin version v1.2.1 had worst behaviour, failing in an earlier stage.

### References
I haven't found any directly related.

**Comment by soliverprofesional** [comment]
Also confirmed the same error with etcd

**Comment by hkantare** [comment]
Can you let me know in which region the database is created.Did the provider region set to same location in which resource is created.Refer the note section for more information
https://cloud.ibm.com/docs/terraform?topic=terraform-databases-resources

**Comment by soliverprofesional** [comment]
Thanks @hkantare, seems after refactoring the project I missed that one.
