### ISSUE TITLE
Feature Request: Make ibm_resource_key resources linked to ibm_database resources more importable

### ISSUE THREAD

**Issue by maristgeek** [IBM-Cloud/terraform-provider-ibm#1232]
When doing an import of an existing `ibm_resource_key`, we have to add `role` and `resource_instance_id` to be ignored in its lifecycle management.

For `role` it seems like _roleCrn_ the if/else block could be extended to look for _crn_ in these cases. And for `resource_instance_id` you could use the _source_crn_ parameter.

### Terraform Version
0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_resource_key

### Terraform Configuration Files
Example config:
```hcl
resource "ibm_database" "elasticsearch" {
  name              = var.name
  plan              = "standard"
  location          = var.region
  service           = "databases-for-elasticsearch"
  resource_group_id = data.ibm_resource_group.group.id

  members_memory_allocation_mb = var.total_memory_mb
  members_disk_allocation_mb   = var.total_disk_mb
  members_cpu_allocation_count = var.total_dedicated_cores
}

resource "ibm_resource_key" "service_key" {
  name                 = var.service_key_name
  role                 = "Editor"
  resource_instance_id = ibm_database.elasticsearch.id

  lifecycle {
    ignore_changes = [role, resource_instance_id]
  }
}
```

**Comment by a-wagener** [comment]
We have the same problem. In our case it was enough to set `ignore_changes = [resource_instance_id]`. And the state is not just missing `role` and `resource_instance_id`, there is also an additional but empty field `timeouts`.
