### ISSUE TITLE
Deleting default worker pool result in LoadBalancer stuck in Creating mode

### ISSUE THREAD

**Issue by Mallear** [IBM-Cloud/terraform-provider-ibm#1240]
Hi there,
I'm deploying k8s VPC cluster and deleting default worker pool to deploy my own.

### Terraform Version
Terraform v0.12.23
+ provider.ibm v1.2.5

### Affected Resource(s)
- ibm_container_vpc_cluster
- ibm_is_lb

### Terraform Configuration Files
```hcl
resource "ibm_container_vpc_cluster" "k8s_cluster" {
  resource_group_id = data.ibm_resource_group.resource_group.id
  name              = "k8s"
  vpc_id            = var.vpc_id
  flavor            = c2x4

  worker_count = 3
  kube_version = "1.17"
  wait_till = "OneWorkerNodeReady"

  dynamic "zones" {
    for_each = var.subnets
    content {
      name      = zones.key
      subnet_id = zones.value
    }
  }
}

data "ibm_container_vpc_cluster" "k8s_cluster" {
  cluster_name_id   = ibm_container_vpc_cluster.k8s_cluster.id
  resource_group_id = data.ibm_resource_group.resource_group.id
}


resource "null_resource" "delete_default_worker_pool" {
  triggers = {
    clusterid = ibm_container_vpc_cluster.k8s_cluster.id #Force launching when cluster change
  }

  provisioner "local-exec" {
    command = "ibmcloud ks worker-pool rm -f -s --cluster ${ibm_container_vpc_cluster.k8s_cluster.id} --worker-pool ${data.ibm_container_vpc_cluster.k8s_cluster.worker_pools.0.id}"
  }

  depends_on = [
    ibm_container_vpc_cluster.k8s_cluster,
  ]
}

```

### Expected Behavior
Default worker pool deleted and LB in Active state or worker pool deleted and LB deleted.

### Actual Behavior
Default worker pool deleted and LB stuck in Creating  state

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I've made a ticket to IBM Cloud support before thinking maybe it was linked to the provider.

**Comment by hkantare** [comment]
I think it will be issue because wait_till = "OneWorkerNodeReady" based on that condition we are only waiting for only worker node to be ready we are not waiting for ALB to be assigned..ALB's will start assign once we have all worker nodes available. So when you start deleting the cluster may be ALB would have just started initializing....

**Comment by Mallear** [comment]
Thanks for your fast answer @hkantare :) 
That's what I though. If I first delete the LB, do you think it should fix the problem ?

**Comment by hkantare** [comment]
How you will delete LB ? From UI?

**Comment by Mallear** [comment]
Through a null_resource like for worker pool, I guess

**Comment by Mallear** [comment]
Hello, I'm closing this issue as the problem was on IBM side. I've checked with the support to delete these.
