### ISSUE TITLE
Terraform Plan should have failed when `vpc` parameter was missing on the ibm_is_network_acl resource.

### ISSUE THREAD

**Issue by rbustami** [IBM-Cloud/terraform-provider-ibm#1251]
Problem:
Terraform plan should fail on ibm_is_network_acl if vpc gen 2 is selected and the vpc field is missing. 

Documentation issue for ibm_is_network_acl under gen 2 https://ibm-cloud.github.io/tf-ibm-docs/v1.2.4/r/is_network_acl.html.`vpc` is set as an optional field in the docs but is a required field in practice. 

### Terraform Version
v0.11.14

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_network_acl (gen2)

### Terraform Configuration Files
Block 1: Passes Plan but fails Apply:
```
resource ibm_is_network_acl multizone_acl {
  name = "${var.unique_id}-multizone-acl"
  rules = [
    {
      name   = "egress"
      action = "allow"
      source      = "0.0.0.0/0"
      destination = "0.0.0.0/0"
      direction   = "outbound"
    },
    {
      name   = "ingress"
      action = "allow"
      source      = "0.0.0.0/0"
      destination = "0.0.0.0/0"
      direction   = "inbound"
    }
  ]
}
```
Block 2: Passes both Plan & Apply:
```
resource ibm_is_network_acl multizone_acl {
  name = "${var.unique_id}-multizone-acl"
  vpc = "${ibm_is_vpc.vpc.id}" # <------ VPC ADDED
  rules = [
    {
      name   = "egress"
      action = "allow"
      source      = "0.0.0.0/0"
      destination = "0.0.0.0/0"
      direction   = "outbound"
    },
    {
      name   = "ingress"
      action = "allow"
      source      = "0.0.0.0/0"
      destination = "0.0.0.0/0"
      direction   = "inbound"
    }
  ]
}
```

### Expected Behavior
Issue 1 (Terraform plan):
When Block 1 above is used the plan should fail. 

Issue 2: Documentation: 
Original docs:
```
vpc - (Optional, Forces new resource, string) The VPC Id. This is a Required field and to be set only when the generation parameter is 2
```

### Actual Behavior
Issue 1: Terraform plan passes

Issue 2: 
Should be updated to something along the lines of:
```
vpc - (Required for Gen 2, Optional for Gen1) ...
```

### Steps to Reproduce
Issue 1: `terraform plan` on block 1
Issue 2: Go to https://ibm-cloud.github.io/tf-ibm-docs/v1.2.4/r/is_network_acl.html

**Comment by hkantare** [comment]
Now we have docs moved to ibm cloud docs we have seperate example for gen1 and gen2
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen1-resources
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources

**Comment by VaishnaviGopal** [comment]
Avaialble in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.9.0
