### ISSUE TITLE
cloud provider  should not require org guid and space guid to create a cluster

### ISSUE THREAD

**Issue by louiseohalloran** [IBM-Cloud/terraform-provider-ibm#127]
cloud provider  should not require org guid and space guid to create a cluster

Here - https://ibm-cloud.github.io/tf-ibm-docs/v0.7.0/r/container_cluster.html they are listed as required and also I have tried to create cluster without them and it fails

Error: ibm_container_cluster.monitoring_cluster: "org_guid": required field is not set
Error: ibm_container_cluster.monitoring_cluster: "space_guid": required field is not set

Can the requirement of these params be removed since they should not be necessary to create a cluster in armada

Also I am seeing 
Error: data.ibm_account.account: "org_guid": required field is not set

So checking the docs it looks like org guid is used to get the account info. Can this be modified so that the account id can be passed in instead ( as in either account or org id - at the moment only org guid can be specified to get the account ) - Let me know if I should open a separate issue for this. I thought maybe they should be looked at together but best for you to decide.

**Comment by Praveengostu** [comment]
We will look in to this and get back to you.

**Comment by snayakie** [comment]
ICCS (IBM Cloud Container Service) has been made independent of org/space (CF concepts) and can be used with "Account" only if org/space are not provided. I believe it still supports org/space if they are set, but its not mandatory. The terraform provider should be made consistent with ICCS features for authentication.

**Comment by louiseohalloran** [comment]
Hi @Praveengostu @ashishth09 - Can you tell me if the second part of this issue was addressed :

```So checking the docs it looks like org guid is used to get the account info. Can this be modified so that the account id can be passed in instead ( as in either account or org id - at the moment only org guid can be specified to get the account ) - Let me know if I should open a separate issue for this. I thought maybe they should be looked at together but best for you to decide.```

**Comment by ashishth09** [comment]
Hi @louiseohalloran,

org_guid is optional now.. so if you know you account_guid you can directly pass that over..
there is a data source which helps you to know the account_guid if you know your org.
