### ISSUE TITLE
Support for CIS Metrics - Rate Limit config

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1271]
Hi there,

We would like to handle the CIS configuration, especially the Rate Limit configuration with native TF resource, instead of using a null_resource and bash scripts.

Thanks in advance

**Comment by hkantare** [comment]
The support for CIS ratelimit is available in last releases (1.7.1 and 1.7.0)

https://cloud.ibm.com/docs/terraform?topic=terraform-cis-resources#rate-limit

**Comment by hkantare** [comment]
closing the issue
