### ISSUE TITLE
Error: Unsupported argument for resources block in ibm_iam_access_group_policy

### ISSUE THREAD

**Issue by dilbertside** [IBM-Cloud/terraform-provider-ibm#1275]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.24
provider.ibm v1.3.0
on Fedora 

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_iam_access_group_policy

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.12"
}

provider "ibm" {
  version = "~> 1.3.0"
}
#copy verbatim from 
#https://cloud.ibm.com/docs/terraform?topic=terraform-iam-resources#access-group-policy-using-resource-and-resource-type

resource "ibm_iam_access_group" "accgrp" {
  name = "test"
}

data "ibm_resource_group" "group" {
  name = "default"
}

resource "ibm_iam_access_group_policy" "policy" {
  access_group_id = ibm_iam_access_group.accgrp.id
  roles        = ["Administrator"]

  resources = [{
    resource_type = "resource-group"
    resource      = data.ibm_resource_group.group.id
  }
  ]
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
when running terraform validate, we should see:
Success! The configuration is valid.

### Actual Behavior
What actually happened?
Error: Unsupported argument
  on main.tf line 22, in resource "ibm_iam_access_group_policy" "policy":
  22:   resources = [{
An argument named "resources" is not expected here. Did you mean to define a
block of type "resources"?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform validate`

### Important Factoids
no known factoids

### References
no ref known

**Comment by hkantare** [comment]
Its Terraform v0.12 syntax .....The blocks should be specified as
```
resource "ibm_iam_access_group_policy" "policy" {
  access_group_id = ibm_iam_access_group.accgrp.id
  roles        = ["Administrator"]

  resources {
    resource_type = "resource-group"
    resource      = data.ibm_resource_group.group.id
  }
 
}
```

**Comment by dilbertside** [comment]
ok, that works, thanks
issue with documentation then, I followed by the letter in
https://cloud.ibm.com/docs/terraform?topic=terraform-tf-provider#versions
It might be useful to upgrade documentation syntax, as it is confusing
