### ISSUE TITLE
Datasource support to Read CMS

### ISSUE THREAD

**Issue by ifs-hamoucheaitalioua** [IBM-Cloud/terraform-provider-ibm#1277]
Hi there,

We would like to export the certificate from CMS resource, to be able to upload it into the kubernetes secret with native TF resource, instead of using a null_resource and bash scripts.

Thanks in advance

**Comment by hkantare** [comment]
We already have Terraform support to 
https://cloud.ibm.com/docs/terraform?topic=terraform-container-resources#container-alb-cert

**Comment by ifs-pauljegouic** [comment]
It is only supported for `resource`.

What we would like to achieve is the ability to provision our existing certificate in CMS, into a new created cluster to enable HTTPS with our domain.

**Comment by hkantare** [comment]
We do have Terraform support to create or import certificate into CMS
https://cloud.ibm.com/docs/terraform?topic=terraform-cert-manager-resources

**Comment by ifs-pauljegouic** [comment]
I know, but there is no way to retrieve it once created. There is no datasource for CMS. That's our request

**Comment by hkantare** [comment]
Ok..May be can you change the issue somethink like Datasource support to Read  CMS

**Comment by hkantare** [comment]
Available in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.5.1

**Comment by ifs-pauljegouic** [comment]
@hkantare not sure if using it well but here are my result (which are not satisfying)

```hcl
variable "region" {
  default = "eu-de"
}


provider ibm {
  region = var.region
  generation       = 1
  ibmcloud_timeout = 60
}

data "ibm_resource_group" "id" {
  name = "Default"
}

data "ibm_resource_instance" "cm" {
    name     = "cms-skt-integration.ibm.ifsalpha.com"
    location = var.region
    service  = "cloudcerts"
    resource_group_id = data.ibm_resource_group.id.id
}
data "ibm_certificate_manager_certificates" "certs"{
    certificate_manager_instance_id=data.ibm_resource_instance.cm.id
}

output "debug" {
  value = data.ibm_certificate_manager_certificates.certs
}
```

Outputs:

```hcl
➜  Desktop terraform apply
data.ibm_resource_group.id: Refreshing state...
data.ibm_resource_instance.cm: Refreshing state...
data.ibm_certificate_manager_certificates.certs: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

debug = {
  "certificate_manager_instance_id" = "crn:v1:bluemix:public:cloudcerts:eu-de:a/67a4395fde4e4e0ca52f5554b249ceb7:835761c5-f7aa-484c-ac56-313d1011ab1f::"
  "id" = "crn:v1:bluemix:public:cloudcerts:eu-de:a/67a4395fde4e4e0ca52f5554b249ceb7:835761c5-f7aa-484c-ac56-313d1011ab1f::"
}
```

**Comment by ifs-pauljegouic** [comment]
Obivously:

**Comment by hkantare** [comment]
Fixed in latest release v1.6.0 & v1.5.3
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.6.0

**Comment by ifs-pauljegouic** [comment]
Integrated. Resolved, thanks

**Comment by ifs-hamoucheaitalioua** [comment]
Resolved, thanks
