### ISSUE TITLE
Return gateway IP and cidr of primary subnet when vlan is created

### ISSUE THREAD

**Issue by louiseohalloran** [IBM-Cloud/terraform-provider-ibm#128]
It would be very useful if the gateway IP and cidr was returned form network_vlan create 

https://ibm-cloud.github.io/tf-ibm-docs/v0.7.0/r/network_vlan.html

This would be helpful in order to set  the interface on the associated vyatta - ( gateway IP and cidr required ) else scripts need to be written to extract the gateway IP and cidr using SL api calls.

**Comment by Praveengostu** [comment]
So the expectation is to export https://sldn.softlayer.com/reference/datatypes/softlayer_network_Gateway- publicIpAddressId as gateway ip correct?

**Comment by louiseohalloran** [comment]
Hi Praveen,
Thank  you for looking into this. I have been using https://sldn.softlayer.com/reference/services/SoftLayer_Network_Vlan/getPrimarySubnets to get the gateway and cidr  return values. See https://sldn.softlayer.com/reference/datatypes/softlayer_network_subnet return values
```cidr

A subnet's Classless Inter-Domain Routing prefix. This is a number between 0 and 32 signifying the number of bits in a subnet's netmask. These bits separate a subnet's network address from it's host addresses. It performs the same function as the netmask property, but is represented as an integer.
Type:

integer
gateway

A subnet's gateway address. This is an IP address that belongs to the router on the subnet and may not be assigned to a network interface.
Type:

string```


My curl to retrieve what I need is
curl --user "$SOFTLAYER_USERNAME:$SOFTLAYER_API_KEY" -sk https://api.softlayer.com/rest/v3/SoftLayer_Network_Vlan/$VLAN_ID/getPrimarySubnets?objectMask=mask"\[cidr,gateway\]" | python -m json.tool > /tmp/subnets.json

**Comment by Praveengostu** [comment]
@louiseohalloran thanks for the detail description.. Will check this

**Comment by louiseohalloran** [comment]
@ashishth09 @Praveengostu - I see the issue is closed - is the code updated a recent version of the provider - is it possible for me to try this out?
Thanks
Louise

**Comment by Praveengostu** [comment]
The Fix will be available in the next release. You can try building the provider from the master and try with that.

**Comment by louiseohalloran** [comment]
Thanks @Praveengostu - Do you have an approximate date for next release. Will that be 0.8.0?
