### ISSUE TITLE
CIS health check resource creation disregads the description input field.

### ISSUE THREAD

**Issue by ashishth09** [IBM-Cloud/terraform-provider-ibm#1291]
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_cis_healthcheck.go#L36. This field is not used at all.

Happens with https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.5.

**Comment by kavya498** [comment]
Available in
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.4.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.26.0
