### ISSUE TITLE
No data source for ibm_is_security_group (VPC.NG)

### ISSUE THREAD

**Issue by j4zzcat** [IBM-Cloud/terraform-provider-ibm#1292]
Hello, I'm using v1.3.0 and noticed that a data source for ibm_is_security_group is missing (VPC.NG). When is that expected to be implemented?

**Comment by hkantare** [comment]
We will plan to prioritize this item and available in early June

**Comment by somaya10** [comment]
It would be great to have this functionality.

**Comment by hkantare** [comment]
Available in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.10.0
