### ISSUE TITLE
terraform import not working with cluster with bare metal nodes

### ISSUE THREAD

**Issue by krakel** [IBM-Cloud/terraform-provider-ibm#1302]
### Terraform Version
Terraform v0.12.24
+ provider.ibm v1.3.0

### Terraform Command
terraform import

### Debug Output
The targeted resource group could not be found. Make sure you have required permissions to access the resource group.

### Steps to Reproduce
1. create a cluster with bare metal nodes
2. terraform state rm 'ibm_container_cluster.the_name'
3. terraform import 'ibm_container_cluster.the_name'  'crn:v1:bl.......b0::'

I had to change the flavour of the node of a cluster. The ibm provider was deleting and recreating these cluster (this operation needs 3 hours for bare metal). At the end of this operation I got a network error from terraform (sorry I forget to copy the message). The cluster was created correcly . But I can not import existing cluster with terrafrom. I know that I have all permission. A other cluster I changed at this location was created by terraform with no network problems.

**Comment by hkantare** [comment]
Can you export IC_RESOURCE_GROUP=<to the id of resource grp where your cluster resides" because by default it targets to default resource group of your account
```
export IC_RESOURCE_GROUP=<id of resgrp>
terraform import ibm_container_cluster.the_name <id of the cluster>
```

**Comment by krakel** [comment]
now I get:

```
ibm_container_cluster.the_cluster_map["agw-clstr"]: Importing from ID "crn:v1:blue.....k1b0::"...
ibm_container_cluster.the_cluster_map["agw-clstr"]: Import prepared!
  Prepared ibm_container_cluster for import
ibm_container_cluster.the_cluster_map["agw-clstr"]: Refreshing state... [id=crn:v1:blue.....k1b0::]

Error: Cannot import non-existent remote object
```

**Comment by krakel** [comment]
I used `ibmcloud ks cluster get --cluster agw-clstr-fra02-ru --json` for the crn

**Comment by hkantare** [comment]
It should be the ID of the cluster not the CRN
terraform import ibm_container_cluster.the_name bpguksad0ucnesip2ma0

**Comment by krakel** [comment]
It's working. Thanks.

Now I get other problems.
The datacenter will be changed form fra02 to fra02 and no_subnet wil be changed
`
datacenter                   = "fra02" # forces replacement
no_subnet                    = false # forces replacement
`
But I think this is a other issue.
