### ISSUE TITLE
ibm_network_gateway provisioning failing due ipv6_enabled and private_network_only dependency 

### ISSUE THREAD

**Issue by sumit-tembe** [IBM-Cloud/terraform-provider-ibm#131]
Hi there,

Terraform Version
sumit@ubuntu:~/$ terraform -v
2018/02/12 15:59:29 [INFO] Terraform version: 0.11.3 3802b14260603f90c7a1faf55994dcc8933e2069
2018/02/12 15:59:29 [INFO] Go runtime version: go1.9.1

Affected Resource(s)
Please list the resources as a list, for example:

ibm_network_gateway
Debug Output
https://gist.github.com/sumit-tembe/7bf746d203ac3a99a727d91f4e6be6b3

Expected Behavior
What should have happened?
Resource should get provisioned.

Actual Behavior
What actually happened?
IPv6 is mandatory Single Processor Multi-Core Servers but not for Dual Processor Multi-Core Servers. This is SoftLayer behavior need to follow by Terraform provider also.

Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
For 1] issue reported in gist:

Set private_network_only=true , ipv6_enabled=true and
package_key_name=NETWORK_GATEWAY_APPLIANCE
Fort 2] issue reported in gist:

Set private_network_only=true , ipv6_enabled=false and
package_key_name=NETWORK_GATEWAY_APPLIANCE

terraform apply

**Comment by Praveengostu** [comment]
Looking in to this..

**Comment by Praveengostu** [comment]
IPv6 is mandatory Single Processor Multi-Core Servers but not for Dual Processor Multi-Core Servers. This is SoftLayer behavior need to follow by Terraform provider also.
-- Have you set the `package_key_name to 2U_NETWORK_GATEWAY_APPLIANCE_1O_GBPS ` when trying with Dual Processor Multi-Core Servers. This is not available with release 0.7.0. This is fixed part of issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/111

**Comment by sumit-tembe** [comment]
![single-server](https://user-images.githubusercontent.com/35101244/36133902-5379c9cc-10a7-11e8-8633-706726b7f842.png)
![dual-server](https://user-images.githubusercontent.com/35101244/36133904-57d06224-10a7-11e8-9f1c-becb5eb171cc.png)

As you can see for Single Processor Multi-Core Servers IPv6 field is mandatory but for Dual Processor Multi-Core Servers it is optional and you can set IPv6 even if private_network_only=true.

**Comment by Praveengostu** [comment]
@sumit-tembe It should be optional if you set package_key_name to 2U_NETWORK_GATEWAY_APPLIANCE_1O_GBPS

**Comment by sumit-tembe** [comment]
Yes for 2U_NETWORK_GATEWAY_APPLIANCE_1O_GBPS no issues.

**Comment by ashishth09** [comment]
@sumit-tembe 
Please raise a ticket agaist SL to disable setting the IPV6 when the gateway is going to be private in the portal.
If you  order a gateway which is going to be on a  private network and choose IPV6 on the portal , order will go through but you won't get the IPV6. This is an issue with the SL portal
