### ISSUE TITLE
Renaming of Default ACL and Default SG which creates with VPC

### ISSUE THREAD

**Issue by umar201290** [IBM-Cloud/terraform-provider-ibm#1314]
Hi Team, 

Is there any way i can rename the Default ACl and Default SG created as a part of VPC Creation through terraform ?
Even in the attributes i cannot give any existing SG or ACL, it will only create as a part of VPC creation.
Can you please let me know the best possible way to handle it or any feature coming in ?

As of now i tried with local-exec with ibm cli commands to get things done but that's not ideal.

**Comment by VaishnaviGopal** [comment]
If you want to rename already existing security group.. you need to import that security group first and then change the name.

```
terraform import ibm_is_security_group.example <your_sg_id>
```

and define empty sg block in your template like this:

```
resource "ibm_is_security_group" "example" {
}
```

This will import the security group. Now if you want to chnage the name
```
resource "ibm_is_security_group" "example" {
  vpc =  <vpc_id_of_this_sg>
  name = "newname"
}
```

Similarly, you can also rename Network ACL attached to the VPC by following the above mentioned steps

**Comment by umar201290** [comment]
So, if we are creating VPC, then default acl or security group created we need to import them first ?

**Comment by VaishnaviGopal** [comment]
In case you want to rename them usin gterraform , then yes.

**Comment by umar201290** [comment]
is there any plan in future to add name of security group and acl while creating VPC ?
or mentioning an existing security group or acl as default sg and acl while creating VPC via terraform.

**Comment by hkantare** [comment]
This depends on the API support which we get from VPC team..We should have respective API support for this feature
https://cloud.ibm.com/apidocs/vpc#create-a-vpc
