### ISSUE TITLE
Not able to create classic infrastructure resources like vlan with just IC_API_KEY

### ISSUE THREAD

**Issue by ashishth09** [IBM-Cloud/terraform-provider-ibm#1323]
I exported IC_API_KEY and can create containers etc. But can't create ibm_nework_vlan for example. It gives 

```
Error: Error obtaining VLAN id: SoftLayer_Exception_Public: Access Denied.  (HTTP 401)
```
There are couple of fixes. One straightforward fix is to set 
IAAS_CLASSIC_USERNAME to "apikey"
IAAS_CLASSIC_API_KEY to value of IC_API_KEY 

This should be done by the provider if IAAS_* values are not provided.

Probably https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/config.go#L499 is never executed too as I don't give any values. Had just a glance so please check this too.

**Comment by maristgeek** [comment]
Obtaining classic infrastructure keys is called out in https://cloud.ibm.com/docs/terraform?topic=terraform-tf-provider#retrieve_credentials. Are you requesting a change of wording?

**Comment by ashishth09** [comment]
The docs says
```
To provision IBM Cloud classic infrastructure resources, retrieve the classic infrastructure user name and API key. For more information, see Managing classic infrastructure API keys
```

which is not required.

You can provision classic infrastructure resources with IBM Cloud API Key basically with `IC_API_KEY` by setting classic username as "apikey" and classic api key as the value of IBM Cloud API key itself.


My request is to make this change at provider level. If I provide just the IC_API_KEY then I should be able to provision classic infrastructure  resources as well.

**Comment by hkantare** [comment]
Closing this issue and trackign with new issue #3405
