### ISSUE TITLE
Provisioning mongo in us-east fails

### ISSUE THREAD

**Issue by cncook001** [IBM-Cloud/terraform-provider-ibm#1327]
### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
ibm_resource_instance

### Terraform Configuration Files

```
This fails, (times out)
 MongoDB - Production
 resource ibm_database my_team_mongodb {
   name              = "MongoDB - Test and Operations - Production"
   plan              = "standard"
   location          = "us-east" # us-south, us-east, eu-gb, eu-de, au-syd, jp-tok, oslo01
   service           = "databases-for-mongodb"
   resource_group_id = ibm_resource_group.my_team_resource_group.id
   version           = "4.2"
   members_memory_allocation_mb = 2048
   members_disk_allocation_mb   = 20480
}


This works
 MongoDB - Production
 resource ibm_database my_team_mongodb {
   name              = "MongoDB - Test and Operations - Production"
   plan              = "standard"
   location          = "us-south" # us-south, us-east, eu-gb, eu-de, au-syd, jp-tok, oslo01
   service           = "databases-for-mongodb"
   resource_group_id = ibm_resource_group.my_team_resource_group.id
   version           = "4.2"
   members_memory_allocation_mb = 2048
   members_disk_allocation_mb   = 20480
}
### Debug Output
```
module.ibm_cloud.ibm_database.my_team_mongodb: Still creating... [11m30s elapsed]
module.ibm_cloud.ibm_database.my_team_mongodb: Still creating... [11m40s elapsed]
module.ibm_cloud.ibm_database.my_team_mongodb: Still creating... [11m50s elapsed]
Error: Error getting database groups: Request failed with status code: 404, ServerErrorResponse: {"errors":"not_found"}

  on ../../workspace/ibm-cloud/my_team.tf line 216, in resource "ibm_database" "my_team_mongodb":

 216: resource ibm_database my_team_mongodb {
```

### Expected Behavior
Database should be created in us-east like happens in us-south

### Actual Behavior
Error. does not get created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
 `terraform apply`

**Comment by hkantare** [comment]
Please set the provider region attribute to "us-east" if you are trying to provision in us-east
please refer to the docs
https://cloud.ibm.com/docs/terraform?topic=terraform-databases-resources

**Comment by hkantare** [comment]
closing the issue

**Comment by neerajkaushik** [comment]
This is not right we can have a database created in another region than all other resources.
