### ISSUE TITLE
Documentation load balancer listeners

### ISSUE THREAD

**Issue by juanpinzon** [IBM-Cloud/terraform-provider-ibm#1332]
Hi there,

The IBM Cloud provider documentation ([https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#lb-listener](https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#lb-listener)) states that "When provisioning the load balancer listener along with load balancer pool or pool member, use explicit dependencies on the resources", followed by an example of provisioning a `lb_pool` which depends on the `lb_listener`. 

I followed the example and the provisioning part was successful, however, the VPC Load Balancer was not working due there was not a `default_pool` defined on the `listener`. I had to add it manually on the ibmcloud GUI. 

I tried to add `default_pool` to my terraform script but then a problem arises: `Cycle dependency` . My first approach to solve the problem was to use a `local-exec` to run a command cli to update the `lb_listener` after provisioned it. It worked, but then I carefully think about the problem and I realized the example was wrong: `pools` does not have a dependency on `listeners` (there is not a single `input parameter` which depends on the `listener`). `pools` has a dependency though, but on the `load_balancer` due it needs the `load_balancer_id`. Thus, I tried a new approach where you first create a `load_balancer`, then the `lb_pool`(depends on `load_balancer`) and `pools members` (depends on `lb_pool`) and finally the `listeners` (depends on the `lb_pool`, also I could add the `default_pool` input attribute) and now everything is working.

Please update the documentation to avoid this misunderstanding. Thank you.

**Comment by hkantare** [comment]
ok..We will update the example and doc

**Comment by hkantare** [comment]
With latest release of provider the dependency cycle is internally handled uisng mutex
