### ISSUE TITLE
ibm_is_vpc Error when creating VPC with Classic Access

### ISSUE THREAD

**Issue by seafre** [IBM-Cloud/terraform-provider-ibm#1336]
### Terraform Version
```
$  terraform -v
Terraform v0.12.24
+ provider.ibm v1.4.0
+ provider.null v2.1.2
+ provider.tls v2.1.1
```

### Affected Resource(s)
- ibm_is_vpc

### Expected Behavior
Should show graceful failure with re-direction towards documents on Virtual routing and forwarding (VRF) prerequisite actions when enabling `classic_access = true` for a VPC created by Terraform - https://cloud.ibm.com/docs/vpc-on-classic-network?topic=vpc-on-classic-setting-up-access-to-your-classic-infrastructure-from-vpc

### Actual Behavior
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_is_vpc.test_vpc: Creating...

Error: Error while creating VPC gen2-vpc:

  on intel_gen2_vsi.tf line 112, in resource "ibm_is_vpc" "test_vpc":
 112: resource "ibm_is_vpc" "test_vpc" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by hkantare** [comment]
We are moving to new SDK owned by VPC team...We will test this as part of that SDK and will update

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.5.1
