### ISSUE TITLE
Insuffiient details from Bluemix APIs nd terraform resource

### ISSUE THREAD

**Issue by vijaylakshmi-b** [IBM-Cloud/terraform-provider-ibm#134]
Hi there,

For enabling Bluemix services from Consume, we are looking at the terraform resource:

https:1//github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/data_source_ibm_service_instance.go

To enable a resource using this resource, we would required 2 things:
1) Name of the resource
2)  Additional parameters specific to a resource

For (1), as per the docs, we use the following API to list the resources that can be provisioned in BX: http://api.ng.bluemix.net/v2/services

Althoug this returns 164 results, it still misses some of the resources that we have as stories like : Compose for <service>, DB2 Wareshouse, API connect etc. 

Terraform provider for "service_instance" has an Optional field parameters, but these extra parameters passed in the tf file are not used by this resource (This may be an issue of key name being used). This was tried through command line with extra parameters as json object but that does not seem to work. Following are the concerns we have:
Lack of documentation on usage of extra parameters.
Default value of extra parameters taken by terraform/cli.
Missing service offerings as part of the service offering cli/api
Bluemix api key is required in order to create any service otherwise terraform gives an error.

Example
MongoDB:
This service has an additional parameter "Database version". However, the API does not process the key-value pairs of following request body, even though it shows that it is being passed as part of the Optional parameter attribute.
{
"database_version":"3.2.11"
}
Attached are the screenshots for reference
![parameter](https://user-images.githubusercontent.com/36625534/36377042-801cb16c-159b-11e8-8007-0fc4d970e9a0.png)
![mongo_parameter](https://user-images.githubusercontent.com/36625534/36377044-80d9c4dc-159b-11e8-87a2-a459371645e8.png)

Request your help on pointing us to the correct usage of these parameters. Also, a little clarity on the role of "service brokers" API. Any documentation/reference would be of great help.

For (2), some resources have additional parameters which seem like they could be handled by the "parameters" atribute of the terraform resource. But since this resource lacks documentation, we need some more information on the keys that would be part of teh additional parameters. 

We will keep this story updated as and when we find some useful information. But any help from BX and the plugin team will help us handle the large number of stories around bluemix efficiently.  

### Affected Resource(s)
- ibm_service_instance

**Comment by albee-jhoney** [comment]
Using the Chrome debugging tools to inspect the POST going to create the service..  
The request payload when you try and create a Compose/MongoDB:
{
"name":"Compose for MongoDB-gd",
"space_guid":"8c64dc9b-7bd5-4b4c-9ac5-1708cc3ff4ef",
"service_plan_guid":"b62704d2-2bd4-4041-ac3c-08945f9f9c3b",
"service_guid":"4d546349-a9d5-42e9-b0bb-dd069efbb456",
"parameters":{"db_version":"3.2.18"}
}

Try "db_version" instead of "database_version".

**Comment by hkantare** [comment]
closing this issue ...Please reopen if issue still exists
