### ISSUE TITLE
Add Terraform support to VPC - Dedicated hosts

### ISSUE THREAD

**Issue by SukeshPrabhakar** [IBM-Cloud/terraform-provider-ibm#1355]

**Comment by MalarvizhiK** [comment]
Dedicated Host is not GAed. Once the component is GAed, we will deliver the Terraform provider support for this. Expected date is Q4 2020.

**Comment by l2fprod** [comment]
@MalarvizhiK  @hkantare 

dedicated host had GAed - https://cloud.ibm.com/docs/vpc?topic=vpc-creating-dedicated-hosts-instances

**Comment by svennam92** [comment]
@hkantare can we close this now? looks like we have support for dedicated host:
https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-resources#is-dedicatedhost

Looks like it was released in IBM Cloud Terraform Provider v1.22.0

**Comment by hkantare** [comment]
closing this issue
