### ISSUE TITLE
Add Terraform support to VPC - FlowLogs

### ISSUE THREAD

**Issue by SukeshPrabhakar** [IBM-Cloud/terraform-provider-ibm#1356]

**Comment by movinglightspeed** [comment]
+ plus for this, I would like to see this as well.

**Comment by MalarvizhiK** [comment]
We are working on adding terraform provider support for VPC Flow Logs. The expected date is 1st week of sep.

**Comment by hkantare** [comment]
We delviered support for flow logs
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources
