### ISSUE TITLE
update network_vlan resource to allow user to pass in "notes" value

### ISSUE THREAD

**Issue by louiseohalloran** [IBM-Cloud/terraform-provider-ibm#136]
Would it be possible to update network_vlan resource to allow user to pass in "notes" value - that will appear in SL in "Notes" field for VLAN.

This is allowed in network_gateway resource but not in VLAN.

**Comment by ashishth09** [comment]
This will be dealt with when we can edit the notes fields or add the notes field while ordering a VLAN.  I have tried this and was unable to do so. I have raised a ticket for the same. Are you able to do so from the SoftLayer portal?

**Comment by ashishth09** [comment]
Per SL `the notes field in the VLAN is not usable for customers. It is only intended for internal use at this time.`
