### ISSUE TITLE
terraform cannot update cluster as no_subnet is null

### ISSUE THREAD

**Issue by jackevans-ibm** [IBM-Cloud/terraform-provider-ibm#1360]
Hello, I am trying to move management of existing clusters to Terraform and am running into issues (potentially where they are old clusters).

I am doing `terraform import ibm_container_cluster.cluster <clusterid>` where the resource is defined as follows:
```
resource "ibm_container_cluster" "cluster" {
  name              = var.cluster_name
  datacenter        = ""
  default_pool_size = var.pool_size
  hardware          = var.hardware
  machine_type      = var.machine_type
  public_vlan_id    = var.public_vlan_id
  private_vlan_id   = var.private_vlan_id
  kube_version      = var.kube_version
}
```
which fetches the state of my cluster and stores in the .tfstate file. However, no matter what when  I run `terraform plan -var-file=<tfvarfile>` it always says it will destroy and recreate my cluster (which I really dont want as I would want to migrate some production clusters to the same).

The problem appears to be the no_subnet property. The tfstate file shows the cluster as having it set to null, but I am unable to define null in the resource above as it will default to false (causing a force replacement) or if I set to true (causes a force replacement). Is there any way around this?

### Terraform Version
```bash
terraform -v
Terraform v0.12.24
+ provider.ibm v1.4.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_cluster

### Expected Behavior
What should have happened?

No difference between plans

### Actual Behavior
What actually happened?

will destroy and force create a new cluster

### Important Factoids
- This is a cluster created in 2018, so may have differences between old and new clusters created in IKS

### References
N/A

**Comment by hkantare** [comment]
As a temporary workaround can you set the no_subnet to fasle in tf.state..We will look into the issue

**Comment by hkantare** [comment]
Fixed in latest releases..Imports works as expected 
https://github.com/IBM-Cloud/terraform-provider-ibm/releases
