### ISSUE TITLE
Security Group Rule terraform resource does not contain all rules as shown on the SoftLayer Portal

### ISSUE THREAD

**Issue by vijaylakshmi-b** [IBM-Cloud/terraform-provider-ibm#138]
Hi there,

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_security_group_rule

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
The Security group rule resource does not contain the some of the values, which are available on SoftLayer Portal:
The "Protocol" dropdown for the Security Group Rule service currently displays only 3 protocols:
1. TCP
2. UDP
3. ICMP
But, Softlayer dashboard provides some additional options which are as follows:
1. All
2. All TCP
3. All UDP
4. All ICMP

### Actual Behavior
The above mentioned extra protocols need to be included in the provider resource.

**Comment by ashishth09** [comment]
Existing resource supports creation of 4,5,6 and 7 above.
Please use the below configuration:

```
resource "ibm_security_group" "testacc_sg" {
  name = "akt"
}

//All
resource "ibm_security_group_rule" "testacc_sg_rule" {
  direction         = "ingress"
  security_group_id = "${ibm_security_group.testacc_sg.id}"
}

//All TCP
resource "ibm_security_group_rule" "testacc_sg_rule1" {
  direction         = "ingress"
  protocol          = "tcp"
  security_group_id = "${ibm_security_group.testacc_sg.id}"
}

//All UDP
resource "ibm_security_group_rule" "testacc_sg_rule2" {
  direction         = "ingress"
  protocol          = "udp"
  security_group_id = "${ibm_security_group.testacc_sg.id}"
}

//All ICMP
resource "ibm_security_group_rule" "testacc_sg_rule3" {
  direction         = "ingress"
  protocol          = "icmp"
  security_group_id = "${ibm_security_group.testacc_sg.id}"
}
```
