### ISSUE TITLE
IBM Cloud Databases CLI Behavior Update

### ISSUE THREAD

**Issue by svennam92** [IBM-Cloud/terraform-provider-ibm#1387]
From James Thorne (IBM):

There's a behaviour change in the ibmcloud CLI that I wanted to give your team a heads up on in case it impacts you.
The `ibmcloud resource service-key-create` command has been broken for ICD services -- they've been working with the CLI team on a fix but it's coming with a behaviour change -- the [ROLE] parameter must now not be passed when working with ICD and other non-IAM-enabled services.
So
`ibmcloud resource service-key-create <key> Administrator --instance-name <name>`
is now just
`ibmcloud resource service-key-create <key> --instance-name <name>`
Does Terraform use the CLI and does that cause any issues on your end? The associated Resource Controller API is unchanged, as is the UI; the change just affects the ibmcloud CLI.
For more context the ticket is here: https://github.ibm.com/Bluemix/bluemix-cli/issues/3006

**Comment by hkantare** [comment]
Yes we do have similar desgin flow as cli where the roles is required parameter..We need to make roles a optional parameter and migrate to v2 version of API's (we are using v1 version API's)

**Comment by hkantare** [comment]
@svennam92 We are using our own developed SDK which we are v1 version..Can we work with Resource controller team does they have any SDK developed ?
