### ISSUE TITLE
Add terraform provider support for Instance template - new VPC feature

### ISSUE THREAD

**Issue by MalarvizhiK** [IBM-Cloud/terraform-provider-ibm#1394]
This API will be taken care by IBM Cloud Network team in Bangalore. 

You can find the details here: https://github.ibm.com/orion/vnf-vpc-planning/issues/89

REST API:
/instance/templates

Instance Template:
-----------------------
CreateInstanceTemplate
UpdateInstanceTemplate
DeleteInstanceTemplate
GetInstanceTemplate
ListInstanceTemplates

Swagger: https://pages.github.ibm.com/riaas/api-spec/spec_genesis_scoped/#/Instances/create_instance_template

As part of Instance Template, we will also be doing the Dedicated Host and Dedicated Host Group. 

DedicatedHost: 
-------------------
ListDedicatedHosts
CreateDedicatedHost
DeleteDedicatedHost
GetDedicatedHost
UpdateDedicatedHost

DedicatedHostGroup 
----------------------
ListDedicatedHostGroups
CreateDedicatedHostGroup
DeleteDedicatedHostGroup
GetDedicatedHostGroup
UpdateDedicatedHostGroup

**Comment by MalarvizhiK** [comment]
I am unable to update milestone. We will deliver this in Q3 2020. Custom route and antispoofing features are not yet GAed.

**Comment by kavya498** [comment]
Closing this issue..
Thanks
