### ISSUE TITLE
ICMP allow all rule is not doable

### ISSUE THREAD

**Issue by pkrishn1-pk** [IBM-Cloud/terraform-provider-ibm#1401]
### Affected Resource(s)
- ibm_is_security_group_rule

If I want to create ICMP security inbound allow all rule (0.0.0.0), code and type is not needed in REST API, so in terraform provider also I did not give code and type

### Expected Behavior
Resource should have ran and the appropriate security rule should have been created.

### Actual Behavior
It fails to execute the script, it needs code and type as mandatory input.

### Steps to Reproduce
Execute the below resource in terraform script, it should pass, but fails since code and type is not passed as input.

resource "ibm_is_security_group_rule" "testacc_security_group_rule_icmp" {
		depends_on = [ibm_is_security_group_rule.testacc_security_group_rule_all]
		group      = ibm_is_security_group.testacc_security_group.id
		direction  = "inbound"
		remote     = "0.0.0.0"
		icmp {		  
		}
	  }

**Comment by hkantare** [comment]
Fixed in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.9.0

**Comment by hkantare** [comment]
closing the issue
