### ISSUE TITLE
container_worker_pool label attribute type change

### ISSUE THREAD

**Issue by wderezin** [IBM-Cloud/terraform-provider-ibm#1406]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
terraform --version
Terraform v0.12.24
+ provider.ibm v1.5.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_worker_pool

Occured in Commit 94fdca1e9ee9f3796ae4747df99e9627f29aee14

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource ibm_container_cluster cluster {
  name                     = "test"
  datacenter               = "dal10"
  hardware = "shared"
}
resource "ibm_container_worker_pool" "pool" {
  worker_pool_name  = "test"
  cluster           = ibm_container_cluster.cluster.id
  machine_type      = "u3c.2x4"
  size_per_zone     = 1
  labels            = {
    env = "dev"
  }
}
terraform {
  required_version = ">= 0.12, < 0.13"
  required_providers {
    ibm = "1.5.1"
  }
}
```

### Debug Output
```
➜  worker_pool_test git:(test) grep -w ibm main.tf
    ibm = "1.5.1"
➜  worker_pool_test git:(test) terraform plan 
Error: Incorrect attribute value type

  on main.tf line 11, in resource "ibm_container_worker_pool" "pool":
  11:   labels            = {
  12:     env = "dev"
  13:   }
```

### Panic Output
n/a

### Expected Behavior
It should `terraform plan` clean

### Actual Behavior
Get attribute errorSee debug output.  

### Steps to Reproduce
Using the above HCL config will produce the debug output
1. `terraform plan`

Change the ibm provider to 1.5.0 in the HCL config and the config will plan:
```
➜  worker_pool_test git:(test) grep -w ibm main.tf
    ibm = "1.5.0"

➜  worker_pool_test git:(test) terraform plan  
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ibm_container_cluster.cluster will be created
... # resource removed for brevity
  # ibm_container_worker_pool.pool will be created
... # resource removed for brevity

Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Important Factoids

The worker pool label attribute was changed from map to set in commit 94fdca1e9ee9f3796ae4747df99e9627f29aee14

**Comment by hkantare** [comment]
We rolled back the type to Type.Map in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.5.2

**Comment by allen-servedio** [comment]
Thanks @hkantare - we tested it and it is working again. Appreciate the fast turn around on it.
