### ISSUE TITLE
Support for IBM Cloud Satellite

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#1425]
As a end user we need a Terraform support to work with satellite

1. Create location
2. Assign host
3. Downloading host scripts

**Comment by svennam92** [comment]
@hkantare FYI - moving this to Q4 for now but may need to move to early 2021Q1 based on availability.

**Comment by hkantare** [comment]
The support for satellite is available in latest releases
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs
