### ISSUE TITLE
Citrix VPX Load Balancer provisioning fails for ip_count=1

### ISSUE THREAD

**Issue by siddharthoak** [IBM-Cloud/terraform-provider-ibm#143]
Hi there,

## Terraform Version
Terraform v0.11.3

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_ibm_lb_vpx.go

### Terraform Configuration Files

resource "ibm_lb_vpx" "testacc_foobar_vpx" {
    datacenter = "dal09"
    speed = 10
    version = "10.1"
    plan = "Standard"
	ip_count = 1
	tags = ["one", "two", "three"]
}

### Expected Behavior
Irrespective of ip count, the provisioing should have been succesful

### Actual Behavior
Error : * ibm_lb_vpx.testacc_foobar_vpx: Error Cannot find Application Delivery Controller prices 'IP quantity value is incorrect'.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Fix: 
func getPublicIpItemKeyName(ipCount int) string {

	name := "STATIC_PUBLIC_IP_ADDRESSES"
	**if ipCount == 1 {
		name = "STATIC_PUBLIC_IP_ADDRESS"
	}**
	ipCountString := strconv.Itoa(ipCount)

	return strings.Join([]string{ipCountString, name}, DELIMITER)
}

**Comment by ashishth09** [comment]
Ordering a single IP is free.. so look up for the price should not be performed.

**Comment by ashishth09** [comment]
I just scanned https://api.softlayer.com/rest/v3/SoftLayer_Product_Package/192/getItems and looks  like, the suggested fix should work.

@siddharthoak ,
Could you raise PR for the same? We will need one UAT to be added to the bucket for the same.
Thanks
