### ISSUE TITLE
where to get VPC instance image id?

### ISSUE THREAD

**Issue by DanielChuDC** [IBM-Cloud/terraform-provider-ibm#1432]
Just download this project and navigate to example folder trying to provision the `ibm-is-vpc`. 

Where can we get the image list and image id? Please include the method to list the image if possible.

Second question about pre-bake image, can we pre-bake the image and use it for this VPC instance?

If we cannot pre-bake, can we use import custom image from AWS AMI or using Packer to build the custom image and use it for this VPC instance?

- Example
```tf
resource "ibm_is_instance" "instance1" {
  name    = "instance1"
  image   = var.image
  profile = var.profile

  primary_network_interface {
    subnet = ibm_is_subnet.subnet1.id
  }

  vpc       = ibm_is_vpc.vpc1.id
  zone      = var.zone1
  keys      = [ibm_is_ssh_key.sshkey.id]
  user_data = file("nginx.sh")
}

resource "ibm_is_floating_ip" "floatingip1" {
  name   = "fip1"
  target = ibm_is_instance.instance1.primary_network_interface[0].id
}
```

**Comment by hkantare** [comment]
You can use ibmcloud cli to get the list of images....Yes we support custom_image for creating an vm instance

https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-managing-images
The image should be imported to COS and then can use ibm_is_image resource to import the image from cos to VPC..https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#image

**Comment by DanielChuDC** [comment]
Thank you for replying @hkantare 

May I know if I can import the custom image using terraform script?

I intend to do all automatically and I look though the documentation from https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-managing-images. What I found is there is no full automated lifecycle.

I am suggesting to add in support for `create COS bucket`, `create custom image using terraform or Packer`, `Upload the custom image in COS`, `Use the return COS ID for provisioning the Next gen instance`

**Comment by hkantare** [comment]
We support automation of creating COS, COS bucket the remaining sections of creating custom image and upload of image can be achieved using some scripts or null resource

**Comment by hkantare** [comment]
closing based on above comments
