### ISSUE TITLE
Terraform support for IAM custom roles

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#1433]
As a end user I need terraform support to create IAM custom roles
- Resource to create custom role
- Datasource to fetch service action names
- Fix the existing resources like policies , resource_key to accept the custom role

**Comment by kjoconnor** [comment]
Is this supposed to allow assigning custom JSON policy documents to a custom role? Or is that already supported somewhere?

**Comment by hkantare** [comment]
@kjoconnor We are not clear with the query you are asking...As part of this issue we supported terraform support for CURD of custom roles as per this API
https://cloud.ibm.com/apidocs/iam-policy-management#create-a-role
https://cloud.ibm.com/docs/terraform?topic=terraform-iam-resources#iam-custom-role

**Comment by kjoconnor** [comment]
I'm looking for the provider to support this: https://cloud.ibm.com/docs/account?topic=account-wildcard

I'm new to IBM Cloud so forgive me if this doesn't make sense!

**Comment by hkantare** [comment]
That is related to access policies..currently we don't have support to take json for creating policies

**Comment by hkantare** [comment]
closing the issue
