### ISSUE TITLE
Try to provision IBM-IS-NG example , face:  Error: Incorrect attribute value type   

### ISSUE THREAD

**Issue by DanielChuDC** [IBM-Cloud/terraform-provider-ibm#1436]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.12.24
+ provider.ibm v1.5.2

### Error message
Error: Incorrect attribute value type

  on main.tf line 23, in resource "ibm_is_lb" "lb2":
  23:   subnets = ibm_is_subnet.subnet1.id

Inappropriate value for attribute "subnets": set of string required.

**Comment by DanielChuDC** [comment]
It seem like same issue from 
https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/271

**Comment by hkantare** [comment]
The issue here is with example syntax  ...The subnets is the the list for loadbalancer
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/d8f229d9550bd684edcd69b9b454059e8ebee27b/examples/ibm-is-ng/main.tf#L23
