### ISSUE TITLE
is_security_group is returning before it's available in an instance

### ISSUE THREAD

**Issue by f5craigsca** [IBM-Cloud/terraform-provider-ibm#1447]
Using Terraform v0.12.24

We are creating instances, but first creating a series of security groups associated with the instance.  We are experiencing the following error:
"apply failure: \nError: The security group to attach to is not available\n\n  on main.tf line 193, in resource \"ibm_is_instance\" \"f5_ve_instance\":\n 193: resource \"ibm_is_instance\" \"f5_ve_instance\" {\n\n\n"

Here is the code - we create a security group, add rules and then create the instance:
```
resource "ibm_is_security_group" "f5_management_sg" {
  name = "sm-${random_uuid.namer.result}"
  vpc  = data.ibm_is_subnet.f5_management.vpc
}

resource "ibm_is_security_group_rule" "f5_management_in_icmp" {
  group     = ibm_is_security_group.f5_management_sg.id
  direction = "inbound"
  icmp {
    type = 8
  }
}

resource "ibm_is_instance" "f5_ve_instance" {
  name    = var.instance_name
  image   = data.ibm_is_image.tmos_image.id
  profile = data.ibm_is_instance_profile.instance_profile.id
  primary_network_interface {
    name            = "management"
    subnet          = data.ibm_is_subnet.f5_management.id
    security_groups = [ibm_is_security_group.f5_management_sg.id]
  }
  network_interfaces {
    name            = "tmm-1-1-internal"
    subnet          = data.ibm_is_subnet.f5_internal.id
    security_groups = [ibm_is_security_group.f5_tmm_sg.id]
  }
  network_interfaces {
    name            = "tmm-1-2-external"
    subnet          = data.ibm_is_subnet.f5_external.id
    security_groups = [ibm_is_security_group.f5_tmm_sg.id]
  }
  vpc  = data.ibm_is_subnet.f5_management.vpc
  zone = data.ibm_is_subnet.f5_management.zone
  keys = [data.ibm_is_ssh_key.f5_ssh_pub_key.id]
  user_data = data.template_file.user_data.rendered
  depends_on = [ibm_is_security_group.f5_management_sg, ibm_is_security_group.f5_tmm_sg]
}
```

**Comment by f5craigsca** [comment]
We are seeing about 36% of our instances fail with this error.

**Comment by sakthishanmugam2terraform** [comment]
@f5craigsca 
For this case, we have proposed a way to serialize the operations of creating security group > security group rule > VSI instance provisioning using terraform depends_on block. This approach is tested and proved effective, and no failure is seen after that. Hope with this solution in place, we can close this issue.

e.g. 
```
resource "ibm_is_security_group" "f5_tmm_sg" {
  depends_on = [ibm_is_security_group_rule.f5_management_out_icmp]
  ...
} 
resource "ibm_is_security_group_rule" "f5_tmm_out_icmp" {
  depends_on = [ibm_is_security_group.f5_tmm_sg]
  ...
} 
resource "ibm_is_instance" "f5_ve_instance" {
  depends_on = [ibm_is_security_group_rule.f5_tmm_out_icmp]
  ...
}
```

**Comment by MalarvizhiK** [comment]
Documentation PR: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/1522/files

**Comment by MalarvizhiK** [comment]
We have proposed a workaround to Craig. We have documented the solution proposed above in the cloud.ibm.com terraform documentation. This issue can be closed.
