### ISSUE TITLE
Feature Request: more CIS Domain Settings

### ISSUE THREAD

**Issue by maristgeek** [IBM-Cloud/terraform-provider-ibm#1475]
Hi there,

The list of settings that are managed as of v1.5.3 of the provider is: `{"waf", "ssl", "min_tls_version", "automatic_https_rewrites", "opportunistic_encryption", "cname_flattening"}`

We would like to manage at least these additional settings through Terraform:
- `always_use_https`
- `ipv6`

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_cis_domain_settings

### References
- `ibmcloud cis domain-settings-update --help` is the best reference with descriptions and valid values

**Comment by hkantare** [comment]
Fixed in latest https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.7.1

**Comment by maristgeek** [comment]
Will close since those were added but filing a regression that blocks users from having CIS instances using a _Standard_ plan.
