### ISSUE TITLE
0.27.3 release linux archive now has folder inside

### ISSUE THREAD

**Issue by tpolekhin** [IBM-Cloud/terraform-provider-ibm#1479]
Hello,
latest release 0.27.3 archive for linux_amd64.zip now has binaries inside the linux_amd64 folder in the archive instead of the top level:
was `linux_amd64.zip/terraform-provider-ibm_v0.27.2`
now `linux_amd64.zip/linux_amd64/terraform-provider-ibm_v0.27.3`
This change broke our CICD process for building terraform agent image with provider

Is this a permanent change going forward, or was it just a one time mistake release?
Thanks!

**Comment by Anil-CM** [comment]
Hi @tpolekhin, yeah it was by mistake. We have reverted it back. Please use the updated release package.

**Comment by tpolekhin** [comment]
@Anil-CM thanks a lot for a quick response!
I did test our build again and it looks like everything is fixed now.
Thanks for your help!
