### ISSUE TITLE
Race condition upgrading ibm_container_vpc_worker_pool

### ISSUE THREAD

**Issue by tpolekhin** [IBM-Cloud/terraform-provider-ibm#1485]
### Terraform Version
Terraform v0.12.24
+ provider.ibm v1.5.2

### Affected Resource(s)
ibm_container_vpc_worker_pool

### Terraform Configuration Files
```hcl
resource "ibm_container_vpc_worker_pool" "cassandra" {
  cluster           = ibm_container_vpc_cluster.cluster.id
  worker_pool_name  = "cassandra"
  flavor            = "cx2.2x4"
  vpc_id            = ibm_is_vpc.vpc.id
  worker_count      = "1"
  resource_group_id = data.ibm_resource_group.group.id
  labels = {
    dedicated = "cassandra"
  }
  zones {
    name      = "us-south-1"
    subnet_id = ibm_is_subnet.us-south-1.id
  }
  zones {
    name      = "us-south-2"
    subnet_id = ibm_is_subnet.us-south-2.id
  }
  zones {
    name      = "us-south-3"
    subnet_id = ibm_is_subnet.us-south-3.id
  }
}
```

### Expected Behavior
ibm_container_vpc_worker_pool upgraded with 2 new zones

### Actual Behavior
```
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 15m50s elapsed]
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 16m0s elapsed]
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 16m10s elapsed]
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 16m20s elapsed]
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 16m30s elapsed]
ibm_container_vpc_worker_pool.cassandra: Destruction complete after 16m30s
ibm_container_vpc_worker_pool.cassandra: Creating...

Error: Request failed with status code: 409, ServerErrorResponse: {"incidentID":"596f44f110ea840a-KBP","code":"E0d39","description":"A worker pool with the same name already exists within the cluster. Choose another name.","type":"Provisioning"}

  on main.tf line 143, in resource "ibm_container_vpc_worker_pool" "cassandra":
 143: resource "ibm_container_vpc_worker_pool" "cassandra" {
```

### Steps to Reproduce
1. create a cluster with `ibm_container_vpc_worker_pool` having only 1 zone
2. update terraform code for `ibm_container_vpc_worker_pool` to have 3 zones

**Comment by tpolekhin** [comment]
Any updates on this issue?

**Comment by hkantare** [comment]
As of now we don't have any update we are working on this feature to support the update of zones ..This work is in progress we will update once its release

**Comment by tpolekhin** [comment]
@hkantare this issue is not about updating the zones for the worker_pool
This is about doing a re-create on a worker_pool object that fails right after destruction is done and terraform tries to create a new worker_pool with the same name. Apparently the backend API for it doesn't know yet that the name is free so it fails with `Error: Request failed with status code: 409, ServerErrorResponse: {"incidentID":"596f44f110ea840a-KBP","code":"E0d39","description":"A worker pool with the same name already exists within the cluster. Choose another name.","type":"Provisioning"}`

**Comment by hkantare** [comment]
```
Steps to Reproduce

    create a cluster with ibm_container_vpc_worker_pool having only 1 zone
    update terraform code for ibm_container_vpc_worker_pool to have 3 zones

```

As per above steps you are adding new zones...since currently don't have update support we are force_new on the change of the zones which means it destroy and recreate total worker pool.

With the update support which we are planning to provide will add or delete  zones to the existing worker pool ...

```
Error: Request failed with status code: 409, ServerErrorResponse: {"incidentID":"596f44f110ea840a-KBP","code":"E0d39","description":"A worker pool with the same name already exists within the cluster. Choose another name.","type":"Provisioning"}
```

May be there is some time lag at the armada API to update the backend API regarding the name

**Comment by tpolekhin** [comment]
@hkantare I understand that updating a resource to support dynamic zone addition and removal will fix this particular use case, but I think that this issue will persist in ANY worker_pool modification that requires `force_new` and this is what this issue is about specifically, not zones adding or removal.
If there's a time lag in the armada API to update the worker_pool name status as available I think terraform provider should account for that, instead of failing the entire deployment.
