### ISSUE TITLE
add vpc flow log collector support to the ibm_is_X collection of resources and data sources

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#1488]
The vpc gen 2 offering needs flow low collector support:
- https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources
- https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-data-sources

Currently available through a white listed account.

**Comment by MalarvizhiK** [comment]
We are working on this. Expected date of delivery is 1st week of sep. Q3 2020.

**Comment by MalarvizhiK** [comment]
Code is merged. Here are the instructions for Provisioning VPC Flow Logs in IBM Cloud using Terraform:
https://developer.ibm.com/recipes/tutorials/provisioning-vpc-flow-logs-in-ibm-cloud-using-terraform/
