### ISSUE TITLE
Feature Request: Add support for Identity & Access Manager elements

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#149]
IAM concepts such as:
- Policies,
- Roles,
- Resource Groups,
- Assigning Users to Access Groups
- Assigning Policies to Access Groups and Users
- API keys,
- Service IDs
should be supported by the provider

https://console.bluemix.net/docs/iam/iam_overview.html#iamconcepts

Terraform resources compatible with the "resource group" concept should also expose a "resource_group" property to be added/removed from a resource group

**Comment by crosen188** [comment]
@davetropeano

**Comment by hirodotp** [comment]
Is there any time line when IAM Access Groups will become available?  I am managing many users for many different spaces and it becomes a pain to handle permissions, etc. for every user individually.  The ability to at least add a user to an Access Group would alleviate this limitation.

**Comment by hkantare** [comment]
The support for IAM access groups are provided in v0.12.0

IBM IAM Access Group (ibm_iam_access_group)
IBM IAM Access Group Members (ibm_iam_access_group_members)
IBM IAM Access Group Policy (ibm_iam_access_group_policy)

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0

**Comment by hkantare** [comment]
We added support for IAM Resources.

**Comment by oker1** [comment]
I can't find any support for API keys, is it planned?
