### ISSUE TITLE
Support for IAM namespace for Cloud Functions

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1493]
Hi there,

We would like to be able to use Cloud Functions with the IAM-based namespace. It's only supporting the `<org>_<space>` syntax.

Thanks in advance,

### Affected Resource(s)

- ibm_function_*

**Comment by hkantare** [comment]
The latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.9.0
We have support to work with both CF and IAM namespaces....
