### ISSUE TITLE
Support for ibm_function_api

### ISSUE THREAD

**Issue by pauljegouic** [IBM-Cloud/terraform-provider-ibm#1494]
Hi there,

We would like to have the opportunity to manage the API resource of Cloud Functions through Terraform.

Regards,

**Comment by itraveribon** [comment]
Hi,

I am also interested in this feature. Is this something planned in the near future?

Regards.

**Comment by ifs-pauljegouic** [comment]
Any update ?

**Comment by hkantare** [comment]
We are working on it..We are intiating the discussion between OM and Funtion team.

**Comment by l2fprod** [comment]
any news on this?

It is the missing piece in allowing full configuration of my Cloud Functions project through terraform :(
