### ISSUE TITLE
HTTP code 400 when creating a docker ibm_function_action

### ISSUE THREAD

**Issue by itraveribon** [IBM-Cloud/terraform-provider-ibm#1503]
Hi there,

### Terraform Version
Terraform v0.12.25
+ provider.ibm v1.6.0

### Affected Resource(s)
- ibm_function_action

### Terraform Configuration Files
```data "ibm_space" "spacedata" {
  space = var.space
  org   = var.org
}

resource "ibm_function_package" "package" {
  name = var.packageName

}

resource "ibm_function_action" "action" {
  name = "${ibm_function_package.package.name}/${var.actionName}"

  exec {
    kind = "itraveribon/ibmcloud"
    image = file("tensorflow_predict.py")
  }
}
```

### Debug Output
https://gist.github.com/itraveribon/0c5e1e030edf951db437b2dec96395cd

### Panic Output
I did not see any panic.

### Expected Behavior
The cloud function should have been created without problems.

### Actual Behavior
For some reason, terraforms does not accept this configuration. However, the configuration is very similar to what we find here https://ibm-cloud.github.io/tf-ibm-docs/v1.0.0/r/function_action.html. The difference is that we are dealing with a python script. If I try to create the function setting "kind: python3.6", then terraform works properly. However, the function won't work because the dependencies are in the docker container, which was not uploaded.

### Steps to Reproduce
Terraform apply should be enough.
1. `terraform apply`

### Important Factoids
I am running with the lite account. I could create this function by using the ibmcloud CLI:
`ibmcloud fn action create action --docker itraveribon/ibmcloud tensorflow_predict.py`

Am I doing something wrong or is there a bug in the software?

**Comment by itraveribon** [comment]
It seems I was doing something wrong. The documentation we find [here](https://ibm-cloud.github.io/tf-ibm-docs/v1.0.0/r/function_action.html) for docker actions is wrong. If we want a terraform resource equivalent to what we get when we execute `ibmcloud fn action create action --docker itraveribon/ibmcloud tensorflow_predict.py`, then the terraform file should look like as follows:
`data "ibm_space" "spacedata" {
  space = var.space
  org   = var.org
}

resource "ibm_function_action" "action" {
  name = var.actionName

  exec {
    kind = "blackbox"
    image = "itraveribon/ibmcloud:latest"
    code = file("tensorflow_predict.py")
  }
}`

**Comment by hkantare** [comment]
we will update the documentation with proper example

**Comment by hkantare** [comment]
Fixed in docs https://cloud.ibm.com/docs/terraform?topic=terraform-function-resources#docker-action
