### ISSUE TITLE
Feature request: support flavor in ibm_compute_vm_instance

### ISSUE THREAD

**Issue by aughr** [IBM-Cloud/terraform-provider-ibm#151]
We're interested in using `ibm_compute_vm_instance` to manage provisioning VMs, but it appears that the current resource doesn't understand how to order machines with flavors (or modify them, although that's less important to us).

Given that prices are lower for flavors than using the same resulting configuration without a flavor, this is a bit of a blocker to using this provider to manage VMs for us.

**Comment by tianhw2006** [comment]
I really appreciate if anyone can have a look at this.

**Comment by sakshiag** [comment]
@tianhw2006 : We are looking into this.. Will update you soon.

**Comment by sakshiag** [comment]
We have added support for flavor while provisioning the vm instance in the following commit:
https://github.com/IBM-Cloud/terraform-provider-ibm/commit/b278d49ad47ecd7489d83f613116c73944c73674

You can test it and let us know.

Update for flavor is pending. We will keep it open to track the update flavor feature.

**Comment by sakshiag** [comment]
The feature is available in the latest build located at https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.9.1
Hence closing this.
