### ISSUE TITLE
Feature request: Certificate manager add key_algorithm to order

### ISSUE THREAD

**Issue by timroster** [IBM-Cloud/terraform-provider-ibm#1512]
Support the specification of the key strength properties [`rsaEncryption 2048 bit`, `rsaEncryption 4096 bit`] as supported by `key_algorithm` property in the `/v1/{instance_id}/certificates/order` API endpoint

**Comment by hkantare** [comment]
Fixed in latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.7.1

**Comment by timroster** [comment]
verified request and creation of 4k certificates in `v1.7.1`

**Comment by timroster** [comment]
Requested certificates of length 4k are not actually being fulfilled when using a non-CIS DNS provider. This is probably not an issue caused by the terraform provider and a support ticket is open. 

@hkantare I think it's ok to close this issue, functionality looks good.

**Comment by timroster** [comment]
tested, working.
