### ISSUE TITLE
Intermittent 404 error on Kubernetes cluster in IBM CLOUD 

### ISSUE THREAD

**Issue by RavitejaSonti** [IBM-Cloud/terraform-provider-ibm#1513]
### Terraform Version
Terraform v0.11.10
+ * provider.ibm: version = "~> 0.22"

### Affected Resource(s)
-ibm_space

Seeing cluster not found issues intermittently while deploying updates to Kubernetes cluster

### Terraform Configuration Files
#----------------------------------------------------
# Clusters
#----------------------------------------------------

# Production

resource "ibm_container_cluster" "cluster_us_east" {
  name              = "${var.cluster_name}"
  datacenter        = "wdc04"
  default_pool_size = "${var.num_workers}"
  hardware          = "${var.hardware}"
  machine_type      = "${var.machine_type}"
  resource_group_id = "${data.ibm_resource_group.resource_group.id}"
  public_vlan_id    = "xxxx"
  private_vlan_id   = "xxxx
[error_log.zip](https://github.com/IBM-Cloud/terraform-provider-ibm/files/4711765/error_log.zip)

"
}

resource "ibm_container_cluster" "cluster_eu_de" {
  name            = "${var.cluster_name}"
  datacenter        = "fra04"
  default_pool_size = "${var.num_workers}"
  hardware          = "${var.hardware}"
  machine_type      = "${var.machine_type}"
  resource_group_id = "${data.ibm_resource_group.resource_group.id}"
  public_vlan_id    = "xxxx"
  private_vlan_id   = "xxxx"
}

# Sandbox

resource "ibm_container_cluster" "cluster_sandbox_us_east" {
  name            = "${var.sandbox_cluster_name}"
  datacenter        = "wdc06"
  default_pool_size = "3"
  hardware          = "${var.hardware}"
  machine_type      = "${var.machine_type}"
  resource_group_id = "${data.ibm_resource_group.resource_group.id}"
  public_vlan_id    = "xxxxx"
  private_vlan_id   = "xxxxx"
}

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
N/A

### Expected Behavior
No Errors. Changes to reflect on the without cluster not found error

### Actual Behavior
Build failure

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
We observe the behavior only when there is an update or add observed in the Terraform plan. And that to intermittently
 
### References
N/A

**Comment by Anil-CM** [comment]
Hello @RavitejaSonti, Can you please try with latest terraform provider  v0.29.0?

**Comment by RavitejaSonti** [comment]
@Anil-CM is it a known bug? do you have the fix in the suggested version?

**Comment by RavitejaSonti** [comment]
HI @Anil-CM, Do you have an update on the above query?

**Comment by hkantare** [comment]
@RavitejaSonti For status code 404 intermittent issue we don't have any fix but we have some retry the request on certain code like 502,520(which are intermittent) in the latest release

**Comment by hkantare** [comment]
From the error log I see the error is from the datasource can you share me your configuration

**Comment by RavitejaSonti** [comment]
Hi @hkantare, thanks for your response. I have already attached the config information, can u let me know what config you are looking for in specific

Configuration is available under Terraform Configuration Files

**Comment by RavitejaSonti** [comment]
Below is the DB configuration:

data "ibm_container_cluster" "cluster_us_east" {
--
  | cluster_name_id   = "bmng6qrw0ihn2a4k3ip0"
  | }
  |  
  | data "ibm_container_cluster" "cluster_eu_de" {
  | cluster_name_id   = "bmng6shf0jl7m2c635jg"
  | }
  |  
  | data "ibm_container_cluster" "cluster_sandbox_us_east" {
  | cluster_name_id   = "bp24863w0ekvs3pda1a0"
  | }
  |  
  | data "ibm_container_cluster_config" "cluster_config_us_east" {
  | cluster_name_id = "${data.ibm_container_cluster.cluster_us_east.id}"
  | config_dir      = "config/us-east"
  | }
  |  
  | data "ibm_container_cluster_config" "cluster_config_eu_de" {
  | cluster_name_id = "${data.ibm_container_cluster.cluster_eu_de.id}"
  | config_dir      = "config/eu-de"
  | }
  |  
  | data "ibm_container_cluster_config" "cluster_config_sandbox_us_east" {
  | cluster_name_id = "${data.ibm_container_cluster.cluster_sandbox_us_east.id}"
  | config_dir      = "config/sandbox/us-east"
  | }

**Comment by RavitejaSonti** [comment]
We are using default resource group

**Comment by RavitejaSonti** [comment]
@hkantare any update on the issue?

**Comment by RavitejaSonti** [comment]
@hkantare is there some suggestion to tweak the configuration to solve the issue?

**Comment by hkantare** [comment]
@RavitejaSonti Is it an intermittent issue or you facing everytime?
Can you paste me the output of clusters in your account

**Comment by RavitejaSonti** [comment]
It is a intermittent issue, build fails with below error:

Error: Error refreshing state: 1 error occurred:
	* data.ibm_container_cluster.cluster_eu_de: 1 error occurred:
	* data.ibm_container_cluster.cluster_eu_de: data.ibm_container_cluster.cluster_eu_de: Error retrieving cluster: Request failed with status code: 404, ServerErrorResponse: {"incidentID":"586fe36e84cf9fb2-IAD","code":"G0004","description":"The specified cluster could not be found. If applicable, make sure that you target the correct account and resource group.","type":"General","recoveryCLI":"To list the clusters you have access to, run 'ibmcloud ks cluster ls'. To list the resource groups that you have access to, run 'ibmcloud resource groups'. To target the resource group, run 'ibmcloud target -g \u003cresource_group\u003e'."}

**Comment by hkantare** [comment]
@RavitejaSonti Can you open a support ticket for IKS kubernetes with the error (incidentID":"586fe36e84cf9fb2-IAD",)
With the help of incident ID they will help with more details ....
Can you share me the o/p of the list of clusters using ibmcloud cli command

**Comment by RavitejaSonti** [comment]
Can you provide the channel for IKS kubernettes?

**Comment by hkantare** [comment]
From you UI IBM Cloud console...You can raise a support case

Can you share me the o/p from ibmcloud cli command
(ibmcloud ks clusters)

**Comment by RavitejaSonti** [comment]
i already raised the case with IBM Cloud.

**Comment by RavitejaSonti** [comment]
Name               ID                     State    Created        Workers   Location          Version        Resource Group Name   Provider
open-marketplace   bmng6shf0jl7m2c635jg   normal   7 months ago   5         Frankfurt         1.16.10_1533   Default               classic
open-marketplace   bmng6qrw0ihn2a4k3ip0   normal   7 months ago   15        Washington D.C.   1.16.10_1533   Default               classic
symposium          bp24863w0ekvs3pda1a0   normal   3 months ago   3         Washington D.C.   1.16.10_1533   Default               classic

**Comment by bhadrim** [comment]
I also have this issue. I am using terraform-provider-ibm_v0.26.0 and terraform-provider-ibm_v1.4.0. Though cluster is being deployed, resource refresh results in 404. This happens 4 out or 5 times off late.

```
ibm_container_cluster.kubecluster: Error waiting for workers of cluster (brfu5qid0gvmflnc6o2g) to become ready: Error retrieving workers for cluster: Request failed with status code: 404, ServerErrorResponse: {"incidentID":"5a0d872fd15f032b-IAD","code":"G0008","description":"The specified cluster could not be found by name. Provide the cluster ID instead.","type":"General","recoveryCLI":"To list all clusters you have access to, run 'ibmcloud ks cluster ls'."}
```

**Comment by hkantare** [comment]
@RavitejaSonti Did we get any update on IBM cloud case

**Comment by RavitejaSonti** [comment]
Hi @hkantare We are still waiting on a solution

**Comment by bhadrim** [comment]
Consistent 404 that I encountered day before might be related to some outage on IBM Cloud.

**Comment by hkantare** [comment]
closing the issue ..We have an issue fixed from armada API

**Comment by marifse** [comment]
> issue

I am facing the same issue again for few days, @hkantare can you help me to fix this, how did you fix it.

**Comment by hkantare** [comment]
@marifse 
Its a fix from back end API team from provider end their was no fix required. Can you rasie a support ticket for cluster.
