### ISSUE TITLE
Support for attaching volumes to Kubernetes workers

### ISSUE THREAD

**Issue by aaronmcohen** [IBM-Cloud/terraform-provider-ibm#1525]
Trying to automate the manual steps documented at https://cloud.ibm.com/docs/containers?topic=containers-utilities#vpc_api_attach with terraform. Based on current capabilities it does not look like this is feasible. Please enhance the current functionality to support automating these steps. 

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
> Terraform v0.12.26

### Affected Resource(s)
Please list the resources as a list:
- ibm_is_volume
- ibm_container_vpc_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

**Comment by hkantare** [comment]
We now support attaching the volumes to cluster worker nodes
resource "ibm_container_storage_attachment" "volume_attach"{
    volume = ibm_is_volume.storage.id
    cluster = ibm_container_vpc_cluster.cluster.id
    worker = data.ibm_container_vpc_cluster.cluster.workers[0]
}
