### ISSUE TITLE
No way of interconnecting two ibm cloud functions

### ISSUE THREAD

**Issue by itraveribon** [IBM-Cloud/terraform-provider-ibm#1526]
Hi there,

I am trying to make an IBM cloud function A to call another function B. For that, I have to give the URL of B as input parameter to the function A. However, I was not able to find a way to get this URL. In the UI of IBM Cloud this URL can be found under Cloud Functions / Actions / <name_of_function> / Endpoints. In this page we can see a box called REST API. Is there anyway to get this data (the URL and the API-Key) in terraform?

### Terraform Version
v0.12.25

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_function_action

### Terraform Configuration Files
Here I leave an example of I would like to do but I do not find the way:
```hcl
resource "ibm_function_action" "B" {
  name = "${ibm_function_package.package.name}/${var.actionName}"

  exec {
    kind = "itraveribon/ibmcloud"
    image = file("function_b.py")
  }
}

resource "ibm_function_action" "A" {
  name = "${ibm_function_package.package.name}/${var.actionName}"

  exec {
    kind = "itraveribon/ibmcloud"
    image = file("function_a.py")
  }
user_defined_parameters = <<EOF
  [
    {
        "key": "function_b_url",
        "value":"${ibm_function_action.B.??URL??}"
    },
 ]
  EOF
}
```

**Comment by movinglightspeed** [comment]
@hkantare Will there be a way to get an output of cloud functions endpoint url in terraform?

**Comment by anilkumarnagaraj** [comment]
Currently, Terraform doesn't provide an endpoint URL for the actions. In our next release, we will provide support for generating an action endpoint URL (HTTP Method).

**Comment by hkantare** [comment]
Now we exposed the `target_endpoint_url` attribute
https://cloud.ibm.com/docs/terraform?topic=terraform-function-resources#fn-action-output

Avaialble in latest releases v1.12.0 , 1.13.0
