### ISSUE TITLE
container_vpc_cluster fails for OCP VPC cluster with ALB error

### ISSUE THREAD

**Issue by seansund** [IBM-Cloud/terraform-provider-ibm#1528]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- data ibm_container_vpc_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

```
local {
  cluster_name = "xxx"
}

data "ibm_resource_group" "resource_group" {
  name = var.resource_group_name
}

data "ibm_container_vpc_cluster" "config" {
  count      = var.is_vpc ? 1 : 0

  cluster_name_id   = local.cluster_name
  alb_type          = "public"
  resource_group_id = data.ibm_resource_group.resource_group.id
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

```
module.dev_cluster.data.ibm_container_vpc_cluster.config[0]: Refreshing state...
 2020/06/04 04:02:50 Terraform apply | 
 2020/06/04 04:02:50 Terraform apply | Error: Error retrieving alb's of the cluster gsi-dev-ocp4-vpc-g2: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"59dec2b52055c189-IAD","code":"E3918","description":"This operation is not supported for your cluster's version.","type":"General"}
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

The configuration for the vpc cluster should have been retrieved

### Actual Behavior
What actually happened?

An error was returned

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- This is a similar error that was returned by the ibm_container_cluster on OCP when originally released #1083

**Comment by hkantare** [comment]
Can you let me know the IBM cloud terraform provider version?

**Comment by seansund** [comment]
v1.5.3. I can try again with v1.7.0

**Comment by hkantare** [comment]
I think we will have same issue with v1.7.0...The terraform support for ROKS on VPC is completely not available..In the last release we have enhanced the resources to support for ROKS on VPC..
In the next release we will fix the datasource (next week)

**Comment by hkantare** [comment]
Fixed in latest https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.7.1

**Comment by bparinas** [comment]
encountered the same error for terraform-provider-ibm v1.22.0

Error: Error waiting for ALBs in zone (dal12) of cluster (c1km5n7d0pn58scp1e60) to become ready: Error retrieving ALBs for cluster: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"63a905a9c33dd94e-HKG","code":"E3918","description":"This operation is not supported for your cluster's version.","type":"General"}

**Comment by hkantare** [comment]
I think its from container worker pool attachment resource for openshift can you set this parameter wait_till_albs=false

**Comment by bparinas** [comment]
changing the default true value to wait_till_albs=false fixed the issue. @hkantare thanks much!
