### ISSUE TITLE
Dynamic Rule returning wrong resource

### ISSUE THREAD

**Issue by argeiger** [IBM-Cloud/terraform-provider-ibm#1535]
### Terraform Version
Terraform v0.12.24
+ provider.ibm v1.7.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_iam_access_group_dynamic_rule

### Important Factoids
For the dynamic rule create, it is returning resourceIBMIAMAccessGroupMembersRead(d, meta).  This needs to be changed to resourceIBMIAMDynamicRuleRead

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_iam_access_group_dynamic_rule.go#L76

**Comment by hkantare** [comment]
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.7.1
