### ISSUE TITLE
Error received - Current user does not have access to team directory

### ISSUE THREAD

**Issue by argeiger** [IBM-Cloud/terraform-provider-ibm#1536]
### Terraform Version
Terraform v0.12.24
+ provider.ibm v1.7.0

### Affected Resource(s)
- "ibm_iam_access_group_dynamic_rule

### Terraform Configuration Files
```hcl
resource "ibm_iam_access_group_dynamic_rule" "rule1" {
  name              = "newrule"
  access_group_id   = "AccessGroupId-8810e2ce-7666-4f85-90fd-cc81721aa288"
  expiration        = 4
  identity_provider = "test-idp.com"
  conditions {
    claim    = "blueGroups"
    operator = "CONTAINS"
    value    = "cloudAdmin"
  }
  conditions {
    claim    = "lastName"
    operator = "CONTAINS"
    value    = "Fred"
  }
  conditions {
    claim    = "firstName"
    operator = "CONTAINS"
    value    = "Ted"
  }
}
```

### Debug Output
Error: Request failed with status code: 403, ServerErrorResponse: {"trace":"51891495311","errors":[{"code":9999,"message":"Current user does not have access to team directory.","more_info":" "}]}

The problem looks to be that function resourceIBMIAMAccessGroupMembersRead(..) that is returned from the function resourceIBMIAMDynamicRuleCreate utilizes the v1 version of the API instead of v2.  This needs to be switched to v2 otherwise you will get the error.  There might be other areas that in the code that should be checked for the proper version also.

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_iam_access_group_members.go#L140

### Expected Behavior
Apply to occur without err

### Actual Behavior
Error occurred 

### Steps to Reproduce
1. `terraform apply`

**Comment by hkantare** [comment]
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.7.1

**Comment by hkantare** [comment]
The resource and datasource of ibm_access_group_memebrs and ibm_access_group is using the v1 version of API to fetch all users added to an account

After investigation more we have an GetAccount users from User management  API
https://cloud.ibm.com/apidocs/user-management#get-users 

We need to update the resources to use this API.

**Comment by hkantare** [comment]
Fixed in latest release
