### ISSUE TITLE
OCP Cluster tagging issue

### ISSUE THREAD

**Issue by vikasprasad007** [IBM-Cloud/terraform-provider-ibm#1538]
Hi Team,

I'm trying to add tags inside provider.tf file and try to run Terraform script but I'm facing issue while executing terraform plan script.

**provider.tf sample---**
variable "ibmcloud_api_key" {}

provider "ibm" {
	ibmcloud_api_key    = var.ibmcloud_api_key
}

data "ibm_resource_group" "resource_group" {
	name = "acit-ds-resourceGroup"
}

resource "ibm_container_cluster" "ocp-cp4a-auto-ind" {
	name            = "ocp-cp4a-auto-ind"
	datacenter      = "dal10"
	machine_type    = "b3c.4x16"
	hardware        = "shared"
	kube_version      = "4.3_openshift"
	default_pool_size = 2
	public_service_endpoint  = "true"
	private_service_endpoint = "true"
	public_vlan_id    = "2714848"
	private_vlan_id    = "2711330"
	resource_group_id = data.ibm_resource_group.resource_group.id
	entitlement = "cloud_pak"
}

**Error**---
"stderr": "\u001b[31m\n\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mError waiting for initializing ingress hostname and secret: Error retrieving cluster: Request failed with status code: 404, ServerErrorResponse: {\"incidentID\":\"5a10a7126481e156-BOM\",\"code\":\"G0004\",\"description\":\"The specified cluster could not be found. If applicable, make sure that you target the correct account and resource group.\",\"type\":\"General\",\"recoveryCLI\":\"To list the clusters you have access to, run 'ibmcloud ks cluster ls'. To list the resource groups that you have access to, run 'ibmcloud resource groups'. To target the resource group, run 'ibmcloud target -g \\u003cresource_group\\u003e'.\"}\u001b[0m\n\n\u001b[0m  on provider.tf line 11, in resource \"ibm_container_cluster\" \"ocp-cp4a-auto-ind\":\n  11: resource \"ibm_container_cluster\" \"ocp-cp4a-auto-ind\" \u001b[4m{\u001b[0m\n\u001b[0m\n\u001b[0m\u001b[0m",

**Comment by vikasprasad007** [comment]
**provider.tf sample with tags---**

variable "ibmcloud_api_key" {}

provider "ibm" {
	ibmcloud_api_key    = var.ibmcloud_api_key
}

data "ibm_resource_group" "resource_group" {
	name = "acit-ds-resourceGroup"
}

resource "ibm_container_cluster" "ocp-cp4a-auto-ind" {
	name            = "ocp-cp4a-auto-ind"
	datacenter      = "dal10"
	machine_type    = "b3c.4x16"
	hardware        = "shared"
	kube_version      = "4.3_openshift"
	default_pool_size = 2
	public_service_endpoint  = "true"
	private_service_endpoint = "true"
	public_vlan_id    = "2714848"
	private_vlan_id    = "2711330"
	**tags = ["creator:MK","location:ind","team:Internal","type:demo","expiry:2020-07-10"]**
	resource_group_id = data.ibm_resource_group.resource_group.id
	entitlement = "cloud_pak"
}

**Comment by vikasprasad007** [comment]
Hello Team,

Same issue..

Tried below command:

terraform init -input=false
terraform plan -out=tfplan -input=false
terraform apply -input=false tfplan

**Comment by hkantare** [comment]
can you share me the complete log by enabling trace TF_LOG=debug

**Comment by hkantare** [comment]
Does the issue still exists?

**Comment by vikasprasad007** [comment]
Hello Team,

No now i'm able to set tag through terraform script.
We have specific requirement, we need to retrieve tag detail along with cluster detail, for retrieving cluster detail i'm using "https://containers.cloud.ibm.com/global/swagger-global-api/#/clusters/GetCluster" api.
________________________________

**Comment by hkantare** [comment]
Tags are  not specific to resources....We have general API which attach / detaches the tags to the services..
https://cloud.ibm.com/apidocs/tagging

So "https://containers.cloud.ibm.com/global/swagger-global-api/#/clusters/GetCluster" this api can't be used to get the tags.

**Comment by hkantare** [comment]
closing the issue
