### ISSUE TITLE
Terraform provider code is not running test case for resource_ibm_is_image in jenkins job

### ISSUE THREAD

**Issue by MalarvizhiK** [IBM-Cloud/terraform-provider-ibm#1541]
Jenkins job is missing test case for resource_ibm_is_image as it expects 2 environment variables:

export IMAGE_OPERATING_SYSTEM="red-7-amd64"
export IMAGE_COS_URL="cos://us-south/vnf-samples/rhel-guest-image-7.0-20140930.0.x86_64.qcow2"

Please run the test case for resource_ibm_is_image: resource_ibm_is_image_test.go. We can provide a RHEL7 qcow2 image. You can upload to COS bucket and run the test case in jenkins job.  

### Terraform Version
terraform v0.12

### Affected Resource(s)
-ibm_is_image

### Debug Output
crash.log:

---------------------------------------
2020/06/10 11:21:15 Terraform apply | panic: runtime error: invalid memory address or nil pointer dereference
 2020/06/10 11:21:15 Terraform apply | 2020-06-10T11:21:15.771Z [DEBUG] plugin.terraform-provider-ibm_v1.5.3: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19da54a]
 2020/06/10 11:21:15 Terraform apply | 2020-06-10T11:21:15.771Z [DEBUG] plugin.terraform-provider-ibm_v1.5.3: 
 2020/06/10 11:21:15 Terraform apply | 2020-06-10T11:21:15.771Z [DEBUG] plugin.terraform-provider-ibm_v1.5.3: goroutine 90 [running]:
 2020/06/10 11:21:15 Terraform apply | 2020-06-10T11:21:15.771Z [DEBUG] plugin.terraform-provider-ibm_v1.5.3: github.com/IBM-Cloud/terraform-provider-ibm/ibm.imgGet(0xc000896a10, 0x21827a0, 0xc00047a400, 0xc0004098f0, 0x29, 0x0, 0x0)
 2020/06/10 11:21:15 Terraform apply | 2020-06-10T11:21:15.771Z [DEBUG] plugin.terraform-provider-ibm_v1.5.3: 	/Users/anil/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_is_image.go:555 +0x8da
----------------------------------------------

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

[schematics_log_file.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/4763027/schematics_log_file.txt)

**Comment by MalarvizhiK** [comment]
I have sent the qcow2 image zip to @VaishnaviGopal 
Please unzip the image and upload the qcow2 image in COS bucket. I am unable to upload to defect, as it is more than 10MB.

**Comment by ankursri1** [comment]
@SukeshPrabhakar , request you to please look into this. This test case needs to be included in the Jenkins else it will break the things for VNF.

**Comment by VaishnaviGopal** [comment]
We have created a cosbucket in the alchemy test account with the custom image provided by Malar. Modifications are done in the data source of `is_image` test case file.
