### ISSUE TITLE
container_vpc_cluster fails for OCP VPC cluster with cloud object storage error

### ISSUE THREAD

**Issue by Lightning318** [IBM-Cloud/terraform-provider-ibm#1543]
### Terraform Version
```
Terraform v0.12.26
+ provider.ibm v1.7.1
```

### Affected Resource(s)
- `ibm_container_vpc_cluster`

### Terraform Configuration Files
```hcl
variable "ibmcloud_api_key" {}

provider "ibm" {
    ibmcloud_api_key = var.ibmcloud_api_key
    generation = 2
}

data "ibm_resource_group" "group" {
  name = "Default"
}

resource "ibm_is_vpc" "vpc" {
  name = "test"
}

resource "ibm_is_subnet" "subnet" {
  name                     = "test"
  vpc                      = ibm_is_vpc.vpc.id
  zone                     = "us-south-3"
  total_ipv4_address_count = 256
}

resource "ibm_resource_instance" "cos" {
  name              = "test"
  service           = "cloud-object-storage"
  plan              = "lite"
  location          = "global"
  resource_group_id = data.ibm_resource_group.group.id
}

resource "ibm_container_vpc_cluster" "cluster" {
  name              = "test"
  vpc_id            = ibm_is_vpc.vpc.id
  flavor            = "bx2-4x16"
  worker_count      = 2
  resource_group_id = data.ibm_resource_group.group.id
  kube_version      = "4.3_openshift"
  entitlement       = "cloud_pak"
  wait_till         = "IngressReady"

  zones {
    subnet_id = ibm_is_subnet.subnet.id
    name      = "us-south-3"
  }
}
```

### Debug Output
[Debug output gist](https://gist.github.com/Lightning318/6d1e68d61fccb8445d7e8c3060bf6c7d)

### Panic Output
None

### Expected Behavior
OCP cluster created

### Actual Behavior
Cluster creation returns an error 
> "Provide a standard cloud object storage instance CRN to back up the internal registry in your OpenShift on VPC Gen 2 cluster."
```
ibm_container_vpc_cluster.cluster: Creating...

Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"5a2031a8a166e6f8-EWR","code":"E7278","description":"Provide a standard cloud object storage instance CRN to back up the internal registry in your OpenShift on VPC Gen 2 cluster.","type":"Provisioning","recoveryCLI":"To list the CRN of your instances, run 'ibmcloud resource service-instances --long' and find the ID of your cloud object storage instance."}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
`ibm_container_vpc_cluster` has both a `crn` and `resource_crn` field but neither can be set

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? 
None found

**Comment by hkantare** [comment]
We are facing same issue with cli ibmcloud CLI tool also...We are checking with armada team

**Comment by hkantare** [comment]
```
Creating cluster...
FAILED
Provide a standard cloud object storage instance CRN to back up the internal registry in your OpenShift on VPC Gen 2 cluster. (E7278)

To list the CRN of your instances, run 'ibmcloud resource service-instances --long' and find the ID of your cloud object storage instance.
Incident ID: ee9d3db5-bd59-4856-a825-4d668dd5a3e2
```

**Comment by Lightning318** [comment]
Is there an update from the armada team regarding the issue in the CLI tooling?

**Comment by aaronmcohen** [comment]
Any news on this?

**Comment by hkantare** [comment]
@aaronmcohen We are making chnages from terraform side..It will be available in next release

**Comment by hkantare** [comment]
Fixed in latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.8.0
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/container_vpc_cluster.html.markdown

Cloud docs Docs will be updated shortly

**Comment by hkantare** [comment]
Example https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-cluster/vpc-gen2-cluster

**Comment by hkantare** [comment]
Fixed in latest releases

**Comment by jarrodu** [comment]
I am also running into this issue. I am using the current version of all tools.

**Comment by hkantare** [comment]
@jarrodu please share the log of error you are facing and smaple configuration file

**Comment by jarrodu** [comment]
Sure. When I get a minimal example, I will post it.

**Comment by jarrodu** [comment]
```bash
│ Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"a472f200-9dd3-46be-b601-f324a08162bd","code":"E7278","description":"Provide a standard cloud object storage instance CRN to back up the internal registry in your OpenShift on VPC Gen 2 cluster.","type":"Provisioning","recoveryCLI":"To list the CRN of your instances, run 'ibmcloud resource service-instances --long' and find the ID of your cloud object storage instance."}
│ 
│   with module.ks_cluster.ibm_container_vpc_cluster.cluster,
│   on cluster/main.tf line 5, in resource "ibm_container_vpc_cluster" "cluster":
│    5: resource ibm_container_vpc_cluster cluster {
```

So, I am trying to deploy in `eu-de`. The code I have works for `kube_version` of `1.25.4`, but not for `4.11.12_openshift`. It seems the only difference is that I am trying to deploy an OpenShift cluster instead of a normal Kubernetes cluster.

I am still working on a minimal example. As you can imagine, it is a bit expensive and time-consuming to spin up clusters. The code I have is for a work related project.

**Comment by jarrodu** [comment]
Perfect. Do you have any other documentation on the topic? 🙇

**Comment by jarrodu** [comment]
I had to create a new one.

```
resource "ibm_resource_instance" "cos_instance" {
  name              = local.prefix
  resource_group_id = data.ibm_resource_group.resource_group.id
  service           = "cloud-object-storage"
  plan              = "standard"
  location          = "global"
}
```

I am still not sure what this thing is, but it seems to create a `CRN` that works.

**Comment by hkantare** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-cluster/vpc-gen2-cluster/main.tf
you can find some sample example here
