### ISSUE TITLE
IKS VPC - Add/remove zones and workers without recreating the cluster

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1546]
Hi there,

### Terraform Version

Terraform v0.12.23
+ provider.ibm v1.7.1

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_vpc_cluster

### Expected Behavior
When modifying:

- `zones` property
- `worker_count` property

The cluster is updated

### Actual Behavior

The cluster is deleted and recreated.

**Comment by hkantare** [comment]
Presently we have update support on number of workers count attribute
worker_count but not for the zones attribute.

We will plan in the upcoming sprints

**Comment by ifs-pauljegouic** [comment]
Ok ! Nice to read that I will take this in account in our current design. Thanks for the feedback.

**Comment by ifs-pauljegouic** [comment]
Fixed. But will create for `machine_type`...
