### ISSUE TITLE
terraform import ibm_container_vpc_cluster not working

### ISSUE THREAD

**Issue by vincenthodicq** [IBM-Cloud/terraform-provider-ibm#1547]
Hi team,

I am trying to import existing resources into terraform. I have success on some but i am facing an error when importing my VPC (Gen 1) cluster.

### Terraform Version
Terraform v0.12.26
+ provider.ibm v1.7.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_vpc_cluster

### Terraform Configuration Files
```hcl
provider "ibm" {
  generation = 1
  region = var.region
  ibmcloud_api_key   = var.ibmcloud_api_key
}
resource "ibm_container_vpc_cluster" "cluster" {
  name              = var.cluster_name
  vpc_id            = ibm_is_vpc.vpc.id
  flavor            = var.flavor
  worker_count      = var.worker_count
  resource_group_id = ibm_resource_group.rg.id

  zones {
    subnet_id = ibm_is_subnet.subnet1.id
    name      = local.ZONE1
  }

  zones {
    subnet_id = ibm_is_subnet.subnet2.id
    name      = local.ZONE2
  }

  zones {
    subnet_id = ibm_is_subnet.subnet3.id
    name      = local.ZONE3
  }
}
```

### Debug Output
Terraform cannot found the cluster

### Panic Output
N/A

### Expected Behavior
Successful import of the cluster in terraforum

### Actual Behavior
What actually happened?
Error: Cannot import non-existent remote object.
I checked the cluster ID by IBM Cloud Dashboard or with ibmcloud CLI

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import ibm_container_vpc_cluster.cluster <CLUSTER_ID>`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1302

Issue is similar so I also try to add env var IC_RESOURCE_GROUP to the RG where the cluster is but same issue.

**Comment by hkantare** [comment]
can you share us the complete error by enabling TF_LOG=debug

IC_RESOURCE_GROUP did you set to the ID or the name of the resource group

**Comment by vincenthodicq** [comment]
I use name for IC_RESOURCE_GROUP.

I change to use ID instead of name and it is now working. This information must be displayed on the documentation to avoid the ticket that I opened :-)

**Comment by hkantare** [comment]
Now the user need not export IC_RESOURCE_GROUP for cluster..

terraform import ibm_container_vpc_cluster.cluster <CLUSTER_ID>
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
