### ISSUE TITLE
Documentation enhancement - Add a "Update requires" column 

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1554]
Hello there,

I think an awesome feature that could be added to your documentation and that lead us to continuous "re-thinking" of our design:

- Just add a column to the property list of resource. "Update requires".

- If the update of the property cause a replacement, inform "REPLACEMENT"
- if nothing, then "NOTHING".

We are using Terraform to manage the lifecycle of our infrastructure. Therefore, this information is really missing and cause a lot of frustration in my teams.

**Comment by hkantare** [comment]
We have an issue to track already on documentation side to add the label (force_new)
https://github.ibm.com/alchemy-writers/terraform/issues/41

**Comment by ifs-pauljegouic** [comment]
We cannot access it but I trust you ;) 

Any ETA regarding this ?

**Comment by hkantare** [comment]
I will update the ETA once I get information from doc team

**Comment by hkantare** [comment]
cloud docs updated with this attribute
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#instance-input

**Comment by hkantare** [comment]
closing the issue
