### ISSUE TITLE
Feature Request:- Terraform Resource for Multi-Vlan Firewall

### ISSUE THREAD

**Issue by utsav-r** [IBM-Cloud/terraform-provider-ibm#156]
Need Support for Creating/Updating/Deleting a Multi-Vlan Firewall in Softlayer via Terraform

**Comment by hkantare** [comment]
Can you please go ahead and raise PR.We will review and merge.

**Note:**
    

1. please add UAT
2. Take the latest code before rasing PR

**Comment by hkantare** [comment]
We have added support for multi-vlan..
