### ISSUE TITLE
Unable to deploy ROKS on VPC2

### ISSUE THREAD

**Issue by soumypau1** [IBM-Cloud/terraform-provider-ibm#1568]
Hello, 

We are unable to deploy ROKS cluster on VPC gen 2 using the example code provided. 
Apparently, the example needs plugin version 1.7.2. However, 1.7.2 release binary is not available. Building from the master branch also didnt help. 

### Terraform Version
terraform -v
Terraform v0.12.26
+ provider.ibm v1.7.1
+ provider.random v2.2.1

### Affected Resource(s)
Please list the resources as a list, for example:
* provider.ibm: version = "~> 1.7"
* provider.random: version = "~> 2.2"

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-cluster/roks-on-vpc-gen2
```

### Debug Output

terraform plan

Error: Unsupported argument

  on roks_on_vpc/roks_on_vpc.tf line 53, in resource "ibm_container_vpc_cluster" "cluster":
  53:   cos_instance_crn  = var.cos_instance_crn

An argument named "cos_instance_crn" is not expected here.

### Panic Output
NA

### Expected Behavior
Cluster is provisioned

### Actual Behavior
terraform plan fails ith error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
NA

### References
NA

**Comment by hkantare** [comment]
Its a know issue...https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1543
Its part of next release
