### ISSUE TITLE
Study compatibility with Terraform 0.13

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1569]
Hello there,

Since Terraform 0.13 will be release soon, I was wondering if you plan to test your current Terraform provider for the compatibility and fixes to be made to be compatible with 0.13.

Terraform 0.13 brings a lot of critical features for us (such as count, for_each, depends_on on module ...) so I would like to plan this migration be end Q3 or Q4 for our projects.

Do you have any plan regarding this ?

Regards,

**Comment by ifs-pauljegouic** [comment]
https://github.com/hashicorp/terraform/issues/25016

**Comment by hkantare** [comment]
We support Terraform v0.13  and registered with hashicorp 
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest
