### ISSUE TITLE
Feature-Request:- Support for Portable Storage in Block Storage

### ISSUE THREAD

**Issue by utsav-r** [IBM-Cloud/terraform-provider-ibm#157]
Hi,
We need support for Portable Storage in Block Storage. Currently we cant create/update/delete a Portable Storage in Block Storage in Softlayer via Terraform

**Comment by hkantare** [comment]
Can you please go ahead and raise PR.We will review and merge.

**Note:**

1. Please add UAT
2. Take the latest code before rasing PR

**Comment by hkantare** [comment]
currently we don't have portable storage in block Classic infrastructure so closing the issue
