### ISSUE TITLE
https://ibm-cloud.github.io/tf-ibm-docs/ points to 0.6.0 instead of the most recent 0.7.0

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#158]
would be better if https://ibm-cloud.github.io/tf-ibm-docs/ was always showing the latest and greatest release

**Comment by davetropeano** [comment]
Yes, we will be migrating the docs homepage to point to the most recent version always by next week.

**Comment by kskewes** [comment]
Looks like this has been done. `Readme.md`  fix here #201
