### ISSUE TITLE
Classic Virtual Server

### ISSUE THREAD

**Issue by suppix** [IBM-Cloud/terraform-provider-ibm#1592]
Hello

I can't find how to create with terraform Classic Virtual Server in IBM Cloud with some profile, ex. B1.1x2.
resource_ibm_compute_vm_instance accept only ram, cores and disk as parameters. Is it possible to define/apply some profile?

Thank you in advance

**Comment by hkantare** [comment]
Please use the attribute `flavor_key_name` instead of memory and cores to work with profiles
https://cloud.ibm.com/docs/terraform?topic=terraform-infrastructure-resources#vm

**Comment by suppix** [comment]
Thank you.
