### ISSUE TITLE
Doc says you need a CRN but here we reference an ID, which one is correct?

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#1621]
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/281bd6f3fc8d3e89e47506ea7f98b8ed4910d52a/examples/ibm-cos-bucket/main.tf#L33

**Comment by hkantare** [comment]
The id and the crn for activity tracker are same

**Comment by hkantare** [comment]
We have another field guid which is the just the unique identifier of the resource

**Comment by l2fprod** [comment]
but from a user point of view this is misleading as in other places in the provider we use `_id` as suffix when we need to pass a resource id. Here it says `_crn` so it is really `activity_tracker.crn` that I would expect. They might be the same value but for clarity we should use the right property.

**Comment by hkantare** [comment]
The ID and CRN are same for resource instances
