### ISSUE TITLE
ibm_compute_ssh_key - Error creating SSH Key: SoftLayer_Exception_Public: Access Denied.  (HTTP 401) - no classic key provided

### ISSUE THREAD

**Issue by bhadrim** [IBM-Cloud/terraform-provider-ibm#1628]
According to this page https://cloud.ibm.com/docs/iam?topic=iam-classic_keys, it says IBM API key can be used to access classic inrastructure. When I have only ibmcloud_api_key  in provider and use ibm_compute_ssh_key to set the key I get the following error

Error applying plan:1 error(s) occurred:
* ibm_compute_ssh_key.orpheus_public_key: 1 error(s) occurred:
* ibm_compute_ssh_key.orpheus_public_key: Error creating SSH Key: SoftLayer_Exception_Public: Access Denied.  (HTTP 401)
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

But when I add iaas_classic_username and iaas_classic_api_key I do not see any error. Are classic keys required to work with classic reosurces?

### Terraform Version
0.11.11

### Terraform Version

Tried on v0.26.0, v1.4.0 and v1.8.1

### Affected Resource(s)
Please list the resources as a list, for example:
ibm_compute_ssh_key

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "ibm" {
  ibmcloud_api_key = <key>
}

variable "public_ssh_key" {
  description = "Public SSH key used to connect to the virtual guest"
}

variable "datacenter" {
  description = "Softlayer datacenter where infrastructure resources will be deployed"
}

variable "hostname" {
  description = "Hostname of the virtual instance (small flavor) to be deployed"
  default     = "debian-small"
}

# This will create a new SSH key that will show up under the \
# Devices>Manage>SSH Keys in the SoftLayer console.
resource "ibm_compute_ssh_key" "orpheus_public_key" {
  label      = "my Public Key"
  public_key = "${var.public_ssh_key}"
}

variable "domain" {
  description = "VM domain"
}

# Create a new virtual guest using image "Debian"
resource "ibm_compute_vm_instance" "debian_small_virtual_guest" {
  hostname                 = "${var.hostname}"
  os_reference_code        = "DEBIAN_8_64"
  domain                   = "${var.domain}"
  datacenter               = "${var.datacenter}"
  network_speed            = 10
  hourly_billing           = true
  private_network_only     = false
  cores                    = 1
  memory                   = 1024
  disks                    = [25, 10, 20]
  user_metadata            = "{\"value\":\"newvalue\"}"
  dedicated_acct_host_only = false
  local_disk               = false
  ssh_key_ids              = ["${ibm_compute_ssh_key.orpheus_public_key.id}"]
}
```

### Debug Output
Error applying plan:1 error(s) occurred:
* ibm_compute_ssh_key.orpheus_public_key: 1 error(s) occurred:
* ibm_compute_ssh_key.orpheus_public_key: Error creating SSH Key: SoftLayer_Exception_Public: Access Denied.  (HTTP 401)
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by hkantare** [comment]
yes for Terraform we need to have iaas_classic_username and iaas_classic_api_key to work with  classic infrastructure resources

**Comment by bhadrim** [comment]
Thank you I will close the issue.
