### ISSUE TITLE
dns support with VPC load balancer

### ISSUE THREAD

**Issue by VaishnaviGopal** [IBM-Cloud/terraform-provider-ibm#1630]
Support for dns to generate a secondary domain with an SSL certificate for the host name of the VPC load balancer

https://cloud.ibm.com/docs/containers?topic=containers-vpc-lbaas&locale=it#vpc_lb_dns

**Comment by kavya498** [comment]
Available in latest releases
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_nlb_dns
Closing this issue 
Thanks.
