### ISSUE TITLE
Not able to provision COS with monitoring using terraform

### ISSUE THREAD

**Issue by umar201290** [IBM-Cloud/terraform-provider-ibm#1643]
Not able to provision COS with monitoring using terraform.

if i am using template https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-cos-bucket/main.tf

it gives me error .

Error: Unsupported block type

  on main.tf line 30, in resource "ibm_cos_bucket" "standard-ams03":
  30:  activity_tracking {

Blocks of type "activity_tracking" are not expected here.

Error: Unsupported block type

  on main.tf line 35, in resource "ibm_cos_bucket" "standard-ams03":
  35:   metrics_monitoring {

Blocks of type "metrics_monitoring" are not expected here.

**Comment by hkantare** [comment]
@umar201290 Which version of Terraform Provider you are using ..This feature is released in latest release v1.8.1 and v1.80

**Comment by umar201290** [comment]
Actually i updated to latest provider version before raising issue, but as you confirmed that it was released in latest version. I just cross checked and removed all older provider version files. 
It worked now, might be some reference to old version.

Thanks for help.
