### ISSUE TITLE
Resources destroyed on apply after import if resource_group specified

### ISSUE THREAD

**Issue by ileneruth** [IBM-Cloud/terraform-provider-ibm#1644]
### Terraform Version
Tried with 0.12.20 (currently used by IBM Cloud schematics) and 0.12.28

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_public_gateway
- ibm_is_subnet
- ibm_is_network_acl
- maybe more

ibm_is_vpn does **not** have this issue.

### Terraform Configuration Files
```resource "ibm_is_vpc" "main_vpc" {
  name = "${var.BASENAME}-vpc"
  resource_group = var.RESOURCE_GROUP
}

# Create a public gateway.  Attaching to subnet is done in the subnet definition.
# NOTE: At time of writing, terraform handling to attach after creation is broken.
resource "ibm_is_public_gateway" "public_gateway" {
# name = "${var.BASENAME}-gateway"
  name = "test-gateway"
  vpc = ibm_is_vpc.main_vpc.id
  zone = var.ZONE1
  resource_group = var.RESOURCE_GROUP

  timeouts {
     create = "90m"
  }
}

```
### Expected Behavior
No change (and certainly not a destroy) should happen on the public gateway on `terraform apply`

### Actual Behavior
On `terraform apply` forces replacement of public gateway due to resource_group being specified.  This does **not** happen with the vpc resource.  It **does** happen with subnet and network_acl.

` # ibm_is_public_gateway.public_gateway must be replaced
-/+ resource "ibm_is_public_gateway" "public_gateway" {
      ~ floating_ip             = {
          - "address" = "<redacted>"
          - "id"      = "<redacted>"
        } -> (known after apply)
      ~ id                      = "<redacted>" -> (known after apply)
        name                    = "test-gateway"
      ~ resource_controller_url = "https://cloud.ibm.com/vpc/network/publicGateways" -> (known after apply)
      ~ resource_crn            = "redacted" -> (known after apply)
      + resource_group          = "xxxxxxxxxxx<redacted<" # forces replacement
      + resource_group_name     = (known after apply)
      ~ resource_name           = "test-gateway" -> (known after apply)
      ~ resource_status         = "available" -> (known after apply)
      ~ status                  = "available" -> (known after apply)
      ~ tags                    = [] -> (known after apply)
        vpc                     = "<redacted>"
        zone                    = "us-east-1"

      ~ timeouts {
          + create = "90m"
        }
    }`

### Steps to Reproduce

1. Create a VPC, I've been using gen 1.  

2.  Create a public gateway or subnet using IBM Cloud CLI or GUI  Example: 
`ibmcloud is public-gateway-create test-gateway <vpc-id> <zone> --json`

3. Run `terraform init` to initialize terraform environment

4. Import the vpc  `terraform import ibm_is_vpc.main_vpc <vpc_id>`

5. Import the public gateway `terraform import ibm_is_public_gateway.public_gateway <public_gateway_id>`

6. Run `terraform plan`.  

See the destroy message on the public_gateway in the generated plan.

**Note** If I leave the resource_group property out of the terraform for the ibm_is_subnet resource, I don't get this error; however, the resource_group really does need to be specified to ensure that it is in the correct resource_group.

### Other Observations
If I look at the tfstate file after import, I can see that the resource_group fields didn't get imported properly for the affected resources.  They are set to null.  

In addition to resource_group, the ip_version field isn't imported for the ibm_is_subnet resource, so I have the same problem with that.  To workaround, I actually manually update the .tfstate file to set the fields that didn't import properly!

**Comment by hkantare** [comment]
Its because we see some API difference between gen1 and gen2 API....For gen1 resource-group is not a parameter while creating subnet or public gateway so we can't READ back the resource group to store in state file...

So please remove the resource_group from tf file..We will try to update docs  when the parameters is optional for (gen1/gen2)

**Comment by ileneruth** [comment]
Hello @hkantare - Does that mean that resource_group shouldn't even be in the schema?    I can remove it from the .tf files as long as these resources are created in the right resource_group when I use terraform to create them (vs. import.)

I have an even more difficult problem with ip_version on ibm_is_subnet.  When I do an import, this comes back as null in the tfstate file.  But, when I do a plan, it thinks it should be ipv4 which causes a destroy.  This field isn't documented and isn't in the .tf file at all.  Even when I added it and set it to ipv4 (which is correct value), it still wants to destroy the subnet because the .tfstate imported it as null.   I think the import should set it to ipv4.  I updated the tfstate file manually and this resolved the problem.

**Comment by hkantare** [comment]
yes resource_group should not be in the tf files for gen1 subnet and public gateway resources

Regarding this ip_version we need to remove from our schema we will make that changes as temporary work around you can add life_cycle block in subnet resource
```
resource "ibm_is_subnet" "subnet" { 
-----
---
lifecycle {
    ignore_changes = [
      ip_version,
    ]
  }
}
```

**Comment by ileneruth** [comment]
Thank you.  I will use this workaround for **ip_version**!  

You might check other resources for the **resource_group** problem.  I think it also occurs in ibm_is_network_acls.

**Comment by hkantare** [comment]
Removed the ip_version fixe din latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.9.0

**Comment by hkantare** [comment]
closing the issue
