### ISSUE TITLE
Taint config for ibm_container_worker_pool and ibm_container_cluster

### ISSUE THREAD

**Issue by alexandrsemak** [IBM-Cloud/terraform-provider-ibm#1646]
In latest ibmcloud CLI was added [Taint config for worker pool](https://cloud.ibm.com/docs/containers?topic=containers-cli-plugin-kubernetes-service-cli#worker_pool_taint_set).
Is it possible to add taint config to `ibm_container_cluster` and `ibm_container_worker_pool ` ?

**Comment by sh0m1** [comment]
And `ibm_container_vpc_worker_pool`

**Comment by mschenk42** [comment]
I am also looking to use this feature.

**Comment by Obihoernchen** [comment]
Any ETA?

**Comment by somaya10** [comment]
Also need this. We would love to have it via the provider, instead of manually adding it via `null_resource`
