### ISSUE TITLE
VPC autoscale support in vpc-gen2 resources

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#1650]
VPC Autoscale is available on request. 
Here are the docs - https://cloud.ibm.com/docs/vpc?topic=vpc-creating-auto-scale-instance-group

ibmcloud infrastructure/VPC infrastructure (is) plugin CLI also supports creation of instance group and instance template. So, expecting support for VPC autoscale in Terraform provider as well under VPC Gen 2 resources

**Comment by hkantare** [comment]
Feature support is released in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.12.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
