### ISSUE TITLE
CRN invalid when creating an encrypted data volume

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#1666]
## Terraform Version

Terraform v0.12.28
+ provider.ibm v1.8.1
+ provider.null v2.1.2
+ provider.template v2.1.2
### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_volumes

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Template is here: https://github.com/dprosper/byok_gen1_gen2

### Debug Output
```
Error: [DEBUG] Create volume err The CRN specified in the request is not valid.
{
    "StatusCode": 400,
    "Headers": {
        "Cache-Control": [
            "max-age=0, no-cache, no-store, must-revalidate"
        ],
        "Cf-Cache-Status": [
            "DYNAMIC"
        ],
        "Cf-Ray": [
            "5b0c1297cd3073cd-IAD"
        ],
        "Cf-Request-Id": [
            "03db69f2dc000073cd1a8a1200000001"
        ],
        "Connection": [
            "keep-alive"
        ],
        "Content-Length": [
            "291"
        ],
        "Content-Security-Policy": [
            "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ssl.google-analytics.com https://assets.zendesk.com https://connect.facebook.net; img-src 'self' https://ssl.google-analytics.com https://s-static.ak.facebook.com https://assets.zendesk.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://assets.zendesk.com; font-src 'self' https://themes.googleusercontent.com; frame-src https://assets.zendesk.com https://www.facebook.com https://s-static.ak.facebook.com https://tautt.zendesk.com; object-src 'none'"
        ],
        "Content-Type": [
            "application/json; charset=utf-8"
        ],
        "Date": [
            "Fri, 10 Jul 2020 17:40:56 GMT"
        ],
        "Expect-Ct": [
            "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
        ],
        "Expires": [
            "-1"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Referrer-Policy": [
            "no-referrer"
        ],
        "Server": [
            "cloudflare"
        ],
        "Set-Cookie": [
            "__cfduid=da9006d58d32e615391bc5c483868aa831594402855; expires=Sun, 09-Aug-20 17:40:55 GMT; path=/; domain=.iaas.cloud.ibm.com; HttpOnly; SameSite=Lax; Secure"
        ],
        "Strict-Transport-Security": [
            "max-age=31536000; includeSubDomains"
        ],
        "Transaction-Id": [
            "2cbbfb94b7b8563c882f035153851683"
        ],
        "Vary": [
            "Accept-Encoding"
        ],
        "X-Content-Type-Options": [
            "nosniff"
        ],
        "X-Frame-Options": [
            "DENY"
        ],
        "X-Request-Id": [
            "2cbbfb94b7b8563c882f035153851683"
        ],
        "X-Xss-Protection": [
            "1; mode=block"
        ]
    },
    "Result": {
        "errors": [
            {
                "code": "volume_crn_invalid",
                "message": "The CRN specified in the request is not valid.",
                "more_info": "https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-rias-error-messages#volume_crn_invalid",
                "target": {
                    "name": "",
                    "type": ""
                }
            }
        ],
        "trace": "2cbbfb94b7b8563c882f035153851683"
    },
    "RawResult": null
}
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
This script worked prior to version 1.8.1 of the provider

### Actual Behavior
What actually happened?

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
The same script in VPC Gen 2 results in NO errors, however the data volume created is provider managed, not encrypted.  My account is in the beta for VPC gen 2 encrypted volumes: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1673

**Comment by hkantare** [comment]
@dprosper Here the issue with the iam authorization policy as per your template 
```
resource "ibm_iam_authorization_policy" "policy" {
  source_service_name  = "server-protect"
  source_resource_group_id = data.ibm_resource_group.group.id
  target_service_name  = "kms"
  roles                = ["Reader"]
  target_resource_group_id = data.ibm_resource_group.group.id
}
```
or even with ibmcloud cli command
```
ic iam authorization-policy-create server-protect kms Reader  --source-resource-group-id a7a89ca48da04fb991a4ae687ed332a8 --target-resource-group-id a7a89ca48da04fb991a4ae687ed332a8
```
where we are providing both the source and target resource_group the policy is created as below
<img width="1008" alt="Screen Shot 2020-07-14 at 2 21 26 PM" src="https://user-images.githubusercontent.com/24930306/87405914-b1d21180-c5dd-11ea-91a0-0c68b0b2f181.png">


This policy is not getting authorized between the services
<img width="903" alt="Screen Shot 2020-07-14 at 2 30 43 PM" src="https://user-images.githubusercontent.com/24930306/87406664-a6331a80-c5de-11ea-8681-9518e286e963.png">


But when you create same authorization policy in UI using the resource groups for both services then the policy is created in this way
<img width="1033" alt="Screen Shot 2020-07-14 at 2 32 36 PM" src="https://user-images.githubusercontent.com/24930306/87406839-f01c0080-c5de-11ea-80f6-4a3c5f7cf088.png">


The policy is now getting authorized between services
<img width="850" alt="Screen Shot 2020-07-14 at 2 33 33 PM" src="https://user-images.githubusercontent.com/24930306/87406922-10e45600-c5df-11ea-8435-6095cc2d2e06.png">

**Comment by hkantare** [comment]
Can you raise an issue with iam policies or VPC team to understand why we see such difference between the policies

**Comment by hkantare** [comment]
For Gen2 still the feature is in beta we will provide the support once we have the SDK updated
https://github.com/IBM/vpc-go-sdk/

**Comment by dprosper** [comment]
That is interesting, thank you for the investigation.  I will confirm as well and open with IAM, This template has been used a number of times over the last 12 months (this version in github.com is an excerpt I did for the issue), so this must be a recent change that caused it to no longer work.

**Comment by jeunsscs** [comment]
Can we get an update for this? is there any other link that we need to monitor?

- IBM cloud support

**Comment by battbeach** [comment]
There is no recent changes related to the authorization policies. Please start with the team responsible with that service first. They should be able to provide the transaction ID for the success and failure cases so that we can further investigate.

**Comment by hkantare** [comment]
Can we close this issue?

**Comment by dprosper** [comment]
thanks @hkantare I believe this is now working. closing
