### ISSUE TITLE
VPC IKS workers upgrade should be optional

### ISSUE THREAD

**Issue by tpolekhin** [IBM-Cloud/terraform-provider-ibm#1681]
When upgrading IKS version via terraform it also replaces all worker nodes in the cluster to upgrade them to the specified master version as well. This is a destructive behavior that brings your entire cluster down for an upgrade period.

Upgrading workers together with the master upgrade should be optional
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_container_vpc_cluster.go#L475

**Comment by mschenk42** [comment]
I agree, the automatic upgrade for the workers needs to be optional.  There is no way we can run this on a production cluster, especially with stateful services that need some care when upgrading. Can we help add this functionality?  We have experienced Go developers that would like to help.

**Comment by hkantare** [comment]
@mschenk42 yes you can gohead and contribute may be we need to introduce a bool argument

**Comment by mschenk42** [comment]
Thanks, will do.  Currently testing change.  Will be submitting a PR soon.

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.9.0

**Comment by tpolekhin** [comment]
Fixed by #1694
