### ISSUE TITLE
ROKS gen2 example is missing public_gateway(s)

### ISSUE THREAD

**Issue by jeffhoek** [IBM-Cloud/terraform-provider-ibm#1687]
### Terraform Version
Using IBM Cloud Schematics with Terraform `v0.12.20`
```
provider.ibm: version = "~> 1.8"
```

### Affected Resource(s)
- ibm_container_vpc_cluster (4.3_openshift (gen2))
- ibm_is_public_gateway (missing)

### Terraform Configuration Files
ROKS Gen2 example here: https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-cluster/roks-on-vpc-gen2

### Expected Behavior
What should have happened?
Cluster should come up with full access to OpenShift web console

### Actual Behavior
What actually happened?
OpenShift web console is not available, Catalog items are not available, OperatorHub is not populated.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` the example.

### Important Factoids
N/A

### References
I have a fix and will post a pull request.

**Comment by hkantare** [comment]
Updated example
https://github.com/IBM-Cloud/terraform-provider-ibm/commit/f5e9d13a8cc68ce5525fdb1ddbd6e21ae5bb7757

**Comment by hkantare** [comment]
closing the issue
