### ISSUE TITLE
Spelling in VPC Load Balancer error message

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#1689]
> Error: Error while creating Load Balanacer err createLoadBalancerOptions failed validation

correct **Balanacer** to **Balancer**

**Comment by data-henrik** [comment]
twice in https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_is_lb.go

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.9.0

**Comment by hkantare** [comment]
closing the issue
