### ISSUE TITLE
ibm_is_lb_pool does not support HTTPS protocol

### ISSUE THREAD

**Issue by chanster** [IBM-Cloud/terraform-provider-ibm#1700]
Trying to use `https` protocol for `ibm_is_lb_pool` via terraform fails while provisioning from web console works.

### Terraform Version
Terraform v0.12.28

### Affected Resource(s)
- ibm_is_lb_pool

### Terraform Configuration Files
```hcl
resource "ibm_is_lb_pool" "my_pool" {
  name           = "my_pool"
  lb             = ibm_is_lb.my-lb.id
  algorithm      = "least_connections"
  protocol       = "https"

  health_type         = "tcp"
  health_delay        = 5
  health_retries      = 2
  health_timeout      = 2
  health_monitor_port = 9443

  session_persistence_type        = "source_ip"
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Allow `https` protocol

### Actual Behavior
```
Error: "protocol" must contain a value from []string{"http", "tcp"}, got "https"

  on main.tf line 993, in resource "ibm_is_lb_pool" "my_pool":
 993: resource "ibm_is_lb_pool" "my_pool" {
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
n/a

**Comment by hkantare** [comment]
Its fixed in latest releses
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_lb_pool
