### ISSUE TITLE
Terraform Crashes

### ISSUE THREAD

**Issue by Prajyot-Parab** [IBM-Cloud/terraform-provider-ibm#1701]
terraform apply results in crash on PowerVS - Washington and Dallas region.

### Terraform Version
`Terraform v0.12.20`

### Affected Resource(s)
- Multiple resources

### Panic Output
[crash.log](https://gist.github.com/Prajyot-Parab/2b3c45a3968f8d43a7286187296cc42c)

### Expected Behavior
What should have happened?
`terraform apply` command should have worked fine.

### Actual Behavior
What actually happened?
`terraform apply` command results in a crash.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
- Observed in Washington and Dallas region of PowerVS

```
Dallas
- ibmcloud_region     = "us-south"
- ibmcloud_zone       = "us-south"

Washington
- ibmcloud_region     = "us-east"
- ibmcloud_zone       = "us-east"
```

**Comment by Prajyot-Parab** [comment]
@surajsub ^^^

**Comment by surajsub** [comment]
Hmm - it should not crash.. do you have your key loaded on the service instance. I'll take a deeper look at it

**Comment by surajsub** [comment]
what resource are you trying to provision

**Comment by Prajyot-Parab** [comment]
> what resource are you trying to provision

We are trying to create VSI

**Comment by Prajyot-Parab** [comment]
> Hmm - it should not crash.. do you have your key loaded on the service instance. I'll take a deeper look at it

This works fine with London, Toronto regions so I believe the key part should be fine.

**Comment by yussufsh** [comment]
After looking at the crash logs found that the index out of bound error here: https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/data_source_ibm_pi_public_network.go#L71

```
panic: runtime error: index out of range [0] with length 0
2020-07-16T12:32:57.972Z [DEBUG] plugin.terraform-provider-ibm:
2020-07-16T12:32:57.972Z [DEBUG] plugin.terraform-provider-ibm: goroutine 43 [running]:
2020-07-16T12:32:57.972Z [DEBUG] plugin.terraform-provider-ibm: github.com/IBM-Cloud/terraform-provider-ibm/ibm.dataSourceIBMPIPublicNetworksRead(0xc0004ccaf0, 0x2284220, 0xc0002f7800, 0xc0004ccaf0, 0x0)
2020-07-16T12:32:57.972Z [DEBUG] plugin.terraform-provider-ibm:         /root/go/src/github.com/IBM-Cloud/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/data_source_ibm_pi_public_network.go:71 +0x2c3
```

This was failing because there were no public networks here. As a workaround I create a LPAR manually which creating the public network for me.

Feel that this should be taken care in the provider code to handle the failure when public network does not exist initially.
@surajsub

**Comment by surajsub** [comment]
The power instance does not create a public network when a new instance is created . The public network is created only when 1st pvm instance is created.. It's a chicken and egg problem. I will discuss with the power team.

**Comment by yussufsh** [comment]
Hi @surajsub 

Can we have something like a flag for public ip `pi_public_network` in pi_instance? Just like the Gen2 VSI?

**Comment by yussufsh** [comment]
Another suggestion is to create the public network if does not exist using `data_source_ibm_pi_public_network`.

**Comment by kavya498** [comment]
Fixed the crash..
Closing this issue.. Thanks
