### ISSUE TITLE
Add the capability to take snapshots of running VMs and make new boot images from it

### ISSUE THREAD

**Issue by rpsene** [IBM-Cloud/terraform-provider-ibm#1704]
As an user I would like to have the option to take snapshots of a running VM and launch new VMs from this. This is helpful when there is some security issue that should be fixed via update, when a base VM should be created for CICD, etc. 

This will remove the necessity to create a image in PowerVC and import it in PowerVS for any new change we do.

**Comment by surajsub** [comment]
Thanks - will evaluate

**Comment by drjeep** [comment]
This is crucial for autoscaling. The current (manual) process for creating VPC autoscale images makes it a non-starter.

**Comment by yussufsh** [comment]
You can now capture instances to image catalog and/or cos bucket. Fixed by https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3480.
See https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_capture for more details.
