### ISSUE TITLE
ibm_resource_instance forces a replacement on updates to parameters field

### ISSUE THREAD

**Issue by ashishth09** [IBM-Cloud/terraform-provider-ibm#1705]
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_resource_instance.go#L88.
I can very well update the memory, endpoints type etc. Why is it restricted?

**Comment by ashishth09** [comment]
I can see it has  https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_resource_instance.go#L403 function which can do the updates in-place so why destroy and create

**Comment by AnandPalani92** [comment]
Hi Team,

When i can expect this fix in IBM terraform provider plugin.

We need it soon and update the IBM resources on environment.

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
