### ISSUE TITLE
"pi_sys_type" Power systems resource fails when using "any" as the value

### ISSUE THREAD

**Issue by bpradipt** [IBM-Cloud/terraform-provider-ibm#1713]
Trying to use `any` for `pi_sys_type` as documented [here](https://cloud.ibm.com/docs/terraform?topic=terraform-power-vsi) results in the following error:
```
Error: Failed to provision {"description":"bad request: calculated parameter has failed for cloud-instance 69d558f6be0347ac8d8721bdfa1e259e: host group any does not exist: user's requested system type any is not available","error":"bad request"}
```

### Terraform Version
```
$ terraform -v
Terraform v0.12.20
+ provider.ibm (unversioned)
+ provider.ignition v1.2.1
+ provider.null v2.1.2
+ provider.random v2.3.0

Your version of Terraform is out of date! The latest version
is 0.12.28. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
- pi_sys_type

### Expected Behavior
The resource should have got created

### Actual Behavior
Resource creation failed with the following error:
```
Error: Failed to provision {"description":"bad request: calculated parameter has failed for cloud-instance 69d558f6be0347ac8d8721bdfa1e259e: host group any does not exist: user's requested system type any is not available","error":"bad request"}
```

**Comment by surajsub** [comment]
Power team changed the api spec to pass in only restricted values depending on the region like [s922,e880 or e980] - Any was removed. Please do not try any.

**Comment by bpradipt** [comment]
thanks @surajsub. Should the doc be updated ?

**Comment by kavya498** [comment]
Updated Docs https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_instance
thanks..
