### ISSUE TITLE
Broken link issue 

### ISSUE THREAD

**Issue by geethasm** [IBM-Cloud/terraform-provider-ibm#1714]
Hi,
Re: https://github.com/Cloud-Schematics/multitier-vpc-bastion-host
In Readme.md
The figure here illustrates the configuration of the VPC deployed by this example. For a detailed explanation of bastion host, ACL and security group configuration, please see the IBM Developer article Secure VPC access with a bastion host and Terraform. 
hyperlink is not working https://github.com/Cloud-Schematics/multitier-vpc-bastion-host/blob/master.

Hyperlink shows 404 error.
Regards,
Geetha

**Comment by hkantare** [comment]
its fixed now https://github.com/Cloud-Schematics/multitier-vpc-bastion-host
