### ISSUE TITLE
ibm_is_lb ignores dependency on required VPC subnet

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#1720]
I am trying to provision a gen2 VPC including a Load Balancer. The LB references the subnets but does not seem to catch the dependency. It results in an error:

> ibm_is_vpc.vpc: Creating...
> ibm_is_vpc.vpc: Still creating... [10s elapsed]
> ibm_is_vpc.vpc: Creation complete after 17s [id=r010-e134efb0-cade-4da2-9f85-72cc3be36f44]
> ibm_is_security_group_rule.cluster_inbound: Creating...
> ibm_is_vpc_address_prefix.subnet_prefix[0]: Creating...
> ibm_is_lb.lb: Creating...
> ibm_is_vpc_address_prefix.subnet_prefix[1]: Creating...
> ibm_is_vpc_address_prefix.subnet_prefix[2]: Creating...
> ibm_is_network_acl.network_acl: Creating...
> ibm_is_security_group_rule.cluster_inbound: Creation complete after 1s [id=r010-86a2e285-ca44-4406-9a33-6cb69225116d.r010-e61e8ab3-7bc4-4dd0-a3a0-99293ae62c4b]
> ibm_is_vpc_address_prefix.subnet_prefix[0]: Creation complete after 3s [id=r010-e134efb0-cade-4da2-9f85-72cc3be36f44/r010-1bf4926b-6303-4f7a-902c-1b6fa8cebdb9]
> ibm_is_network_acl.network_acl: Creation complete after 3s [id=r010-0f247623-a2c4-4036-836c-bd618ef66b36]
> ibm_is_vpc_address_prefix.subnet_prefix[2]: Creation complete after 3s [id=r010-e134efb0-cade-4da2-9f85-72cc3be36f44/r010-32775bde-7f6a-44fe-9372-9a5da9db7cfa]
> ibm_is_vpc_address_prefix.subnet_prefix[1]: Creation complete after 3s [id=r010-e134efb0-cade-4da2-9f85-72cc3be36f44/r010-fa663d98-938f-4e98-8037-375bebfecec6]
> ibm_is_subnet.subnet[1]: Creating...
> ibm_is_subnet.subnet[0]: Creating...
> ibm_is_subnet.subnet[2]: Creating...
> ibm_is_subnet.subnet[1]: Still creating... [10s elapsed]
> ibm_is_subnet.subnet[0]: Still creating... [10s elapsed]
> ibm_is_subnet.subnet[2]: Still creating... [10s elapsed]
> ibm_is_subnet.subnet[0]: Creation complete after 11s [id=02b7-27e64bc9-83d5-4bab-b669-2af40eb431ef]
> ibm_is_subnet.subnet[2]: Creation complete after 11s [id=02d7-6912ba0b-7d31-4a2f-9fae-d9c5e00d59b1]
> ibm_is_subnet.subnet[1]: Creation complete after 14s [id=02c7-da447f4f-dce4-4388-8d39-07781c5ebec0]
> 
> Error: Error while creating Load Balanacer err createLoadBalancerOptions failed validation:
> Key: 'CreateLoadBalancerOptions.Subnets' Error:Field validation for 'Subnets' failed on the 'required' tag
> null
> 
> 
>   on main.tf line 61, in resource "ibm_is_lb" "lb":
>   61: resource ibm_is_lb lb {
> 

### Terraform Version
**Terraform v0.12.28**

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_lb
- ibm_is_subnet

### Terraform Configuration Files
variables.tf:
```hcl

variable "ibmcloud_api_key" {}
variable "name" {}
variable "tags" {}
variable "resource_group_id" {}
variable "region" {}
variable "cidr_blocks" {}
variable "image_name" {
  default = "ibm-ubuntu-18-04-1-minimal-amd64-2"
}
variable "profile_name" {
  default = "cx2-2x4"
}

variable "iks_machine_type" {
  default = "bx2.4x16"
}

variable iks_worker_count {
  default = 3
}
variable iks_version {
  default = "1.17.7"
}

variable "ibmcloud_timeout" {
  description = "Timeout for API operations in seconds."
  default     = 900
}
```
main.tf:
```hcl
resource ibm_is_vpc vpc {
  name = var.name
  resource_group = var.resource_group_id
  address_prefix_management	= "manual"
  tags = concat(var.tags, [ "vpc" ])
}

resource ibm_is_vpc_address_prefix subnet_prefix {
  count = "3"

  name  = "${var.name}-prefix-zone-${count.index + 1}"
  zone  = "${var.region}-${(count.index % 3) + 1}"
  vpc   = ibm_is_vpc.vpc.id
  cidr  = element(var.cidr_blocks, count.index)
}

resource ibm_is_network_acl network_acl {
  name = "${var.name}-acl"
  vpc  = ibm_is_vpc.vpc.id
  resource_group = var.resource_group_id
  rules {
      name   = "egress"
      action = "allow"
      source      = "0.0.0.0/0"
      destination = "0.0.0.0/0"
      direction   = "outbound"
  }
  rules {
      name   = "ingress"
      action = "allow"
      source      = "0.0.0.0/0"
      destination = "0.0.0.0/0"
      direction   = "inbound"
  }
}

resource ibm_is_subnet subnet {
  count           = "3"

  name            = "${var.name}-subnet-${count.index + 1}"
  vpc             = ibm_is_vpc.vpc.id
  zone            = "${var.region}-${count.index + 1}"
  resource_group = var.resource_group_id
  ipv4_cidr_block = element(ibm_is_vpc_address_prefix.subnet_prefix.*.cidr, count.index)
  network_acl     = ibm_is_network_acl.network_acl.id
}


resource "ibm_is_security_group_rule" "cluster_inbound" {
  
  group = ibm_is_vpc.vpc.default_security_group
  direction = "inbound"
  remote = "0.0.0.0/0"
  tcp {
    port_min = 30000
    port_max = 32767
  }
}


resource ibm_is_lb lb {
  name    = "${var.name}-lb"
  subnets = ibm_is_vpc.vpc.subnets[*].id
  type = "public"
  resource_group = var.resource_group_id
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
terraform provider should detect dependency and provision resources in different order

### Actual Behavior
see log above, LB created before subnets

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by VaishnaviGopal** [comment]
Hello @data-henrik , the way `subnets` field is written in the creation of the load balancer is to be modified this way.

```
resource ibm_is_lb lb {
  name    = "${var.name}-lb"
  subnets = ibm_is_vpc.vpc.subnets.*.id
  type = "public"
  resource_group = var.resource_group_id
}
```

**Comment by data-henrik** [comment]
@VaishnaviGopal I had that syntax before and just retried it that way. Same error.

> ibm_is_vpc.vpc: Creating...
> ibm_is_vpc.vpc: Still creating... [10s elapsed]
> ibm_is_vpc.vpc: Creation complete after 16s [id=r010-964b018e-d6dd-4356-a8ea-eb28d44913ac]
> ibm_is_vpc_address_prefix.subnet_prefix[0]: Creating...
> ibm_is_vpc_address_prefix.subnet_prefix[1]: Creating...
> ibm_is_vpc_address_prefix.subnet_prefix[2]: Creating...
> ibm_is_security_group_rule.cluster_inbound: Creating...
> ibm_is_lb.lb: Creating...
> ibm_is_network_acl.network_acl: Creating...
> ibm_is_security_group_rule.cluster_inbound: Creation complete after 0s [id=r010-9021fae2-fc4b-4c04-bab3-c5addaa94831.r010-76636745-2f8b-4d1c-a842-4c70e5429dd2]
> ibm_is_vpc_address_prefix.subnet_prefix[0]: Creation complete after 2s [id=r010-964b018e-d6dd-4356-a8ea-eb28d44913ac/r010-4df37b70-d2a3-490e-9d1e-1aa177a5bf6d]
> ibm_is_network_acl.network_acl: Creation complete after 4s [id=r010-891aaca9-bcca-4140-a379-5b325cafa15b]
> ibm_is_vpc_address_prefix.subnet_prefix[1]: Creation complete after 5s [id=r010-964b018e-d6dd-4356-a8ea-eb28d44913ac/r010-8dbf424d-b70a-46c6-b72a-d90b84272384]
> ibm_is_vpc_address_prefix.subnet_prefix[2]: Creation complete after 5s [id=r010-964b018e-d6dd-4356-a8ea-eb28d44913ac/r010-09e64b96-cb61-4050-8ada-6681bd224c50]
> ibm_is_subnet.subnet[0]: Creating...
> ibm_is_subnet.subnet[1]: Creating...
> ibm_is_subnet.subnet[2]: Creating...
> ibm_is_subnet.subnet[0]: Still creating... [10s elapsed]
> ibm_is_subnet.subnet[1]: Still creating... [10s elapsed]
> ibm_is_subnet.subnet[2]: Still creating... [10s elapsed]
> ibm_is_subnet.subnet[2]: Creation complete after 10s [id=02d7-d167eca4-ba86-4c6a-896c-7dbe9db333bf]
> ibm_is_subnet.subnet[1]: Creation complete after 10s [id=02c7-bb0992ab-9548-4f6b-aa26-53b745ebbc4d]
> ibm_is_subnet.subnet[0]: Creation complete after 12s [id=02b7-a8eddcbd-da99-4fcf-a930-413d0ccce8dc]
> 

Error: Error while creating Load Balanacer err createLoadBalancerOptions failed validation:
Key: 'CreateLoadBalancerOptions.Subnets' Error:Field validation for 'Subnets' failed on the 'required' tag
null


  on main.tf line 61, in resource "ibm_is_lb" "lb":
  61: resource ibm_is_lb lb {

**Comment by VaishnaviGopal** [comment]
Subnets are attached to the lb from the `subnet` resource to avoid any errors while creation and deletion.
 
```
resource ibm_is_lb lb {
  name    = "${var.name}-lb"
  subnets = ibm_is_subnet.subnet.*.id
  type = "public"
  resource_group = var.resource_group_id
}
```

**Comment by data-henrik** [comment]
Ok, referencing it that way solves it. I am closing it. Is it documented?

**Comment by VaishnaviGopal** [comment]
Documentation is available [here](https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#lb).

**Comment by data-henrik** [comment]
well, I know that page - I was more thinking regarding referencing ibm_is.vpc.subnets vs. ibm_is_subnet directly to configure the LB

**Comment by VaishnaviGopal** [comment]
Documentation can't be done because this is specific to a particular template. It depends on how users writes the template and what kind of resource combination he/she is using.
