### ISSUE TITLE
IBM Container VPC Cluster with no default worker pool crashes on destroy

### ISSUE THREAD

**Issue by evpirnia** [IBM-Cloud/terraform-provider-ibm#1733]
[Archive.zip](https://github.com/IBM-Cloud/terraform-provider-ibm/files/4962439/Archive.zip)

Goal: Create a VPC Cluster with no default worker pool. I want to make my own worker pools. 

Both the IBM Cloud CLI and UI allow me to delete the default worker pool and make my own worker pools. I tried to automate this task in terraform using the IBM Cloud terraform provider.

Attached you will find an archive of my code that performs the following actions:
- Create a vpc cluster (a default worker pool will automatically be created as well)
- Create an additional worker pool 
- Delete the default worker pool (in a null resource local-exec provisioner)

I am able to plan and apply. However, when I try to `terraform destroy`, terraform crashes (see `destroy.log` in archive). 

The crash references the below function.
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/f9566a20835a1515b56bb499dd1d1c4d4efe0145/ibm/resource_ibm_container_vpc_cluster.go#L605

Please note that I am using terraform v0.12.28 and the IBM Cloud terraform provider v1.8.1.

**Comment by hkantare** [comment]
We fixed the issue to fix the nil pointer exception when the default worker pool is removed
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/1763

We added some check to exists the element exists and read the value
The fix is available in master branch..It will be part of the next release

**Comment by evpirnia** [comment]
Thank you @hkantare !!

**Comment by evpirnia** [comment]
Merged, closing! :D
