### ISSUE TITLE
Plan for ibm_certificate_manager_import results in a a change every time it runs

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#1744]
Every time I run plan after importing the certificate in CM, the plan comes back with modification to the content and an add for the priv_key

![image](https://user-images.githubusercontent.com/11874942/88333213-da54bc80-ccfd-11ea-9eab-c6a0e53e8ae6.png)

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
$ terraform -v
Terraform v0.12.26
+ provider.ibm v1.8.1
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.tls v2.1.1

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_certificate_manager_import

### Terraform Configuration Files
```hcl
resource "tls_private_key" "ca" {
  algorithm   = "RSA"
}

variable ca_cert_validity_period_days {
  default     = 3660
  description = "ca certificate validity, in days"
}

variable ca_cert_early_renewal_days {
  default     = 180
  description = "ca early certificate renewal, in days"
}


resource "tls_self_signed_cert" "ca" {
  key_algorithm         = "RSA"
  private_key_pem       = tls_private_key.ca.private_key_pem
  validity_period_hours = var.ca_cert_validity_period_days * 24
  early_renewal_hours   = var.ca_cert_early_renewal_days * 24
  is_ca_certificate     = true

  allowed_uses = ["digital_signature", "cert_signing", "key_encipherment"]

  dns_names = ["example.com"]

  subject {
    common_name = "example.com"
    organization = "Example"
  }
}

resource "ibm_certificate_manager_import" "cert" {
  certificate_manager_instance_id =  var.cm_id
  name                            = "tls-ca-tf"
  description="string"
  data = {
    content = tls_self_signed_cert.ca.cert_pem
    priv_key = tls_private_key.ca.private_key_pem
    intermediate = ""
  }
}
```

### Expected Behavior
What should have happened?
Plan should run with no changes to the resource unless there was really a change. 

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

**Comment by dprosper** [comment]
I upgraded the version of Terraform and the provider ...

$ terraform -v
Terraform v0.12.29
+ provider.ibm v1.9.0
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.tls v2.1.1

... and I get the same result as above.

**Comment by dprosper** [comment]
It looks is ibm_certificate_manager_import is checking for the existence of the resource in CM prior to determining what to do... i.e. if I delete the key from CM, it recognizes that the key is gone and simply wants to add it back, but if the key already exist it wants to change it everytime ... that seems to be a different behavior when compared to other resources in the provider, the other resources seems to only check the Terraform state.

**Comment by kavya498** [comment]
Hi,
I see that the plan is not modifying content and private key.
It is trying to add the intermediate="". 
This is because we are not setting empty values in the state file..As, it doesn't find intermediate attribute in the state file, the plan plan is trying to add..

You can just skip sending empty values in the payload, then plan will not come back with diff..

We are trying to add a validator that validates all non empty values in the payload..

**Comment by dprosper** [comment]
that worked thank you, feel free to close unless you need to track the validates.

**Comment by hkantare** [comment]
closing the issue based on above comments
