### ISSUE TITLE
Datasource support for VPC public gateway

### ISSUE THREAD

**Issue by VaishnaviGopal** [IBM-Cloud/terraform-provider-ibm#1745]
Support for VPC Public gateway data source in the provider.

**Comment by arjunsbabu** [comment]
I have read like its only possible to have 1 Public gateway per zone. What is the best way fetch the same using terraform for subnet creation inside a vpc

**Comment by hkantare** [comment]
We have datasource to read a public gateway
https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-data-sources#public-gwy-g2
