### ISSUE TITLE
ibm_container_vpc_worker_pool resource forces a replace if resource_group_id not set

### ISSUE THREAD

**Issue by mschenk42** [IBM-Cloud/terraform-provider-ibm#1748]
With the latest release `1.9` the `ibm_container_vpc_worker_pool` resource will require replacement if the resource group id is not set.  The reason for this is the reading and setting of the resource_group_id on the worker pool.

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_container_vpc_worker_pool.go#L317-L330

Currently the resource_group_id is optional.  Not sure what the best approach to fixing this. Maybe the resource_group_id should be required? 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_container_vpc_worker_pool.go#L89

**Comment by hkantare** [comment]
I think the resource_group_id should be both optional and computed...We will update the fix

**Comment by hkantare** [comment]
As a temporary workaround you can add the life_cycle block with ignore_changes
```
lifecycle {
    ignore_changes = [
      resource_group_id,
    ]
  }
}
```

**Comment by hkantare** [comment]
Fixed in latest releases
