### ISSUE TITLE
ibm_container_vpc_cluster recreated on update machine_type

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1755]
Hi there,

### Terraform Version

Terraform v0.12.23
+ provider.ibm v1.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_vpc_cluster

### Expected Behavior
When modifying:

- `machine_type` property

The cluster is updated

### Actual Behavior

The cluster is deleted and recreated.

**Comment by hkantare** [comment]
Yes its working as per API..We don't have any update API where we can update the machine types of the workers once the cluster is created..
https://cloud.ibm.com/apidocs/kubernetes

**Comment by ifs-pauljegouic** [comment]
OK I will then submit a request to IKS team to have the ability to change the flavor of a workerpool, especially the `default`, without having to recreate it.

Thanks for the feedback 👍

**Comment by ifs-pauljegouic** [comment]
IBM Support Ticket: CS1905737

**Comment by hkantare** [comment]
closing the issue since its behind the scope of provider to support change of flavor
