### ISSUE TITLE
Feature Request: Support `HTTP_COOKIE` for ibm_lbaas `session_stickiness` parameter

### ISSUE THREAD

**Issue by cbrune-signal** [IBM-Cloud/terraform-provider-ibm#1757]
It would be *nice* to support the `HTTP_COOKIE`  option for ibm_lbaas `session_stickiness` parameter.

### Terraform Version
`Terraform v0.12.24`

### Affected Resource(s)
- ibm_lbaas

### Expected Behavior
According to the Softlayer API, one should be able to specify `HTTP_COOKIE` for the `session_stickiness` parameter.
See [Softlayer API](https://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_LBaaS_LoadBalancerProtocolConfiguration/)

### Actual Behavior
Terraform errors out with:
```
Error: "protocols.0.session_stickiness" must contain a value from []string{"SOURCE_IP"}, got "HTTP_COOKIE"
```

### Steps to Reproduce
1. Create a `ibm_lbaas` configuration with a protocol section like:
```
  protocols {
    frontend_protocol     = "HTTPS"
    frontend_port         = 443
    tls_certificate_id    = var.api_ssl_certificate_id
    backend_protocol      = "HTTP"
    backend_port          = 7072
    load_balancing_method = "round_robin"
    session_stickiness    = "HTTP_COOKIE"
}
```

**Comment by kavya498** [comment]
Avalable in [1.21.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.21.0)
