### ISSUE TITLE
Allow configuration of the key used to encrypt IBM Cloud Databases backups

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#1761]
Currently only the key used to encrypt the database can be specified:

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/cf43312d2164261828ea7877c3a294d1ff278e77/ibm/resource_ibm_database.go#L176

but ICD also supports providing the key to encrypt backups as described in https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-key-protect#byok-for-backups

Today it is not possible and I end up having only the data but not the backup being encrypted with my own key:

![image](https://user-images.githubusercontent.com/12746550/88728472-706e5580-d0f7-11ea-9ad1-78fa152f7194.png)

**Comment by movinglightspeed** [comment]
Also another issue on this
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1727

**Comment by hkantare** [comment]
Fixed in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.11.1

**Comment by l2fprod** [comment]
@hkantare there is a naming inconsistency in the newly added key:

![image](https://user-images.githubusercontent.com/12746550/91874324-b317d600-ec3f-11ea-8c9f-bafedf7039e3.png)

- notice "key_protect_key" for the disk encryption pointing to a `crn`.
- And then "backup_encryption_key_crn" for the backup encryption, this one has "crn" in its name. Not very consistent with the other one.
- Also the doc for "key_protect_instance" does not say if this instance will be used to look for the backup encryption key. Is this instance needed at all given we have the crn for the key?

**Comment by kavya498** [comment]
Hi,
`key_protect_instance ` is not required.. crn for the key i.e `backup_encryption_key_crn` parameter is good enough for icd backup encryption..

`backup_encryption_key_crn` parameter name is chosen from [docs](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-provisioning#list-of-additional-parameters).

`key_protect_key` support was introduced long back in terraform, we see some updates from icd api..
we'll work on the consistency of parameters and update soon.

**Comment by l2fprod** [comment]
@kavya498 

I tried the new backup_encryption_key_crn and the Redis instance I wanted to create stayed in "Provisioning" for hours before failing. I use the same key for both db encryption and backup encryption.

After I removed the backup_encryption_key_crn I could create a Redis instance

**Comment by l2fprod** [comment]
here is a terraform template that fails to provision a Redis database:

```hcl
variable ibmcloud_api_key {}
variable basename { default="redis-failed"}
variable resource_group_name {}
variable region { default = "us-south" }

provider "ibm" {
  ibmcloud_api_key = var.ibmcloud_api_key
  region           = var.region
  generation       = 2
  ibmcloud_timeout = 900
}

data ibm_resource_group group {
  name = var.resource_group_name
}

resource ibm_resource_instance kms {
  name              = "${var.basename}-kms"
  resource_group_id = data.ibm_resource_group.group.id
  service           = "kms"
  plan              = "tiered-pricing"
  location          = var.region
}

resource ibm_kp_key key {
  key_protect_id = ibm_resource_instance.kms.guid
  key_name       = "root_key"
  standard_key   = false
  force_delete   = true
}

resource ibm_database redis {
  name              = "${var.basename}-redis"
  resource_group_id = data.ibm_resource_group.group.id
  plan              = "standard"
  service           = "databases-for-redis"
  location          = var.region

  key_protect_key           = ibm_kp_key.key.crn
  key_protect_instance      = ibm_resource_instance.kms.crn
  backup_encryption_key_crn = ibm_kp_key.key.crn

  service_endpoints = "private"

  depends_on = [
    ibm_iam_authorization_policy.redis_policy
  ]
}

resource ibm_iam_authorization_policy redis_policy {
  source_service_name         = "databases-for-redis"
  target_service_name         = "kms"
  target_resource_instance_id = ibm_resource_instance.kms.guid
  roles                       = ["Reader"]
}
```
