### ISSUE TITLE
Cant find any resource definition for RabbitMQ

### ISSUE THREAD

**Issue by vinchauhan** [IBM-Cloud/terraform-provider-ibm#1762]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- I am looking to create rabbitmq resource as below but no luck , the document is not clear for RabbitMq resource.
```
resource "ibm_resource_instance" "rabbitmq_instance" {}
```

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by hkantare** [comment]
The rabbitmq_instance can be provisioned using two ways
1)Using ibm_resource_instance where the user needs to pass additional parameters (like memory disks,...so on parameters)
https://cloud.ibm.com/docs/terraform?topic=terraform-resource-mgmt-resources#rg
resource "ibm_resource_instance" "rabbitmq" {
name = "test"
service = "messages-for-rabbitmq"
plan = "standard"
location = "us-south"
parameters = {
members_memory_allocation_mb = "XXX"
members_disk_allocation_mb = "XXX"
-----
}
----
}

2) Using ibm_database resource
```
resource "ibm_database" "<your_database>" {
  name              = "<your_database_name>"
  plan              = "standard"
  location          = "us-south"
  service           = "messages-for-rabbitmq"
  resource_group_id = data.ibm_resource_group.group.id
  tags              = ["tag1", "tag2"]

  adminpassword                = "password12"
  members_memory_allocation_mb = 3072
  members_disk_allocation_mb   = 61440
  users {
    name     = "user123"
    password = "password12"
  }
  whitelist {
    address     = "172.168.1.1/32"
    description = "desc"
  }
}
```

**Comment by hkantare** [comment]
closing the issue
