### ISSUE TITLE
Feature Request: CIS Domain setting: Range for Apps

### ISSUE THREAD

**Issue by movinglightspeed** [IBM-Cloud/terraform-provider-ibm#1766]
Hi,

I would like to see CIS Range for Apps setting enabled or added. They work with existing domains attached to the CIS instance and is a needed for a client I"m working with.

### Terraform Version
The latest CIS for terraform doesnt have it
https://cloud.ibm.com/docs/terraform?topic=terraform-cis-resources&locale=en

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_compute_instance
- ibm_storage_file

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
ibm_cis
```

### Expected Behavior
What should have happened?
Ibm_cis_range added or included in ibm_cis_domain or ibm_cis_domain_settings

### Actual Behavior
What actually happened?
No way to create cis range through terraform

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by movinglightspeed** [comment]
@KumarGanesanIBM Thanks for following up, that feature appears to import a read only copy of an existing range configuration in CIS. I'd like to be able to create range settings directly from terraform, using the wealth of arguments found from the gui. This appears to only import an unmodifiable range config created in the ibm cloud gui. Looking forward to your response.

**Comment by KumarGanesanIBM** [comment]
@movinglightspeed 
You can also manage the range settings.  Please check [this link](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cis_range_app)

**Comment by KumarGanesanIBM** [comment]
@movinglightspeed 
I hope, you are using Range APP terraform support. 
Please let me know, whether I can close this issue.
Thanks,
KumarG

**Comment by movinglightspeed** [comment]
I haven't had a chance to test it, been so busy. I've looked at the link and it looks like that does exactly what I was referring to and was hoping to have earlier this year. 

Thank you, you can close this out Kumar.

**Comment by KumarGanesanIBM** [comment]
👌
