### ISSUE TITLE
Create resource instance fails if the instance is still provisioning.

### ISSUE THREAD

**Issue by vinchauhan** [IBM-Cloud/terraform-provider-ibm#1767]
### Terraform Version
Terraform v0.12.26

### Terraform Configuration Files
```hcl
resource "ibm_resource_instance" "rabbitmq" {
    name = "test-rabbit-mq"
    service = "messages-for-rabbitmq"
    plan = var.standard
    location = var.region
    resource_group_id = data.ibm_resource_group.group.id
    parameters = {
        members_memory_allocation_mb = "3072"
        members_disk_allocation_mb = "3072"
    }
    timeouts {
        create = "15m"
        update = "15m"
        delete = "15m"    
    }
}
```

### Panic Output
```
ibm_resource_instance.rabbitmq: Creating...
ibm_resource_instance.rabbitmq: Still creating... [10s elapsed]

Error: Error waiting for create resource instance (crn:v1:bluemix:public:messages-for-rabbitmq:us-south:a/<resource-Id>::) to be succeeded: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)

  on messaging.tf line 1, in resource "ibm_resource_instance" "rabbitmq":
   1: resource "ibm_resource_instance" "rabbitmq" {
```

### Expected Behavior
I was considering the timeout will allows terraform to not check for the resource status soon enough and it wouldnt fail on provisioning status.

### Actual Behavior
Resource get created but the terraform apply command fails with the above error.
There should be an option to not fail on resource status 'provisioning'

**Comment by kavya498** [comment]
kindly use `ibm_database` resource instead of `ibm_resource_instance`
This should resolve the issue..

Closing this issue.. Kindly open new issue if you still encounter this error..
Thanks.
