### ISSUE TITLE
Feature request: Support vpc network load balancer

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#1796]
See https://github.ibm.com/NetworkTribe/NLB/issues/265 

There is current support for the VPC application load balancer (HTTP) https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#lb

Hopefully the VPC Network Load Balancer can be feathered in with little change to the terraform configuration files.  https://cloud.ibm.com/docs/vpc?topic=vpc-network-load-balancers

**Comment by hkantare** [comment]
Feature is available in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
