### ISSUE TITLE
IBM_Storage_Block not returning data as expected

### ISSUE THREAD

**Issue by surajsub** [IBM-Cloud/terraform-provider-ibm#180]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:

- ibm_storage_file

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```


variable "datacenter" {
	description = "Target vSphere datacenter for Virtual Machine creation"
}


variable "iops" {
	description = "IOPS for the storage"
	
	
	}


variable "size" {
	description = "Size of the storage"
	
	
	}


provider ibm {} 

resource "ibm_storage_block" "test1" {
        type = "Endurance"
        datacenter = "${var.datacenter}"
        capacity = "${var.size}"
        iops = "${var.iops}"
        os_format_type = "Linux"
        allowed_ip_addresses =["10.155.72.75", "10.155.72.127"]

        
}

output "hostname" {
  value = "${ibm_storage_block.test1.hostname}"
}
output "storageId" {
value = "${ibm_storage_block.test1.id}"
}
output "volumename" {
  value = "${ibm_storage_block.test1.volumename}"
}
output "allowed_virtual_guest_info" {
  value = "${ibm_storage_block.test1.allowed_virtual_guest_info}"
}

```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
As per the provider documentation , it should return the allowed_virtual_guest_info data back in the provider output 
### Actual Behavior
allowed_virtual_guest_info returns a null array

**Comment by hkantare** [comment]
Looking into the issue will update with findings

**Comment by hkantare** [comment]
The fix is now available in master branch. We added `allowed_host_info`to store the user name, password, and host IQN of the hosts with access to the storage. Now this attribute holds the information however we provide access by virtualguest id, baremaetal id or ip address.

**Comment by surajsub** [comment]
So if i request a storage , this should be returned as part of the response ( username, password and host IQN) correct. Is there anything else that i need to do to authorize the storage so that it can be used in my downstream calls ?

**Comment by hkantare** [comment]
If you request the storage without ` allowed_ip_addresses ` ,` allowed_hardware_ids ` or  ` allowed_virtual_guest_ids ` then `allowed_host_info` will be empty.Here we are not authorize any device to storage.
```
resource "ibm_storage_block" "test1" {
        type = "Endurance"
        datacenter = "${var.datacenter}"
        capacity = "${var.size}"
        iops = "${var.iops}"
        os_format_type = "Linux"
        allowed_ip_addresses =["10.155.72.75", "10.155.72.127"]

        
}
```
If you run above resource then `allowed_host_info` will have values populated

**Comment by surajsub** [comment]
Updated this provider in cam - here is the output of the failure 

Initializing provider plugins...Terraform has been successfully initialized!You may now begin working with Terraform. Try running "terraform plan" to seeany changes that are required for your infrastructure. All Terraform commandsshould now work.If you ever set or change modules or backend configuration for Terraform,rerun this command to reinitialize your working directory. If you forget, othercommands will detect it and remind you to do so if necessary.ibm_storage_block.test1: Creating...  allowed_hardware_ids.#:          "" => ""  allowed_hardware_info.#:         "" => ""  allowed_host_info.#:             "" => ""  allowed_ip_addresses.#:          "" => "2"  allowed_ip_addresses.336416711:  "" => "10.155.72.75"  allowed_ip_addresses.3935066784: "" => "10.155.72.127"  allowed_virtual_guest_ids.#:     "" => ""  allowed_virtual_guest_info.#:    "" => ""  capacity:                        "" => "20"  datacenter:                      "" => "dal09"  hostname:                        "" => ""  hourly_billing:                  "" => "false"  iops:                            "" => "2"  os_format_type:                  "" => "Linux"  type:                            "" => "Endurance"  volumename:                      "" => ""Error applying plan:1 error(s) occurred:* ibm_storage_block.test1: 1 error(s) occurred:* ibm_storage_block.test1: unexpected EOFTerraform does not automatically rollback in the face of errors.Instead, your Terraform state file has been partially updated withany resources that successfully completed. Please address the errorabove and apply again to incrementally change your infrastructure.panic: runtime error: invalid memory address or nil pointer dereference2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc8a44e]2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: goroutine 65 [running]:2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: github.com/terraform-providers/terraform-provider-ibm/ibm.buildStorageProductOrderContainer(0xc4202b6120, 0xc42027eca0, 0x9, 0x4000000000000000, 0x14, 0x0, 0xf3ddbd, 0xd, 0xc42027ec90, 0x5, ...)2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/root/go/src/github.com/terraform-providers/terraform-provider-ibm/ibm/resource_ibm_storage_file.go:683 +0x4de2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: github.com/terraform-providers/terraform-provider-ibm/ibm.resourceIBMStorageBlockCreate(0xc4203b0150, 0xf01c80, 0xc42037c000, 0x0, 0x0)2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/root/go/src/github.com/terraform-providers/terraform-provider-ibm/ibm/resource_ibm_storage_block.go:221 +0x4592018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4203271a0, 0xc42028cd20, 0xc420285f40, 0xf01c80, 0xc42037c000, 0xc420378901, 0xc42004bb88, 0x4b9ddc)2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/root/go/src/github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x3a02018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4202e36c0, 0xc42028ccd0, 0xc42028cd20, 0xc420285f40, 0x18, 0x18, 0xc420285f80)2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/root/go/src/github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0xa42018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4202851c0, 0xc420285b20, 0xc42027db10, 0x0, 0x0)2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/root/go/src/github.com/terraform-providers/terraform-provider-ibm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x572018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: reflect.Value.call(0xc42013ac00, 0xc4200a0670, 0x13, 0xf357bc, 0x4, 0xc42004bf18, 0x3, 0x3, 0xc420280b00, 0x20002, ...)2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/tmp/go/go/src/reflect/value.go:447 +0x9692018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: reflect.Value.Call(0xc42013ac00, 0xc4200a0670, 0x13, 0xc42029ef18, 0x3, 0x3, 0xc420327740, 0x7055ab, 0x1)2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/tmp/go/go/src/reflect/value.go:308 +0xa42018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: net/rpc.(*service).call(0xc4201fe840, 0xc4200a2c80, 0xc42009d800, 0xc42009d810, 0xc420092500, 0xc4202858a0, 0xd2ae60, 0xc420285b20, 0x16, 0xd2aea0, ...)2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/tmp/go/go/src/net/rpc/server.go:384 +0x14e2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: created by net/rpc.(*Server).ServeCodec2018-04-16T21:33:41.917Z [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 	/tmp/go/go/src/net/rpc/server.go:480 +0x43a2018/04/16 21:33:41 [TRACE] root: eval: *terraform.EvalWriteState2018/04/16 21:33:41 [TRACE] root: eval: *terraform.EvalApplyProvisioners2018/04/16 21:33:41 [TRACE] root: eval: *terraform.EvalIf2018/04/16 21:33:41 [TRACE] root: eval: *terraform.EvalWriteState2018/04/16 21:33:41 [TRACE] root: eval: *terraform.EvalWriteDiff2018/04/16 21:33:41 [TRACE] root: eval: *terraform.EvalApplyPost2018-04-16T21:33:41.918Z [DEBUG] plugin: plugin process exited: path=/home/terraform/.terraform.d/plugins/terraform-provider-ibm_v0.8.02018/04/16 21:33:41 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:* ibm_storage_block.test1: unexpected EOF2018/04/16 21:33:41 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:* ibm_storage_block.test1: unexpected EOF2018/04/16 21:33:41 [TRACE] [walkApply] Exiting eval tree: ibm_storage_block.test12018/04/16 21:33:41 [TRACE] dag/walk: upstream errored, not walking "output.allowed_host_info"2018/04/16 21:33:41 [TRACE] dag/walk: upstream errored, not walking "output.volumename"2018/04/16 21:33:41 [TRACE] dag/walk: upstream errored, not walking "output.storageId"2018/04/16 21:33:41 [TRACE] dag/walk: upstream errored, not walking "output.hostname"2018/04/16 21:33:41 [TRACE] dag/walk: upstream errored, not walking "provider.ibm (close)"2018/04/16 21:33:41 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"2018/04/16 21:33:41 [TRACE] dag/walk: upstream errored, not walking "root"2018/04/16 21:33:41 [TRACE] Preserving existing state lineage "e1475bef-3ac2-43d7-b4da-ad490b54bcca"2018/04/16 21:33:41 [DEBUG] plugin: waiting for all plugin processes to complete...2018-04-16T21:33:41.923Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!Terraform crashed! This is always indicative of a bug within Terraform.A crash log has been placed at "crash.log" relative to your currentworking directory. It would be immensely helpful if you could pleasereport the crash with Terraform[1] so that we can fix this.When reporting bugs, please include your terraform version. Thatinformation is available on the first line of crash.log. You can alsoget it by running 'terraform --version' on the command line.[1]: https://github.com/hashicorp/terraform/issues!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hkantare** [comment]
Hi 
Can you please share me the tf file because I see the above issue when we trying to create storage itself.

**Comment by surajsub** [comment]
This was fixed. Thanks for your help.
