### ISSUE TITLE
datasource ibm_cis_domain only retrieve 20 domains

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1804]
Hello there,

We are facing an **URGENT** issue with `ibm_cis_domain` with our CIS instance.

We have a CIS instances that has more than 20 domains, and maybe more than 50.

The datasource uses the API endpoints to retrieve the domains list with the default parameter "item-per-page" (default is 20), leading that a datasource on the 21st will trigger an error.

Here is the error thrown:

```hcl
Error: dataSourcCISdomainRead - Domain with name xpzone.bivwak.com does not exist
```

Proof:

```bash
➜  ~ ic cis domains | grep xpzone
➜  ~ ic cis domains --per-page 21 | grep xpzone
9cxxxiiu0c67c22fb594403b047d0d00   xpzone.bivwak.com                           active    false   
```

Also I saw that there is a limit with CLI set to 50, but I don't see this limit into the REST API.

Thanks in advance

**Comment by kavya498** [comment]
Hello,
We are working on it..

**Comment by ifs-pauljegouic** [comment]
Any update ? This is a blocker for us.

**Comment by kavya498** [comment]
We fixed the issue, and worked with robhy to test the fix and it is working as expected..
We are planning to make a release on monday..

**Comment by kavya498** [comment]
Hi,
Fix is available in the latest release [v1.11.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.11.0)

**Comment by ifs-pauljegouic** [comment]
@kavya498 

Cannot test as it this version breaks my template.

**Comment by kavya498** [comment]
Hi @ifs-pauljegouic,
Are you able to test with latest version of the provider..?

**Comment by ifs-pauljegouic** [comment]
Yes fixed, sorry for the non-feedback
