### ISSUE TITLE
Resource ibm_container_cluster - does not support encrypted workers

### ISSUE THREAD

**Issue by IBMRob** [IBM-Cloud/terraform-provider-ibm#182]
### Terraform Version
```
Terraform v0.11.1
+ provider.ibm (unversioned) (0.8)
+ provider.null v1.0.0
```
### Affected Resource(s)
ibm_container_cluster

### Terraform Configuration Files
```
resource "ibm_container_cluster" "appconnectcluster" {
  name         = "${var.cluster_name}"
  datacenter   = "${var.datacenter1}"
  account_guid = "${data.ibm_account.account.id}"
  machine_type = "b2c.4x16.encrypted"
  public_vlan_id = "${var.public_vlan_id1}"
  private_vlan_id = "${var.private_vlan_id1}"
  kube_version = "1.9.3"
  workers = [ {
    name   = "worker-az1-a"
    action = "add"
  },
  {
    name   = "worker-az1-b"
    action = "add"
  }  ]
}
```

### Expected Behavior

Cluster should be created with `b2c.4x16.encrypted` workers

### Actual Behavior

Workers are created with `b2c.4x16` workers
```
OK
ID                                                 Public IP        Private IP     Machine Type         State      Status   Version   
kube-dal13-cra798eabc574a46fc86f8ac6a09aeb0c2-w1   xx.xx.xx.xx   xx.xx.xx.xx   b2c.4x16             normal     Ready    1.9.3_1507   
kube-dal13-cra798eabc574a46fc86f8ac6a09aeb0c2-w2   xx.xx.xx.xx   xx.xx.xx.xx   b2c.4x16             normal     Ready    1.9.3_1507  
```
### Steps to Reproduce
1. `terraform apply` with an encrypted machine type

### References

**Comment by IBMRob** [comment]
The cli does not list them but they are available (and now the default in the UI)  i.e. if you ran 

`bx cs worker-add --cluster Sandbox--workers 2 --machine-type b2c.4x16.encrypted --public-vlan xxxx --private-vlan xxxxx --hardware shared `

you will then get workers such as 
```
ID                                                 Public IP        Private IP     Machine Type         State    Status   Version   
kube-dal13-cra798eabc574a46fc86f8ac6a09aeb0c2-w7   169.60.187.123   10.73.38.179   b2c.4x16.encrypted   normal   Ready    1.9.3_1507   
kube-dal13-cra798eabc574a46fc86f8ac6a09aeb0c2-w8   169.60.187.125   10.73.38.180   b2c.4x16.encrypted   normal   Ready    1.9.3_1507   
```

**Comment by Praveengostu** [comment]
@IBMRob Added attribute disk_encryption to the cluster resource schema. The disk_encryption to be explicitly set to false to disable encryption. By default it is true. Let us know if this helps..

**Comment by IBMRob** [comment]
Thanks - I will let you know how I get on. Note that in IBM Cloud the default now is to create encrypted workers so IMO the default should be true not false.

**Comment by Praveengostu** [comment]
Yes the default is true for disk_ encryption .. so the workers are encrypted by default
