### ISSUE TITLE
ibm_iam_service_id (data / resouce) should return iam_id

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#1820]
### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_iam_service_id

### Expected Behavior
The key **iam_id** is included in the out(put).

### Actual Behavior
Not included

### Important Factoids
The iam_id is needed as input to create API keys for a service ID. Right now the experience / workflow is broken.

**Comment by hkantare** [comment]
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
