### ISSUE TITLE
Feature request: Retrieve details of an API key

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#1821]
Have a data source which returns the result from this API call: https://cloud.ibm.com/apidocs/iam-identity-token-api#v1getapikey

Because some API keys can be retrieved later on (store_value:true), obtaining stored API keys using terraform would help for automation.

**Comment by kavya498** [comment]
@data-henrik , 
API Key can be retrieved using https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/iam_api_key
This feature is available from [1.25.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.25.0) release..

Closing this issue.
Thanks.

**Comment by data-henrik** [comment]
Ok. This feature request is from 2020, so it was delivered.
