### ISSUE TITLE
Feature request: Automatically empty COS bucket before destroy

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#1827]
IBM Cloud Object Storage buckets need to be empty before they can be deleted (destroyed). 

AWS S3 buckets have a force_destroy options which seems to empty the bucket, then destroy / delete it.

**Comment by wderezin** [comment]
Release 1.17 add force_delete for COS:   https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.17.0

**Comment by hkantare** [comment]
closing the isssue based on above comment
