### ISSUE TITLE
ibm_compute_vm_instance always recreating resource

### ISSUE THREAD

**Issue by vknemanavar** [IBM-Cloud/terraform-provider-ibm#1828]
Hi there,

I am using Terraform 0.12.29 and ibm cloud provider plugin v1.11.0. I am able to create vsi using version which mentioned, but there is issue after creation when I rerun again it is destroying existing vsi and recreating, even if there is no change in the vm configuration. terraform command output what I can see is "- os_reference_code          = "REDHAT_7_64" -> null # forces replacement " though I have not use os_reference_code in my code, I have used image_id in my code. It is weird issue I am seeing, appreciate any help

### Terraform Version
Terraform v0.12.29

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_compute_vm_instance

### Terraform Configuration Files
```

resource "ibm_compute_vm_instance" "vm" {
--
  | count           = var.vm_count
  | hostname        = var.hostname
  | domain          = var.domain
  | image_id        = var.image_id
  | datacenter      = var.datacenter
  | hourly_billing  = var.hourly_billing
  | cores           = var.cores
  | memory          = var.memory
  | disks           = [var.disks]
  | local_disk      = var.local_disk
  | public_vlan_id  = var.public_vlan_id
  | private_vlan_id = var.private_vlan_id
  | ssh_key_ids     = [var.ssh_key_ids]
  | }


```

### Expected Behavior
It shouldn't recreate the resource since there is no change in the configuration when we re run next attempt

### Actual Behavior
It is destroying existing resource and creating new one even though there is no change in the configuration

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. `After successful creation of resource just rerunning it again`
5. `terraform init`
6.  `terraform plan - tells it is going to add 1 resource and destroy 1 resource even though there is no change in the configuration`
7. `terraform apply - It destroys the existing resource and create new one even though there is no change in the configuration`

### Important Factoids
- None

### References
- No

**Comment by hkantare** [comment]
fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.14.0
