### ISSUE TITLE
ibm_container_cluster data source should not require org and space guids

### ISSUE THREAD

**Issue by ruben-burr** [IBM-Cloud/terraform-provider-ibm#184]
Hi there,

as of the latest release, org and space guids are optional for ibm_container_cluster resource. But they are still required for the corresponding data source. This is inconsistent and not necessary. Could you please remove that required flag?

Greets, Ruben

**Comment by Praveengostu** [comment]
Thanks @ruben-burr We are working on it, and will update you once the fix is pushed to public
