### ISSUE TITLE
An error should be thrown if the subnets provided to ibm_container_vpc_cluster on create do not come from the vpc specified 

### ISSUE THREAD

**Issue by evpirnia** [IBM-Cloud/terraform-provider-ibm#1841]
## Situation
When creating an `ibm_container_vpc_cluster`, both `vpc_id` and `zones` are required. It is currently possible to specify the id of a subnet that does not belong to the vpc specified. 

```
resource ibm_container_vpc_cluster cluster {
    name                            = var.cluster_name
    vpc_id                          = data.ibm_is_vpc.vpc_A.id
    ...
    zones {
        subnet_id  = var.subnet_id_from_vpc_A
        name       = var.subnet_zone
    }
    zones {
        subnet_id  = var.subnet_id_from_vpc_B
        name       = var.subnet_zone
    }

```

## Current behavior
The VPC cluster is created but, the worker nodes spun up on the subnet `var.subnet_id_from_vpc_B` cannot interact with those spun up on on the other subnet `var.subnet_id_from_vpc_A` because the VPC specified is vpc A. 

## Desired behavior: 
An error is thrown when subnet ids are provided that do not exist within the VPC specified. 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/6e9f8cc368832c4aab97b6f509d65470a74b7935/ibm/resource_ibm_container_vpc_cluster.go#L356

For reference, this issue does not occur in the UI. In the UI, the user is prompted to select the VPC and then the subnet dropdowns are automatically populated with *only* the subnets from that VPC. 
<img width="566" alt="Screen Shot 2020-08-26 at 10 56 36 AM" src="https://user-images.githubusercontent.com/11401353/91340652-342d2400-e78d-11ea-8f2b-cc1d28a776d3.png">

**Comment by hkantare** [comment]
I think this needs to fixed in the armada API team since we just send payload to the armada API...Can you try same thing using ibmcloud cli or the API and share us the behaviour

**Comment by evpirnia** [comment]
Nice catch! I was able to recreate the issue via the ibmcloud cli. Closing and creating an issue under armada-api
