### ISSUE TITLE
Cannot create MX record with priority of 0 using Terraform

### ISSUE THREAD

**Issue by andrewferrier** [IBM-Cloud/terraform-provider-ibm#1842]
### Terraform Version
(through Schematics, terraform 0.12.20 at the time of writing).

### Affected Resource(s)
`ibm_cis_dns_record`

### Terraform Configuration Files
Relevant section:

```hcl
resource "ibm_cis_dns_record" "dns_mx_1" {
  cis_id    = ibm_cis.cis_instance.id
  domain_id = ibm_cis_domain.piptcom.id
  name      = var.global_domain
  ttl       = 3600
  type      = "MX"
  priority  = "0"
  content   = "pipt-com.mail.protection.outlook.com"
}
```

### Debug Output
Relevant section of Terraform/Schematics output: 

```
2020/08/26 16:47:50 Terraform apply | ibm_cis_dns_record.dns_mx_1: Creating...
 2020/08/26 16:47:50 Terraform apply | 
 2020/08/26 16:47:50 Terraform apply | Error: Failed to create record: Request failed with status code: 400, ServerErrorResponse: {"trace": "36906f6a-82c8-4e13-b201-f4c910fd6dc1", "errors": [{"code": "CIS-FRT-00005", "message": "property 'priority' is a required property"}], "notices": "Scheduled maintenance: September 9, 2020 from 18:00 to 20:00 UTC (9/9/2020 1pm - 3pm US CDT): During this maintenance window, our partner, Cloudflare, will conduct a failover of their control plane services to their secondary site in Luxembourg. The control path might be degraded or unavailable. The data path is not impacted. A second maintenance window is planned for September 16, 2020, for another failover from their secondary site back to their primary site."}
```

### Expected Behavior
DNS record should be created.

### Actual Behavior
DNS record not created - see error above.

### Steps to Reproduce
1. Create a Terraform script similar to above.
2. Wrap in Schematics workspace.
3. Run.

### Important Factoids
If the priority is changed to 1 (0 is valid for DNS, though), there is no error and the resource is created.

### References
Relevant IBM internal Slack discussion on this issue: https://ibm-cloudplatform.slack.com/archives/C53NF5MB4/p1598464166081500?thread_ts=1598443692.075400&cid=C53NF5MB4

**Comment by kavya498** [comment]
We recently made a terraform release, with the new CIS SDK.. `name ="@"` , `priority =0 or "0"` as inputs works in the latest provider..
Schematics is expecting to make a release on monday which includes latest terraform provider..
Feel free to report, if you face the same issue after schematics release..

**Comment by hkantare** [comment]
Fixed in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.12.0
