### ISSUE TITLE
Deprovisioning K8s cluster - PVC's not being deleted

### ISSUE THREAD

**Issue by SpencerReynolds18** [IBM-Cloud/terraform-provider-ibm#1847]
Just got off a client call where they expressed the following frustration with the Schematics/Terraform experience:
While de-provisioning the Kubernetes cluster via Terraform automation, supportive PVCs are not getting deleted.

If we de-provision the Kubernetes cluster manually, there is an option in the UI, to optionally delete the PVCs, but same doesn’t exist via Terraform automation.

Connecting to an internal issue that mirrors this: https://github.ibm.com/blueprint/product/issues/2992

**Comment by hkantare** [comment]
Releases in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.12.0
