### ISSUE TITLE
"file" provisioner for ibm_compute_vm_instance requires public network interface

### ISSUE THREAD

**Issue by jlerm** [IBM-Cloud/terraform-provider-ibm#185]
I found out that the provisioner of type "file" for "ibm_compute_vm_instance" requires the new VM to be created with a public network interface.
Without a non-blocked public network access, the terraform template fails with "getsockopt" error.

I am using the templates shipped with Cloud Automation Manager 2.1.0.2.

This may be OK for development and demos, but is not acceptable for production environments.

I verified with different tests. 

The following fail:

- With just a private network only;
- With both private and public networks defined in the VM, but the public interface blocked by a Vyatta gateway.

It works if both the private and pubic networks are defined for a VM, and there is no firewall blocking/disabling access to the public network.

I need to create one type of VM that requires a 50 line-long shell script for its initialization.
I could try do it in a "remote-exec" provisioner, but there are limitations in the syntax accepted by the "inline" property. It's too cumbersome to try save a longer script in that property.

Please let me know if this is something can be fixed.

Thanks,

Julius

**Comment by hkantare** [comment]
Hi Julius

**1 With just a private network only**
For private network only you need to login to vpn to particular datacenter on which vm resides. Then you can execute any scripts via remote-exec

**2With both private and public networks defined in the VM, but the public interface blocked by a Vyatta gateway.**
May be you can define some firewall rules to allow traffic .Sample example
```
resource "ibm_firewall" "accfw" {
  ha_enabled     = false
  public_vlan_id = "${ibm_compute_vm_instance.vm1.public_vlan_id}"
}

resource "ibm_firewall_policy" "rules" {
  firewall_id = "${ibm_firewall.accfw.id}"

  rules = {
    "action"               = "deny"
    "src_ip_address"       = "0.0.0.0"
    "src_ip_cidr"          = 0
    "dst_ip_address"       = "any"
    "dst_ip_cidr"          = 32
    "dst_port_range_start" = 1
    "dst_port_range_end"   = 65535
    "notes"                = "Deny all"
    "protocol"             = "tcp"
  }

  rules = {
    "action"               = "permit"
    "src_ip_address"       = "0.0.0.0"
    "src_ip_cidr"          = 0
    "dst_ip_address"       = "any"
    "dst_ip_cidr"          = 32
    "dst_port_range_start" = 22
    "dst_port_range_end"   = 22
    "notes"                = "Allow SSH"
    "protocol"             = "tcp"
  }
```

**3 50 line-long shell script for its initialization**
You can save the script in a file and transfer the script to remote location and execute by using remote-exec. More information can be found here
https://www.terraform.io/docs/provisioners/remote-exec.html

Can you please try above solution and let us know..

**Comment by jlerm** [comment]
I figured out the root problem: the "connection" within the "ibm_compute_vm_instance" resource was referencing ${self.ipv4_address}, instead of ${self.ipv4_address_private}. 
Once I modified that, the file provisioner worked with a private network-only VM.
