### ISSUE TITLE
Feature Request: Auto Scaling for ICD

### ISSUE THREAD

**Issue by werne2j** [IBM-Cloud/terraform-provider-ibm#1853]
It would be nice to have the option to turn on auto scaling when provisioning a new IBM Cloud Database instance

**Comment by ethilesen** [comment]
Yes Yes please add the cluster add on feature to terraform

**Comment by kavya498** [comment]
We have added ICD Auto Scaling feature..
It'll be available in upcoming release..

**Comment by hkantare** [comment]
Released in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.12.0
