### ISSUE TITLE
Terraform provider does not support 'Universal SSL' switch for Cloud Internet Services

### ISSUE THREAD

**Issue by andrewferrier** [IBM-Cloud/terraform-provider-ibm#1855]
# Terraform Version
0.12.20 (currently in use by Schematics)

### Affected Resource(s)
`ibm_cis_domain_settings`

### Terraform Configuration Files
Where I would expect this setting to be exposed:

```hcl
resource "ibm_cis_domain_settings" "xyz" {
  cis_id                   = ibm_cis.cis_instance.id
  domain_id                = ibm_cis_domain.xyzcom.id
  waf                      = "on"
  browser_check            = "on"
  automatic_https_rewrites = "on"
  always_use_https         = "on"
  ssl                      = "full"
  brotli                   = "on"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
N/A

### Actual Behavior
N/A

### References
Discussed internally on Slack here: https://ibm-garage.slack.com/archives/C53NF5MB4/p1598619084106600.

**Comment by kavya498** [comment]
Hi @andrewferrier,
Universal SSL switch is support using `tls-settings`, which will be a new resource. Please find the CLI docs for the same [here](https://cloud.ibm.com/docs/cis-cli-plugin?topic=cis-cli-plugin-cis-cli#show-tls-setting).
One of the developers @KumarGanesanIBM  from service team will be working on this..
