### ISSUE TITLE
How to use database backup_id: ibm_database - databases-for-postgresql - backup_id

### ISSUE THREAD

**Issue by Mountain-Rock** [IBM-Cloud/terraform-provider-ibm#1856]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.12.28
+ provider.ibm v1.8.1

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_database
      databases-for-postgresql

### Terraform Configuration Files
In [plugin doc](https://cloud.ibm.com/docs/terraform?topic=terraform-databases-resources#db),  there is field `backup_id` which is the CRN of a backup resource to restore from.

- The backup must have been created by a database deployment with the same service ID. 
   **Question**: we create the postgresql with apikey without service ID, could you explain more about how to use service ID for backup?
- The backup is loaded after provisioning and the new deployment starts up that uses that data. A backup CRN is in the format `crn:v1:<…>:backup:`. 
   **Question**: where can I find the crn of backup postgresql?

**Comment by kavya498** [comment]
**Question:** `we create the postgresql with apikey without service ID, could you explain more about how to use service ID for backup?`
service id here is `databases-for-postgresql`. That meant `service attribute in resource` and database that is being used to backup i.e `backup_id` should be of same service.. 
eg: You cannot use redis or any other backup_id to create a postgresql database.
You can use this basic template which restores the backup for a given backup_id
```
resource "ibm_database" "redis_standard" {
    name              = "rabbit-backup"
    service           = "databases-for-postgresql"
    plan              = "standard"
    location          = "us-south"
    backup_id           = "your backup_id of existing postgresql"
```
**Question:** where can I find the crn of backup postgresql?
On clicking the `backup now` button on the `backups`  tab of your instance page you can find the backup_id of that particular instance.

**Comment by kavya498** [comment]
Closing this issue..
Thanks..
