### ISSUE TITLE
Cloud Object Storage access key and secret

### ISSUE THREAD

**Issue by msilverm-web** [IBM-Cloud/terraform-provider-ibm#1860]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.26

### Terraform Configuration Files
resource "ibm_resource_instance" "cos_instance" {
name              = "Cloud-Object-Storage-${var.customer_id}"
service           = "cloud-object-storage"
plan              = "standard"
location          = "global"
}
resource "ibm_iam_service_id" "serviceID" {
  name        = "cos-service-id"
  description = "New ServiceID"
}
resource "ibm_resource_key" "resourceKey" {
  name                 = "COS-API-KEYS"
  role                 = "Manager"
  resource_instance_id = ibm_resource_instance.cos_instance.id
  parameters = {
    serviceid_crn = ibm_iam_service_id.serviceID.crn
    HMAC = true
  }
  timeouts {
    create = "15m"
    delete = "15m"
  }
}
output "cloud_object_storage_credentials" {
  value = ibm_resource_key.resourceKey.credentials
}

OUTPUT:
cloud_object_storage_credentials = {
  "apikey" = "xxxxx"
  "cos_hmac_keys.access_key_id" = "yyyyyy"
  "cos_hmac_keys.secret_access_key" = "zzzzzzzzzz"
  "endpoints" = "https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints"
  "iam_apikey_description" = "Auto generated apikey during resource-key operation for Instance - crn:v1:bluemix:public:cloud-object-storage:global:a/xxxxxxxxx:zzzzz::"
  "iam_apikey_name" = "auto-generated-apikey-xxxxxxxxx"
  "iam_role_crn" = "crn:v1:bluemix:public:iam::::serviceRole:Manager"
  "iam_serviceid_crn" = "crn:v1:bluemix:public:iam-identity::a/xxxxxxxx::serviceid:ServiceId-xxxxxxxx"
  "resource_instance_id" = "crn:v1:bluemix:public:cloud-object-storage:global:a/yyyyyyyy::"
}

Issue is that the cos_hmac_keys.access_key_id and cos_hmac_keys.secret_access_key have a period in the key, which is making it difficult to access the values because terraform does not like periods "." in the key name.

**Comment by data-henrik** [comment]
see #1741
