### ISSUE TITLE
Support Service Roles in iam_role_actions

### ISSUE THREAD

**Issue by 0az** [IBM-Cloud/terraform-provider-ibm#1861]
The data provider `ibm_iam_role_actions` only supports the default Platform roles. As a result, it is impossible to create a Custom Role derived from Service Roles for use in `ibm_iam_service_policy` instances. (The root problem is that `ibm_iam_service_policy` does not support using string Service Roles, as far as I can tell, but this is a simple enough workaround.)

One suggestion for implementation is adding a `service_roles` map to the `ibm_iam_role_actions` output, with keys of `string` service role names, and values of `list`s of `string` action names: `service_roles: map<string, list<string>>`.

### Affected Resource(s)
Please list the resources as a list, for example:
- `iam_role_actions`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "ibm_iam_role_actions" "current" {
	service = "cloud-object-storage"
}

# Only exposes manager, reader, reader_plus, and writer
output "current" {
	value = ibm_iam_role_actions.current
}
```
```hcl
# Desired usage
data "ibm_iam_role_actions" "example" {
	service = "cloud-object-storage"
}

resource "ibm_iam_custom_role" "read_write" {
	name = "role"
	display_name = "Role"
	service = "cloud-object-storage"
	actions = concat(
		data.ibm_iam_role_actions.example["Content Reader"],
		data.ibm_iam_role_actions.example["Object Writer"],
	)
}

# Apply the custom role to a service policy
resource "ibm_iam_service_policy" "policy" {
	iam_service_id = var.cos_service_id
	roles = [ibm_iam_custom_role.read_write.name]
	resources {
		service = "cloud-object-storage"
		# Etc
	}
}
```

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1527

(Internal Slack Username: `@afzhou`)

**Comment by guicabr** [comment]
1. Verified that we are setting only roles based on display name being equal to `Reader`, `Manager`, `Reader Plus` or `Writer` 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/9051101e9e7761a4b58d86336b23801b1c47f690/ibm/data_source_ibm_iam_role_actions.go#L70

2. Trying to understand why this specified in the example for custom role. It is not being referenced afterwards 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-iam-custom-role/main.tf#L19

**Comment by guicabr** [comment]
Draft PR: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2746

TODO:
1. Find out if Terraform config syntax (`[data.ibm_iam_role_actions.test["Object Writer"]]`) is allowed
2. Implement map in iam_role_actions data source with key (ex. Object Writer) and values (ex. All actions associated w/ Object Writer).
3. Find out from Kavya if we will need to add deprecation notice in next version this is included (Already sent message)
4. Update documentation/examples

**Comment by guicabr** [comment]
* Updated PR, code and tests are done. Now working on documentation/examples

**Comment by guicabr** [comment]
Sample way to retrieve custom service role actions, for this particular case only `cloud-object-storage.object.head_version`:

```
provider "ibm" {}

data "ibm_iam_role_actions" "current" {
        service = "cloud-object-storage"
}

output "onlyobjectreaderactions" {
        value = split(",", data.ibm_iam_role_actions.current.actions["Object Reader"]).3
}
```

**Comment by guicabr** [comment]
Regarding choice of Schema being Map[string]string. Below is relevant section from  Terraform [docs](https://www.terraform.io/docs/extend/schemas/schema-methods.html):

> // The following fields are only set for a TypeList, TypeSet, or TypeMap.
//
// Elem represents the element type. For a TypeMap, it must be a *Schema
// with a Type of TypeString, otherwise it may be either a *Schema or a
// *Resource. If it is *Schema, the element type is just a simple value.
// If it is *Resource, the element type is a complex structure,
// potentially with its own lifecycle.
Elem interface{}
