### ISSUE TITLE
data source ibm_schematics_workspace cannot find EU hosted workspace instance

### ISSUE THREAD

**Issue by stevestrutt** [IBM-Cloud/terraform-provider-ibm#1865]
### Terraform Version under Schematics 
0.12.6 with latest Schematics Terraform provider

### Affected Resource(s)
ibm_schematics_workspace

### Terraform Configuration Files
```hcl
data "ibm_schematics_workspace" "vpc" {
  workspace_id = var.workspace_id
}

variable "workspace_id" {
  description = "Id of the source Schematics Workspace for target VSIs"
  default     = "ssh_bastion-host-0353ce37-3748-4c"
}
```

### Expected Behavior
ibm_schematics_workspace data source should retrieve workspace information from Schematics EU instance. Schematics workspace is saved on the EU instance and executed from the EU instance with an input variable that points to a workspace on the EU instance. 

Expected behaviour is that by default when no Schematics instance is specified the data source should target the schematics instance that the provider is executing under. Ideally the data source should support the ability to specify the target instance, but if not specified default to the Schematics instance executing the TF config. If running under TF standalone it is acceptable to default to the US. 

### Actual Behavior
Terraform provider points to the US Schematics instance and fails to locate a workspace on the Schematics EU instance and returns 404 error.  The data source is targeting the US instance of Schematics to locate the EU workspace and this fails as it is saved on the EU instance. If a US workspace-id is specified the data source locates this successfully on the US instance.  

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create workspace on Schematics EU instance
2. Input workspace-id of an EU workspace
3. Generate Plan

### Important facts
This breaks usage of the Terraform Ansible Provisioner in the EU as it is not possible to retrieve target VPC VSI information from the referenced workspace.

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.12.0
