### ISSUE TITLE
Option to reboot in ibm_pi_instance create

### ISSUE THREAD

**Issue by yussufsh** [IBM-Cloud/terraform-provider-ibm#1878]
Need an option to force instance reboot incase the instance is not available say after 30m (configurable/optional).

The purpose of such change is because most of the time we have seen that the instance get stuck at grub or maintance prompt and creation times out after 2 hours which make a bad user experience. With this approach we can try a reboot after a speified time period if instance is not Available or in desired health state.

@surajsub @hkantare Let me know what you think about this? I can help with dev part if need be.

### Affected Resource(s)
- ibm_pi_instance

**Comment by yussufsh** [comment]
cc @bpradipt

**Comment by surajsub** [comment]
Please use hard-reboot..option

**Comment by surajsub** [comment]
it's already available today

**Comment by yussufsh** [comment]
@surajsub I understand we have a standalone resource to reboot an instance but how is it going to help with this scenario? This would be a always reboot option. But we need reboot only in case when instance is not active for some time. In addition it will be another overhead (failing resource) if instance is not active even after a reboot.

We are looking for a solution to work around instance creation when it is not active for 2 hrs (unable to boot). Giving a buffer time to start or else try reboot within create instance process flow.

**Comment by surajsub** [comment]
@yussufsh  - what you are asking is not the generic pattern for IAC.  Try to provision a resource --> Resource fails - Provision another . Period. Trying to embed logic for reboot and then maintaining those intermediary states will complicate the issue. 
E.g  - if the reboot fails then we have to be able to recover from it etc.

**Comment by yussufsh** [comment]
I understand the point but what it is right now is not helping. When user run `terraform apply` node get stuck in boot for 2 hours and never becomes active. When we re-apply it fails saying "Name already in use". User then would manually delete the instance to apply again since TF does not know the state of the resource,
