### ISSUE TITLE
ibm_pi_instance not failing on ERROR state

### ISSUE THREAD

**Issue by yussufsh** [IBM-Cloud/terraform-provider-ibm#1879]
Terraform continue to create instance for 2 hours even when GUI shows instance in ERROR state.

Also, the instance create timeout value should be customizable.

### Terraform Version
# terraform version
Terraform v0.13.2
+ provider registry.terraform.io/ibm-cloud/ibm v1.11.2

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_pi_instance

### Expected Behavior
ibm_pi_instance should exit with error if instance status is ERROR.

### Actual Behavior
ibm_pi_instance continously wait for Available, OK state till timeout.

### Important Factoids
There was some maintanance at the CoLo side which turned the instance into ERROR state.

**Comment by yussufsh** [comment]
@bpradipt

**Comment by surajsub** [comment]
Also please note that this is not a terraform issue. This is a power / cloud colo issue.

**Comment by bpradipt** [comment]
> Also please note that this is not a terraform issue. This is a power / cloud colo issue.

Yes true, it's not a TF issue. It's a colo issue and there could be other such cases where instances errors out as we are seeing. 
Providing some flexibility in the provider to fail fast will help the end user experience.

**Comment by hkantare** [comment]
Like other resources (VPC instances, soon ) we need to add Target for even Error or failed state 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/f2b3d7fa3ed6508906f81ba24cc31a488f59cea7/ibm/resource_ibm_is_instance.go#L839 and come out from the wait logic

**Comment by hkantare** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/f2b3d7fa3ed6508906f81ba24cc31a488f59cea7/ibm/resource_ibm_pi_instance.go#L765
Add the keyword for failed or error based on the API response (keyword for error)

**Comment by surajsub** [comment]
I spoke to the power team. they did provide me with some input. I will submit another PR
