### ISSUE TITLE
Feature Request: Configure COS bucket retention policy

### ISSUE THREAD

**Issue by maristgeek** [IBM-Cloud/terraform-provider-ibm#1880]
Hi there,

We would like to be able to configure a retention policy on a COS bucket through terraform rather than hand manipulation.

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-immutable

**Comment by maristgeek** [comment]
Semi-related to #1590.

**Comment by ileneruth** [comment]
Is there any update on this one?

**Comment by kavya498** [comment]
Available in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.23.2)

**Comment by kavya498** [comment]
Closing this issue
Thanks.
