### ISSUE TITLE
DNS resolution not working 

### ISSUE THREAD

**Issue by jangel97** [IBM-Cloud/terraform-provider-ibm#1883]
Hi there,

I am trying to create DNS records in IBM Cloud VPC via Terraform. Apparently resources are created properly, the problem is that after the deploy when I test the internal resolution inside the VPC through the "dig" command it returns NXDOMAIN.

### Terraform Version
Terraform v0.12.20

### Provider version
 provider.ibm: version = "~> 1.11"

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_resource_instance
- ibm_dns_zone
- ibm_dns_permitted_network
- ibm_dns_resource_record

### Terraform Configuration Files
```hcl

resource "ibm_resource_instance" "resource_instance" {  //https://cloud.ibm.com/docs/terraform?topic=terraform-resource-mgmt-resources#resource-instance
  name              = "dns-services-for-vpc"
  service           = "dns-svcs" //ibmcloud catalog service-marketplac
  plan              = "standard-dns" // ibmcloud catalog service dns-svcs
  location          = "global"
  resource_group_id = data.ibm_resource_group.group.id
#  tags              = ["tag1", "tag2"]

  //User can increase timeouts 
  timeouts {
    create = "15m"
    update = "15m"
    delete = "15m"
  }
}

resource "ibm_dns_zone" "pdns-1-zone" { //https://cloud.ibm.com/docs/dns-svcs?topic=dns-svcs-managing-dns-zones#multi-level-limitations
    depends_on = [ibm_resource_instance.resource_instance]
    name = "jangdemos.com"
    instance_id = ibm_resource_instance.resource_instance.guid
    description = "testdescription"
    label = "testlabel"
}

resource "ibm_dns_permitted_network" "test-pdns-permitted-network-nw" {
    instance_id = ibm_resource_instance.resource_instance.guid
    zone_id = ibm_dns_zone.pdns-1-zone.zone_id
    vpc_crn = ibm_is_vpc.testacc_vpc.crn
    type = "vpc"
}


resource "ibm_dns_resource_record" "test-pdns-resource-record-a" {
  depends_on  = [ibm_dns_permitted_network.test-pdns-permitted-network-nw]
  instance_id = ibm_resource_instance.resource_instance.guid
  zone_id     = ibm_dns_zone.pdns-1-zone.zone_id
  type        = "A"
  name        = "bastion"
  rdata       = ibm_is_instance.bastion_instance.primary_network_interface[0].primary_ipv4_address
  ttl         = 3600
}

resource "ibm_dns_resource_record" "test-pdns-resource-record-ptr" {
  instance_id = ibm_resource_instance.resource_instance.guid
  zone_id     = ibm_dns_zone.pdns-1-zone.zone_id
  type        = "PTR"
  name        = ibm_is_instance.bastion_instance.primary_network_interface[0].primary_ipv4_address
  rdata       = "${ibm_is_instance.bastion_instance.name}.${ibm_dns_zone.pdns-1-zone.name}"
  ttl         = 3600
}

```

### Expected Behavior
What should have happened?
I expect the command ```dig bastion.jangdemos.com``` not to return NXDOMAIN when tested inside the VPC.

### Actual Behavior
What actually happened?
Whenever I ssh into the instance created I run the command ```dig bastion.jangdemos.com```, and it returns NXDOMAIN. Nevertheless, I must say that terraform never complaint during the "terraform apply".

Thanks in advance to everyone!

**Comment by hkantare** [comment]
@MalarvizhiK can you look into this

**Comment by MalarvizhiK** [comment]
@jangel97, Can you read this example: https://github.com/IBM-Cloud/vnf-samples/blob/master/pdns-mongo-nodejs/README.md 
Specifically section: Updating the DNS resolver for your VSI

We have tried the above and it worked.

**Comment by jangel97** [comment]
Okay, it worked.

Thanks @MalarvizhiK :)
