### ISSUE TITLE
Feature Request: support for Global Load Balancer, GLB, for private DNS

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#1887]
See #958 

A new feature, global load balancers (Beta), is available https://cloud.ibm.com/docs/dns-svcs?topic=dns-svcs-global-load-balancers

The API will eventually be here: https://github.com/IBM/dns-svcs-go-sdk it is currently not available.  See https://github.ibm.com/NetworkTribe/PrivateDNS-Support/issues/49

**Comment by lipingsh** [comment]
Being worked in https://github.ibm.com/NetworkTribe/nw-sdk-terraform-planner/issues/125.
PRs are merged. Awaiting next Terraform release.

**Comment by lipingsh** [comment]
There's a Terraform release v1.15.0 on Nov 24 with the PDNS GLB feature included:
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.15.0

**Comment by hkantare** [comment]
closing this issue
