### ISSUE TITLE
Instance Group/AutoScale Max count should be 1000 not 100

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM-Cloud/terraform-provider-ibm#1889]
Hi @Anil-CM , as we've discussed the limit of the max count is 1000 not 100.

```
Error: expected instance_count to be in the range (0 - 100), got 500
  on main.tf line 143, in resource "ibm_is_instance_group" "instance_group":
 143: resource "ibm_is_instance_group" "instance_group" {
root@af997905ad1c:/system-tf-base/test/system/autoscale/cpu#
Error: expected max_membership_count to be in the range (1 - 100), got 1000
  on main.tf line 150, in resource "ibm_is_instance_group_manager" "instance_group_manager":
 150: resource "ibm_is_instance_group_manager" "instance_group_manager" {
```
Sean Thornton
1000 is the limit

**Comment by Anil-CM** [comment]
Hi @syyang-in-cloud,

As per the API DOCs of VPC SDK. The maximum number of instances in the instance group should be `1 < count < 100`.

https://cloud.ibm.com/apidocs/vpc#create-instance-group

**Comment by syyang-in-cloud** [comment]
> Hi @syyang-in-cloud,
> 
> As per the API DOCs of VPC SDK. The maximum number of instances in the instance group should be `1 < count < 100`.
> 
> https://cloud.ibm.com/apidocs/vpc#create-instance-group

Hi @Anil-CM , this document is incorrect, and it's not matching with the actual implementation. I raised the issue to Sean T that we need to change both document and provider.

**Comment by hkantare** [comment]
Fixed in latest 
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
