### ISSUE TITLE
ibm_compute_vm_instance can't create VMs with 1000Mbit/s network interface

### ISSUE THREAD

**Issue by jlerm** [IBM-Cloud/terraform-provider-ibm#190]
I am trying to create Softlayer VMs using the IBM Cloud provider that comes with IBM's CAM (Cloud Automation Manager) 2.1.0.1, but the VMs can't seem to be created with 1000Mbit/s network interfaces

In the example below, I specify network_speed=1000, but the VMs are always created with 100Mbit/s:

resource "ibm_compute_vm_instance" "isds" {
  count="1"
  hostname = "${var.vm_name_prefix}-isds"
  os_reference_code        = "REDHAT_7_64"
  domain                   = "${var.vm_domain}"
  datacenter               = "${var.datacenter}"
  private_vlan_id          = "${data.ibm_network_vlan.cluster_vlan.id}"
  network_speed            = 1000
  hourly_billing           = true
  private_network_only     = true
  cores                    = "${var.dsengine_num_cpus}"
  memory                   = "${var.dsengine_mem}"
  disks                    = [100,1000]
  dedicated_acct_host_only = false
  local_disk               = false
  ssh_key_ids              = ["${ibm_compute_ssh_key.cam_public_key.id}", "${ibm_compute_ssh_key.temp_public_key.id}"]

  connection {
    user        = "root"
    private_key = "${tls_private_key.ssh.private_key_pem}"
    host        = "${self.ipv4_address_private}"
  }
}

Any ideas?

Thanks,

Julius

**Comment by hkantare** [comment]
Hi Julie
I tried with latest provider I'm not able to reproduce the issue . VM is created with network speed=1000
```
ibm_compute_ssh_key.ssh_key:
  id = 1123905
  fingerprint = 1c:c6:ca:b7:6f:4f:0d:20:ec:40:d0:90:27:47:ae:53
  label = ssh-test
  notes = for public vlan test
  public_key = ssh-rsa ----
ibm_compute_vm_instance.isds:
  id = 53010769
  block_storage_ids.# = 0
  cores = 1
  datacenter = dal05
  dedicated_acct_host_only = false
  disks.# = 2
  disks.0 = 100
  disks.1 = 1000
  domain = test.com
  file_storage_ids.# = 0
  hostname = test-isds
  hourly_billing = true
  ip_address_id_private = 111123399
  ipv4_address = 
  ipv4_address_private = 10.41.6.35
  ipv6_enabled = false
  ipv6_static_enabled = false
  local_disk = false
  memory = 1024
  network_speed = 1000
  notes = 
  os_reference_code = REDHAT_7_64
  private_interface_id = 30265937
  private_network_only = true
  private_security_group_ids.# = 0
  private_subnet = 10.41.6.32/29
  private_subnet_id = 256088
  private_vlan_id = 2298937
  public_bandwidth_unlimited = false
  public_interface_id = 30265939
  public_security_group_ids.# = 0
  secondary_ip_addresses.# = 0
  ssh_key_ids.# = 1
  ssh_key_ids.1123905 = 1123905
  wait_time_minutes = 90
ibm_network_vlan.test_vlan_private:
  id = 2298937
  child_resource_count = 0
  datacenter = dal05
  name = testprvlan
  router_hostname = bcr01a.dal05
  softlayer_managed = false
  subnet_size = 8
  subnets.# = 1
  subnets.0.cidr = 29
  subnets.0.gateway = 
  subnets.0.subnet = 10.41.6.32/29
  subnets.0.subnet_size = 8
  subnets.0.subnet_type = PRIMARY
  type = PRIVATE
  vlan_number = 924
```
Can you lets know the provider version in IBM CAM's

**Comment by jlerm** [comment]
I am not sure how to find out the version of the provider, will try find it out.
CAM version is 2.1.0.1.

You are listing just the output produced by the terraform template. The template is telling you the network speed is 1000.

Did you look at the VM details on the Softlayer portal?
What does the Softlayer portal tell you, after the VM was created?

**Comment by jlerm** [comment]
Just got a reply from the slack channel: the IBM Cloud terraform provider version in CAM 2.1.0.1 is 0.5.1.

**Comment by hkantare** [comment]
In portal also I do see same network speed 1000
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/24930306/38651290-f305adba-3def-11e8-9c21-64168938e16a.png">


I think the provider need to be updated to latest v0.8.0 .Because in v0.7.0 a fix related to network speed as gone
https://github.com/IBM-Cloud/terraform-provider-ibm/commit/3dfcd43e5eddb4f875a1e90a07f0ec81639ae596#diff-e4b220657319756663dd781aea77b4d0

**Comment by jlerm** [comment]
Thanks for verifying. I will install the latest CAM (2.1.0.2) and see if it works then.
Appreciate your help.
