### ISSUE TITLE
IBM Cloud -CDN deletion is failing if resource is deleted from portal and The tfstate file should have resources as {} if resource is deleted from portal side .

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#1902]
Hi there,

### Terraform Version
0.12

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_cdn

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "ibm_cdn" "cdn" {
  host_name = "${var.host_name}"
  cname = "${var.cname}"
  vendor_name = "${var.vendor_name}"
  header = "${var.header}"
  path = "${var.path}"
  origin_address = "${var.origin_address}"
  origin_type = "${var.origin_type}"
  protocol = "${var.protocol}"
  http_port = "${var.http_port}"
  https_port = "${var.https_port}" 
  bucket_name = "${var.bucket_name}" 
  respect_headers = "${var.respect_headers}"
  certificate_type="${var.certificate_type}"
  cache_key_query_rule="${var.cache_key_query_rule}"
  performance_configuration="${var.performance_configuration}"
  file_extension = "${var.file_extension}"
}
```

### Expected Behavior
The tfstate file should have resources as {} if resource is deleted from portal side .

### Actual Behavior
tftstate file contains resources even if the resource is deleted.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by M-Rushabh** [comment]
PR - https://github.com/IBM-Cloud/terraform-provider-ibm/pull/1903

**Comment by M-Rushabh** [comment]
CC @hkantare  Request to review this ...this is tested and and working fine.

**Comment by hkantare** [comment]
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
