### ISSUE TITLE
IBM Cloud - IAM Environment Sandboxing for Terraform

### ISSUE THREAD

**Issue by kskewes** [IBM-Cloud/terraform-provider-ibm#191]
**Disclaimer:**

Sorry this is probably the wrong place to ask and a simple question however I have:
- searched through the IBM docs on Access Groups, Resource Groups and Cloud Foundry
- used IBM chat, created IBM tickets
- had a go with Bluemix console
- google searched. 

There are separate Cloud Foundry Organizations in IBM Cloud Bluemix portal, but I can't see how they relate to Kubernetes clusters under Containers... 

**Questions:**

1. How can you create separate environments to match your desired Terraform state file separation (eg: dev/uat/stg/prod/service breakout/etc).  ??

**Comment by kskewes** [comment]
Sorry this seems to be a duplicate of the last sentence in issue #149 . 

In Terraform, if we could specify the IBM `Resource Group` when provisioning entities (vm's, clusters, COS, etc) then we would be fine for our use case.

I would just manually create required `Service ID` and `Resource Group` via BX CLI or the web portal, then continue in Terraform.

**Comment by kskewes** [comment]
Any news on this? ETA?
Without support for IBM `resource groups`, I can't see a way to follow terraform best practice with isolated environments on IBM Cloud.

**Comment by hkantare** [comment]
We are working to include support for resource and IAM services . We added resource support to create instance and key and datasource to fetch existing resource-group . Our next priority is to add resource support to resource-groups.

**Comment by kskewes** [comment]
Thank you for replying. Sounds promising.

**Comment by hkantare** [comment]
The support for resource groups is implemented and available in master branch. We are planning for release v0.11.0 this week.

**Comment by kskewes** [comment]
Thank you @hkantare. 
I see support for creating clusters in resource groups has just been released. This was what I was initially requesting with this issue but wasn't sure what terminology was. 
Creating VMs and clusters within a resource group.

**Comment by hkantare** [comment]
@kskewes The support for creating cluster in resource groups from API is available recently we are planning to work on it. We will update the ETA soon

**Comment by hkantare** [comment]
The support for resource group for cluster is available as part of v0.12.0

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0

**Comment by kskewes** [comment]
Thanks very much for this. I see the cluster support docs in #389
Is it possible to also add `resource_group_id` for BM and VSI please?

**Comment by hkantare** [comment]
closing the issue...For resource_Group_id we have separate issue to track it https://github.com/IBM-Cloud/terraform-provider-ibm/issues/400
