### ISSUE TITLE
ibm_pi_instance: network_ids are assigned in random order to the instance

### ISSUE THREAD

**Issue by yussufsh** [IBM-Cloud/terraform-provider-ibm#1910]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.X and 0.13.X

### Affected Resource(s)
- ibm_pi_instance

### Terraform Configuration Files
```hcl
data "ibm_pi_network" "network" {
    pi_network_name         = var.network_name
    pi_cloud_instance_id    = var.service_instance_id
}
resource "ibm_pi_network" "public_network" {
    pi_network_name         = "pub-net"
    pi_cloud_instance_id    = var.service_instance_id
    pi_network_type         = "pub-vlan"
    pi_dns                  = var.network_dns
}
resource "ibm_pi_instance" "bastion" {
    pi_memory               = var.memory
    pi_processors           = var.processors
    pi_instance_name        = "bastion"
    pi_proc_type            = var.processor_type
    pi_image_id             = data.ibm_pi_image.bastion.id
    pi_network_ids          = [ibm_pi_network.public_network.network_id, data.ibm_pi_network.network.id]
    pi_key_pair_name        = ibm_pi_key.key.key_id
    pi_sys_type             = var.system_type
    pi_cloud_instance_id    = var.service_instance_id
}
```

### Debug Output
Unable to access the machine via public network.

### Panic Output
None.

### Expected Behavior
Networks should get assigned in order. Since 1st network id provided in public network default route should be on public gateway.

### Actual Behavior
TF use network ids as set and sorts on string. This behaviour changes the order of network interfaces randomly. If the first interface is public then we have internet access. If the first interface is private we do not have internet access.

### Steps to Reproduce
Provide set of pi_network_ids in same order and run below steps on different resources and observe the pi_network_ids order always sorted.
1. `terraform apply`

**Comment by surajsub** [comment]
Let me test this as well to make sure it does not break our code
