### ISSUE TITLE
AutoScaleGroup update error

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM-Cloud/terraform-provider-ibm#1915]
Hi @Anil-CM , as we've discussed when I tried to update ig membership and igm min members from 200 to 500, then I got the below error. Anything I am doing wrong?

The provider that I used is from the PR branch: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/1906

To work around this update failure, I destroyed and recreated the AutoScale group.

variables assigned in `terraform.tfvars`
```
refix = "asg-nwk-2214"
# ig_count            = 1
ig_membership_count = 500
igm_min_members     = 500
igm_max_members     = 1000

utilization = 50
```

```

Error: Error updating InstanceGroup manager: if creating or updating manager, instance group membership count must be within the manager range
{
    "StatusCode": 400,
    "Headers": {
        "Cache-Control": [
            "max-age=0, no-cache, no-store, must-revalidate"
        ],
        "Cf-Cache-Status": [
            "DYNAMIC"
        ],
        "Cf-Ray": [
            "5d763d39dfc5273a-DEN"
        ],
        "Cf-Request-Id": [
            "055dc4982b0000273aa3030200000001"
        ],
        "Connection": [
            "keep-alive"
        ],
        "Content-Length": [
            "378"
        ],
        "Content-Type": [
            "application/json; charset=utf-8"
        ],
        "Date": [
            "Wed, 23 Sep 2020 18:13:21 GMT"
        ],
        "Expect-Ct": [
            "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
        ],
        "Expires": [
            "-1"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Server": [
            "cloudflare"
        ],
        "Set-Cookie": [
            "__cfduid=dc196b2631906edbc66ef9c565d75c4821600884801; expires=Fri, 23-Oct-20 18:13:21 GMT; path=/; domain=.iaasdev.cloud.ibm.com; HttpOnly; SameSite=Lax; Secure"
        ],
        "Strict-Transport-Security": [
            "max-age=31536000; includeSubDomains"
        ],
        "Vary": [
            "Accept-Encoding"
        ],
        "X-Content-Type-Options": [
            "nosniff"
        ],
        "X-Request-Id": [
            "2f17f4e3-6fbe-4b64-96cd-0e3fe8bd9729"
        ],
        "X-Xss-Protection": [
            "1; mode=block"
        ]
    },
    "Result": {
        "errors": [
            {
                "code": "admission_membership_count_not_in_manager_range",
                "message": "if creating or updating manager, instance group membership count must be within the manager range",
                "more_info": "InstanceGroup validation: MembershipCount=200 not in enabled manager range 500-1000",
                "target": {
                    "name": "membership_count",
                    "type": "field"
                }
            }
        ],
        "trace": "2f17f4e3-6fbe-4b64-96cd-0e3fe8bd9729"
    },
    "RawResult": null
}


  on main.tf line 157, in resource "ibm_is_instance_group_manager" "instance_group_manager":
 157: resource "ibm_is_instance_group_manager" "instance_group_manager" {


```

**Comment by Anil-CM** [comment]
Hi @syyang-in-cloud, the configurations you are using, `ig_membership_count = 500` and `igm_max_members     = 1000`

instance group is having 200 instances managed and you are trying to manage 500 to 1000 instances from the same instance group. 
The igm_min_members > current instance count. This is causing the error.

Incase if you want to have the same range that you are trying out, you need to do the below steps:
```
1. Disable the instance group manager by updating `enable_manager` to False
2. Update the instance group `instance_count` to 1000 and update instancegroup manager with these values igm_min_members  = 500
igm_max_members = 1000
```

**Comment by syyang-in-cloud** [comment]
> Hi @syyang-in-cloud, the configurations you are using, `ig_membership_count = 500` and `igm_max_members = 1000`
> 
> instance group is having 200 instances managed and you are trying to manage 500 to 1000 instances from the same instance group.
> The igm_min_members > current instance count. This is causing the error.
> 
> Incase if you want to have the same range that you are trying out, you need to do the below steps:
> 
> ```
> 1. Disable the instance group manager by updating `enable_manager` to False
> 2. Update the instance group `instance_count` to 1000 and update instancegroup manager with these values igm_min_members  = 500
> igm_max_members = 1000
> ```

Hi @Anil-CM , thanks for the reply. I understand the procedure. If I use any imperative interface such as CLI, I would do as you've described. However, the procedure you've mentioned is similar to what CLI does when that destroys AutoScale group, but we don't follow the procedure to terraform destroy. Terraform built around `declarative` convention not `imperative`. 

It's a little hard to agree with you to update terraform resources using those procedures. What do you think?

**Comment by deepaksibm** [comment]
Hi @syyang-in-cloud , can this issue be closed ?

**Comment by syyang-in-cloud** [comment]
> Hi @syyang-in-cloud , can this issue be closed ?

Hi @deepaksibm , I won't be able to follow this issue. You can close.

**Comment by deepaksibm** [comment]
Hi @kavya498 @astha-jain We can close this issue.
