### ISSUE TITLE
Not able to provision subnet using terraform with an earlier working configuration.

### ISSUE THREAD

**Issue by umar201290** [IBM-Cloud/terraform-provider-ibm#1918]
Hello Team. 

Below is my terraform configuration and it is not able to provision subnet. earlier the same code worked in different account.

main.tf content :-
### Create Private Subnets ###
resource "ibm_is_subnet" "private_subnet" {
  name            = "app-subnet"
  vpc             = "r022-023ca402-ee92-4de0-9df3-552a2d472088"
  zone            = "jp-tok-1"
  ipv4_cidr_block = "172.24.1.0/24"
}

providers.tf content :-

provider "ibm" {
  version          = "~> 1.11.2"
  ibmcloud_api_key = "my-key"
  generation       = 2
  region           = "jp-tok"
}

Note : I am able to create through UI
error message :-

ibm_is_subnet.private_subnet: Creating...

Error: Error while creating Subnet resource group is not active
{
    "StatusCode": 400,
    "Headers": {
        "Cache-Control": [
            "max-age=0, no-cache, no-store, must-revalidate"
        ],
        "Cf-Cache-Status": [
            "DYNAMIC"
        ],
        "Cf-Ray": [
            "5d81d9724ad6172c-SIN"
        ],
        "Cf-Request-Id": [
            "0565063b6a0000172c033fb200000001"
        ],
        "Connection": [
            "keep-alive"
        ],
        "Content-Length": [
            "122"
        ],
        "Content-Type": [
            "application/json; charset=utf-8"
        ],
        "Date": [
            "Fri, 25 Sep 2020 04:02:25 GMT"
        ],
        "Expect-Ct": [
            "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
        ],
        "Expires": [
            "-1"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Server": [
            "cloudflare"
        ],
        "Set-Cookie": [
            "__cfduid=d7ba43a6d8353efcd03d1b48eb48e00771601006543; expires=Sun, 25-Oct-20 04:02:23 GMT; path=/; domain=.iaas.cloud.ibm.com; HttpOnly; SameSite=Lax; Secure"
        ],
        "Strict-Transport-Security": [
            "max-age=31536000; includeSubDomains"
        ],
        "Vary": [
            "Accept-Encoding"
        ],
        "X-Content-Type-Options": [
            "nosniff"
        ],
        "X-Request-Id": [
            "45712ae6-df2c-41d8-b329-fdc058c08dd1"
        ],
        "X-Trace-Id": [
            "4cf3dc51d43788cd"
        ],
        "X-Xss-Protection": [
            "1; mode=block"
        ]
    },
    "Result": {
        "errors": [
            {
                "code": "bad_field",
                "message": "resource group is not active"
            }
        ],
        "trace": "45712ae6-df2c-41d8-b329-fdc058c08dd1"
    },
    "RawResult": null
}

  on main.tf line 2, in resource "ibm_is_subnet" "private_subnet":
   2: resource "ibm_is_subnet" "private_subnet" {

**Comment by hkantare** [comment]
From the error its issue with your resource group
```
"resource group is not active"
```

**Comment by umar201290** [comment]
old issue, closing it.
