### ISSUE TITLE
Destroying CDN resource does not return proper error message

### ISSUE THREAD

**Issue by vijaylakshmi-b** [IBM-Cloud/terraform-provider-ibm#1925]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your % terraform version
Terraform v0.12.28

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_cdn

### Terraform Configuration Files
```hcl
terraform {
  required_version = "0.12"
}

resource "ibm_cdn" "cdn_resource" {
  host_name = "gslCDN-latest.com"
  cname = "testCDNrelease"
  vendor_name = "akamai"
  header = "test.com"
  path = "/cdn"
  origin_address = "10.0.0.9"
  origin_type = "Object Storage"
  protocol = "HTTPS"
  https_port = "443" 
  bucket_name = "testBucket" 
  respect_headers = "On"
  certificate_type="SHARED_SAN_CERT"
  cache_key_query_rule="include-all"
  performance_configuration="General web delivery"
}
```

### Expected Behavior
Deleting a CDN in "CERTIFICATE_REQUESTING" or "DOMAIN_VALIDATION_PENDING" status should return the correct error message returned from the Delete https://api.softlayer.com/rest/v3/SoftLayer_Network_CdnMarketplace_Configuration_Mapping/deleteDomainMapping.json API.

```
{
    "error": "Status [400]: Wrong state. Status is CERTIFICATE_REQUESTING",
    "code": "SoftLayer_Exception"
}
```
### Actual Behavior
Delete returned a successful message.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
