### ISSUE TITLE
Provide a way to reserve external IP without creating an instance

### ISSUE THREAD

**Issue by yussufsh** [IBM-Cloud/terraform-provider-ibm#1930]
Need to provide a way to reserve network addresses on a public network using `ibm_pi_network_port`. Currently, when we create a network_port we can get only a private network address. Our use case needs to know the external/public address associated with that public network port.

### Affected Resource(s)
- ibm_pi_network
- ibm_pi_network_port

### Expected Behavior
When reserving a network port on a public network we should be able to read external IP address as well.

### Actual Behavior
The network port only returns the IP address and no external IP is returned.

### Use case
Our use case is to reserve a network port on a public network. The external IP of the network port will be used as a failover IP in accessing HA services running on multiple VMs with public network.

**Comment by yussufsh** [comment]
cc @bpradipt @surajsub

**Comment by surajsub** [comment]
send me your tf file on slack.. please

**Comment by yussufsh** [comment]
Network port creation via TF is working fine. We are interested in the computed values of the network port. The request here is to have external ip as well incase the network used is public.

**Comment by surajsub** [comment]
Power team will provide a fix for this next week.  Till then -hold your horses

**Comment by yussufsh** [comment]
Great news! Thanks Suraj.

**Comment by lsmcfadden** [comment]
Any updates @surajsub on providing the fix?

**Comment by surajsub** [comment]
Waiting on the power team to push a fix..
