### ISSUE TITLE
Support for encrypted images for VPC

### ISSUE THREAD

**Issue by astha-jain** [IBM-Cloud/terraform-provider-ibm#1938]
@hkantare Image encryption feature is in Beta and enroute to GA. 
https://pages.github.ibm.com/riaas/api-spec/spec_genesis_scoped/#/Images/create_image 
Add support for `encrypted_data_key` and `encryption_key`.

**Comment by hkantare** [comment]
Release in latest release v1.16.0

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_images
