### ISSUE TITLE
key_protect should be renamed to kms_key_crn 

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#1947]
COS bucket supports for Key Protect and Hyper Protect Crypto Services keys which can be provisioned with the `ibm_kms_key` resource.

The parameter should be renamed to match the new `ibm_kms_key` resource that should be used in place of `ibm_kp_key`.

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/53d5b98be197f11fb472305681c053216b1389a4/ibm/resource_ibm_cos_bucket.go#L74

**Comment by IBM-diksha** [comment]
This issue has been fixed in the latest release(v1.55.0).
Thank you.
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.55.0
