### ISSUE TITLE
Feature Request: Data Source For service-instances

### ISSUE THREAD

**Issue by schmidtuconn** [IBM-Cloud/terraform-provider-ibm#195]
Hi there,

### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
N/A

### Expected Behavior
ibm_service_instance

Argument Reference
The following arguments are supported:
    name - (Required, string) The name of the service instance. You can retrieve the value by running the `bx resource service-instances` command in the IBM Cloud CLI.

### Actual Behavior
This behavior does not exist. A service like AppId is an IAM service instead of a Cloud Foundry service. I have cloud foundry apps which need to bind to the App Id instance. This App Id instance is not listed with `bx service list` but instead `bx resource service-instances`

**Comment by hkantare** [comment]
we are working on providing support for resource_instances in provider.

**Comment by hkantare** [comment]
We provided support for following IAM and resource controller API's. 
Can you please try with  latest v0.10.0 binary https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.10.0

# **Resource API**

## **Data sources**
ibm_resource_group
ibm_resource_instance
ibm_resource_key

## **Resources**
bm_resource_instance
ibm_resource_key

# **IAM API**

## **Data sources**
ibm_iam_user_policy
ibm_iam_service_id
ibm_iam_service_policy

## **Resources**
ibm_iam_user_policy
ibm_iam_service_id
ibm_iam_service_policy
