### ISSUE TITLE
Capability to provision with vlan with /25 and above subnet

### ISSUE THREAD

**Issue by surajsub** [IBM-Cloud/terraform-provider-ibm#196]
When the subnet_size is provided as /25 ( 128)  , get a response with this message . Is this a limitation in the tf code or an issue with credential / account where we cannot request a vlan with  > /25 subnet . 

Thoughts on potential fixes 

```
* ibm_network_vlan.test_vlan_suraj: 1 error(s) occurred:
* ibm_network_vlan.test_vlan_suraj: Error creating vlan: No product items matching 128_STATIC_PUBLIC_IP_ADDRESSES could be found
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
```

### Terraform Version
0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
ibm_network_vlan

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
## Added the provider version

variable "datacenter" {
	description = "Target vSphere datacenter for Virtual Machine creation"
}

variable "subnet_size" 
{
description="Size of the subnet"
}



provider ibm {
version="0.8"
} 



resource "ibm_network_vlan" "test_vlan_suraj" {
   name = "test_vlan_suraj"
   datacenter = "${var.datacenter}"
   type = "PUBLIC"
   subnet_size = "${var.subnet_size}"
   
}




output "id" {
  value = "${ibm_network_vlan.test_vlan_suraj.id}"
}
output "vlan_number" {
value = "${ibm_network_vlan.test_vlan_suraj.vlan_number}"
}
output "subnets" {
  value = "${ibm_network_vlan.test_vlan_suraj.test1.subnets}"
}


```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the 
```
No panic log
```

**Comment by surajsub** [comment]
The api doc  states that ..
subnet_size - (Required, integer) The size of the primary subnet for the VLAN. Accepted values are 8, 16, 32, and 64.
Are these the one sizes supported ?

**Comment by hkantare** [comment]
Yes those are subnet_size supported

**Comment by surajsub** [comment]
what if i want more than 64 ?

**Comment by hkantare** [comment]
From UI are you able to request more than 64?Even with our account we are not able to request more than 64 . We tried softlayer_API to list prices for network_VLAN 
```
583 - 8 Static Public IP Addresses --- 8_STATIC_PUBLIC_IP_ADDRESSES
	203603 - locationGroupId: 
1072 - Private Network Vlan --- PRIVATE_NETWORK_VLAN
	203703 - locationGroupId: 509
	203713 - locationGroupId: 505
	203733 - locationGroupId: 545
	203693 - locationGroupId: 503
	203743 - locationGroupId: 
	203723 - locationGroupId: 507
1071 - Public Network Vlan --- PUBLIC_NETWORK_VLAN
	203663 - locationGroupId: 507
	203673 - locationGroupId: 545
	203683 - locationGroupId: 
	203653 - locationGroupId: 505
	203643 - locationGroupId: 509
	203633 - locationGroupId: 503
586 - 64 Static Public IP Addresses --- 64_STATIC_PUBLIC_IP_ADDRESSES
	203623 - locationGroupId: 
584 - 16 Static Public IP Addresses --- 16_STATIC_PUBLIC_IP_ADDRESSES
```
We are not able to get any price item related to 128.I'm thinking may be it could  be account level restriction. I will check with softlayer support team and will update more

**Comment by hkantare** [comment]
I checked with support team they says subnet size greater that 64 requires customer to raise a support ticket then the internal team will help .
```
That is because subnet size larger than that will require a manual review from the network team.
```

**Comment by surajsub** [comment]
I will close this for now .
