### ISSUE TITLE
Give the ability to retrieve the instances in a specific VPC or subnet

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#1961]
`data ibm_is_instances` return all virtual server instances in the account. In most cases one will want to focus on a single VPC or a single subnet.

The data resource should have optional vpc_id or subnet_id input parameter to filter the list of retrieved instances.

### Affected Resource(s)
- ibm_is_instances

**Comment by l2fprod** [comment]
@hkantare any plan to include this? ibm_is_instances return all instances now which may end up being a lot!

My use case is to apply a security group (bastion) to all existing instances in a VPC. I can do it by filtering on the ibm_is_instances using a for/if in terraform but loading all instances in the account is inefficient

**Comment by hkantare** [comment]
We will plan in next sprint

**Comment by hkantare** [comment]
Released in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.20.0
Cloud docs will be updated soon
Registry docs:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs

**Comment by hkantare** [comment]
closing the issue
