### ISSUE TITLE
No Support for HTTPS protocol in load balancer pool

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#1968]
Hi there,

I am trying to enable end-to-end encryption by enabling HTTPS on load balancer pool protocol and Health protocol. But it fails with the below error 

```
Error: "protocol" must contain a value from []string{"http", "tcp"}, got "https"

  on main.tf line 143, in resource "ibm_is_lb_pool" "lb-pool":
 143: resource "ibm_is_lb_pool" "lb-pool" {

Error: "health_type" must contain a value from []string{"http", "tcp"}, got "https"

  on main.tf line 143, in resource "ibm_is_lb_pool" "lb-pool":
 143: resource "ibm_is_lb_pool" "lb-pool" {
```

### Terraform Version
Terraform v0.13.4
+ provider registry.terraform.io/ibm-cloud/ibm v1.13.1

Reproducible with `v0.12.29` of Terraform

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_lb_pool
- ibm_is_lb_listener
- ibm_is_lb

### Expected Behavior
As the load balancer UI and `is` CLI plugin supports HTTPS expect the same behaviour here as well

### Actual Behavior
Fails as HTTPS is not supported

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a load balancer, load balancer listener and a load balancer pool using the below code snippet

```
resource "ibm_is_lb_pool" "lb-pool" {
  lb                 = ibm_is_lb.lb.id
  name               = "test-lb-pool"
  protocol           =  "https" 
  algorithm          = "round_robin"
  health_delay       = "15"
  health_retries     = "2"
  health_timeout     = "5"
  health_type        =  "https"
  health_monitor_url = "/"
}

```
2. terraform apply

**Comment by hkantare** [comment]
We support for HTTPS protocol in latest releases from v1.15.0 and above
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/is_lb_pool.html.markdown
