### ISSUE TITLE
Feature: Write certificate to file for ICD datasources

### ISSUE THREAD

**Issue by hasueki** [IBM-Cloud/terraform-provider-ibm#1985]
For ICD datasources, I would like for the provider to write ICD provided certificates to local file so that this file path can be referenced in other resources. Currently, the ICD datasource only returns a base64 encoded certificate string as part of the connection strings. 

My use case:
I am using the provider to provision an ICD instance (PostgreSQL to be exact) and wanting to use the [PostgreSQL provider](https://www.terraform.io/docs/providers/postgresql/index.html) to manage PostgreSQL resources. When instantiating the PostgreSQL provider, it requires to pass in an absolute path for the certificate, given that all ICD instances are TLS enabled.

**Comment by hkantare** [comment]
Fixed in latest 1.14.0 release
https://cloud.ibm.com/docs/terraform?topic=terraform-databases-data-sources#database-output

**Comment by hasueki** [comment]
Execellent, thank you!
