### ISSUE TITLE
Request: ibm_container_bind_service should support key ID in addition to key name

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#2021]
### Affected Resource(s)
- ibm_container_bind_service

### Expected Behavior
When binding or unbinding a service using an existing key, it should run without error.

### Actual Behavior
When there are multiple service keys with the name, binding and unbinding runs into problems.

### Important Factoids
There can be multiple keys with different IDs. Having just the key name is easy to use, but sometimes the actual key ID / GUID would make destroying the binding simpler.

**Comment by hkantare** [comment]
The current argument "key" can take both name and guid of the service key...Raised PR to make documentation more specific and will be available in next release
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3450
