### ISSUE TITLE
Directlink Gateway terraform provider got broken

### ISSUE THREAD

**Issue by KumarGanesanIBM** [IBM-Cloud/terraform-provider-ibm#2036]
Hi there,

There is compilation issue seen in this file `ibm/resource_ibm_dl_gateway.go`.  this compilation issue is fixed as part of below PR
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2033
Not sure, whether it is correct and did not check the functionality for this changes.

### Panic Output
NA

### Expected Behavior
should compile properly and there won't be any breakage

### Actual Behavior
compilation issue

### Steps to Reproduce
NA

### References
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2033

**Comment by hkantare** [comment]
Fixed
