### ISSUE TITLE
Unable to create new cluster

### ISSUE THREAD

**Issue by bensullivan** [IBM-Cloud/terraform-provider-ibm#204]
Hi

I started using IBM Cloud a couple of days ago.  I have used Terraform with AWS in the past.  I'm trying to create a free cluster in ap-south region (Terraform v0.11.7 with version 0.8.0 of the IBM provider) and seeing this error:

```
ibm_container_cluster.cluster: Creating...
  account_guid:      "" => "003dab982ad91ba5f88aaf375b2dc22d"
  billing:           "" => "hourly"
  datacenter:        "" => "syd04"
  ingress_hostname:  "" => "<computed>"
  ingress_secret:    "<sensitive>" => "<sensitive>"
  isolation:         "" => "public"
  kube_version:      "" => "<computed>"
  machine_type:      "" => "free"
  name:              "" => "egregore"
  no_subnet:         "" => "true"
  server_url:        "" => "<computed>"
  wait_time_minutes: "" => "90"
  worker_num:        "" => "<computed>"
  workers.#:         "" => "1"
  workers.0.action:  "" => "add"
  workers.0.id:      "" => "<computed>"
  workers.0.name:    "" => "worker1"
  workers.0.version: "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.cluster: 1 error(s) occurred:

* ibm_container_cluster.cluster: Request failed with status code: 403, ServerErrorResponse: {"incidentID":"a807e281-6dbc-4ac9-b38e-509929481c7c","code":"E0013","description":"The free cluster limit is reached. Create a standard cluster.","type":"Provisioning"}
```

bluemix is telling me there are no clusters on my account so I'm not sure why this is happening:

```
$ bx cs clusters
OK
Name   ID   State   Created   Workers   Location   Version
```

Could you please advise?

Thanks

Ben

**Comment by bensullivan** [comment]
Yeah you're right - the error does clearly state the the free cluster limit has been reached.  The problem is the error message is clearly wrong.  I have no clusters created in the Sydney location as the response from ```bx cs clusters``` clearly states (see orginial post).  

Why can't I create a free cluster using your terraform plugin?

**Comment by Praveengostu** [comment]
Are you able to create it using bx? And what is the region you had set in the provider IBM . The default region is "us-south"

**Comment by bensullivan** [comment]
OK so even though I had set the required datacenter to syd04, the default region of us-south was being used on the provider and the datacenter was defaulting to us-south-hou02.  Perhaps some validation should be in place here to inform user of invalid combination of region/datacenter?  I can create a cluster now in us-south region.  Terraform reports it taking just shy of 19min.  Is that performance expected for creating clusters?  My terraform provider and resource now look like this sensitive values have been obfuscated):

```
provider "ibm" {
  region="ap-south"
}

resource "ibm_container_cluster" "cluster" {
  name = "XXXX"
  datacenter = "syd04"
  account_guid = "YYYYYY"
  no_subnet = true
  workers = [
    {
      name = "worker1"
      action = "add"
    }
  ]
  machine_type = "free"
  isolation = "public"
}
```

I am now getting the following error for ```terraform apply```:

```
Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.cluster: 1 error(s) occurred:

* ibm_container_cluster.cluster: Error occured while configuring Container Service for K8s cluster: "ServiceEndpointDoesnotExist: IAM  endpoint doesn't exist for region: \"ap-south\
```

If IAM doesn't exist for ap-south, why does it exist for us-south?

I need to create my cluster in Sydney...

How do I create an IAM endpoint for ap-south?

Thanks

Ben

**Comment by Praveengostu** [comment]
@bensullivan Could you please share us the output of `bx target`

**Comment by Praveengostu** [comment]
@bensullivan The bx cli target is region is pointed to au-syd. Could you please try setting the region to au-syd in provider and let us know

provider "ibm" {
  region="au-syd"
}

**Comment by Praveengostu** [comment]
@bensullivan Are you still facing this issue after setting the region in provider?

**Comment by hkantare** [comment]
Closing this for now .If you find any issue please reopen
