### ISSUE TITLE
terraform support for IBM secrets manager

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2054]
Secrets manager support:
- Secrets manager instance
- Secret group
- Secrets

**Comment by jbaskeen** [comment]
Also have a use case here 👍

**Comment by JorgeHernandezRamirez** [comment]
this will be useful for me either! Hope it will be come soon :)

**Comment by palcoberro** [comment]
Needed for me as well, please take consideration to this issue 🙏

**Comment by bernardoarnaizgarcia** [comment]
Useful for me too. Take it in consideration please¡¡

**Comment by l2fprod** [comment]
This should also include all Secrets Manager configuration options -- like configuring the IAM Credentials engine

**Comment by wosteven** [comment]
We will need this also soon, we have ~60 Cert Manager instances  which we need to migrate to SM. We would require:
- Create instance
- Create secret groups
- Create secrets
- Ideally also: Create/Configure secrets engine (IAM And public certs (DNS providers (esp. CIS) /Certificate Authorities (esp. Let's Encrypt))

**Comment by l2fprod** [comment]
```hcl
resource "ibm_resource_instance" "secrets-manager" {
  name              = "secrets-manager-global"
  service           = "secrets-manager"
  plan              = "standard"
  location          = "us-south"
  resource_group_id = ibm_resource_group.dev.id

  tags = var.tags
}
```

works to create Secrets Manager instance

**Comment by IdanAdar** [comment]
The Secrets Manager provider has been released.
