### ISSUE TITLE
Question: Does the IBM Terraform provider support Terraform 13 and/or 14 yet?

### ISSUE THREAD

**Issue by mschenk42** [IBM-Cloud/terraform-provider-ibm#2092]
If it's not currently supported, when is support likely to be added? Thanks.

**Comment by hkantare** [comment]
@mschenk42 Already we support Terraform v0.13
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest

**Comment by hkantare** [comment]
closing the issuewith above comments
