### ISSUE TITLE
Update ibm_container_alb_cert to match new ingress controller requirement

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#2097]
Hello there,

Since 1st december, IKS provision an standard kubernetes ingress controller.

Therefore, some changes needs to be done, especially, the location of certificates.

- Before 1st december: ingress controller was able to access `ibm-cert-store` namespace.
- After 1st december: ingress controller can only access the namespace where you provision the ingress.

![image](https://user-images.githubusercontent.com/50360031/101465571-6596bd80-3940-11eb-8b09-e7e4b8808dc9.png)

Source: https://cloud.ibm.com/docs/containers?topic=containers-ingress-types

Having said that, we need to have a `namespace` property as an input, to manage the target of the certificate copies in the cluster.

**Comment by ifs-pauljegouic** [comment]
@hkantare

**Comment by hkantare** [comment]
We are analysing the issue

**Comment by kavya498** [comment]
Available in latest[ 1.18.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.18.0)

**Comment by kavya498** [comment]
Can we close this issue?

**Comment by Nashluffy** [comment]
As a part of this, shouldn't the `terraform import` command be updated to allow namespace specification?

For example,

```
terraform import certificate.ibm_container_alb_cert.cert <cluster-id>/<namespace>/<secret-name>
```

**Comment by hkantare** [comment]
we are closing the issue since the feature is a vaialble long back and docs updated accordingly
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_alb_cert#import
