### ISSUE TITLE
vpc-gen2 Request for support for addons for kubernetes service resources 

### ISSUE THREAD

**Issue by danej1** [IBM-Cloud/terraform-provider-ibm#2116]
Requesting the re-add of the ability to configure for addons for kubernetes service resources in the terraform as it was for gen1.

Specifically, we are trying to have istio addon preconfigured in our terraform.

### Terraform Version
Gen2 

### Important Factoids
While we are interested in the istio addon, this is the full list of addons I'm refering to:
alb-oauth-proxy
cluster-autoscaler
debug-tool
hpcs-router
image-key-synchronizer
istio
knative
kube-terminal
openshift-container-storage
static-route
vpc-block-csi-driver

### References
Previously this was available to configure the terraform for resources.addons
https://cloud.ibm.com/docs/terraform?topic=terraform-container-resources#container-addons

**Comment by danej1** [comment]
Hi,
I’ll look at this monday again….but my I guess I wasn’t clear in my request.  
The terraform for gen1 allows the syntax for addons when creating the cluster.  are you saying it works the same in gen2?
I was told otherwise, hence the issue.

Regards,
-Dane

**Comment by kavya498** [comment]
`ibm_container_addons` resource works across all types of `clusters classic`, `vpc-gen2`,` openshift`.

**Comment by hkantare** [comment]
closing the issue based on comments
