### ISSUE TITLE
Feature: Terraform script to set and reset the ks api-key

### ISSUE THREAD

**Issue by indirakalagara** [IBM-Cloud/terraform-provider-ibm#2118]
Hi Team,

Customer is looking for the  terraform equivalent of the following ibmcloud cli command  to set "ks api-key"  
ibmcloud ks api-key reset --region <region>

https://cloud.ibm.com/docs/containers?topic=containers-users#api_key_most_cases

Request you to add this feature on priority to address the customer needs.

**Comment by kavya498** [comment]
Available in Latest [1.19.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.19.0)

**Comment by hkantare** [comment]
closing the issue
