### ISSUE TITLE
Feature: Terraform resource to add  icr namespace

### ISSUE THREAD

**Issue by indirakalagara** [IBM-Cloud/terraform-provider-ibm#2119]
Hi team ,  

Customer is looking for the  terraform resource to create ibm container registry (icr)  namespace. 

Please add the terraform equivalent for the following ibmcloud cli command

  "ibmcloud cr namespace-add <my_namespace> "   
  
  https://cloud.ibm.com/docs/Registry?topic=Registry-getting-started#gs_registry_namespace_add

Request you to add this feature on the priority .

**Comment by kavya498** [comment]
@indirakalagara , available in latest [1.19.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.19.0)

**Comment by hkantare** [comment]
closing the issue
