### ISSUE TITLE
Feature: Enable Cluster cluster-autoscaler add-on using terraform

### ISSUE THREAD

**Issue by indirakalagara** [IBM-Cloud/terraform-provider-ibm#2120]
Hi Team,

Customer is looking for enabling the auto-scaling feature using the terraform script.

https://cloud.ibm.com/docs/containers?topic=containers-ca

From the existing add-ons on ibm_container_addons , there is no cluster-autoscaler is available.
https://cloud.ibm.com/docs/terraform?topic=terraform-container-resources#container-addons

Request you to add this feature for the IBM terraform provider

**Comment by maristgeek** [comment]
It's not provided in documented examples but nothing needs to be added to the provider to support that particular addon. In the `ibm_container_addons` resource you configure any number of addons available through the API. We use a configuration like these in multiple clusters.


```hcl
resource "ibm_container_addons" "apis_cluster" {
  cluster           = ibm_container_cluster.apis.id
  resource_group_id = data.ibm_resource_group.resource_group.id

  addons {
    name    = "cluster-autoscaler"
    version = "1.0.1"
  }

  timeouts {
    create = "30m"
  }
}
```

**Comment by indirakalagara** [comment]
Can you please help  me with  the updated document for this ? I am not able to find the cluster-autosacler in this document  https://cloud.ibm.com/docs/terraform?topic=terraform-container-resources#container-addons

**Comment by hkantare** [comment]
Hi Indira
The cloud docs is not yet updated we will update in next week...Meanwhile you can refer the registry docs 
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_addons

```
 addons {
    name    = "vpc-block-csi-driver"
    version = "2.0.3"
  }
  ```

**Comment by indirakalagara** [comment]
Thank you Harini for the quick update.
