### ISSUE TITLE
The ibm-hpcs-crypto example requires manual cleanup before destroy.

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM-Cloud/terraform-provider-ibm#2123]
Issue: The example `ibm-hpcs-crypto`: `terraform destroy` failure due to the cryptounits were not zeroized.

```
ibm_resource_instance.hpcs_instance[0]: Destroying... [id=crn:v1:staging:public:hs-crypto:us-south:a/3771957022b64706b0dc1c92b5153c20:467b9bf3-d432-4d36-8d9e-448436858907::]

Error: Error deleting resource instance: Request failed with status code: 400, ServerErrorResponse: {"error_code":"RC-ServiceBrokerErrorResponse","message":"Service Broker returned error status code 409","details":"[{\"description\":\"There are still domains configured with a master key. Use the IBM Cloud CLI tke plugin to zeroize the domains.\",\"error\":\"HsmStateError\"}]","status_code":400,"transaction_id":"bss-b398a859ff677865"}

```

Definition of Done:
add a lifecycle of `delete` to `zeroize` the cryptounits for the HPCS service instance.

**Comment by syyang-in-cloud** [comment]
It's not an urgent issue, just we need to address to destroy the terraform `resource_instance` properly at certain point.

**Comment by kavya498** [comment]
new resource has been developed for hpcs..[ibm_hpcs](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/hpcs)
Closing this issue as this example is no longer available..
Thanks..
