### ISSUE TITLE
Support for cis Page rules

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#2130]
Hello there,

We would like to have the opportunity to manage our Page Rules configuration within a CIS DOmain through Terraform.

Regards

**Comment by ifs-pauljegouic** [comment]
Great.

Which documentation source are you recommending ? 
https://cloud.ibm.com/docs/terraform?topic=terraform-cis-resources
Or terraform registry doc ?

**Comment by kavya498** [comment]
Docs is available in terraform registry..
We ll update in cloud docs soon..
