### ISSUE TITLE
Migrate all cis resources to v4 version of go-sdk-core

### ISSUE THREAD

**Issue by kavya498** [IBM-Cloud/terraform-provider-ibm#2138]
In order to main consistency across all cis resources.. Migrate all cis resources to v4 version of `go-sdk-core`

**Comment by KumarGanesanIBM** [comment]
Issue - https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2138
PR - https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2139

**Comment by KumarGanesanIBM** [comment]
code was merged
