### ISSUE TITLE
Missing jp-osa endpoints make the bucket creation fail

### ISSUE THREAD

**Issue by blacksd** [IBM-Cloud/terraform-provider-ibm#2149]
### Terraform Version
```txt
Terraform v0.14.2
+ provider registry.terraform.io/ibm-cloud/ibm v1.18.0
```

### Affected Resource(s)
- ibm_cos_bucket

### Terraform Configuration Files
```hcl
resource "ibm_cos_bucket" "standard" {
  bucket_name          = "test"
  resource_instance_id = ibm_resource_instance.cos_instance.id
  storage_class        = "smart"
  region_location      = "jp-osa"
}
```

### Expected Behavior
Bucket successfully created, as happened with the Web UI and CLI.

### Actual Behavior
```txt
Error: The endpoint doesn't exists for given location jp-osa and endpoint type public
```

### Steps to Reproduce
`terraform apply` with a configured provider

### References
-  #2148

**Comment by hkantare** [comment]
Released in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.20.0
Cloud docs will be updated soon
Registry docs:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs

**Comment by hkantare** [comment]
closing the issue
