### ISSUE TITLE
Feature request: Hardware firewall (Shared)

### ISSUE THREAD

**Issue by siddharthoak** [IBM-Cloud/terraform-provider-ibm#215]
Hardware Firewall (Shared)
Intended Use: Single Server Primary IP Protection

The Hardware Firewall (Shared) leverages a multi-tenant enterprise platform to protect an individual server.  It can be purchased with the server or added on later.  It delivers virtualized network security through its Virtual Domain (VDOM) technology, providing virtualized security domains that are separately provisioned and managed.  Because there are multiple customers associated with the hardware, if the firewall fails or is overwhelmed by an attack, every customer that shares a Hardware Firewall (Shared) instance may be impacted.  Up to 79 firewall rules can be configured for the for the primary and statically routed IP addresses assigned to the server.  Reports for Shared Firewalls are available based on the activity of a single IP for a selected date range.

**Comment by hkantare** [comment]
Merged the PR 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/hardware_firewall_shared.html.markdown
