### ISSUE TITLE
can't assign iam access group policy to a vpc instance

### ISSUE THREAD

**Issue by Tyrael** [IBM-Cloud/terraform-provider-ibm#2152]
### Terraform Version
```
Terraform v0.14.4
+ provider registry.terraform.io/ibm-cloud/ibm v1.19.0
```

### Affected Resource(s)
- ibm_iam_access_group_policy

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    ibm = {
      source = "IBM-Cloud/ibm"
      version = "~> 1.19.0"
    }
  }
}

provider "ibm" {
  generation         = 2
  region             = "eu-de"
}

data "ibm_iam_access_group" "streaming" {
  access_group_name = "streaming-dev"
}

data "ibm_is_instance" "prometheus" {
  name        = "fra1-prometheus-trans01"
}

resource "ibm_iam_access_group_policy" "group_policy" {
  access_group_id = data.ibm_iam_access_group.streaming.groups.0.id
  roles = ["Administrator"]
  resources {
    service = "is.instance"
    resource_instance_id = data.ibm_is_instance.prometheus.id
  }
}
```

### Debug Output
https://gist.github.com/Tyrael/343f20d37dc2a908a10b54bce825fe38

### Expected Behavior
The group policy should have been created/appended with Administrator role for the streaming-dev iam group for the fra1-prometheus-trans01 vpc gen2 instance

### Actual Behavior
The error provided in the debug output.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I think this is a common enough usecase that this should be covered in the resource documentation, moreso that the is service is a composite service so I was a bit hesitant that I should use service = "is.instance" or simply service = "is" with or without resource_type = "instance"

**Comment by hkantare** [comment]
To assign a policy to IS VPC Instance
```
resource "ibm_iam_access_group" "accgrp" {
  name = "test"
}

data "ibm_resource_group" "group" {
  name = "default"
}

resource "ibm_iam_access_group_policy" "policy" {
  access_group_id = ibm_iam_access_group.accgrp.id
  roles           = ["Viewer"]

  resources {
    service = "is"

    attributes = {
      "instanceId" = "*"
    }

    resource_group_id = data.ibm_resource_group.group.id
  }
}
```

**Comment by Tyrael** [comment]
thank you, I was able to specify the instance this way and the apply completed successfully!

**Comment by hkantare** [comment]
closing the issue based on comments
