### ISSUE TITLE
documentation defect in terraform - Virtual Private Endpoint

### ISSUE THREAD

**Issue by MalarvizhiK** [IBM-Cloud/terraform-provider-ibm#2169]
Just want to point out some errors in the documentation:
resource https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_virtual_endpoint_gateway_ip, the documentation example is wrong. Instead of gateway_id, it should be gateway
Same for:
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-data-sources#vpc-endpoint-gwy-ipsds

**Comment by MalarvizhiK** [comment]
Kumar Ganesan from IBM Cloud Network team spoke to Harini. This issue is related to cloud.ibm.com page. It is handled by geetha_sathyamurthy@in.ibm.com.

**Comment by geemurth** [comment]
Hi @KumarGanesanIBM 

As per our provider repo,  https://github.com/IBM-Cloud/terraform-provider-ibm/blob/v1.20.0/website/docs/d/is_virtual_endpoint_gateway_ips.html.markdown the example stated seems to rightly updated. However, could you please clarify if I have missed any.

@MalarvizhiK the doc team refer the ibm provider repo to update the content. The terraform repo shared https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_virtual_endpoint_gateway_ip,is not used from us.

Regards,
Geetha

**Comment by KumarGanesanIBM** [comment]
@geemurth 
Thanks for the update.

I still see the `gateway_id` in example section of the doc link https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-data-sources#vpc-endpoint-gwy-ipsds.

Please change it to `gateway`.

Thanks,
KumarG.

**Comment by geemurth** [comment]
@KumarGanesanIBM 

Could you please check in this link https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-data-sources#vpc-endpoint-gwy-ipsds  Probably due to the new url for Terraform docs has created this confusion.

Regards,
Geetha

**Comment by kavya498** [comment]
Closing based on above comments
