### ISSUE TITLE
Transit gateway Connection creation fails for cross account 

### ISSUE THREAD

**Issue by pinky-bhargava** [IBM-Cloud/terraform-provider-ibm#2170]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.26

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_tg_connection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
 ibm_tg_connection.tg_connection must be replaced
-/+ resource "ibm_tg_connection" "tg_connection" {
      ~ connection_id      = "abbe8f91-1858-41ce-bcd8-7c64e4970e92" -> (known after apply)
      ~ created_at         = "2021-01-14T16:53:40.930Z" -> (known after apply)
      ~ id                 = "df8a83a8-2fd5-4bc1-a22b-b46eeeb731bc/abbe8f91-1858-41ce-bcd8-7c64e4970e92" -> (known after apply)
        name               = "transit-gateway-connection"
      - network_account_id = "72cbd8dc47ae35c60c925005d212fdbc" -> null # forces replacement
      ~ related_crn        = "crn:v1:bluemix:public:transit:us-east:a/1b0834ebce7f4b94983d856f532ebfe2::gateway:df8a83a8-2fd5-4bc1-a22b-b46eeeb731bc" -> (known after apply)
      ~ status             = "attached" -> (known after apply)
      ~ updated_at         = "2021-01-14T16:56:12.167Z" -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
tg connection should get created successfully

### Actual Behavior
ibm_tg_connection.tg_connection: Still creating... [9m50s elapsed]
ibm_tg_connection.tg_connection: Still creating... [10m0s elapsed]
Error: timeout while waiting for state to become 'attached, ' (last state: 'pending', timeout: 10m0s)
  on network_structure.tf line 628, in resource "ibm_tg_connection" "tg_connection":
 628: resource "ibm_tg_connection" "tg_connection"{

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by pinky-bhargava** [comment]
PR : https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2179 - Merged and hence closing this issue

**Comment by hkantare** [comment]
Released in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.20.0
Cloud docs will be updated soon
Registry docs:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs
