### ISSUE TITLE
Cannot import database resources in `eu-de` region

### ISSUE THREAD

**Issue by drjeep** [IBM-Cloud/terraform-provider-ibm#2177]
We can import database resources from the `eu-gb` region, but when trying to import database resources from the `eu-de` region we get the 500 error below

> Error: Error getting database config for: crn with error Request failed with status code: 500, ServerErrorResponse: {"status":500,"error":"Internal Server Error"}

### Terraform Version
Terraform v0.12.24
+ provider.ibm v1.19.0

### Affected Resource(s)
- ibm_database

### Terraform Configuration Files
```hcl
resource "ibm_database" "this" {
  name                         = "health-eu-db"
  plan                         = "standard"
  location                     = "eu-de"
  service                      = "databases-for-postgresql"
  service_endpoints            = "private"
  version                      = 11
  adminpassword                = var.db_passwd
  members_memory_allocation_mb = "16384"
  members_disk_allocation_mb   = "131072"
}
```

### Expected Behavior
Database resource should be imported to `terraform.tfstate`

### Actual Behavior
Import fails with 500 error

### Steps to Reproduce
1. `terraform import ibm_database.this crn`

**Comment by hkantare** [comment]
We can import the database resources in other region etiher decalring the provider block with region attribute or export region via environmental variable IC_REGION=<region>.
Please refer to import section for more info
https://cloud.ibm.com/docs/terraform?topic=terraform-databases-resources#db-import

**Comment by drjeep** [comment]
Thanks, that was indeed the issue. However, after setting the region I'm getting a different error

> Error: Error getting user connection string for user (admin): Error getting database user connection string via ICD API: Request failed with status code: 404, ServerErrorResponse: {"errors":"not_found"}

**Comment by drjeep** [comment]
After more testing the above error only occurs when importing older databases. Newly created databases in the `eu-de` region import without issues.

**Comment by hkantare** [comment]
Closing the issue ...Please feel to reopen if you still see the issue
