### ISSUE TITLE
ibm_is_instance_template `volume_attachment` Error Creating InstanceGroup: volume not found

### ISSUE THREAD

**Issue by faseyiks** [IBM-Cloud/terraform-provider-ibm#2198]
### Terraform Version
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.19.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_instance_template
- ibm_is_instance_template
- ibm_is_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "ibm_is_volume" "volume" {
  name           = format("%s-volume", var.prefix) 
  profile        = var.iops_profile
  zone           = data.ibm_is_zones.available.zones[var.availability_zone_index]
  resource_group = data.ibm_resource_group.resourcegroup.id
  capacity       = var.volume_capacity
  encryption_key = var.generation == 1 ? ibm_kms_key.kms_key.crn : var.null
  tags           = local.tags
}

resource "ibm_is_instance_template" "instance" {
  name           = format("template-%s", prefix)
  image          = ibm_is_image.image.id
  profile        = var.scaleset_vsi_profile
  vpc            = data.ibm_is_vpc.main.id
  zone           = data.ibm_is_zone.deploy_zone[0].name
  keys           = [var.ssh_key_name]
  resource_group = data.ibm_resource_group.resourcegroup.id

  primary_network_interface {
    name                 = format("interface-%s", var.prefix)
    subnet               = data.ibm_is_subnet.subnet[0].id 
    primary_ipv4_address = true
    security_groups = [
      ibm_is_security_group.asg.id
    ]
  }

  boot_volume {
    delete_volume_on_instance_delete = lookup(var.boot_volume_map, "delete_volume_param")
    encryption                       =  ibm_kms_key.kms_key.instance_id
    iops    = var.iops
    name  = var.name
    profile =var.profile
    size    = var.size
  }

  volume_attachments {
   delete_volume_on_instance_delete = true
   name                             = var.volume_map_name
   volume                           = var.volume_map_volume
  }
}

resource "ibm_is_instance_group" "groups" {
  name              = format("%s-%s", var.prefix, var.environment)
  instance_template = ibm_is_instance_template.template.id
  instance_count    = var.scaleset_instance_count
  subnets           =  [data.ibm_is_subnet.subnet[0].id]
  application_port   = lookup(var.inbound_destination_ports, "https")
  resource_group = data.ibm_resource_group.resourcegroup.id

  timeouts {
    create = "15m"
    delete = "15m"
    update = "10m"
  }
}
```

### Debug Output
ibm_is_instance_template.itemplate: Modifying... [id=.....]
ibm_is_instance_template.itemplate: Modifications complete after 3s [id=....]
ibm_is_instance_group.igroup: Creating...

Error: Error Creating InstanceGroup: volume not found
{
    "StatusCode": 400,
    "Headers": {
        "Cache-Control": [
            "max-age=0, no-cache, no-store, must-revalidate"
        ],
        "Cf-Cache-Status": [
            "DYNAMIC"
        ],
        "Cf-Ray": [
            "616c000dcb05424b-LHR"
        ],
        "Cf-Request-Id": [
            "07d75e5c9c0000424baa185000000001"
        ],
        "Connection": [
            "keep-alive"
        ],
        "Content-Length": [
            "173"
        ],
        "Content-Type": [
            "application/json; charset=utf-8"
        ],
        "Date": [
            "Sun, 24 Jan 2021 19:01:00 GMT"
        ],
        "Expect-Ct": [
            "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
        ],
        "Expires": [
            "-1"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Server": [
            "cloudflare"
        ],
        "Set-Cookie": [
            "__cfduid=d09b360ea769be3d63111ed5a14f4e4261611514856; expires=Tue, 23-Feb-21 19:00:56 GMT; path=/; domain=.iaas.cloud.ibm.com; HttpOnly; SameSite=Lax; Secure"
        ],
        "Strict-Transport-Security": [
            "max-age=31536000; includeSubDomains"
        ],
        "Vary": [
            "Accept-Encoding"
        ],
        "X-Content-Type-Options": [
            "nosniff"
        ],
        "X-Request-Id": [
            "0ec4164f-7842-4cbd-a29e-6bcf74065ed1"
        ],
        "X-Xss-Protection": [
            "1; mode=block"
        ]
    },
    "Result": {
        "errors": [
            {
                "code": "bad_field",
                "message": "volume not found",
                "target": {
                    "name": "volume_attachments[0].volume",
                    "type": "field"
                }
            }
        ],
        "trace": "0ec4164f-7842-4cbd-a29e-6bcf74065ed1"
    },
    "RawResult": null
}

### Expected Behavior
The expected behaviour would be for the instance group instance count to be provisioned and each of the volumes also provisioned appropriately

### Actual Behavior
The behaviour was the error above. This error is seen where you allow the instances created to be spread into more than a single zone by providing multiple subnets to the `instance_group`

When you "disable" subnets spread and ensure the volume is created in the same ZONE as the instance_group, then another errors as below is shown

`Error: Error Creating InstanceGroup: Provided instance_template is invalid
"Result": {
        "errors": [
            {
                "code": "admission_instance_template_invalid",
                "message": "Provided instance_template is invalid",
                "more_info": "InstanceGroup validation: InstanceTemplate Disks[] must not contain ExternalVolumeID",
                "target": {
                    "name": "instance_template",
                    "type": "field"
                }
            }
        ],`

If the volume/volumeId is not provided, then another error is given as below
`"errors": [
            {
                "code": "validation_oneof",
                "message": "Expected only one oneOf fields to be set: got 0",
                "target": {
                    "name": "VolumeAttachmentPrototypeInstanceContextVolume",
                    "type": "field"
                }
            },
            {
                "code": "validation_invalid_field",
                "message": "VolumeIdentity is invalid: Message: Expected only one oneOf fields to be set: got 0 Code: validation_oneof TargetName: VolumeIdentity TargetType: field:: Message: VolumeIdentityByID is invalid: Key: 'VolumeIdentityByID.ID' Error:Field validation for 'ID' failed on the 'required' tag Code: validation_invalid_field TargetName: VolumeIdentityByID TargetType: field:: Message: VolumeIdentityByCrn is invalid: Key: 'VolumeIdentityByCrn.Crn' Error:Field validation for 'Crn' failed on the 'required' tag Code: validation_invalid_field TargetName: VolumeIdentityByCrn TargetType: field:: Message: VolumeIdentityByHref is invalid: Key: 'VolumeIdentityByHref.Href' Error:Field validation for 'Href' failed on the 'required' tag Code: validation_invalid_field TargetName: VolumeIdentityByHref TargetType: field:: ",
                "target": {
                    "name": "VolumeIdentity",
                    "type": "field"
                }
            },
            {
                "code": "validation_invalid_field",
                "message": "VolumePrototypeInstanceContext is invalid: Message: Expected only one oneOf fields to be set: got 0 Code: validation_oneof TargetName: VolumePrototypeInstanceContext TargetType: field:: Message: VolumeByCapacity is invalid: Key: 'VolumeByCapacity.Capacity' Error:Field validation for 'Capacity' failed on the 'required' tag Code: validation_invalid_field TargetName: VolumeByCapacity TargetType: field:: Message: VolumeBySourceSnapshot is invalid: Key: 'VolumeBySourceSnapshot.SourceSnapshot' Error:Field validation for 'SourceSnapshot' failed on the 'required' tag Code: validation_invalid_field TargetName: VolumeBySourceSnapshot TargetType: field:: ",
                "target": {
                    "name": "VolumePrototypeInstanceContext",
                    "type": "field"
                }
            }
        ],`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
my thinking is that the implementation of `volume_attachment` is most probably not quite the way it should have been.  The Volume_Attachment appears to have been borrowed from `ibm_is_instance` where an actual physical resource is created.  `ibm_is_instance_template` does not provision an actual resource but the model for the creation of one.  Therefore it should not seek for a physical storage resource but the model of one.  From the below error, it seems clear to me that it was seeking an actual volume
` "code": "bad_field",
                "message": "volume not found",
                "target": {
                    "name": "volume_attachments[0].volume",
                    "type": "field" `

Let us imagine we are creating 200 instances, then we need to pre-create 200 block storage disks for attachment. There are critical use-cases here that gets problematic
 * Volume creation requires a zone but we may be spreading our instances across all the available zones or at least more than one zone.
 * What could be added to the volume_attachment must be similar to the way boot_volume is implemented. Just to provide the information needed for creating the volumes at creation time of the instance_group itself.

### References
It makes for pragmatism to support exactly the same parameters and attributes that are supported on the CLI for attaching boot and data volume or the flexibility to convert/template the attributes of a physical volume if such exists.

+ boot_volume {
          + delete_volume_on_instance_delete = true
          + encryption                       = (known after apply)
          + iops                             = 3000
          + name                             = "boot-volume"
          + profile                          = "5iops-tier"
          + size                             = 100
        }
...
...
+ volume_attachments {
          + delete_volume_on_instance_delete = true
          + encryption                       = (known after apply)
          + iops                             = 3000
          + name                             = "boot-volume"
          + profile                          = "5iops-tier"
          + size                             = 100
        }

Instead of below that that does provide CLI equivalency
   + volume_attachments {
          + delete_volume_on_instance_delete = (known after apply)
          + name                             = (known after apply)
          + volume                           = (known after apply)
        }

**Comment by deepaksibm** [comment]
https://cloud.ibm.com/docs/vpc?topic=vpc-creating-auto-scale-instance-group#creating-instance-template-cli


instance groups does not support templates that has attached data volumes

**Comment by deepaksibm** [comment]
"volume not found" occurs when the volume id that is assigned is not valid, or not volume is available in the vpc with this ID. 
Probably, volume = var.volume_map_volume, here the assigned ID is not a valid volume id.

**Comment by faseyiks** [comment]
Thanks @deepaksibm.

The point is that it is misleading when on your terraform support page, it shows that volume attachment is supported. See https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance_template#volume_attachments when indeed, this is not a supported feature.  While trying to resolve this I spend considerable effort and incurred significant expenses unnecessarily. Can you remove the below block and correct the terraform documentation page accordingly.

`volume_attachments - (Optional, list) A nested block describing the storage volume configuration for the template. Nested volume_attachments blocks have the following structure:
name - (Required, string) Name of the boot volume.
volume - (Required, string) Storage volume ID created under VPC.
delete_volume_on_instance_delete - (Required, bool) Configured to delete the storage volume to be deleted upon instance deletion.`

**Comment by deepaksibm** [comment]
Hi @faseyiks, 
 
       volume_attachments are supported in instance templates where you use the template to provision instances, and the instances will have the volumes attached, according to the template created. However, When you want to create a template to use within a group, the template should not contain volume attachments. We have added a Note in the docs to make this clearer. Thanks.
