### ISSUE TITLE
enhancement: cos backend

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2210]
Provide a COS backend, identical to the s3 back end: https://www.terraform.io/docs/language/settings/backends/s3.html

```
terraform {
  backend "cos" {
    bucket = "mybucket"
    key    = "path/to/my/key"
    region = "us-west"
  }
}
```

Another cos == s3 request: #2164 

See idea:
- https://bigblue.aha.io/ideas/ideas/CPS-I-277 (sorry this is internal to ibm)

Work around, likely brittle, until this issue is resolved

```
terraform {
  required_version = ">= 0.13.2"
  backend "s3" {
    bucket                      = "fredl-terraforming"
    key                         = "terraform.tfstate"
    region                      = "us-east"
    skip_region_validation      = true
    skip_credentials_validation = true
    # skip_get_ec2_platforms      = true
    # skip_requesting_account_id  = true
    skip_metadata_api_check     = true
    endpoint                    = "s3.us-east.cloud-object-storage.appdomain.cloud"
  }
}
```

**Comment by shawnzhu** [comment]
the work around works, as long as you don't mind creating a new service credential (and a service id, and policies for this id).

I'd love to have this capability to store tfstate file in IBM cloud object storage bucket with API key only (or a JWT token only), it's going to make the terraform experience much better.

**Comment by hkantare** [comment]
Currently Terraform core is not accepting to provide any new backends
https://www.terraform.io/plugin/sdkv2/best-practices/deprecations#renaming-an-optional-attribute
So we don't have any plan to develop Terraform backend

**Comment by strakerpj** [comment]
this used to work but doesn't anymore.   Latest terraform that appears to have supported this was 1.5.7 but newer versions throw an error related to "Retrieving AWS account details".
Was there an updated workaround that allows the storing of terraform in IBM cos backend?

**Comment by nostromo200** [comment]
for newer versions of TF this works

```hcl
terraform {
  required_version = ">= 1.6.3"

  backend "s3" {
    endpoints = {
      s3 = "https://s3.us-south.cloud-object-storage.appdomain.cloud"
    }
    bucket                      = "cos-terraform-backend-bucket"
    key                         = "global.tfstate"
    region                      = "us-south"
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    access_key                  = "xxxxxxxx"
    secret_key                  = "xxxxxxxx"
  }
}
```

**Comment by strakerpj** [comment]
Hi @nostromo200 - thanks for this.  I have tried an upgrade of terraform past 1.5.7 (which I had pinned) and attempted the method you describe.
With your changes to the versions.tf file I have managed to get a successful init as follows:
`terraform init -backend-config="access_key=${ACCESS_KEY}" -backend-config="secret_key=${SECRET_KEY}" -reconfigure`

Looks like the state file cos connectivity issue is now working. Thanks.

**Comment by merlyel** [comment]
`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env variables can be used for backend `access_key` and `secret_key` parameters.

**Comment by maheshd2** [comment]
@nostromo200 @strakerpj @merlyel 
I have a use case where i need to use ibm cos bucket to store terraform state files.

I'm trying to use above syntax as mentioned by @nostromo200
My question are, 
- If it is ibm cos bucket why do we need to provide AWS ACCESS and SECRET keys..?
- I'm trying to provide HMAC access/secret keys generated while creating ibm cos bucket, but terraform init fails with below error.

```
Error: Failed to get existing workspaces: Unable to list objects in S3 bucket "cloudlogs-cos-bucket-data-eu-de" with prefix "env:/": operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: 579d54ab-2882-4cd7-8206-434227190ff6, HostID: , api error InvalidAccessKeyId: The AWS Access Key ID you provided does not exist in our records.
```

Here is my terraform block, please guide me
```
terraform {
  required_version = ">= 1.6.3"

  backend "s3" {
    endpoints = {
      s3 = "https://s3.eu-de.cloud-object-storage.appdomain.cloud"
    }
    bucket                      = "cloudlogs-cos-bucket-data-eu-de"
    key                         = "global.tfstate"
    region                      = "eu-de"
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    access_key                  = "<<cos_hmac_keys.access_key_id>>"
    secret_key                  = "<<cos_hmac_keys.secret_access_key>>"
  }
}
```

**Comment by merlyel** [comment]
> If it is ibm cos bucket why do we need to provide AWS ACCESS and SECRET keys..?

IBM cos bucket uses s3 interface. Backend type "s3" uses either `access_key`/`secret_key` bucket parameters or env variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

> The AWS Access Key ID you provided does not exist in our records.

At first I'd try accessing the bucket with some tools provided by IBM to make sure that you are using the correct key values. Just to be sure that the bucket is really created and keys are really working

**Comment by maheshd2** [comment]
> > If it is ibm cos bucket why do we need to provide AWS ACCESS and SECRET keys..?
> 
> IBM cos bucket uses s3 interface. Backend type "s3" uses either `access_key`/`secret_key` bucket parameters or env variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
> 
> > The AWS Access Key ID you provided does not exist in our records.
> 
> At first I'd try accessing the bucket with some tools provided by IBM to make sure that you are using the correct key values. Just to be sure that the bucket is really created and keys are really working. Probably via `ibmcloud cos object-get` and `ibmcloud cos object-put`

@merlyel Thanks a lot.
It seems some issue with the bucket and its HMAC keys. I created a new bucket and it is working fine now.
