### ISSUE TITLE
Links on the IBM VPC Terraform page are all outdated. Should be gen2 not gen1.

### ISSUE THREAD

**Issue by babaganooosh** [IBM-Cloud/terraform-provider-ibm#2212]
https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-is-vpc

Links on the IBM VPC Terraform page are all outdated. Should be gen2 not gen1.

**Comment by astha-jain** [comment]
Here are gen2 examples - https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-is-ng

**Comment by kavya498** [comment]
Closing this issue.. 
Thanks..
