### ISSUE TITLE
enhancement: ibm_is_vpc arguments for naming of default Network ACL, Security Group and Routing Table

### ISSUE THREAD

**Issue by sean-freeman** [IBM-Cloud/terraform-provider-ibm#2216]
### Affected Resource(s)

Please list the resources as a list, for example:
- `ibm_is_vpc`
- `ibm_is_network_acl`
- `ibm_is_security_group`
- `ibm_is_vpc_routing_table`

### Missing capability

Upon instantiation of new VPC, the following resources are generated automatically:
- default Network ACL
- default Security Group
- default Routing Table

Given the affected resources cannot handle updates to names of existing resources in an account (as the name is used to identify the resource), it is not possible to use these resources to update the auto-naming with a hyphenated list of randomly-selected words.

Alternatively, an easier implementation may be to update the VPC resource `ibm_is_vpc` with resource arguments for updating the naming of these immediately after they are automatically created. For example:
```
default_network_acl_name
default_security_group_name
default_routing_table_name
```

Which subsequently can be used in a data resource to identify the resource in the account, and apply Security Group rules etc.

### Related issues

#2203 

### Important Factoids

IBM Cloud APIs with PATCH call is the current mechanism to update naming using the resource identifiers:
- https://cloud.ibm.com/apidocs/vpc#update-network-acl
- https://cloud.ibm.com/apidocs/vpc#update-security-group
- https://cloud.ibm.com/apidocs/vpc#update-vpc-routing-table

**Comment by astha-jain** [comment]
PR is merged. Can this issue be closed? @hkantare

**Comment by kavya498** [comment]
Available in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.25.0)
