### ISSUE TITLE
Feature Request: serve_stale_content support for ibm_cis_cache_settings resources

### ISSUE THREAD

**Issue by maristgeek** [IBM-Cloud/terraform-provider-ibm#2219]
We would like to be able to manage the serve_stale_content setting of a CIS domain. Please add the support for `ibm_cis_cache_settings` resources.

Followup to #1995.

**Comment by hkantare** [comment]
Available in latest release v1.22.0
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cis_cache_settings

**Comment by kavya498** [comment]
Closing this issue.. 
thanks
