### ISSUE TITLE
Link to official documentation is broken

### ISSUE THREAD

**Issue by qrilka** [IBM-Cloud/terraform-provider-ibm#2221]
The link to "official documentation" in https://github.com/IBM-Cloud/terraform-provider-ibm/blob/281bd6f3fc8d3e89e47506ea7f98b8ed4910d52a/README.md which points to https://cloud.ibm.com/docs/terraform?topic=terraform-tf-provider appears to be not available anymore.
The page says:

> Sorry, this content isn’t available.
> It seems we can’t find what you’re looking for.

**Comment by kavya498** [comment]
Fixed
