### ISSUE TITLE
Allow Logging feature of ibm_is_lb to be controlled via terraform

### ISSUE THREAD

**Issue by chanster** [IBM-Cloud/terraform-provider-ibm#2228]
Hi there,

### Terraform Version
`0.14.5`

### Affected Resource(s)
- ibm_is_lb

### Feature Request
Allow the management of LB logging via terraform. The current [documentation](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_lb) does not have this option available. In the web console, there is a switch to turn it on or off.

**Comment by hkantare** [comment]
Released in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.21.1
docs https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_lb

**Comment by kavya498** [comment]
Closing this issue..
thanks.
