### ISSUE TITLE
Feature Request: is_ssh_key upsert / getsert

### ISSUE THREAD

**Issue by garrettrowe** [IBM-Cloud/terraform-provider-ibm#2231]
### Important Factoids
When creating VPC Gen2 compute instances, a SSH key is required.  Validation rules on IBM Cloud via the portal, CLI, and terraform allow a SSH key fingerprint to exist only once in an account, even if the copies are called different names or exist in different resource groups.  The SSH key seems to be the one item that is required to be unique across an entire account, and that breaks some automation.

As terraform does not allow for the conditional creation of resources in HCL, the conditional logic must be applied at the provider level.

Ideally IBM Cloud would just allow for duplicate SSH key fingerprints with different unique names, but the shorter path here is to allow the is_ssh_key provider to simply return the existing key if it already exists, instead of erroring out.  I propose an optional boolean flag: warn_on_exist

This flag would allow the same script to be run repeatedly without modification to create instances 0-n.  As the providers are written today, they would require user knowledge and intervention to manually set a flag or run a separate script indicating that the key already exists.

**Comment by hkantare** [comment]
@astha-jain Mostly its an requirement from API side can you take up this with API team

**Comment by hkantare** [comment]
closing the issue based on above comments
