### ISSUE TITLE
Enhancement Request on ibm_is_instance

### ISSUE THREAD

**Issue by faseyiks** [IBM-Cloud/terraform-provider-ibm#2237]
### Terraform Version
terraform version
Terraform v0.14.3
+ provider registry.terraform.io/ibm-cloud/ibm v1.20.1
+ provider registry.terraform.io/vancluever/acme v2.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_instance

`Error: "boot_volume.0.size": this field cannot be set

  on main.tf line 58, in resource "ibm_is_instance" "instance":
  58: resource "ibm_is_instance" "instance" {

Error: "boot_volume.0.iops": this field cannot be set

  on main.tf line 58, in resource "ibm_is_instance" "instance":
  58: resource "ibm_is_instance" "instance" {

Error: "boot_volume.0.profile": this field cannot be set

  on main.tf line 58, in resource "ibm_is_instance" "instance":
  58: resource "ibm_is_instance" "instance" { `

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

Please can you consider adding enhancement to ibm_is_instance so that users can specify the below on `boot-volume1
        + encryption = "crn:v1:bluemix:public:kms:us-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
          + iops       = (known after apply)
          + name       = (known after apply)
          + profile    = (known after apply)
          + size       = (known after apply)

**Comment by hkantare** [comment]
As per my understanding we cann't edit boot volume size/profile...we can update only the name or encryption
<img width="485" alt="Screenshot 2021-02-08 at 3 11 31 PM" src="https://user-images.githubusercontent.com/24930306/107202739-8783ed80-6a20-11eb-8e8d-cbbcec625176.png">

**Comment by faseyiks** [comment]
It is the ability to specify this when creating the instance that I refer when we use terraform. Right now on the console, you specify what you want. But in terraform you cannot. You only get the default with terraform.  Apart from name and encryption, terraform template should include ability to use a wide range of options that are available as in the console
          `+ iops       = (known after apply)
          + name       = (known after apply)
          + profile    = (known after apply)
          + size       = (known after apply)`

**Comment by hkantare** [comment]
May be I may understood wrong but from UI also you can only specify the name and encryption only for boot volume..The remainign fields are not editable..

**Comment by edabe** [comment]
Correct @hkantare : The boot volume is set to 100GB and a maximum of 3,000 IOPS ([doc](https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-about#block-storage-vpc-boot-volumes)). This cannot be modified

**Comment by kavya498** [comment]
Closing this issue based on above discussion..
Thank you..
