### ISSUE TITLE
Release new provider version

### ISSUE THREAD

**Issue by martinohansen** [IBM-Cloud/terraform-provider-ibm#2238]
If possible we want two changes that are already merged to be built into a new release so we can use upstream to deploy against jp-osa. 

- https://github.com/IBM-Cloud/bluemix-go/pull/273
- https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2226

**Comment by hkantare** [comment]
We will update the release date soon

**Comment by kavya498** [comment]
New version of provider has been released
Please find the [latest version 1.21.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.21.0)
