### ISSUE TITLE
Enhancement request Security Advisor IAM access via Terraform

### ISSUE THREAD

**Issue by amfred** [IBM-Cloud/terraform-provider-ibm#2240]
### Terraform Version
1.20

### Affected Resource(s)
- security-advisor (proposed name)

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I've been told via the Slack support channel that Security Advisor is not available as a resource that can be configured via Terraform.  This is a request to add that feature, so that we can give people access to the Security Advisor dashboard via Terraform, rather than doing it manually.
Here's the description of the access I was trying to grant: https://cloud.ibm.com/docs/security-advisor?topic=security-advisor-service-access

### Actual Behavior
We had to configure access manually, through the IBM Cloud dashboard. This is a departure from our usual auditable change request flow.

### Steps to Reproduce
N/A

### Important Factoids
We're using vanilla IKS.

### References
N/A

**Comment by hkantare** [comment]
We have now support for SCC in latest releases
https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-terraform-setup

**Comment by amfred** [comment]
Thank you!  I'm not with IBM any more so I won't be able to test it, but this should work.

**Comment by kavya498** [comment]
Thanks very much..
closing this issue.. Thanks
