### ISSUE TITLE
The provider provider.ibm does not support data source "ibm_is_volume_profiles".

### ISSUE THREAD

**Issue by catholic-indulgence-vaper** [IBM-Cloud/terraform-provider-ibm#2252]
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/efa5de769b91072713998836f0d3d018acbe9d12/examples/ibm-is-ng/main.tf#L289

Terraform validate reports this datasource as unsuported.

Terraform v0.14.6
+ provider registry.terraform.io/ibm-cloud/ibm v1.20.1

**Comment by hkantare** [comment]
IT will be part of next release

**Comment by hkantare** [comment]
It available in v1.21.1 release
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_volume_profile
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_volume_profiles

**Comment by kavya498** [comment]
closing this issue..
thanks.
