### ISSUE TITLE
Support for COS bucket object resource

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#2255]
Support for COS bucket object resource similar to what S3 offers here - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object

```
resource "aws_s3_bucket_object" "object" {
  bucket = "your_bucket_name"
  key    = "new_object_key"
  source = "path/to/file"


  etag = filemd5("path/to/file")
}
```

This also gives an option to create a COS directory(folder) just in case if the user wishes to create folders to store data or results(json).

**Comment by kavya498** [comment]
Available in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.25.0)
