### ISSUE TITLE
ibm_is_vpc should support the creation of a default_security_group with no rules

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2262]
```
resource "ibm_is_vpc" "testacc_vpc" {
    name = "test"
}
```

Results in a default security group created for the vpc.  Here is the output parameter created. https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-resources#vpc-arguments

> default_security_group | String | The unique identifier of the default security group that was created for your VPC.

I don't want the rules that are provided in security group created.  The enhancement is to add a boolean to create the default security group with no rules:

> default_security_group_rules| boolean|default true -  security group rules... if false then no rules are added

Or it could follow the model for `address_prefix_management` using the string `auto` and `manual`

To work around this I can write a shell script that deletes the rules.  And then populate them.  But the shell script is not portable, doesn't work in schemartics, etc

Kubernetes has a short coming that the security group for the worker nodes is the default_security_group... Bummer for me, I really need to get it initialized exactly as required.

https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#security_groups

> The default security group for the VPC is applied to your worker nodes ...

Current work around:
```
# default security group is cleaned then initialized
data "external" "vpc_clean" {
  program = ["/bin/bash", "vpc_clean.sh"]

  query = {
    vpc_id = ibm_is_vpc.vpc.id
    vpc_default_security_group = ibm_is_vpc.vpc.default_security_group
    ibmcloud_api_key = var.ibmcloud_api_key
  }
}

resource "ibm_is_security_group_rule" "inbound_all" {
  group     = data.external.vpc_clean.result.default_security_group
...
}
```

vpc_clean.sh:
```
#!/bin/bash
set -ex
success=false
output_file=$(mktemp /tmp/vpc_clean.XXXXX)
function on_exit(){
  cat $output_file 1>&2
  if [ $success = true ]; then
    # result terraform needs
    cat <<EOF
    {
      "default_security_group": "$vpc_default_security_group",
      "date": "$date"
    }
EOF
  fi
}
trap on_exit EXIT

function main(){
  eval "$(jq -r '@sh "vpc_id=\(.vpc_id) vpc_default_security_group=\(.vpc_default_security_group) ibmcloud_api_key=\(.ibmcloud_api_key)"')"
  date=$(date)
  ibmcloud login --apikey $ibmcloud_api_key
  for rule_id in $(ibmcloud is security-group $vpc_default_security_group --output json | jq -r '.rules[]|.id'); do
    ibmcloud is security-group-rule-delete $vpc_default_security_group $rule_id --force
  done
}

# call function so all the output can be put into a file
main > $output_file
success=true
```

**Comment by powellquiring** [comment]
Consider the same kind of change to default_network_acl adding a parameter: `default_network_acl_rules: boolean`

**Comment by powellquiring** [comment]
The aws terraform provider has special default resources.  This could be considered as well:
- [Resource: aws_default_route_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table)
- [Resource: aws_default_network_acl](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_network_acl)
- [Resource: aws_default_security_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_security_group)

**Comment by ileneruth** [comment]
Ref #2011

**Comment by ujjwal-ibm** [comment]
Hi @powellquiring 

this  feature is not directly supported by the apis. When a vpc is created a default sg is created with default rules.

As a workaround this configuration can be used which uses a null_resource, which does :
1. create a vpc
2. fetches and removes the 2 default rules on the default sg
3.  creates a new outbound rule

```
provider ibm {
    region = var.region
}
provider null {
}
variable region {
    default = "us-south"
}

resource ibm_is_vpc this {
    name = "tfp-test"
}
data ibm_is_security_group_rules this {
    security_group = ibm_is_vpc.this.default_security_group
}

resource null_resource sg_del_0 {
  provisioner "local-exec" {
      command = <<-EOT
						curl --location --request DELETE 'https://${var.region}.iaas.cloud.ibm.com/v1/security_groups/${ibm_is_vpc.this.default_security_group}/rules/${data.ibm_is_security_group_rules.this.rules.0.id}?version=2022-09-13&generation=2' \
						--header 'Content-Type: application/json' \
						--header 'Cache-Control: no-cache' \
						--header 'Accept: application/json' \
						--header 'Authorization: ${data.ibm_iam_auth_token.tokendata.iam_access_token}' 
			EOT
  }
}
resource null_resource sg_del_1 {
  provisioner "local-exec" {
      command = <<-EOT
						curl --location --request DELETE 'https://${var.region}.iaas.cloud.ibm.com/v1/security_groups/${ibm_is_vpc.this.default_security_group}/rules/${data.ibm_is_security_group_rules.this.rules.1.id}?version=2022-09-13&generation=2' \
						--header 'Content-Type: application/json' \
						--header 'Cache-Control: no-cache' \
						--header 'Accept: application/json' \
						--header 'Authorization: ${data.ibm_iam_auth_token.tokendata.iam_access_token}' 
			EOT
  }
}

data ibm_iam_auth_token tokendata {}

resource ibm_is_security_group_rule this {
	group     = ibm_is_vpc.this.default_security_group
	direction = "outbound"
	remote    = "127.0.0.1"
	tcp {
		port_min = 8080
		port_max = 8080
	}
}
```

**Comment by powellquiring** [comment]
This is a great work around.  Could this be integrated into the ibm_is_vpc resource?  Add an argument to the ibm_is_vpc resource that triggers this code in the ibm terraform provider.

**Comment by astha-jain** [comment]
`no_sg_acl_rules` argument now removed the default sg and acl rules
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4702
