### ISSUE TITLE
Enhancement Request: Filtering support when using data.ibm_is_instances

### ISSUE THREAD

**Issue by faseyiks** [IBM-Cloud/terraform-provider-ibm#2272]
This is an enhancement request

### Terraform Version
v0.12.29

### Affected Resource(s)
Please list the resources as a list, for example:
-  data.ibm_is_instances

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

data "ibm_is_vpc" "main" {
  name = var.vpc_name

data "ibm_is_instances" "instances" {
  vpc_name = var.vpc_name
}

output "vm_instance_names" {
  value = data.ibm_is_instances.instances.instances.*.name
}
```

### Expected Behavior
Currently, this outputs all the instance names within the VPC.  However, it is not always that one is interested in all of such instances. Sometimes you want just a subset.  This is where ability to add a filter to provide the subset is important and required.  A use-case is when you use the instance-group feature to create multiple vsi's and you want an output of the vsi. It is currently not supported within data.ibm_is_instance_group to retrieve the associated vsi.  However, because the instances  follow a naming convention that appends a UUID to a naming format, it should be possible to retrieve that using something like

```
data "ibm_is_instances" "instances" {
  vpc_name = var.vpc_name
  filter {
    name   = "name"
    values = ["my-naming-prefix-*"]
  }
}

**Comment by astha-jain** [comment]
For the particular scenario of filtering instances attached to an instance group, this filter was released https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.30.0

For a generic filtering, I would request @hkantare to provide guidance.
