### ISSUE TITLE
vpc_cluster won't provision since IKS 1.19

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#2283]
Hello there,

Look like a "deja-vu" ... @hkantare 

IKS teams has evolved there API.

Now the IBM TF provider always fails with following error:

```
ibm_container_vpc_cluster.cluster: Still creating... [40m21s elapsed]
Error: Request failed with status code: 409, ServerErrorResponse: {"incidentID":"62721ab7615aee27-CDG","code":"E0120","description":"The master is already up to date for the specified version.","type":"Versions"}
  on main.tf line 1, in resource "ibm_container_vpc_cluster" "cluster":
   1: resource "ibm_container_vpc_cluster" "cluster" {
```

The cluster ends up correctly, but not stored in our Terraform state.

Tested with version K8S 1.19 and 1.18.

Terraform 0.12
IBM TF: 1.20

**Comment by hkantare** [comment]
@ifs-pauljegouic Can you please upgrade your terraform provider to latest version v1.20.1 or v1.21.0 (the lates release)
We fixed the regresison issue win v1.20.1...

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.20.1

**Comment by ifs-pauljegouic** [comment]
No way , fixed an un-handled response by IKS through this ?

Looks like a regression when you inform specifically a kube_version, could you provide more info ?

![image](https://user-images.githubusercontent.com/50360031/109266976-21151280-7809-11eb-9db0-442ec32657cf.png)

**Comment by hkantare** [comment]
@ifs-pauljegouic 

Its not an response from IKS...There was some flow regression introduced in the  v1.20.0 release...
We first create the cluser and then come to update to see if any fields like kms, so on needs to atttach to the cluster..
In v1.20.0 release as part of patch_version functionality there was some error introudced in the if condition
<img width="1199" alt="Screenshot 2021-02-26 at 1 16 23 PM" src="https://user-images.githubusercontent.com/24930306/109271156-1ff9da80-7835-11eb-9da6-ea92812473f3.png">
For the first time of cluster creation it should enter this if block...but it was entering and again trying to update the version
So it was failing with error Master already up-do-date

We fixed this block of condition code in v1.20.1 and later releases

**Comment by hkantare** [comment]
Can we close this issue

**Comment by ifs-pauljegouic** [comment]
Yes @hkantare sorry, I'm closing
