### ISSUE TITLE
Detailed documentation in two different places that is not identical makes it twice as hard to figure things out

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2289]
I've been reading docs on VPC both vpn and routing.  I've found discrepancies in the two documentation locations.  To understand how to use the product I need to always check both places.  This is going to make it two times harder to use ibm terraform.

Suggestion: The accurate and detailed description of every resource and data on the terraform site.  The IBM docs need to be largely generated as well, or just focus on the interactions and examples.

Examples:

- https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-resources#vpn-gateway
- https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpn_gateway

For the ibm_is_vpn_gateway the registry documents mode  Is one of these the official docs?

Answer: Cloud Docs is maintained by our Documentation team..may be mode is been missed

I also noticed 

- https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc_routing_table_route
- https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-resources#vpc-routing-table-route

ibm docs: action | String | Optional | The action to perform with a packet matching the route. The default value is deliver. The supported values are delegate, deliver, and drop

terraform: action - (Optional,string) The action to perform with a packet matching the route.

**Comment by geethasathyamurthy** [comment]
@powellquiring , this is updated. 
Thanks,
Geetha

**Comment by powellquiring** [comment]
@geethasathyamurthy I think the docs need to be re-organized.  Who should be involved in the design of the docs?

**Comment by stevestrutt** [comment]
@powellquiring what is your thinking about reorganising the docs?

**Comment by powellquiring** [comment]
@stevestrutt the reference docs should be on the terraform site.  Can all of the info from the ibm docs be inserted into the terraform site docs?  Nadine?

**Comment by hkantare** [comment]
Now we have docs hosted only in Terraform registry
