### ISSUE TITLE
ibm_container_addons resource not detecting version change 

### ISSUE THREAD

**Issue by evpirnia** [IBM-Cloud/terraform-provider-ibm#2295]
### Terraform Version
v0.12.20

### Affected Resource(s)
- ibm_container_addons

### Terraform Configuration Files
```hcl
##############################################################################
# Variables
##############################################################################
variable resource_group {}
variable cluster_id {}
variable istio_addon_version {}
##############################################################################
# Enable managed istio addon
##############################################################################
resource ibm_container_addons istio {
  cluster           = var.cluster_id
  resource_group_id = var.resource_group

  addons {
    name    = "istio"
    version = var.istio_addon_version
  }

  addons {
    name = "kube-terminal"
  }
}
```

### Debug Output
See slack thread in references. 

### Panic Output
None 

### Expected Behavior
When the value for `var.istio_addon_version` is changed from "1.7" to "1.8", I expect the change to be reflected in the output of `terraform plan`. 

### Actual Behavior
The resource does not appear in the output of `terraform plan`. No changes are detected.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Set `var.istio_addon_version` to have a value of '1.7'
2. `terraform plan && terraform apply`
3. Set `var.istio_addon_version` to have a value of '1.8' 
4. `terraform plan` -> **no changes detected, why?** 

### Important Factoids
Testing on a VPC Gen 2 cluster in IBM Cloud. 

### References
For more information, here is the slack thread that identified the issue: https://ibm-cloudplatform.slack.com/archives/C53NF5MB4/p1614305528113800

**Comment by kavya498** [comment]
@evpirnia, Can we close this?

**Comment by evpirnia** [comment]
Yes, thank you @kavya498!
