### ISSUE TITLE
ibm_cos_bucket deletion issue

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#2305]
### Terraform Version
0.12.29

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_cos_bucket

### Terraform Configuration Files
```hcl
resource "ibm_resource_instance" "cos_account" {
  name     = "var.service_instance_name"
  service  = "cloud-object-storage"
  plan     = "standard"
  location = "global"
  count = "${var.neworexistance?0:1}"
  resource_group_id = "data.ibm_resource_group.group.id"
}

resource "ibm_cos_bucket" "bucket_cr" {
  bucket_name          = "testingBucket"
  count = "${var.cross_region_location?1:0}"
  resource_instance_id = "${var.neworexistance?var.resource_instance_id:ibm_resource_instance.cos_account[0].id}"
  storage_class        = "standard"
    activity_tracking {
    read_data_events     = false
    write_data_events    = false
    activity_tracker_crn = ""
  }
  metrics_monitoring {
    usage_metrics_enabled  = false
    metrics_monitoring_crn = ""
  }
  expire_rule {
    rule_id = "a-bucket-expire-rule"
    enable  = false
    days    = 30
    prefix  = "logs/"
  }
  cross_region_location = "us"
}
```

### Debug Output
2021/03/03 06:32:48 [TRACE] EvalWriteState: recording 0 dependencies for ibm_resource_instance.bfast-resource-ord-JGBJ9TJYCP-4[0]
2021/03/03 06:32:48 [TRACE] EvalWriteState: writing current state object for ibm_resource_instance.bfast-resource-ord-JGBJ9TJYCP-4[0]
2021/03/03 06:32:48 [TRACE] [walkRefresh] Exiting eval tree: ibm_resource_instance.bfast-resource-ord-JGBJ9TJYCP-4[0]
2021/03/03 06:32:48 [TRACE] vertex "ibm_resource_instance.bfast-resource-ord-JGBJ9TJYCP-4[0]": visit complete
2021/03/03 06:32:48 [TRACE] dag/walk: upstream of "provider.ibm (close)" errored, so skipping
2021/03/03 06:32:48 [INFO] backend/local: refresh calling Refresh
2021/03/03 06:32:48 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
[31m
2021/03/03 06:32:48 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
[1m[31mError: [0m[0m[1mAccessDenied: Access Denied
	status code: 403, request id: 819f6f06-55f0-4a16-b3a4-cad0fe4db61b, host id: [0m

[0m[0m[0m
2021-03-03T06:32:48.972Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-03-03T06:32:48.977Z [DEBUG] plugin: plugin process exited: path=/tmp/go/bin/terraform-provider-ibm pid=562
2021-03-03T06:32:48.977Z [DEBUG] plugin: plugin exited
### Expected Behavior
 terraform refresh on tfstate file should return resources with zero instances.

### Actual Behavior
terraform refresh on tfstate file it is throwing above error as access denied.

### Steps to Reproduce
Create cloud object storage acc. with ibm_resource_instance and bucket in that same account.
Delete the whole cloud object storage acc from the IBM Cloud Portal.
Then do terraform refresh on tfstate file it is throwing above error as access denied.

**Comment by M-Rushabh** [comment]
@hkantare  Could you please take a look at it.
thanks.

**Comment by IBM-Deeksha** [comment]
Hi @M-Rushabh ,
Thanks for reporting this issue. I attempted to replicate the issue by manually deleting the resources from console and then running `terraform refresh` on my setup. The terraform state file updated without encountering any http 403 errors. Could you please help with  which IBM provider version you're currently using ? 
Also, could you please confirm if the error occurs consistently on your side or if it appears to be intermittent. In case it is consistent, it would be helpful if you could share detailed logs using by setting `TF_LOG=DEBUG` and rerunning `terraform refresh` for more insights.
Thank you!

**Comment by IBM-Deeksha** [comment]
Hi @M-Rushabh 
Following up on this issue, we would appreciate any updates you might have or if you could take a look at the suggestions/queries posted above. It would be helpful for moving forward with a resolution.
Thank you for your attention and looking forward to your response :)

**Comment by IBM-diksha** [comment]
This issues has been fixed , if you still continue to see this issues please reopen the ticket.
Thank you.
