### ISSUE TITLE
Should ibm_kms_key even support `endpoint_type`?

### ISSUE THREAD

**Issue by kjoconnor** [IBM-Cloud/terraform-provider-ibm#2309]
### Terraform Version
Terraform v0.12.29
IBM Cloud Plugin v1.13.1

### Affected Resource(s)
- ibm_kms_key

### Terraform Configuration Files
```hcl
resource ibm_kms_key bucket_key {
  instance_id   = "<guid>"
  key_name      = "my-key"
  standard_key  = false
  endpoint_type = "private"
}
```

### Expected Behavior
The key is created and used via a private endpoint.

### Actual Behavior
The key is created, but every time you `plan` after terraform wants to recreate the key to change the `endpoint_type` from public to private. I'm guessing that this is just not supported after looking at the [API Docs](https://cloud.ibm.com/apidocs/key-protect#createkey), or if it somehow is, it's not getting set appropriately during creation or not being retrieve properly when refreshing state.

### Steps to Reproduce
1. Use the hcl above.
2. Plan and apply.
3. Plan again, you'll see it will want to change the `endpoint_type` and in order to do so will want to recreate the key.

**Comment by kavya498** [comment]
Fixed in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.25.0)
