### ISSUE TITLE
ibm_iam_user_policy data source produces no results

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#2312]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
$ terraform -v
Terraform v0.14.7
+ provider registry.terraform.io/ibm-cloud/ibm v1.21.1

### Affected Resource(s)
- ibm_iam_user_policy

### Terraform Configuration Files
```hcl
data "ibm_iam_user_policy" "user_policy" {
  ibm_id = var.ibm_id
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Policies array should have contained policies as described here: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/iam_user_policy#attribute-reference  instead it was empty

### Actual Behavior
What actually happened?
```hcl
 "resources": [
    {
      "mode": "data",
      "type": "ibm_iam_user_policy",
      "name": "user_policy",
      "provider": "provider[\"registry.terraform.io/ibm-cloud/ibm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "ibm_id": "<redacted>",
            "id": "<redacted>",
            "policies": [],
            "sort": null
          },
          "sensitive_attributes": []
        }
      ]
    }
]
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by kavya498** [comment]
When I tried it was working as expected
```
{
      "mode": "data",
      "type": "ibm_iam_user_policy",
      "name": "user_policy",
      "provider": "provider.ibm",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "ibm_id": "XX",
            "id": "XX",
            "policies": [
              {
                "id": "YY",
                "resources": [
                  {
                    "region": "",
                    "resource": "",
                    "resource_group_id": "",
                    "resource_instance_id": "",
                    "resource_type": "",
                    "service": "internet-svcs"
                  }
                ],
                "roles": [
                  "Viewer",
                  "Operator",
                  "Editor",
                  "Administrator",
                  "Reader",
                  "Writer",
                  "Manager"
                ]
              }
            ],
            "sort": null
          }
        }
      ]
    },
```
@dprosper We are not able to reproduce the error..

What did you provide for `ibm_id`,is it email id?

**Comment by dprosper** [comment]
@kavya498 I used my e-mail address. Note that I am not creating a new resource in my template, I am only trying to retrieve existing resources.

**Comment by kavya498** [comment]
Fixed in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.21.2)
