### ISSUE TITLE
ElasticSearch Provider Node Update (Feature Request)

### ISSUE THREAD

**Issue by wderezin** [IBM-Cloud/terraform-provider-ibm#2313]
Add support so that `ibm_database` resource can manage the number of ElasticSearch nodes and scale out with terraform.

Add 4 variables to the terraform provider `ibm_database` resource.
```
node_memory_allocation_mb
node_disk_allocation_mb
node_cpu_allocation_count
node_count
```

The usage of these variables will be exclusive to to the `members_` attributes.
```
members_memory_allocation_mb
members_disk_allocation_mb
members_cpu_allocation_count
```

Attribute Reference (output)
Provide reference to both node_ and members_  regardless of the which is specified in the resource. 
For example:
If the following is provided as input
```
node_memory_allocation_mb=256
node_count=10
```

Then referencing `members_memory_allocation_mb` would equal 2560.

Features to add:
1) Validate that only `node_` or `members_` is being used in a configuration.
2) Support switching from `members_` to `node_`   
3) For new deployment workflow
      Step 1: Create initial elastic cluster
      Step 2: Scale up if needed
4) Prevent decreasing the `node_count` to prevent dataloss by the provider.   This would require a manual scale in then update terraform

**Comment by allen-servedio** [comment]
We are willing to do the PR for this @hkantare - mainly creating the issue first to see if you all have input in the interface and will consider a change like this.
