### ISSUE TITLE
missing "ibm_subnet" data type

### ISSUE THREAD

**Issue by jkwong888** [IBM-Cloud/terraform-provider-ibm#232]
### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_subnet

### Expected Behavior
There is an `ibm_subnet` resource provider, but not a data provider.  I need this to enable the use case where I want to set a remote CIDR range for my security group (that my VM instance is on).

I know i can set remote groups for my security group, but actually the use case is that I want to lock down the remote CIDR range to the subnet that I provision the LBaaS on, and this could be any IP in the subnet I specify.  Additionally, security groups for LBaaS is not supported yet, so this is the best I can do for now until that support comes in.

**Comment by hkantare** [comment]
Ok . We will be working on adding datasource for ibm_subnet but as a workaround can you try below
Once After VM is created successfully you can access the subnet (CIDR) of both public and private
${ibm_compute_vm_instance.vm1.public_subnet}
${ibm_compute_vm_instance.vm1.private_subnet}
Can you assign these values while creating security group
```
resource "ibm_security_group_rule" "allow_port_443_mulesoft" {
  direction = "ingress"
  ether_type = "IPv4"
  protocol = "tcp"
  port_range_min = 443
  port_range_max = 443
  remote_ip = "${ibm_compute_vm_instance.vm1.public_subnet}"
  security_group_id = "${ibm_security_group.worker_sg.id}"
}
```

**Comment by jkwong888** [comment]
actually for this use case i need the `private_subnet` because I want to restrict traffic to the private subnet my LBaaS instance is provisioned on.

according to documentation, i only have access to `public_subnet` and `private_subnet_id`, hence the above request for the data provider.

**Comment by hkantare** [comment]
Even you can access ```private_subnet ```  Once vm gets created successfully the terraform state stores below configuration
```
ibm_compute_vm_instance.test:
  id = 53010769
  block_storage_ids.# = 0
  cores = 1
  datacenter = dal05
  dedicated_acct_host_only = false
  disks.# = 2
  disks.0 = 100
  disks.1 = 1000
  domain = test.com
  file_storage_ids.# = 0
  hostname = test-isds
  hourly_billing = true
  ip_address_id_private = 111123399
  ipv4_address = 
  ipv4_address_private = 10.41.6.35
  ipv6_enabled = false
  ipv6_static_enabled = false
  local_disk = false
  memory = 1024
  network_speed = 1000
  notes = 
  os_reference_code = REDHAT_7_64
  private_interface_id = 30265937
  private_network_only = true
  private_security_group_ids.# = 0
  private_subnet = 10.41.6.32/29
  private_subnet_id = 256088
  private_vlan_id = 2298937
  public_interface_id = 30265939
  public_security_group_ids.# = 0
  secondary_ip_addresses.# = 0
```
So you can access even private_subnet

**Comment by jkwong888** [comment]
i have additional use case for this where I would like to use the data provider to get a subnet ID that I can use to provision my `ibm_compute_vm_instance` resources into.  For example, I already have a gateway appliance routing this subnet.

**Comment by sakshiag** [comment]
@jkwong888 : Hi, for subent we can use vlan datasource to get the subnet id as to each subnet there will a vlan attached to it.. 
Can you please try and let us know if this works for your usecase.

**Comment by jkwong888** [comment]
i am using this approach for now, however i would like to know during provisioning when a new primary subnet is going to get created on the VLAN as it's a manual step to log into the gateway appliance and route this subnet.

**Comment by sakshiag** [comment]
@jkwong888 : 
From your comment, as per my understanding  you are trying to configure the gateway manually?? If yes, then Terraform is used only for provisioning the resources . For any manual step which is required for configuring the gateway , you need to write the scripts or you can use the provisioners . 
https://www.terraform.io/docs/provisioners/index.html
I guess you are referring to this resource https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_network_gateway.go ?? If yes, then we can use the vlan attachment resource to attach the vlan to the gateway.

**Comment by jkwong888** [comment]
no, the use case is that my subnet is already provisioned and routed by the gateway, and I potentially have firewall rules on this particular subnet.  in the case that the subnet runs out of space, terraform/softlayer API will return an error, which alerts me that I may need to manually log in to my gateway appliance to route an additional subnet.

**Comment by sakshiag** [comment]
@jkwong888 : How you are attaching the subnet with the gateway. ? In the  provider , you can try to attach the vlan and same vlan can be attached to the firewall . In vlan , you can have multiple subnets.. If one subnet is exhausted, it will automatically provision a new subnet in that vlan.

**Comment by hkantare** [comment]
Closing this no respone from long time..
