### ISSUE TITLE
ibm_is_virtual_endpoint_gateway does not allow modification of the ip blocks

### ISSUE THREAD

**Issue by argeiger** [IBM-Cloud/terraform-provider-ibm#2322]
### Terraform Version

Terraform v0.12.29

### Affected Resource(s)
- ibm_is_virtual_endpoint_gateway

### Terraform Configuration Files
```hcl
resource "ibm_is_virtual_endpoint_gateway" "endpoint_gateway_cos" {
    name    = "cos-vpe"
    target {
        crn            = "crn:v1:bluemix:public:cloud-object-storage:global:::endpoint:s3.direct.us-south.cloud-object-storage.appdomain.cloud"
        resource_type   = "provider_cloud_service"
    }
    vpc = data.ibm_is_vpc.vpc.id
    ips {
        subnet   = data.ibm_is_subnet.subnet.id
        name        = "reserved-cos-ip-new"
    }
   ips {
        subnet   = data.ibm_is_subnet.subnet2.id
        name        = "reserved-cos-ip-new-2"
    }
    resource_group = data.ibm_resource_group.rg.id
}

```

### Behavior

ibm_is_virtual_endpoint_gateway does not allow modification of the ip blocks.  This looks to be how it was implemented (https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_is_virtual_endpoint_gateway.go#L103) but this prevents the user from any modification to the ip blocks.

**Comment by deepaksibm** [comment]
Adding and removing ips is supported through a different resource https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_virtual_endpoint_gateway_ip

**Comment by argeiger** [comment]
@deepaksibm thanks for the response.  I am fine keeping it as is and utilizing the other resource but could we just put it in the documentation that the ip block can not be modified after it has been applied?  Thanks.
