### ISSUE TITLE
Allow control of Security Groups on Load Balancer

### ISSUE THREAD

**Issue by chanster** [IBM-Cloud/terraform-provider-ibm#2324]
Allow terraform to control `ibm_is_lb` security groups.

Security Groups have been implemented in [VPC Load Balancers](https://ibmcloud.ideas.aha.io/ideas/IDEA-I-3204?utm_source=idea_mailer&utm_medium=email&utm_campaign=subscribers_status_change)

### Terraform Version
`0.14.1`

### Affected Resource(s)
- `ibm_is_lb`

### Expected Behavior
Have an argument to manage security groups

### Actual Behavior
No argument available to manage security groups

### References
- [Aha IDEA Request](https://ibmcloud.ideas.aha.io/ideas/IDEA-I-3204?utm_source=idea_mailer&utm_medium=email&utm_campaign=subscribers_status_change)

**Comment by SunithaGudisagarIBM** [comment]
Solved this with the below PRs and these PRs are merged with master.
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2383
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2395
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2412

**Comment by hkantare** [comment]
The feature is available and releases in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.22.0
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_lb
