### ISSUE TITLE
Add support for user_data to ibm_compute_vm_instance 

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#2341]
Currently the ibm_compute_vm_instance does not seem to support providing `user_data`:

https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-ordering-vs-public
![image](https://user-images.githubusercontent.com/11874942/110787378-3f343700-823b-11eb-8c2d-b7f2766b0cd9.png)

Can the  support be added to the provider, similar to what is done in `ibm_is_instance`

**Comment by hkantare** [comment]
We already support the paramete 
https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-infrastructure-resources#bm-input

<img width="855" alt="Screenshot 2021-03-11 at 6 32 02 PM" src="https://user-images.githubusercontent.com/24930306/110791322-155d2d80-8298-11eb-92bb-ca36fffe45ce.png">

**Comment by dprosper** [comment]
Thank you, the name of the parameter and examples provided in the documentation are a tad confusing.
