### ISSUE TITLE
Creation of VPC address prefix fails on eu-de and eu-gb zones

### ISSUE THREAD

**Issue by micsafi** [IBM-Cloud/terraform-provider-ibm#2366]
Hi there,

### Summary description:
Creation of Gen2 VPC address prefixes fails on zones eu-de-1/2/3 and eu-gb-1/2/3. Seems to work when changing zone to Dallas (for example us-south-2).

### Terraform Version
Terraform v0.14.8
+ provider registry.terraform.io/ibm-cloud/ibm v1.21.2

### Affected Resource(s)
Please list the resources as a list, for example:
ibm_is_vpc_address_prefix

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

resource "ibm_is_vpc" "vpc" {
  name                      = "${var.environment_name}-vpc"
  resource_group            = ibm_resource_group.rg.id
  address_prefix_management = "manual"
}
resource "ibm_is_vpc_address_prefix" "vpc_address_prefix" {
  name = "${var.environment_name}-vpc-add-pre"
  zone = var.cloud_zone
  vpc  = ibm_is_vpc.vpc.id
  cidr = "10.243.0.0/18"
}

variable "cloud_zone" {
  default = "eu-de-1"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Terraform should create the VPC address prefix for my VPC.

### Actual Behavior
Terraform throws an error during apply with following error:

```
    "Result": {
        "errors": [
            {
                "code": "bad_field",
                "message": "invalid zone eu-de-1",
                "target": {
                    "name": "zone",
                    "type": "field",
                    "value": "eu-de-1"
                }
            }
        ],
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Using Gen2 VPCs.

**Comment by hkantare** [comment]
By default provider targets to us-south region..They need to configure provider to "us-east"
provider "ibm" {
region = "us-east"
}

**Comment by micsafi** [comment]
Thanks @hkantare, your pointed out the root cause for the error.

I didn't have region defined at the provider level, so the VPC was created in Dallas by default. That's why the reference to Frankfurt zones caused error.

**Comment by hkantare** [comment]
closing the issue
