### ISSUE TITLE
SSH keys. Gather public key.

### ISSUE THREAD

**Issue by jxadro** [IBM-Cloud/terraform-provider-ibm#2388]
IBM VPC Gen2. How to recover SSH public key.

Hi it seems it is not possible using terraform to recover the public key from an SSH key in IBM Cloud.

"ibm_is_ssh_key" does not return it: https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-data-sources#vpc-ssh-key

And the "ibm_is_instance" https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-data-sources#instance returns the key id but not the public key.

In the IBM Cloud Console UI I can recover it.

Also taking into account that IBM Cloud does not allow to generate two different keys with the same value this is a big usability issue.

**Comment by hkantare** [comment]
Available in latest release
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_ssh_key

**Comment by kavya498** [comment]
Closing this issue..
Thanks.
