### ISSUE TITLE
ibm_is_volume_snapshot not supported

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2422]
Resource does not exist? ibm_is_volume_snapshot
It is in the documentation.

```
resource "ibm_is_volume_snapshot" "mains" {
  for_each       = ibm_is_instance.mains
  name         = each.value.name
    volume_id   = "${ibm_is_volume.testacc_volume.id}"
}

tf version
Terraform v0.14.9
+ provider registry.terraform.io/ibm-cloud/ibm v1.21.2

...
  on main.tf line 90, in resource "ibm_is_volume_snapshot" "mains":
  90: resource "ibm_is_volume_snapshot" "mains" {

The provider provider.ibm does not support resource type
"ibm_is_volume_snapshot".

```

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_volume_snapshot

![image](https://user-images.githubusercontent.com/6932057/112685885-6b9ea480-8e32-11eb-98fc-cd9827fc1c07.png)

**Comment by kavya498** [comment]
@powellquiring ,
Documentation has been removed and will be available when the development is complete.. 
Team is working on development..
Please track the progress in #2431..Closing this issue..
Thank you..
