### ISSUE TITLE
lon06 zone ibm_pi_instance error - all volumes not in the same storage pool

### ISSUE THREAD

**Issue by lukebrowning** [IBM-Cloud/terraform-provider-ibm#2428]
I am using this project github.com/ocp-power-automation/ocp4-upi-power to deploy an OCP cluster.   

These are terraform modules being used: 

Initializing provider plugins...
- Finding hashicorp/null versions matching "~> 2.1, ~> 2.1"...
- Finding community-terraform-providers/ignition versions matching "~> 2.1.0"...
- Finding ibm-cloud/ibm versions matching "1.21.0, 1.21.0, 1.21.0"...
- Finding hashicorp/random versions matching "~> 2.3"...
- Installing ibm-cloud/ibm v1.21.0...
- Installed ibm-cloud/ibm v1.21.0 (unauthenticated)
- Installing hashicorp/random v2.3.1...
- Installed hashicorp/random v2.3.1 (unauthenticated)
- Installing hashicorp/null v2.1.2...
- Installed hashicorp/null v2.1.2 (unauthenticated)
- Installing community-terraform-providers/ignition v2.1.1...
- Installed community-terraform-providers/ignition v2.1.1 (unauthenticated)
 
The bastion node and master nodes are properly configured.   The worker nodes which have an extra disk fail with this message:

module.nodes.ibm_pi_instance.bootstrap[0]: Creation complete after 13m2s [id=fac4755e-8aff-45f5-8d5c-1d3b58b7a229/7163fe8d-cb5e-40b5-9e04-31e66df5fae3]
module.nodes.data.ibm_pi_instance_ip.bootstrap_ip[0]: Reading...
module.nodes.data.ibm_pi_instance_ip.bootstrap_ip[0]: Read complete after 3s [id=d74aed4d-6600-48d1-b960-342b81b4ec23]

Error: failed to provision Failed to Create PVM Instance :[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances][400] pcloudPvminstancesPostBadRequest  &{Code:0 Description:bad request: calculated parameter has failed for cloud-instance 740e57e1802241f5b9c66ff03813a9d9: validate volumes failed, all volumes are not in the same storage pool Error:bad request Message:}

  on modules/4_nodes/nodes.tf line 146, in resource "ibm_pi_instance" "worker":
 146: resource "ibm_pi_instance" "worker" {

The error message above is emitted from the terraform module -- ibm-cloud/ibm v1.21.0

The same cluster create code works properly in the tokyo zone tok04.    It just fails in the lon06 zone.    In fact, both clusters are deployed from the same server in the IBM austin stg lab.    The same underlying terraform modules are used, so it would appear that there is a configuration issue with lon06 zone.

**Comment by lukebrowning** [comment]
Initially, I opened a PowerVS Support Case in the lon06 zone for this issue.   They referred me here for support as they don't support terraform access yet.   Apparently, only GUI access.

**Comment by kavya498** [comment]
@lukebrowning ,
Can you please share us your template configuration?

**Comment by lukebrowning** [comment]
We use two tfvars files as input -- var.tfvars and site.tfvars in that order.   Defaults for input variables are provided in variables.tf.   At the time of the failure, you can see some of the variables in play using 'terraform show'.   I will provide these, but first I want to recreate the problem using tier 1 storage.   Recently, I learned that there has been contention for tier3 resources in the powervs zone - lon06 resulting in some failures / outages...  There have been complaints and there may have been some administrative action to solve the problem on behalf of paying customers... The code only fails in the lon06 zone.  I am using two other zones.  I want to recreate the problem using tier 1 storage and then I will provide snapshots of the files I mentioned above and terraform command output.   Is this how debug data is typically provided or is there some other way?

**Comment by kavya498** [comment]
@lukebrowning 
snapshots of the your variables.tf, provider block main.tf..
looking into the error it says 400 as volumes are not in same storage pool.. We would like to see if volumes that are assigned to instance are valid or not..
`validate volumes failed, all volumes are not in the same storage pool `

@surajsub any help here ^^

**Comment by kavya498** [comment]
Assuming this to be resolved and closing the issue..
Kindly, reopen if issue still persists..

Thanks.
