### ISSUE TITLE
feature request:  vpc gen2 snapshot support

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2431]
It is possible to work with snapshots in the using the cli and api:

https://cloud.ibm.com/docs/vpc?topic=vpc-snapshots-vpc-create#snapshots-vpc-create-api

Suggestions:
- [ ] ibm_is_volume_snapshot  - already documented (see #2422)
- [ ] data ibm_is_volume_snapshot - 
- [ ] ibm_is_instance - make modifications.  image / boot_volume only one of these is required see: ibmcloud `is instance-create --help`
- [ ] other places that specify an image, like ibm_is_instance_template

**Comment by astha-jain** [comment]
Snapshots is WIP

**Comment by surajsub** [comment]
Is this still WIP ?

**Comment by kavya498** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2672

**Comment by kavya498** [comment]
Closing this issue.. 
Thanks.
