### ISSUE TITLE
k8s workers/agents with disks?

### ISSUE THREAD

**Issue by jsilberm** [IBM-Cloud/terraform-provider-ibm#244]
When I use the Terraform provider to create "ibm_compute_vm_instance",
I can specify disk configuration, as below:
```
resource "ibm_compute_vm_instance" "k8s_agent" {
  [...]
  disks = [ 25, 25 ]
  [...]
}
```

How can I do that with "workers" in `ibm_container_cluster` ?

Thanks,
     -Jeff

**Comment by Praveengostu** [comment]
The container API does not support this.
Alternatively you can get the VSI id of worker node and import it as a VM_instance and try to update the disks. We dont not recommend this approach but you can try this as a workaround

**Comment by jsilberm** [comment]
But what if my worker needs local storage (either raw local disk or iSCSI block devices)?

**Comment by Praveengostu** [comment]
@jsilberm I see this is the only way to add disks get the VSI id of worker node and import it as a VM_instance and try to update the disks. I will check with API team and let you know if there is any thing else

**Comment by Praveengostu** [comment]
@jsilberm I had an update from API team, We can not add any local storage after the worker is created. The only way is to  create worker choosing a machine type with bigger storage but you cannot change the existing worker.

**Comment by jsilberm** [comment]
@Praveengostu : Can you please qualify for me, and tell me how I can easily distinguish which machine types present additional/unused/unmounted local (or remote) block storage?
```
Name                Cores   Memory   Network Speed   OS             Server Type   Storage   Secondary Storage   Trustable
u2c.2x4             2       4GB      1000Mbps        UBUNTU_16_64   virtual       25GB      100GB               false
mr1c.28x512         28      512GB    10000Mbps       UBUNTU_16_64   physical      2000GB    960GB               true
mg1c.16x128         16      128GB    10000Mbps       UBUNTU_16_64   physical      2000GB    960GB               false
mg1c.28x256         28      256GB    10000Mbps       UBUNTU_16_64   physical      2000GB    960GB               false
md1c.16x64.4x4tb    16      64GB     10000Mbps       UBUNTU_16_64   physical      2000GB    8000GB              true
md1c.28x512.4x4tb   28      512GB    10000Mbps       UBUNTU_16_64   physical      2000GB    8000GB              true
mb1c.4x32           4       32GB     10000Mbps       UBUNTU_16_64   physical      2000GB    2000GB              false
mb1c.16x64          16      64GB     10000Mbps       UBUNTU_16_64   physical      2000GB    960GB               true
b2c.4x16            4       16GB     1000Mbps        UBUNTU_16_64   virtual       25GB      100GB               false
b2c.16x64           16      64GB     1000Mbps        UBUNTU_16_64   virtual       25GB      100GB               false
b2c.32x128          32      128GB    1000Mbps        UBUNTU_16_64   virtual       25GB      100GB               false
b2c.56x242          56      242GB    1000Mbps        UBUNTU_16_64   virtual       25GB      100GB               false
```
For example, it is only the physical nodes that would qualify?

Thanks.

**Comment by Praveengostu** [comment]
None of the machine types have unmounted storage.
Primary disk is used for the main file system (/)
Secondary disk is used for persistent  storage for the container runtime
1. To access a remote softlayer, block storage, you can use the storage-plugin helm-chart link . Plugin supports create/attach/authorize/delete operations.
https://console.bluemix.net/containers-kubernetes/solutions/helm-charts/ibm/ibmcloud-block-storage-plugin

2. if you have some existing softlayer block storage with data, that you want to use it instead of creating a new one. Then you can create static PV and use with storage-plugin.
https://console.bluemix.net/docs/containers/cs_storage.html#existing_block

**Comment by hkantare** [comment]
Closed based on above comment
