### ISSUE TITLE
k8s cluster update issue during terraform apply

### ISSUE THREAD

**Issue by bemahone** [IBM-Cloud/terraform-provider-ibm#2442]
### Terraform Version
Terraform 13 w/ v1.21.2 IBM Cloud provider (running under schematics)

### Affected Resource(s)
ibm_container_vpc_cluster

### Details
**On a 1.19 kubernetes cluster with three worker nodes, the `patch_version` was updated as part of the generate/plan action:**
`patch_version                   = "8_1539" -> "9_1541"`

After the apply, only one of the three worker nodes was updated to the new level and after 2 hours the terraform apply timed out.  

As noted in issue #2379 - we modified the timeout block to allow for 120m during updates to account for the third scenario we referenced in that issue.  Unfortunately, this just appeared to prolong the failure and not impact the state of the workers in any beneficial way (as after the first worker was replaced, nothing else happened).  

I had a running log of the workers before, during and after the patching exercise (polling every 30 seconds).  After about 10 minutes, the first worker was updated (replaced) and complete (running the new version (1.19.9_1541).  At that time, the worker state via the IBMCloud CLI indicated the worker that was replaced was in a normal state and ready.  After that time, nothing else happened to the other 2 workers for the duration of the terraform apply.  

**Error message observed due to the timeout threshold being met:**
```
2021/03/30 16:42:16 Terraform apply | module.iks_cluster.ibm_container_vpc_cluster.cluster[0]: Still modifying... [id=c1f7di8w0j082qk6qf8g, 2h3m1s elapsed]
 2021/03/30 16:42:26 Terraform apply | module.iks_cluster.ibm_container_vpc_cluster.cluster[0]: Still modifying... [id=c1f7di8w0j082qk6qf8g, 2h3m11s elapsed]
 2021/03/30 16:42:36 Terraform apply | module.iks_cluster.ibm_container_vpc_cluster.cluster[0]: Still modifying... [id=c1f7di8w0j082qk6qf8g, 2h3m21s elapsed]
 2021/03/30 16:42:46 Terraform apply | module.iks_cluster.ibm_container_vpc_cluster.cluster[0]: Still modifying... [id=c1f7di8w0j082qk6qf8g, 2h3m31s elapsed]
 2021/03/30 16:42:56 Terraform apply | module.iks_cluster.ibm_container_vpc_cluster.cluster[0]: Still modifying... [id=c1f7di8w0j082qk6qf8g, 2h3m41s elapsed]
 2021/03/30 16:43:06 Terraform apply | module.iks_cluster.ibm_container_vpc_cluster.cluster[0]: Still modifying... [id=c1f7di8w0j082qk6qf8g, 2h3m51s elapsed]
 2021/03/30 16:43:12 Terraform apply | 
 2021/03/30 16:43:12 Terraform apply | Error: Error waiting for cluster (c1f7di8w0j082qk6qf8g) worker nodes kube version to be updated: timeout while waiting for state to become 'normal' (last state: 'updating', timeout: 2h0m0s)
 2021/03/30 16:43:12 Terraform apply | 
 2021/03/30 16:43:12 Terraform apply |   on cluster/cluster.tf line 30, in resource "ibm_container_vpc_cluster" "cluster":
 2021/03/30 16:43:12 Terraform apply |   30:  resource "ibm_container_vpc_cluster" "cluster" {
 2021/03/30 16:43:12 Terraform apply | 
 2021/03/30 16:43:12 Terraform apply | 
 2021/03/30 16:43:12 Terraform APPLY error: Terraform APPLY errorexit status 1
 2021/03/30 16:43:12 Could not execute action
```

**Question:** Since "updates" on VPC Gen 2 clusters are actually "worker replace" actions, where the original worker is deleted and replaced with a new worker (often with a new worker id/name as well as a new IP address), is it possible that the provider is polling the state of the wrong worker (the one that got deleted) and not checking the worker with the new id/name and IP to determine if another worker should be updated/replaced?
https://cloud.ibm.com/docs/containers?topic=containers-update#vpc_worker_node

What is peculiar is this seems to be happening sporadically - it does not seem to happen every time, but today we witnessed this same issue on two different clusters.  Since we can't simply run the terraform plan/apply again to resume where the previous run left off, we would then have to wait 2 weeks for a new version to come out and try again, or manually remediate the clusters using the cloud CLI or cloud UI.

**Comment by hkantare** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2379#issuecomment-966079106
