### ISSUE TITLE
Example for kuberentes ibm_ob_logging is wrong

### ISSUE THREAD

**Issue by dal13002** [IBM-Cloud/terraform-provider-ibm#2443]
Hi there,

The documentation here https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/ob_logging is for `ibm_ob_monitoring ` and not `ibm_ob_logging`

**Comment by umarali-nagoor** [comment]
Hi,

working on it, will correct the same.

**Comment by kavya498** [comment]
Fixed in latest [1.23.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.23.0)
