### ISSUE TITLE
Dedicated host with status 'failed' throws error during destroy

### ISSUE THREAD

**Issue by deepaksibm** [IBM-Cloud/terraform-provider-ibm#2446]
### Terraform Version
0.14.8

### Affected Resource(s)

- ibm_is_dedicated_host

### Terraform Configuration Files
```hcl
data "ibm_resource_group" "default" {
  name = "Default"
}

resource "ibm_is_dedicated_host_group" "dh_group01" {
  family = "balanced"
  class = "bx2d"
  zone = "eu-de-1"
  name = "dp-dh-group-bx2d"
  resource_group = data.ibm_resource_group.default.id
}


data "ibm_is_dedicated_host_group" "dgroup" {
	name = ibm_is_dedicated_host_group.dh_group01.name
}

resource "ibm_is_dedicated_host" "is_dedicated_host" {
  profile = "bx2d-host-152x608"
  name = "dp-dedicated-host-bx2d"
host_group = data.ibm_is_dedicated_host_group.dgroup.id
  
```

### Debug Output
Error: DedicatedHost instance is in FAILED state

### Expected Behavior
Dedicated host should be deleted without throwing error

### Actual Behavior
Deletion fails throwing error saying the State is FAILED

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by kavya498** [comment]
Fixed in latest [1.23.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.23.0)
thanks..
