### ISSUE TITLE
Feature Update:ibm_compute_ssl_certificate

### ISSUE THREAD

**Issue by jkhan001** [IBM-Cloud/terraform-provider-ibm#246]
hi,
we need an to add an input parameter "Certificate Signing Request" which is present on the softlayer portal but is missing in the terraform provider. for import ssl certificate service.

**Comment by hkantare** [comment]
Supported https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/ssl_certificate.html.markdown
