### ISSUE TITLE
Error Deleting Public Gateway, used by a subnet

### ISSUE THREAD

**Issue by mariesetnes** [IBM-Cloud/terraform-provider-ibm#2485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

1.23.0

### Affected Resource(s)

ibm_container_vpc_cluster
ibm_is_public_gateway
ibm_is_subnet

### Terraform Configuration Files

```
resource "ibm_is_public_gateway" "vpc_public_gateway" {
  count          = var.create_zone_gateways ? 3 : 0
  name           = format("%s-%s-%s", var.unique_id, "gateway", (count.index + 1))
  
  vpc            = var.vpc_id
  zone           = format("%s-%s", var.ibm_region, (count.index + 1))
  
  resource_group = var.resource_group_id

  #User can configure timeouts
  timeouts {
    create = "90m"
  }
}
```

```
resource "ibm_is_subnet" "multizone_subnet_kube" {
  count = var.create_kube_subnets ? 3 : 0
  name =  format("%s-%s-%s", var.unique_id, "kube", (count.index + 1) )
  
  resource_group = var.resource_group_id
  
  vpc   = var.vpc_id
  zone  = format("%s-%s", var.ibm_region, (count.index + 1))
  
  ipv4_cidr_block = var.kube_subnet_cidr_blocks[count.index]
  
  public_gateway  = length(var.zone_gateway_ids) > count.index ? element(var.zone_gateway_ids, count.index) : null

  network_acl     = element(ibm_is_network_acl.kube_subnet_acl.*.id, 0) 
}
```
```
module "gateways" {
  source = "./gateways"

  ibm_region           = var.ibm_region
  vpc_id               = module.vpcmod.vpc_id
  unique_id            = var.unique_id
  resource_group_id    = module.resource_groups.ops_resource_group_id
  # People kept forgetting to turn on gateways, so if cluster is on, gateway is on.
  # May need to look at this again later.
  #create_zone_gateways = var.create_zone_gateways
  create_zone_gateways = var.create_iks_cluster
}

module "subnets_and_acls" {
  source = "./subnetsandacls"

  ibm_region = var.ibm_region

  vpc_id                        = module.vpcmod.vpc_id
  vpc_default_security_group_id = module.vpcmod.vpc_default_security_group_id

  unique_id         = var.unique_id
  resource_group_id = module.resource_groups.ops_resource_group_id

  zone_gateway_ids = module.gateways.zone_gateway_ids

  ### control of subnet creation and ip count of each subnet type
  create_kube_subnets     = var.create_kube_subnets
  kube_subnet_cidr_blocks = var.kube_subnet_cidr_blocks
   
  kube_subnets_acl_rules  = var.kube_subnets_acl_rules
}


module "iks_cluster" {
  source            = "./cluster"
  vpc_id            = module.vpcmod.vpc_id
  unique_id         = var.unique_id
  resource_group_id = module.resource_groups.kube_resource_group_id

  # pass in the subnet IDs into cluster creation, they are needed for each worker
  iks_subnet_ids = module.subnets_and_acls.kube_subnet_ids

  # turn on/off cluster creation
  create_iks_cluster = var.create_iks_cluster
  
  # number of clusters to create
  iks_cluster_count = var.iks_cluster_count

  # region for the cluster creation (used to seed the zone names) 	
  region = var.ibm_region

  iks_cluster_name         = var.iks_cluster_name
  iks_cluster_tags         = var.iks_cluster_tags
  
  # Optional will select the latest IKS version.     Must be specified for ROKS
  iks_cluster_kube_version = var.iks_cluster_kube_version
    
  #Optional additions for security patching
  iks_cluster_update_all_workers = var.iks_cluster_update_all_workers
  iks_wait_for_worker_update = var.iks_wait_for_worker_update
  iks_cluster_patch_version = var.iks_cluster_patch_version
    
  # Optional kubernetes cluster addons
  iks_cluster_addons = var.iks_cluster_addons

  # Needed by ROKS (Name and Resource group of a COS instance)
  account_cos_name         = var.account_cos_name
  account_resource_group   = var.account_resource_group

  iks_pod_subnet     = var.iks_pod_subnet
  iks_service_subnet = var.iks_service_subnet
 
  iks_cluster_default_worker_pool_labels = var.iks_cluster_default_worker_pool_labels
  iks_cluster_default_worker_pool_flavor = var.iks_cluster_default_worker_pool_flavor
  iks_cluster_default_worker_pool_count  = var.iks_cluster_default_worker_pool_count

  create_iks_ingress_pool = var.create_iks_ingress_pool
  iks_cluster_ingress_worker_pool_name   = var.iks_cluster_ingress_worker_pool_name
  iks_cluster_ingress_worker_pool_flavor = var.iks_cluster_ingress_worker_pool_flavor
  iks_cluster_ingress_worker_pool_count  = var.iks_cluster_ingress_worker_pool_count
  iks_cluster_ingress_worker_pool_labels = var.iks_cluster_ingress_worker_pool_labels

  create_iks_egress_pool = var.create_iks_egress_pool
  iks_cluster_egress_worker_pool_name   = var.iks_cluster_egress_worker_pool_name
  iks_cluster_egress_worker_pool_flavor = var.iks_cluster_egress_worker_pool_flavor
  iks_cluster_egress_worker_pool_count  = var.iks_cluster_egress_worker_pool_count
  iks_cluster_egress_worker_pool_labels = var.iks_cluster_egress_worker_pool_labels

  create_iks_cluster_custom_worker_pool1 = var.create_iks_cluster_custom_worker_pool1
  iks_cluster_custom_worker_pool1_name   = var.iks_cluster_custom_worker_pool1_name
  iks_cluster_custom_worker_pool1_flavor = var.iks_cluster_custom_worker_pool1_flavor
  iks_cluster_custom_worker_pool1_count  = var.iks_cluster_custom_worker_pool1_count
  iks_cluster_custom_worker_pool1_labels = var.iks_cluster_custom_worker_pool1_labels

  create_iks_cluster_custom_worker_pool2 = var.create_iks_cluster_custom_worker_pool2
  iks_cluster_custom_worker_pool2_name   = var.iks_cluster_custom_worker_pool2_name
  iks_cluster_custom_worker_pool2_flavor = var.iks_cluster_custom_worker_pool2_flavor
  iks_cluster_custom_worker_pool2_count  = var.iks_cluster_custom_worker_pool2_count
  iks_cluster_custom_worker_pool2_labels = var.iks_cluster_custom_worker_pool2_labels
}
```
### Debug Output

I will attach log files from schematics to this issue.

### Expected Behavior

My cluster and all associated resources (gateways and subnets) should have deleted successfully. There is a corresponding IBM Support ticket `CS2251959` created for it.

### Actual Behavior

The cluster appears to have deleted (eventually) but schematics died with the following error. These resources are still in place.
`2021/04/07 17:17:18 Terraform apply | Error: Error Deleting Public Gateway : The Public Gateway is used by a subnet.`

### Steps to Reproduce
[Schematics_public_gateway_in_use.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6281664/Schematics_public_gateway_in_use.txt)
[Schematics_public_gateway_in_use2.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6281665/Schematics_public_gateway_in_use2.txt)
[Schematics_public_gateway_in_use2_second_try.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6281666/Schematics_public_gateway_in_use2_second_try.txt)
[Schematics_public_gateway_in_use2_third_try.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6281667/Schematics_public_gateway_in_use2_third_try.txt)

Using schematics and terraform to manage cluster resources in IBM Cloud. The terraform creates 3 subnets, 1 in each zone, with a gateway in each.  I had two clusters that I wanted to remove so kicked off a process to do so. Refer to the attachments for the logs.

On April 6th... attempting to delete a cluster calls a marie-firs-bbtest-ibm-test1-wdc schematics workspace... 
`Schematics_public_gateway_in_use2.txt` contains the schematics log that initially ran and failed.  You can see that it was able to delete the cluster, but not the dependent resources. So I waited a while and tried again. `Schematics_public_gateway_in_use2_second_try.txt` represents that second try and you can see the similar error.  So I waited a while and tried a third time. Same result. `Schematics_public_gateway_in_use2_third_try.txt`

On April 7th... attempting to delete a cluster calls a marie-four-merge2-ibm-take2-lon schematics workspace...
`Schematics_public_gateway_in_use.txt` contains the schematics log that ran and failed. Again, the cluster was eventually deleted successfully but various related resources were left behind. I did not attempt a second deletion.

### Important Factoids

Another colleague has experienced the behavior on the same day I did. Anecdotally we estimate this is happening on 1 out of every 5 deletion attempts.

### References

IBM Cloud support ticket CS2251959 <-- Link to schematics workspaces and cloud accounts can be found within that ticket.
Possible related issue already reported: <https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1627> <https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1438>

**Comment by hkantare** [comment]
From logs I can see that after cluster modules is getting destroyed its trying to destroy the public gateway module..
whereas it should call the subnet and network acl module for destroy and then public gateway for destroying..

From logs I see you are using Terraformv0.13 can you use depends_on for module
https://www.terraform.io/docs/language/meta-arguments/depends_on.html

```
module "subnets_and_acls" {
 depends_on = [module.gateways]
  source = "./subnetsandacls"

  ibm_region = var.ibm_region

  vpc_id                        = module.vpcmod.vpc_id
  vpc_default_security_group_id = module.vpcmod.vpc_default_security_group_id

  unique_id         = var.unique_id
  resource_group_id = module.resource_groups.ops_resource_group_id

  zone_gateway_ids = module.gateways.zone_gateway_ids

  ### control of subnet creation and ip count of each subnet type
  create_kube_subnets     = var.create_kube_subnets
  kube_subnet_cidr_blocks = var.kube_subnet_cidr_blocks
   
  kube_subnets_acl_rules  = var.kube_subnets_acl_rules
}
```

But still I want to see the terrafor plan logs because the logs which you shared is showing some modification is going on subnets...I want to see on which field or argument its modifying
```
id=0777-3a006011-160f-4708-8bad-75df58cb7f2b]
 2021/04/06 22:59:03 Terraform apply | module.subnets_and_acls.ibm_is_subnet.multizone_subnet_kube[0]: Refreshing state... [id=0757-9222b85c-99ca-4717-90cf-53af0635b6d6]
 2021/04/06 22:59:12 Terraform apply | module.gateways.ibm_is_public_gateway.vpc_public_gateway[0]: Destroying... [id=r014-d64ff852-3ccf-4b5a-a554-a4a38c3c3adc]
 2021/04/06 22:59:12 Terraform apply | module.gateways.ibm_is_public_gateway.vpc_public_gateway[1]: Destroying... [id=r014-88ff63f2-8022-4652-abd9-103ac6291f31]
 2021/04/06 22:59:12 Terraform apply | module.gateways.ibm_is_public_gateway.vpc_public_gateway[2]: Destroying... [id=r014-f3726f80-ff71-43cf-9d85-5fb6ae5d0794]
 2021/04/06 22:59:13 Terraform apply | module.subnets_and_acls.ibm_is_network_acl.kube_subnet_acl[0]: Modifying... [id=r014-4e8bc1b5-bd6b-4153-8e20-c9d13ce9a2d3]
 2021/04/06 22:59:23 Terraform apply | module.subnets_and_acls.ibm_is_network_acl.kube_subnet_acl[0]: Still modifying... [id=r014-4e8bc1b5-bd6b-4153-8e20-c9d13ce9a2d3, 10s elapsed]
 2021/04/06 22:59:25 Terraform apply | module.subnets_and_acls.ibm_is_network_acl.kube_subnet_acl[0]: Modifications complete after 13s [id=r014-4e8bc1b5-bd6b-4153-8e20-c9d13ce9a2d3]
 ```

**Comment by mariesetnes** [comment]
[Plan_Generated_RightBefore_Schematics_public_gateway_in_use.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6288153/Plan_Generated_RightBefore_Schematics_public_gateway_in_use.txt)
[Plan_Generated_RightBefore_Schematics_public_gateway_in_use2.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6288154/Plan_Generated_RightBefore_Schematics_public_gateway_in_use2.txt)
[Plan_Generated_RightBefore_Schematics_public_gateway_in_use2_second_try.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6288155/Plan_Generated_RightBefore_Schematics_public_gateway_in_use2_second_try.txt)
[Plan_Generated_RightBefore_Schematics_public_gateway_in_use2_third_try.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6288156/Plan_Generated_RightBefore_Schematics_public_gateway_in_use2_third_try.txt)

Attached the plan logs that I yanked from schematics.

The deletion was working great for over a year without explicit dependencies in the terraform. Only within the last two months have we started seeing this problem. 

If we do try `depends_on` to solve this, do we make the gateway depend on the subnet (or do I have that backwards)? I want to make sure we get the direction correct. You re-posted our subnet module so wondering if we add the code to that subnet module and depend on the gateway.

**Comment by hkantare** [comment]
@mariesetnes I have couple of questions on the templates

You are 3 subnets, 1 in each zone, with a gateway in each. (means 3 gateways)  and cluster.. From your tempalte Your are controlling the creation of gateways using the parameter of cluster # create_zone_gateways = var.create_iks_cluster

During initial Terraform apply it creates 3 subnets, 3 gateway(since count=var.create_zone_gateways ? 3 : 0 and in gateway module your are sending create_zone_gateways with number of cluster variable ) and 1 or 2 cluster based on  var.create_iks_cluster

**Comment by mariesetnes** [comment]
Thanks for pointing that out.  We have adjusted the code as follows...
```
module "gateways" {
# everything stays the same as previously pasted in this module except for the next line....
  create_zone_gateways = var.create_zone_gateways
}
```

```
variable "create_zone_gateways" {
  description = "If set to true, zone gateways should be created"
  default     = true
}
```
I am going to go ahead and close this issue.
