### ISSUE TITLE
bug: ibm_is_subnet and ibm_is_subnets return data only for us-south region

### ISSUE THREAD

**Issue by sean-freeman** [IBM-Cloud/terraform-provider-ibm#2486]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
$ terraform -v
Terraform v0.14.10
+ provider registry.terraform.io/ibm-cloud/ibm v1.20.1
```

### Affected Resource(s)

* ibm_is_subnets
* ibm_is_subnet

### Terraform Configuration Files

```hcl

terraform {
  required_version = ">= 0.13"
  required_providers {
    ibm = {
      source = "IBM-Cloud/ibm"
      version = "1.20.1"
    }
  }
}

provider "ibm" {

  ibmcloud_api_key = var.ibmcloud_api_key

}

variable "ibmcloud_api_key" {
  description = "Enter your IBM Cloud API Key"
}
````

```hcl
data "ibm_is_subnets" "vpc_subnet" {
}

output "test" {
  value = data.ibm_is_subnets.vpc_subnet
}
```

```hcl
data "ibm_is_subnet" "vpc_subnet" {
  name = "testsubnet"
}

output "test" {
  value = data.ibm_is_subnets.vpc_subnet
}
```

### Actual Behavior

**Does not list all subnets visible from the given API Key:**
```hcl

Changes to Outputs:
  + name = {
      + id      = "2021-04-08 23:13:36.294534 +0000 UTC"
      + subnets = [
          + {
              + REMOVED_DATA_POINTS
              + name                         = "subnet-1"
              + zone                         = "us-south-1"
            },
```

**Does not find subnet name if the subnet is outside us-south region:**
```hcl
Error: No subnet found with name (testsubnet)

  on main.tf line 15, in data "ibm_is_subnet" "vpc_subnet":
  15: data "ibm_is_subnet" "vpc_subnet" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- tested on multiple versions of Terraform Provider since 1.20 onwards, and on Terraform 0.14.8 - always same result

**Comment by hkantare** [comment]
Please include region attribute in provider level for other regions

provider "ibm" {

  ibmcloud_api_key = var.ibmcloud_api_key"
  region = "us-east"

}

**Comment by sean-freeman** [comment]
Required action is not documented:
- https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_subnet
- https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_subnets

In addition the region argument for the provider is optional, it is not made clear in the documentation that this optional argument impacts the Data Sources:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs#region


Shouldn't the expected logical behaviour of Data Sources be:
> Get data for resource type
> ---- All data `or` select using optional argument name= / id=
> ---- All regions `or` select using optional argument region=

**Comment by ujjwal-ibm** [comment]
@sean-freeman 

As a workaround something like this can be used : 

```
provider "ibm" {
  region             = "eu-de"
} 
provider "ibm" {
  alias                 = "dal"
  region                = "us-south"
}
data ibm_is_subnets eu-de{
}
data ibm_is_subnets dal {
   provider = ibm.dal
}

output "subnets" {
  value = concat(
    tolist(data.ibm_is_subnets.eu-de.subnets), 
    tolist(data.ibm_is_subnets.dal.subnets)
    )
} 
```

**Comment by astha-jain** [comment]
Are we good to close?  @kavya498 FYI
