### ISSUE TITLE
ICD Service endpoint doesn't exist for region: "ca-tor"

### ISSUE THREAD

**Issue by blacksd** [IBM-Cloud/terraform-provider-ibm#2489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v0.14.8
+ provider registry.terraform.io/ibm-cloud/ibm v1.21.0
```

### Affected Resource(s)

* `ibm_database`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "ibm" {
   version = "1.21.0"
   ibmcloud_api_key  = var.ibmcloud_api_key
   region                = "ca-tor"
}

resource "ibm_database" "postgresql" {
  name              = "Test PGSQL"
  location          = "ca-tor"
  service           = "databases-for-postgresql"
  plan                = "standard"
  members_memory_allocation_mb = 8192
```

### Expected Behavior

ICD for PostgreSQL correctly provisioned in `ca-tor`.

### Actual Behavior

```
Error: Error getting database client settings: Error occured while configuring IBM Cloud Database Services: "ServiceEndpointDoesnotExist: ICD Service endpoint doesn't exist for region: \"ca-tor\""

  on .terraform/modules/ibm-databases-postgresql/database.tf line 2, in resource "ibm_database" "postgresql":
   2: resource "ibm_database" "postgresql" {
```

### Steps to Reproduce

1. `terraform apply`

### References

This is the same of what happened on: 
* #1894 for `che01`
* #1831 for `seo01`

meaning that the endpoints are missing in
https://github.com/IBM-Cloud/bluemix-go/blob/master/endpoints/endpoints.go.
The endpoints themselves are already OK:

```
dig api.ca-tor.databases.cloud.ibm.com

; <<>> DiG 9.10.6 <<>> api.ca-tor.databases.cloud.ibm.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57759
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;api.ca-tor.databases.cloud.ibm.com. IN	A

;; ANSWER SECTION:
api.ca-tor.databases.cloud.ibm.com. 300	IN A	104.18.1.221
api.ca-tor.databases.cloud.ibm.com. 300	IN A	104.18.0.221

;; Query time: 144 msec
;; SERVER: 10.255.0.2#53(10.255.0.2)
;; WHEN: Fri Apr 09 12:02:08 CEST 2021
;; MSG SIZE  rcvd: 95
```

I'll open a PR for the library and another PR here for bumping said library with the new version.

**Comment by kavya498** [comment]
@blacksd 
Can we know which version of provider you  are using?

**Comment by kavya498** [comment]
@blacksd 
provider version > =1.22.0 supports all regions of ICD endpoints..
Can you please try with latest provider and let us know

**Comment by blacksd** [comment]
@hkantare yes, it looks like the `1.23.0` version (latest available for `darwin_amd64`) is fine. Apologies for wasting your time.
