### ISSUE TITLE
ibm_satellite_location resource doesn't work correctly to ensure that resource is created / deleted appropriately

### ISSUE THREAD

**Issue by andrewferrier** [IBM-Cloud/terraform-provider-ibm#2497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.23.0
```

### Affected Resource(s)

* `ibm_satellite_location` (and maybe `ibm_satellite_host`).

### Terraform Configuration Files

Seems to affect any Satellite location, but example:

```hcl
resource "ibm_satellite_location" "location" {
  location      = "test-location"
  zones         = ["fake-zone-1", "fake-zone-2", "fake-zone-3"]
  managed_from  = "lon"

  cos_config {
    bucket  = ibm_cos_bucket.location_cos_bucket.bucket_name
    region  = "eu-gb"
  }
}
```

### Debug Output

Creation:

```
ibm_satellite_location.location: Creating...
ibm_satellite_location.location: Still creating... [10s elapsed]
ibm_satellite_location.location: Still creating... [20s elapsed]
ibm_satellite_location.location: Still creating... [30s elapsed]
ibm_satellite_location.location: Creation complete after 30s [id=test-location]
```

Destruction:

(no example, but it's very similar)

### Expected Behavior

When creating or destroying a location through Terraform, the provider should be blocking on marking the resource as created or destroyed until the location is ready, or completely gone.

### Actual Behavior

The provider almost immediately marks the resource as 'created' or 'destroyed', rather than the Terraform-standard behaviour of waiting for resource state to stabilize. This means other resources cannot use the location in a 'depends' manner; they cannot reliably depend on it being present or being gone.

### Steps to Reproduce

Run `terraform apply` or `terraform destroy` with a Terraform recipe similar to above.

### References

* Previous internal IBM discussion: https://ibm-garage.slack.com/archives/C01149RMSCU/p1618331537426300

**Comment by andrewferrier** [comment]
FYI - in my experience a location can take about 20-30 mins to create. That's the amount of time I'd expect the creation to block on...

**Comment by anilkumarnagaraj** [comment]
@andrewferrier 

We have added wait logic for location deletion, But not for location creation.
Location creation usually takes 15 minutes to complete. So in that wait time, users can use 'ibm_satellite_host' resource to assign their hosts to the control plane. We agree that we need to add wait time in ibm_satellite_location resource in order to mark the resource created completely. yes, we will make the changes in our code & update you about the fix.

**Comment by andrewferrier** [comment]
@anilkumarnagaraj I understand, but the issue is that as an automation tool, it's important to understand that users are not driving each of these steps manually; Terraform itself is co-ordinating them. Until the location is ready, hosts cannot be assigned to the control plane, so it's important that Terraform blocks on the location readiness.

**Comment by kavya498** [comment]
Available is [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.23.2)

**Comment by andrewferrier** [comment]
Cool @kavya498, seems to work!

**Comment by kavya498** [comment]
Can we close this issue? @andrewferrier

**Comment by andrewferrier** [comment]
Yeah, sorry, I should have done that :) Thanks for fixing.
