### ISSUE TITLE
ibm_satellite_location: cannot specify resource group

### ISSUE THREAD

**Issue by andrewferrier** [IBM-Cloud/terraform-provider-ibm#2499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform 0.15
IBM Provider 1.23.0

### Affected Resource(s)

`ibm_satellite_location`

### Expected Behavior

It is possible to specify the resource group for an IBM Cloud Satellite Location. Cloud Satellite Locations have a resource group in their data model, but is not expressible through the Terraform provider.

### Actual Behavior

It is not possible to specify the resource group for a Location, see https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-satellite-resources#satellite-location-resource.

**Comment by kavya498** [comment]
Available in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.23.2)

**Comment by kavya498** [comment]
closing this issue based on  https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2497
