### ISSUE TITLE
Save state in Cloud Object Storage

### ISSUE THREAD

**Issue by zhyinjun** [IBM-Cloud/terraform-provider-ibm#2506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform has the [state backend functionality](https://www.terraform.io/docs/language/settings/backends/index.html), each Terraform configuration can specify a backend, which defines where and how operations are performed, where state snapshots are stored, etc.

However, I did not find the Cloud Object Storage is listed in [here](https://www.terraform.io/docs/language/settings/backends/cos.html), does it support now? If it's not supported yet, which IBM Cloud Service I can leverage right now?

**Comment by l2fprod** [comment]
the COS listed in https://www.terraform.io/docs/language/settings/backends/cos.html is not IBM COS.

Using the S3 compatibility, I was able to use a COS bucket to save state https://github.com/l2fprod/cos-terraform-backend. It does not support versioning or locking but the basic of saving the state remotely works
