### ISSUE TITLE
Broken links in bold for ibm_container_cluster

### ISSUE THREAD

**Issue by qrilka** [IBM-Cloud/terraform-provider-ibm#2509]
The page https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_cluster has 2 links is a section with a bold font - https://cloud.ibm.com/docs/containers/cs_versions.html#version_types and https://cloud.ibm.com/docs/containers/cs_cluster_update.html
It looks like the links are broken as they open the same page "Getting started with IBM Cloud Kubernetes Service" and appear to have no information about cluster updates (which the 2nd link should point to)

**Comment by VaishnaviGopal** [comment]
Hi, closing this issue as the links are properly assigned
first link: [version changelog](https://cloud.ibm.com/docs/containers?topic=containers-changelog)
![image](https://user-images.githubusercontent.com/25303242/146127749-a9587624-8a73-494d-801c-043b5620253e.png)



second link: [version information and update information](https://cloud.ibm.com/docs/containers?topic=containers-cs_versions)
![image](https://user-images.githubusercontent.com/25303242/146127691-7e22afba-7f59-4bfa-b7a6-2aef5afbdddc.png)
