### ISSUE TITLE
Enhancement: Ability to define LBaaS health checks

### ISSUE THREAD

**Issue by coreylane** [IBM-Cloud/terraform-provider-ibm#252]
### Affected Resource(s)
- ibm_lbaas

### Request
Ability to define/update service health check configurations of [IBM Cloud Load Balancer](https://console.bluemix.net/docs/infrastructure/loadbalancer-service/getting-started.html#getting-started) (lbaas) instances. 
 
### Reference
- https://softlayer.github.io/reference/datatypes/SoftLayer_Network_LBaaS_LoadBalancerHealthMonitorConfiguration/
- http://softlayer.github.io/reference/services/SoftLayer_Network_LBaaS_HealthMonitor/updateLoadBalancerHealthMonitors/

**Comment by chajo19** [comment]
This feature would be very helpful to us at CA so that we can implement maintenance pages when performing updates to backend services that the LB's point to.

**Comment by sshingarapu** [comment]
Load balancer protocols should be able to send dynamically. I am trying to send frontend_protocol, frontend_port, backend_protocol, backend_port dynamically. Lets say i have set the below variable in the module.

protocols                             =       [{
                frontend_protocol     = "HTTPS"
                frontend_port         = 443
                backend_protocol      = "HTTP"
                backend_port          = 443
                load_balancing_method = "round_robin"
                tls_certificate_id    = "${ibm_compute_ssl_certificate.app_certs.id}"
                },
                {
                frontend_protocol     = "HTTP"
                frontend_port         = 80
                backend_protocol      = "HTTP"
                backend_port          = 80
                load_balancing_method = "round_robin"
                },

        ]

Read the above variable in the resource "ibm_lbaas" like the below.
protocols = ["${var.protocols}"]

When i do terraform plan it is throwing the below errors saying ports & protocols are not set.

ibm_lbaas.lbaas: "protocols.0.backend_port": required field is not set
ibm_lbaas.lbaas: "protocols.0.backend_protocol": required field is not set
ibm_lbaas.lbaas: "protocols.0.frontend_port": required field is not set
ibm_lbaas.lbaas: "protocols.0.frontend_protocol": required field is not set.

Please provide support to send the protocols & ports dynamically to the resource ibm_lbaas.

**Comment by Praveengostu** [comment]
@coreylane We will look in to this once we prioritize the items
@sshingarapu The error you are getting should be with your script. Pls go through using modules at https://www.terraform.io/docs/modules/usage.html
I tried as below and it works
```
main.tf
module "lbaas" {
  source = "lbaas"

  protocols = [{
    frontend_protocol     = "HTTPS"
    frontend_port         = 443
    backend_protocol      = "HTTP"
    backend_port          = 443
    load_balancing_method = "round_robin"
  },
    {
      frontend_protocol     = "HTTP"
      frontend_port         = 80
      backend_protocol      = "HTTP"
      backend_port          = 80
      load_balancing_method = "round_robin"
    },
  ]
}

lbaas/main.tf

resource "ibm_lbaas" "lbaas" {
  name        = "terraformLBExample"
  description = "lbaas example"
  subnets     = ["1511875"]
  protocols   = ["${var.protocols}"]
}

variable "protocols" {
  type = "list"
}
```

**Comment by sshingarapu** [comment]
@Praveengostu One argument missing here is "tls_certificate_id" in HTTPS case and i think that is the reason it is working for you.

Let me explain what exactly i am doing here.

In protocols i have to pass "tls_certificate_id" when the frontend_protocol is HTTPS.
There is no infrastructure data source support to get the id of existing certificates and hence i had to define the resource in module to create the certificate like below

resource "ibm_compute_ssl_certificate" "app_certs" {
  certificate = "${file("/path-to-cert-file")}"
  private_key = "${file("/path-to-key-file")}"
} 

Now i have to pass the above certificate id for "tls_certificate_id" in protocols section like below.
tls_certificate_id    = "${ibm_compute_ssl_certificate.app_certs.id}"

Now if i run terraform plan it will through the error which i mentioned previously. However it will work if i give value of "tls_certificate_id" is some number (eg: 16879) and this is not we are looking for.

I also tried the certificate resource in separate module and defined output variable to get the certificate id and referred the module output variable in "tls_certificate_id" but no luck.

**Comment by sshingarapu** [comment]
@Praveengostu Thanks for your quick response. 
The variable "tls_certificate_id" is not only the dynamic value but also protocols as we are sending from different modules.

For example: 
module "A" {
source = "lbaas"
protocols = [{
    frontend_protocol     = "HTTPS"
    frontend_port         = 443
    backend_protocol      = "HTTP"
    backend_port          = 443
    load_balancing_method = "round_robin"
    tls_certificate_id    = "${ibm_compute_ssl_certificate.app_certs.id}"
  },
    {
      frontend_protocol     = "HTTP"
      frontend_port         = 80
      backend_protocol      = "HTTP"
      backend_port          = 80
      load_balancing_method = "round_robin"
    },
  ]
}

module "B" {
source = "lbaas"
protocols = [{
    frontend_protocol     = "TCP"
    frontend_port         = 80
    backend_protocol      = "TCP"
    backend_port          = 80
    load_balancing_method = "round_robin"
   },
  ]
}

In module i have to refer the protocols as a variable from different modules.
lbaas/main.tf
resource "ibm_lbaas" "lbaas" {
  name        = "terraformLBExample"
  description = "lbaas example"
  subnets     = ["1511875"]
  protocols  = ["${var.protocols}"]
}

**Comment by Praveengostu** [comment]
@sshingarapu Received response from terraform team, and they confirm that passing the list of maps to resource modules may not work in all cases (https://github.com/hashicorp/terraform/issues/18147#issuecomment-393528303) So this look like a limitation with terraform core.   Please let us know if you need any more help.

**Comment by sshingarapu** [comment]
@Praveengostu Thanks for your help on this but the actual issue was with LB health checks which is still persistent.

**Comment by Praveengostu** [comment]
@coreylane @chajo19 To support the define/update of health monitor we would like to propose the below design 
New resource - ibm_lbaas_health_monitor
Arguments/schema
health_monitor_id - (Required,string) Health Monitor UUID
interval - (optional,int) Interval in seconds to perform
timeout - (optional,int)Health check methods timeout in 
maxretries - (optional,int)
url_path - (optional,string)If monitor is "HTTP", this specifies URL path 
The datasource ibm lbaas will be enhanced to provide the list of health check/health monitors

Let us know if this helps

**Comment by sshingarapu** [comment]
@Praveengostu, I am getting "type" is not a valid argument while using the above released provider. I used "type" in ibm_lbaas resource like below

resource "ibm_lbaas" "lbaas" {
  name        = "test"
  subnets     = ["1629415"]
  type           = "PRIVATE"
}

**Comment by sshingarapu** [comment]
@Praveengostu, My apologies. It is working as expected.

**Comment by Praveengostu** [comment]
@sshingarapu Could you please close this issue
