### ISSUE TITLE
ibm_container_vpc_worker_pool deletes existing pool before making a new one

### ISSUE THREAD

**Issue by ceastman-ibm** [IBM-Cloud/terraform-provider-ibm#2526]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_container_vpc_worker_pool

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Expected Behavior
I would expect that when a pool is getting replaced that the new pool would be created first and stabilize before the old pool is deleted

### Actual Behavior
The old pool was deleted which meant all the pods running were terminated with no place to start up.

### Steps to Reproduce

create a worker pool with ibm_container_vpc_worker_pool, generate plan, apply plan. then change the flavor of the pool in the template, generate plan and apply plan. 

1. `terraform apply`

### References

* #0000

**Comment by hkantare** [comment]
Can you please update more steps how are you deleting the exisiting workerpool...As per my basic understanding its a generic usage of Terraform if any argument is not able to update or if you destroy the resource it destroy's first and recreate again...To control this behaviour you have lifecycle block which can control the behaviour..
https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#create_before_destroy

**Comment by ceastman-ibm** [comment]
@hkantare this was probably it, i didnt realize there was a default destroy then create for the lifecycle.
