### ISSUE TITLE
Support creating IAM policies with operator 

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#2533]
We want to create an iam policy on a resource with the string match operator but by default only string equal which is applied

**Comment by nathan-hekman** [comment]
@hkantare @kavya498 please provide an ETA on closure for this one as it is high priority. Thanks

**Comment by hkantare** [comment]
We are working on this feature and we have provided a effort of 3 to 3.5 weeks (3rd week of May)
It will be part of  new release v1.26.0 Tentative 26May
