### ISSUE TITLE
ibm_resource_group data source doesn't honor dependencies properly

### ISSUE THREAD

**Issue by seansund** [IBM-Cloud/terraform-provider-ibm#2534]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v0.13.6
IBM-Cloud/ibm v1.23.1

### Affected Resource(s)

* data.ibm_resource_group
This specific test is related to ibm_resource_group but the issue may be more widespread.

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "resource_group_name" {
  type        = string
  description = "The name of the resource group that will be provisioned."
}
variable "ibmcloud_api_key" {
  type        = string
  description = "The api key for IBM Cloud access"
}
variable "region" {
  type        = string
  description = "The region where the resources will be provisioned."
}
module "resource_group" {
  source = "github.com/cloud-native-toolkit/terraform-ibm-resource-group.git"

  resource_group_name = var.resource_group_name
  ibmcloud_api_key    = var.ibmcloud_api_key
  provision           = true
}
module "logdna" {
  source = "github.com/cloud-native-toolkit/terraform-ibm-logdna.git?ref=v3.1.1"

  resource_group_name      = module.resource_group.name
  region                   = var.region
  provision                = true
  name_prefix              = "dependency-test"
}
```

### Debug Output

Here is the trace log of the failed run - https://gist.github.com/seansund/de2bcf60288a442c1874f045cdda3332

### Panic Output

N/A

### Expected Behavior

The github.com/cloud-native-toolkit/terraform-ibm-resource-group.git module outputs the name variable with a dependency on the resource that creates the resource group -
```hcl
output "name" {
  description = "The name of the resource group"
  value       = var.resource_group_name
  depends_on  = [ibm_resource_group.resource_group]
}
```

When the github.com/cloud-native-toolkit/terraform-ibm-logdna.git tries to lookup the resource group by name it is expected to wait until the `ibm_resource_group.resource_group` resource has completed before it attempts to look up the value.

### Actual Behavior

The logdna module immediately tries to use the resource and fails because it has not yet been created. The workaround we found is to pass the variable through a null_resource that prints the value before trying to use it in the data.ibm_resource_group block - 

```hcl
resource null_resource print_names {
  provisioner "local-exec" {
    command = "echo 'Resource group: ${var.resource_group_name}'"
  }
}

data "ibm_resource_group" "resource_group" {
  depends_on = [null_resource.print_names]

  name = var.resource_group_name
}
```

Because this workaround works, we believe the issue lies within the ibm_resource_group data source and not something more fundamental with Terraform. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is the same test case but with the workaround applied. (Notice v3.1.2 for the logdna module. That's the version where we applied the workaround)

```hcl
variable "resource_group_name" {
  type        = string
  description = "The name of the resource group that will be provisioned."
}
variable "ibmcloud_api_key" {
  type        = string
  description = "The api key for IBM Cloud access"
}
variable "region" {
  type        = string
  description = "The region where the resources will be provisioned."
}
module "resource_group" {
  source = "github.com/cloud-native-toolkit/terraform-ibm-resource-group.git"

  resource_group_name = var.resource_group_name
  ibmcloud_api_key    = var.ibmcloud_api_key
  provision           = true
}
module "logdna" {
  source = "github.com/cloud-native-toolkit/terraform-ibm-logdna.git?ref=v3.1.2"

  resource_group_name      = module.resource_group.name
  region                   = var.region
  provision                = true
  name_prefix              = "dependency-test"
}
```

Here's the log from the successful run that uses the workaround - https://gist.github.com/seansund/0efa798e1bc45577490ef2fe4c8b0647

**Comment by triceam** [comment]
I ran into this exact same issue.  I have a resource group that will be created in another terraform module and is a dependency to my module containing the data source that references the resource group.  The resource group has not been created yet, and is a dependency off my target module.  When I run terraform plan I get this error b/c the RG doesn't exist yet:

```
│ Error: [ERROR] Given Resource Group is not found in the account : %!s(<nil>) {
```

This happens b/c the data source is expecting the resource group to exist, even though it is created in a dependency passed into my module from the output of another module.  So, it is not respecting the dependency tree.

I can work around the issue by adding a local-exec provisioner that just echos the vpn name, which will correctly wait until the RG is created before executing, and having that provisioner be a dependency for the data source.
```
resource null_resource print_resources {
  provisioner "local-exec" {
    command = "echo 'Resource group: ${var.resource_group_name}'"
  }
}
data "ibm_resource_group" "resource_group" {
  depends_on = [null_resource.print_resources]

  name = var.resource_group_name
}
```

Here's the commit to work around the issue, which we really shouldn't have to do: https://github.com/cloud-native-toolkit/terraform-ibm-vpn-server/commit/080ae2d681ade022df0c8c76670f0ec3f2f15f98#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbb

**Comment by kavya498** [comment]
@seansund ,
It is an expected terraform behaviour..
You have added dependency on the attribute which is an user input, but not on any attribute that is known after apply(Eg: `id` of resource)..
name [here](https://github.com/cloud-native-toolkit/terraform-ibm-resource-group/blob/main/outputs.tf#L3) is basically an input that is provided by user, so terraform knows the value before applying the module and hence it starts executing the other module in parallel..
This is more of a concern to terraform core rather than to provider..
In such cases explicit depends_on between modules is encouraged..

Thanks.

**Comment by VaishnaviGopal** [comment]
@seansund  `depends_on` is now supported while using modules. so you can add `depends_on=[module.resource_group]` to module.logdna

**Comment by seansund** [comment]
> 

You missed the point of the issue... The value provided as input to the module is not a string provided by the user but is a value output from another module. That value has a pending status but the IBM Cloud terraform module ignores that status and uses it immediately. The null_resource provider correctly honors that status so we are forced to run those values through the null_resource provider first
