### ISSUE TITLE
Feature Request: Ability to change IOPS or expand existing volumes without destruction

### ISSUE THREAD

**Issue by cnocula-i** [IBM-Cloud/terraform-provider-ibm#2537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Similar to the changes for classic (https://github.com/IBM-Cloud/terraform-provider-ibm/issues/174) we would like to have the same option for Block Storage for VPC. Changing either the IOPS or the capacity results in recreation of the volume and thus data loss:

```
 2021/04/23 10:47:16 Terraform plan | -/+ resource "ibm_is_volume" "volumes" {
 2021/04/23 10:47:16 Terraform plan |         capacity                = 500
 2021/04/23 10:47:16 Terraform plan |       ~ crn                     = "<my_crn>"
 2021/04/23 10:47:16 Terraform plan |       + encryption_key          = (known after apply)
 2021/04/23 10:47:16 Terraform plan |       ~ id                      = "<my ID>"
 2021/04/23 10:47:16 Terraform plan |       ~ iops                    = 5000 -> 3000 # forces replacement
```

### New or Affected Resource(s)

* ibm_is_volume

### Potential Terraform Configuration

```hcl
resource "ibm_is_volume" "volumes" {
  count = length(var.volumes)
  name     = var.volumes[count.index].name
  profile  = "custom"
  zone     = var.zone
  capacity = var.volumes[count.index].capacity
  iops     = var.volumes[count.index].iops
  resource_group = data.ibm_resource_group.group.id
}
```

### References

* #0000

**Comment by hkantare** [comment]
This "ibm_is_volume" is to create a VPC block storage not a classic Infrastructure storage...
Currently the iops cann' t be expanded for VPC block storage 
https://cloud.ibm.com/apidocs/vpc#update-volume
Once API supports terraform will support the update

**Comment by cnocula-i** [comment]
Ah okay. Although: the API states, that it is supported via the `VolumePatch` in the request body. And this modification is also possible via the UI and via the CLI.

**Comment by astha-jain** [comment]
This capability is not GA released yet. Hence, cannot include it in current Terraform provider.

**Comment by astha-jain** [comment]
We will work on it when it is close to general availability.

**Comment by astha-jain** [comment]
This item can be closed as support for this feature was made available https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.32.1 
@kavya498 Please close this issue.

**Comment by hkantare** [comment]
The features are available in latest releases
