### ISSUE TITLE
Support specifying a specific IP for a server provisioned on PowerVS

### ISSUE THREAD

**Issue by nareshnayar1** [IBM-Cloud/terraform-provider-ibm#2545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

PowerVS allows a specific IP ( out of the designated subnet) to be used for provisioning a PowerVS server, instead of  PowerVS choosing an IP out of that subnet.  This capability has to be exposed at the Terraform provider level.
Currently the terraform provider lets PowerVS choose the IP ( out of the designatet subnet).

### New or Affected Resource(s)

* ibm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by surajsub** [comment]
Working this

**Comment by yussufsh** [comment]
Is this similar to https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3102? If yes then the feature should be available in the next release.

**Comment by pbfinley1911** [comment]
@yussufsh  This is the same as #3102  Are you able to link the pull request?  Otherwise, please close it manually.
