### ISSUE TITLE
How to add rules to existing is_network_acl

### ISSUE THREAD

**Issue by seansund** [IBM-Cloud/terraform-provider-ibm#2546]
Not a feature or bug request, just a general question... From the documentation I cannot determine how to add rules to an existing is_network_acl instance.

Generally, I'm trying to do the following:

```hcl
resource ibm_is_vpc vpc {
  name                        = local.vpc_name
  resource_group              = var.resource_group_id
  default_security_group_name = "${local.vpc_name}-security-group"
  default_network_acl_name         = "${local.vpc_name}-acl"
  default_routing_table_name  = "${local.vpc_name}-routing"
}

resource ibm_is_network_acl network_acl {
  depends_on = [ibm_is_vpc.vpc]

  name       = "${local.vpc_name}-acl"

  rules {
    name        = "egress"
    action      = "allow"
    source      = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    direction   = "outbound"
  }
  rules {
    name        = "ingress"
    action      = "allow"
    source      = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    direction   = "inbound"
  }
}
```

The ibm_is_network block errors because it says VPC is required (although the docs say it is optional). If the VPC is added it fails because a resource with that name already exists.

How does one add rules to an existing ACL?

**Comment by seansund** [comment]
Just to add further info, I see a `network-acl-rule-add` operation on the ibmcloud is plugin but the provider does not seem to have equivalent resources. As a workaround for now we can drop to the shell using a null_resource and call the ibmcloud is plugin operation...

**Comment by ujjwal-ibm** [comment]
Hi @seansund 

I was able to add rules as per the examples [here](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_network_acl)


I used the same configuration as shown in example, first I created a Network ACL and then added more rules to it.
As per the documentation, vpc id is required for generation 2

**Comment by astha-jain** [comment]
is this good to close?

**Comment by kavya498** [comment]
Closing this issue
Kindly, reopen is you face any issue..
Thanks.

**Comment by seansund** [comment]
Sorry, I missed the response but it doesn't seem to answer my question. From the example, it appears that you are creating a **new** network acl and adding rules to it. I understand how to do that. What I am looking for is a way to create a network acl then add rules to it later (i.e. not create a new acl). For example (the last resource):

```
data ibm_is_vpc vpc {
  name = var.vpc_name
}

resource ibm_is_network_acl subnet_acl {
  name = local.name
  vpc  = data.ibm_is_vpc.vpc.id
  resource_group = var.resource_group_id

  dynamic "rules" {
    for_each = local.acl_rules

    content {
      name        = rules.value["name"]
      action      = rules.value["action"]
      direction   = rules.value["direction"]
      source      = rules.value["source"]
      destination = rules.value["destination"]

      dynamic "tcp" {
        for_each = lookup(rules.value, "tcp", null) != null ? [ lookup(rules.value, "tcp", null) ] : []

        content {
          port_min = tcp.value["port_min"]
          port_max = tcp.value["port_max"]
          source_port_min = tcp.value["source_port_min"]
          source_port_max = tcp.value["source_port_max"]
        }
      }

      dynamic "udp" {
        for_each = lookup(rules.value, "udp", null) != null ? [ lookup(rules.value, "udp", null) ] : []

        content {
          port_min = udp.value["port_min"]
          port_max = udp.value["port_max"]
          source_port_min = udp.value["source_port_min"]
          source_port_max = udp.value["source_port_max"]
        }
      }

      dynamic "icmp" {
        for_each = lookup(rules.value, "icmp", null) != null ? [ lookup(rules.value, "icmp", null) ] : []

        content {
          type = icmp.value["type"]
          code = lookup(icmp.value, "code", null)
        }
      }
    }
  }
}

resource ibm_is_network_acl_rule new_rule {
  acl_id = ibm_is_network_acl.subnet_acl.id
  
  name        = "another-rule"
  action      = "allow"
  direction   = "inbound"
  source      = "0.0.0.0/0"
  destination = "0.0.0.0/0"
}
```

I know `ibm_is_network_acl_rule` doesn't exist currently but is that because there is some other way to add rules to an existing ACL? As it is, I'm resorting to dropping into a shell in a null_resource to use the cli to call `ibmcloud is network-acl-rule-add` which is less than ideal.

**Comment by hkantare** [comment]
@astha-jain we need to develop a new resource simialr to ibm_is_security_group_rule like ibm_is_network_acl_rule to attach a rule to exisitng network acl

**Comment by seansund** [comment]
I just opened a feature request - #2713

**Comment by astha-jain** [comment]
@seansund I got your point. Will prioritize this work.
