### ISSUE TITLE
ibm_is_public_gateway selected by subnet

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#2549]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
If you want to assign a subnet to an already existing public gateway you need to set the id of the public gateway. You can not easily create a new one because you just can have one by each zone (https://cloud.ibm.com/docs/vpc-on-classic-network?topic=vpc-on-classic-network-about-networking-for-vpc#use-a-public-gateway). This means that you can use a ibm_is_public_gateway data source. Unfortunately you need the name of the public gateway as a required parameter. Due to the fact that this name can set by other terraform scripts or sub projects it is hard to figure this out. 

A better idea would be that you select it by the name of the subnet. (you have a 1:1 relation)

### Potential Terraform Configuration

```hcl
data "ibm_is_public_gateway" "public_gateway" {
  for_each = var.pam_locations
  vpc      = data.ibm_is_vpc.pam_vpc.id
  zone     = each.key

}
```

* #0000

**Comment by mayukh-sarkar-1** [comment]
Hi...Please check if this [PR](https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2571) solves your problem!

**Comment by astha-jain** [comment]
@kavya498 please close this issue. work item complete
