### ISSUE TITLE
Apply for iam_service_id fails with 404 when using IBMCLOUD_VISIBILITY=private

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#2560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_iam_service_id

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = ">= 1.23.2"
    }
  }
}

provider "ibm" {
}

resource "ibm_iam_service_id" "functional_user" {
  name = "test-private-functional-user"
}
```

### Expected Behavior

Apply should have worked

### Actual Behavior

```hcl
$ terraform apply -auto-approve
ibm_iam_service_id.functional_user: Creating...
╷
│ Error: Error creating serviceID: Request failed with status code: 404, ServerErrorResponse: <!DOCTYPE html>
│ <html>
│ <head>
│ <title>Error</title>
│ <style>
│     body {
│         width: 35em;
│         margin: 0 auto;
│         font-family: Tahoma, Verdana, Arial, sans-serif;
│     }
│ </style>
│ </head>
│ <body>
│ <h1>An 404 error occurred in iam-gateway.</h1>
│ </body>
│ </html>
│
│   with ibm_iam_service_id.functional_user,
│   on main.tf line 13, in resource "ibm_iam_service_id" "functional_user":
│   13: resource "ibm_iam_service_id" "functional_user" {
│
╵
```

### Steps to Reproduce

```
export IBMCLOUD_VISIBILITY=private
terraform init
terraform apply
```

Things work if `IBMCLOUD_VISIBILITY=public`

**Comment by kavya498** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2539

**Comment by l2fprod** [comment]
@kavya498 FYI I built the latest provider from master and tried to use it but it does not seem to fix the issue I'm seeing

**Comment by l2fprod** [comment]
@kavya498 

just tested with latest provider and this still fails when VISIBILITY is private

```sh
$ terraform version
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.24.0
```

I can see the provider calling `private.us-south.iam.cloud.ibm.com` when I do `tcpdump`

**Comment by kavya498** [comment]
okay..
Is it working fine for your scenerio?

**Comment by l2fprod** [comment]
no it still fails

**Comment by l2fprod** [comment]
@kavya498 

is there any way to show more debug traces like the API calls?

**Comment by kavya498** [comment]
SDK issue,
provider SDK has to be migrated to v1 APIs

**Comment by l2fprod** [comment]
@kavya498 when is this planned to be fixed? It should be marked as a BUG, not an enhancement. The feature is currently broken.
