### ISSUE TITLE
Virtual server instance failing to start

### ISSUE THREAD

**Issue by anilkumarnagaraj** [IBM-Cloud/terraform-provider-ibm#2564]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

After provisioning the instance through 'ibm_is_instance' resource, VSI is going on "stopped" status.

### Affected Resource(s)

ibm_is_instance

### Terraform Configuration Files

```hcl
data "ibm_resource_group" "resource_group" {
  name = var.resource_group
}

resource "ibm_is_vpc" "satellite_vpc" {
  name = "${var.is_prefix}-vpc"
}

resource "ibm_is_subnet" "satellite_subnet" {
  count                    = 3
  name                     = "${var.is_prefix}-subnet-${count.index}"
  vpc                      = ibm_is_vpc.satellite_vpc.id
  total_ipv4_address_count = 256
  zone                     = "${var.ibm_region}-${count.index + 1}"
}

resource "tls_private_key" "example" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "ibm_is_ssh_key" "satellite_ssh" {

  name        = "${var.is_prefix}-ssh"
  public_key  = var.public_key != "" ? var.public_key : tls_private_key.example.public_key_openssh
}

resource "ibm_is_instance" "satellite_instance" {
  count          = 3

  name           = "${var.is_prefix}-instance-${count.index}"
  vpc            = ibm_is_vpc.satellite_vpc.id
  zone           = "${var.ibm_region}-${count.index + 1}"
  image          = "r014-931515d2-fcc3-11e9-896d-3baa2797200f"
  profile        = "mx2-8x64"
  keys           = [ibm_is_ssh_key.satellite_ssh.id]
  resource_group = data.ibm_resource_group.resource_group.id

  primary_network_interface {
    subnet = ibm_is_subnet.satellite_subnet[count.index].id
  }
}

resource "ibm_is_floating_ip" "satellite_ip" {
  count  = 3
  
  name   = "${var.is_prefix}-fip-${count.index}"
  target = ibm_is_instance.satellite_instance[count.index].primary_network_interface[0].id
}
```

### Expected Behavior

Instance should be in running status.

### Actual Behavior

After provisioning, instance going on stop status

### Steps to Reproduce

1.  Clone terraform provider repo 'https://github.com/IBM-Cloud/terraform-provider-ibm'
2. RUN 'make build'
3. Use the generated 'terraform-provider-ibm' binary to reproduce the error.

**Comment by anilkumarnagaraj** [comment]
@astha-jain @deepaksibm 

Due to this issue, We are not able to test our ROKS cluster resources.
Could you please look into this issue and let me know if you need any details?

**Comment by astha-jain** [comment]
Looking at it

**Comment by SunithaGudisagarIBM** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2566

**Comment by kavya498** [comment]
Available in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.24.0)
