### ISSUE TITLE
location, managed_from and resource_group_id mark these attibutes in ibm_satellite_location either DiffSuppress or throw back an error

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#2567]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* ibm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by kavya498** [comment]
Available in [1.25.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.25.0)
