### ISSUE TITLE
ibm_iam_authorization_policy can only be a resource, not a data source

### ISSUE THREAD

**Issue by triceam** [IBM-Cloud/terraform-provider-ibm#2575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the IBM Cloud Terraform provider `ibm_iam_authorization_policy` is only available as a resource, not as `data`

```
resource "ibm_iam_authorization_policy" "policy" {
  source_service_name = "is"
  source_resource_type = "flow-log-collector"
  target_service_name = "cloud-object-storage"
  roles = ["Writer"]
}
```

I want to be able to see if a policy like this exists before creating the policy instance.   Currently, the Terraform execution fails if the policy already exists.   I tried using count/conditionals to detect if the policy already exists, but didn't have any luck getting it to work as desired.

If you create a policy that already exists, Terraform execution fails with a message like so:

```
Error: Error creating authorization policy: 
Request failed with status code: 409, 
ServerErrorResponse: 
{
  "trace":"ffd62a460e444f3bac19145c153ca0fc",
  "status_code":409,
  "errors":[
    {
      "code":"policy_conflict_error",
      "message":"The policy wasn't created because an access policy with identical attributes already exists. Please update the roles in the existing policy, or update the one you're trying to assign to include a different attribute assignment." 
...
```
(truncated)

### Potential Terraform Configuration

If this were available as data, it could be used to conditionally create policies using count as a conditional (with a ternary operator), something like this:

```
data "ibm_iam_authorization_policy" "policy-lookup" {
  source_service_name = "is"
  source_resource_type = "flow-log-collector"
  target_service_name = "cloud-object-storage"
  roles = ["Writer"]
}

resource "ibm_iam_authorization_policy" "policy" {
  count = length(data.ibm_iam_authorization_policy.policy-lookup) == 0 ? 1 :0
  source_service_name = "is"
  source_resource_type = "flow-log-collector"
  target_service_name = "cloud-object-storage"
  roles = ["Writer"]
}
```
```

**Comment by kavya498** [comment]
```
data "ibm_iam_authorization_policy" "policy-lookup" {
  source_service_name = "is"
  source_resource_type = "flow-log-collector"
  target_service_name = "cloud-object-storage"
  roles = ["Writer"]
}
```

This configuration of datasource is not possible from our end.. API takes policy_id as input for GET call..
and also your your potential terraform configuration will never work because even if we have such datasource when the policy is not found we return error and hence your automation exits..

Instead we are coming up with new datasource that lists all authourisation policies on the account..
May be you can filter your policies based on your requirement using terraform locals block..
PR is linked to this issue..

Thanks
