### ISSUE TITLE
Support for dedicated host/group in instance template

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#2579]
Though there is an option for a dedicated host/group in the VPC instance template creation UI and CLI, it's missing in the terraform provider. 

I see an issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1394 dated last year. So, opening a new issue for tracking.

**Comment by kavya498** [comment]
Fixed in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.25.0)
