### ISSUE TITLE
Update autoscaling - ibm_is_instance_template and ibm_is_instance_group

### ISSUE THREAD

**Issue by juanpinzon** [IBM-Cloud/terraform-provider-ibm#2589]
Hi terraform-provider-ibm team,
I hope everything is going well,

I work as Solution Developer for GCAT team - IBM Cloud. Currently one of our clients requires to use auto-scaling that provisions instances with additional block storage attached to them. As part of our efforts to make it happen we contacted Sean Thornton sthornt@us.ibm.com, Software Engineer Team Lead, IBM Cloud. His team already developed this feature and it is possible, using API Calls, to create instances, based on an instance-template, that automatically attach a block-storage volume to them at auto-scaling time. Likewise, it is possible to create instance-groups that use this kind of instance-template. Attached you can find the API Calls to do such things.

Currently, even though this feature is available via IBM API Calls, IBM terraform plugin does not offer such auto-scaling feature, I tried to create the instance-template but it did not work due IBM terraform plugin does not have the option to create an instance-template with a prototype volume to be attached, instead always asks for a volume_id (which must be already created). It does not make sense, since both the instance and the volume will be provisioned at auto-scaling time, not at provisioning time. Here the documentation https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-data-sources#vpc-instance-templates, 

Could you please UPDATE the IBM terraform plugin to match this new feature. Thank you so much in advance for your help.

Please don't hesitate to contact me if you need further information.

Best Regards,
Juan Pinzon
Solution Developer | Global Cloud Acceleration Team | IBM Cloud

API Call to create an instance-template
```
response="$(curl -s -X POST "${vpc_api_endpoint}/instance/templates?version=${version}&generation=${generation}" \
  --header "Authorization: ${iam_token}" \
  --data-raw '{
    "name": "'${instance_template}'",
    "resource_group": {
      "id": "'${resource_group_id}'"
    },
    "vpc": {
      "id": "'${vpc_id}'"
    },
    "zone": {
      "name": "'"${region}-1"'"
    },
    "primary_network_interface": {
      "subnet": {
        "id": "'${subnet_id}'"
      }
    },
    "keys": [
      {
        "id": "'${key_id}'"
      }
    ],
    "profile": {
      "name": "bx2-2x8"
    },
    "image": {
      "id": "'${image_id}'"
    },
    "volume_attachments": [
      {
        "delete_volume_on_instance_delete": '${volume_delete_on_instance_delete}',
        "volume": {
          "capacity": '${volume_capacity}',
          "profile": {
            "name": "'${volume_profile_name}'"
          }
        }
      }
    ]
  }'
)"
instance_template_id=$(echo ${response} | jq  -r .id )
```

API Call to create an instance-group
```
response="$(curl -s -X POST "${vpc_api_endpoint}/instance_groups?version=${version}&generation=${generation}" \
  --header "Authorization: ${iam_token}" \
  --data-raw '{
    "name": "'${instance_group}'",
    "resource_group": {
      "id": "'${resource_group_id}'"
    },
    "membership_count": '${membership_count}',
    "subnets": [
      {
      "id": "'${subnet_id}'"
      }
    ],
    "instance_template": {
      "id": "'${instance_template_id}'"
    }
  }'
)"
```

**Comment by astha-jain** [comment]
We are working on supporting data volumes for templates to be used in creating instance groups. 
FYI @deepaksibm

**Comment by kavya498** [comment]
Closing this issue..
Thanks..
