### ISSUE TITLE
Provide a data source for ibm_is_vpc_address_prefix

### ISSUE THREAD

**Issue by seansund** [IBM-Cloud/terraform-provider-ibm#2594]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There currently isn't a data source available to retrieve the address prefixes that have been created for a VPC that corresponds with the `ibm_is_vpc_address_prefix` resource.

In particular it would be good to know the ip range, the zone, and whether the address prefix is a default for the VPC

### New or Affected Resource(s)

* `ibm_is_vpc_address_prefix` data source

### References

* #0000

**Comment by astha-jain** [comment]
I have added a feature request and we're prioritizing this work.
