### ISSUE TITLE
`service_endpoint` attribute validation for resource_instance resource..

### ISSUE THREAD

**Issue by kavya498** [IBM-Cloud/terraform-provider-ibm#2599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_resource_instance

### Terraform Configuration Files

```hcl
resource "ibm_resource_instance" "cms" {
    service ="cloudcerts"
    service_endpoints ="private"
    location = "eu-gb"
    name = "test-private-1"
    plan= "free"
}
```
silently ignores `service_endpoints ="private"` and creates instance in public.
A validation is required just like CLI
`Service endpoints can not be specified because no option found for the service plan in the given location`

```hcl
resource "ibm_resource_instance" "cms" {
    service ="cloudcerts"
    location = "eu-gb"
    name = "test-private-1"
    plan= "free"
    parameters = {
        allowed_network= "private-only"
    }
}
```
this way works as expected for CMS

### Expected Behavior

It should have created an instance a cms instance with private-only service endpoint

### Actual Behavior

It silently ignores `service_endpoints ="private"` and creates instance in public.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by hkantare** [comment]
Avaialble in latest releases
