### ISSUE TITLE
data ibm_iam_role should return custom roles for all services if no service provided

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#2606]
```
data "ibm_iam_roles" "my_iam_roles" {
}

```
only returns system (built-in) IAM roles, not any custom roles. Custom roles for a specific service are returned when the service is provided as parameter. How would I retrieve ALL custom roles? `ibmcloud iam roles` by default returns all system and custom roles.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
```
terraform {
  required_version = ">= 0.15"
  required_providers {
    ibm = {
      source  = "ibm-cloud/ibm"
      version = "~>1.24.0"
    }
  }
}
```
```
$ terraform -v
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.24.0

```

**Comment by kavya498** [comment]
@data-henrik ,
Fixed in [latest](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.25.0)
