### ISSUE TITLE
Terraform script for  Virtual server with VPC  is not working

### ISSUE THREAD

**Issue by vbsontakke** [IBM-Cloud/terraform-provider-ibm#2612]
Hi,
I am working on Virtual server with VPC
I am getting
Invalid JSON provided 
Error for
{
   "ibm_is_instance":{
      "bfast-resource-ord-ENXH5YVDJY-6":{
         "name":"${var.testacc_instance_name}",
         "tags":"${var.testacc_instance_tags}",
         "image":"${var.operating_system_type_d9518e20-944f-11eb-bfcf-b70b417fdb4f?var.testacc_instance_image:(var.custom_image_255f38d0-9464-11eb-b7d2-7d29f44d4afb)}",
         "profile":"${var.testacc_instance_profile}",
         "user_data":"${var.testacc_instance_user_data}",
         "primary_network_interface":{
            "subnet":"${var.neworexistingvpc?var.subnet_id:ibm_is_subnet.bfast-resource-ord-ENXH5YVDJY-2[0].id}",
            "primary_ipv4_address":"${var.testacc_instance_primary_network_interface_primary_ipv4_address}",
            "security_groups":"${var.testacc_instance_primary_network_interface_security_groups}"
         },
         "network_interfaces":{
            "name":"${var.testacc_instance_network_interfaces_name}",
            "subnet":"${var.neworexistingvpc?var.subnet_id:ibm_is_subnet.bfast-resource-ord-ENXH5YVDJY-2[0].id}",
            "security_groups":"${var.testacc_instance_network_interfaces_security_groups}"
         },
         "boot_volume":{
            "name":"${var.testacc_instance_boot_volume_name}"
         },
         "volumes":[
            "${var.is_data_volume?var.volume_id:ibm_is_volume.bfast-resource-ord-ENXH5YVDJY-4[0].id}"
         ],
         "vpc":"${var.neworexistingvpc?var.vpc_id:ibm_is_vpc.bfast-resource-ord-ENXH5YVDJY-1[0].id}",
         "zone":"${var.testacc_instance_zone}",
         "keys":[
            "${var.neworexistingssh?var.ssh_key:ibm_is_ssh_key.bfast-resource-ord-ENXH5YVDJY-3[0].id}"
         ]
      }
   }
}
above block

[VS_VPC_not_working_tf_error.tf.zip](https://github.com/IBM-Cloud/terraform-provider-ibm/files/6463402/VS_VPC_not_working_tf_error.tf.zip)

**Comment by mayukh-sarkar-1** [comment]
Hi @vbsontakke, 

The error seems a bit obfuscated. Can you please share a detailed error. Also would you be able to try without JSON and see if this problem persists. It seems the syntax for `network_interfaces` is not correct. Please refer docs as well. But anyway please share the detailed error. 

Thanks

**Comment by kavya498** [comment]
Closing this issue.. As there is no response..
Please reopen if you see this issue again..
Thanks
