### ISSUE TITLE
Error: Incompatible provider version - Apple M1

### ISSUE THREAD

**Issue by maximiano86** [IBM-Cloud/terraform-provider-ibm#2626]
Terraform Provider not available for apple `M1` is there any plan to support this platform?

terraform version
```
terraform version
Terraform v0.15.0
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html
```

Error
```
 terraform init

Initializing the backend...

Initializing provider plugins...
- Finding ibm-cloud/ibm versions matching 1.24.0...
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/ibm-cloud/ibm v1.24.0 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```

**Comment by kavya498** [comment]
@maximiano86  We are looking into this..

As a workaround please refer..
https://github.com/hashicorp/terraform/issues/27257#issuecomment-754777716
https://github.com/hashicorp/terraform/issues/27257#issuecomment-745640493

**Comment by Amina-Emenena** [comment]
Is this planned to be supported in any upcoming release? The workaround works, but I don't want to document that as a "solution" for our organization if it will be fixed in the near future.

**Comment by dprosper** [comment]
This is needed.

**Comment by hkantare** [comment]
We are working on this...It will be available in upcoming future releases

**Comment by dprosper** [comment]
@hkantare thank you, fyi: https://github.com/hashicorp/terraform-provider-aws/blob/41fe8a96949b8096e01ab6edbbb0026092e5bc6d/.goreleaser.yml#L16
