### ISSUE TITLE
data ibm_iam_access_group.id should return the access group id instead it returns the account id 

### ISSUE THREAD

**Issue by dmittal-delphix** [IBM-Cloud/terraform-provider-ibm#2627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.40.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.21.2

### Affected Resource(s)

* ibm_iam_access_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
#
# Copyright (c) 2021 by Delphix. All rights reserved.
#

module tags {
  source         = "git@github.com:delphix/terraform-delphix.git//tags?ref=2.5.5"
  cost_center_id = "qa"
  owner          = local.env
  project        = "DCoA"
}

data "ibm_iam_access_group" "image_builder_dcoa_group" {
  access_group_name = "dlpx-dcoa-dmittal"
}

data "ibm_resource_group" "env_group" {
  name = "dlpx-dcoa-${local.env}"
}

resource "ibm_resource_instance" "env_cos" {
  name              = "${local.env}-cos"
  resource_group_id = data.ibm_resource_group.env_group.id
  service           = "cloud-object-storage"
  plan              = "standard"
  location          = "global"
  tags              = module.tags.ibm_tags
}

resource "ibm_cos_bucket" "dev_de_images" {
  bucket_name          = "dlpx-dev-de-images-${local.env}"
  resource_instance_id = ibm_resource_instance.env_cos.id
  region_location      = "us-south"
  storage_class        = "smart"
  expire_rule {
    rule_id = "dlpx-dev-de-images-expire-${local.env}"
    enable  = true
    days    = 3
  }
}

resource "ibm_cos_bucket" "snapshot_de_images" {
  bucket_name          = "dlpx-snapshot-de-images-${local.env}"
  resource_instance_id = ibm_resource_instance.env_cos.id
  region_location      = "us-south"
  storage_class        = "smart"
  expire_rule {
    rule_id = "dlpx-snapshot-de-images-expire-${local.env}"
    enable  = true
    days    = 30
  }
}

resource "ibm_cos_bucket" "release_de_images" {
  bucket_name          = "dlpx-release-de-images-${local.env}"
  resource_instance_id = ibm_resource_instance.env_cos.id
  region_location      = "us-south"
  storage_class        = "smart"
  expire_rule {
    rule_id = "dlpx-release-de-images-expire-${local.env}"
    enable  = local.env != "prod"
    days    = 30
  }
}

# Create a role for accessing storage
resource "ibm_iam_access_group_policy" "image_builder_dcoa_policy" {
  access_group_id = data.ibm_iam_access_group.image_builder_dcoa_group.id
  roles           = ["Content Reader", "Object Writer"]
  resources {
    service = "cloud-object-storage"
    resource_group_id = data.ibm_resource_group.env_group.id
  }
}
```

### Debug Output
Acquiring state lock. This may take a few moments...
module.tags.data.external.tags_to_ibm: Refreshing state... [id=-]
data.external.check_workspace: Refreshing state... [id=-]
module.tags.data.external.tags_to_gcp: Refreshing state... [id=-]
module.tags.data.external.tags_to_aws: Refreshing state... [id=-]
module.tags.data.external.tags_to_oci_defined_dlpx: Refreshing state... [id=-]
module.tags.data.external.tags_to_azure: Refreshing state... [id=-]
data.ibm_iam_access_group.image_builder_dcoa_group: Refreshing state... [id=3ea3d4c29d3b46ff80ab363b2c96ed97]
data.ibm_resource_group.env_group: Refreshing state... [id=817ed351ba4a49d2be8ae822dec506e7]
data.ibm_iam_service_id.robot_user: Refreshing state... [id=dlpx-dcoa-dmittal]
ibm_iam_service_policy.access_policy_for_image: Refreshing state... [id=ServiceId-74e42c19-fae4-4f51-9c6f-1bd50211631d/14382e92-ead3-40a6-bce9-945d6ada93ab]
ibm_iam_service_api_key.service_api_key: Refreshing state... [id=ApiKey-92c5d50a-2fff-465d-8b85-d4adfcbe99be]
aws_ssm_parameter.service_api_key: Refreshing state... [id=/dlpx/dcenter/dmittal/ibm/service-api-key]
ibm_resource_instance.env_cos: Refreshing state... [id=crn:v1:bluemix:public:cloud-object-storage:global:a/3ea3d4c29d3b46ff80ab363b2c96ed97:070acd8b-bc3e-4d94-970c-9e8c64535487::]
ibm_cos_bucket.release_de_images: Refreshing state... [id=crn:v1:bluemix:public:cloud-object-storage:global:a/3ea3d4c29d3b46ff80ab363b2c96ed97:070acd8b-bc3e-4d94-970c-9e8c64535487:bucket:dlpx-release-de-images-dmittal:meta:rl:us-south:public]
ibm_cos_bucket.snapshot_de_images: Refreshing state... [id=crn:v1:bluemix:public:cloud-object-storage:global:a/3ea3d4c29d3b46ff80ab363b2c96ed97:070acd8b-bc3e-4d94-970c-9e8c64535487:bucket:dlpx-snapshot-de-images-dmittal:meta:rl:us-south:public]
ibm_cos_bucket.dev_de_images: Refreshing state... [id=crn:v1:bluemix:public:cloud-object-storage:global:a/3ea3d4c29d3b46ff80ab363b2c96ed97:070acd8b-bc3e-4d94-970c-9e8c64535487:bucket:dlpx-dev-de-images-dmittal:meta:rl:us-south:public]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ibm_iam_access_group_policy.image_builder_dcoa_policy will be created
  + resource "ibm_iam_access_group_policy" "image_builder_dcoa_policy" {
      + access_group_id    = "3ea3d4c29d3b46ff80ab363b2c96ed97"
      + account_management = false
      + id                 = (known after apply)
      + roles              = [
          + "Content Reader",
          + "Object Writer",
        ]
      + version            = (known after apply)

      + resources {
          + resource_group_id = "dlpx-dcoa-dmittal"
          + service           = "cloud-object-storage"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "dmittal"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_iam_access_group_policy.image_builder_dcoa_policy: Creating...

Error: Error creating access group policy: Request failed with status code: 400, ServerErrorResponse: {"trace":"5fe166b7b56f42819d39525344195908","errors":[{"code":"invalid_body","message":"Access groups can only be assigned against resources in the same account as the access group."}],"status_code":400}

  on storage.tf line 66, in resource "ibm_iam_access_group_policy" "image_builder_dcoa_policy":
  66: resource "ibm_iam_access_group_policy" "image_builder_dcoa_policy" {

Releasing state lock. This may take a few moments...

### Expected Behavior
When manually passed the access group ID 
Terraform will perform the following actions:

  # ibm_iam_access_group_policy.image_builder_dcoa_policy will be created
  + resource "ibm_iam_access_group_policy" "image_builder_dcoa_policy" {
      + access_group_id    = "AccessGroupId-d94220f5-8f4e-464e-8d6a-2a61b5e8007c"
      + account_management = false
      + id                 = (known after apply)
      + roles              = [
          + "Content Reader",
          + "Object Writer",
        ]
      + version            = (known after apply)

      + resources {
          + resource_group_id = "817ed351ba4a49d2be8ae822dec506e7"
          + service           = "cloud-object-storage"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "dmittal"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_iam_access_group_policy.image_builder_dcoa_policy: Creating...
ibm_iam_access_group_policy.image_builder_dcoa_policy: Creation complete after 4s [id=AccessGroupId-d94220f5-8f4e-464e-8d6a-2a61b5e8007c/75fd6b13-a720-49af-b345-217ebd278608]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
Releasing state lock. This may take a few moments...

### Actual Behavior
It fails because the ID returned by data task is of account instead of group. 
Error: Error creating access group policy: Request failed with status code: 400, ServerErrorResponse: {"trace":"0ca17ab6aa9747b5816ea0ba833989a7","errors":[{"code":"invalid_body","message":"Access groups can only be assigned against resources in the same account as the access group."}],"status_code":400}

  on storage.tf line 66, in resource "ibm_iam_access_group_policy" "image_builder_dcoa_policy":
  66: resource "ibm_iam_access_group_policy" "image_builder_dcoa_policy" {

### Steps to Reproduce

1. `terraform apply`
Run terraform init , plan and then apply. 

### References

* #0000

**Comment by hkantare** [comment]
This datasource lists set of accessgroups...Because when the datasource was developed you can create multiple access groups with same .....
To access the id of the access group please use below...The outerlevel ID is set to accountID

data.ibm_iam_access_group.image_builder_dcoa_group.groups.0.id

**Comment by dmittal-delphix** [comment]
Document says this : The name of the Access Group. If not specified all access group present in the account will be fetched.
So I thought if the name is not specified then it would list all. 
Yeah but this is working. Thanks !

**Comment by kavya498** [comment]
closing this issue.. 
Thanks..
