### ISSUE TITLE
ibm_is_vpn_gateways data source documentation is wrong

### ISSUE THREAD

**Issue by seansund** [IBM-Cloud/terraform-provider-ibm#2629]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

IBM cloud provider - v1.24.0

### Affected Resource(s)

* ibm_is_vpn_gateways data source

### Terraform Configuration Files

N/A

### Description of issue

The design/documentation of the data source doesn't make any sense. The resource is named `ibm_is_vpn_gateways` (plural) and takes no arguments as input, both of which imply the data source will return multiple gateways. However, the documentation of the output of the data source indicates that a single gateway is returned. I would expect to see a list of gateways returned...

**Comment by astha-jain** [comment]
Looking at it

**Comment by astha-jain** [comment]
Good to close

**Comment by kavya498** [comment]
closing this issue 
Thanks
