### ISSUE TITLE
ibm_satellite_location resource does not correctly support cross-region COS buckets

### ISSUE THREAD

**Issue by andrewferrier** [IBM-Cloud/terraform-provider-ibm#2640]
### Terraform CLI and Terraform IBM Provider Version

```
Terraform v0.15.3
on darwin_amd64
```

IBM provider v1.25.0

### Affected Resource(s)

* ibm_satellite_location

### Recreation

As per https://ibm-garage.slack.com/archives/C01PCPAB9HS/p1620718351081400, cross-region COS buckets should always be used for Satellite Locations. So if I use this:

```hcl
resource "ibm_resource_instance" "location_cos_instance" {
  name              = "location-cos-instance"
  resource_group_id = "resource-group"
  service           = "cloud-object-storage"
  plan              = "standard"
  location          = "global"
}

resource "ibm_cos_bucket" "location_cos_bucket" {
  bucket_name           = "location-cos-bucket"
  resource_instance_id  = ibm_resource_instance.location_cos_instance.id
  cross_region_location = "eu"
  storage_class         = "standard"
}

resource "ibm_satellite_location" "location" {
  location          = "location"
  zones             = ["location-zone-1", "location-zone-2", "location-zone-3"]
  managed_from      = "lon"
  resource_group_id = "resource-group"

  cos_config {
    bucket = ibm_cos_bucket.location_cos_bucket.bucket_name
    region = "eu"
  }
}
```

For the above Terraform, output like this is seen after about 13 minutes of running `terraform apply`:

```
     "Result": {
│         "code": "G0008",
│         "description": "The specified cluster could not be found by name. Provide the cluster ID instead.",
│         "incidentID": "9fe8e8d7-ffc8-4e27-ab92-47271a6ef365",
│         "recoveryCLI": "To list all clusters you have access to, run 'ibmcloud ks cluster ls'.",
│         "type": "General"
│     },
│     "RawResult": null
```

If instead the cos_config/region parameter is changed to `eu-gb`, I see errors like this after about 7 minutes of running `terraform apply`:

│     "Result": {
│         "code": "E6b1d",
│         "description": "A Satellite location with the same name already exists in your account. Choose another name and try again.",
│         "incidentID": "651507ab65470682-LHR",
│         "type": "Satellite"
│     },
│     "RawResult": null

### Expected Behavior

Location created.

### Actual Behavior

Errors shown above.

### References

See discussion with Satellite development here: https://ibm-garage.slack.com/archives/C01PCPAB9HS/p1620827200088200

**Comment by andrewferrier** [comment]
Hi - this is not an enhancement, this is a bug. Currently the location resource does not (appear to) support using COS buckets as they designed to be used.

**Comment by anilkumarnagaraj** [comment]
@andrewferrier 

"Result": {
│         "code": "G0008",
│         "description": "The specified cluster could not be found by name. Provide the cluster ID instead.",
│         "incidentID": "9fe8e8d7-ffc8-4e27-ab92-47271a6ef365",
│         "recoveryCLI": "To list all clusters you have access to, run 'ibmcloud ks cluster ls'.",
│         "type": "General"
│     },
│     "RawResult": null

The above error is related to satellite API not with 'ibm_satellite_location' resource.
After location creation, we will wait for location state to reach 'Action Required' state.
In that wait time, we will do repeated GET request call on satellite API to fetch the location details.
For unknown reason GET call has failed and returned 404 error here.

I am checking with the satellite team for resolution:
https://ibm-argonauts.slack.com/archives/G01F1PB6T7U/p1621346368004500

Tried the resource template which you have shared in the comment section and I was able to provision the satellite location with cross-region COS buckets.

anilkumarnagaraj@anis-MacBook-Pro cos % terraform apply
data.ibm_resource_group.resource_group: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ibm_cos_bucket.location_cos_bucket will be created
  + resource "ibm_cos_bucket" "location_cos_bucket" {
      + bucket_name           = "location-cos-bucket"
      + crn                   = (known after apply)
      + cross_region_location = "eu"
      + endpoint_type         = "public"
      + force_delete          = true
      + id                    = (known after apply)
      + resource_instance_id  = (known after apply)
      + s3_endpoint_private   = (known after apply)
      + s3_endpoint_public    = (known after apply)
      + storage_class         = "standard"
    }

  # ibm_resource_instance.location_cos_instance will be created
  + resource "ibm_resource_instance" "location_cos_instance" {
      + account_id              = (known after apply)
      + allow_cleanup           = (known after apply)
      + created_at              = (known after apply)
      + created_by              = (known after apply)
      + crn                     = (known after apply)
      + dashboard_url           = (known after apply)
      + deleted_at              = (known after apply)
      + deleted_by              = (known after apply)
      + extensions              = (known after apply)
      + guid                    = (known after apply)
      + id                      = (known after apply)
      + last_operation          = (known after apply)
      + location                = "global"
      + locked                  = (known after apply)
      + name                    = "location-cos-instance"
      + plan                    = "standard"
      + plan_history            = (known after apply)
      + resource_aliases_url    = (known after apply)
      + resource_bindings_url   = (known after apply)
      + resource_controller_url = (known after apply)
      + resource_crn            = (known after apply)
      + resource_group_crn      = (known after apply)
      + resource_group_id       = "7744ea5ec1ae483eaa466676abc8b972"
      + resource_group_name     = (known after apply)
      + resource_id             = (known after apply)
      + resource_keys_url       = (known after apply)
      + resource_name           = (known after apply)
      + resource_plan_id        = (known after apply)
      + resource_status         = (known after apply)
      + restored_at             = (known after apply)
      + restored_by             = (known after apply)
      + scheduled_reclaim_at    = (known after apply)
      + scheduled_reclaim_by    = (known after apply)
      + service                 = "cloud-object-storage"
      + service_endpoints       = (known after apply)
      + state                   = (known after apply)
      + status                  = (known after apply)
      + sub_type                = (known after apply)
      + tags                    = (known after apply)
      + target_crn              = (known after apply)
      + type                    = (known after apply)
      + update_at               = (known after apply)
      + update_by               = (known after apply)
    }

  # ibm_satellite_location.location will be created
  + resource "ibm_satellite_location" "location" {
      + created_on           = (known after apply)
      + crn                  = (known after apply)
      + host_attached_count  = (known after apply)
      + host_available_count = (known after apply)
      + id                   = (known after apply)
      + ingress_hostname     = (known after apply)
      + ingress_secret       = (sensitive value)
      + location             = "location"
      + managed_from         = "lon"
      + resource_group_id    = "7744ea5ec1ae483eaa466676abc8b972"
      + resource_group_name  = (known after apply)
      + tags                 = (known after apply)
      + zones                = [
          + "location-zone-1",
          + "location-zone-2",
          + "location-zone-3",
        ]

      + cos_config {
          + bucket = "location-cos-bucket"
          + region = "eu"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_resource_instance.location_cos_instance: Creating...
ibm_resource_instance.location_cos_instance: Still creating... [10s elapsed]
ibm_resource_instance.location_cos_instance: Still creating... [20s elapsed]
ibm_resource_instance.location_cos_instance: Creation complete after 25s [id=crn:v1:bluemix:public:cloud-object-storage:global:a/ab3ed67929c2a81285fbb5f9eb22800a:9285c5f3-fb61-444f-b25c-d7afe24fe156::]
ibm_cos_bucket.location_cos_bucket: Creating...
ibm_cos_bucket.location_cos_bucket: Still creating... [10s elapsed]
ibm_cos_bucket.location_cos_bucket: Creation complete after 13s [id=crn:v1:bluemix:public:cloud-object-storage:global:a/ab3ed67929c2a81285fbb5f9eb22800a:9285c5f3-fb61-444f-b25c-d7afe24fe156:bucket:location-cos-bucket:meta:crl:eu:public]
ibm_satellite_location.location: Creating...
ibm_satellite_location.location: Still creating... [10s elapsed]
ibm_satellite_location.location: Still creating... [20s elapsed]
ibm_satellite_location.location: Still creating... [30s elapsed]
ibm_satellite_location.location: Still creating... [40s elapsed]
ibm_satellite_location.location: Still creating... [50s elapsed]
ibm_satellite_location.location: Still creating... [1m0s elapsed]
ibm_satellite_location.location: Still creating... [1m10s elapsed]
ibm_satellite_location.location: Still creating... [1m20s elapsed]
ibm_satellite_location.location: Still creating... [1m30s elapsed]
ibm_satellite_location.location: Still creating... [1m40s elapsed]
....
.....
....
ibm_satellite_location.location: Still creating... [12m51s elapsed]
ibm_satellite_location.location: Still creating... [13m1s elapsed]
ibm_satellite_location.location: Still creating... [13m11s elapsed]
ibm_satellite_location.location: Still creating... [13m21s elapsed]
ibm_satellite_location.location: Still creating... [13m31s elapsed]
ibm_satellite_location.location: Creation complete after 13m38s [id=c2ht2n1l0n59a4p4vfbg]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

**Comment by andrewferrier** [comment]
@anilkumarnagaraj ok, thanks. Let me retry the testing from my end...

**Comment by kavya498** [comment]
@andrewferrier ,
Did you get chance to retry? Do you still face issue?

**Comment by kavya498** [comment]
Closing this issue..
Please reopen, if you still see this issue

**Comment by andrewferrier** [comment]
Apologies, just got round to testing this. Yes, this seems to be working now. Thank you!
