### ISSUE TITLE
ibm_container_cluster_config data source is broken in 1.25 release

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#2651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
$ terraform -v
Terraform v0.15.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.25.0
+ provider registry.terraform.io/sysdiglabs/sysdig v0.5.14

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* ibm_container_cluster_config

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.

data "ibm_container_cluster_config" "clusterConfig" {
  cluster_name_id   = var.cluster_id
  resource_group_id = data.ibm_resource_group.group.id
  config_dir        = "/tmp"
}

```

### Debug Output

![image](https://user-images.githubusercontent.com/11874942/118867433-1373a400-b8b1-11eb-8a93-0ef9fb77e347.png)

### Expected Behavior
The same exact code works fine in the provider release versions 1.24.0 nd 1.23.2

### Actual Behavior

It fails with the error seen above in the provider version 1.25.0
### Steps to Reproduce

1. add the code snippet above and run...
1. `terraform apply`

**Comment by dprosper** [comment]
In addition, when I run the code with 1.25.0 of the provicer, the following files are created in the /tmp folder relevant to the cluster:
![image](https://user-images.githubusercontent.com/11874942/118868641-6c900780-b8b2-11eb-822f-ddccecd9734b.png)

when running the same template with 1.24.0 of the  provicer, the following files are created in the /tmp folder relevant to the cluster:
![image](https://user-images.githubusercontent.com/11874942/118868711-80d40480-b8b2-11eb-883a-a556e3b4f284.png)

**Comment by kavya498** [comment]
@dprosper,
Looks like cluster config is able to download but it has failed due to some permission issue..
Error says `process cannot access the file because it is been used by other another process` 
Do you have any parallel process which is trying access the folder while the cluster config datasource is running?

**Comment by dprosper** [comment]
possibly, anti-virus or Terraform itself, but what is weird is this is working with earlier version of the provider, I reverted to version 1.24.0.

**Comment by kavya498** [comment]
I couldn't reproduce this issue on my machine (macOS)

**Comment by dprosper** [comment]
can I ask you to ping me on Slack @dimitri_prosper ?
