### ISSUE TITLE
When using `ibm_ob_monitoring` resource to install sysdig agents onto a cluster with no public service endpoint, the deployment fails 

### ISSUE THREAD

**Issue by jvallexm** [IBM-Cloud/terraform-provider-ibm#2656]
The default agent image that is used for the daemonset deployment is hosted at `quay.io/sysdig` but this cannot be accessed from the cluster. This issue could be fixed if it were possible to specify an icr image (like `icr.io/ext/sysdig/agent:latest`).

**Comment by kavya498** [comment]
@jvallexm ,
This is an issue from API side..
We don't have control on these images..

**Comment by hkantare** [comment]
closing the issue with above comment
