### ISSUE TITLE
Support for VPC scheduled scaling by adding instance group manager actions

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#2662]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for scheduled instance group actions

### New or Affected Resource(s)

* ibm_is_instance_group_manager (existing)
* ibm_is_instance_group_action (new)

### Potential Terraform Configuration

```hcl
resource "ibm_is_instance_group_manager" "instance_group_manager" {
  name                 = "testmanager"
  aggregation_window   = 120
  instance_group       = ibm_is_instance_group.instance_group.id
  cooldown             = 300
  manager_type         = "scheduled" # currently, there's only autoscale
  enable_manager       = true
  max_membership_count = 2
  min_membership_count = 1
}
```

### References

CLI supports autoscale and scheduled - https://cloud.ibm.com/docs/vpc?topic=vpc-scheduled-scaling-vpc

**Comment by astha-jain** [comment]
@kavya498 Please close this issue.

**Comment by hkantare** [comment]
closing the issue
