### ISSUE TITLE
ibm_app error - "Applications couldn't be staged, current status is FAILED

### ISSUE THREAD

**Issue by MarekMyjak** [IBM-Cloud/terraform-provider-ibm#267]
Hi there, I try to create ibm_app resource using terraform, but still get an error
`* ibm_app.app: Applications couldn't be staged, current status is  FAILED`
I am asking for help in solving this problem.
Below I provide a detailed description of the problem.

### Affected Resource(s)
- ibm_app

### Terraform Configuration Files
```hcl
provider "ibm" {
  bluemix_api_key = "****"
  region = "eu-gb"
}

data "ibm_org" "orgData" {
  org = "my-org"
}

data "ibm_space" "space" {
  space = "dev"
  org = "${data.ibm_org.orgData.org}"
}

data "ibm_app_domain_shared" "domain" {
  name = "eu-gb.mybluemix.net"
}

resource "ibm_app_route" "route" {
  domain_guid = "${data.ibm_app_domain_shared.domain.id}"
  space_guid = "${data.ibm_space.space.id}"
  host = "terraform-host"
}

resource "ibm_app" "app" {
  name = "my-app"
  space_guid = "${data.ibm_space.space.id}"
  app_path = "get-started-node-master.zip"
  buildpack = "sdk-for-nodejs"
  memory = "128"
  disk_quota = "128"
  route_guid = ["${ibm_app_route.route.id}"]

  instances = 1
  app_version = "1"
}
```
Tested on two types of application and buildpack

- sdk-for-nodejs - https://github.com/IBM-Cloud/get-started-node
- go_buildpack - https://github.com/IBM-Cloud/get-started-go

### Debug Output
https://gist.github.com/MarekMyjak/562d5cfa39ba818efc5087ec5be3f345

### Expected Behavior
Application running, and can be accessed via public url

### Actual Behavior
The application is created, but don't start. When starting manually from dashboard the same result.

### Logs error when try with node:
```
cat: /tmp/app/package.json: No such file or directory
!Unable to parse package.json
Failed to compile droplet: Failed to run finalize script: exit status 12
Staging failed: STG: Exited with status 223
```
### Logs error when try with go lang:
```
Failed to compile droplet: Failed to run finalize script: exit status 12
Staging failed: STG: Exited with status 223
```

### Terraform Version
Terraform v0.11.7
Tested on IBM Cloud Provider v0.9.1 and IBM Cloud Provider v0.8.0
Tested on Ubuntu 17.10 and windows 8.1

**Comment by sakshiag** [comment]
@MarekMyjak : The issue is with zip which you are using to create the app...package.json should be at the root of the zip file and there should be no top level folder.
When you download the zip directly from github , it has the top level folder under which package.json is present. When you try to create the app it will not be able to find the package.json.
Please refer this example , here we are using the null provisioner for cloning and creating the zip file for the app.
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-app/main.tf

**Comment by MarekMyjak** [comment]
It works now!
@sakshiag Thank you for your help.
