### ISSUE TITLE
"Satellite Link Administrator" role should be available for "satellite" service, but isn't 

### ISSUE THREAD

**Issue by annumberhocker** [IBM-Cloud/terraform-provider-ibm#2674]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

1.12

### Affected Resource(s)

* ibm_iam_access_group_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "ibm" {region             = "us-south"}

resource "ibm_iam_access_group" "sat_access_group" {  
  name = var.sat_access_group_name  
  description = join(" ", ["Satellite Admininstrators in the", var.resource_group_name, "environment"])
}

resource "ibm_iam_access_group_policy" "sat_link_policy" {  
  access_group_id = ibm_iam_access_group.sat_access_group.id  
  roles =  ["Satellite Link Administrator"]  
  resources  {    
    service = "satellite"    
    resource_type = "link"  
  }
}
```

### Expected Behavior

The  "Satellite Link Administrator" role would be set for the `satelite` service, `link` resource
![image](https://user-images.githubusercontent.com/38887336/119522346-7f3a8e80-bd41-11eb-802b-17fdb95b05bf.png)

These are all of the roles that are available in the UI
![image](https://user-images.githubusercontent.com/38887336/119522274-721d9f80-bd41-11eb-889e-333cee67b13a.png)

### Actual Behavior

Got this error: 

```console
2021/05/24 19:56:20 Terraform apply | 
 2021/05/24 19:56:20 Terraform apply | Error: RoleDoesnotExist: Satellite Link Administrator was not found. Valid roles are Manager, Reader, Writer, Deployer, Satellite Cluster Creator, Satellite Link Source and Endpoint Controller, Satellite Link Source Access Controller, Viewer, Administrator, Operator, Editor
 2021/05/24 19:56:20 Terraform apply | 
 2021/05/24 19:56:20 Terraform apply |   on agroups/main.tf line 192, in resource "ibm_iam_access_group_policy" "sat_link_policy":
 2021/05/24 19:56:20 Terraform apply |  192: resource "ibm_iam_access_group_policy" "sat_link_policy" {
 2021/05/24 19:56:20 Terraform apply | 
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kavya498** [comment]
@annumberhocker 
Looks like `Satellite Link Source and Endpoint Controller` assigns the  Satellite Link Administrator policy.
Can you please try with `Satellite Link Source and Endpoint Controller` in your roles.

**Comment by annumberhocker** [comment]
That worked.  Where is this documented?  How can we find details on the Terraform to handle Satellite roles and access

**Comment by kavya498** [comment]
It'ss a generic resource...we have n number pf policies with different services with each arguments
May be service team has documentation that can explain more about roles and policies..

To avoid confusions we give back the error given by apis
Your error clearly gives the list of supported roles for this service
```
 2021/05/24 19:56:20 Terraform apply | Error: RoleDoesnotExist: Satellite Link Administrator was not found. Valid roles are Manager, Reader, Writer, Deployer, Satellite Cluster Creator, Satellite Link Source and Endpoint Controller, Satellite Link Source Access Controller, Viewer, Administrator, Operator, Editor
 
```

**Comment by kavya498** [comment]
Closing this issue..
Please reopen, if you still face this issue
Thanks

**Comment by annumberhocker** [comment]
@kavya498 Please reopen this issue. The documentation https://cloud.ibm.com/docs/satellite?topic=satellite-iam#iam-roles-service clearly indicates that the "Satellite Link Administrator" and "Satellite Link Source Access Controller" have different permissions.  According to the chart, "Satellite Link Source Access Controller" will not have the same level of privileges.

**Comment by kavya498** [comment]
`"Satellite Link Administrator"` and `"Satellite Link Source Access Controller"` are not same 
but `"Satellite Link Administrator"` and `"Satellite Link Source and Endpoint Controller"` are same.. please find[ iam docs ](https://cloud.ibm.com/docs/account?topic=account-iam-service-roles-actions#satellite)
