### ISSUE TITLE
Feature request: user related resources

### ISSUE THREAD

**Issue by ruben-burr** [IBM-Cloud/terraform-provider-ibm#268]
Hi there,

as we build a platform for a larger project in our account, we scripted user management. For other things like k8s clusters we user terraform, while for user management, we are lacking some resources to be able to also do this. The commands for which we could not find an appropriate resource are:

- bx account user-invite
- bx account user-delete
- bx resource group-create
- bx iam user-policy-create
- bx iam user-policy-delete

Could you please add resources for users, resource groups and user-policies? 

Thanks,
Ruben

**Comment by tgau** [comment]
+1
Especially the ability to authorize user access to a kubernetes cluster is key.

**Comment by hkantare** [comment]
The support for following is available in v0.11.1 
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.1

- bx resource group-create(ibm_resource_group)
- bx iam user-policy-create(ibm_iam_user_policy)
- bx iam user-policy-delete

User invite and delete with required access can be done using "ibm_org" resource.
https://ibm-cloud.github.io/tf-ibm-docs/v0.11.0/r/org.html

**Comment by ruben-burr** [comment]
Thanks for adding this resources. Will update to them. 

How does the terraform provider recognize if a user must be deleted? If the user is removed from the last org?

**Comment by hkantare** [comment]
User can be deleted by removing the user email id from `user` attribute  and corresponding access levels.

resource "ibm_org" "testacc_org" {
    name = "myorg"
    org_quota_definition_guid = "myorgquotaguid"
    auditors = ["auditor@in.ibm.com"]
    managers = ["manager@in.ibm.com"]
    **users = ["user@in.ibm.com","user2@in.ibm.com"]**
    billing_managers = ["billingmanager@in.ibm.com"]
}

**Comment by kugelr** [comment]
@hkantare Did some testing here. And I can add users to the "ibm_org" as you described above. However, I would like to give this access to a certain resource group. My idea was to use a "ibm_iam_user_policy" for that. So my script looks as follows:

`resource "ibm_org" "test-org" {
  name = "account-setup"
  auditors = ["user1@test.de","user2@test.de"]
  managers = ["user1@test.de","user2@test.de"]
  users = ["user1@test.de","user2@test.de"]
  billing_managers = ["user1@test.de"]
}

resource "ibm_iam_user_policy" "policy" {
  ibm_id = "user1@test.de"
  roles  = ["Viewer"]
}
`
The error I am getting is this:
`
* ibm_iam_user_policy.policy: Request failed with status code: 400, ServerErrorResponse: {"errors":[{"code":1003,"message":"Can not get users from database. (User user1@test.de does not exist within the given account.)","more_info":""}]}
`

So as far as I can see the user is indeed added to the ibm_org. Also I can add him to a ibm_space. However, I am not able to assign him any other kind of access. This is confusing. So IMHO there is the missing the mapping between resource groups/resources and ibm_orgs/ibm_space.

My overall goal is: 
- Add a user which has an IBM ID but is not associated with my account or my org and space so far
- Give this user access (i.e. Viewer) to a Cloud Object Store

Am I missing something here?

**Comment by ruben-burr** [comment]
Hast du Mal ne dependency zwischen den beiden Ressourcen eingebaut? So dass erst die org uns dann die Policy angelegt wird?


--

Ruben Burr
Managing Consultant


T. +49 711 22040-700 ∙ M. +49 151 52880992
ruben.burr@novatec-gmbh.de ⋅ www.novatec-gmbh.de

Novatec Consulting GmbH
Dieselstraße 18/1, D-70771 Leinfelden-Echterdingen

Free/busy information for appointments (ics to import as calendar): https://tinyurl.com/y9m2ulgr

Folgen Sie uns auf Facebook, LinkedIn, Twitter, XING oder auf unserem Blog

Sitz: Leinfelden-Echterdingen ∙ Handelsregister: Amtsgericht Stuttgart ∙ HRB 739078 
Geschäftsführer: Stefan Bleicher, Hans-Dieter Brenner, Konrad Pfeilsticker, Michael Schuchart



________________________________
Von: René Kugel <notifications@github.com>
Gesendet: Donnerstag, 18. Oktober 2018 17:01
An: IBM-Cloud/terraform-provider-ibm
Cc: Ruben Burr; Author
Betreff: Re: [IBM-Cloud/terraform-provider-ibm] Feature request: user related resources (#268)

@hkantare Did some testing here. And I can add users to the "ibm_org" as you described above. However, I would like to give this access to a certain resource group. My idea was to use a "ibm_iam_user_policy" for that. So my script looks as follows:

`resource "ibm_org" "test-org" {
name = "account-setup"
auditors = ["user1@test.de","user2@test.de"]
managers = ["user1@test.de","user2@test.de"]
users = ["user1@test.de","user2@test.de"]
billing_managers = ["user1@test.de"]
}

resource "ibm_iam_user_policy" "policy" {
ibm_id = "user1@test.de"
roles = ["Viewer"]
}
The error I am getting is this:

ibm_iam_user_policy.policy: Request failed with status code: 400, ServerErrorResponse: {"errors":[{"code":1003,"message":"Can not get users from database. (User user1@test.de does not exist within the given account.)","more_info":""}]}
`

So as far as I can see the user is indeed added to the ibm_org. Also I can add him to a ibm_space. However, I am not able to assign him any other kind of access. This is confusing. So IMHO there is the missing the mapping between resource groups/resources and ibm_orgs/ibm_space.

My overall goal is:

Add a user which has an IBM ID but is not associated with my account or my org and space so far
Give this user access (i.e. Viewer) to a Cloud Object Store

Am I missing something here?

**Comment by kugelr** [comment]
@hkantare Added a dependency as you told me - Didn't fix the problem. Still the same error.

**Comment by hkantare** [comment]
Once you create a org need to create a space and then attach the policy to that user
```
resource "ibm_org" "test-org" {
  name             = "new-account"
  auditors         = ["xxxx@in.ibm.com"]
  managers         = ["xxxx@in.ibm.com"]
  users            = ["xxxx@in.ibm.com"]
  billing_managers = ["xxxx@in.ibm.com"]
}

resource "ibm_space" "space" {
  org        = "${ibm_org.test-org.name}"
  name       = "accspace"
  auditors   = ["xxxxx@in.ibm.com"]
  managers   = ["xxxx@in.ibm.com"]
  developers = ["xxxx@in.ibm.com"]
}

resource "ibm_iam_user_policy" "policy" {
  depends_on = ["ibm_org.test-org", "ibm_space.space"]
  ibm_id     = "xxxx@in.ibm.com"
  roles      = ["Viewer"]
}
````
I tried with above configuration it worked successfully

```
2018/10/22 11:20:43 [DEBUG] plugin: waiting for all plugin processes to complete...
  id = xxxx@in.ibm.com/60f5c471-4e42-4457-8388-08b9a807e63b
  ibm_id = xxxx@in.ibm.com
  resources.# = 1
  resources.0.region = 
  resources.0.resource = 
  resources.0.resource_group_id = 
  resources.0.resource_instance_id = 
  resources.0.resource_type = 
  resources.0.service = 
  roles.# = 1
  roles.0 = Viewer
  version = 1-2378ed4eedabc98412fdea1655cd7dda
ibm_org.test-org:
  id = 4090c447-36ce-4986-a7dc-ec214a972fd0
  auditors.# = 1
  auditors.1847556851 = xxxx@in.ibm.com
  billing_managers.# = 1
  billing_managers.1847556851 = xxxx@in.ibm.com
  managers.# = 1
  managers.1847556851 = xxxx@in.ibm.com
  name = new-account
  org_quota_definition_guid = d8787d01-7943-4b80-b06e-ee2576137e19
  users.# = 1
  users.1847556851 = xxxx@in.ibm.com
ibm_space.space:
  id = 1895e765-6856-4689-aab7-09a7bfbf45ce
  auditors.# = 1
  auditors.1847556851 = xxxx@in.ibm.com
  developers.# = 1
  developers.1847556851 = xxxx@in.ibm.com
  managers.# = 1
  managers.1847556851 = xxxx@in.ibm.com
  name = accspace
  org = new-account

````
