### ISSUE TITLE
Error waiting for ALBs in zone for roks cluster

### ISSUE THREAD

**Issue by palkokec** [IBM-Cloud/terraform-provider-ibm#2681]
Hi, 
using IBM schematics with classic roks cluster to create new ibm_container_worker_pool_zone_attachment results into the terraform error. 
The resources are marked as tainted, however they seem to be created in the cluster.

### Affected Resource(s)

* ibm_container_worker_pool_zone_attachment

### Terraform Configuration Files

```
resource "ibm_container_worker_pool" "cluster_agent_pool" { 
          cluster           = ibm_container_cluster.cluster.id
          worker_pool_name  = var.agent_worker_pool_name
          machine_type      = var.agent_worker_flavor
          hardware          = var.agent_worker_hardware
          size_per_zone     = var.agent_worker_count
          labels            = var.agent_worker_labels
          resource_group_id = data.ibm_resource_group.group.id
          entitlement       = var.entitlement
        }
      
 resource "ibm_container_worker_pool_zone_attachment" "agents_zone" {      
          cluster         = ibm_container_cluster.cluster.id
          worker_pool     = element(split("/", ibm_container_worker_pool.cluster_agent_pool.id), 1)
          zone            = var.datacenter
          public_vlan_id  = data.ibm_network_vlan.vlan_public.id
          private_vlan_id = data.ibm_network_vlan.vlan_priv.id
          wait_till_albs  = true
        }
```

### Debug Output

2021/05/27 10:54:09 Terraform apply | Error: Error waiting for ALBs in zone () of cluster () to become ready: Error retrieving ALBs for cluster: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"","code":"","description":"This operation is not supported for your cluster's version.","type":"General"}
 2021/05/27 10:54:09 Terraform apply | 
 2021/05/27 10:54:09 Terraform apply |   on  line 61, in resource "ibm_container_worker_pool_zone_attachment" "agents_zone":
 2021/05/27 10:54:09 Terraform apply |   61: resource "ibm_container_worker_pool_zone_attachment" "agents_zone" {
 2021/05/27 10:54:09 Terraform apply | 
 2021/05/27 10:54:09 Terraform apply | 
 2021/05/27 10:54:09 Terraform apply | 
 2021/05/27 10:54:09 Terraform APPLY error: Terraform APPLY errorexit status 1
 2021/05/27 10:54:09 Could not execute action

### Expected Behavior

The ALBs in zone are created and no error returned from terreform. The terraform does not mark resources as tainted.

### Actual Behavior

Terraform throws above mentioned error and marks the resources as *tainted*, however it seems the resources are created properly in cluster.

### Steps to Reproduce

1.  create roks classic cluster
2. add zone attachment resources to tf
3. `terraform plan`
4. `terraform apply`

**Comment by hkantare** [comment]
For openshift clusters we should set wait_till_albs = false  since we don't have albs for them
```resource "ibm_container_worker_pool_zone_attachment" "agents_zone" {      
          cluster         = ibm_container_cluster.cluster.id
          worker_pool     = element(split("/", ibm_container_worker_pool.cluster_agent_pool.id), 1)
          zone            = var.datacenter
          public_vlan_id  = data.ibm_network_vlan.vlan_public.id
          private_vlan_id = data.ibm_network_vlan.vlan_priv.id
          wait_till_albs  = false
        }
        ```

**Comment by palkokec** [comment]
Thanks for the info. We will recreate the resources with _wait_till_albs  = false_ option.
