### ISSUE TITLE
bug: ibm_is_vpc_routing_table value of id is concatenated string of VPC ID and Routing Table ID

### ISSUE THREAD

**Issue by sean-freeman** [IBM-Cloud/terraform-provider-ibm#2693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.25.0
```

### Affected Resource(s)

* ibm_is_vpc_routing_table

### Terraform Configuration Files

```hcl
resource "ibm_is_vpc" "testacc_vpc" {
  name = "testvpc"
  address_prefix_management = "manual"
}

resource "ibm_is_vpc_address_prefix" "testacc_vpc_address_prefix" {
  name = "testvpc-address-prefix"
  zone = "us-east-1"
  vpc  = ibm_is_vpc.default_vpc.id
  cidr = "10.20.0.0/21"
}

resource "ibm_is_vpc_routing_table" "test_ibm_is_vpc_routing_table" {
    vpc = ibm_is_vpc.testacc_vpc.id
    name = "route-table-test"
    route_direct_link_ingress = false
    route_transit_gateway_ingress = false
    route_vpc_zone_ingress = false
}

# SUCCESS using... routing_table = ibm_is_vpc_routing_table.test_ibm_is_vpc_routing_table.routing_table
# FAILURE using... routing_table = ibm_is_vpc_routing_table.test_ibm_is_vpc_routing_table.id
resource "ibm_is_vpc_routing_table_route" "test_ibm_is_vpc_routing_table_route" {
  vpc = ibm_is_vpc.testacc_vpc.id
  routing_table = ibm_is_vpc_routing_table.test_ibm_is_vpc_routing_table.routing_table
  zone = ibm_is_vpc_address_prefix.testacc_vpc_address_prefix.zone
  name = "custom-route-1"
  destination = "10.20.0.30/32"
  action = "deliver"
  next_hop = "10.20.0.24"
}
```

### Terraform State file
```json
    {
      "mode": "managed",
      "type": "ibm_is_vpc_routing_table",
      "name": "test_ibm_is_vpc_routing_table",
      "provider": "provider[\"registry.terraform.io/ibm-cloud/ibm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "created_at": "2021-05-31T16:37:46.000Z",
            "href": "https://us-east.iaas.cloud.ibm.com/v1/vpcs/r014-xxxx-xxxx-xxxx-xxxx-xxxxxx/routing_tables/r014-yyyyyy-yyyy-yyyy-yyyy-yyyyyy",
            "id": "014-xxxx-xxxx-xxxx-xxxx-xxxxxx/r014-yyyyyy-yyyy-yyyy-yyyy-yyyyyy",
            "routing_table": "r014-yyyyyy-yyyy-yyyy-yyyy-yyyyyy"
          }
        }
      ]
    }
```

### Expected Behavior

Consistent behaviour with other resources, where `id` returns only the Resource Short ID.

### Actual Behavior

Inconsistent behaviour, difficult to notice the error in `ibm_is_vpc_routing_table_route` was cascading error from dependency creation of Routing Table `ibm_is_vpc_routing_table`.

**Comment by kavya498** [comment]
'id' here is the ID of the resource but not the Id of routing table.. and it cannot be consistent across resources
All the dependent / child resources do generally have id as combination of IDs..and it's an ideal terraform practice..
Please use 'routing_table' attribute to get routing table id

Thanks.

**Comment by kavya498** [comment]
Closing this issue..
Thanks.
