### ISSUE TITLE
feat: ibm_is_vpc resource to output ALBs attached to VPC 

### ISSUE THREAD

**Issue by jkerezsi** [IBM-Cloud/terraform-provider-ibm#2695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform: `v0.13.5`
IBM provider: `1.25.0`

### Affected Resource(s)

* ibm_is_vpc

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
```

### Expected Behavior

I am using VPC gen 2 Openshift clusters. When I create a VPC cluster an ALB will be automatically created with a name "kube- <clusterId> ". In order to get the ID of the ALB i should be able get as an outpot of the vpc resource. This is not an Ingress ALB but a VPC ALB which gets created once a vpc cluster is created. However terraform does not know about this resource. 

### Actual Behavior

There is no possible solution at the moment to access VPC ALB's ID which is triggerd by vpc cluster creation.

To access this ID via CLI: `ibmcloud is lbs`

### Steps to Reproduce

1. Create vpc 2 openshift cluster with Terraform by creating a vpc and vpc_cluster resource
2. Above step will trigger a creation of a VPC load-balancer

**Comment by hkantare** [comment]
Can you try from ibmcloud cli commands to list the albs for openshift cluster

ibmcloud ks ingress alb ls --cluster <clusterid>


```
|harinireddy@Harinis-MacBook-Pro ~ % ibmcloud ks ingress alb ls --cluster c2qcq24w0c09393icfg0
FAILED
This operation is not supported for your cluster's version. (E3918)

Incident ID: 196f81ea-d71e-43af-b768-a5c6dcaeaf8a
```

We don't get back any albs for openshift that why the list is empty

**Comment by jkerezsi** [comment]
I see, then I would like to convert this ticket to be a a feature.

**Comment by hkantare** [comment]
Can this feature request opend at aramada IKS side

**Comment by hkantare** [comment]
Can you please update this issue with IKS issue so that we can keep a track on this..

**Comment by jkerezsi** [comment]
> Can this feature request opend at aramada IKS side

@hkantare  I updated the ticket. Please let me know if I can keep this issue here.

**Comment by kavya498** [comment]
Closing this issue for now as we don't have API support..
Kindly, track using IKS ticket..
Thank you..
