### ISSUE TITLE
Couldn't able to delete the Service Policy

### ISSUE THREAD

**Issue by sridharmula** [IBM-Cloud/terraform-provider-ibm#2703]
We are trying to provision in a new cluster and we have deleted the service ID  and when we ran terraform destroy it was complains about service policy couldn't found and no way to delete them. IBM cloud UI or CLI because the Service ID no longer exists  (CLI params require the ServiceID, and UI does not show individual policies.) 

Below is the conversation

Guillermo Cabrera:

The problem I see here is in our IBM Terraform provider. The deletion of the policies did not occur via Terraform but was done automatically as a result of that ServiceId that was deleted. As such, when you did your terraform destroy the IBM Terraform provider is also not aware of soft deleted policies.
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/adf805036f8028dae74003b3a583efefe25a2c79/ibm/resource_ibm_iam_service_policy.go#L422
ibm/resource_ibm_iam_service_policy.go:422
        return fmt.Errorf("Error deleting service policy: %s", err)

Terraform destroy actually does a soft delete and I believe it should remove the resource from the terraform state file.

**Comment by kavya498** [comment]
@guicabr,
As discussed, Can we add a condition to empty the state file on response status = deleted as well?

**Comment by guicabr** [comment]
Looking into this
