### ISSUE TITLE
Destroy ibm_container_cluster is not consistent 

### ISSUE THREAD

**Issue by kugelr** [IBM-Cloud/terraform-provider-ibm#271]
Hi,

we have the following use case: for the sake of security we want to destroy and recreate our cluster regularly. We want to do this in automation. We have a Jenkins job which destroys and creates our cluster called "staging". Terraform states that the destruction completes within 3 seconds. However, in the IBM Cloud WebUI the cluster is still visible in the state "deleting". If we run a "terraform apply" right after the destruction completes, terraform returns an error "cluster with name 'staging' already exist...'

We would like to suggest that the cluster destruction only completes if the cluster is completely removed.

Regards,
René  

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- ibm_container_cluster

### Terraform Configuration Files
resource "ibm_container_cluster" "staging" {
  name            = "${var.kubernetes_cluster_name}"
  datacenter      = "fra02"
  machine_type    = "u2c.2x4"
  isolation       = "public" 
  public_vlan_id  = "${var.public_non_prod_vlan_id}"
  private_vlan_id = "${var.private_non_prod_vlan_id}"
  subnet_id       = ["${ibm_subnet.private_staging_subnet.id}", "${ibm_subnet.public_staging_subnet.id}"]
  workers = [{
    name   = "worker1"
    action = "add"
  },
    {
      name   = "worker2"
      action = "add"
    },
    {
      name   = "worker3"
      action = "add"
    },
  ]
  account_guid = "${var.ibm_bmx_account_guid}"
}

### Debug Output
...
ibm_container_cluster.staging: Refreshing state... (ID: b977cff06c954d968749e72c30b7b179)
ibm_container_cluster.staging: Destroying... (ID: b977cff06c954d968749e72c30b7b179)
ibm_container_cluster.staging: Destruction complete after 3s
...

### Expected Behavior
Terraform should wait until the cluster is "really" destroyed (usually takes ~3 to 4 mins). So that in the next step the cluster can be recreated again. 

### Actual Behavior
Terraform states that the cluster destruction is completed after 3 seconds. When recreating Terraform runs into an error saying cluster with the name "staging" already exists 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply (create cluster)
2. terraform destroy (destroy cluster)
3. terraform apply (recreate cluster right after destruction completed)

**Comment by Praveengostu** [comment]
@kugelr Cluster resource does not support to wait for the cluster to be destroyed completely during terraform destroy. We will investigate and update you on this. As a workaround  to avoid the name conflict during apply after destroy you can use the random_string resource(https://www.terraform.io/docs/providers/random/r/string.html) to generate a random string and append it to name of the cluster every time it gets created.

**Comment by kugelr** [comment]
@Praveengostu thanks for your reply. I am looking forward for the update. Unfortunately, your proposed workaround is not feasible for us since we have multiple dev teams which depend on a consistent cluster name. We currently worked around the issue by querying the existence of the cluster via a bash script. However, we would prefer to have a Terraform-only approach for our cluster setup.

**Comment by Praveengostu** [comment]
@kugelr Sure We will look in to this..

**Comment by sakshiag** [comment]
@kugelr : We have added the wait for the deletion of cluster in the latest release.. You can get the latest binary from https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.0

**Comment by Praveengostu** [comment]
@kugelr Can we close this issue?
