### ISSUE TITLE
Database for Redis is provisioning with automatic KMS key even when passed with user generated KMS instance

### ISSUE THREAD

**Issue by ananya23d** [IBM-Cloud/terraform-provider-ibm#2717]
Terraform Version

Terraform v0.12.29

    provider.ibm v0.16.7

Affected Resource(s)

    ibm_database

Terraform Configuration FilesI am using terraform template 

> provider "ibm" {
    ibmcloud_api_key = "xxx"
    iaas_classic_api_key = "xxx"
    iaas_classic_username = "xxx"
}
resource ibm_database "redis" {
  name = "${var.redis_name}"
  plan = "${var.redis_plan}"
  location = "${var.redis_location}"
  service = "${var.redis_service}"
  resource_group_id = "${var.redis_resource_group_id}"
  members_memory_allocation_mb = "${var.redis_members_memory_allocation_mb}"
  members_disk_allocation_mb = "${var.redis_members_disk_allocation_mb}"
  members_cpu_allocation_count = "${var.redis_mmembers_cpu_allocation_count}"
  tags = "${var.redis_tags}"
  key_protect_key = "${var.redis_key_protect_key}"
  key_protect_instance = "${var.redis_key_protect_instance}"
  version = "${var.redis_version}"
  service_endpoints = "${var.redis_service_endpoints}"
}
variable "redis_resource_group_id" {
  type = "string"
  default = "270979f087074ccb9f3f84314b64a402"
}
variable "redis_name" {
  type = "string"
  default = "redis-test-imp"
}
variable "redis_plan" {
  type = "string"
  default = "standard"
}
variable "redis_location" {
  type = "string"
  default = "us-south"
}
variable "redis_service" {
  type = "string"
  default = "databases-for-redis"
}
variable "redis_tags" {
  default = ["tag1"]
  type = "list"
}
variable "redis_members_memory_allocation_mb" {
  default = 2048
}
variable "redis_members_disk_allocation_mb" {
  default = 20480
}
variable "redis_key_protect_instance" {
	type = "string"
	default = "b4e80d20-005e-4687-915b-e55adb1d7eb0"
}
variable "redis_key_protect_key" {
	type = "string"
	default = "mcmp"
}
variable "redis_mmembers_cpu_allocation_count" {
	default = 0
}
variable "redis_version" {
	type = "string"
	default = "6"
}
variable "redis_service_endpoints" {
	type = "string"
	default = "public"
}

where I have used the KMS instances. I have authorized the KMS instance to be used by Redis from IAM -> Authorization.
From the IBMCloud portal I am able to use the KMS instance and its key for provisioning the Redis instance.
However when I use the same KMS instance (key_protect_instance) and the kms key (key_protect_key) id in the terraform template, the provisioning is going through with the automatic KMS key on the IBMcloud portal.

**Comment by kavya498** [comment]
@ananya23d ,
Can we know which version of provider you are using? We don't have 0.16.7

Looks like you are not passing CRN for `redis_key_protect_key` 
`key_protect_key`  argument accepts key CRN.. Please refer [docs](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#argument-reference)

**Comment by kavya498** [comment]
Hope the above comment resolved the issue..
Closing this issue.. Please reopen if issue still persists..

Thanks.
