### ISSUE TITLE
Cannot download ibm provider from terraform

### ISSUE THREAD

**Issue by StevenYCChou** [IBM-Cloud/terraform-provider-ibm#272]
### Terraform Version
v0.11.6

### Affected Resource(s)
N/A - mostly provider ibm 

### Terraform Configuration Files
N/A

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
N/A

### Expected Behavior
Install the IBM provider for me

### Actual Behavior
provider ibm is not available for installation.

### Steps to Reproduce
```
terraform init -get-plugins=true

Initializing modules...
- module.my-service
  Getting source "../../ibm_plans"

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "ibm" not available for installation.

A provider named "ibm" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

```

**Comment by MarekMyjak** [comment]
@StevenYCChou  At the moment ibm provider isn't in the official hashicorp repository
You can download provider [here](https://github.com/IBM-Cloud/terraform-provider-ibm/releases)

**Comment by sakshiag** [comment]
Closing this issue based on above comment.

**Comment by devurandom** [comment]
Would it be possible to register the IBM provider with the Terraform provider repository?

### Expected Behavior

I would expect `terraform init` to be able to automatically download the IBM provider when it is referenced in a Terraform configuration.

### Actual Behavior

```
$ terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "ibm" not available for installation.

A provider named "ibm" could not be found in the official repository.
[...]
```

### Steps to Reproduce
1. Have `~/.terraform.d/plugins/` NOT contain `terraform-provider-ibm_*`
2. Have a file `main.tf` with contents `provider "ibm" {}`
3. Run `terraform init`
