### ISSUE TITLE
IBM Cloud Provider - `ibm_satellite_location` silent correction

### ISSUE THREAD

**Issue by david-shepard** [IBM-Cloud/terraform-provider-ibm#2724]
Hi, it appears there's a minor bug related to the resource `ibm_satellite_location` resource within IBM Cloud Provider (v1.26.0). For example, if you specify the wdc region, and attempt any other `managed_from` location than `wdc06` it silently corrects it to `wdc04` (in the statefile), so when you run it twice it errors out since you still have `wdc06` in HCL vs `wdc04` in the state.

I'd expect it to error out if the initial value you pass to `managed_from` is invalid in the first place.

**Comment by david-shepard** [comment]
Thread: https://ibm-analytics.slack.com/archives/C01149RMSCU/p1624299920245400

**Comment by anilkumarnagaraj** [comment]
@david-shepard 

This is a bug should have handled by the service team. But they replied to me saying it's working as designed & not an API issue. 

Below is the reply message from the service team:

"This is working as designed as far as I’m concerned. We take in the managed_from value at API and as long as the metro supports satellite (e.g. wdc) we create the location in the supported datacenter
the managed from exact location should not matter one bit to the user, as this is just the location of the backend control plane
the customers resources are not deployed here, but in their own infrastructure"

As the service team mentioned, They are only concerned about metro value(wdc) not with data center(wdc04).
Based on that, we will work on the fix from the provider side to silently ignore the error message if there is any data center value difference.

For a temporary solution, you can use lifecycle ignore_changes block in 'ibm_satellite_location' resource block to suppress the error:

resource "ibm_satellite_location" "create_location" {
  location          = "test01"
  managed_from      = "wdc06"
  resource_group_id = data.ibm_resource_group.group.id

  lifecycle {
    ignore_changes = [
      managed_from,
    ]
  }

}


We wil let you know once the fix is ready.

**Comment by pierre-archambault** [comment]
@anilkumarnagaraj in a consumer/producer contract the producer doesn't have the necessary context to determine how to correct the input appropriately. The best course of action is to fail the request forcing the consumer to correct its input and resubmit the request.

The current behaviour is not ideal and will lead to expensive defects at scale.

Please reconsider updating the implementation as per the requirements submitted by CPDaaS.

**Comment by anilkumarnagaraj** [comment]
@david-shepard @pierre-archambault 

We have fixed the data center auto-correct issue. Terraform provider will fail immediately if an invalid data center is specified for satellite location creation.
Here is the list of supported data center: "wdc04, lon04, fra02, wdc, lon, fra"

If user pass the metro name without the datacenter(wdc), still provider accepts it as valid value & process the request.
Please let me know if you have any issue in accepting just metro name has a valid value.

Fix is available in the latest release: https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.28.0

**Comment by david-shepard** [comment]
Thanks for the fix. Something I noticed though - it appears that it fails when the user inputs `wdc` or `lon` it fails since it doesn't appear that the Satellite API accepts metro's **without** datacenters **and** (looking at the [source](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_satellite_location.go) it doesn't look like there's any logic to coerce `wdc` --> `wdc04`.)

Here's the error if you just specify `wdc` for example:

```
Error: Error waiting for location (c3s4hs7w0tj58s81prfg) to reach ready state: Error Getting location : Not Found
{
    "StatusCode": 404,
    "Headers": {
        "Cache-Control": [
            "max-age=0, no-cache, no-store"
        ],
        "Content-Length": [
            "270"
        ],
        "Content-Security-Policy": [
            "default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self'"
        ],
        "Content-Type": [
            "application/json; charset=utf-8"
        ],
        "Date": [
            "Wed, 21 Jul 2021 16:20:36 GMT"
        ],
        "Expires": [
            "Wed, 21 Jul 2021 16:20:36 GMT"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Server-Timing": [
            "edge; dur=3",
            "origin; dur=37916",
            "cdn-cache; desc=MISS"
        ],
        "Strict-Transport-Security": [
            "max-age=31536000; includeSubDomains"
        ],
        "X-Carrier": [
            "prod-wdc04-carrier103"
        ],
        "X-Content-Type-Options": [
            "nosniff"
        ],
        "X-Correlation-Id": [
            "08ddfe08-02db-4f7c-9d4e-6a7af188ab97"
        ],
        "X-Frame-Options": [
            "DENY"
        ],
        "X-Hostname": [
            "armada-global-api-94f9bbc7f-gdn25"
        ],
        "X-Permitted-Cross-Domain-Policies": [
            "master-only"
        ],
        "X-Region": [
            "us-east"
        ],
        "X-Request-Id": [
            "ced622b2-48c1-9105-9c9b-5b3f1e2cf95f"
        ],
        "X-Xss-Protection": [
            "1; mode=block"
        ]
    },
    "Result": {
        "code": "G0008",
        "description": "The specified cluster could not be found by name. Provide the cluster ID instead.",
        "incidentID": "ced622b2-48c1-9105-9c9b-5b3f1e2cf95f",
        "recoveryCLI": "To list all clusters you have access to, run 'ibmcloud ks cluster ls'.",
        "type": "General"
    },
    "RawResult": null
}
```

(Note: it's also odd that the error message talks about `cluster` and not `location`)

**Comment by david-shepard** [comment]
One thing to note, a consequence of coercing a metro name into a `metro name-datacenter` is that the HCL does not match the statefile. For example if you specify `wdc` in the HCL, the state file will contain `wdc04`. Which causes subsequent attempts (future `terraform apply`'s) to error out, unless you modify your HCL to reflect `wdc04`.
