### ISSUE TITLE
CIS Domain Setting resource still have bluemix-go adk dependency

### ISSUE THREAD

**Issue by kavya498** [IBM-Cloud/terraform-provider-ibm#2734]
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_cis_domain_settings.go#L945
It should be using generated SDK Client

**Comment by kavya498** [comment]
@MalarvizhiK , Can this be fixed on high priority?
We will be removing bluemix-go cis SDK dependencies from terraform Provider

**Comment by MalarvizhiK** [comment]
@shivaleelac is working on this.

**Comment by kavya498** [comment]
closing this issue thanks..
