### ISSUE TITLE
VPC Instance Template and Instance Groups

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#2750]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

After having created a VPC Instance Template and Instance Group, if there is a change to the Instance Template, the template is deleted by Terraform and recreated.  However, since the Instance Group cannot exist without an Instance Template, the deletion fails with the following error:  

```sh
╷
│ Error: instance template is attached to instance group
```

In order to fix this issue you are forced to take either one of the following two options: 
Option 1. Taint the Instance Group and the Instance Template, so both are deleted and recreated. 
or
Option 2. Add a lifecycle event to the instace template of `create_before_destroy` and change the name of the instance template (since duplicate template names are not allowed).

This request is to enable the behavior described in Option 1 in the IBM provider itself, i.e. if there is a destroy of the instance template as a result of a change/update to the template, then the provider should also destroy the instance group.

### New or Affected Resource(s)

* ibm_is_instance_template
* ibm_is_instance_group

### Potential Terraform Configuration

```hcl
resource "ibm_is_instance_template" "instance_template" {
  name           = "${var.name}-template"
  image          = var.image_id
  profile        = "cx2-2x4"
  resource_group = var.resource_group_id

  primary_network_interface {
    subnet          = var.subnet_id
    security_groups = var.security_groups
  }

  vpc       = var.vpc_id
  zone      = "${var.region}-1"
  keys      = var.ssh_key_ids
  user_data = var.user_data

  lifecycle {
    create_before_destroy = true
  }
}

resource "ibm_is_instance_group" "instance_group" {
  name               = "${var.name}-group"
  instance_template  = ibm_is_instance_template.instance_template.id
  instance_count     = var.instance_count
  subnets            = var.subnets
  load_balancer      = var.lb_id
  load_balancer_pool = element(split("/", var.lb_pool_id), 1)
  application_port   = 80
  resource_group     = var.resource_group_id
}
```

### References

* #0000

**Comment by astha-jain** [comment]
@dprosper Have you tried tainting instance group and instance template both? What is the behavior? 
IMO tainting both should work just fine.

**Comment by dprosper** [comment]
@astha-jain: that is option 1 above, and yes it does work.  What I am suggesting is the provider should perform that work, i.e. when using **Schematics** as the engine to run my Terraform template, tainting the instance group resource is not an option. Ideally, thiss would be done by the provider when it is determining it needs to destroy the template

**Comment by astha-jain** [comment]
Instance group provide capability to update instance template, terraform provider must also just update the instance group with the new template and not force a new instance group.

**Comment by dprosper** [comment]
agreed, but I believe that is the behavior today, however in order to update the instance group with the new instance template, you have to:
1. create the new instance template
2. update instance group with the instance template
3. delete the old instance template. 

1 & 3 cannot happen easily today, because the instance template name is considered unique, therefore this forces you into option 2 above.

```
╷
│ Error: Error creating InstanceTemplate: instance template name vsdheast-frontend-template is already in use
│ {
│     "StatusCode": 400,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store, must-revalidate"
│         ],
│         "Cf-Cache-Status": [
│             "DYNAMIC"
│         ],
│         "Cf-Ray": [
│             "6603f3c64dee19df-EWR"
│         ],
│         "Cf-Request-Id": [
│             "0ab656aff2000019dfed9d1000000001"
│         ],
│         "Content-Length": [
│             "234"
│         ],
│         "Content-Type": [
│             "application/json; charset=utf-8"
│         ],
│         "Date": [
│             "Wed, 16 Jun 2021 12:13:28 GMT"
│         ],
│         "Expect-Ct": [
│             "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
│         ],
│         "Expires": [
│             "-1"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Server": [
│             "cloudflare"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000; includeSubDomains"
│         ],
│         "Vary": [
│             "Accept-Encoding"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Request-Id": [
│             "b3820182-979a-4b06-8bd6-795837061095"
│         ],
│         "X-Xss-Protection": [
│             "1; mode=block"
│         ]
│     },
│     "Result": {
│         "errors": [
│             {
│                 "code": "validation_unique_failed",
│                 "message": "instance template name vsdheast-frontend-template is already in use",
│                 "target": {
│                     "name": "instance_template.name",
│                     "type": "field"
│                 }
│             }
│         ],
│         "trace": "b3820182-979a-4b06-8bd6-795837061095"
│     },
│     "RawResult": null
│ }
```

**Comment by astha-jain** [comment]
Are there any challenges with lifecycle meta attribute option 2 above?

**Comment by dprosper** [comment]
Yes, using the lifecycle attribute in option 2 is not enough, the name of the Instance Template needs to be changed as well, otherwise when you run `terraform apply` you receive the error shown in the above comment, i.e.: 
```sh
Error: Error creating InstanceTemplate: instance template name vsdheast-frontend-template is already in use
```

**Comment by ujjwal-ibm** [comment]
@dprosper if we make `name` as optional field, this should resolve this issue.
