### ISSUE TITLE
VPC Address Prefix can't delete even though Subnet Deletion process complete.

### ISSUE THREAD

**Issue by duelist2021jp** [IBM-Cloud/terraform-provider-ibm#2759]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

$ terraform -version
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.26.0

### Affected Resource(s)
* ibm_is_vpc_address_prefix

### Terraform Configuration Files
locals{
  res_grp_id = "xxxxxxxxxxxxxxxxxxxxxx"
  zone_name = "jp-tok-1"
}

resource "ibm_is_vpc" "my_access_vpc" {
  name = "my-vpc"
  address_prefix_management = "manual"
  resource_group = local.res_grp_id
}

resource "ibm_is_vpc_address_prefix" "my_access_vpc_address_prefix"{
  name = "my-vpc-prefix"
  zone = local.zone_name
  vpc = ibm_is_vpc.my_access_vpc.id
  cidr = "10.0.0.0/16"
}

resource "ibm_is_public_gateway" "my_access_public_gateway"{
  name = "my-public-gateway"
  vpc = ibm_is_vpc.my_access_vpc.id
  zone = local.zone_name
  resource_group = local.res_grp_id
}

resource "ibm_is_subnet" "my_access_vpc_subnet"{
  name = "my-vpc-subnet"
  vpc = ibm_is_vpc.my_access_vpc.id
  zone = local.zone_name
  ipv4_cidr_block = "10.0.1.0/24"
  public_gateway = ibm_is_public_gateway.my_access_public_gateway.id
  resource_group = local.res_grp_id
}

resource "ibm_is_security_group" "my_access_vm_sgrp"{
  name = "my-vpc-security-group"
  vpc = ibm_is_vpc.my_access_vpc.id
  resource_group = local.res_grp_id
}

resource "ibm_is_security_group_rule" "my_access_vm_sgrp_rule_tcp"{
  group = ibm_is_security_group.my_access_vm_sgrp.id
  direction = "inbound"
  tcp{
    port_min = 22
    port_max = 80
  }
}

resource "ibm_is_security_group_rule" "my_access_vm_sgrp_rule_icmp"{
  group = ibm_is_security_group.my_access_vm_sgrp.id
  direction = "inbound"
  icmp{
    code = 0
    type = 8
  }
}

### Expected Behavior
I confirmed terraform apply process completed successfully about the above terraform configuration file.

ibm_is_vpc.my_access_vpc: Creating...
ibm_is_vpc.my_access_vpc: Still creating... [10s elapsed]
ibm_is_vpc.my_access_vpc: Creation complete after 19s [id=r022-bb73ad82-6b5a-4ef7-bb5d-84ccfaa5b537]
ibm_is_vpc_address_prefix.my_access_vpc_address_prefix: Creating...
ibm_is_public_gateway.my_access_public_gateway: Creating...
ibm_is_security_group.my_access_vm_sgrp: Creating...
ibm_is_vpc_address_prefix.my_access_vpc_address_prefix: Creation complete after 1s [id=r022-bb73ad82-6b5a-4ef7-bb5d-84ccfaa5b537/r022-647be451-368a-490d-9114-f85af72f30b7]
ibm_is_security_group.my_access_vm_sgrp: Creation complete after 4s [id=r022-da0a7f0e-c51a-4ebc-bf84-f45089df9652]
ibm_is_security_group_rule.my_access_vm_sgrp_rule_icmp: Creating...
ibm_is_security_group_rule.my_access_vm_sgrp_rule_tcp: Creating...
ibm_is_security_group_rule.my_access_vm_sgrp_rule_tcp: Creation complete after 2s [id=r022-da0a7f0e-c51a-4ebc-bf84-f45089df9652.r022-690467f7-6de5-43fd-8944-9929f8c25ee5]
ibm_is_security_group_rule.my_access_vm_sgrp_rule_icmp: Creation complete after 4s [id=r022-da0a7f0e-c51a-4ebc-bf84-f45089df9652.r022-fdb631ed-bbaf-4472-90a3-c2564213ff67]
ibm_is_public_gateway.my_access_public_gateway: Still creating... [10s elapsed]
ibm_is_public_gateway.my_access_public_gateway: Creation complete after 16s [id=r022-d289b7d1-e5ea-474e-a49e-ee10f15ca05d]
ibm_is_subnet.my_access_vpc_subnet: Creating...
ibm_is_subnet.my_access_vpc_subnet: Still creating... [10s elapsed]
ibm_is_subnet.my_access_vpc_subnet: Creation complete after 13s [id=02e7-f89111db-67db-4041-96e3-6275db37c223]

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

But I found the vpc address prefix couldn't delete even though subnet deletion process was complete on terraform destroy.
I could delete vpc address prefix by using IBM Cloud CLI.

ibm_is_vpc_address_prefix.my_access_vpc_address_prefix: Destroying... [id=r022-bb73ad82-6b5a-4ef7-bb5d-84ccfaa5b537/r022-647be451-368a-490d-9114-f85af72f30b7]
ibm_is_subnet.my_access_vpc_subnet: Destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223]
ibm_is_security_group_rule.my_access_vm_sgrp_rule_icmp: Destroying... [id=r022-da0a7f0e-c51a-4ebc-bf84-f45089df9652.r022-fdb631ed-bbaf-4472-90a3-c2564213ff67]
ibm_is_security_group_rule.my_access_vm_sgrp_rule_tcp: Destroying... [id=r022-da0a7f0e-c51a-4ebc-bf84-f45089df9652.r022-690467f7-6de5-43fd-8944-9929f8c25ee5]
ibm_is_security_group_rule.my_access_vm_sgrp_rule_icmp: Destruction complete after 2s
ibm_is_security_group_rule.my_access_vm_sgrp_rule_tcp: Destruction complete after 2s
ibm_is_security_group.my_access_vm_sgrp: Destroying... [id=r022-da0a7f0e-c51a-4ebc-bf84-f45089df9652]
ibm_is_security_group.my_access_vm_sgrp: Destruction complete after 2s
ibm_is_subnet.my_access_vpc_subnet: Still destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223, 10s elapsed]
ibm_is_subnet.my_access_vpc_subnet: Still destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223, 20s elapsed]
ibm_is_subnet.my_access_vpc_subnet: Destruction complete after 25s
ibm_is_public_gateway.my_access_public_gateway: Destroying... [id=r022-d289b7d1-e5ea-474e-a49e-ee10f15ca05d]
ibm_is_public_gateway.my_access_public_gateway: Still destroying... [id=r022-d289b7d1-e5ea-474e-a49e-ee10f15ca05d, 10s elapsed]
ibm_is_public_gateway.my_access_public_gateway: Destruction complete after 12s
╷
│ Error: Error Deleting VPC Address Prefix (r022-647be451-368a-490d-9114-f85af72f30b7): Cannot delete due to existing subnets
│ {
│     "StatusCode": 409,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store, must-revalidate"
│         ],
│         "Cf-Cache-Status": [
│             "DYNAMIC"
│         ],
│         "Cf-Ray": [
│             "661cfc34cb3a203d-NRT"
│         ],
│         "Cf-Request-Id": [
│             "0ac5fbf4fa0000203dc319c000000001"
│         ],
│         "Content-Length": [
│             "135"
│         ],
│         "Content-Type": [
│             "application/json; charset=utf-8"
│         ],
│         "Date": [
│             "Sat, 19 Jun 2021 13:08:17 GMT"
│         ],
│         "Expect-Ct": [
│             "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
│         ],
│         "Expires": [
│             "-1"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Server": [
│             "cloudflare"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000; includeSubDomains"
│         ],
│         "Vary": [
│             "Accept-Encoding"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Request-Id": [
│             "ab6e1920-724b-4cab-90cf-2cc1403ed27f"
│         ],
│         "X-Xss-Protection": [
│             "1; mode=block"
│         ]
│     },
│     "Result": {
│         "errors": [
│             {
│                 "code": "conflict_field",
│                 "message": "Cannot delete due to existing subnets"
│             }
│         ],
│         "trace": "ab6e1920-724b-4cab-90cf-2cc1403ed27f"
│     },
│     "RawResult": null
│ }
 
### Steps to Reproduce

1. `terraform destroy` on above configuration

**Comment by duelist2021jp** [comment]
I don't know why vpc_address_prefix Destroy process is starting before destroying completion of subnet. 
I think that the following work is correct originally. Please advice for me.

<expected work>
ibm_is_subnet.my_access_vpc_subnet: Destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223]
ibm_is_subnet.my_access_vpc_subnet: Still destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223, 10s elapsed]
ibm_is_subnet.my_access_vpc_subnet: Still destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223, 20s elapsed]
ibm_is_subnet.my_access_vpc_subnet: Destruction complete after 25s
ibm_is_vpc_address_prefix.my_access_vpc_address_prefix: Destroying... [id=r022-bb73ad82-6b5a-4ef7-

<unexpected work>
ibm_is_vpc_address_prefix.my_access_vpc_address_prefix: Destroying... [id=r022-bb73ad82-6b5a-4ef7-
ibm_is_subnet.my_access_vpc_subnet: Destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223]
ibm_is_subnet.my_access_vpc_subnet: Still destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223, 10s elapsed]
ibm_is_subnet.my_access_vpc_subnet: Still destroying... [id=02e7-f89111db-67db-4041-96e3-6275db37c223, 20s elapsed]
ibm_is_subnet.my_access_vpc_subnet: Destruction complete after 25s

**Comment by astha-jain** [comment]
Hi @duelist2021jp  Please state dependency relationship when setting address prefix to manual. We have updated the documents to say the same.  Please create a new issue if problem persist. 

@kavya498 good to close.

**Comment by kavya498** [comment]
Thanks.. 
Closing this issue..
