### ISSUE TITLE
Terraform behaviour does not match that of the UI

### ISSUE THREAD

**Issue by nolantomy** [IBM-Cloud/terraform-provider-ibm#2785]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.23.2

Your version of Terraform is out of date! The latest version
is 1.0.0. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* ibm_is_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Expected Behavior

When removing or adding an additional network interfaces to an `ibm_is_instance` it would add/remove it from the resources without having to replace it with a new instance 

### Actual Behavior

When removing or adding an additional network interfaces to an `ibm_is_instance` it forces the replacement of the entire instance

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The expected behaviour is possible it achieve via the IBMCloud portal

### References

* #0000

**Comment by astha-jain** [comment]
@deepaksibm FYI

**Comment by astha-jain** [comment]
PR is merged and released. Good to close.

**Comment by kavya498** [comment]
Thanks
closing this issue..
