### ISSUE TITLE
Support for vpc fileshare

### ISSUE THREAD

**Issue by soumypau1** [IBM-Cloud/terraform-provider-ibm#2786]
Hi Team, 
VPC file storage is in beta, but we are using it currently. 
Is there a pre release build of the terraform plugin we can use to manage VPC fileshare resources ? 

-Soumyadeep

**Comment by kavya498** [comment]
@soumypau1 , We don't do any pre-release build.

Thanks

**Comment by soumypau1** [comment]
Thanks @kavya498 , 
Is there any way we can manage IBM Cloud VPC Fileshare ? 
![image](https://user-images.githubusercontent.com/11217399/123952807-24412a80-d9c4-11eb-86d5-39be417b7d11.png)

**Comment by soumypau1** [comment]
Hi team, can you pls confirm if VPC fileshare creation is possible via terraform.

**Comment by kavya498** [comment]
I dont this it is still supported via terraform..
@astha-jain , can you please confirm?

**Comment by deepaksibm** [comment]
Hi @kavya498 @soumypau1  File share is available only as beta and not GA yet. so terraform currently does not support it. Once the feature is GAed the provider will support it. 
@astha-jain

**Comment by ujjwal-ibm** [comment]
feature is available, https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_share
