### ISSUE TITLE
Schematics Workspace apply error

### ISSUE THREAD

**Issue by Ref-Architect** [IBM-Cloud/terraform-provider-ibm#2788]
I am seeing inconsistent workspace apply on "us-south.workspace.Account-2314068-bluePrint---us-south-Region.c766c2d0"

Sometimes we see it, sometimes we do not. We don't know why it is but here are the trace ids and errors.
If i hit apply again on the schematics workspace, it goes through without any issue.

It seems like an ibm backend issue as sometimes it works sometimes it works, the server error response is 404, missing those policies.

----------------------------------------------------------------------------------------------------------------------------------------------

 2021/06/24 17:21:06 -----  Terraform INIT  -----
 
 2021/06/24 17:21:06 Starting command: terraform14 init -input=false -lock=false -no-color
 2021/06/24 17:21:06 Starting command: terraform14 init -input=false -lock=false -no-color
 2021/06/24 17:21:07 Terraform init | 
 2021/06/24 17:21:07 Terraform init | Initializing the backend...
 2021/06/24 17:21:07 Terraform init | 
 2021/06/24 17:21:07 Terraform init | Initializing provider plugins...
 2021/06/24 17:21:07 Terraform init | - Finding ibm-cloud/ibm versions matching "~> 1.23.0"...
 2021/06/24 17:21:08 Terraform init | - Installing ibm-cloud/ibm v1.23.2...
 2021/06/24 17:21:09 Terraform init | - Installed ibm-cloud/ibm v1.23.2 (unauthenticated)
 2021/06/24 17:21:09 Terraform init | 
 2021/06/24 17:21:09 Terraform init | Terraform has created a lock file .terraform.lock.hcl to record the provider
 2021/06/24 17:21:09 Terraform init | selections it made above. Include this file in your version control repository
 2021/06/24 17:21:09 Terraform init | so that Terraform can guarantee to make the same selections by default when
 2021/06/24 17:21:09 Terraform init | you run "terraform init" in the future.
 2021/06/24 17:21:09 Terraform init | 
 2021/06/24 17:21:09 Terraform init | Terraform has been successfully initialized!
 2021/06/24 17:21:09 Command finished successfully.

 2021/06/24 17:23:51 Terraform apply | Error: Error retrieving access group policy: Request failed with status code: 404, ServerErrorResponse: {"trace":"f944a966d3344989b7170cceb7b94188","errors":[{"code":"policy_not_found","message":"Policy with Id 34de1650-69d5-4bfd-bbf8-ee12005e274d not found."}],"status_code":404}
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply |   on group-organization-admins.tf line 16, in resource "ibm_iam_access_group_policy" "cloud-organization-admins-org_admin":
 2021/06/24 17:23:51 Terraform apply |   16: resource "ibm_iam_access_group_policy" "cloud-organization-admins-org_admin" {
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply | Error: Error retrieving access group policy: Request failed with status code: 404, ServerErrorResponse: {"trace":"9a03513f08334f8abea05a168b35beba","errors":[{"code":"policy_not_found","message":"Policy with Id cc35eb13-2fdd-4ac6-bdba-5f7eab252f5e not found."}],"status_code":404}
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply |   on group-security-admins.tf line 32, in resource "ibm_iam_access_group_policy" "cloud-security-admins-groups":
 2021/06/24 17:23:51 Terraform apply |   32: resource "ibm_iam_access_group_policy" "cloud-security-admins-groups" {
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply | Error: Error retrieving access group policy: Request failed with status code: 404, ServerErrorResponse: {"trace":"1e1ab641916045dc9d00d087601d6301","errors":[{"code":"policy_not_found","message":"Policy with Id 12c7a539-841a-45da-9706-31a1f913bd47 not found."}],"status_code":404}
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply |   on group-security-admins.tf line 112, in resource "ibm_iam_access_group_policy" "security_policy_5":
 2021/06/24 17:23:51 Terraform apply |  112: resource "ibm_iam_access_group_policy" "security_policy_5" {
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform apply | 
 2021/06/24 17:23:51 Terraform APPLY error: Terraform APPLY errorexit status 1
 2021/06/24 17:23:51 Could not execute action

**Comment by Ref-Architect** [comment]
Same behavior seen in the latest version
 2021/06/27 01:04:34 -----  Terraform INIT  -----
 
 2021/06/27 01:04:34 Starting command: terraform14 init -input=false -lock=false -no-color
 2021/06/27 01:04:34 Starting command: terraform14 init -input=false -lock=false -no-color
 2021/06/27 01:04:34 Terraform init | 
 2021/06/27 01:04:34 Terraform init | Initializing the backend...
 2021/06/27 01:04:34 Terraform init | 
 2021/06/27 01:04:34 Terraform init | Initializing provider plugins...
 2021/06/27 01:04:34 Terraform init | - Finding latest version of ibm-cloud/ibm...
 2021/06/27 01:04:35 Terraform init | - Installing ibm-cloud/ibm v1.27.0...
 2021/06/27 01:04:39 Terraform init | - Installed ibm-cloud/ibm v1.27.0 (self-signed, key ID AAD3B791C49CC253)
 2021/06/27 01:04:39 Terraform init | 
 2021/06/27 01:04:39 Terraform init | Partner and community providers are signed by their developers.
 2021/06/27 01:04:39 Terraform init | If you'd like to know more about provider signing, you can read about it here:
 2021/06/27 01:04:39 Terraform init | https://www.terraform.io/docs/cli/plugins/signing.html
 2021/06/27 01:04:39 Terraform init | 
 2021/06/27 01:04:39 Terraform init | Terraform has created a lock file .terraform.lock.hcl to record the provider
 2021/06/27 01:04:39 Terraform init | selections it made above. Include this file in your version control repository
 2021/06/27 01:04:39 Terraform init | so that Terraform can guarantee to make the same selections by default when
 2021/06/27 01:04:39 Terraform init | you run "terraform init" in the future.
 2021/06/27 01:04:39 Terraform init | 
 2021/06/27 01:04:39 Terraform init | Terraform has been successfully initialized!
 2021/06/27 01:04:39 Command finished successfully.

**Comment by kavya498** [comment]
Available in latest [1.27.1](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.27.1)

**Comment by kavya498** [comment]
Closing this issue..

Thanks
