### ISSUE TITLE
Container cluster creation runs into timeout.

### ISSUE THREAD

**Issue by kugelr** [IBM-Cloud/terraform-provider-ibm#279]
Hi,

I am not certain if this is a Terraform issue or an IBM Cloud issue. Maybe you can have a look into this.

When we create our cluster it usually takes about 20 to 25 mins. But every once in a while it takes over two hours and Terraform runs into a timeout. I am aware of the "wait_time_minutes: "" => "90". However, I think that >90mins is way to long for a three-node-cluster to provision. If this is not Terraform Provider issue, where could I file a appropriate ticket?

Thanks
René

### Terraform Version
0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_cluster

### Terraform Configuration Files
resource "ibm_container_cluster" "staging" {
name = "${var.kubernetes_cluster_name}"
datacenter = "fra02"
machine_type = "u2c.2x4"
isolation = "public"
public_vlan_id = "${var.public_non_prod_vlan_id}"
private_vlan_id = "${var.private_non_prod_vlan_id}"
subnet_id = ["${ibm_subnet.private_staging_subnet.id}", "${ibm_subnet.public_staging_subnet.id}"]
workers = [{
name = "worker1"
action = "add"
},
{
name = "worker2"
action = "add"
},
{
name = "worker3"
action = "add"
},
]
account_guid = "${var.ibm_bmx_account_guid}"
}

### Debug Output
https://gist.github.com/kugelr/53ef77d1da321177ced9ae21dc84b433

### Expected Behavior
Cluster should be created within ~25 mins.

### Actual Behavior
Cluster creation takes up to ~2h and runs into timeout

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This does not happen every time. Maybe 1 times out of 10.

**Comment by Praveengostu** [comment]
@kugelr The default time out for the terraform container cluster resource is 90m  and it waits for the cluster and workers to be normal also the ingress hostname and secrets to be assigned. We will take this issue with the API team and update you.

**Comment by Praveengostu** [comment]
@kugler We have resolve the issue from the API team for the time taken for assigning the ingress hostname and secrets. Could you please try with the latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.2 and close this issue if working as expected.

**Comment by kugelr** [comment]
Hi @Praveengostu 

I tested it with version 0.11.2. The problem is still present for us. Here's the setup

```
# Creation of the cluster
resource "ibm_container_cluster" "staging" {
  name            = "${var.kubernetes_cluster_name}"
  datacenter      = "fra02"
  machine_type    = "b2c.4x16"
  hardware        = "shared"
  public_vlan_id  = "${var.public_non_prod_vlan_id}"
  private_vlan_id = "${var.private_non_prod_vlan_id}"

  subnet_id = ["${var.staging_private_portable_sn}", "${var.staging_public_portable_sn}"]
  no_subnet = true

  default_pool_size = 2

  region = "eu-de"
}
```
This is the last part of the logs:

```
...
11:36:48 ibm_container_cluster.staging: Still creating... (1h29m40s elapsed)
11:36:57 ibm_container_cluster.staging: Still creating... (1h29m50s elapsed)
11:37:07 ibm_container_cluster.staging: Still creating... (1h30m0s elapsed)
11:37:18 ibm_container_cluster.staging: Still creating... (1h30m10s elapsed)
11:37:21 
11:37:21 Error: Error applying plan:
11:37:21 
11:37:21 1 error(s) occurred:
11:37:21 
11:37:21 * ibm_container_cluster.staging: 1 error(s) occurred:
11:37:21 
11:37:21 * ibm_container_cluster.staging: Error waiting for cluster (29d374a7f322424ab198c142b33b6db2) to become ready: timeout while waiting for state to become 'normal' (last state: 'provisioning', timeout: 1h30m0s)
11:37:21 
11:37:21 Terraform does not automatically rollback in the face of errors.
11:37:21 Instead, your Terraform state file has been partially updated with
11:37:21 any resources that successfully completed. Please address the error
11:37:21 above and apply again to incrementally change your infrastructure.
```

**Comment by BhagyashreeK1** [comment]
@kugelr can you please provide one cluster id of a cluster which took long time in getting ingress secret and subdomain to debug further.
Or provide details of in which environment/region this issue occurred so that I can check if there was any issue from ingress perspective in that specific region.

**Comment by arpadkun** [comment]
90 minutes should be plenty for the ingress hostname to get registered with Cloudflare and Letsencrypt. In some cases when either of these providers slow down (or there is a spike in demand) I could see that this behavior would be 'expected', but should happen very rare, hopefully never.

@kugelr As @BhagyashreeK1 a cluster ID would help to see where the process got stuck and see if there is something we can improve.

**Comment by kugelr** [comment]
@BhagyashreeK1 @arpadkun 
The cluster ID from the case above is: 29d374a7f322424ab198c142b33b6db2 However, this cluster does not exist anymore (Is the ID sufficent or do you need the ID of a existing cluster where the problem occured?).

Here are more details on the environment:
Terraform provider version: 0.11.2
Region eu-de
Datacenter: fra02 
Cluster type: Standard
Kubernetes version: 1.10.5_1517
Machine type: b2c.4x16
Availibility: Single Zone
Hardware isolation: Virtusal - Shared
Disk encryption: true
Number of worker nodes: 2
VLAN IDs: Private: 2350213 - Public: 2350207

**Comment by arpadkun** [comment]
Thank you, no we need to see it where it got stuck. If deleted, the machines are gone we cannot recover anything from that.

**Comment by kugelr** [comment]
Okay, I'll try to reproduce it and send you and ID of a existing cluster. However, this might take a while. In my experience the problem occurs one time out of ten.

**Comment by greglanthier** [comment]
After scanning the repo issues more carefully I found https://github.com/IBM-Cloud/terraform-provider-ibm/issues/345 which suggests that setting `no_subnet = true` prevents subnets from being allocated.

Since I provided both a subnet id _and_ the `no_subnet` parameter its possible that these parameters were in conflict.  I'll dig more into the plugin code to confirm this at some point...

**Comment by Praveengostu** [comment]
Hi @greglanthier The cluster first creates with a `no_subnet = true` and then it adds the subnet_id.  This is the comment I received from the ingress team 
```Even after 4 hours since cluster create, the Ingress domain is null. Reason being `"OrderPortableSubnet": "false",`. As there was no subnets provided, the network micro service did not reserve public IP and private IP for the cluster.```

**Comment by hkantare** [comment]
closing the issue..
