### ISSUE TITLE
ibm_container_cluster documentation says space_guid and org_guid are required when they aren't

### ISSUE THREAD

**Issue by jgarcows** [IBM-Cloud/terraform-provider-ibm#280]
The documentation for ibm_contaienr_cluster, https://ibm-cloud.github.io/tf-ibm-docs/v0.9.1/d/container_cluster.html , says that space_guid and org_guid are required fields, but this hasn't been the case since v0.8.0.  https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.8.0

**Comment by Praveengostu** [comment]
Hi @jgarcows you are referring to the datasource cluster link, for datasource cluster we had made them optional in release v.10.0. Help link for cluster resource for version 0.9.1 is https://ibm-cloud.github.io/tf-ibm-docs/v0.9.1/r/container_cluster.html

**Comment by hkantare** [comment]
Closing this we made org_guid and space_guid as optinal
