### ISSUE TITLE
Volume attachment to PVS Instances not working

### ISSUE THREAD

**Issue by Prajyot-Parab** [IBM-Cloud/terraform-provider-ibm#2810]
### Terraform CLI and Terraform IBM Provider Version

```
Terraform v0.13.6
./ibmcloud version 2.0.0+5a84b9b-2021-06-23T17:07:07+00:00
```

### Affected Resource(s)

* ibm_pi_instance

### Terraform Configuration Files

```
resource "ibm_pi_instance" "master" {
  count = var.master["count"]

  pi_memory            = var.master["memory"]
  pi_processors        = var.master["processors"]
  pi_instance_name     = "${var.name_prefix}-master-${count.index}"
  pi_proc_type         = var.processor_type
  pi_image_id          = data.ibm_pi_image.rhcos.id
  pi_sys_type          = var.system_type
  pi_cloud_instance_id = var.service_instance_id
  pi_network_ids       = [data.ibm_pi_network.network.id]
  pi_volume_ids        = local.master.volume_count == 0 ? null : chunklist(ibm_pi_volume.master.*.volume_id, local.master.volume_count)[count.index]

  # Inject ignition source timeout to force ignition fail when HTTP file is not available for 500s. This will reboot the node and try ignition fetch process again.
  pi_user_data = base64encode(replace(data.ignition_config.master[count.index].rendered, "\"timeouts\":{}", "\"timeouts\":{\"httpTotal\":500}"))

  # Not needed by RHCOS but required by resource
  pi_key_pair_name = "${var.name_prefix}-keypair"
  pi_health_status = "WARNING"
}

resource "ibm_pi_volume" "master" {
  count = local.master.volume_count == 0 ? 0 : var.master["count"] * local.master.volume_count

  pi_volume_size       = local.master.volume_size
  pi_volume_name       = "${var.name_prefix}-master-${count.index}-volume"
  pi_volume_type       = data.ibm_pi_image.rhcos.storage_type
  pi_volume_shareable  = var.volume_shareable
  pi_cloud_instance_id = var.service_instance_id
}
```

### Expected Behavior

Volumes should have attached successfully to Instance.

### Actual Behavior

`Error: failed to provision Failed to Create PVM Instance :[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances][400] pcloudPvminstancesPostBadRequest  &{Code:0 Description:bad request: calculated parameter has failed for cloud-instance a007eb5664ab4188a236468c86e51f16: validate volumes failed, all volumes are not in the same VM deployment storage pool Tier3-Flash-1 Error:bad request Message:}`

### Steps to Reproduce

1. Create volumes
2. Try attaching volumes as part of instance creation

**Comment by kavya498** [comment]
@surajsub , Can you please have a look?

**Comment by Prajyot-Parab** [comment]
@kavya498 @surajsub Any updates on this?

**Comment by surajsub** [comment]
@Prajyot-Parab  - this is not supported by power. The way it will work is 
1) you create the vm
2) create the volume, during create volume you pass in two additional params - affinity and the boot volume_id of the lpar
3) perform an attach of the volume.

**Comment by Prajyot-Parab** [comment]
@surajsub 

```
resource "ibm_pi_instance" "bastion" {
  count = local.bastion_count

  pi_memory            = var.bastion["memory"]
  pi_processors        = var.bastion["processors"]
  pi_instance_name     = "${var.name_prefix}-bastion-${count.index}"
  pi_proc_type         = var.processor_type
  pi_image_id          = local.bastion_image_id
  pi_network_ids       = [ibm_pi_network.public_network.network_id, data.ibm_pi_network.network.id]
  pi_key_pair_name     = ibm_pi_key.key.key_id
  pi_sys_type          = var.system_type
  pi_cloud_instance_id = var.service_instance_id
  pi_health_status     = var.bastion_health_status
}

resource "ibm_pi_volume" "volume" {
 
  pi_volume_size       = var.volume_size
  pi_volume_name       = "${var.name_prefix}-${var.storage_type}-volume"
  pi_affinity_policy   = "affinity"
  pi_affinity_instance = ibm_pi_instance.bastion[count.index].pi_instance_name
  pi_volume_shareable  = var.volume_shareable
  pi_cloud_instance_id = var.service_instance_id
}
```

1. VM gets created (**ibm_pi_instance**)
2. Volume gets created (**ibm_pi_volume**)
3. Attach ? --> can you please point me to resource you are referring to at this stage

Also do let me know if my flow is correct or it needs some tweaks

**Comment by surajsub** [comment]
ibm_pi_volume_attach

**Comment by Prajyot-Parab** [comment]
@surajsub Thanks for your pointer, it did fix a part of my problem.

I do have instances (RHCOS Nodes) which when provisioned will have `health_status` as "Warning" and I would still want to attach volume to them. (My nodes will be in active state at a later stage once I pass them ignition, I want to attach before that if possible)

Right now I am getting issue -

```
Error: Failed to Attach PI Instance Volume rdr-praj-6305-sao01-worker-0 :[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-inst
ances/{pvm_instance_id}/volumes/{volume_id}][409] pcloudPvminstancesVolumesPostConflict  &{Code:0 Description:conflict: unable to atta
ch volume e29fb419-4b47-4179-b014-38d86881fa1e to pvm-instance rdr-praj-6305-sao01-worker-0 (health=WARNING), while pvm-instnace healt
h is not 'OK' Error:conflict Message:}
```

**Comment by surajsub** [comment]
If the lpar is in the warning state , you cannot attach or perform any operation on them. Power Cloud is working on a fix. I can ask them for an ETA

**Comment by Prajyot-Parab** [comment]
> If the lpar is in the warning state , you cannot attach or perform any operation on them. Power Cloud is working on a fix. I can ask them for an ETA

@surajsub sure that would be great, Thanks!

**Comment by surajsub** [comment]
October..

**Comment by Prajyot-Parab** [comment]
> October..

@surajsub Thanks for the update.

QQ - Is there a way to avoid following error while deleting tf resources (A instance with volume attached to it)

`Error: Failed to Delete PI Instance Volume c7d4b5f8-f0bc-472a-9666-28420a390da1 :[DELETE /pcloud/v1/cloud-instances/{cloud_instance_id}/volumes/{volume_id}][500] pcloudCloudinstancesVolumesDeleteInternalServerError  &{Code:0 Description:an error has occurred; please try again: Unable to delete Volume c7d4b5f8-f0bc-472a-9666-28420a390da1: Bad request with: [DELETE https://192.168.8.136:9000/v3/a007eb5664ab4188a236468c86e51f16/volumes/c7d4b5f8-f0bc-472a-9666-28420a390da1], error message: {"badRequest": {"message": "Invalid volume: Volume c7d4b5f8-f0bc-472a-9666-28420a390da1 is in detaching status, it must be available or error or error_restoring or error_extending or error_managing or error_deleting and must not be migrating, attached, belong to a group", "code": 400}} Error:internal server error Message:}
`

**Comment by surajsub** [comment]
Hmm - this seems like a timing issue.. let me investigate further and get back to you ..if you do a delete again it will clean up .. but let me check on this locally and i can provide a fix.

**Comment by Prajyot-Parab** [comment]
> Hmm - this seems like a timing issue.. let me investigate further and get back to you ..if you do a delete again it will clean up .. but let me check on this locally and i can provide a fix.

Yes deleting again fixes it, but we expect it to work during the first attempt itself (I guess this happens as volume takes time to detach before it could be deleted)

**Comment by Prajyot-Parab** [comment]
> > Hmm - this seems like a timing issue.. let me investigate further and get back to you ..if you do a delete again it will clean up .. but let me check on this locally and i can provide a fix.
> 
> Yes deleting again fixes it, but we expect it to work during the first attempt itself (I guess this happens as volume takes time to detach before it could be deleted)

@surajsub any luck with possible workaround?

**Comment by surajsub** [comment]
I have the code in my repo - you want to try to do a build and test it  ?

**Comment by Prajyot-Parab** [comment]
> I have the code in my repo - you want to try to do a build and test it ?

@surajsub Yes please share the link, I will test it out.

**Comment by Prajyot-Parab** [comment]
@surajsub Is the fix part of latest release?

> > I have the code in my repo - you want to try to do a build and test it ?
> 
> @surajsub Yes please share the link, I will test it out.

@surajsub Is the fix part of latest release?

**Comment by yussufsh** [comment]
Voliume attachment resource is working now fixed with https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3467
