### ISSUE TITLE
Need to configure security groups for already available load balancers through terraform script!

### ISSUE THREAD

**Issue by siddhinaik** [IBM-Cloud/terraform-provider-ibm#2813]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
 ===================================================================

Requirement : I have a load balancer already created, I want to attach security groups to it. 
Solution tried : Using resource ibm_is_lb. Tried below script to add security_group to it.

resource "ibm_is_lb" "lb" {
    name    = "lb-XXXX" 
    subnets = ["xxxx-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"] 
    security_groups = ["test-security-020721"]  
}

Output : It tries to create new load balancer.  Output of terraform plan being : 
Plan: 1 to add, 0 to change, 0 to destroy.
(terraform version used : v1.0.1 and ibm : v1.27.1 )
 

Is there any way to add security group to already existing load balancer via terraform script.
Or am I missing anything in the script ?

**Comment by kroc353** [comment]
I’ve used the ibm_is_security_group_target resource to attach existing security groups to existing load balancer…

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_security_group_target

**Comment by kavya498** [comment]
@siddhinaik ,
Can we close this issue?

**Comment by siddhinaik** [comment]
Thanks
