### ISSUE TITLE
support for ibmcloud is instance-reboot, start, stop

### ISSUE THREAD

**Issue by joergrenn** [IBM-Cloud/terraform-provider-ibm#2814]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I am looking for a way to reboot VSI instances via ansible.
Since the ansible modules wrap the IBM Cloud Terraform provider I am opening this request here.
As far as I can tell the cli commands "ibmcloud is instance-reboot" as well as instance-start, instance-stop are not yet supported. 
Would be great if this could be implemented.

**Comment by astha-jain** [comment]
@kavya498 good to close
