### ISSUE TITLE
Feature request: Support for multi zone k8s clusters

### ISSUE THREAD

**Issue by ruben-burr** [IBM-Cloud/terraform-provider-ibm#282]
Hi there,

as multi zone clusters were announced for the Kubernetes offering, we would like to use it in our project. As we set our clusters up with terraform, it would be necessary that this is supported by the terraform provider.

Affected resource: https://ibm-cloud.github.io/tf-ibm-docs/v0.9.1/r/container_cluster.html

https://www.ibm.com/blogs/bluemix/2018/06/improving-app-availability-multizone-clusters/

Greets, Ruben

**Comment by Praveengostu** [comment]
@ruben-burr We are looking in to this..

**Comment by Praveengostu** [comment]
@ruben-burr Here is the latest release with support to worker pools and zones
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.0

**Comment by Praveengostu** [comment]
@ruben-burr We have enhanced the cluster resource to support both the standalone worker and multi AZ support with release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.2. Could you check and close this issue if working as expected.

**Comment by bennythejudge** [comment]
@Praveengostu do you have a working example of Terraform code to create a multizone cluster? Thx.

**Comment by Praveengostu** [comment]
@bennythejudge Could you please check example at https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-cluster/cluster-worker-pool-zone

**Comment by kskewes** [comment]
Hi @Praveengostu , can we please clarify this in the docs?
`default_pool_size - (Optional,int) The number of workers created under the default worker pool which support Multi-AZ.`

This would suggest that we don't have to create custom pools for each zone. If so, can you please provide a simple example with minimal configuration.

Separately, I would like to still add zone label to each node though so can differentiate for node affinities so may need to use custom pools anyway.

**Comment by priyadarshi035** [comment]
@kskewes Were you able to create Multi-Zone Cluster using terraform

**Comment by kskewes** [comment]
I haven't tried recently. 
I had an existing vlan in one of the AZ's and that would prevent provisioning due to optional/required conflicts. There was a patch to fix this merged but I haven't tried since. 

I ended up finding a workaround process with ibmcloud cli. The IBM cloud portal doesn't work.

At some point will try again with next cluster and have another go at importing existing into Terraform state.

**Comment by hkantare** [comment]
closing the issue..The support for multi-zone is provided in provider..
Examples can be refereed here : https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-cluster
