### ISSUE TITLE
ibm secrets manager rate limitting breaks plans

### ISSUE THREAD

**Issue by sdague** [IBM-Cloud/terraform-provider-ibm#2820]
The IBM Secrets Manager service currently limits API calls to 10/s. That means if you are loading a large number of secrets from secrets manager using `data "ibm_secrets_manager_secret"` it is possible to hit the rate limit.

Currently the provider has no retry logic to wait some time and reload. 

# Solution

Add retry logic with time delay for API rate limit error codes on this resource.

**Comment by kavya498** [comment]
@sdague .
Can you please share the error logs

Thanks

**Comment by IdanAdar** [comment]
Secrets Manager no longer imposes a rate limit.
