### ISSUE TITLE
Intermittent "Error downloading the cluster config" errors in data.ibm_container_cluster_config - "You must specify an IAM token as an Authorization header"

### ISSUE THREAD

**Issue by vburckhardt** [IBM-Cloud/terraform-provider-ibm#2826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
terraform -v
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/ibm-cloud/ibm v1.27.1
```

### Affected Resource(s)

data.ibm_container_cluster_config

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "ibm_container_cluster_config" "cluster_config" {
  cluster_name_id = var.cluster_id
}

##############################################################################
# Config providers
##############################################################################

provider "ibm" {
  ibmcloud_api_key = var.ibmcloud_api_key
}

provider "helm" {
  kubernetes {
    host                   = data.ibm_container_cluster_config.cluster_config.host
    token                  = data.ibm_container_cluster_config.cluster_config.token
    cluster_ca_certificate = data.ibm_container_cluster_config.cluster_config.ca_certificate
  }
}
```

### Debug Output

Debug output posted at: https://gist.github.com/vburckhardt/ccc18b10119f4b86a0b03c76b289cc9d

### Expected Behavior

No error!

### Actual Behavior

Getting this error intermittently - generally a few retries (terraform apply / destroy) gets past this issue.

╷
│ Error: Error downloading the cluster config [c3gj1v5s005sa12n1sm0]: Request failed with status code: 401, ServerErrorResponse: {"incidentID":"0bcf7af3-13f0-4d5d-924b-1906261f253a","code":"G0001","description":"You must specify an IAM token as an Authorization header.","type":"Authentication","recoveryCLI":"To retrieve your IAM token, run 'ibmcloud login' and then 'ibmcloud iam oauth-tokens'."}
│ 
│   with data.ibm_container_cluster_config.cluster_config,
│   on main.tf line 14, in data "ibm_container_cluster_config" "cluster_config":
│   14: data "ibm_container_cluster_config" "cluster_config" {
│ 
╵

### Steps to Reproduce

1. `terraform apply / destory`

### Important Factoids

A ServiceID API Key was used in this scenario. On top of my head, I do not think I have seen this category of errors with personal IBM Cloud API Key.

The ServiceId has got the cluster-admin role on the cluster.

### References

* #0000

**Comment by vburckhardt** [comment]
PR for the authentication issue at https://github.com/IBM-Cloud/bluemix-go/pull/318

**Comment by hkantare** [comment]
closing the issue...above PR has been merged ...
