### ISSUE TITLE
ibm_satellite_cluster resource - kube_version upgrade,  provider never returns 

### ISSUE THREAD

**Issue by david-shepard** [IBM-Cloud/terraform-provider-ibm#2827]
Hi, it appears that when you change the `kube_version` [argument](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/satellite_cluster#kube_version), the provider hangs indefinitely (ie. `Still creating...` until it reaches the timeout). 

This is due to the fact that the workers don't seem "phoning home" properly so the provider never gets any resolution on whether the upgrade failed or succeeded.

**Comment by anilkumarnagaraj** [comment]
@david-shepard 

We are not able to reproduce the issue. we are able to successfully update the kube version without any hung issue.
This could be an intermittent issue. Are you seeing this hung issue repeatedly?

I agree that during kube version update, "phoning home" is not happening properly. 
Provider returns before the completion of worker nodes version update. we are working on the fix.

**Comment by david-shepard** [comment]
Thanks for the fix!
