### ISSUE TITLE
Get the list of all load balancers based on region

### ISSUE THREAD

**Issue by siddhinaik** [IBM-Cloud/terraform-provider-ibm#2838]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I want to get the list of all load balancers based on region.Tried using : 
data "ibm_is_lbs" "test_lbs" {  
    
}
this returns the only which was created by my username.

It doesnot accept any argument to state the region

**Comment by astha-jain** [comment]
When you instantiate the provider block, you set the region.
Secondly, datasource for  "ibm_is_lbs" would fetch all the lbs in the account associated with the API key you used to instantiate the provider.

**Comment by kavya498** [comment]
@siddhinaik ,
Can we close this issue?

**Comment by siddhinaik** [comment]
Thanks
