### ISSUE TITLE
terraform apply issue occurs when selecting a specific location

### ISSUE THREAD

**Issue by Najeongho** [IBM-Cloud/terraform-provider-ibm#284]
Hi there,

Please check this problem.

### Terraform Version

$ terraform -v
Terraform v0.11.7
+ provider.ibm (unversioned)

### Affected Resource(s)
- ibm_container_cluster

### Terraform Configuration Files
```hcl

resource "ibm_container_cluster" "iccs_test" {
  name            = "iccs_test"
  datacenter      = "seo01"
  kube_version    = "1.9.7_1510"
  machine_type    = "u2c.2x4"
  isolation       = "public"
  public_vlan_id  = 2251207
  private_vlan_id = 2251209
  billing         = "hourly"

  workers = [{
    name = "worker1"
    action = "add"
    version = "1.9.7_1513"
  }]

  account_guid = "<My account_guid>"
}

output "id" {
  value = "${ibm_container_cluster.iccs_test.id}"
}

output "name" {
  value = "${ibm_container_cluster.iccs_test.name}"
}

output "server_url" {
  value = "${ibm_container_cluster.iccs_test.server_url}"
}

output "workers_info" {
  value = "${ibm_container_cluster.iccs_test.workers_info}"
}

output "workers_id" {
  value = "${ibm_container_cluster.iccs_test.workers.id}"
}

```

### Debug Output

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.iccs_test: 1 error(s) occurred:

* ibm_container_cluster.iccs_test: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"ac5513ae-919d-45be-960a-00f1230fdd0d","code":"E0055","description":"The specified location is invalid.","type":"Provisioning","recoveryCLI":"To list available locations, run 'bx cs locations'."}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Panic Output

The crash.log has not been created.

### Expected Behavior
What should have happened?

Occur terraform apply error.

### Actual Behavior
What actually happened?

1 error(s) occurred:

* ibm_container_cluster.iccs_test: 1 error(s) occurred:

* ibm_container_cluster.iccs_test: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"ac5513ae-919d-45be-960a-00f1230fdd0d","code":"E0055","description":"The specified location is invalid.","type":"Provisioning","recoveryCLI":"To list available locations, run 'bx cs locations'."}

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. Input `yes`

### Important Factoids

I ran my MAC PC. 
Mac OS version is 10.13.4.

I ran terraform-provider-ibm file. 
terraform-provider-ibm binary file version is 0.10.0
(IBM Cloud Provider v0.10.0)

No run on VM.
No apply Firewall and ACLs.

### References

Nothing.

**Comment by Praveengostu** [comment]
datacenter      = "seo01" belongs to which region? 
By default the provider region is set to us-south. You can override the default region by using the region argument in the provider or you can export the BM_REGION to appropriate region. Please look for the region argument https://ibm-cloud.github.io/tf-ibm-docs/v0.9.1/r/container_cluster.html

**Comment by Najeongho** [comment]
Hi Praveengostu


Datacenter "seo01" is Seoul datacenter in South Korea.

"seo01" is included in the "ap-north" region.


* This is the result of using "ibmcloud cli".

$ ibmcloud cs regions
Region Name   Region Alias
ap-north      jp-tok
ap-south      au-syd
eu-central    eu-de
uk-south      eu-gb
us-east       us-east
us-south      us-south

$ ibmcloud cs region

Region:   ap-north

$ ibmcloud cs locations
OK
Location
tok02
hkg02
seo01
sng01


Please check using "seo01".

**Comment by Praveengostu** [comment]
Could you please update your terraform configuration file with below and let me know if you still see's the issue

```
provider "ibm" {
  region = "ap-north"
}
```

**Comment by Najeongho** [comment]
I added "region = 'ap-north'" content as shown below. However, the error still occurs.

* Terraform content

provider "ibm" {
    region = "ap-north"
    softlayer_api_key = "(My API Key)"
    softlayer_username = "(My username)"
    bluemix_api_key    = "(My BX Key)"
}


resource "ibm_container_cluster" "iccs_test" {
  name            = "iccs_test"
  datacenter      = "seo01"
  kube_version    = "1.9.7_1510"
  machine_type    = "u2c.2x4"
  isolation       = "public"
  public_vlan_id  = 2251207
  private_vlan_id = 2251209
  billing         = "hourly"

  workers = [{
    name = "worker1"
    action = "add"
    version = "1.9.7_1513"
  }]

  account_guid = "(My account guid)"
}

output "id" {
  value = "${ibm_container_cluster.iccs_test.id}"
}

output "name" {
  value = "${ibm_container_cluster.iccs_test.name}"
}

output "server_url" {
  value = "${ibm_container_cluster.iccs_test.server_url}"
}

output "workers_info" {
  value = "${ibm_container_cluster.iccs_test.workers_info}"
}

output "workers_id" {
  value = "${ibm_container_cluster.iccs_test.workers.id}"
}


* Run command
$ terraform apply


* Error log

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.iccs_test: 1 error(s) occurred:

* ibm_container_cluster.iccs_test: Error occured while configuring Container Service for K8s cluster: "ServiceEndpointDoesnotExist: IAM  endpoint doesn't exist for region: \"ap-north\""

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by Praveengostu** [comment]
This was different from the original one. Here it says the IAM end point doesn't exist for region: "ap-north"".  Are you able to create the cluster in the same region and datacenter using ibmcloud cli?

**Comment by Najeongho** [comment]
I selected a same datacenter in the same region in ibmcloud cli, the same result is displayed.


jeonghonaui-MacBook-Pro:terraform jeongho.na$ ibmcloud login
API 엔드포인트: https://api.au-syd.bluemix.net

Email> jeongho.na@sk.com

Password> 
인증 중...
확인

계정 선택:
1.  (My account guid 1) <-> (My account number 1)
2.  (My account guid 2) <-> (My account number 2)
번호 입력> 1
대상 지정된 계정  (My account guid 1) <-> (My account number 1)

대상 지정된 리소스 그룹 Default

                        
API 엔드포인트:      https://api.au-syd.bluemix.net   
지역:                au-syd   
사용자:              jeongho.na@sk.com   
계정:                 (My account guid 1) <-> (My account number 1) 
리소스 그룹:         Default   
CF API 엔드포인트:      
조직:                   
영역:                   

팁: Cloud Foundry 애플리케이션 및 서비스를 관리하는 경우
- 'ibmcloud target --cf'을(를) 사용하여 대화식으로 Cloud Foundry 조직/영역을 대상으로 지정하거나 'ibmcloud target --cf-api ENDPOINT -o ORG -s SPACE'을(를) 사용하여 조직/영역을 대상으로 지정하십시오.
- 현재 IBM Cloud CLI 컨텍스트를 사용하여 Cloud Foundry CLI를 실행하려면 'ibmcloud cf'을(를) 사용하십시오.

jeonghonaui-MacBook-Pro:terraform jeongho.na$ ibmcloud regions
지역 나열 중...

이름       표시 이름   CF API 엔드포인트                 고객   배치       유형   
au-syd     시드니      https://api.au-syd.bluemix.net    IBM    프로덕션   public   
eu-de      독일        https://api.eu-de.bluemix.net     IBM    프로덕션   public   
eu-gb      영국        https://api.eu-gb.bluemix.net     IBM    프로덕션   public   
us-east    미국 동부   https://api.us-east.bluemix.net   IBM    프로덕션   public   
us-south   미국 남부   https://api.ng.bluemix.net        IBM    프로덕션   public   
jeonghonaui-MacBook-Pro:terraform jeongho.na$ ibmcloud cs region-set
If you have clusters that run Kubernetes version 1.5 or 1.7, update them now to continue receiving important security updates and support. Kubernetes version 1.7 is deprecated and will be unsupported 21 June 2018. Version 1.5 is already unsupported. Learn more at <https://ibm.biz/BdZ3ut>

Choose a region:
1. ap-north
2. ap-south
3. eu-central
4. uk-south
5. us-east
6. us-south
Enter a number> 1
OK
jeonghonaui-MacBook-Pro:terraform jeongho.na$ ibmcloud cs region
             
Region:   ap-north   
jeonghonaui-MacBook-Pro:terraform jeongho.na$ ibmcloud cs locations
OK
Location   
tok02   
hkg02   
seo01   
sng01   
jeonghonaui-MacBook-Pro:terraform jeongho.na$ terraform init

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
jeonghonaui-MacBook-Pro:terraform jeongho.na$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + ibm_container_cluster.iccs_test
      id:                <computed>
      account_guid:      "e6734a6994f7c1c0d454a623e2135760"
      billing:           "hourly"
      datacenter:        "seo01"
      disk_encryption:   "true"
      ingress_hostname:  <computed>
      ingress_secret:    <computed>
      isolation:         "public"
      kube_version:      "1.9.7_1510"
      machine_type:      "u2c.2x4"
      name:              "iccs_test"
      no_subnet:         "false"
      private_vlan_id:   "2251209"
      public_vlan_id:    "2251207"
      server_url:        <computed>
      wait_time_minutes: "90"
      worker_num:        <computed>
      workers.#:         "1"
      workers.0.action:  "add"
      workers.0.id:      <computed>
      workers.0.name:    "worker1"
      workers.0.version: "1.9.7_1513"
      workers_info.#:    <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_container_cluster.iccs_test: Creating...
  account_guid:      "" => "e6734a6994f7c1c0d454a623e2135760"
  billing:           "" => "hourly"
  datacenter:        "" => "seo01"
  disk_encryption:   "" => "true"
  ingress_hostname:  "" => "<computed>"
  ingress_secret:    "<sensitive>" => "<sensitive>"
  isolation:         "" => "public"
  kube_version:      "" => "1.9.7_1510"
  machine_type:      "" => "u2c.2x4"
  name:              "" => "iccs_test"
  no_subnet:         "" => "false"
  private_vlan_id:   "" => "2251209"
  public_vlan_id:    "" => "2251207"
  server_url:        "" => "<computed>"
  wait_time_minutes: "" => "90"
  worker_num:        "" => "<computed>"
  workers.#:         "" => "1"
  workers.0.action:  "" => "add"
  workers.0.id:      "" => "<computed>"
  workers.0.name:    "" => "worker1"
  workers.0.version: "" => "1.9.7_1513"
  workers_info.#:    "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.iccs_test: 1 error(s) occurred:

* ibm_container_cluster.iccs_test: Error occured while configuring Container Service for K8s cluster: "ServiceEndpointDoesnotExist: IAM  endpoint doesn't exist for region: \"ap-north\""

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


jeonghonaui-MacBook-Pro:terraform jeongho.na$

**Comment by Praveengostu** [comment]
Thanks for confirming. So we do not have a IAM end point in the region "ap-north". Could you please try creating a cluster in a different region.

**Comment by Najeongho** [comment]
Did you plan to make another IAM end point the region "ap-north"?

We need IAM end point in the region "ap-north".

**Comment by Najeongho** [comment]
@Praveengostu 

I have changed this region to the ap-south.
So I have changed this location to the syd01.

## But it still is not run.


jeonghonaui-MacBook-Pro:test jeongho.na$ ibmcloud cs region-set
Choose a region:
1. ap-north
2. ap-south
3. eu-central
4. uk-south
5. us-east
6. us-south
Enter a number> 2
OK
jeonghonaui-MacBook-Pro:test jeongho.na$ ibmcloud cs region
             
Region:   ap-south   
jeonghonaui-MacBook-Pro:test jeongho.na$ ibmcloud cs locations
OK
Location   
syd04   
syd01   
mel01   
jeonghonaui-MacBook-Pro:test jeongho.na$ cat iccs.tf 

provider "ibm" {
    region = "ap-south"
    softlayer_api_key = "1570767_jeongho.na@sk.com"
    softlayer_username = "0d7ece6df906ec71ac8d44414861b8915b0a0953d6e40c878f386b5316568f26"
    bluemix_api_key    = "rwa-gWtacCsEy-NO-KMSyJnv92cre14xW1NlNu1TJCp-"
}


resource "ibm_container_cluster" "iccs_test_syd" {
  name            = "iccs_test_syd"
  datacenter      = "syd01"
  kube_version    = "1.9.7_1510"
  machine_type    = "u2c.2x4"
  isolation       = "public"
  public_vlan_id  = 2251207
  private_vlan_id = 2251209
  billing         = "hourly"

  workers = [{
    name = "worker1"
    action = "add"
    version = "1.9.7_1513"
  }]

  account_guid = "e6734a6994f7c1c0d454a623e2135760"
}

output "id" {
  value = "${ibm_container_cluster.iccs_test_syd.id}"
}

output "name" {
  value = "${ibm_container_cluster.iccs_test_syd.name}"
}

output "server_url" {
  value = "${ibm_container_cluster.iccs_test_syd.server_url}"
}

output "workers_info" {
  value = "${ibm_container_cluster.iccs_test_syd.workers_info}"
}

output "workers_id" {
  value = "${ibm_container_cluster.iccs_test_syd.workers.id}"
}
jeonghonaui-MacBook-Pro:test jeongho.na$ terraform init

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
jeonghonaui-MacBook-Pro:test jeongho.na$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + ibm_container_cluster.iccs_test_syd
      id:                <computed>
      account_guid:      "e6734a6994f7c1c0d454a623e2135760"
      billing:           "hourly"
      datacenter:        "syd01"
      disk_encryption:   "true"
      ingress_hostname:  <computed>
      ingress_secret:    <computed>
      isolation:         "public"
      kube_version:      "1.9.7_1510"
      machine_type:      "u2c.2x4"
      name:              "iccs_test_syd"
      no_subnet:         "false"
      private_vlan_id:   "2251209"
      public_vlan_id:    "2251207"
      server_url:        <computed>
      wait_time_minutes: "90"
      worker_num:        <computed>
      workers.#:         "1"
      workers.0.action:  "add"
      workers.0.id:      <computed>
      workers.0.name:    "worker1"
      workers.0.version: "1.9.7_1513"
      workers_info.#:    <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_container_cluster.iccs_test_syd: Creating...
  account_guid:      "" => "e6734a6994f7c1c0d454a623e2135760"
  billing:           "" => "hourly"
  datacenter:        "" => "syd01"
  disk_encryption:   "" => "true"
  ingress_hostname:  "" => "<computed>"
  ingress_secret:    "<sensitive>" => "<sensitive>"
  isolation:         "" => "public"
  kube_version:      "" => "1.9.7_1510"
  machine_type:      "" => "u2c.2x4"
  name:              "" => "iccs_test_syd"
  no_subnet:         "" => "false"
  private_vlan_id:   "" => "2251209"
  public_vlan_id:    "" => "2251207"
  server_url:        "" => "<computed>"
  wait_time_minutes: "" => "90"
  worker_num:        "" => "<computed>"
  workers.#:         "" => "1"
  workers.0.action:  "" => "add"
  workers.0.id:      "" => "<computed>"
  workers.0.name:    "" => "worker1"
  workers.0.version: "" => "1.9.7_1513"
  workers_info.#:    "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.iccs_test_syd: 1 error(s) occurred:

* ibm_container_cluster.iccs_test_syd: Error occured while configuring Container Service for K8s cluster: "ServiceEndpointDoesnotExist: IAM  endpoint doesn't exist for region: \"ap-south\""

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


## I removed the "region" part of provider "ibm" and ran it again.

jeonghonaui-MacBook-Pro:test jeongho.na$ cat iccs.tf 

provider "ibm" {
    softlayer_api_key = "1570767_jeongho.na@sk.com"
    softlayer_username = "0d7ece6df906ec71ac8d44414861b8915b0a0953d6e40c878f386b5316568f26"
    bluemix_api_key    = "rwa-gWtacCsEy-NO-KMSyJnv92cre14xW1NlNu1TJCp-"
}


resource "ibm_container_cluster" "iccs_test_syd" {
  name            = "iccs_test_syd"
  datacenter      = "syd01"
  kube_version    = "1.9.7_1510"
  machine_type    = "u2c.2x4"
  isolation       = "public"
  public_vlan_id  = 2251207
  private_vlan_id = 2251209
  billing         = "hourly"

  workers = [{
    name = "worker1"
    action = "add"
    version = "1.9.7_1513"
  }]

  account_guid = "e6734a6994f7c1c0d454a623e2135760"
}

output "id" {
  value = "${ibm_container_cluster.iccs_test_syd.id}"
}

output "name" {
  value = "${ibm_container_cluster.iccs_test_syd.name}"
}

output "server_url" {
  value = "${ibm_container_cluster.iccs_test_syd.server_url}"
}

output "workers_info" {
  value = "${ibm_container_cluster.iccs_test_syd.workers_info}"
}

output "workers_id" {
  value = "${ibm_container_cluster.iccs_test_syd.workers.id}"
}
jeonghonaui-MacBook-Pro:test jeongho.na$ terraform init

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
jeonghonaui-MacBook-Pro:test jeongho.na$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + ibm_container_cluster.iccs_test_syd
      id:                <computed>
      account_guid:      "e6734a6994f7c1c0d454a623e2135760"
      billing:           "hourly"
      datacenter:        "syd01"
      disk_encryption:   "true"
      ingress_hostname:  <computed>
      ingress_secret:    <computed>
      isolation:         "public"
      kube_version:      "1.9.7_1510"
      machine_type:      "u2c.2x4"
      name:              "iccs_test_syd"
      no_subnet:         "false"
      private_vlan_id:   "2251209"
      public_vlan_id:    "2251207"
      server_url:        <computed>
      wait_time_minutes: "90"
      worker_num:        <computed>
      workers.#:         "1"
      workers.0.action:  "add"
      workers.0.id:      <computed>
      workers.0.name:    "worker1"
      workers.0.version: "1.9.7_1513"
      workers_info.#:    <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_container_cluster.iccs_test_syd: Creating...
  account_guid:      "" => "e6734a6994f7c1c0d454a623e2135760"
  billing:           "" => "hourly"
  datacenter:        "" => "syd01"
  disk_encryption:   "" => "true"
  ingress_hostname:  "" => "<computed>"
  ingress_secret:    "<sensitive>" => "<sensitive>"
  isolation:         "" => "public"
  kube_version:      "" => "1.9.7_1510"
  machine_type:      "" => "u2c.2x4"
  name:              "" => "iccs_test_syd"
  no_subnet:         "" => "false"
  private_vlan_id:   "" => "2251209"
  public_vlan_id:    "" => "2251207"
  server_url:        "" => "<computed>"
  wait_time_minutes: "" => "90"
  worker_num:        "" => "<computed>"
  workers.#:         "" => "1"
  workers.0.action:  "" => "add"
  workers.0.id:      "" => "<computed>"
  workers.0.name:    "" => "worker1"
  workers.0.version: "" => "1.9.7_1513"
  workers_info.#:    "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.iccs_test_syd: 1 error(s) occurred:

* ibm_container_cluster.iccs_test_syd: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"701d7024-3b0d-492a-a8a9-69aa6b3e4739","code":"E0055","description":"The specified location is invalid.","type":"Provisioning","recoveryCLI":"To list available locations, run 'bx cs locations'."}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



## This time I learned that the entire Asia Pacific region can not be ran.


We have no reason to use this service if it is not in the Asia Pacific region.


Please be sure to check and resolve this issue.

**Comment by Praveengostu** [comment]
@Najeongho We will check with our IAM dev team and will update to you on this.

**Comment by Praveengostu** [comment]
@Najeongho we will enhance the terraform to support the Asia pacific regions and will let you know once the fix is available

**Comment by Praveengostu** [comment]
@Najeongho We had enabled the terraform ibm cloud provider to  support the container resources in asia pacific region. The fix will be available in next release which will be early next week. As the mccp end point is not available in asia-pacific regions we had made the attribute `account_guid` optional on the container resources.

**Comment by Najeongho** [comment]
Okay. I will use it when released. Thank you for your active support.

**Comment by Najeongho** [comment]
Sadly I got the same error.

terraform-provider-ibm has been upgraded to version 0.11.0.

The terraform and error contents are as follows.

----------------------------------------------------------------------------------------------

** terraform file **

provider "ibm" {
    softlayer_api_key = "<My softlayer_api_key>"
    softlayer_username = "<My softlayer_username>"
    bluemix_api_key    = "<My bluemix_api_key>"
}


resource "ibm_container_cluster" "iccs_test" {
  name            = "iccs_test"
  datacenter      = "seo01"
  kube_version    = "1.9.8_1515"
  machine_type    = "u2c.2x4"
  isolation       = "public"
  public_vlan_id  = 2251207
  private_vlan_id = 2251209
  billing         = "hourly"

  workers = [{
    name = "worker1"
    action = "add"
    version = "1.9.8_1517"
  }]

  account_guid = "<My account_guid>"
}

output "id" {
  value = "${ibm_container_cluster.iccs_test.id}"
}

output "name" {
  value = "${ibm_container_cluster.iccs_test.name}"
}

output "server_url" {
  value = "${ibm_container_cluster.iccs_test.server_url}"
}

output "workers_info" {
  value = "${ibm_container_cluster.iccs_test.workers_info}"
}

output "workers_id" {
  value = "${ibm_container_cluster.iccs_test.workers.id}"
}

----------------------------------------------------------------------------------------------

** terraform apply result **

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + ibm_container_cluster.iccs_test
      id:                <computed>
      account_guid:      "<My account_guid>"
      billing:           "hourly"
      datacenter:        "seo01"
      disk_encryption:   "true"
      ingress_hostname:  <computed>
      ingress_secret:    <computed>
      isolation:         "public"
      kube_version:      "1.9.8_1515"
      machine_type:      "u2c.2x4"
      name:              "iccs_test"
      no_subnet:         "false"
      private_vlan_id:   "2251209"
      public_vlan_id:    "2251207"
      server_url:        <computed>
      wait_time_minutes: "90"
      worker_num:        <computed>
      workers.#:         "1"
      workers.0.action:  "add"
      workers.0.id:      <computed>
      workers.0.name:    "worker1"
      workers.0.version: "1.9.8_1517"
      workers_info.#:    <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_container_cluster.iccs_test: Creating...
  account_guid:      "" => "<My account_guid>"
  billing:           "" => "hourly"
  datacenter:        "" => "seo01"
  disk_encryption:   "" => "true"
  ingress_hostname:  "" => "<computed>"
  ingress_secret:    "<sensitive>" => "<sensitive>"
  isolation:         "" => "public"
  kube_version:      "" => "1.9.8_1515"
  machine_type:      "" => "u2c.2x4"
  name:              "" => "iccs_test"
  no_subnet:         "" => "false"
  private_vlan_id:   "" => "2251209"
  public_vlan_id:    "" => "2251207"
  server_url:        "" => "<computed>"
  wait_time_minutes: "" => "90"
  worker_num:        "" => "<computed>"
  workers.#:         "" => "1"
  workers.0.action:  "" => "add"
  workers.0.id:      "" => "<computed>"
  workers.0.name:    "" => "worker1"
  workers.0.version: "" => "1.9.8_1517"
  workers_info.#:    "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.iccs_test: 1 error(s) occurred:

* ibm_container_cluster.iccs_test: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"f750be80-5e40-4032-8b43-0d35e5000dbc","code":"E0055","description":"The specified location is invalid.","type":"Provisioning","recoveryCLI":"To list available locations, run 'ibmcloud cs locations'."}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


----------------------------------------------------------------------------------------------

I add region = "ap-north" to the IBM Cloud Provider, you will get the following error when running terraform apply:



** terraform file **

provider "ibm" {
    softlayer_api_key = "<My softlayer_api_key>"
    softlayer_username = "<My softlayer_username>"
    bluemix_api_key    = "<My bluemix_api_key>"
    region = "ap-north"
}

.. omit ..


----------------------------------------------------------------------------------------------

** terraform apply result **

.. omit ..

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.iccs_test: 1 error(s) occurred:

* ibm_container_cluster.iccs_test: Error occured while configuring Container Service for K8s cluster: "ServiceEndpointDoesnotExist: IAM  endpoint doesn't exist for region: \"ap-north\""

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


----------------------------------------------------------------------------------------------


Please make sure that I am doing something wrong or that the changes are not reflected in this release.

**Comment by Praveengostu** [comment]
@Najeongho The release 0.11.0 does not have the fix. The release with fix will be in this week. Will keep you updated.

**Comment by sakshiag** [comment]
@Najeongho : You need to define the region name as 'jp-tok' which is alias for ap-north.

**Comment by Najeongho** [comment]
Okay. I am waiting for the release next week.

**Comment by sakshiag** [comment]
You can get the latest driver from here - https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.1 which contains the fix for this.

**Comment by guyos** [comment]
The relationship between the IAM region to authenticate with and the region where to create IKS is not clear to me. Perhaps these should be unrelated. You could authenticate in one region and create a cluster in a different region, you may want to create multiple clusters in different regions unrelated to where you have authenticated.
**Suggestion** to include region as a variable of the cluster resource.

**Comment by sakshiag** [comment]
@guyos : Thank you for the suggestion. We will surely look into this and do the possible.

**Comment by Praveengostu** [comment]
Hi, Released v0.11.2 Please try with latest
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.2
We have added region attribute for all the container resource. Could you please close this issue if its working as expected.

**Comment by guyos** [comment]
@Praveengostu - has there been additional changes? I only added region to the container resource but I am getting...
ibm_container_cluster.iks_cluster: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"1a16ae41-2b5d-4887-81a2-55ad59c6667f","code":"E0010","description":"The input parameters in the request body are either incomplete or in the wrong format. Be sure to include all required parameters in your request in JSON format.","type":"General"}

**Comment by Praveengostu** [comment]
@guyos Could you please share me your configuration to understand the issue further

**Comment by guyos** [comment]
My fault! I had errors with my export statements to set some of the variables.
It is creating the cluster now.
I can't close this issue as I am not the author

**Comment by hkantare** [comment]
Closing the issue based on above comments
