### ISSUE TITLE
terraform apply issue occurs while selecting cooldown value as '0'.

### ISSUE THREAD

**Issue by smalpani37** [IBM-Cloud/terraform-provider-ibm#285]
Hi there,

Please check this problem.

Terraform Version

$ terraform -v
Terraform v0.11.7

provider.ibm (unversioned)
Affected Resource(s)

ibm_compute_autoscale_policy
Terraform Configuration Files
resource "ibm_compute_autoscale_policy" "test"{
scale_group_id= "230XX07",
 name= "test_policy",
 
 cooldown= "0",
 scale_type= "PERCENT",
 scale_amount= "250"
}
Debug Output

Error: Error applying plan:

1 error(s) occurred:

Error: Error applying plan:

1 error(s) occurred:

* ibm_compute_autoscale_policy.test: 1 error(s) occurred:

* ibm_compute_autoscale_policy.test: Error retrieving scalePolicy: cooldown must be between 0 seconds and 10 days.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
Panic Output

The crash.log has not been created.

Expected Behavior

What should have happened?

New policy get attached to Autoscale Group with the given configuration.

Actual Behavior

What actually happened?
Error: Error applying plan:

1 error(s) occurred:

* ibm_compute_autoscale_policy.test: 1 error(s) occurred:

* ibm_compute_autoscale_policy.test: Error retrieving scalePolicy: cooldown must be between 0 seconds and 10 days.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Steps to Reproduce

terraform init
terraform plan
terraform apply
Input yes

References

Nothing.

**Comment by hkantare** [comment]
The fix is available in v0.11.0 & v0.11.1 can you please try with latest driver.

**Comment by hkantare** [comment]
Can you close this issue if its working as expected.

**Comment by hkantare** [comment]
Closing the issue . If issue still exists please reopen it.
