### ISSUE TITLE
How do I find a default security group to attach to a load balancer which is already created, using a terraform script.

### ISSUE THREAD

**Issue by siddhinaik** [IBM-Cloud/terraform-provider-ibm#2882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kavya498** [comment]
@siddhinaik 
VPC resource and datasource has a attribute called [default_security_group](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc#default_security_group) which gives the ID of default security group

**Comment by siddhinaik** [comment]
yeah, but using data "ibm_is_lb" how can I get the vpc associated to a load balancer and then attch the default security group.

**Comment by astha-jain** [comment]
@SunithaGudisagarIBM  Please help

**Comment by astha-jain** [comment]
I think you can use this datasource https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_security_group_targets

**Comment by astha-jain** [comment]
resource_type attribute would tell you if it is a security group

**Comment by SunithaGudisagarIBM** [comment]
@siddhinaik @astha-jain 

Please use the following template to find  and attach the default security group to load balancer 

resource "ibm_is_vpc" "testacc_vpc" {
  name = "vpcname"
}
resource "ibm_is_subnet" "testacc_subnet" {
  name            = "subnetname"
  vpc             = ibm_is_vpc.testacc_vpc.id
  zone            = "us-south-1"
  ipv4_cidr_block = "10.240.0.0/24"
}
resource "ibm_is_security_group" "testacc_security_group" {
  name = "securitygroup"
  vpc  = ibm_is_vpc.testacc_vpc.id
}
resource "ibm_is_lb" "testacc_LB" {
  name            = "loadbalancer"
  subnets         = [ibm_is_subnet.testacc_subnet.id]
  security_groups = [ibm_is_security_group.testacc_security_group.id]
  logging         = false
}

data "ibm_is_subnet" "ds_subnet" {
  identifier = ibm_is_subnet.testacc_subnet.id
}

data "ibm_is_vpc" "testacc_vpc" {
  name = data.ibm_is_subnet.ds_subnet.vpc_name
}

resource "ibm_is_security_group_target" "testacc_security_group_target" {
  security_group = ibm_is_vpc.testacc_vpc.default_security_group
  target         = ibm_is_lb.testacc_LB.id
}


<img width="1509" alt="Screenshot 2021-07-16 at 9 40 50 AM" src="https://user-images.githubusercontent.com/78336632/125890795-c34a8ec9-4a93-44e0-88ca-5f9c13c995c7.png">

**Comment by astha-jain** [comment]
@siddhinaik is this good to close?

**Comment by kavya498** [comment]
Closing this issue as it has been inactive for more than 30 days..This helps maintainers find and focus on the active issues.

If you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thanks!
