### ISSUE TITLE
IAM Managing members

### ISSUE THREAD

**Issue by PKehnel** [IBM-Cloud/terraform-provider-ibm#2905]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

*  ibm_iam_access_group_members

### Terraform Configuration Files

Adding a person to a access group:
```hcl
resource "ibm_iam_access_group_members" "verify_ag_members" {
  access_group_id = access_group_name
  ibm_ids         = ["id1@ibm.com"]
}
```
 Removing a person from an access group:
```hcl
resource "ibm_iam_access_group_members" "verify_ag_members" {
  access_group_id = access_group_name
  ibm_ids         = []
}
```

### Expected Behavior

Adding a person with the code snippet above works. 
Removing the person by passing a empty list works as well.

Adding a person via GUI in the IBM Cloud works.
Now removing this person via terraform and empty list should also work.

### Actual Behavior

Terraform detects the following changes made outside of Terraform.
But is not removing the person.
### Steps to Reproduce

1.  Add a person via GUI
2. Set 'ibm_ids" to. = []
3. `terraform apply`

**Comment by PKehnel** [comment]
@guicabr Is this intended?

**Comment by guicabr** [comment]
Hello @PKehnel , sorry for the delay in my response, I was on sick leave for last 2 weeks. I have re routed this issue to the lead  for IAM Access Groups.

**Comment by narinder-kaur** [comment]
@PKehnel, we are currently looking into it and Will get back soon.
