### ISSUE TITLE
Deprecated field in ibm_container_worker_pool

### ISSUE THREAD

**Issue by guillelb** [IBM-Cloud/terraform-provider-ibm#2915]
Creating Kubernetes worker pools as described in the doc:  https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_worker_pool

Warning: Attribute is deprecated on worker_pools.tf line 8, in resource "ibm_container_worker_pool" "workerpool":
8:   region           = var.ibm_region
This field is deprecated

**Comment by kavya498** [comment]
@guillelb ,
region field is deprecated.. We ll update the docs..
