### ISSUE TITLE
Dependency not work

### ISSUE THREAD

**Issue by erotallgeese** [IBM-Cloud/terraform-provider-ibm#294]
Hi there,

After deploying an loadbalancer(lbass) with an vm instance, i try to simply change the loadbalancer's name but failed.
After checking its error, the root cause is that the destroy order is wrong.
I have try to add dependency setting to fix the order but still not work.

Also, the destroy would get unexpected behavior.
I have test many times ...and find some things:
1. destroy with origin tf file and it would succeed.
2. destroy with modified tf file would get same error.
In my thought, destroy does not need tf file, but it seems cause the destroy order be wrong.... i'm not very sure but i reproduce this situation 2 times.

I'm not sure whether this is terraform's issue or something else, please kindly help.

### Terraform Version
terraform 0.11.7
terraform-provider-ibm 0.10.0

### Affected Resource(s)
- ibm_lbaas
- ibm_lbaas_server_instance_attachment

### Terraform Configuration Files
[origin tf](https://gist.github.com/erotallgeese/53659dff34ce70e6e0056e399555d4c5)
[modified tf](https://gist.github.com/erotallgeese/49a549ba21a6d8d88c2ce4f7ed49aaa4) Here only change ibm_lbaas 's name and its resource name.

### Debug Output
[update_fail](https://gist.github.com/erotallgeese/dee9cd51e02bec0dd792701ae8d33bbc)
[delete_fail](https://gist.github.com/erotallgeese/b4686ba742859df4f98ac8d957469345)

### Expected Behavior
It should update/delete in following order:
destroy ibm_lbaas_server_instance_attachment.attachment_vm0_asdf
destroy ibm_lbaas.loadbalance01_qq

### Actual Behavior
It would destroy ibm_lbaas.loadbalance01_qq first and cause following destroy failed

### Steps to Reproduce
1. Update
    1. apply origin tf
    1. change loadbalancer's name (modified tf) and apply again
2. Delete
    1. apply origin tf
    1. change loadbalancer's name (modified tf) and do destroy

**Comment by Praveengostu** [comment]
@erotallgeese Could you please help us understand your use case for changing the resource name.
What is the command you are using to destroy `terraform destroy` or `terrafrom apply`.
Try using `terraform destroy` and then `terraform apply`.

**Comment by erotallgeese** [comment]
@Praveengostu There are 2 cases:
```terrafrom apply``` for update;
```terraform destroy``` for delete.

**Comment by Praveengostu** [comment]
@erotallgeese Could you please help us to understand with your use case.

**Comment by Praveengostu** [comment]
@erotallgeese Let us know if you still have the issue, or Please close this
