### ISSUE TITLE
Terraform doc for custom resolver

### ISSUE THREAD

**Issue by MalarvizhiK** [IBM-Cloud/terraform-provider-ibm#2946]
Our doc team,  noticed a weird thing in the DNS Services navigation. There seems to be one item in "DNS Svcs" instead of everything being under the "DNS Services" heading.
 https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/dns_custom_resolver_forwarding_rule

**Comment by hkantare** [comment]
Its fixed in the latest branch...It will be available as part of next release

**Comment by kavya498** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/commit/b2724c9751d5584affc762b3c9fdbbac8b3fee7b
Closing this issue..
Thanks
