### ISSUE TITLE
Need Licensing fee management feature

### ISSUE THREAD

**Issue by mossuchida** [IBM-Cloud/terraform-provider-ibm#2950]
Currently, there is no documentation about 
- How to add "OCP Entitlement".  Please provide me steps to add my "Cloud pak OCP entitlement" to this worker pool.
- How to setup so that it can be charged "hourly".

These features are needed for `classic infrastructure`
Please provide these steps. If they are not implemented, please provide me guidance on how to add these features as I run daily automation testing, I need them added to reduce the incurring costs.

**Comment by mossuchida** [comment]
Oh, I guess this?  https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_cluster
resource "ibm_container_cluster" "cluster" {
....
  entitlement       = "cloud_pak"
}

and Billing is depricated that means there is no longer hourly & monthly billing?

`billing - (Deprecated, Optional, Forces new resource, string) The billing type for the instance. Accepted values are hourly or monthly.
`

**Comment by kavya498** [comment]
@mossuchida ,
Billing is based on the flavor of the pool..
`machine_type` argument in the resource defines flavor.. 
I believe all virtual machines are hourly billing..
<img width="909" alt="image" src="https://user-images.githubusercontent.com/46739084/128671032-d4b40dbe-c57d-4441-92d3-d89e7b8cb6c9.png">

**Comment by kavya498** [comment]
@mossuchida , 
Hope above comment helped you to resolve the issue..
Closing this issue..Please reopen if issue persists..
Thanks..
