### ISSUE TITLE
update feature ibm local load balancer

### ISSUE THREAD

**Issue by jkhan001** [IBM-Cloud/terraform-provider-ibm#296]
need to add update method for connections limit in resource ibm_lb

**Comment by sakshiag** [comment]
We have added the upgrade connection limit.. Fix is present in the master code , you can build and try it.

**Comment by sakshiag** [comment]
Fix is available in the latest release. Can we close this issue?

**Comment by hkantare** [comment]
Closing the issue . If issue still exists please reopen it.
