### ISSUE TITLE
ibm_is_vpc_default_routing_table and ibm_is_vpc_default_routing_table differences

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2983]
The are two different ways to get at a routing table.  But the attributes are different.  Below is the focus on the attributes that interested me, but all of the attributes should be examined.

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc_routing_table

Attribute reference
- id - (String) The routing table ID. The ID is composed of <vpc_id>/<vpc_route_table_id> of the VPC route.
- routing_table - (String) The generated routing table ID.

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_vpc_default_routing_table
- default_routing_table - (String) The unique identifier for the default routing table.
- id - (String) The unique ID for the default routing table.

- [ ] Are the resources really as different as they seem
- [ ] what is the diff between ibm_is_vpc_default_routing_table.id and ibm_is_vpc_default_routing_table.default_routing_table
- [ ] what is the diff between the ibm_is_vpc_default_routing_table.id and is_vpc_routing_table.id

Expected: The attribute reference section of these resources to be almost identical
Actual: differences.

**Comment by astha-jain** [comment]
I'll take a look

**Comment by ujjwal-ibm** [comment]
@powellquiring 

> Are the resources really as different as they seem

First one(https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc_routing_table) is a resource, second one(https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_vpc_default_routing_table) is a datasource.




> what is the diff between ibm_is_vpc_default_routing_table.id and ibm_is_vpc_default_routing_table.default_routing_table
 
 the id generated for a connected resource is usually a combination, so  **<vpc_id>/<vpc_route_table_id>** is the id wrt to the resource, used for importing the resource.
 
 
> what is the diff between the ibm_is_vpc_default_routing_table.id and is_vpc_routing_table.id

One is the id of the default Routing table of the vpc (data source) and one is the terraform generated id of the resource to keep the import easier.

**Comment by ujjwal-ibm** [comment]
@powellquiring these two `default_routing_table` and `id` here (https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_vpc_default_routing_table) are the same.

**Comment by kavya498** [comment]
@powellquiring , Are we good to close?
Thanks.

**Comment by powellquiring** [comment]
> The are two different ways to get at a routing table. But the attributes are different. Below is the focus on the attributes that interested me, but all of the attributes should be examined.

```
ibm_is_vpc_default_routing_table = {
  "created_at" = "2021-12-21T16:18:17.000Z"
  "default_routing_table" = "r006-5dd90323-f8bf-4e34-bf87-df8bad3d6c62"
  "href" = "https://us-south.iaas.cloud.ibm.com/v1/vpcs/r006-de8d3daf-292b-4bad-8e20-1653747bfa3c/routing_tables/r006-5dd90323-f8bf-4e34-bf87-df8bad3d6c62"
  "id" = "r006-5dd90323-f8bf-4e34-bf87-df8bad3d6c62"
  "is_default" = true
  "lifecycle_state" = "stable"
  "name" = "imitate-showier-jacket-amazingly"
  "resource_type" = "routing_table"
  "route_direct_link_ingress" = false
  "route_transit_gateway_ingress" = false
  "route_vpc_zone_ingress" = false
  "routes" = tolist([])
  "subnets" = tolist([])
  "vpc" = "r006-de8d3daf-292b-4bad-8e20-1653747bfa3c"
}


ibm_is_vpc_routing_table = {
  "created_at" = "2021-12-21T16:18:32.000Z"
  "href" = "https://us-south.iaas.cloud.ibm.com/v1/vpcs/r006-9ce4d584-00d4-45f8-9ed4-68d57e1b86e4/routing_tables/r006-23901944-4b2f-4457-934a-bf74d677dfcc"
  "id" = "r006-9ce4d584-00d4-45f8-9ed4-68d57e1b86e4/r006-23901944-4b2f-4457-934a-bf74d677dfcc"
  "is_default" = false
  "lifecycle_state" = "stable"
  "name" = "vpc2-route-table"
  "resource_type" = "routing_table"
  "route_direct_link_ingress" = true
  "route_transit_gateway_ingress" = false
  "route_vpc_zone_ingress" = false
  "routing_table" = "r006-23901944-4b2f-4457-934a-bf74d677dfcc"
  "subnets" = tolist([])
  "timeouts" = null /* object */
  "vpc" = "r006-9ce4d584-00d4-45f8-9ed4-68d57e1b86e4"
}
```
Missing in the docs:

```
ibm_is_vpc_routing_table = {
  "created_at" = "2021-12-21T16:18:32.000Z"
```

**Comment by kavya498** [comment]
@ujjwal-ibm ,FYI
