### ISSUE TITLE
ibm_is_snapshot - Unable to set timeouts

### ISSUE THREAD

**Issue by DanielFarrarCO** [IBM-Cloud/terraform-provider-ibm#2989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
Terraform v1.0.4 - IBM Cloud version 1.29.0

### Affected Resource(s)

* ibm_is_snapshot

### Terraform Configuration Files

Reference:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_snapshot

Basic Snapshot Create:
resource "ibm_is_snapshot" "testacc_snapshot" {
  name            = "testsnapshot"
  source_volume   = ibm_is_instance.testacc_instance.volume_attachments[0].volume_id
}

### Debug Output

Error: timeout while waiting for state to become 'stable, failed' (last state: 'pending', timeout: 10m0s)

### Expected Behavior

Snapshot create process should be able to monitor during length of creation.

Other modules allow you to edit the default timeouts for create/update/delete but this one has not yet implemented. 

### Actual Behavior

Disks with a large amount of data to sync which take more than 10 minutes to complete are unable to exceed the default 10 minute timeout.

### Steps to Reproduce

Create disk with large amount of data, take snapshot with:

1. `terraform apply`

**Comment by astha-jain** [comment]
@ujjwal-ibm Can you please take a look?

**Comment by ujjwal-ibm** [comment]
@DanielFarrarCO 

Snapshot do support timeouts,  please use the `timeouts` attribute as done in other resources.
```
  timeouts {
    create = "15m"
    delete = "15m"
  }
```  
Added a documentation update

**Comment by DanielFarrarCO** [comment]
Thanks for the documentation update!  I'll pass this along to the Ansible team so that timeouts can be added to the Ansible modules as well.
