### ISSUE TITLE
VSI from custom image

### ISSUE THREAD

**Issue by gitjps** [IBM-Cloud/terraform-provider-ibm#3009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a VSI using an existing custom image, see also [How to create an IBM Cloud VSI using a custom image](https://stackoverflow.com/questions/68846613/how-to-create-an-ibm-cloud-vsi-using-a-custom-image)

### New or Affected Resource(s)

* ibm_is_instance

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

data "ibm_is_image" "centos" {
   name       = "r010-489ff05b-1494-4a05-8b12-c6f44a958859"
   visibility = "private"
}

# Virtual Server Insance
resource "ibm_is_instance" "vsi1" {
   name    = "${local.BASENAME}-vsi1"
   vpc     = ibm_is_vpc.vpc-instance.id
   keys    = [data.ibm_is_ssh_key.ssh_key_id.id]
   zone    = local.ZONE
   image   = data.ibm_is_image.centos.id
   profile = "cx2-2x4"
   
   # References to the subnet and security groups
   primary_network_interface {
     subnet          = ibm_is_subnet.subnet1.id
     security_groups = [ibm_is_security_group.sg1.id]
   }
}
```

### References

* #0000

**Comment by ujjwal-ibm** [comment]
@gitjps 

Seems like you're using `id` in place of `name` in your datasource

```
data "ibm_is_image" "centos" {
   name       = "r010-489ff05b-1494-4a05-8b12-c6f44a958859"
   visibility = "private"
}
```

Try using the name of the image.

**Comment by gitjps** [comment]
obsolete
