### ISSUE TITLE
ibm_container_vpc_cluster docs needs improvement

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3014]
Docs here https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_cluster

A number of the parameters are actually parameters of the default worker pool, but this is not clear from the docs:
----
zones - (Required, List) A nested block describes the zones of this VPC cluster.

Nested scheme for zones:

name - (Required, Forces new resource, String) The name of the zone.
subnet_id - (Required, Forces new resource, String) The VPC subnet to assign the cluster.
---
This stuff is for the worker pool, make it clear in the docs:
- [ ] zone specification
- [ ] entitlement 
- [ ] flavor (already correct)

Also:
- [ ] Worker count of 0 does not create 0 worker pools.  It must be documented.  It would be great if this was an error condition.

**Comment by geethaostrg** [comment]
@powellquiring , docs description is fixed for zone and entitlement, as per the content shared by the dev team and a PR is raised to merge into registry, in the upcoming release,  the change will be reflected. 

Thanks much for letting us know,
@geethasathyamurthy

**Comment by hkantare** [comment]
Fixed https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_cluster#wait_till
