### ISSUE TITLE
ibm_database fails to update user password

### ISSUE THREAD

**Issue by tpolekhin** [IBM-Cloud/terraform-provider-ibm#3018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.29.0
```

### Affected Resource(s)

* ibm_database

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "ibm_resource_group" "group" {
  name = "Default"
}
resource "ibm_database" "postgres" {
  name              = "postgres"
  plan              = "standard"
  location          = "us-south"
  service           = "databases-for-postgresql"
  resource_group_id = data.ibm_resource_group.group.id

  adminpassword                = "password12"
  members_memory_allocation_mb = 4096
  members_disk_allocation_mb   = 20480
  users {
    name     = "user123"
    password = "password12"
  }
}
```

### Expected Behavior

Terraform should update existing user password to new one
User password update is supported operation in the CDB API
https://cloud.ibm.com/apidocs/cloud-databases-api/cloud-databases-api-v5#changeuserpassword

### Actual Behavior
`Error: [ERROR] Error waiting for database (crn:v1:bluemix:public:databases-for-postgresql:us-south:<REDACTED>:<REDACTED>::) user (user123) create task to complete: [Error] Database task failed`

### Steps to Reproduce

1. Deploy an ibm_database resource with user defined
2. Update user password and run `terraform apply`

**Comment by kavya498** [comment]
@tpolekhin ,
Can we get complete logs?

**Comment by tpolekhin** [comment]
```
$ terraform apply
ibm_database.postgres: Refreshing state... [id=crn:v1:bluemix:public:databases-for-postgresql:us-south:<REDACTED>:<REDACTED>::]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # ibm_database.postgres will be updated in-place
  ~ resource "ibm_database" "postgres" {
        id                           = "crn:v1:bluemix:public:databases-for-postgresql:us-south:<REDACTED>:<REDACTED>::"
        name                         = "postgres"
        tags                         = []
        # (24 unchanged attributes hidden)


      - users {
          - name     = "user123" -> null
          - password = (sensitive value)
        }
      + users {
          + name     = "user123"
          + password = (sensitive value)
        }
        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ibm_database.postgres: Modifying... [id=crn:v1:bluemix:public:databases-for-postgresql:us-south:<REDACTED>:<REDACTED>::]
ibm_database.postgres: Still modifying... [id=crn:v1:bluemix:public:databases-for-pos...<REDACTED>::, 10s elapsed]
╷
│ Error: [ERROR] Error waiting for database (crn:v1:bluemix:public:databases-for-postgresql:us-south:<REDACTED>:<REDACTED>::) user (user123) create task to complete: [Error] Database task failed
│
│   with ibm_database.postgres,
│   on main.tf line 99, in resource "ibm_database" "postgres":
│   99: resource "ibm_database" "postgres" {
│
╵
```

**Comment by tpolekhin** [comment]
btw, after this error Terraform sees no changes to the infrastructure, even though user password update failed
```
$ terraform apply
ibm_database.postgres: Refreshing state... [id=crn:v1:bluemix:public:databases-for-postgresql:us-south:<REDACTED>:<REDACTED>::]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by kavya498** [comment]
@tpolekhin,
We not only update user name and password.. but also wait for the status of the task to be `completed`
Looks like the status is `failed` i.e is the reason terraform failed..

We are not setting back in READ method as we dont have any API to get users of database.. That is why you see No Infrastructure.. We ll look into it how it can be handled..

**Comment by kavya498** [comment]
As API doesn't return users, we cannot set back users in READ method of provider..
and since you have users defined in your template terraform sets back in the state file and hence you see no infrastructure change.. This is expected terraform behaviour..

We cannot do much until we get users attribute from API response..

Closing this issue..
Thanks.
