### ISSUE TITLE
Terraform provider for ibm_is_vpc does not allow for tags to be assigned to a SG, ACL, routing table

### ISSUE THREAD

**Issue by andrewferrier** [IBM-Cloud/terraform-provider-ibm#3029]
### Terraform CLI and Terraform IBM Provider Version

Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.29.0

### Affected Resource(s)

* ibm_is_vpc

### Terraform Configuration Files

```hcl
resource "ibm_is_vpc" "vpc" {
  name                        = "${var.prefix}-vpc"
  resource_group              = var.resource_group_id
  address_prefix_management   = "manual"
  default_security_group_name = "${var.prefix}-sg-default"
  default_network_acl_name    = "${var.prefix}-acl-default"
  default_routing_table_name  = "${var.prefix}-rt-default"
  tags                        = var.tags
}
```

The IBM FS Cloud reference architecture, as well as general best practice, stipulates that resources should have appropriate tags attached (e.g. environment name). The VPC resource currently allows tags to be attached to the VPC itself, but not the default Security Group, Network ACL, and Routing Table.

### Steps to Reproduce

1. `terraform apply`

**Comment by andrewferrier** [comment]
Yes, that's the problem I'm reporting.

**Comment by astha-jain** [comment]
@andrewferrier You are making a good point. I will need to investigate further.

**Comment by astha-jain** [comment]
Hello @andrewferrier  
Routing table does not support tagging.
I see the name and ID for default acl and default sg is available for vpc and one way to achieve this could be to use the security group datasource and tagging resource.

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_security_group#crn
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/resource_tag


```
data "ibm_is_security_group" "sg1_rule" {
  name = ibm_is_vpc.vpc1.default_security_group_name
}

resource "ibm_resource_tag" "tag" {
    resource_id = ibm_is_security_group.sg1_rule.crn
    tags        = var.tag_names
}

``` 
I noted that the datasource(s) for ACL is missing and I am working on adding that so you can tag the ACLs same way.

**Comment by andrewferrier** [comment]
OK - can we please reopen this until the ACL data source is present?

**Comment by andrewferrier** [comment]
Thanks for the workarounds @astha-jain
