### ISSUE TITLE
Error during creating discovery as resource instance

### ISSUE THREAD

**Issue by blbird** [IBM-Cloud/terraform-provider-ibm#304]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- ibm_resource_instance

### Terraform Configuration Files
```hcl
resource "ibm_resource_instance" "discovery" {
  name              = "test/discovery"          # from parameter
  service           = "discovery"
  plan              = "lite"               # from plan
  location          = "us-east"                             # from plan
}
```

### Debug Output
ibm_resource_instance.discovery: Creating...
  location:          "" => "us-east"
  name:              "" => "test/discovery"
  plan:              "" => "lite"
  service:           "" => "discovery"
  status:            "" => "<computed>"
ibm_resource_instance.discovery: Still creating... (10s elapsed)
ibm_resource_instance.discovery: Still creating... (20s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* ibm_resource_instance.discovery: 1 error(s) occurred:

* ibm_resource_instance.discovery: Error waiting for create resource instance (crn:v1:bluemix:public:discovery:us-east:a/67c979772369d74ae076be6673fdb5a8:4b40219b-21c9-48fd-a4c7-9eb0db390354::) to be succeeded: unexpected state 'inactive', wanted target 'active'. last error: %!s(<nil>)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
No error.

### Actual Behavior
What actually happened?
Error occurs

### Steps to Reproduce
1. `terraform apply`

**Comment by hkantare** [comment]
We will look and fix the issue

**Comment by hkantare** [comment]
The issue is fixed in latest driver. Can you please try with latest drive v0.11.1 https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.1

**Comment by blbird** [comment]
@hkantare Thanks. It work fine.
