### ISSUE TITLE
ibm_pi_instance_info is not showing decimal places for CPUs

### ISSUE THREAD

**Issue by cunlifs** [IBM-Cloud/terraform-provider-ibm#3053]
Using:
Terraform v1.0.3 on linux_ppc64le & terraform-provider-ibm_v1.28.0

When I run the ibm.cloudcollection.ibm_pi_instance_info modules against a PVS VSI it only returns the unit information about the min/current and max entitled cores. In PVS this number can be a fraction of a whole core, from 0.25. Max is 2 decimal points. For example a VSI with 0.25 cores is showing as 0.

pi_instance_existing_output”: {
    “changed”: false,
    “resource”: {
…..
      **“minproc”: 0,**
      “pi_cloud_instance_id”: “dd5a404f-59cb-4c04-b9a0-811b47c6df19",
      “pi_instance_name”: “stu-test2",
      “pin_policy”: “none”,
      **“processors”: 0,**

Info from @jaywcarman:
Terraform provider is calling them out as integers:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/pi_instance#attribute-reference

But it's easy to show that's not the case:
> ic pi in 00140962-1c1d-4256-93b7-3f8f4ff836c1 --json | jq .minproc
0.25

-------
Can this be looked at please as I'm hoping its a simple fix.

**Comment by jwcroppe** [comment]
@yussufsh FYI

**Comment by yussufsh** [comment]
We need to also look at other attributes where the types needs to be corrected and also the website page need some updates. I will work on the fix.

**Comment by jwcroppe** [comment]
Thanks @yussufsh - agree - we should also clarify the documentation as well with some examples of the various data types so that it's clear what each attribute represents.
