### ISSUE TITLE
Error:Bare Metal Monthly Service Could not found matching id with categorycode MONITORING_HOST_PING 

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#307]
Hi there,

While Provisioning bare metal monthly service with following configurations:-

terraform apply -var 'hostname=hostanme' -var 'domain=doamin.com' -var 'datacenter=sao01' -var 'package_key_name=BI_S1_NW128_VMWARE_VIRTUALIZATION' -var 'os_key_name=OS_VMWARE_SERVER_VIRTUALIZATION_6_5' -var 'process_key_name=INTEL_XEON_2690_2_60' -var 'memory=128' -var 'private_vlan_id=0' -var 'private_subnet=' -var 'private_network_only=true' -var 'public_bandwidth=0' -var 'public_vlan_id=0' -var 'public_subnet=' -var 'unbonded_network=false' -var 'redundant_network=false' -var 'restricted_network=false' -var 'network_speed=1000' -var 'ssh_key_ids=[]' -var 'user_metadata=' -var 'post_install_script_uri=' -var 'tags=[]' -var 'disk_key_names=["HARD_DRIVE_1_2_TB_SSD_10_DWPD"]' -input=false -auto-approve
giving error.

Package Id for this is :- 901

https://api.softlayer.com/rest/v3/SoftLayer_Product_Package/901/getItems.json?objectMask=mask%5Bid%2Ccategories%2Ccapacity%2Cdescription%2Cunits%2CkeyName%2Cprices%5Bid%2Ccategories%5Bid%2Cname%2CcategoryCode%5D%2ClocationGroupId%5D%5D

In above api with package id 901 item with categorycode MONITORING_HOST_PING  does not exists but MONITORING_HOST_PING_AND_TCP_SERVICE  exists.

In terraform provider we are calling getItemPriceId for MONITORING_HOST_PING but in package response it does not exists.
  --

monitoring, err := getItemPriceId(items, "monitoring", "MONITORING_HOST_PING")
	if err != nil {
		return datatypes.Container_Product_Order{}, err
	}
	if d.Get("tcp_monitoring").(bool) {
		monitoring, err = getItemPriceId(items, "monitoring", "MONITORING_HOST_PING_AND_TCP_SERVICE")
		if err != nil {
			return datatypes.Container_Product_Order{}, err
		}
	}

**Comment by M-Rushabh** [comment]
@hkantare Could you please look at this issue

**Comment by hkantare** [comment]
We will look and get back

**Comment by hkantare** [comment]
We made the fix and its available in latest driver. Can you please try with https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.1

**Comment by hkantare** [comment]
Can you please close this issue if it working as expected..

**Comment by M-Rushabh** [comment]
Sure Thank you
