### ISSUE TITLE
Power client doesnot expose URL or endoint env variable in provider config.go

### ISSUE THREAD

**Issue by kavya498** [IBM-Cloud/terraform-provider-ibm#3072]
Support for private endpoints or modify endpoint URL via provider is not possible as values are hardcoded in SDK.. 
Power SDK has to be modified to accept endpoint as variable..

**Comment by yussufsh** [comment]
The SDK provides a way to override the endpoint for power APIs by using `IBMCLOUD_POWER_API_ENDPOINT` environment variable.
Example for using test env:
```
export IBMCLOUD_POWER_API_ENDPOINT="dal.power-iaas.test.cloud.ibm.com"
```

Is your plan to use another environment variable in the provider code to set the given SDK variable?
