### ISSUE TITLE
Adding certain classic access permissions is not working.

### ISSUE THREAD

**Issue by PKehnel** [IBM-Cloud/terraform-provider-ibm#3074]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

1.30

### Affected Resource(s)

* ibm_IAM

### Terraform Configuration Files

```
resource "ibm_iam_user_invite" "invite_user" {
  users = ["test@in.ibm.com"]
  classic_infra_roles {
    permissions = ["ACCESS_ALL_DEDICATEDHOSTS","ACCESS_ALL_HARDWARE","ACCESS_ALL_GUEST"]
  }
}
```

### Expected Behavior

Invite user with the above permissions.

### Actual Behavior

Error: 

Request failed with status code: 400, ServerErrorResponse: {"trace":"9a7a69f1-383d-48ff-8fa8-fe31aad94670","errors":[{"code":"Bad Request","message":"Invalid payload. Error: INVALID_IAAS_PERMISSIONS : ACCESS_ALL_DEDICATEDHOSTS,ACCESS_ALL_HARDWARE,ACCESS_ALL_GUEST","more_info":""}],"status_code":400}

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Executed as account owner

### References

This issue seems to be known since over a year.

* #1330
* #1662

**Comment by PKehnel** [comment]
@narinder-kaur Is this your area again? 😄

**Comment by kavya498** [comment]
@PKehnel ,

Using user invite resource we can assign following roles of classic infra across Account, Devices, Network and Services [here](https://cloud.ibm.com/iam/users/invite_users).. 
```
No access
View only
Basic user
Super user
```
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/46739084/132342623-32c39686-7989-40b7-8f0c-138ea29395c9.png">

I don't see these roles `ACCESS_ALL_DEDICATEDHOSTS","ACCESS_ALL_HARDWARE","ACCESS_ALL_GUEST` in that list..

Can you please let us know how this is performed via UI or CLI?

**Comment by PKehnel** [comment]
This is performed via a terraform file. 

They refer to devices. 

Same resources are for example used in: 
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/compute_user

**Comment by kavya498** [comment]
compute resources uses soft layers APIs.. user invite resources uses IAM APIs..
I dont think it is possible via user invite resource.. may be you can add local exec provisioners and perform
`ibmcloud sl user permission-edit <user_id> --permission <permission_keyname> --enable (true|false)`

**Comment by PKehnel** [comment]
okay, not happy with the solution but I understand the issue. 
Thanks for the info.
