### ISSUE TITLE
Zones are mutable in provider, but seem immutable in IBM Cloud?

### ISSUE THREAD

**Issue by david-shepard** [IBM-Cloud/terraform-provider-ibm#3078]
It seems that, for an existing location,you can change zones with the IBM Cloud Provider, but it has no effect on the resulting location. For example, if a location contains the zones us-east-1, us-east-2, us-east-3 and we attempt to change the HCL so the location contains only zones us-east-1a, us-east-1b, us-east-1c. You get the following behavior with terraform generate (removal of initial zones)
![image](https://user-images.githubusercontent.com/12449626/132414511-95d2dda3-0e1b-43ab-aaa4-17dc5059ddb2.png)

But after hitting apply the zones remain **unchanged**
![image](https://user-images.githubusercontent.com/12449626/132414640-c38d3f90-193c-4515-b655-ec8b3aa902cd.png)

**Comment by anilkumarnagaraj** [comment]
zones can't be updated in the cloud console.
We will make the 'zones' parameter has immutable in the provider code.

**Comment by david-shepard** [comment]
Thanks! Let me know when the fix is in place.

**Comment by anilkumarnagaraj** [comment]
@david-shepard 

Fix is available in the latest release.

**Comment by kavya498** [comment]
Closing this issue thanks..
