### ISSUE TITLE
Terraform is crashing during apply

### ISSUE THREAD

**Issue by kannn012** [IBM-Cloud/terraform-provider-ibm#3081]
terraform version - 1.0.6
Plugin version - terraform-provider-ibm_v1.31.0

â Error: Request cancelled
â
â   with ibm_compute_vm_instance.wsusdal[0],
â   on main.tf line 63, in resource "ibm_compute_vm_instance" "wsusdal":
â   63: resource "ibm_compute_vm_instance" "wsusdal" {
â
â The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
âµ

Stack trace from the terraform-provider-ibm_v1.31.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x1e6a8d1]

goroutine 88 [running]:
github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMComputeVmInstanceCreate(0xc0004d9a80, 0x2955aa0, 0xc000c80000, 0x2, 0xffffffffffffffff)
        github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_compute_vm_instance.go:1019 +0x2b1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0009587e0, 0x2e73648, 0xc00050f1c0, 0xc0004d9a80, 0x2955aa0, 0xc000c80000, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0009587e0, 0x2e73648, 0xc00050f1c0, 0xc00040c3f0, 0xc000aa68a0, 0x2955aa0, 0xc000c80000, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c708, 0x2e73648, 0xc00050f1c0, 0xc000d6a820, 0xc00050f1c0, 0x2882560, 0xc000d5ff00)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000aa63e0, 0x2e736f0, 0xc00050f1c0, 0xc00040c1c0, 0xc000aa63e0, 0xc000d5ff20, 0xc001151ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x2882560, 0xc000aa63e0, 0x2e736f0, 0xc000d5ff20, 0xc001246480, 0x0, 0x2e736f0, 0xc000d5ff20, 0xc000baad80, 0xd1e)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000ab0000, 0x2e8c4f8, 0xc000524600, 0xc0004c8900, 0xc00067a570, 0x3c49860, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000ab0000, 0x2e8c4f8, 0xc000524600, 0xc0004c8900, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00050ce90, 0xc000ab0000, 0x2e8c4f8, 0xc000524600, 0xc0004c8900)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-ibm_v1.31.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
â·
â Error: Plugin did not respond
â
â   with ibm_compute_vm_instance.wsuswdc[0],
â   on main.tf line 90, in resource "ibm_compute_vm_instance" "wsuswdc":
â   90: resource "ibm_compute_vm_instance" "wsuswdc" {
â
â The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

**Comment by hkantare** [comment]
Can you please enable Trace by exporting TF_LOG=debug and share us the log of terraform apply
and share us the sample configuration

**Comment by kannn012** [comment]
our main.tf file

resource "ibm_compute_vm_instance" "rhsatdal" {
  count                 = var.count_rhsatdal01
  hostname              = var.hostname_rhsatdal01
  domain                = var.domain
  image_id              = var.image_id
  datacenter            = var.datacenter_rhsatdal01
  hourly_billing        = var.hourly_billing
  cores                 = var.cores_rhsatdal01
  memory                = var.memory_rhsatdal01
  disks                 = var.disks_rhsatdal01
  local_disk            = var.local_disk
  private_network_only  = var.private_network_only
  network_speed         = var.network_speed
  private_vlan_id       = var.private_vlan_id_rhsatdal01
  ssh_key_ids           = var.ssh_key_ids
  user_metadata         = data.template_file.userdatal.rendered

  lifecycle {
  ignore_changes = [user_metadata]
}
}

resource "ibm_compute_vm_instance" "rhsatwdc" {
  count                 = var.count_rhsatwdc01
  hostname              = var.hostname_rhsatwdc01
  domain                = var.domain
  image_id              = var.image_id
  datacenter            = var.datacenter_rhsatwdc01
  hourly_billing        = var.hourly_billing
  cores                 = var.cores_rhsatwdc01
  memory                = var.memory_rhsatwdc01
  disks                 = var.disks_rhsatwdc01
  local_disk            = var.local_disk
  private_network_only  = var.private_network_only
  network_speed         = var.network_speed
  private_vlan_id       = var.private_vlan_id_rhsatwdc01
  ssh_key_ids           = var.ssh_key_ids
  user_metadata         = data.template_file.userdatal.rendered

  lifecycle {
  ignore_changes = [user_metadata]
}
}

resource "ibm_compute_vm_instance" "wsusdal" {
  count                 = var.count_wsusdal01
  hostname              = var.hostname_wsusdal01
  domain                = var.domain
  image_id              = var.image_id_wsusdal01
  datacenter            = var.datacenter_wsusdal01
  hourly_billing        = var.hourly_billing
  cores                 = var.cores_wsusdal01
  memory                = var.memory_wsusdal01
  disks                 = var.disks_wsusdal01
  local_disk            = var.local_disk
  private_network_only  = var.private_network_only
  network_speed         = var.network_speed
  private_vlan_id       = var.private_vlan_id_wsusdal01
  user_metadata         = data.template_file.userdataw.rendered

  lifecycle {
  ignore_changes = [user_metadata]
}
}

resource "ibm_compute_vm_instance" "wsuswdc" {
  count                 = var.count_wsuswdc01
  hostname              = var.hostname_wsuswdc01
  domain                = var.domain
  image_id              = var.image_id_wsuswdc01
  datacenter            = var.datacenter_wsuswdc01
  hourly_billing        = var.hourly_billing
  cores                 = var.cores_wsuswdc01
  memory                = var.memory_wsuswdc01
  disks                 = var.disks_wsuswdc01
  local_disk            = var.local_disk
  private_network_only  = var.private_network_only
  network_speed         = var.network_speed
  private_vlan_id       = var.private_vlan_id_wsuswdc01
  user_metadata         = data.template_file.userdataw.rendered

  lifecycle {
  ignore_changes = [user_metadata]
}
}

**Comment by hkantare** [comment]
Please share variables  values also

**Comment by kannn012** [comment]
[tfapply.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/7128888/tfapply.txt)
debug logs attached. will share variable values shortly.

**Comment by kannn012** [comment]
[tfapply.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/7129065/tfapply.txt)
debug logs.

**Comment by kannn012** [comment]
we are trying to provision new servers and its getting provisioned in cloud, but terraform crashes and not updating state file. 
here is our variable values. 
`{
  "domain": "abc.com",
  "image_id": "7916604",
  "hourly_billing": "true",
  "local_disk": "false",
  "private_network_only": "true",
  "network_speed": "1000",
  "ssh_key_ids": ["11111"],
  
  "datacenter_prdwveeam1": "wdc06",
  "private_vlan_id_prdwveeam1": "2222",
  "hostname_rhsatdal01": "iipmgmtrhsat1",
  "cores_rhsatdal01": "4",
  "memory_rhsatdal01": "8192",
  "disks_rhsatdal01": [
    "100",
    "200"
  ],

 "datacenter_rhsatdal01": "dal10",
 "private_vlan_id_rhsatdal01": "2222",
 "count_rhsatdal01": "1",
 "hostname_rhsatwdc01": "iipmgmtrhsat2",
 "cores_rhsatwdc01": "4",
 "memory_rhsatwdc01": "8192",
 "disks_rhsatwdc01": [
   "100",
   "200"
 ],
 "datacenter_rhsatwdc01": "wdc04",
 "private_vlan_id_rhsatwdc01": "2222",
 "count_rhsatwdc01": "1",
 "hostname_wsusdal01": "iipmgmtwsus1",
 "image_id_wsusdal01": "6300150",
 "cores_wsusdal01": "4",
 "memory_wsusdal01": "8192",
 "disks_wsusdal01": [
   "100",
   "200"
 ],
 "datacenter_wsusdal01": "dal10",
 "private_vlan_id_wsusdal01": "2222",
 "count_wsusdal01": "1",
 "hostname_wsuswdc01": "iipmgmtwsus2",
 "image_id_wsuswdc01": "6300150",
 "cores_wsuswdc01": "4",
 "memory_wsuswdc01": "8192",
 "disks_wsuswdc01": [
   "100",
   "200"
 ],
 "datacenter_wsuswdc01": "wdc04",
 "private_vlan_id_wsuswdc01": "2222",
 "count_wsuswdc01": "1"

 "datacenter_rhsatwdc01": "wdc04",
  "private_vlan_id_rhsatwdc01": "2222",
  "count_rhsatwdc01": "1",
  "hostname_wsusdal01": "iipmgmtwsus1",
  "image_id_wsusdal01": "6300150",
  "cores_wsusdal01": "4",
  "memory_wsusdal01": "8192",
  "disks_wsusdal01": [
    "100",
    "200"
  ],
  "datacenter_wsusdal01": "dal10",
  "private_vlan_id_wsusdal01": "2222",
  "count_wsusdal01": "1",
  "hostname_wsuswdc01": "iipmgmtwsus2",
  "image_id_wsuswdc01": "6300150",
  "cores_wsuswdc01": "4",
  "memory_wsuswdc01": "8192",
  "disks_wsuswdc01": [
    "100",
    "200"
  ],
  "datacenter_wsuswdc01": "wdc04",
  "private_vlan_id_wsuswdc01": "2222",
  "count_wsuswdc01": "1"
}
`

**Comment by hkantare** [comment]
When we checked the logs we see one of the POST request failed with
```
021-09-08T12:24:27.013Z [DEBUG] provider.terraform-provider-ibm_v1.31.0: 2021/09/08 12:24:27 [DEBUG] Parameters:  {"parameters":[{"complexType":"SoftLayer_Container_Product_Order","orderContainers":[{"complexType":"SoftLayer_Container_Product_Order_Virtual_Guest","imageTemplateId":6300150,"location":"1441195","packageId":46,"prices":[{"hourlyRecurringFee":0.0994,"id":32985,"item":{"description":"4 x 2.0 GHz or higher Cores"},"recurringFee":65.98},{"hourlyRecurringFee":0.0262,"id":32438,"item":{"description":"8 GB"},"recurringFee":17.4},{"hourlyRecurringFee":0.012,"id":23065,"item":{"description":"100 GB (SAN)"},"recurringFee":7.46},{"hourlyRecurringFee":0.015,"id":26293,"item":{"description":"200 GB (SAN)"},"recurringFee":9.11},{"hourlyRecurringFee":0,"id":23070,"item":{"description":"Reboot / Remote Console"},"recurringFee":0},{"hourlyRecurringFee":0.008,"id":23777,"item":{"description":"1 Gbps Private Network Uplink"},"recurringFee":5},{"hourlyRecurringFee":0,"id":34183,"item":{"description":"0 GB Bandwidth Allotment"}},{"hourlyRecurringFee":0,"id":34807,"item":{"description":"1 IP Address"},"recurringFee":0},{"hourlyRecurringFee":0,"id":34241,"item":{"description":"Host Ping and TCP Service Monitoring"},"recurringFee":0},{"hourlyRecurringFee":0,"id":32500,"item":{"description":"Email and Ticket"},"recurringFee":0},{"hourlyRecurringFee":0,"id":32627,"item":{"description":"Automated Notification"},"recurringFee":0},{"hourlyRecurringFee":0,"id":16594,"item":{"description":"Unlimited SSL VPN Users"},"recurringFee":0}],"provisionScripts":[""],"quantity":1,"useHourlyPricing":true,"virtualGuests":[{"blockDevices":[{"device":"0","diskImage":{"capacity":100}},{"device":"2","diskImage":{"capacity":200}}],"datacenter":{"name":"dal10"},"domain":"ibminsplat.com","hostname":"iipmgmtwsus1","hourlyBillingFlag":true,"localDiskFlag":false,"maxMemory":8192,"networkComponents":[{"maxSpeed":1000}],"operatingSystemReferenceCode":"UBUNTU_LATEST","postInstallScriptUri":"","primaryBackendNetworkComponent":{"networkVlan":{"id":2947598}},"privateNetworkOnlyFlag":true,"startCpus":4,"userData":[{"value":"#ps1_sysnative\nSet-DnsClientServerAddress -InterfaceAlias \"Ethernet 5\" -ServerAddresses xxxx, xxxx\n\n$domain = \"ibminsplat.com\"\n$password = ConvertTo-SecureString -String \"Vkumar@123\" -asPlainText -Force\n$domainuser = \"vijneman\"\n$username = \"$domain\\$domainuser\"\n$credential = New-Object System.Management.Automation.PSCredential($username,$password)\nAdd-Computer -DomainName $domain -Credential $credential\nSet-NetFirewallProfile -Profile Domain,Public,Private -Enabled False\nRestart-Computer\n"}]}]}]},false]}
2021-09-08T12:24:31.114Z [DEBUG] provider.terraform-provider-ibm_v1.31.0: 2021/09/08 12:24:31 [DEBUG] Status Code:  200
2021-09-08T12:24:31.114Z [DEBUG] provider.terraform-provider-ibm_v1.31.0: 2021/09/08 12:24:31 [DEBUG] Response:  {"error":"Internal Error","code":"SoftLayer_Exception_Public"}
```
Can you please open a support case against Classic infrastructure to investigate more why the request is failed..But any way we will look and fix not to crash the provider

**Comment by kannn012** [comment]
sure Thanks for the update. We will raise a case.

**Comment by hkantare** [comment]
Closing the issue due to inactivity
