### ISSUE TITLE
Unable to provision global IP

### ISSUE THREAD

**Issue by uteerna** [IBM-Cloud/terraform-provider-ibm#3086]
We are getting errors when trying to provision global IPs using terraform. The following is our code:
resource "ibm_network_public_ip" "ftp_global_ip_02" {
    routes_to = ibm_compute_vm_instance.<servername>.ipv4_address
    notes     = var.note
}

The terraform provider version was 1.20.0. When we ran terraform apply, we got the following:
Error: Error editing network public Ip: json: cannot unmarshal bool into Go value of type datatypes.Provisioning_Version1_Transaction

We were able to see the global IPs in IBM Cloud portal, but when we tried to run terraform plan, we got following:

ibm_network_public_ip.ftp_global_ip_02 is tainted, so must be replaced
Plan: 1 to add, 0 to change, 1 to destroy.

And the resource is marked as tainted

We upgraded the terraform provider version to 1.30.0 and tried to provision the global IPs again but this time we got a timeout.
Error: Error during creation of network public ip: timeout while waiting for state to become 'complete' (last state: 'pending', timeout: 30m0s)

**Comment by hkantare** [comment]
The version 1.20.0 is little old binary six month back....For the timeout with 1.30.0 can you please raise a support ticket to follow up with classic infrastructure team why provisioning of global IP is taking more than 30 mins

**Comment by hkantare** [comment]
We see the support ticket closed saying backend fixed the issue and able to provision successfully
