### ISSUE TITLE
ibm_is_instance: updating user_data forces a reprovision

### ISSUE THREAD

**Issue by willholley** [IBM-Cloud/terraform-provider-ibm#3092]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_is_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
locals {
  user_data = yamlencode({
    "ssh_authorized_keys" : [
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKVmnMOlHKcZK8tpt3MP1lqOLAcqcJzhsvJcjscgVERRN7/9484SOBJ3HSKxxNG5JN8owAjy5f9yYwcUg+JaUVuytn5Pv3aeYROHGGg+5G346xaq3DAwX6Y5ykr2fvjObgncQBnuU5KHWCECO/4h8uWuwh/kfniXPVjFToc+gnkqA+3RKpAecZhFXwfalQ9mMuYGFxn+fwn8cYEApsJbsEmb0iJwPiZ5hjFC8wREuiTlhPHDgkBLOiycd20op2nXzDbHfCHInquEe/gYxEitALONxm0swBOwJZwlTDOB7C6y2dzlrtxr1L59m7pCkWI4EtTRLvleehBoj3u7jB4usR"
    ]
  })
}

resource "ibm_is_vpc" "testacc_vpc" {
  name = "testvpc"
}

resource "ibm_is_subnet" "testacc_subnet" {
  name            = "testsubnet"
  vpc             = ibm_is_vpc.testacc_vpc.id
  zone            = "us-south-1"
  ipv4_cidr_block = "10.240.0.0/24"
}

resource "ibm_is_instance" "testacc_instance" {
  name    = "testinstance"
  image   = "7eb4e35b-4257-56f8-d7da-326d85452591"
  profile = "bc1-2x8"

  boot_volume {
    encryption = "crn:v1:bluemix:public:kms:us-south:a/dffc98a0f1f0f95f6613b3b752286b87:e4a29d1a-2ef0-42a6-8fd2-350deb1c647e:key:5437653b-c4b1-447f-9646-b2a2a4cd6179"
  }

  primary_network_interface {
    subnet = ibm_is_subnet.testacc_subnet.id
    primary_ipv4_address = "10.240.0.6"
    allow_ip_spoofing = true
  }

  network_interfaces {
    name   = "eth1"
    subnet = ibm_is_subnet.testacc_subnet.id
    allow_ip_spoofing = false
  }

  vpc  = ibm_is_vpc.testacc_vpc.id
  zone = "us-south-1"
  user_data = local.user_data
}
```

### Expected Behavior

`user_data` contains configuration for cloud-init modules. cloud-init modules support [different lifecycles](https://cloudinit.readthedocs.io/en/latest/topics/events.html) - some data is processed on first boot, some on every boot etc. The semantics of the configuration lifecycle cannot be determined by the Terraform provider.

I'd expect changing `user_data` *not* to force a VSI to be recreated - as a user, I have other mechanisms in Terraform that allow me to force recreation if I need it.

### Actual Behavior

The current behaviour of the `user_data` attribute in `ibm_is_instance` forces an instance to be reprovisioned if the attribute value changes. This is unexpected, both because it prevents user_data being used to inject data that, as a consumer, I know will only be processed on first boot (e.g. single-use SSH keys), and also it prevents the use of user-data to inject configuration that may be processed on a different lifecycle e.g. on VSI restart.

### Steps to Reproduce

1. `terraform apply` the above configuration
2. remove the SSH authorized keys from the user-data and `terraform apply`. I would not expect this to recreate the VSI instance.

**Comment by astha-jain** [comment]
This is correct behavior. User data is not supposed to change after a VSI is provisioned. Hence when terraform notices change in user data, the behavior is to delete the previous VSI and create a fresh one with the user data provided.

**Comment by willholley** [comment]
@astha-jain it seems like there's an inconsistency there: if user-data only applies on first boot then it should be possible to ignore user-data changes after the initial provision. For example, my use case is that I want to have Terrafirn render the `user-data` string for a VSI using a variable that changes over time. I don't want the provider to force existing VSIs to be reprovisioned every time this variable changes given it only applies on first boot - I can do this myself if that's the behaviour I require. Terraform [specifically call this out as a use case for taints](https://www.terraform.io/docs/cli/state/taint.html).

As mentioned above, some `cloud-init` modules also allow `user_data` to [change over time](https://cloudinit.readthedocs.io/en/latest/topics/events.html) (e.g. `BOOT_NEW_INSTANCE` vs `BOOT`) and the current behaviour breaks this.

**Comment by astha-jain** [comment]
Hello there @willholley. Terraform provider's lifecycle meta-argument `ignore_changes` will work great for this scenario. 
https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes

**Comment by willholley** [comment]
thanks @astha-jain - I'll try that as a workaround and report back

**Comment by willholley** [comment]
@astha-jain this solution with `ignore_changes` works for us - thanks for suggesting it.
