### ISSUE TITLE
target in data.ibm_is_virtual_endpoint_gateway is null

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
$ terraform -v
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.31.0
```

### Affected Resource(s)

data.ibm_is_virtual_endpoint_gateway

### Expected Behavior

Based on https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_virtual_endpoint_gateway the target should have been returned

### Actual Behavior

Target is shown as follows in tfstate:

`"target": null,`

### Steps to Reproduce

1. Create VPC with subnets
2. Create COS service
3. Create VPE gateway to COS service
4. Retrieve data about 1-3 using TF

**Comment by astha-jain** [comment]
@kavya498 could you help close this item please?
