### ISSUE TITLE
Terraform provider does not support Trusted Profiles

### ISSUE THREAD

**Issue by andrewferrier** [IBM-Cloud/terraform-provider-ibm#3099]
### Description

Terraform provider does not support Trusted Profiles: https://cloud.ibm.com/docs/account?topic=account-create-trusted-profile&interface=ui#create-profile-compute-ui

**Comment by hkantare** [comment]
The support for IAM trusted profiles is in development by IAM team..

**Comment by hkantare** [comment]
Its avaialble in latest releases
