### ISSUE TITLE
Ability to provide IP address for provisioning Power Systems using ibm_pi_instance resource

### ISSUE THREAD

**Issue by deshmuk1** [IBM-Cloud/terraform-provider-ibm#3102]
Hi,

ibm_pi_instance terraform resource is missing the ability to provide the IP address for the Power Systems VSI. There is client who is looking for the same. Request if this could be implemented.

**Comment by surajsub** [comment]
are you looking to pass ip as input to the terraform resource  ?

**Comment by rmoralesjr** [comment]
We are looking into your request to pass in an IP address to associate with the instance along with the network identifier.

**Comment by pbfinley1911** [comment]
The enhancement has been merged (and made available).  Thanks
