### ISSUE TITLE
ibm_is_vpc_address_prefix not accepting is_default argument

### ISSUE THREAD

**Issue by maximiano86** [IBM-Cloud/terraform-provider-ibm#3104]
We want to create a ibm_is_vpc_address_prefix with a default prefix but is not accepting the value `is_default` as stated in the documentation: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc_address_prefix#is_default

resource sample is:

```
resource "ibm_is_vpc_address_prefix" "basic-networking-prefix" {
  name  = "basic-networking-prefix"
  zone  = var.availability-zone
  vpc   = ibm_is_vpc.basic-networking-vpc.id
  cidr  = var.address-prefix1
  is_default = true
}
```

error is:

```
│ Error: Unsupported argument
│
│   on networking.tf line 12, in resource "ibm_is_vpc_address_prefix" "basic-networking-prefix":
│   12:   is_default = true
│
│ An argument named "is_default" is not expected here.
```

please advised

**Comment by astha-jain** [comment]
Looking into it

**Comment by maximiano86** [comment]
my bad upgrading from provider version 1.24.0 -> 1.32.0 helped, thanks for looking into it
