### ISSUE TITLE
tf fails when there are two clusters with same name

### ISSUE THREAD

**Issue by ac427** [IBM-Cloud/terraform-provider-ibm#3113]
```
data "ibm_container_cluster" "foo" {
  cluster_name_id = "xxxxx"
}

resource "ibm_iam_service_policy" "foo-policy" {
  iam_service_id = ibm_iam_service_id.foo_service_id.id
  roles          = ["Viewer"]
  resources {
    service              = "containers-kubernetes"
    resource_instance_id = data.ibm_container_cluster.foo.id
  }
}

```
When I use above code it asks to use name, but we have two clusters with same name in different regions. It also fails when I give region and name combination. region is also deprecated filed. Are there any options other than renaming the clusters? If IBM cloud is allowing to use same name, probably provider should consider that too :) 

```
Warning: Argument is deprecated

  on modules/services/main.tf line 2, in data "ibm_container_cluster" "foo":

   2:   cluster_name_id = "xxxx"

use name instead
```

**Comment by kavya498** [comment]
@ac427 , what is the error?

By seeing log that you provided, it looks like a warning..
```
data "ibm_container_cluster" "foo" {
  cluster_name_id = "xxxxx"
}
```
to 

```
data "ibm_container_cluster" "foo" {
  name = "xxxxx"
}
```

**Comment by kavya498** [comment]
Closing this issue as it has been inactive...This helps maintainers find and focus on the active issues.

If you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thanks!
