### ISSUE TITLE
ibm_resource_key doc nests arguments beneath parameters incorrectly

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3120]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/resource_key

The indentation indicates that parameters like `role` are children of `parameters` but in the example this is not the case.

![image](https://user-images.githubusercontent.com/6932057/133833210-fb1263f9-09d9-4f84-a107-369637b2d566.png)

**Comment by powellquiring** [comment]
Is service-endpoints = "private" a child of parameters?  If so that would seem odd, since parameters are parameters to 'pass to the resource' but the service-endpoint is the path to get to the resource.

**Comment by kavya498** [comment]
We ll fix the doc..
`service-endpoints = "private"` It is a child argument of parameter according to the API.. I believe we are following the same in terraform as well

**Comment by hkantare** [comment]
Fixed in latest docs
