### ISSUE TITLE
ibm_is_lb_pool_member member weight is not working as expected when weight is 0

### ISSUE THREAD

**Issue by anamikaagrawal123** [IBM-Cloud/terraform-provider-ibm#3124]
Terraform required version is : => 0.13
provider.ibm version = "1.30.2"
Affected Resource(s)

ibm_is_lb_pool_member
Expected Behaviour
- when a member is added with the weight 0 its expected to be added with weight 0.

Actual Behavior

It gets added with the weight 50. 
![Screenshot 2021-09-20 at 21 00 21](https://user-images.githubusercontent.com/78848657/134029664-a8d3f44d-93be-48f2-8129-c13e2eb0bf56.png)

Note with weight 100 ...  its working as expected. Only in case of 0 weight I am seeing this behaviour

**Comment by astha-jain** [comment]
Checking
