### ISSUE TITLE
How to set timeout values on ibm_app

### ISSUE THREAD

**Issue by blbird** [IBM-Cloud/terraform-provider-ibm#313]
Hello,

It takes time to run my application correctly. 

So, I need below timeout configuration on my manifest.yml

https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#timeout

However, I can not find to set this option on ibm_app. 

How can I set this option on ibm_app?

### Terraform Version
Terraform v0.11.7
terraform-provider-ibm v0.11.0

### Affected Resource(s)
- ibm_app

### Terraform Configuration Files
resource "ibm_app_route" "route" {
  domain_guid = "${data.ibm_app_domain_shared.domain.id}"
  space_guid  = "${data.ibm_space.space.id}"
  host        = "${uuid()}"
}

resource "ibm_app" "app" {
  depends_on        = ["ibm_app_route.route"]
  name              = "test_app"
  space_guid        = "${data.ibm_space.space.id}"
  app_path          = "app/defaultServer.zip"
  wait_time_minutes = 20
  buildpack         = "liberty-for-java"
  memory            = 512
  instances         = 1
  disk_quota        = 1024
  route_guid        = ["${ibm_app_route.route.id}"]
}

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Not failed.

### Actual Behavior
Sometimes failed.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
N/A

### References
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#timeout

**Comment by sakshiag** [comment]
@blbird : you can increase the value for "wait_time_minutes".. It defines the wait time for the app to be in a running state.

**Comment by blbird** [comment]
@sakshiag I think timeout on manifest.yml is slightly different from wait_time_minutes. If the app is not running within health check timeout, ibm cloud kills the apps. And I think that wait_time_minutes means waiting time on terraform.  Does it wrong? 
My problem which I think is like below: 
1. terraform-provider-ibm tries to deploy my application.
2. Ibm cloud detects that my application is not running within health check timeout and kills my application.
3. Ibm cloud re-tries to run my application. 
4. After all, terraform-provider-ibm fails to deploy my application after wait_time_minutes.

**Comment by sakshiag** [comment]
@blbird: Can you please attach the detailed logs by exporting TF_LOG=DEBUG.And the sample application which you are trying to deploy.

**Comment by sakshiag** [comment]
@blbird : I guess some issue with the app. In the app logs, It is trying to create the container and trying to perform the health check on container for 1m.. as it fails with the crashed state.. it again tries to create the container and perform the same check. In the terraform logs, after the mentioned wait timeout it will exit with the error saying instance is not in the running state.
Error: The manifest class path jaxb-api.jar can not be found in jar file file:/home/vcap/app/wlp/usr/servers/defaultServer/apps/KITT-API.war/WEB-INF/lib/jaxb-impl-2.2.1.1.jar or its parent due to which app instance is always in the crashed state.

**Comment by blbird** [comment]
@sakshiag As I said on previous comment, it takes more time than 1 minutes to run properly. So I added "timeout" attribute to manifest.yml during deploying with cf command. As you can see the reference document (https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#timeout), this attribute increases the time for health check.

**Comment by sakshiag** [comment]
@blbird : You need to increase the container health check time .. Surely, we will look into this and let you know..

**Comment by blbird** [comment]
@sakshiag Yes. That is what I want.

**Comment by hkantare** [comment]
The support for health check attributes are added in v0.11.3(health_check_timeout,health_check_type,health_check_http_endpoint)..Can you test with latest release  https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.3
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.3

**Comment by blbird** [comment]
@hkantare Ok. I will try to test that.

**Comment by blbird** [comment]
It works well.
