### ISSUE TITLE
HIGH PRIORITY: potential security vulnerabilities

### ISSUE THREAD

**Issue by kavya498** [IBM-Cloud/terraform-provider-ibm#3150]
Remove `github.com/IBM/go-sdk-core/v4` from the provider repo
Looks like API Gateway, CIS, VPC, satellite_endpoint resource are using `github.com/IBM/go-sdk-core/v4`

Direct and indirect dependencies of `go-sdk-code/v4` should be completely removed from these services..

**Comment by kavya498** [comment]
@MalarvizhiK , @astha-jain , Please make sure dependencies are removed from CIS and VPC services respectively both from provider and from SDK on a high priority..

**Comment by astha-jain** [comment]
VPC is not using `go-sdk-code/v4`.

**Comment by hkantare** [comment]
closing the issue
