### ISSUE TITLE
Add retry around delete resource group

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#3165]
Sometimes calls to the IBM Cloud backend can fail, but are succesfull on retry. For example, the below request to delete a resource group:

```
TestTerraformOcpLogin 2021-10-01T07:42:26Z logger.go:66: ╷
TestTerraformOcpLogin 2021-10-01T07:42:26Z logger.go:66: │ Error: Error Deleting resource group: Unexpected HTTP status code 500 (500 Internal Server Error) with responce code  null
TestTerraformOcpLogin 2021-10-01T07:42:26Z logger.go:66: │ 
TestTerraformOcpLogin 2021-10-01T07:42:26Z logger.go:66: │ 
TestTerraformOcpLogin 2021-10-01T07:42:26Z logger.go:66: │ 
TestTerraformOcpLogin 2021-10-01T07:42:26Z logger.go:66: ╵
TestTerraformOcpLogin 2021-10-01T07:42:26Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: Error Deleting resource group: Unexpected HTTP status code 500 (500 Internal Server Error) with responce code  null
│ 
```

Could we add a retry to the code? I would be happy to attempt to contribute here. Would I be correct in thinking the correct place to add the retry would be in the `resourceIBMResourceGroupDelete` function -> https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_resource_group.go#L207-L230

**Comment by kavya498** [comment]
@ocofaigh, How do iam_access_group effect in deletion of a resource_group?

**Comment by ocofaigh** [comment]
Ah sorry, I pasted the wrong function - I guess `resourceIBMResourceGroupDelete` deletes resource groups right (description updated)?

**Comment by kavya498** [comment]
@ocofaigh ,
Do you know what is the reason for rc 500?

**Comment by kavya498** [comment]
I believe SDK is already handling 5xx errors and it retries for 10 times by default..

**Comment by ocofaigh** [comment]
I do not know what the reason was for 500 error - I just know that after terraform hit the error, I manually logged into the UI and successfully delete the resource group. It was probably some backend glitch at the time terraform was running.
Is there an exponential backoff between retires?

**Comment by kavya498** [comment]
@ocofaigh , I think it is not issue related to provider..
It is an API error.. Did you see this issue again?
Thanks..

**Comment by ocofaigh** [comment]
@kavya498 Which api is returning the error? I checked with BSS, and they said they do not see the transaction ids on their end

**Comment by kavya498** [comment]
@ocofaigh ,
They are [resource manager APIs](https://cloud.ibm.com/apidocs/resource-controller/resource-manager#delete-resource-group)

**Comment by ocofaigh** [comment]
Ah sorry @kavya498 I thought this was a different issue - I thought we were talking about https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3426

As for this issue, I believe this occurs when resources have been deleted, but are not fully cleaned up in the backend, and so the resource group cannot be deleted yet. The only thing we could do here is maybe add more retries, or a longer backoff period?

**Comment by ocofaigh** [comment]
Hi @kavya498 It seems recently, resource group deletion fails very frequently with a 500. I believe this is due to a delay in backend deletion of resources in the resource group being deleted. This is the error we see:

```
│ Error: Error Deleting resource group: Resource Group with instance cannot be deleted with response code  {
│     "StatusCode": 500,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store"
│         ],
│         "Content-Length": [
│             "114"
│         ],
│         "Content-Type": [
│             "application/json; charset=utf-8"
│         ],
│         "Date": [
│             "Mon, 28 Feb 2022 13:56:49 GMT"
│         ],
│         "Etag": [
│             "W/\"72-EyDE9Qx2O5Iz+DHdukyRrhu3sa8\""
│         ],
│         "Expires": [
│             "Mon, 28 Feb 2022 13:56:49 GMT"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Server": [
│             "istio-envoy"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000; includeSubDomains"
│         ],
│         "Transaction-Id": [
│             "21749253421"
│         ],
│         "Vary": [
│             "Accept-Encoding"
│         ],
│         "X-Envoy-Upstream-Service-Time": [
│             "11357"
│         ],
│         "X-Request-Id": [
│             "21749253421"
│         ],
│         "X-Response-Time": [
│             "11354.469ms"
│         ],
│         "_request_id": [
│             "21749253421"
│         ]
│     },
│     "Result": {
│         "errors": [
│             {
│                 "code": "NOT_EMPTY",
│                 "message": "Resource Group with instance cannot be deleted"
│             }
│         ],
│         "trace": "21749253421"
│     },
│     "RawResult": null
│ }
│ 
│ 
│ 
╵}
```

Usually if I wait another minute or two, I can delete the resource group. Is it possible we can maybe add more retries here? From the logs, it looks like it stops retrying after 2mins: `TestDefaultExample 2022-02-28T13:56:45Z logger.go:66: module.resource_group.ibm_resource_group.resource_group[0]: Still destroying... [id=c4bbf8b825224fe4b1eaec69d9bcd42a, 1m20s elapsed]`
Could we extend this to more?

**Comment by ocofaigh** [comment]
We are seeing this very often today. Probably some slowness in IBM Cloud. Can we add more retires here?

**Comment by ocofaigh** [comment]
After speaking with the BSS team, I found out that they recently added a fix to resource group deletion that prevents resource groups from being deleted when resources have been deleted from it, but are pending reclamation. And the default period for pending reclamation is 7 days. Hence why resource group deletion had been failing for the past few days.

After some discussions, the BSS team agreed to revert the change, so this is no longer an issue. They are now going to consider options to re-introduce the fix, but with more flexible options. One suggestion was to provider a "force" flag that could be used if you don't care about pending reclamation.

Going to close this issue, as retires would of never worked here, since the default period for pending reclamation is 7 days
