### ISSUE TITLE
Scale down the cpu of the postgres DB fails with the plan validation error

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#3168]
I have tried to scale down the CPU 3 per member to CPU shared
here schematics logs ws-ec002i000814-pg002i000608:

 2021/09/21 13:42:01 Terraform apply | ibm_database.database_instance: Refreshing state... [id=crn:v1:bluemix:public:databases-for-postgresql:eu-fr2:a/05b86f39c75942ca9a520d2b1f7e0bb9:02e5595b-2908-4f1d-9f34-aa4e711896b5::]
 2021/09/21 13:42:04 Terraform apply | 
 2021/09/21 13:42:04 Terraform apply | Error: members_cpu_allocation_count must be >= 6 and <= 56 in increments of 2
 2021/09/21 13:42:04 Terraform apply | 
 2021/09/21 13:42:04 Terraform apply |   on database.tf line 5, in resource "ibm_database" "database_instance":
 2021/09/21 13:42:04 Terraform apply |    5: resource "ibm_database" "database_instance" {
 2021/09/21 13:42:04 Terraform apply | 
 2021/09/21 13:42:04 Terraform apply | 
 2021/09/21 13:42:04 Terraform APPLY error: Terraform APPLY errorexit status 1
 2021/09/21 13:42:04 Could not execute action

**Comment by kavya498** [comment]
Closing this issue thanks..

**Comment by hkantare** [comment]
Its fixed and available in latest Terraform Proivder

**Comment by hkantare** [comment]
closing the issue
