### ISSUE TITLE
504 Errors While Deploying LPARs on PowerVS

### ISSUE THREAD

**Issue by mmarakov** [IBM-Cloud/terraform-provider-ibm#3178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

* Terraform Version: v1.0.5
* Terraform Provider Version: 1.33.1

### Affected Resource(s)

* ibm_pi_instance

### Terraform Configuration Files

I'm utilizing the OCP on PowerVS terraform from the below URL

[https://github.com/ocp-power-automation/ocp4-upi-powervs](https://github.com/ocp-power-automation/ocp4-upi-powervs)

### Debug Output

Full debug here: [https://gist.github.com/mmarakov/e779ce381c4a85fab57bcf8fc75f823c](https://gist.github.com/mmarakov/e779ce381c4a85fab57bcf8fc75f823c)

### Panic Output

```
Error: Failed to Get PVM Instance 6aa29573-28d0-46e3-b70d-d81914bd2539 :Get "https://lon.power-iaas.cloud.ibm.com/pcloud/v1/cloud-instances/98bdaa44-9166-48e6-903e-1d3b2e56f511/pvm-instances/6aa29573-28d0-46e3-b70d-d81914bd2539": context deadline exceeded

  with module.nodes.ibm_pi_instance.master[1],
  on modules/4_nodes/nodes.tf line 92, in resource "ibm_pi_instance" "master":
  92: resource "ibm_pi_instance" "master" {


Error: failed to provision Failed to Create PVM Instance :unknown error (status 504): {}

  with module.nodes.ibm_pi_instance.master[2],
  on modules/4_nodes/nodes.tf line 92, in resource "ibm_pi_instance" "master":
  92: resource "ibm_pi_instance" "master" {


Error: failed to provision Failed to Create PVM Instance :unknown error (status 504): {}

  with module.nodes.ibm_pi_instance.master[0],
  on modules/4_nodes/nodes.tf line 92, in resource "ibm_pi_instance" "master":
  92: resource "ibm_pi_instance" "master" {
```

### Expected Behavior

Terraform should've continued monitoring build status and queryed the LPARs

### Actual Behavior

PowerVS API returned 504 error causing Terraform to error out. This has happened in multiple PowerVS Regions. Sometimes it works. Other times it does not. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Reached out to #terraform-ibmcloud-users on IBM Slack. Was requested to open an Issue. [Relevant thread](https://my.slack.com/archives/C53NF5MB4/p1633354466410900)

**Comment by mmarakov** [comment]
We also get the occasional 404 errors from, but rerunning the Terraform usually gets through those

**Comment by cdhorn** [comment]
Shouldn't fixing this be as simple as increasing the HTTP timeout on the service broker?  The way Apache defaults to 60 seconds and you override it with the Timeout parameter in the httpd.conf? Or it is not as straight forward?

**Comment by yussufsh** [comment]
It is already 240 ATM.

**Comment by cdhorn** [comment]
Yeah that seems more than reasonable.

**Comment by cdhorn** [comment]
Along with these 504 errors we have been getting a large number of context deadline exceeded errors lately as well:

`Error: Failed to Get PVM Instance 7a9fef33-1789-41b6-92d0-ec2ecf9c6b01 :Get "https://tor.power-iaas.cloud.ibm.com/pcloud/v1/cloud-instances/27b2586f-8018-49e3-9d09-cc032a668f1e/pvm-instances/7a9fef33-1789-41b6-92d0-ec2ecf9c6b01": context deadline exceeded`

These timeouts are likely the same root cause with performance issue on the back end correct?

Note with these so far we find the resource is perfectly fine, but has been marked tainted on Terraform side. If we untaint it and refresh state we can then proceed without having Terraform destroy and recreate the resource.  Is it necessary to mark them tainted when this happens?

**Comment by yussufsh** [comment]
Read timeout set in the go client is 3 mins.. So anything above 3 mins would be deadline exceeded. So if we set it to 5 mins then it would return 504 for GET. The above variables are in a mess and is not used at right places. Once I get some time I will need to clean up and make proper use of these variables.

**Comment by lsmcfadden** [comment]
What was the final outcome?

**Comment by christopher-horn** [comment]
@yussufsh did you ever have a chance to try to add some retry logic around 504/502 errors on GETs? We are still seeing these on and off at times, sometimes worse than others, often depending on colo. Some weeks only a couple times, other weeks far more. I realize it would be a band aid that masks some performance issues on the back end, but it would greatly help reduce the amount of manual intervention with automated deployments to either import or delete resources before resuming the apply.

**Comment by clnperez** [comment]
@christopher-horn I came to find this ticket just so I could ask that question. :D it would be a huge help if we could have retry logic added to all the power vs API calls, as they do tend to fail quite often, and even the documentation says to just retry for some things, e.g. Cloud Connections: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-cloud-connections

---
When you perform multiple Cloud connection tasks, numerous actions within a task can time out. When the timeout occurs, the tasks are completed in the background and the changed status might not be reflected immediately. You can run the commands again and the status will be updated to complete.
---

**Comment by christopher-horn** [comment]
@clnperez I don't think you want to retry on everything.  I think adding for GET and just for 502/504 would help a lot though as when it is performing an action and polling for status that is when it is most likely to happen.  Retrying a POST or PUT can create problems if the first request did go through and processing started and you just didn't get a response as you could end up creating duplicate resources.

**Comment by clnperez** [comment]
good point. i suppose i didn't mean to retry the post/put, but to have some logic that checks its existence after, to see if the post really did fail. that's what we're seeing with cloud connection and vm creates quite a bit lately. they said they failed, but, they're created.

**Comment by yussufsh** [comment]
The problem with retry logic on POST/PUT even after checking for existence does not make sense here. This needs to be fixed at the backend with some kind of cache server across pods. There are too many permutations and combinations to take care of to avoid duplicate requests via automation, even with sleep and retry. On top of that, having `replicants` as an input (N no. of instances) will make the code complex.

The main issue is no response on timeout, we do not know what is the state of the last request and if the new request will be considered as fresh or conflict or success. The original request could take 5 or 10 mins, whereas the second request can be completed in say 3mins after even checking for existence.

I would also want the PowerVS TF team (@rmoralesjr @ChaseRun ) to get to the service team to understand if we can fix the backend to reduce such error, which I was told would be fixed later this year but is not a priority. Had also suggested the implementation of jobs framework which could be tracked via GET calls.

I can do some set of retries on the polling (only GET) logic if you want. I did not try it as initially was getting some push-back here.

**Comment by rmoralesjr** [comment]
The service broker team did many performance improvements to minimize the 504 errors.
