### ISSUE TITLE
RC api returning incorrect response when instance already exists

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#3187]
**Project Golden Eye**

IBM Cloud secrets-manager only allows one secrets manager instance per account by default. When you try to provision another one using terraform, you get back the following error:
```
╷
│ Error: Error when creating resource instance: Unexpected HTTP status code 503 (503 Service Unavailable) with resp code: null
│ 
│ 
│   with ibm_resource_instance.secrets_manager,
│   on main.tf line 18, in resource "ibm_resource_instance" "secrets_manager":
│   18: resource "ibm_resource_instance" "secrets_manager" {
│ 
╵
```

The secrets-manager team have said that this response does not come from secrets-manager. When I try in the UI, I get this:
![image](https://user-images.githubusercontent.com/29608224/136542417-31d84118-8dc6-46c3-9d71-9be7c11f5cf5.png)

Is this error message `Unexpected HTTP status code 503 (503 Service Unavailable) with resp code: null` coming from the ibm terraform provider? If so, can we not just return the same error as the secrets-manager api does?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
$ terraform -v
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.31.0
```

### Affected Resource(s)

* ibm_resource_instance.secrets_manager

### Terraform Configuration Files

```hcl
##################################################################
## Variables
##################################################################
variable "ibmcloud_api_key" {
  type        = string
  description = "The IBM Cloud API Token"
  sensitive   = true
}

variable "prefix" {
  type        = string
  description = "Prefix for name of all resource created by this example"
  default     = "temp-conall"
}

##################################################################
## Providers
##################################################################
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = "1.31.0"
    }
  }
}

##################################################################
## Create RG
##################################################################

resource "ibm_resource_group" "test_resource_group" {
  name     = "${var.prefix}-rg"
  quota_id = null
}

##################################################################
## Create Secrets Manager instance
##################################################################

resource "ibm_resource_instance" "secrets_manager" {
  name              = "${var.prefix}-sm-instance"
  service           = "secrets-manager"
  plan              = "lite"
  location          = "us-south"
  resource_group_id = ibm_resource_group.test_resource_group.id
  timeouts {
    create = "20m" // Extending provisioning time to 20 minutes
  }
}

```

### Debug Output

[sm-trace-log.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/7310605/sm-trace-log.txt)

### Expected Behavior

Correct response should be returned so user knows the root cause as to why provisioning failed.

### Actual Behavior

Unexpected HTTP status code 503 (503 Service Unavailable) with resp code: null

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kavya498** [comment]
@ocofaigh , After investigation, We found that SDK is not returning proper error response..
We ll take this to SDK team.. Thanks for identifying this issue..
