### ISSUE TITLE
How to create service alias for Event stream

### ISSUE THREAD

**Issue by Nibedita-Udvavisk** [IBM-Cloud/terraform-provider-ibm#3188]
I am using terraform for service & databases deployment.

I am able to create Event stream instance using terraform. We need service alias for Event stream to use in cloudfoundry application. But I didn't find how to create service alias using terraform.

Referred document:
https://github.com/ibm-messaging/event-streams-samples/blob/master/kafka-nodejs-console-sample/docs/CF_Standard_Enterprise_Plan.md

We have to run the following command to create an alias for event-stream:
ibmcloud resource service-alias-create <alias-name> --instance-name <eventstreams-service-instance-name>

When I'm creating databases-for-elastic-search instance using terraform, it automatically creates the service alias for elastic search instance. 

Terraform code for creating event stream:
resource "ibm_resource_instance" "event_stream_inp" {
  name              = "new_event_stream"
  service           = "messagehub"
  plan              = "standard" 
  location          = "eu-gb" 
  resource_group_id = data.ibm_resource_group.group.id
}

**Comment by kavya498** [comment]
Lets track this issue using [2760](https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2760)
Closing Issue

Thanks..
