### ISSUE TITLE
Order is missing the following category: “SRIOV Enabled” for Network gateway Appliances Error

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#319]
Terraform is failing for following configurations giving error:-

configurations:-
terraform apply -var 'ha=1' -var 'name=jgjhg' -var 'hostname=testing' -var 'domain=tess.com' -var 'datacenter=ams01' -var 'package_key_name=2U_NETWORK_GATEWAY_APPLIANCE_1O_GBPS' -var 'process_key_name=INTEL_INTEL_XEON_E52650_V4_2_20' -var 'memory=64' -var 'os_key_name=OS_VYATTA_5600_5_X_UP_TO_20GBPS_SUBSCRIPTION_EDITION_64_BIT' -var 'private_network_only=true' -var 'public_bandwidth=BANDWIDTH_0_GB_2' -var 'private_vlan_id=0' -var 'public_vlan_id=0' -var 'unbonded_network=false' -var 'redundant_network=false' -var 'network_speed=100' -var 'tcp_monitoring=false' -var 'ipv6_enabled=true' -var 'redundant_power_supply=true' -var 'tags=[]' -var 'disk_key_names=["HARD_DRIVE_1_00TB_SATA_II"]' -input=false -auto-approve

Not only for this configuration for any configuration its giving error through terraform that:
Order is missing the following category: “SRIOV Enabled”

Terraform doesn't support SRIOV_Enabled option for now .
Can you please take Look at it?

**Comment by M-Rushabh** [comment]
@hkantare  Can you please take a look at this ?

**Comment by hkantare** [comment]
We will look and get back..

**Comment by M-Rushabh** [comment]
@hkantare  Thank You

**Comment by Siobhan-Butler** [comment]
Is there an ETA for this fix as it is currently breaking the deployment of our Secure Perimeter code?

**Comment by hkantare** [comment]
Mostly End of next week we are planning for a release..

**Comment by Siobhan-Butler** [comment]
@hkantare Ok thank you. Please keep me updated as I will to re-validate our code with the latest release (including this fix).

**Comment by Siobhan-Butler** [comment]
@hkantare Any update on the latest release?

**Comment by hkantare** [comment]
We are planning to release on Monday

**Comment by Siobhan-Butler** [comment]
@hkantare ok, thanks. I presume this link will be updated once the release is available: https://github.com/IBM-Cloud/terraform-provider-ibm/releases?

**Comment by hkantare** [comment]
Yes .. The link will be updated with latest release..

**Comment by Siobhan-Butler** [comment]
Thank you!!

**Comment by hkantare** [comment]
Released v0.11.2 Please try with latest 
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.2

**Comment by Siobhan-Butler** [comment]
@hkantare Thank you. We will validate with the latest version.

**Comment by M-Rushabh** [comment]
Thank You @hkantare
