### ISSUE TITLE
security group examples need improvement

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3198]
Documentation problem:

Can not figure out how to attach security groups to instances and load balancers. Check out these two examples:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_security_group_network_interface_attachment
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface_sg_attachment

Expected: Examples with security group attachments to instance network interfaces and load balancers

AWS example:

![image](https://user-images.githubusercontent.com/6932057/137015921-0574e139-af4b-4abf-8342-26fd4d0a4b4b.png)

Actual: 
```
resource "ibm_is_security_group_network_interface_attachment" "sgnic" {
  security_group    = "2d364f0a-a870-42c3-a554-000001352417"
  network_interface = "6d6128aa-badc-45c4-bb0e-7c2c1c47be55"
}
```

This example is not realistic enough to be useful.

Check out the rest of the security group related pages and make sure they are meaningful.

**Comment by geethasathyamurthy** [comment]
@astha-jain 
Request to share with us the example that meets the examples with security group attachments to instance network interfaces and load balancers ask, so that, we could add the example in the registry docs.

Regards,
Geetha

**Comment by astha-jain** [comment]
We have identified such documentation fixes across VPC documentation and working on getting a PR out soon.

**Comment by geethasathyamurthy** [comment]
> We have identified such documentation fixes across VPC documentation and working on getting a PR out soon.

Thanks much for the confirmation, @astha-jain when is the tentative date for the PR to be out?
Regards,
Geetha

**Comment by hkantare** [comment]
All VPC examples are updated
