### ISSUE TITLE
Support lookup of Trusted Profile by name

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/iam_trusted_profile

only supports retrieving a trusted profile by its ID. But how do you find out the ID? Support lookups by names. Names are typically constructed for projects and are the natural way of looking up existing resources.

### New or Affected Resource(s)

data ibm_iam_trusted_profile

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by kavya498** [comment]
Available in latest release 1.37.0

Thanks
