### ISSUE TITLE
Documentation for data "ibm_iam_trusted_profile_policy" is wrong

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* data "ibm_iam_trusted_profile_policy
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/iam_trusted_profile_policy

The documentation is not describing the required attributes. What is iam_id? Why is the "either or" part of the iam_id attribute description? 
![image](https://user-images.githubusercontent.com/8414748/137121886-7dc30cac-c8cf-432c-a999-4256c9531878.png)

**Comment by kavya498** [comment]
@data-henrik ,

iam_id and profile_id conflicts with each other.. 
User has to either provide `iam_id` or `profile_id` we shall elaborate docs..

IAM Id looks like `iam-Profile-XXX`
while profile id looks like `Profile-XXX`

**Comment by data-henrik** [comment]
The "either or" should be above the two (profile_id / iam_id) or part of both descriptions.
