### ISSUE TITLE
Container cluster creation should work with no VLANs specified

### ISSUE THREAD

**Issue by guyos** [IBM-Cloud/terraform-provider-ibm#321]
Failing to create a cluster when public and private vlan id are not specified and private and public vlans already exist in the zone to create the cluster in.
This should work - and it does work by using the command
`ibmcloud cs cluster-create`

### Terraform Version
Terraform v0.11.7
IBM provide 0.11.1

### Affected Resource(s)
- ibm_container_cluster

### Terraform Configuration Files

```hcl
provider "ibm" {
  bluemix_api_key = "${var.ibm_bx_api_key}"
  region          = "${var.region}"
}

# define IBM Cloud Kubernetes Service cluster
resource "ibm_container_cluster" "iks_cluster" {
  name            = "${var.cluster_name}"
  datacenter      = "${var.datacenter}"
  machine_type    = "${var.machine_type}"
  hardware        = "${var.hardware}"
  public_vlan_id  = "${var.public_vlan_id}"
  private_vlan_id = "${var.private_vlan_id}"
  subnet_id       = []
  worker_num      = "${var.worker_num}"
}
```

### Debug Output
https://gist.github.com/guyos/c55fa9a7fc349606b7acb1fec3bf2b91

### Expected Behavior
I did not specify private and public vlan ids nor subnet_id. datacenter and machine_type have been specified.
According to documentation - if you dont specify these values, VLANs will be created for you.
BTW - I did have existing VLANs in the location
In a location without VLANs the plan works!

```bash
ibmcloud cs cluster-create -h
   --public-vlan value     Conditional: Specify the ID of the public VLAN. To see available VLANs, run 'bx cs vlans --zone <zone name>'. If you do not have a public VLAN yet, do not specify this option because one will be automatically created for you.
```

### Actual Behavior
I received an error:
* ibm_container_cluster.iks_cluster: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"1e06749e-4a33-4456-a756-f595f3512488","code":"E0020","description":"To create a standard cluster, you must specify values for location, machine type, public VLAN, and private VLAN. To create a free cluster, specify cluster name only.","type":"Provisioning"}

### Steps to Reproduce
1. `terraform apply`

**Comment by Praveengostu** [comment]
HI @guyos We will check this and get back to you

**Comment by guyos** [comment]
Looking further into this, looks like the Console will retrieve existing VLANs in a zone and use them - so through the console no new VLANs will be created if they already exist.
I tried the CLI again (new version) and it fails with the same error mentioned above.
I guess this issue should be directed at the Container Service.
And hence closing
