### ISSUE TITLE
Intermittently ibm_container_vpc_cluster fails saying: "A cluster with the same name already exists"

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#3213]
**Internal Project Golden Eye**

We have noticed that intermittently (but not very frequently), when creating a cluster using `ibm_container_vpc_cluster` the IKS api responds with `Error: Request failed with status code: 409, ServerErrorResponse: {"incidentID":"1a1240b1-c05e-481d-90f4-eefdb89a03b0,1a1240b1-c05e-481d-90f4-eefdb89a03b0","code":"E0007","description":"A cluster with the same name already exists. Choose another name.","type":"Provisioning"}`

Any time this has happened, we have logged in and checked for a cluster with that name. In every case, we have found that actually the `ibm_container_vpc_cluster` did successfully create the cluster! And the timestamp matches the timestamp in the logs. So why is IKS api failing with that error?

We reproduced the issue with trace logs, but to be honest I am struggling to see what the root cause is. Is it possible that somewhere in the provider code, a process to provision the cluster was kicked off, but due to some glitch, it was kicked off a second time, and so ended up with the IKS api response to say cluster with that name already exists?

Here is a screenshot which shows the creation time of the cluster (in UTC +1 time) - 12.04pm:
![image](https://user-images.githubusercontent.com/29608224/137304038-f9c99081-d446-4c73-a883-f1908d8364fb.png)

And below I have attached the logs (including trace log) which show the timestamp matches the cluster creation (these logs are in UTC time):
```
TestOCPSMBasic/TestOCPSMBasic_0 2021-10-13T11:04:11Z logger.go:66: [0m[1mibm_container_vpc_cluster.cluster: Creating...[0m[0m
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.34.0

### Affected Resource(s)

* ibm_container_vpc_cluster

### Terraform Configuration Files

Internal url: https://github.ibm.com/GoldenEye/ocp-service-mesh-module/tree/master/examples/basic

### Debug Output
[stdout.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/7345395/stdout.txt)
[trace.log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/7345396/trace.log)

### Expected Behavior

api should not fail if cluster provisioning passed

### Actual Behavior

api response saying cluster already exists

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ocofaigh** [comment]
Going to try and reproduce with version 1.36.0 which now prints API trace calls. This may help us determine what is going on here

**Comment by ocofaigh** [comment]
@kavya498 I have reproduced the issue on `1.36.0`. See logs and details at internal url https://github.ibm.com/GoldenEye/issues/issues/316#issuecomment-38433092

**Comment by ocofaigh** [comment]
@kavya498 The IKS team took a look at this, and they replied with the following:

> I found the provided incident ID (`e9aa2cb9-926f-436c-a4eb-8916544d1ba4` - which was the 409 result) in our backend logs. (As expected it was a 409.) I used those logs to find that the cluster was named `mcluster-x8d8rx-cluster-1`, and then searched for earlier attempts to create such a cluster. I found one immediately before (request ID `075a3bac-15cb-4d38-b1ff-1f41a94c377e`) with a 201 response.
> 
> The 409 was at "2021-12-06T12:08:09.722Z"  and the 201 was at "2021-12-06T12:07:14.661Z". 
> 
> It seems that the clusters are getting created successfully but the response fails to reach the client (network error, timeout, etc.), so it assumes that the request failed, causing it to retry. Because the original request did successfully create the cluster and cluster names must be unique within a region and resource group, the retry fails.
> 
> I'm unfamiliar with GoldenEye, is it for terraform issues? If they wanted to prevent this in the future, perhaps they could, in the event of a timeout, do a `cluster get --cluster NAME` and if the result isn't 404 then consider it created by the prior timed out request?

Is that something that could be added to the provider code before retrying?

**Comment by ocofaigh** [comment]
Hi folks,

Over the past 2 days we have been hitting this issue ALOT. We have been doing some internal investigation, and actually found that at the moment, the IKS api to provision a cluster is returning a 500 HOWEVER the cluster itself continous to provision in the background. So my guess is that when IKS api is retuning a 500, the provider is retrying, but since the cluster is actually being provisioned, we see the error `A cluster with the same name already exists.`

Unless I am missing it, I cannot see any evidence of this retry in the provider trace logs though. Is it possible the retry is happening silently and not being logged?

[ocp-console-patch-module-test-logs-220308-060652.tar.gz](https://github.com/IBM-Cloud/terraform-provider-ibm/files/8205646/ocp-console-patch-module-test-logs-220308-060652.tar.gz)

Here is what we got with the api directly:
```
{
  "incidentID": "8d10d1bc-e585-4995-9aa5-2c044ff55dc3",
  "code": "G0002",
  "description": "An internal error occurred while processing your request.",
  "type": "General"
}
```

In saying all this, this kind of proves that the issue here is that IKS is returning a 500, but the cluster continues to actually provision. I have an issue open with IKS on this, but it would be great if we could prove that the provider is actually retrying by logging the 500 it got before attempting retry?

**Comment by ocofaigh** [comment]
Infact, someone from my team was able to reproduce this and track the calls using a proxy to confirm that indeed a 500 response was returned when calling `/v2/vpc/createCluster` and the provider retried, and then it produced the 409. See his findings below:


**SUMMARY**: 500 error returned from initial POST to create cluster, then same POST happens 2nd time  (a retry maybe inside provider?) and that returns with 409 "name already in use". Regardless of the errors, the cluster DID get created.

**GUESS?**: perhaps the initial create was actually successful in creating the cluster but somehow resulted in 500 error before returning, then when provider tries 2nd time the cluster name is already in use?

**SOME DETAILS** (taken from an example run while tracing calls):

POST https://containers.cloud.ibm.com/global/v2/vpc/createCluster
```
First request byte:	2022-03-07 14:50:47.454
Response complete:	2022-03-07 14:51:08.783(21s)
Response: 500
{
    "code": "G0002",
    "description": "An internal error occurred while processing your request.",
    "incidentID": "4dd2427a-0dc9-46a4-8ff9-606cafce0518",
    "type": "General"
}
```

Second cluster request: POST https://containers.cloud.ibm.com/global/v2/vpc/createCluster
```
First request byte:	2022-03-07 14:51:13.835
Response complete:	2022-03-07 14:51:21.377(8s)
Response: 409
{
    "code": "E0007",
    "description": "A cluster with the same name already exists. Choose another name.",
    "incidentID": "a45761fa-2f9e-44cd-9867-35dad35d03d6",
    "type": "Provisioning"
}
```

**Comment by chris0030** [comment]
We're having this same issue with IBM. The cluster deletes successfully, and then the next day when we run `terraform apply`, we're getting "A cluster with the same name already exists" and then the cluster spins up.

**Comment by kavya498** [comment]
@ocofaigh, 
Yes, provider retries on 5xx errors but it is not possible for the retry to happen silently and not being logged..
It is very strange that I don't see first POST call as well in the logs..

However, API should not have thrown 500 when it is actually creating a cluster..

I ll check on why is provider unable to log IKS API traces in the logs..

**Comment by kavya498** [comment]
@ocofaigh , It could be a logger issue on our SDK which is why you are unable to see trace logs for kubernetes resources..
I believe it is been fixed [here](https://github.com/IBM-Cloud/bluemix-go/commit/2af2dee48688a19a5953063c2bac2d4fd6dc4646) and is available in 1.38.2 provider release..

But I can confirm you that provider does retry when it gets 5xx response codes..

**Comment by ocofaigh** [comment]
Thanks for confirming this. We will update our provider version to a newer version so that we get correct logging. 
I am working with IKS to find out the root cause of the 500. I don't think that any changes are needed from the provider side - IKS need to ensure that the cluster provisioning process does not proceed if it returns a 500 response.

**Comment by ocofaigh** [comment]
@kavya498 Just as an FYI, when we set `max_retries = 0` we no longer get the 409 error. We actually get the 500 error:
```
╷
│ Error: Request failed with status code: 500, ServerErrorResponse: {"incidentID":"9abec5ec-8f66-492b-9220-98d6acd7b1e2","code":"G0002","description":"An internal error occurred while processing your request.","type":"General"}
│ 
│   with module.ocp_base.ibm_container_vpc_cluster.cluster[0],
│   on .terraform/modules/ocp_base/main.tf line 55, in resource "ibm_container_vpc_cluster" "cluster":
│   55: resource "ibm_container_vpc_cluster" "cluster" {
│ 
```

So just some proof that a) the provider is doing the retry, b) IKS is returning a 500, c) IKS is continuing with cluster provisioning even after returning 500

**Comment by ocofaigh** [comment]
@chris0030 Thanks for confirming this - I am glad it is not just us! I have an internal issue open with IKS on this. Hoping to have an update later

**Comment by daniel-butler-irl** [comment]
I have also hit this issue...

**Comment by ocofaigh** [comment]
Just to clarify, the issue is with IKS (tracking in [internal IKS issue](https://github.ibm.com/alchemy-containers/armada-ironsides/issues/4275)), not with the provider. The provider is retrying on 500 and is making the assumption that the cluster provisioning process has not started. 
Perhaps more advanced logic could be added to the provider to identify such a case, and produce a better error message, but kind of hoping that won't be needed an IKS permanent fix comes soon

**Comment by chris0030** [comment]
It may still require a provider change I suppose if IBM has made changes to their API or broken something.

We have an open ticket with IBM as well, will update here if relevant

**Comment by hkantare** [comment]
We have an open issue from IKS API side and its tracked using 
https://github.ibm.com/alchemy-containers/armada-ironsides/issues/4275

**Comment by ocofaigh** [comment]
The IKS team have fixed the issue in production. They reverted a change that went in on March 5th.

**Comment by hkantare** [comment]
closing the issue based on above comment

**Comment by ocofaigh** [comment]
Just a heads up that this error does still intermittently occur due to a separate IKS bug which is being tracked internally at https://github.ibm.com/alchemy-containers/armada-api/issues/3174
Not related to terraform, so no point in re-opening this issue.
