### ISSUE TITLE
ibm_container_vpc_cluster - ability to update workers one at a time or by worker pool

### ISSUE THREAD

**Issue by lmosca** [IBM-Cloud/terraform-provider-ibm#3214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the patch_version argument and update_all_workers argument let you update the workers of the cluster in all the cluster's worker pools all together. 
We would like to be able to update one node at a time and/or the nodes of a specific worker pool of the cluster

### New or Affected Resource(s)

* ibm_container_vpc_cluster
* ibm_container_vpc_worker_pool

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by hkantare** [comment]
After having with service team This is a limitation of the API behaviour for IKS and ROKS. We don't have the ability to orchestrate this in the control plane, the client would need to implement this orchestration.

So currently we can't support this via Terraform

**Comment by hkantare** [comment]
closing the issue
