### ISSUE TITLE
Wrong documentation for iam_trusted_profile_claim_rule

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3216]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/iam_trusted_profile_claim_rule

The syntax for conditions is wrong, it does not work.

```
resource "ibm_iam_trusted_profile_claim_rule" "iam_trusted_profile_claim_rule" {
  conditions = { "claim" : "claim", "operator" : "operator", "value" : "value" }
  profile_id = "profile_id"
  type = "type"
}
```

It should be something like this:

```
resource "ibm_iam_trusted_profile_claim_rule" "iam_trusted_profile_claim_rule" {
  conditions { 
     "claim" = "claim"
     "operator"= "operator"
     "value" = "value" 
  }
  profile_id = "profile_id"
  type = "type"
}

```

But what about a truly working e2e sample?

**Comment by kavya498** [comment]
@data-henrik ,
working example..
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/data_source_ibm_iam_trusted_profile_claim_rule_test.go#L88

**Comment by hkantare** [comment]
Fixed https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/iam_trusted_profile_claim_rule
