### ISSUE TITLE
Add links to App ID documentation

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3220]
for the template definition in https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/appid_cloud_directory_template, could you link from the resource docs to this?

https://cloud.ibm.com/docs/appid?topic=appid-cd-types#cd-messages

It would help in defining the templates

**Comment by hkantare** [comment]
Fixed in latest release documentation
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs
