### ISSUE TITLE
Is there is a way through the ibm_container_cluster Terraform resource to control the IPs on the COS bucket it creates?

### ISSUE THREAD

**Issue by aratichakravarti** [IBM-Cloud/terraform-provider-ibm#3236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

How we can use terraform resource to control the Ips of the COS bucket which gets created while IBM_container_cluster  is provisioned?

### New or Affected Resource(s)
ibm_Container_cluster 

### Dependant Resource(s)
COS bucket

* ibm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by hkantare** [comment]
closing the ticket
