### ISSUE TITLE
users losing access to resources

### ISSUE THREAD

**Issue by ac427** [IBM-Cloud/terraform-provider-ibm#3248]
ibm_iam_access_group_members is not applying changes properly. We see diff on every apply even when there are no changes. 
Also, some of the users are losing access because of the random case changes.
anyone with IBMid can view code/logs in https://travis.ibm.com/symposium/platform/

Right now we can't rely on TF to manage IBM resources as it is not producing the results as expected

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by hkantare** [comment]
We fixed some of issues from last couple of resources can you please try with latest release 1.36.0 and above

**Comment by hkantare** [comment]
closing the issue
