### ISSUE TITLE
Cannot create ibm_compute_user with IBM ID

### ISSUE THREAD

**Issue by ruben-burr** [IBM-Cloud/terraform-provider-ibm#325]
Hi there,

for my account I want to create a compute user that is already a user for the account. But just on the bluemix level, not softlayer. According the documentation the username property is optional for IBM ID users. The creation fails though with a message indicating that the username property is missing.

### Terraform Version
Terraform v0.11.7
+ provider.ibm v0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_compute_user

### Terraform Configuration Files
```hcl
resource "ibm_compute_user" "ruben-gmail" {
  address1     = "Dieselstraße 18/2"
  city         = "Echterdingen"
  company_name = "NovaTec Consulting GmbH"
  country      = "US"
  email        = "ruben.burr@googlemail.com"
  first_name   = "Ruben"
  last_name    = "Burr"
  has_api_key  = false

  permissions = [
    "ACCESS_ALL_GUEST",
    "ACCESS_ALL_HARDWARE",
    "SERVER_ADD",
    "SERVER_CANCEL",
    "RESET_PORTAL_PASSWORD",
  ]

  state    = "GA"
  timezone = "CET"
}
```

### Debug Output
ibm_compute_user.ruben-gmail: Error creating IBM Cloud User: SoftLayer_Exception_MissingCreationProperty: The property 'username' must be set to create an instance of 'SoftLayer_User_Customer_OpenIdConnect'. (HTTP 500)

### Expected Behavior
The compute user should have been created. 

### Actual Behavior
The compute user was not created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Greets, Ruben

**Comment by hkantare** [comment]
@ruben-burr I checked with softlayer API team they says username is required
```
As far as I know, the username has always been required for all user creation. I believe the username for OpenIdConnect needs to be the same as their email. 
Christopher Gallo
Senior API Developer

IBM Bluemix Infrastructure and Developer Services
315 Capitol St, Suite 205, Houston, TX 77002
281.714.4508 direct  |  cgallo@us.ibm.com
```
Can you please try by passing username and let us know . We will update doc accordingly.

**Comment by ruben-burr** [comment]
Thanks, @hkantare this worked for me. It would be nice, if you could update the docs.

**Comment by ruben-burr** [comment]
Is there a mapping of the permissions strings the terraform provider accepts and the checkboxes in the UI? My expectation would have been to find possible values in the softlayer api docs: https://softlayer.github.io/reference/datatypes/Permissions. But there is nothing behind this URL

**Comment by hkantare** [comment]
The link is broken.I raised a issue https://github.com/softlayer/softlayer.github.io/issues/118

**Comment by allmightyspiff** [comment]
https://softlayer.github.io/reference/datatypes/SoftLayer_User_Customer_CustomerPermission_Permission/ is the page you are looking for.  The whole list of services and datatypes that softlayer supports can be found here: https://softlayer.github.io/reference/softlayerapi/

**Comment by hkantare** [comment]
@ruben-burr You can use this API `https://api.softlayer.com/rest/v3/SoftLayer_User_Customer_CustomerPermission_Permission/getAllObjects/` to retrieve the possible values for permissions.

**Comment by ruben-burr** [comment]
Thanks @hkantare will try that as soon as time allows.

**Comment by hkantare** [comment]
closing the issue
