### ISSUE TITLE
Request detach and update feature in "lbaas_server_instance_attachment"

### ISSUE THREAD

**Issue by Najeongho** [IBM-Cloud/terraform-provider-ibm#326]
Hi there,

I need this feature. "detach and update server instances as loadbalancer members".
Because, I am developing auto scaling function.

However, since there is only attach function like below link, detach and update function are required.
  https://ibm-cloud.github.io/tf-ibm-docs/v0.11.1/r/lbaas_server_instance_attachment.html

For updates, it's likely to use weight changes.

I request updates and detachments feature that autoscaling can be done.

**Comment by Praveengostu** [comment]
Hi @Najeongho When you perform a terraform destroy on lbaas_server_instance_attachment it detaches the attached server instance. The update is already supported to update the `weight`.  Once the resource is created you can add/update the weight attribute and call the terraform apply to update it. Let me know if you need any more information.

**Comment by Najeongho** [comment]
I have verified the use of Terraform's update and destroy features, and I have tested and check that it works normally.

Thank you for your advice.

You can close this issue.
