### ISSUE TITLE
ibm_storage_block - does not support os_format_type of vmware

### ISSUE THREAD

**Issue by surajsub** [IBM-Cloud/terraform-provider-ibm#327]
IBM Provider version
- 0.11.1

### Terraform Version
0.11.7

### Affected Resource(s)
- ibm_storage_block

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
## Added the provider version

variable "datacenter" {
	description = "Target vSphere datacenter for Virtual Machine creation"
}


variable "iops" {
	description = "IOPS for the storage"
	
	
	}


variable "size" {
	description = "Size of the storage"
	
	
	}


provider ibm {
version="0.11.1"
} 

variable "ipToConnect" {
description="Host to connect"
type="list"
}


variable "os_format_type"
{
description="OS Format Type to Provide"
}





resource "ibm_storage_block" "cmas" {
        type = "Performance"
        datacenter = "${var.datacenter}"
        capacity = "${var.size}"
        iops = "${var.iops}"
        os_format_type = "${var.os_format_type}"
        allowed_ip_addresses =["${var.ipToConnect}"]
        
}

output "hostname" {
  value = "${ibm_storage_block.cmas.hostname}"
}
output "storageId" {
value = "${ibm_storage_block.cmas.id}"
}
output "volumename" {
  value = "${ibm_storage_block.cmas.volumename}"
}
output "allowed_host_info" {
  value = "${ibm_storage_block.cmas.allowed_host_info}"
}


```

### Debug Output
ibm_storage_block.cmas: No OS type found with name of vmware

### Panic Output
No Panic

### Expected Behavior
A storage block should be created 

### Actual Behavior
The provider fails with the message above

**Comment by hkantare** [comment]
It works the os_format_type value should match to name key field in https://api.softlayer.com/rest/v3/SoftLayer_Network_Storage_Iscsi_OS_Type/getAllObjects. We will update our documentation

**Comment by surajsub** [comment]
Thank you. Closing this.
