### ISSUE TITLE
Postgres configuration through terraform 

### ISSUE THREAD

**Issue by sflaherty2009** [IBM-Cloud/terraform-provider-ibm#3278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Currently, we are able to deploy Postgres instances through the ibm_database resource. However, many of the configuration options are unavailable to us.   We are currently trying to configure the max connections for our postgres instances which is a cli command tied to cdb 
https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-changing-configuration
```
ibmcloud cdb deployment-configuration agrotech-db-postgres-prod-us-south  '{"configuration":{"max_connections":1600}}'
```
However, this is not available through the ibmcloud terraform provider.  Along this same vein we also need to be able to set the logging abilities on the cluster which is not available due to the same limitation.

![image (1)](https://user-images.githubusercontent.com/17362081/139296597-f20658a5-7587-4692-acfb-322a4f28f144.png)
 

### New or Affected Resource(s)

* ibm_database

### References

* #0000

**Comment by kavya498** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1428

**Comment by sflaherty2009** [comment]
Do we have any idea when this work might be put into sprint? We need to determine if we need to work around this or if something will be available to us prior to moving into production.

**Comment by hkantare** [comment]
We will be planning to take up in next sprint and available in production release by mid of dec
