### ISSUE TITLE
Missing darwin_arm64 provider: Unable to use the provider on Apple's M1

### ISSUE THREAD

**Issue by lra** [IBM-Cloud/terraform-provider-ibm#3280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v1.0.10
on darwin_arm64
```

### Affected Resource(s)

All IBM resources

### Terraform Configuration Files

```hcl
provider "ibm" {
  region           = "us-south"
}
```

### Expected Behavior

Successful `terraform init`

### Actual Behavior

```
terraform init
[...]
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/ibm-cloud/ibm v1.34.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```

**Comment by kavya498** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2626

**Comment by lra** [comment]
Closing in favor of #2626
