### ISSUE TITLE
ibm_cloud_shell_account_settings issue

### ISSUE THREAD

**Issue by jpmonge86** [IBM-Cloud/terraform-provider-ibm#3289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
terraform -v
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/eiqops/restapi v1.15.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.35.0
```
### Affected Resource(s)

* ibm_cloud_shell_account_settings

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = ">= 1.35.0"
    }
  }
}


provider "ibm" {
    ibmcloud_api_key = var.cloud_api_key
   }


// Data source to get account settings
data "ibm_iam_account_settings" "iam_account_settings" {
}

// Data source to get shell settings
data "ibm_cloud_shell_account_settings" "cloud_shell_account_settings" {
  account_id = data.ibm_iam_account_settings.iam_account_settings.account_id
}

resource "ibm_cloud_shell_account_settings" "cloud_shell_account_settings" {
  rev = data.ibm_cloud_shell_account_settings.cloud_shell_account_settings.rev
  account_id = data.ibm_iam_account_settings.iam_account_settings.account_id
  enabled = false
}
```

### Debug Output

https://gist.github.com/jpmonge86/6895decd61ef326cb94f646c88e8143a

### Expected Behavior

Resource to be successfully applied

### Actual Behavior

Error output, my user is clearly associated with the account in question

{
    "total_results": 4,
    "limit": 100,
    "first_url": "/v2/accounts/5a5b9393966873091a0d13cd50dc40ad/users",
    "resources": [
        {
            "id": "ce6c27bd205bf859f1eec60724457aca",
            "iam_id": "IBMid-31000293CH",
            "realm": "IBMid",
            "user_id": "jpmonge@cr.ibm.com",
            "firstname": "Jose Pablo",
            "lastname": "Monge Bolanos",
            "state": "ACTIVE",
            "sub_state": "",
            "email": "jpmonge@cr.ibm.com",
            "phonenumber": "+506-2794-3353",
            "altphonenumber": " ",
            "photo": "https://cloud.ibm.com/avatar/v1/avatar/migrate-bluemix-photos-production/ ",
            "account_id": "5a5b9393966873091a0d13cd50dc40ad"
        },
     
    ]
}

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jpmonge86** [comment]
Hello,

Amy updates or comments about this issue?

Thanks,

Jose

**Comment by hkantare** [comment]
@hartyt Can you please look into the issue

**Comment by hartyt** [comment]
@jpmonge86 looks like a bug/regression was introduced in new version of the provider. If you use version 1.33.0 it will work
````
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = "= 1.33.0"
    }
  }
}
````

The complete code example would look like
````
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = "= 1.33.0"
    }
  }
}

// Data source to get account settings
data "ibm_iam_account_settings" "iam_account_settings" {
}

// Data source to get shell settings
data "ibm_cloud_shell_account_settings" "cloud_shell_account_settings" {
  account_id = data.ibm_iam_account_settings.iam_account_settings.account_id
}

resource "ibm_cloud_shell_account_settings" "cloud_shell_account_settings" {
  rev = data.ibm_cloud_shell_account_settings.cloud_shell_account_settings.rev
  account_id = data.ibm_iam_account_settings.iam_account_settings.account_id
  enabled = false
}
````

**Comment by hartyt** [comment]
I'll follow up with the provider team to fix the issue

**Comment by hartyt** [comment]
@kavya498 @hkantare looks like some recent changes to the [cloudshell datasource and resource](https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/ibm/service/cloudshell) might have introduced a bug, 

the datasource & provider work as expected using 
````
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = "= 1.33.0"
    }
  }
}
````

but fail using newer versions of the provider

**Comment by jpmonge86** [comment]
> I'll follow up with the provider team to fix the issue

Thanks @hartyt , I look forward to your update and/or the team's.

**Comment by mrgadgil** [comment]
@hartyt Any update on the issue? We need this module to add checks to Code Risk Analyzer as well as use the module would be great if you provide us a fix. Thank you

**Comment by hkantare** [comment]
We are looking into it ...Fix will be available in upcoming release

**Comment by jpmonge86** [comment]
@hkantare I saw your commits (7d6f7cc and b10a56e) tagged above, but I do not think these have been made available through a release yet, have they?

**Comment by kavya498** [comment]
@jpmonge86 ,It is not released yet..
Provider release is done on release branch..
Thanks

**Comment by jpmonge86** [comment]
@kavya498 I see this issue tagged in release [v1.39.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.39.0). Does this mean issue was fixed here?

**Comment by hkantare** [comment]
The issue is fixed in latest releases 1.39.1 and 1.39.0

**Comment by hartyt** [comment]
@hkantare thank you for fixing the issue, I was able to verify that it is now working.

**Comment by jpmonge86** [comment]
Thank you, tested it and  works ok
