### ISSUE TITLE
Container Bind Service fails to remove if the resource it is binding is already gone

### ISSUE THREAD

**Issue by pthongsavanh-ibm** [IBM-Cloud/terraform-provider-ibm#3293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Container bind service fails to remove if the resource that it is binding, in this case ibm_database redis, is removed before the binding is.

### Affected Resource(s)

`ibm_container_bind_service` when used with `ibm_database`, more specifically with the `databases-for-redis` service. It may be an issue for other database services as well, but we have not tried.

* ibm_container_bind_service
* ibm_database

### Terraform Configuration Files

Database
```
resource "ibm_database" "example_redis" {
  resource_group_id              = data.ibm_resource_group.default.id
  name                           = "${var.base_name}-${var.env_label}-example-redis-${var.region}"
    service                      = "databases-for-redis"
    plan                         = "standard"
    location                     = var.region
    service_endpoints            = "private"
    tags                         = ["managed", var.base_name]
    auto_scaling {
        cpu {
            rate_increase_percent       = 20
            rate_limit_count_per_member = 20
            rate_period_seconds         = 900
            rate_units                  = "count"
        }
        disk {
            capacity_enabled             = true
            free_space_less_than_percent = 15
            io_above_percent             = 85
            io_enabled                   = true
            io_over_period               = "15m"
            rate_increase_percent        = 15
            rate_limit_mb_per_member     = 3670016
            rate_period_seconds          = 900
            rate_units                   = "mb"
        }
         memory {
            io_above_percent         = 90
            io_enabled               = true
            io_over_period           = "15m"
            rate_increase_percent    = 10
            rate_limit_mb_per_member = 114688
            rate_period_seconds      = 900
            rate_units               = "mb"
        }
    }
}

output "example_redis_name" {
  value = ibm_database.example_redis.name
}
```

Example binding
```
resource "ibm_container_bind_service" "example_redis" {
  cluster_name_id       = data.ibm_schematics_output.kubernetes.output_values.kubernetes_cluster_id
  service_instance_name = data.ibm_schematics_output.kubernetes.output_values.example_redis_name
  namespace_id          = kubernetes_namespace.example_namespace.id
  resource_group_id     = data.ibm_schematics_output.kubernetes.output_values.resource_group
}
```

### Steps to Reproduce

1. Apply ibm_database and output above.
2. Apply ibm_container_bind_service above.
3. Remove ibm_database and out entries and reapply.
4 Attempt to apply removal of ibm_container_bind_service above.

### Expected Behavior

Binding is removed if the resource it is referring to is already gone.

### Error Output

![image (1)](https://user-images.githubusercontent.com/45465724/140336916-17779774-6429-4a0d-9f0a-0013753ccd6f.png)

### Important Factoids

We ran into this in IBM Schematics and actually manage the ibm_database in a different workspace than the ibm_container_bind_service.

It would be equivalent to running two terraform states on the same set of IBM Cloud resources. 

It's possible you may need to manually remove the IBM Database and then attempt to remove the ibm_container_bind_service  via terraform to reproduce the bug.

**Comment by hkantare** [comment]
@pthongsavanh-ibm Can you please try using ibmcloud cli or API to unbind a service of an deleted service instance and share us the output

**Comment by pthongsavanh-ibm** [comment]
@hkantare, apologies, but I do not have an environment that we can test in and unfortunately do not have the bandwidth to spin up a test right now.

I can recall however that we were able to remove the bindings with the CLI. The issue remained with the terraform state not being able to auto-correct itself. For some reason it still wanted to remove the binding on it's own and would bump into the the same 404 error. 

We were able to rectify our situation by manually deleting the resource from our terraform state.

**Comment by hkantare** [comment]
closing the issue
