### ISSUE TITLE
Add support for Code Engine

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#3297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to be able to create all Code Engine artifacts (https://cloud.ibm.com/docs/codeengine?topic=codeengine-getting-started) through terraform resources.

### New or Affected Resource(s)

* ibm_ce_xxxx

**Comment by amrlafi** [comment]
Yes please. Strange that it's missing. A show-stopper.

**Comment by saevarb** [comment]
Thanks for the quick answer, @uwefassnacht. 

Is there some other way to manage code engine infra automatically in the meantime?

**Comment by uwefassnacht** [comment]
Either by scripting (using our CLI https://cloud.ibm.com/docs/codeengine?topic=codeengine-cli) or via the Code Engine API.

Note that we are about to release a new (and much improved) version of the API, so if you plan to go that route, you might want to wait a week or two and watch this space: https://cloud.ibm.com/docs/codeengine?topic=codeengine-api

**Comment by uwefassnacht** [comment]
Just to update my comment above. We are still planning to ship terraform support for Code Engine in March.

**Comment by saevarb** [comment]
> Just to update my comment above. We are still planning to ship terraform support for Code Engine in March.

That's good to hear. Do you have a rough ETA? Are we talking soon-ish, or are we talking end of month?

**Comment by kavya498** [comment]
Supported from (1.52.0-beta)https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/code_engine_app

**Comment by michael-magrian** [comment]
Now with support for secrets: https://registry.terraform.io/providers/IBM-Cloud/ibm/1.53.0-beta0/docs/resources/code_engine_secret

**Comment by michael-magrian** [comment]
And we added service binding support: https://registry.terraform.io/providers/IBM-Cloud/ibm/1.55.0-beta0/docs/resources/code_engine_binding 

@l2fprod I think we can close this item for now and manage improvements in new individual requests, right?
