### ISSUE TITLE
cluster config directory does not cleanup on destroy when using ibm_container_cluster_config

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#3303]
When using the following data lookup, the folder that is created does not get cleaned up on destroy:
```
data "ibm_container_cluster_config" "cluster_config" {
  cluster_name_id = var.cluster_id
}
```

So if using the default (as above), users end up with lots of directories in their home directory (e.g. `$HOME/e7fef2191fe0dee1e5c3eb9771354daeb51d3594ce4e95eece734e6f1484ce4b_c64i057l0pgib58luo3g_k8sconfig/config.yml` (one per cluster)

Is this expected behaviour or a bug? It sound like you guys expected this to be cleanup based on [this comment](https://github.com/IBM-Cloud/bluemix-go/pull/328#issuecomment-951808040).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
$ terraform -v
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/ibm-cloud/ibm v1.35.0
```

### Affected Resource(s)

* ibm_container_cluster_config

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "ibm_container_cluster_config" "cluster_config" {
  cluster_name_id = var.cluster_id
}
```

### Expected Behavior

The directory that was added by `ibm_container_cluster_config` should be removed during destroy

### Actual Behavior

Directory is not deleted

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kavya498** [comment]
@ocofaigh ,
There is no destroy for datasource as it is only meant for READ-only operation
terraform removes state of the datasource automatically..

**Comment by ocofaigh** [comment]
OK if its a known limitation, then I guess this can be closed. It sounded like it should be removed after I read https://github.com/IBM-Cloud/bluemix-go/pull/328#issuecomment-951808040

**Comment by kavya498** [comment]
Closing this issue thanks..
