### ISSUE TITLE
Service to Service authorization not always being honored

### ISSUE THREAD

**Issue by jeuns** [IBM-Cloud/terraform-provider-ibm#3305]
==================================================================================
Service to Service authorization not always being honored

We have automation in place which will detect the creation of new VPCs and then automatically create the resources needed to enable flow logs to a COS bucket. There is a service authorization put in place via Terraform which grants flow logs writer access to the COS service. We then have an IBM Cloud Function that will periodically send flow logs from COS to our LogDNA logger instance.

The service to service authorization is not always seem to be honored by IBM Cloud IaM.

This incident occurred in this account, but is being opened here for visability.
Account: US-CON-IBMC-SBX-566
ID: 9983342416b5415b96ffd49880e4f3c8

We have found that VPCs can get created in two ways.

1 - Manually create a VPC in the cloud dashboard and give it a name.

2 - Create a VSI instance when there are no existing VPCs and a "default" VPC will be created.

In this second case, we get the following error:

{'status_code': 400, 'message': 'Your Cloud Object Storage (COS) bucket is missing the Identity Authorization Management (IAM) authorization to allow the flow logs service to write flow logs to your bucket. (Error response code returned from COS Config call: 403)'}

It seems that in the second case where an default VPC is created that the authorization isn't honored by IBM Cloud.

The Terraform to implement the service to service authorization within the account is below. This authorization is in place and visible within the account as well when we encounter the error, however it seems to only be honored in cases where we manually create a VPC.

# Create an iam authorization policy and permit flow log collector to access COS service with Writer role
resource "ibm_iam_authorization_policy" "policy_1" {
   source_service_name = "is"
    source_resource_type = "flow-log-collector"
    target_service_name = "cloud-object-storage"
    roles = ["Writer"]
}

Why are we getting the missing authorization error in the case where the VPC is created by default but not when we manually create a VPC?

==================================================================================
So creating service to service(between cos and flow logs) created proper policy but it is not working for the VPC that created automatically.

Please let let us know if you need any thing else.

**Comment by astha-jain** [comment]
Can you please share your terraform provider configuration?
From the point no 2 above 

> 2 - Create a VSI instance when there are no existing VPCs and a "default" VPC will be created.

Terraform does not create default VPC when you create a VSI. So it looks like you are running into this issue from UI. Is that correct?

**Comment by astha-jain** [comment]
> Subbu Prabhu (Resolution Manager- Mon-Fri 6am - 3pmCST)  8:47 AM
Customer found issue on their side and resolved the case. Thank you @Astha & @JMiddle for engaging quickly on this. @Sarah Sandel Will go ahead and archive this channel shortly.
:heavy_check_mark:
1

https://ibm-cloudplatform.slack.com/archives/C02M3LYRV7B/p1636552037009100

@kavya498  this item can be closed.

**Comment by kavya498** [comment]
Thanks
Closing this issue..
