### ISSUE TITLE
Support enabling "static website" for COS bucket

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#3354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There should be an option on ibm_cos_bucket to enable the static website

This configuration can be done in the UI or following the doc https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-static-website-tutorial#static-website-scenario but there is no easy way to do it in terraform:

![image](https://user-images.githubusercontent.com/12746550/142935156-eb437e2a-cf2a-4852-927b-1005df3e9ebc.png)

### New or Affected Resource(s)

* ibm_cos_bucket

**Comment by vburckhardt** [comment]
+1 - this is still missing at the moment.

**Comment by hkantare** [comment]
@IBM-diksha Can you look into this

**Comment by IBM-diksha** [comment]
This has been added in the latest version of Terraform. Please  use the version v1.58.1 and above for this feature.
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.58.1
Thank you.

**Comment by IBM-diksha** [comment]
Closing this ticket as this has been delivered.
