### ISSUE TITLE
Rename App ID provider

### ISSUE THREAD

**Issue by benlopez1** [IBM-Cloud/terraform-provider-ibm#3355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, Ben Lopez here, product manager for App ID. 
The App ID provider is named incorrectly. Currently it reads "AppID Management". The correct name/formatting should be "App ID Management API"
 
### New or Affected Resource(s)

* ibm_appid

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
N/A
### References

https://cloud.ibm.com/docs/appid to be consistent with the rest of docs the service name should read "App ID" not "AppID"

* #0000

**Comment by kavya498** [comment]
@benlopez1 ,
Help me understand this issue..
You are asking us to rename [here](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/appid_action_url)?
<img width="230" alt="image" src="https://user-images.githubusercontent.com/46739084/144101549-6d9dac74-48fa-479e-8e79-cce68c9f8706.png">

**Comment by benlopez1** [comment]
@kavya498 yes thats correct. I would like it to read 'App ID Management API'

**Comment by kavya498** [comment]
Is `API` required at the end.. Since these are terraform resources,Does it make sense ?

**Comment by benlopez1** [comment]
Yes API should be included. Activity Tracker and VPC also include API. They are listed in the same menu

**Comment by kavya498** [comment]
Yeah, We are planning to remove API from Activity Tracker and VPC.. The subcategory should just be a service name..

**Comment by benlopez1** [comment]
Ok that works. Thanks
