### ISSUE TITLE
Terraform crashing while ordering Object Storage Account resource

### ISSUE THREAD

**Issue by vijaylakshmi-b** [IBM-Cloud/terraform-provider-ibm#336]
### Terraform Version
~/Work/Terraform/Swift$ terraform version
Terraform v0.11.2
+ provider.ibm (unversioned)

### Affected Resource(s)
- ibm_object_storage_account

### Terraform Configuration Files
resource "ibm_object_storage_account" "storage_account" {
        account_type = "SWIFT"
}

### Debug Output and Panic Output
https://gist.github.com/vijaylakshmi-b/d159bc7727610cb5a1f7b309eaa4f2ee

### Expected Behavior
Provisioning should complete successfully

### Actual Behavior
Provisioning is done, but terraform crashes while trying to fetch the Billing Status

### Steps to Reproduce
`terraform apply`

### References
https://github.com/softlayer/softlayer-go/issues/113

**Comment by vijaylakshmi-b** [comment]
@hkantare @sakshiag

**Comment by Praveengostu** [comment]
@vijaylakshmi-b  We will check and get back to you

**Comment by vijaylakshmi-b** [comment]
@sakshiag 
https://github.com/gsl-broker/terraform-provider-ibm
We're using this fork where we have made changes to support both S3 and SWIFT account types. The PRs are still in review and hence not merged into master yet.

I'll check with the latest ibm cloud terraform code and provide an update.

**Comment by hkantare** [comment]
@vijaylakshmi-b With latest provider we are also able to reproduce the issue. I just raised a PR to softlayer-go https://github.com/softlayer/softlayer-go/pull/114

**Comment by hkantare** [comment]
The fix is available in latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.3
