### ISSUE TITLE
Plugin did not respond to Key Protect operations when behind a corporate proxy

### ISSUE THREAD

**Issue by ShoSuenaga** [IBM-Cloud/terraform-provider-ibm#3361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```sh
$ terraform -v
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.36.0
$
```

### Affected Resource(s)

* ibm_kp_key

### Terraform Configuration Files

```hcl
resource "ibm_resource_instance" "kp_instance" {
  name     = "instance-name"
  service  = "kms"
  plan     = "tiered-pricing"
  location = "us-south"
}

resource "ibm_kp_key" "test" {
  key_protect_id  = ibm_resource_instance.kp_instance.guid
  key_name     = "key-name"
  standard_key = false
}
```

### Panic Output

https://gist.github.com/ShoSuenaga/04d26e407b1b2b8c3c0a03e3a7656dee

### Expected Behavior

The plugin responds and processes successfully.

### Actual Behavior

The plugin did not respond.
However, it works fine on another network that is not through a proxy.
It seems the plugin isn't using a proxy to access Key Protect, as the proxy log only contains access to iam.cloud.ibm.com.

### Steps to Reproduce

1. `export http_proxy=<corporate.proxy.local>`
2. `export https_proxy=<corporate.proxy.local>`
3. `terraform import ibm_kp_key.test <ibm_kp_key_crn>`

`terraform plan` also fails if terraform.tfstate has ibm_kp_key.

**Comment by ShoSuenaga** [comment]
Just to clarify, other resources operations were successfully processed even if Terraform was behind a corporate proxy. 
(Such as ibm_iam_authorization_policy, ibm_cos_bucket, sysdig_monitor_alert_metric, and more.)

**Comment by kavya498** [comment]
@ShoSuenaga , ibm_kp_key resource has been deprecated..
Can you please use ibm_kms_key resource instead?

**Comment by ShoSuenaga** [comment]
@kavya498, thank you for your helpful reply!
It works fine when I use ibm_kms_key instead of ibm_kp_key.

**Comment by kavya498** [comment]
@ShoSuenaga ,
Great! Are we good to close this issue?

**Comment by ShoSuenaga** [comment]
@kavya498 
Yes, of course!
I'm sorry for the delayed response.
