### ISSUE TITLE
Adding 'Extended H/W testing' to the module when ordering Baremetal

### ISSUE THREAD

**Issue by Otterton1978** [IBM-Cloud/terraform-provider-ibm#339]
Hi there,

This is a feature request to add extension to current terraform module so that it will be able to perform `Extended H/W testing` when Baremetal is provisioned. This can be done by setting up the flag https://softlayer.github.io/reference/datatypes/SoftLayer_Container_Product_Order/#extendedHardwareTesting  while placing the order for Baremetal. If the server order supports it and the value is set, It will run the extended test suite as part of provisioning.
 
For terraform it can be disabled by default and user can enable to run the extended test suite as part of provisioning. 

Kind regards.

**Comment by Praveengostu** [comment]
Hi @Otterton1978 We are looking in to this.

**Comment by getreid** [comment]
I am adding some more comments to Otterton1978's request, 
This request is for when ordering 100 BM+ servers at one time in Softlayer Cloud via Terraform.
Please take this request as very important.

Many thanks!

**Comment by Praveengostu** [comment]
Hi,
The bare metal resource is enhanced to support the extended_hardware_testing attribute. The code is pushed and available in public. By default extended_hardware_testing is set to false.

**Comment by Praveengostu** [comment]
@getreid  @Otterton1978 The fix is available in the latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.3

**Comment by getreid** [comment]
@Praveengostu, Thanks for your  update!

**Comment by Praveengostu** [comment]
@Otterton1978 Could you please close this issue.
