### ISSUE TITLE
ibm_container_addons - add OpenShift Data Foundation

### ISSUE THREAD

**Issue by tony-advent** [IBM-Cloud/terraform-provider-ibm#3414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

ibm_container_addons

Is it possible to add OpenShift Data Foundation and all the parameter to the list of available addons?

**Comment by kavya498** [comment]
Similar to #3380 , Closing this issue..
Please track using 3380..

Thanks
