### ISSUE TITLE
It should be possible to create a ibm_container_cluster with default_pool_size = 0 

### ISSUE THREAD

**Issue by kugelr** [IBM-Cloud/terraform-provider-ibm#344]
Hi there,

we are currently implementing worker pools via Terraform. For our situation we do not need a "default_worker_pool" but two other worker_pools. For our desired situation we would like to create a cluster without any worker nodes or pools. Then, after cluster creation we would like to create two worker_pools and then attach zones to them. This brings two advantages:

1.  Pools can be configured completely (default_worker_pool has limited configuration options according to provider documentation)

2. This would decrease creation time because currently default_worker_pool and and specific worker_pool creation (and the creation of the respective nodes) have to run sequentially because specific worker_pools dependent on the existence of the cluster (and thus the default_worker_pool). Duration (2 nodes in default_worker_pool - 2 nodes in the specific worker_pool) => ~30-40 mins
If we could skip the default_worker_pool and create two specific worker_pools they would be able to run in parallel. Duration => 15 - 20mins 

As far as I can see, it is not possible in the IBM Cloud to create a Kubernetes cluster with only a master node and no worker nodes. However, I can remove all worker nodes from a existing cluster. 

Do you see any chance to get this functionality implemented? Any thoughts on this?

Best regards
René

**Comment by Praveengostu** [comment]
Hi, Could you put your query in https://ibm-container-service.slack.com. This repo is specifically to deal issues with the IBM Cloud provider for terraform.

**Comment by hkantare** [comment]
Closing this issue.
