### ISSUE TITLE
Intermittently getting 404 during cluster provisioning using ibm_container_vpc_cluster

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#3449]
Full trace logs are attached for this issue, however multiple tests were running terraform apply at the same time, so going to extract out the important info and summarise ....

1. Cluster creation started at this time: 
`TestMultipleMzrExample 2021-12-16T06:09:43Z logger.go:66: module.ocp_base_cluster_1.ibm_container_vpc_cluster.cluster: Creating...`

2. 26 mins in, this was the last line that was logged for this cluster creation before the error: 
`TestMultipleMzrExample 2021-12-16T06:35:43Z logger.go:66: module.ocp_base_cluster_1.ibm_container_vpc_cluster.cluster: Still creating... [26m0s elapsed]`

3. The following error was produced:
```
TestMultipleMzrExample 2021-12-16T07:10:35Z logger.go:66: │ Error: Request failed with status code: 404, ServerErrorResponse: {"incidentID":"e5bd7015-2160-4db9-a464-7090a3572476,e5bd7015-2160-4db9-a464-7090a3572476","code":"A0006","description":"The specified cluster could not be found. If applicable, make sure that you target the correct resource group or region.","type":"Authentication","recoveryCLI":"To list the clusters you have access to, run 'ibmcloud ks cluster ls'. To set the resource group, get the cluster's resource group, compare it to groups that you have access to, and target the group: 'ibmcloud ks cluster get \u003ccluster_name_or_ID\u003e', 'ibmcloud resource groups', and 'ibmcloud target -g \u003cresource_group\u003e'. To target a region, run 'ibmcloud ks init --host \u003cregional_endpoint\u003e'."}
TestMultipleMzrExample 2021-12-16T07:10:35Z logger.go:66: │ 
TestMultipleMzrExample 2021-12-16T07:10:35Z logger.go:66: │   with module.ocp_base_cluster_1.ibm_container_vpc_cluster.cluster,
TestMultipleMzrExample 2021-12-16T07:10:35Z logger.go:66: │   on ../../main.tf line 48, in resource "ibm_container_vpc_cluster" "cluster":
TestMultipleMzrExample 2021-12-16T07:10:35Z logger.go:66: │   48: resource "ibm_container_vpc_cluster" "cluster" {
TestMultipleMzrExample 2021-12-16T07:10:35Z logger.go:66: │ 
TestMultipleMzrExample 2021-12-16T07:10:35Z logger.go:66: ╵
TestMultipleMzrExample 2021-12-16T07:10:35Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
```

Why did the cluster creation never complete? And why do we see a 404? Hopefully something in the trace log will help identify the issue. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
$ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/ibm-cloud/ibm v1.36.0
```

### Affected Resource(s)

* ibm_container_vpc_cluster

### Terraform Configuration Files

https://github.ibm.com/GoldenEye/base-ocp-vpc-module/tree/master/examples/multiple_mzr_clusters (internal url)

### Debug Output

[trace-logs.zip](https://github.com/IBM-Cloud/terraform-provider-ibm/files/7726124/trace-logs.zip)

### Expected Behavior

Provisioning should pass 

### Actual Behavior
`│ Error: Request failed with status code: 404, ServerErrorResponse: {"incidentID":"e5bd7015-2160-4db9-a464-7090a3572476,e5bd7015-2160-4db9-a464-7090a3572476","code":"A0006","description":"The specified cluster could not be found. If applicable, make sure that you target the correct resource group or region.","type":"Authentication","recoveryCLI":"To list the clusters you have access to, run 'ibmcloud ks cluster ls'. To set the resource group, get the cluster's resource group, compare it to groups that you have access to, and target the group: 'ibmcloud ks cluster get \u003ccluster_name_or_ID\u003e', 'ibmcloud resource groups', and 'ibmcloud target -g \u003cresource_group\u003e'. To target a region, run 'ibmcloud ks init --host \u003cregional_endpoint\u003e'."}
│ 
│   with module.ocp_base_cluster_1.ibm_container_vpc_cluster.cluster,
│   on ../../main.tf line 48, in resource "ibm_container_vpc_cluster" "cluster":
│   48: resource "ibm_container_vpc_cluster" "cluster" {
│ 
╵}`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

There is no sign of this cluster in the UI when I checked. Not sure if it ever existed or what happened.

### References

* #0000

**Comment by hkantare** [comment]
@ocofaigh Can you please pass this to the new Team from IKS who took the ownership of Terraform proivder
https://github.ibm.com/alchemy-containers/armada-terraform/issues

**Comment by ocofaigh** [comment]
Created https://github.ibm.com/alchemy-containers/armada-terraform/issues/17

**Comment by ocofaigh** [comment]
We found some automation that was deleting the cluster and hence causing 404s - closing
