### ISSUE TITLE
Ingress subdomain is not created

### ISSUE THREAD

**Issue by mgluhic10** [IBM-Cloud/terraform-provider-ibm#345]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
-ibm_container_cluster

### Terraform Configuration Files
# a cluster
resource "ibm_container_cluster" "kubernetes" {
  name             = "${var.environment}-test-kubernetes"
  datacenter       = "${var.datacenter}"
  org_guid         = "${var.organisation-guid}
  space_guid       = "${ibm_space.space.id}"
  account_guid     = "${var.account-guid}"
  no_subnet        = true
  hardware         = "shared"
  machine_type     = "${var.cluster-machine-type}"
  worker_num       = "${var.cluster-worker-num}"
  public_vlan_id   = "${var.vlan-public}"
  private_vlan_id  = "${var.vlan-private}"
}

### Expected Behavior
When create cluster manualy  Ingress subdomain is created automaticaly. I can see that on dashboard.
Also I was expecting that I will have that value when I create cluster with Terraform.

### Actual Behavior
What actually happened?
Ingress subdomain
    -- 
Subdomain is not created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Praveengostu** [comment]
Hi @mgluhic10 In the configuration specified I see you had specified no_subnet = true. By default, a public and a private portable subnet are created on the VLAN associated with the cluster. By Specifying no_subnet = true will avoid creating  subnets to the cluster. 
Pls try by removing no_subnet = true or pass subnet_id to the resource container cluster to create the ingress subdomain.

**Comment by hkantare** [comment]
closing the issue..
