### ISSUE TITLE
Mysql - Error getting user connection string for user

### ISSUE THREAD

**Issue by lionelmace** [IBM-Cloud/terraform-provider-ibm#3454]
Provisioning MySQL DB is failing with error code

```
 Error: [ERROR] Error getting user connection string for user (admin): [ERROR] Unrecognised database type during connection string lookup: databases-for-mysql
│
│   with ibm_database.icd_mysql,
│   on mysql.tf line 4, in resource "ibm_database" "icd_mysql":
│    4: resource "ibm_database" "icd_mysql" {
```

Why is the line commented ?
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/cd80aceab069d332a7b7cec0768beddb4723c23e/ibm/resource_ibm_database.go#L1836

**Comment by kavya498** [comment]
@lionelmace , can we get sample configuration that you have used?

**Comment by lionelmace** [comment]
@kavya498 here you go
https://github.com/lionelmace/ibmcloud-utils/tree/master/terraform/mysql

**Comment by lionelmace** [comment]
It works fine with release 1.38.0 :-)
