### ISSUE TITLE
resource "ibm_is_instance_action" docs bad example

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* is_instance_action

### Terraform Configuration Files
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance_action

Current example:

```
resource "ibm_is_instance_action" "example" {
  action = "stop"
  force_action = true
}
```

Expected: Example snippet that is closer to working.  In this case something like:
```
resource "ibm_is_instance_action" "example" {
  action = "stop"
  force_action = true
  instance = ibm_is_instance.example.id
}
```

**Comment by deepaksibm** [comment]
@powellquiring we are working on a PR that fixes these doc issues

**Comment by hkantare** [comment]
closing the issue
