### ISSUE TITLE
Bare metal monthly order faiing Could not find the price item for 2048 GB memory

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#347]
Right now we are checking prefix as RAM_64_GB for keyname for memory 

[
func findMemoryItemPriceId(items []datatypes.Product_Item, d dataRetriever) (datatypes.Product_Item_Price, error) {
	memory := d.Get("memory").(int)
	memoryStr := "RAM_" + strconv.Itoa(memory) + "_GB"
	availableMemories := ""

	for _, item := range items {
		for _, itemCategory := range item.Categories {
			if *itemCategory.CategoryCode == "ram" {
				availableMemories = availableMemories + *item.KeyName + "(" + *item.Description + ")" + ", "
				if strings.HasPrefix(*item.KeyName, memoryStr) {
					for _, price := range item.Prices {
						if price.LocationGroupId == nil {
							return datatypes.Product_Item_Price{Id: price.Id}, nil
						}
					}
				}
			}
		}
	}

]

But for 1024 ,2048 etc.. Keyname is prefix with "RAM_0_UNIT_PLACEHOLDER..." so it is giving error could not find price id for this item .

**Comment by hkantare** [comment]
Fix is available as part of v0.12.0 .Can you please test with latest provider https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0

**Comment by hkantare** [comment]
Closing the issue . If issue still exists please reopen it.
