### ISSUE TITLE
ibm_is_vpc_routing_table docs bad example

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_is_vpc_routing_table

### Terraform Configuration Files

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc_routing_table

Example:
```
resource "ibm_is_vpc" "testacc_vpc" {
  name = "testvpc"
}
resource "ibm_is_vpc_routing_table" "test_ibm_is_vpc_routing_table" {
  vpc = ibm_is_vpc.testacc_vpc.id
  name = "routTabletest"
  route_direct_link_ingress = true
  route_transit_gateway_ingress = false
  route_vpc_zone_ingress = false
}
```

Results in:
```
│ Error: "name" ("routTabletest") should match regexp ^([a-z]|[a-z][-a-z0-9]*[a-z0-9])$ 
│ 
│   with ibm_is_vpc_routing_table.main,
│   on main.tf line 181, in resource "ibm_is_vpc_routing_table" "main":
│  181:   name                          = "routTabletest"
│ 
```
expected: Test all the examples

**Comment by deepaksibm** [comment]
@powellquiring we are working on a PR that fixes these doc issues

**Comment by astha-jain** [comment]
@kavya498 This issue is fixed. Good to close.

**Comment by kavya498** [comment]
Closing this issue 
thanks
