### ISSUE TITLE
Security and Compliance Center (SCC): Support configuration of event notifications / scc_account_settings

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Security and Compliance Center supports the configuration of event notifications. See here for the API: https://cloud.ibm.com/apidocs/security-compliance/admin#patchaccountsettings

The TF provider has scc_account_settings, but the new feature is not supported. Add it.

### New or Affected Resource(s)

* scc_account_settings

**Comment by hkantare** [comment]
Available in latest releases
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_account_settings
