### ISSUE TITLE
Wrong description for example on ibm_iam_access_group_policy

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
See https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/iam_access_group_policy
![image](https://user-images.githubusercontent.com/8414748/149924659-7412108e-99cb-42cf-92d4-4aeb3f305e9d.png)

There is no region in the sample code

* ibm_iam_access_group_policy

**Comment by kavya498** [comment]
@data-henrik , this is been fixed in latest release 1.38.0..
I don't see that in docs.. Could you please confirm?
<img width="699" alt="image" src="https://user-images.githubusercontent.com/46739084/150067102-cc131965-e72d-46b7-8104-d00c21ebd503.png">

**Comment by kavya498** [comment]
Closing this issue as it is already fixed..
Kindly reopen if the issue still persits..
Thanks
