### ISSUE TITLE
Not able to list all the subnets for a given VPC 

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#3506]
data "ibm_is_vpc" is not able to list the subnets attached to a given VPC if the subnets in account is more than 50

**Comment by hkantare** [comment]
A customer is trying to retrive a VPC using a datasource 
data "ibm_is_vpc" "vpc" {
 name = "XXXXXX"
}


terraform {
  required_providers {
    ibm = {
      source = "IBM-Cloud/ibm"
      version = "1.38.0"
    }
  }
}

provider "ibm" {
  region = "eu-de"
}

**terraform show**
 terraform show
# data.ibm_is_vpc.vpc:
data "ibm_is_vpc" "vpc" {
    classic_access              = false
    crn                         = "crn:v1:bluemix:public:is:eu-de:a/175b993c36534af6be7a6499ce289d90::vpc:r010-1a991098-bdc2-4989-81c2-e1ff423bd5d8"
    cse_source_addresses        = [
        {
            address   = "10.223.33.79"
            zone_name = "eu-de-1"
        },
        {
            address   = "10.16.214.162"
            zone_name = "eu-de-2"
        },
        {
            address   = "10.223.54.241"
            zone_name = "eu-de-3"
        },
    ]
    default_network_acl         = "r010-b7570adf-75a9-4554-905e-099ab71d15f6"
    default_network_acl_crn     = "crn:v1:bluemix:public:is:eu-de:a/175b993c36534af6be7a6499ce289d90::network-acl:r010-b7570adf-75a9-4554-905e-099ab71d15f6"
    default_network_acl_name    = "autocar-upcoming-bask-ahead"
    default_routing_table       = "r010-2f48fa82-dae3-4c10-b562-bb51f7e97b53"
    default_routing_table_name  = "cape-other-given-stuck"
    default_security_group      = "r010-0c16b7eb-6f04-40ee-b93b-50976811737f"
    default_security_group_crn  = "crn:v1:bluemix:public:is:eu-de:a/175b993c36534af6be7a6499ce289d90::security-group:r010-0c16b7eb-6f04-40ee-b93b-50976811737f"
    default_security_group_name = "timing-unwritten-structure-happily"
    id                          = "r010-1a991098-bdc2-4989-81c2-e1ff423bd5d8"
    name                        = "vpc-bastion-cedeveud"
    resource_controller_url     = "https://cloud.ibm.com/vpc-ext/network/vpcs"
    resource_crn                = "crn:v1:bluemix:public:is:eu-de:a/175b993c36534af6be7a6499ce289d90::vpc:r010-1a991098-bdc2-4989-81c2-e1ff423bd5d8"
    resource_group              = "65f22f058b9840ab8e3306e3474903c1"
    resource_group_name         = "bastion-dev-relint-eu-de"
    resource_name               = "vpc-bastion-cedeveud"
    resource_status             = "available"
    security_group              = [
        {
            group_id   = "r010-0c16b7eb-6f04-40ee-b93b-50976811737f"
            group_name = "timing-unwritten-structure-happily"
            rules      = [
                {
                    code       = 0
                    direction  = "outbound"
                    ip_version = "ipv4"
                    port_max   = 0
                    port_min   = 0
                    protocol   = "all"
                    remote     = "0.0.0.0/0"
                    rule_id    = "r010-b6b82475-078e-49ef-9d25-69aa8001d3f7"
                    type       = 0
                },
                {
                    code       = 0
                    direction  = "inbound"
                    ip_version = "ipv4"
                    port_max   = 0
                    port_min   = 0
                    protocol   = "all"
                    remote     = "r010-0c16b7eb-6f04-40ee-b93b-50976811737f"
                    rule_id    = "r010-119a0836-4aaf-43ee-bd36-7649420a3641"
                    type       = 0
                },
            ]
        },
        {
            group_id   = "r010-7c8e8172-b961-46b6-9ba1-c113ef16fd21"
            group_name = "vpc-bastion-sg"
            rules      = [
                {
                    code       = 0
                    direction  = "outbound"
                    ip_version = "ipv4"
                    port_max   = 0
                    port_min   = 0
                    protocol   = "all"
                    remote     = "0.0.0.0/0"
                    rule_id    = "r010-482cbbdc-fa10-4324-91bd-d63a290ece66"
                    type       = 0
                },
                {
                    code       = 0
                    direction  = "inbound"
                    ip_version = "ipv4"
                    port_max   = 3026
                    port_min   = 3023
                    protocol   = "tcp"
                    remote     = "0.0.0.0/0"
                    rule_id    = "r010-d6f7e7ab-4842-47d2-9983-40c1d6051e59"
                    type       = 0
                },
                {
                    code       = 0
                    direction  = "inbound"
                    ip_version = "ipv4"
                    port_max   = 443
                    port_min   = 443
                    protocol   = "tcp"
                    remote     = "0.0.0.0/0"
                    rule_id    = "r010-968a7bfa-0c32-45cf-af78-22f4730af892"
                    type       = 0
                },
                {
                    code       = 0
                    direction  = "inbound"
                    ip_version = "ipv4"
                    port_max   = 22
                    port_min   = 22
                    protocol   = "tcp"
                    remote     = "0.0.0.0/0"
                    rule_id    = "r010-387999c3-7c9c-46bd-a3d0-128b182957c0"
                    type       = 0
                },
            ]
        },
    ]
    status                      = "available"
    subnets                     = []
    tags                        = []
}

**Comment by hkantare** [comment]
[apply (1).log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/7897694/apply.1.log)

**Comment by ujjwal-ibm** [comment]
Looking into this.
