### ISSUE TITLE
FileStorage: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by eswarak** [IBM-Cloud/terraform-provider-ibm#351]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.11.7
+ provider.ibm (unversioned)

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_storage_file

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Create a file storage
resource "ibm_storage_file" "unicorn_cs" {
type           = "Endurance"
datacenter     = "${var.datacenter}"
capacity       = "${var.file_storage_size}"
iops           = "${var.file_storage_iops}"
hourly_billing = false
notes          = "${var.vlan_name}_${var.datacenter}_filestorage"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
1 error(s) occurred:

* ibm_storage_file.unicorn_cs: 1 error(s) occurred:

* ibm_storage_file.unicorn_cs: Error during creation of storage: Post https://api.softlayer.com/rest/v3/SoftLayer_Product_Order/placeOrder.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
When creating file storage or block storage, the Client.Timout error pops very frequently. Can't use terraform to use this resource, whereas slcli works file.

slcli file volume-order --storage-type endurance --size 200 --tier 0.25 --location sjc04 --billing monthly
Order #xxxxxxxxx placed successfully!
 > Storage as a Service
 > File Storage
 > 200 GBs
 > 0.25 IOPS per GB
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by hkantare** [comment]
Can you please increase SL_TIMEOUT or SOFTLAYER_TIMEOUT . By default its 60 seconds.
export SL_TIMEOUT=300

**Comment by hkantare** [comment]
closing the issue..No updates from longtime. Please reopen if issue still exists
