### ISSUE TITLE
API endpoints for SCC are wrong and cannot be changed

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3524]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    ibm = {
      source  = "ibm-cloud/ibm"
      version = "~>1.38"
    }
  }
}
```

### Affected Resource(s)

*  data ibm_scc_account_settings

```
Error: ListLocationsWithContext failed Get "https://admin-service-api.cloud.ibm.com/admin/v1/locations": dial tcp: lookup admin-service-api.cloud.ibm.com on 9.0.0.1:53: no such host
│ null
│ 
│ 
│   with data.ibm_scc_account_locations.scc_account_locations,
│   on main.tf line 7, in data "ibm_scc_account_locations" "scc_account_locations":
│    7: data "ibm_scc_account_locations" "scc_account_locations" {
│ 
```

I tried to overwrite the endpoint via environment variable, but it does not work at all.

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

**Comment by tyao117** [comment]
I believe that the current deployed terraform provider for the scc admin settings was using a previous API version of scc-go-sdk. A new version is currently in the works.

**Comment by data-henrik** [comment]
my tests
```
data "ibm_scc_account_locations" "scc_account_locations" {
}

data "ibm_scc_account_settings" "scc_account_location_settings" {
}


data "ibm_scc_account_location" "scc_account_location" {
  location_id = "eu"
}

```

**Comment by hardt-rmt** [comment]
> > I believe that the current deployed terraform provider for the scc admin settings was using a previous API version of scc-go-sdk. A new version is currently in the works.
> 
> What's the ETA? What are the tests to catch such issues in the future?

There's a PR open for this https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3526
