### ISSUE TITLE
ibm_is_lb resource is silently updating subnet details in state with no actual affect on lb

### ISSUE THREAD

**Issue by kavya498** [IBM-Cloud/terraform-provider-ibm#3538]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_is_lb

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
Terraform will perform the following actions:
 
   # ibm_is_lb.lb will be updated in-place
   ~ resource "ibm_is_lb" "lb" {
         id                       = "XXX"
         name                     = "YYY"
       ~ subnets                  = [
           + "<REDACTED>",
             # (2 unchanged elements hidden)
         ]
         tags                     = [
             "XX",
             "YY",
         ]
         # (16 unchanged attributes hidden)
     }
 
 Plan: 0 to add, 1 to change, 0 to destroy.
 ibm_is_lb.lb: Modifying... [id=XXX]
ibm_is_lb.lb: Modifications complete after 4s [id=XXX]
```

### Expected Behavior

Terraform should have added subnet.. OR
If there is no update behaviour, force new should have been added on `subnets` argument so that user is aware that there is no update on subnets

### Actual Behavior

Terraform didn't add any subnet to lb,  but silently updated state file with subnet details

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by astha-jain** [comment]
Hey there should be a force new added to subnet as subnet cannot be patched.

**Comment by astha-jain** [comment]
@kavya498 PR is merged. Good to close.

**Comment by kavya498** [comment]
Closing this issue 
Thanks..
