### ISSUE TITLE
icmp_type not supported on security group rule

### ISSUE THREAD

**Issue by stevestrutt** [IBM-Cloud/terraform-provider-ibm#355]
Apply fails when creating security group rule for icmp, using the details in the API documentation, specifying protocol as 'icmp'. The VPC CLI and the UI have a icmp_type parameter that is a standard feature of (Vyatta etc) firewall rules required to determine the icmp type to allow. No mention in the docs of icmp_type, also specifying icmp_type results in the error:
Error: ibm_security_group_rule.sg_11: : invalid or unknown key: icmp_type

If icmp_type is omitted the plan executes, but fails later with: 

 + ibm_security_group_rule.sg_11
      id:                                <computed>
      direction:                         "ingress"
      ether_type:                        "IPv4"
      protocol:                          "icmp"
      security_group_id:                 "0"

  + ibm_security_group_rule.sg_12
      id:                                <computed>
      direction:                         "egress"
      ether_type:                        "IPv4"
      protocol:                          "icmp"
      security_group_id:                 "0"

Error: Error applying plan:
1 error(s) occurred:
* ibm_security_group.sg_private: 1 error(s) occurred:
* ibm_security_group.sg_private: SoftLayer_Exception: Object does not exist to execute method on. (SoftLayer_Network_SecurityGroup::editObject) (HTTP 500)

**Comment by ashishth09** [comment]
Please see https://github.com/IBM-Cloud/terraform-provider-ibm/issues/140#issuecomment-367670877

**Comment by Praveengostu** [comment]
@stevestrutt Could you please share your configuration. We tried in our environment it was completed sucessfully with below configuration.
```resource "ibm_security_group" "testacc_sg" {
    name = "test"
}
resource "ibm_security_group_rule" "testacc_sg_rule" {
    direction = "ingress"
	protocol = "icmp"
	security_group_id = "${ibm_security_group.testacc_sg.id}"
}```

 The issue I  see in your case is with ibm_security_group .

**Comment by hkantare** [comment]
closing the issue..If issue still exists please reopen it
