### ISSUE TITLE
How to create a single default ACL instead of two?

### ISSUE THREAD

**Issue by lionelmace** [IBM-Cloud/terraform-provider-ibm#3557]
### Actual Behavior

I created a simple VPC with default ACL. It creates two ACLs: default ACL + ACL scripted in Terraform. See screenshot below:

![image](https://user-images.githubusercontent.com/12241613/152851476-01c93835-a405-4898-8b30-f2fa2516a83a.png)

### Expected Behavior

I would expect a single default ACL. How could I create a single default ACL instead of two?

### Terraform CLI and Terraform IBM Provider Version

Terraform Provider version = "1.38.1"
Terraform v1.0.11 on darwin_amd64

### Affected Resource(s)

* ibm_is_network_acl

### Terraform Configuration Files

Here is the script to reproduce:
```
resource "ibm_resource_group" "resource_group" {
  name = "simple-group"
}

resource "ibm_is_vpc" "vpc" {
  name = "simple-vpc"
  resource_group = ibm_resource_group.resource_group.id
}

resource "ibm_is_network_acl" "example" {
  name = "simple-acl"
  vpc  = ibm_is_vpc.vpc.id
  resource_group = ibm_resource_group.resource_group.id

  rules {
    name        = "outbound"
    action      = "allow"
    source      = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    direction   = "outbound"
    icmp {
      code = 1
      type = 1
    }
  }
  rules {
    name        = "inbound"
    action      = "allow"
    source      = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    direction   = "inbound"
    icmp {
      code = 1
      type = 1
    }
  }
}

resource "ibm_is_vpc_address_prefix" "example" {
  cidr = "10.0.1.0/24"
  name = "simple-add-prefix"
  vpc  = ibm_is_vpc.vpc.id
  zone = var.zone
}

resource "ibm_is_subnet" "example" {
  depends_on      = [
    ibm_is_vpc_address_prefix.example
  ]
  ipv4_cidr_block = "10.0.1.0/24"
  name            = "simple-subnet"
  vpc             = ibm_is_vpc.vpc.id
  zone            = var.zone
  network_acl     = ibm_is_network_acl.example.id
}

resource "ibm_is_subnet_network_acl_attachment" attach {
  subnet      = ibm_is_subnet.example.id
  network_acl = ibm_is_network_acl.example.id
}
```

### Steps to Reproduce

Full terraform is here:
https://github.com/lionelmace/ibmcloud-utils/tree/master/terraform/vpc/simple-vpc

**Comment by SunithaGudisagarIBM** [comment]
Hi @lionelmace,

As we discussed over the slack please replace "ibm_is_network_acl" resource with the below code

resource "ibm_is_network_acl_rule" "outbound" {
  network_acl = ibm_is_vpc.vpc.default_network_acl
  name        = "outbound"
  action      = "allow"
  source      = "0.0.0.0/0"
  destination = "0.0.0.0/0"
  direction   = "outbound"
  icmp {
    code = 1
    type = 1
  }
}

resource "ibm_is_network_acl_rule" "inbound" {
  network_acl = ibm_is_vpc.vpc.default_network_acl
  name        = "inbound"
  action      = "allow"
  source      = "0.0.0.0/0"
  destination = "0.0.0.0/0"
  direction   = "inbound"
  icmp {
    code = 1
    type = 1
  }
} 

let me know if you need any assistance.

Thank you for reaching out 
Sunitha

**Comment by lionelmace** [comment]
Thanks for the trick. It works fine.
