### ISSUE TITLE
Posture Management is Security and Compliance Center, too

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#3560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)
![image](https://user-images.githubusercontent.com/8414748/152979599-1385f167-97fe-4851-b4a9-2e08d38d2cbc.png)

Posture Management should be part of SCC. Both start with **ibm_scc**

**Comment by kavya498** [comment]
@data-henrik , 
Issue is already fixed.. will be available in upcoming release 
Related PR - https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3533

**Comment by kavya498** [comment]
Closing this issue
Thanks
