### ISSUE TITLE
Attribute pi_storage_type required in ibm_pi_image resource !! high Priority please

### ISSUE THREAD

**Issue by surajbharadwaj** [IBM-Cloud/terraform-provider-ibm#3575]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_image

It is not possible to create an image obtained from catalog images (stock images) in tier of our choice. By default it gets created in same Tier as the catalog image Tier.

For example:
catalog image SLES is in Tier 1.
When ibm_pi_image is used to create an image in cloud instance, it creates in same Tier i.e Tier1 .

It is not possible to use this image to create an instance in Tier3. (i.e want boot disk in tier3)

below is the code:
```
####list catalog images######
data "ibm_pi_catalog_images" "catalog_images" {
  sap                  = true
  pi_cloud_instance_id = data.ibm_resource_instance.sap_service.guid
}

### Find the image required based on name in catalog image####
locals {
  catalog_node_image = [for x in data.ibm_pi_catalog_images.catalog_images.images : x if x.name == var.PVS_SAP_IMAGE_NAME]
  image_id           = local.catalog_node_image[0].image_id
}

#### create an image in ibmcloud cloud instance #####
resource "ibm_pi_image" "my_sap_image" {
  depends_on          = [data.ibm_pi_catalog_images.catalog_images]
  pi_image_name       = "SLES-SUSE_12-SP-4"
  pi_image_id         = local.image_id
  pi_cloud_instance_id = data.ibm_resource_instance.sap_service.guid
} 

###### create an instance using the image above in tier3#######
resource "ibm_pi_instance" "sap" {
  depends_on               = [ibm_pi_image.my_sap_image]
  pi_cloud_instance_id     = data.ibm_resource_instance.sap_service.guid
  pi_instance_name         = var.PVS_SAP_NAME
  pi_image_id              = ibm_pi_image.my_sap_image.image_id
  pi_sap_profile_id        = var.PVS_SAP_PROFILE_ID == "" ? null : var.PVS_SAP_PROFILE_ID
  pi_processors            = var.PVS_SAP_PROFILE_ID != "" ? null : var.PVS_SAP_PROCESSORS
  pi_memory                = var.PVS_SAP_PROFILE_ID != "" ? null : var.PVS_SAP_MEMORY
  pi_sys_type              = var.PVS_SAP_PROFILE_ID != "" ? null : var.PVS_SAP_SYS_TYPE
  pi_proc_type             = var.PVS_SAP_PROFILE_ID != "" ? null : var.PVS_SAP_PROC_TYPE
  pi_key_pair_name         = data.ibm_pi_key.get_key.id
  pi_health_status         = "OK"
  pi_storage_pool_affinity = false
  pi_storage_type          = "tier3"
 
  dynamic "pi_network" {
      for_each = tolist(data.ibm_pi_network.get_private_nets.*.id)
      content {
         network_id = pi_network.value
              }
  }

}
```

From the image below (source terraform ibm api website) there is no option to specify in which storage_type the image has to be created. This attribute is available for COS only. 

**Would it be possible to include an attr
![ibm_pi_image](https://user-images.githubusercontent.com/46653528/153499450-66398f14-aed9-46c7-98b6-1f619a841b40.png)
ibute  pi_storage_type under ibm_pi_image**

**Comment by yussufsh** [comment]
What you showed in examples 1 & 2 in above screenshot is for 1. Copy Image 2. Import image from a COS bucket.
Providing storage type is not an option we have for copy image. See the API definition at https://cloud.ibm.com/apidocs/power-cloud#pcloud-cloudinstances-images-post
![image](https://user-images.githubusercontent.com/17543270/153542961-50cf0fa8-1b16-49cd-a4e0-d2fec1b44039.png)

**Comment by yussufsh** [comment]
You need to import/copy the stock image into your project and use the image id of the imported image. Specifying any (tier1, tier3) storage type will not result in the error for stock images that is imported.

I have created this https://github.com/yussufsh/ibmcloud-powervs-instance-deploy/blob/multi-tier/main.tf template for filtering the image id and deploy on both storage controllers.

**Comment by surajbharadwaj** [comment]
Not relevant anymore. 

Reason:
**Linux-SUSE-SAP-12-4** image is  apparently is in **TIER 1** In backend and thus gets copied to cloud ID in **TIER 1** type.  it is **not possible to deploy using this image for a Tier** 3 instance. can be used for Tier1 instance only
Whereas rest of images(For example **Linux-RHEL-SAP-8-1**) is in **Tier 3 in backend** and thus gets copied to cloud Id in **Tier3 type**. It is possible to deploy using this image in **both Tier1 and Tier 3 instances**.

Root cause: **Linux-SUSE-SAP-12-4 apparently is in TIER 1 In backend**
Fix required by backend team: **Linux-SUSE-SAP-12-4 should be moved to TIER3 in backend**
