### ISSUE TITLE
While setting up VPC flow log we are getting ibm_iam_authorization_policy error, even though we have authorize policy for COS bucket

### ISSUE THREAD

**Issue by subbapan** [IBM-Cloud/terraform-provider-ibm#3590]
As per the initial investigation, it is working, when the COS bucket is created with a public endpoint and removing restriction access only to specific IPs. 

But, when we create COS bucket private only endpoint and restrict access with specific IPs, maybe this is the cause. 

Seeing weird issue while setting up VPC flow log through terraform, we have resource ibm_iam_authorization_policy for flow-log-collector but still getting below error

Result": {
 2022/02/08 10:39:35 Terraform apply |         "errors": [
 2022/02/08 10:39:35 Terraform apply |             {
 2022/02/08 10:39:35 Terraform apply |                 "code": "service_error",
 2022/02/08 10:39:35 Terraform apply |                 "message": "Your Cloud Object Storage (COS) bucket is missing the Identity Authorization Management (IAM) authorization to allow the flow logs service to write flow logs to your bucket. (Error response code returned from COS Config call: 403)",
 2022/02/08 10:39:35 Terraform apply |                 "more_info": "https://cloud.ibm.com/docs/vpc?topic=vpc-ordering-flow-log-collector#fl-before-you-begin",
 2022/02/08 10:39:35 Terraform apply |                 "target": {
 2022/02/08 10:39:35 Terraform apply |                     "name": "storage_bucket.name",
 2022/02/08 10:39:35 Terraform apply |                     "type": "field",
 2022/02/08 10:39:35 Terraform apply |                     "value": "tsb-edge-fl-cos"
 2022/02/08 10:39:35 Terraform apply |                 }
 2022/02/08 10:39:35 Terraform apply |             }
 2022/02/08 10:39:35 Terraform apply |         ],

Here is the authorization resource code
---------------------------------------------
resource "ibm_iam_authorization_policy" "vpc_auth_flow_policy" {
  source_service_name         = "is"
  source_resource_type        = "flow-log-collector"
  target_service_name         = "cloud-object-storage"
  target_resource_instance_id = ibm_resource_instance.cos_instance[0].guid
  roles                       = ["Writer"]
}

resource "ibm_is_flow_log" "flowlog" {
  depends_on     = [ibm_iam_authorization_policy.vpc_auth_flow_policy]
  count          = var.flowlog_active ? 1 : 0
  name           = "${var.prefix}-flowlog"
  target         = var.vpc_id
  active         = var.flowlog_active
  storage_bucket = ibm_cos_bucket.flowlog_bucket[0].bucket_name
  tags           = var.tags
}

 we have problems when we use cos private endpoint. When we use a public endpoint, we are able to authorize and create flow log Instance.

ACLs were completely allowed when we tested. even though we got the error.

Error:
Result": {
2022/02/08 10:39:35 Terraform apply | "errors": [
2022/02/08 10:39:35 Terraform apply | {
2022/02/08 10:39:35 Terraform apply | "code": "service_error",
2022/02/08 10:39:35 Terraform apply | "message": "Your Cloud Object Storage (COS) bucket is missing the Identity Authorization Management (IAM) authorization to allow the flow logs service to write flow logs to your bucket. (Error response code returned from COS Config call: 403)",
2022/02/08 10:39:35 Terraform apply | "more_info": "https://cloud.ibm.com/docs/vpc?topic=vpc-ordering-flow-log-collector#fl-before-you-begin",
2022/02/08 10:39:35 Terraform apply | "target": {
2022/02/08 10:39:35 Terraform apply | "name": "storage_bucket.name",
2022/02/08 10:39:35 Terraform apply | "type": "field",
2022/02/08 10:39:35 Terraform apply | "value": "tsb-edge-fl-cos"
2022/02/08 10:39:35 Terraform apply | }
2022/02/08 10:39:35 Terraform apply | }
2022/02/08 10:39:35 Terraform apply | ],

Links followed:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_flow_log
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cos_bucket
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/iam_authorization_policy

Our terraform Code:
terraform {
required_providers {
ibm = {
source = "IBM-Cloud/ibm"
version = ">= 1.37.1"
}
}
required_version = ">= 1.0"
}

resource "ibm_iam_authorization_policy" "vpc_auth_flow_policy" {
source_service_name = "is"
source_resource_type = "flow-log-collector"
target_service_name = "cloud-object-storage"
target_resource_instance_id = ibm_resource_instance.cos_instance[0].guid
roles = ["Writer"]
}

resource "ibm_is_flow_log" "flowlog" {
depends_on = [ibm_iam_authorization_policy.vpc_auth_flow_policy]
count = 1
name = flowlog
target = var.vpc_id
active = true
storage_bucket = ibm_cos_bucket.flowlog_bucket[0].bucket_name
}

resource "ibm_cos_bucket" "flowlog_bucket" {
depends_on = [ibm_resource_instance.cos_instance]
bucket_name = buk1
count = 1
resource_instance_id = ibm_resource_instance.cos_instance[count.index].id
region_location = "eu-gb"
storage_class = "standard"
endpoint_type = "private"
allowed_ip = 10.0.0.0/8
key_protect = ibm_kms_key.flowlog_instance_root_key[count.index].id
}

**Comment by hkantare** [comment]
closing the issue the releated servicenow ticket is closed
