### ISSUE TITLE
ibm_pi_volume module fails

### ISSUE THREAD

**Issue by surajbharadwaj** [IBM-Cloud/terraform-provider-ibm#3596]
**ibm_pi_volume** **resource**  doesn't get a response after volumes are created and returns Error: failed to create a volume
But volumes are created and seen In GUI.

Basically this resource fails to get a OK response.

ibm provider version: **"1.39.0-beta0"**

Below is the code snippet.

```
resource "ibm_pi_volume" "ibm_pi_sap_volume"{
  count                = 1
  pi_volume_size       = "100"
  pi_volume_name       = "test"
  pi_volume_type       =  "tier1"
  pi_volume_shareable  = false
  pi_cloud_instance_id = data.ibm_resource_instance.sap_service.guid
}
```

Request you to 
![image (2)](https://user-images.githubusercontent.com/46653528/154374307-03098fd0-6318-40c1-9030-1751db201e50.png)
please fix this release a beta version version **1.39.0-beta1** as soon as possible. 

Thank you :)

**Comment by rmoralesjr** [comment]
Which colo were you using when the errors occurred? Thanks
