### ISSUE TITLE
PowerVS ibm_pi_instance.pi_health_status not working as expected

### ISSUE THREAD

**Issue by christopher-horn** [IBM-Cloud/terraform-provider-ibm#3610]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/community-terraform-providers/ignition v2.1.2
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.38.2

### Affected Resource(s)

* ibm_pi_instance.pi_health_status

### Terraform Configuration Files

Problem seen using the PowerVS OpenShift Terraform automation here:

https://github.com/ocp-power-automation/ocp4-upi-powervs

Problem observed when setting:
```
bastion_health_status      = "WARNING"
```

### Expected Behavior

During provisioning when the Bastion node finishes building and the IBM Cloud UI shows it in Warning state and the CLI shows status as ACTIVE and health status as PENDING or possibly also WARNING Terraform should recognize the VM creation is complete.

### Actual Behavior

What I am seeing is that Terraform does not seem to recognize the VM creation is complete until the health status transitions to OK.

### Steps to Reproduce

Setup variables for a provision and run `terraform apply` and examine what happens when VM enters Warning state.

### Important Factoids

Provisioning in tok04 using a CentOS Streams 8 image.

**Comment by yussufsh** [comment]
The VM status is different from Health Status. Please see [PVM Instance GET API](https://cloud.ibm.com/apidocs/power-cloud#pcloud-pvminstances-get) for more details. The status on GUI for vm listing page is not related to health status.

`pi_health_status` in [`ibm_pi_instance`](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_instance#pi_health_status) resource monitors health status and only monitors for `OK` or `WARNING`. Other value for example can be `PENDING`.

The vm [status](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_instance#status) can be `ACTIVE` way ahead. Other values can be `BUILD` or `ERROR`.

**Comment by christopher-horn** [comment]
Yes the problem seems to be on PowerVS side.  Deploys are not always advancing from PENDING to WARNING when the build is done and they are waiting for RMC as they are supposed to.  I have opened a ticket about that and will close this.
