### ISSUE TITLE
PowerVS VM deployment went into ERROR status but Terraform did not detect it and fail as expected

### ISSUE THREAD

**Issue by christopher-horn** [IBM-Cloud/terraform-provider-ibm#3612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v1.1.6
on linux_amd64

*    provider registry.terraform.io/community-terraform-providers/ignition v2.1.2
*    provider registry.terraform.io/hashicorp/null v2.1.2
*    provider registry.terraform.io/hashicorp/random v2.3.1
*    provider registry.terraform.io/ibm-cloud/ibm v1.38.2

### Affected Resource(s)

* ibm_pi_instance

### Terraform Configuration Files

Problem seen using the PowerVS OpenShift Terraform automation here:

https://github.com/ocp-power-automation/ocp4-upi-powervs

### Debug Output

https://gist.github.com/christopher-horn/99d47813d5f99dd3e30ee22ca7e33ebd

### Panic Output

No panic generated.

### Expected Behavior

When a VM create goes into ERROR state the Terraform provider should have immediately failed.

### Actual Behavior

The VM went into Error state in the UI, the CLI showed Status as ERROR and Health Status as CRITICAL, but Terraform did not fail.  It continued polling for nearly 55 more minutes at which point the bearer token expired and then it failed. 

### Steps to Reproduce

As you need the VM create to fail and go into an ERROR state which is not a normal scenario not sure how you can easily reproduce.

**Comment by yussufsh** [comment]
As per the logs it seems this is duplicate of https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3611.
If it isn't then please upload the configuration and logs in detail.

**Comment by christopher-horn** [comment]
I uploaded the logs.  As per my comment above the VM went into Error state and health was CRITICAL. The bearer token timeout then happened much later on. That was the same as #3611 but seemed to be a secondary issue.

**Comment by christopher-horn** [comment]
When I got bearer token error and checked the VM I found this:

```
Name                    cecc-252701-bastion-0   
CPU Cores               0   
Memory                  0   
Processor Type             
Networks                -   
Disk Size               120   
Volumes                 a89b5e70-b636-4066-9f1c-749ee51a72f8, c52071bd-1006-4a8f
-9ca3-03fe2067518c   
Storage Type            tier3   
Pin Policy              none   
Image                   3bcc6b65-5dd3-4b6a-b7bf-0e661aacf6c1   
Created                 2022-02-23T17:34:42.000Z   
Last Updated            2022-02-23T17:34:42.000Z   
Status                  ERROR   
Progress                0   
Storage Pool            Tier3-Flash-2   
Storage Pool Affinity   true   
Placement Group         none   
Fault Code              500   
Fault Message           Build of instance fea4b61f-be89-4501-b037-6ee8ff444b8b a
borted: ReadTimeout for GET http://localhost:12080/rest/api/uom/VirtualIOServer?
group=ViosFCMapping,ViosStorage: HTTPConnectionPool(host='localhost', port=12080
): Read timed out. (read timeout=1200) 
Fault Details (OMITTED DUE TO SIZE)
Last Health Update      2022-02-23T19:25:29.660299   
Health Reason           Unknown reason   
Health Status           CRITICAL 
```
As the Status was ERROR shouldn't the Terraform have failed 50 minutes before the bearer token expired?

**Comment by yussufsh** [comment]
As per crash log:
Deployment started at 2022-02-23T12:33:43.543-0500
```
2022-02-23T12:33:43.543-0500 [INFO]  Terraform version: 1.1.6
```
Crash due to token happened at (exactly 60 mins):
```
2022-02-23T13:33:53.636-0500 [ERROR] vertex "module.prepare.ibm_pi_instance.bastion[0]" error: failed to Get PVM Instance fea4b61f-be89-4501-b037-6ee8ff444b8b :[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}][500] pcloudPvminstancesGetInternalServerError  &{Code:500 Description: Error: Message:not authorized: bearer token could not be validated: Token is expired}
```


Now, as per cli o/p (+5 for zone):
```
Created                 2022-02-23T17:34:42.000Z 
Fault Date              2022-02-23T18:35:28.000Z
```

So the Terraform failed because of token at `13:33:53`+5(=18.33.53) and VM went into error at `18:35:28`. So you were couple of minutes late to check the cli output.

Hope that helps. Otherwise Terraform throws `failed to create the lpar` error message when the vm status is `ERROR`.

**Comment by christopher-horn** [comment]
Oh wow, it took that long to go into error!  Okay, closing this too then.
