### ISSUE TITLE
Link from documentation pointing at 404

### ISSUE THREAD

**Issue by dobharweim** [IBM-Cloud/terraform-provider-ibm#3615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_cos_bucket

### Description

The [ibm_cos_bucket](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cos_bucket) documentation page contains a hyperlink for ibm_resource_instance pointing at a [page](https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-resource-mgmt-resources#resource-instance) which does not exist . I believe it should be pointing at the provider documentation page for the resource [here](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/resource_instance).

The relevant text on the page is:

> To create a bucket, you must provision an IBM Cloud Object Storage instance first by using the [ibm_resource_instance](https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-resource-mgmt-resources#resource-instance) resource.

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

--->
### References

* #0000

**Comment by IBM-diksha** [comment]
Closing the ticket as this has been fixed in v1.52.0 version.
