### ISSUE TITLE
ibm_pi_instance : Not able to create instance with 0.25 processors.

### ISSUE THREAD

**Issue by surajbharadwaj** [IBM-Cloud/terraform-provider-ibm#3618]
From GUi we can create instances with 0.25 cores on s922 machine. But via terraform its not possible, 

Throws an error:
`
│ Error: failed to provision: failed to Create PVM Instance :[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances][400] pcloudPvminstancesPostBadRequest  &{Code:0 Description:bad request: invalid parameters values: dedicated processor value must be a whole number (requested 0.25) Error:bad request Message:}`

Please accommodate the **whole number to decimal number change** as well for the attribute **pi_processors**

**Comment by yussufsh** [comment]
Looks like the error is coming from the API response from the Power cloud service. Can you please provide more information for debugging this?

**Comment by surajbharadwaj** [comment]
Just try this basic block :

`resource "ibm_pi_instance" "sap" {
  pi_cloud_instance_id     = "blah"
  pi_instance_name         = "test"
  pi_image_id              = "blah"
  pi_processors            = "1"   <---- works. "0.25", 0.25 doesnt work.
  pi_memory                = "2"
  pi_sys_type              = "dedicated"
  pi_proc_type             = "s922"
  pi_key_pair_name         = "blah"
  
  dynamic "pi_network" {
      for_each = tolist(data.ibm_pi_network.get_private_nets.*.id)
      content {
         network_id = pi_network.value
              }
  }

}`

**Comment by yussufsh** [comment]
> Just try this basic block :
> 
> resource "ibm_pi_instance" "sap" { pi_cloud_instance_id = "blah" pi_instance_name = "test" pi_image_id = "blah" pi_processors = "1" <---- works. "0.25", 0.25 doesnt work. pi_memory = "2" pi_sys_type = "dedicated" pi_proc_type = "s922" pi_key_pair_name = "blah"
> 
> dynamic "pi_network" { for_each = tolist(data.ibm_pi_network.get_private_nets.*.id) content { network_id = pi_network.value } }
> 
> }

Is it for any Linux image? Or is it specific to sap because I see that name.

**Comment by yussufsh** [comment]
Ah I see you are using dedicated type. Hence the error message `dedicated processor value must be a whole number`
So you are saying this is possible via GUI? I will check this anyway.

**Comment by yussufsh** [comment]
![IMG_20220228_225949](https://user-images.githubusercontent.com/17543270/156030145-b33f8dfd-0b3f-44ea-924b-5f5f78f30309.jpg)
Hope this explains the reason of the error.

**Comment by surajbharadwaj** [comment]
Ahh. Sorry my bad. I was using dedicated. It's available for shared uncapped. Sorry for the confusion.
