### ISSUE TITLE
ibm_kms_key operations fail behind a corporate proxy

### ISSUE THREAD

**Issue by aquavoyager** [IBM-Cloud/terraform-provider-ibm#3635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
terraform-provider-ibm_v1.38.2 
```

### Affected Resource(s)

* ibm_kms_key

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_kms_key" "storage_key" {
  instance_id  = var.hpcs_id
  key_name     = var.storage_key_name
  standard_key = false
  force_delete = true
}
```

### Debug Output

[https://gist.github.com/aquavoyager/8f8553ecd0a0cc1129e933006b51609a#file-ibm_kms_key-proxy-tflog](https://gist.github.com/aquavoyager/8f8553ecd0a0cc1129e933006b51609a#file-ibm_kms_key-proxy-tflog)

### Expected Behavior

The plugin successfully creates the ibm_kms_key resource

### Actual Behavior

The plugin did not successfully create the ibm_kms_key resource. Fails to resolve the api endpoint
However, other resources are created fine or endpoints like iam and rc are reached fine
Curl requests to the same endpoint respect the http/https proxy setting in the env. 
It seems the plugin isn't using a proxy env to access KMS api for HPCS.

```
$ export HTTP_PROXY=""
$ export HTTPS_PROXY=""
$ curl -X GET https://api.us-south.hs-crypto.cloud.ibm.com:9447/api/v2/keys -H "authorization: Bearer <TOKEN>" -H "bluemix-instance: 0913f457-87e2-402d-a0eb-1aaXXXXe394" -H "accept: application/vnd.ibm.kms.key+json"
curl: (6) Could not resolve host: api.us-south.hs-crypto.cloud.ibm.com

$ export HTTP_PROXY="<proxy>"
$ export HTTPS_PROXY="<proxy>"
$ curl -X GET https://api.us-south.hs-crypto.cloud.ibm.com:9447/api/v2/keys  -H "authorization: Bearer ${TOKEN}" -H "bluemix-instance: 0913f457-87e2-402d-a0eb-1aaXXXXe394" -H "accept: application/vnd.ibm.kms.key+json"
{"metadata":{"c........}
```

### Steps to Reproduce

1. export http_proxy=<corporate.proxy.local>
2. export https_proxy=<corporate.proxy.local>
3. terraform apply

### Important Factoids

Simple terraform for ibm_kms_key, ran behind a corporate proxy.

### References

Older issue : previously reported similar behaviour on internal repo and was fixed :
https://github.ibm.com/csenablement/hamiltondefects/issues/140
and believe this is the corresponding fix that was added,
https://github.com/IBM-Cloud/terraform-provider-ibm/commit/8ce79219b3d07a743ea3823b5393325b0487ce26
but the recent version of plugin stopped working and running into the issue again

**Comment by hkantare** [comment]
I think there was some migration happend to fix multiple instance keys provision where the fix was not ported..We are working https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3634.

Can you let us know do we need the binary released immediatley or can they use the old binary

**Comment by aquavoyager** [comment]
@hkantare we will need it in the next minor release. Thanks.

**Comment by hkantare** [comment]
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.39.2
