### ISSUE TITLE
ibm_is_ssh_key is not working as expected!

### ISSUE THREAD

**Issue by pmgl0935** [IBM-Cloud/terraform-provider-ibm#3639]
I'm using Terraform v1.1.6 and IBM Cloud provider v 1.39.1.
When running this TF code:
```
terraform {
  required_providers {
    ibm = {
      source = "ibm-cloud/ibm"
    }
    tls = {
      source = "hashicorp/tls"
    }
  }
}
variable "ibmcloud_api_key" {
  default = ""
}
provider "ibm" {
  region           = "eu-de"
  ibmcloud_api_key = var.ibmcloud_api_key
}
resource "tls_private_key" "key_root" {
  algorithm = "RSA"
  rsa_bits  = 4096
}
resource "ibm_is_ssh_key" "ssh_key_root" {
  name           = "miic-dummy"
  public_key     = tls_private_key.key_root.public_key_openssh
}

```
The problem is:
- The first time the resource ibm_is_ssh_key is created when I run terraform apply.
- If I run a second time this code with terraform apply, the  resource ibm_is_ssh_key is deleted and created again

Sample (of second run):
ibm_is_ssh_key.ssh_key_root: Destroying... [id=r010-1d4b1383-33d2-47f7-931b-ec2096fdfc5d]
ibm_is_ssh_key.ssh_key_root: Destruction complete after 4s
ibm_is_ssh_key.ssh_key_root: Creating...
ibm_is_ssh_key.ssh_key_root: Creation complete after 1s [id=r010-eee3295c-28e8-4e3a-812d-38192181f4f0]

**Comment by deepaksibm** [comment]
Hi @pmgl0935, 
    
       The APIs used in ibm_is_ssh resource returns public_key value that is trimmed already, and so, terraform detects a change as tls_private_key.key_root.public_key_openssh has a new line character in it. Terraform looks at it as a change and there is nothing that can be done from the provider's side for it.
The best way to go about this is to use trimspace function, or to use lifecycle ignore changes tags in the terraform config

**Comment by ujjwal-ibm** [comment]
https://github.com/hashicorp/terraform-provider-tls/issues/163
