### ISSUE TITLE
ibm_pi_instance, tier 3 stock image not found

### ISSUE THREAD

**Issue by surajbharadwaj** [IBM-Cloud/terraform-provider-ibm#3642]
Hi,

I would like you guys to fix the **ibm_pi_instance** resource.

background (via GUI)
1. Lets assume a new pvs service is created.
2. Boot images section is empty
3.  Click create instance--->Select HANA or netweaver os image--->Select SLES/RHEL Image.
4. Click create 

What happens in GUI background:
When create is triggered, it checks if there is a boot image existing already under boot image section. Since it doesnt exist it will make a copy of boot image and thus a entry is seen in boot image section. Using this boot image an instance is created in chosen tier of choice.
Next time you want to create a new instance with same image:
GUi background checks if the image exists in boot images section and it finds it . it doesnt make a copy , instead uses this image and creates instance.

Power of GUI: Since there is a copy of image from image catalog done automatically , we can deploy instances in any tier

Terraform:
1.using data block catalog_images, we get the id of image.
2. we pass this to ibm_pi_instance and create.

**terraform is not creating a copy of image automatically, it is doing something different and we can create an instance only in same tier as the catalog image tier otherwise you get an error.**  
Able to create an instance by specifying cores, mem, etc.
**Not able to create an instance by setting pi_sap_profile_id attribute** and you get the error put in comment below

Power of Terraform: extra copy is avoided.
Cons of terraform: **Cannot create instance in tier of our choice**

Suggestion: **Please change the module ibm_pi_instance working so that copy and check of catalog images is done automatically in the backend.**

**Comment by surajbharadwaj** [comment]
[pvs_sap.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/8186566/pvs_sap.txt)
Variables:
PVS_HANA_IMAGE_NAME          = "Linux-SUSE-SAP-12-4"
PVS_HANA_HOSTNAME            = "HANA"
PVS_HANA_SAP_PROFILE_ID      = "ush1-4x128"
PVS_HANA_MEMORY              = "256"
PVS_HANA_PROCESSORS          = "4"
PVS_HANA_PROC_TYPE           = "dedicated"
PVS_HANA_SYS_TYPE            = "e980"
PVS_HANA_PRIVATE_NET_NAMES   = ["mgmt_net","sap_net","bkp_net"]
HANA_DISKS_CONFIGURATION     = {
                                 disks_size = "160,150,300,50"
                                 counts = "8,8,1,1"
                                 names  = "data,log,shared,usrsap"
                                 paths  = "/hana/data,/hana/log,/hana/shared,/usr/sap"
                               }

**Comment by surajbharadwaj** [comment]
Error:
 Error: failed to provision: failed to Create SAP Instance: [POST /pcloud/v1/cloud-instances/{cloud_instance_id}/sap][400] pcloudSapPostBadRequest  &{Code:0 Description:bad request: cloud instance 260336c18733496094cb665c8747ba81 does not have access to image b7fb78d5-0466-42c8-bb00-d89bb9afda7d Error:bad request Message:}
│
│   with module.pvs_hana.ibm_pi_instance.sap,
│   on ..\..\modules\pvs_sap\pvs_sap.tf line 38, in resource "ibm_pi_instance" "sap":
│   38: resource "ibm_pi_instance" "sap" {
│
╵

**Comment by yussufsh** [comment]
`ibm_pi_instance` is a Terraform resource to create a VM. Image copy is a different resource `ibm_pi_image` is available for copying the image from stock to service instance. `ibm_pi_instance` takes image id which needs to be the catalog image id as per all the discussion we had.
The same logic provided by GUI is possible via Terraform configurations that I have already provided with an example in this channel before.
GUI does the extra piece of work not only during VM provision but at other places as well such as re-using the public network if already present for example. And you won't be able to copy image from stock list manually from GUI. Hence it is not best to compare with it. Same stands true for CLI, REST APIs, Go SDK.
I am not saying we cannot do it from Terraform provider but I would not like Terraform provider doing extra work here. It is not just about adding simple lines of code but also handling the parallelism on image copy task as well inside pvm instance flow.
Since a possible flow is available to be worked with the current Terraform provider, we will take some time for discussion within the team to go ahead what UI is doing or not.

**Comment by surajbharadwaj** [comment]
So steps that needs to be followed for 2 scenarios :
For green field workflow:
Pvs(make copy of required images for user for deployment)
Create_instance module (takes in image name) and creates instance
For brown field workflow (just deploy instance to exisiting PVS):
pvs_import_image(make copy of required images if not present in PVS boot images for user for deployment)
Create_instance module (takes in image name) and creates instance
So a new module pvs_import_image has to be created (check if image is present in cloud instance else make a copy from catalog image).

**Comment by yussufsh** [comment]
@surajbharadwaj let us know if we can close this issue based on the explanation given above.

**Comment by surajssb** [comment]
```
main.tf:

module "import-image" {
  source                         = "./power-image-import"
  count                          = var.brownfield ? 1 : 0

  pvs_zone                       = var.pvs_zone
  pvs_resource_group_name        = var.pvs_resource_group_name
  pvs_service_name               = var.pvs_service_name
  pvs_image_name                 = var.pvs_instance_image_name
}

module "instance-sap" {
  source                         = "./power-instance"
  depends_on                     = [module.import-image]
  
  pvs_zone                       = var.pvs_zone
  pvs_resource_group_name        = var.pvs_resource_group_name
  pvs_service_name               = var.pvs_service_name
  pvs_instance_hostname          = var.pvs_instance_hostname
  pvs_sshkey_name                = var.pvs_sshkey_name
  pvs_instance_image_name        = var.pvs_instance_image_name
  pvs_instance_profile_id        = var.pvs_instance_profile_id
  pvs_instance_sys_type          = var.pvs_instance_sys_type
  pvs_instance_proc_type         = var.pvs_instance_proc_type
  pvs_instance_processors        = var.pvs_instance_processors
  pvs_instance_memory            = var.pvs_instance_memory
  pvs_instance_private_net_names = var.pvs_instance_private_net_names
  pvs_instance_storage_config    = var.pvs_instance_storage_config
}
```
The above is contents of main .tf which uses 3 internal sub modules. These are made into one module called power-sap-instance.


now when i use the above module in example like this where i create one new subnet and wait for it to be created and then use:
```
provider "ibm" {
  region    =   var.pvs_region
  zone      =   var.pvs_zone
  ibmcloud_api_key = var.ibmcloud_api_key != null ? var.ibmcloud_api_key : null
}

locals {
  service_type = "power-iaas"
}

data "ibm_resource_group" "resource_group_ds" {
  name = var.pvs_resource_group_name
}

data "ibm_resource_instance" "pvs_service_ds" {
  name                 = var.pvs_service_name
  service              = "power-iaas"
  location             = var.pvs_zone
  resource_group_id    = data.ibm_resource_group.resource_group_ds.id
}

resource "ibm_pi_network" "sap_net2" {
  
  pi_cloud_instance_id = data.ibm_resource_instance.pvs_service_ds.guid
  pi_network_name      = "sap_net222"
  pi_cidr              = "10.79.1.1/24"
  pi_dns               = ["127.0.0.1"]
  pi_network_type      = "vlan"
  pi_network_jumbo     = true
}

module "hana" {
  // source = "terraform-ibm-modules/powervs/ibm//modules/power-sap-instance"
  source = "../../modules/power-sap-instance"
  depends_on                     = [ibm_pi_network.sap_net2]
  pvs_zone                       = var.pvs_zone
  pvs_resource_group_name        = var.pvs_resource_group_name
  brownfield                     = var.brownfield
  pvs_service_name               = var.pvs_service_name
  pvs_instance_hostname          = var.pvs_instance_hostname
  pvs_sshkey_name                = var.pvs_sshkey_name
  pvs_instance_image_name        = var.pvs_instance_image_name
  pvs_instance_profile_id        = var.pvs_instance_profile_id
  pvs_instance_private_net_names = concat(var.pvs_instance_private_net_names, formatlist("sap_net222"))
  pvs_instance_storage_config    = var.pvs_hana_instance_storage_config
}

module "netweaver" {
  // source = "terraform-ibm-modules/powervs/ibm//modules/power-sap-instance"
  source = "../../modules/power-sap-instance"
  count                          = 3
  depends_on                     = [ibm_pi_network.sap_net2]
  pvs_zone                       = var.pvs_zone
  pvs_resource_group_name        = var.pvs_resource_group_name
  brownfield                     = var.brownfield
  pvs_service_name               = var.pvs_service_name
  pvs_instance_hostname          = "nw-${count.index + 1}"
  pvs_sshkey_name                = var.pvs_sshkey_name
  pvs_instance_image_name        = var.pvs_instance_image_name
  pvs_instance_sys_type          = "s922"
  pvs_instance_proc_type         = "dedicated"
  pvs_instance_processors        = "3"
  pvs_instance_memory            = "200"
  pvs_instance_private_net_names = concat(var.pvs_instance_private_net_names, formatlist("sap_net2"))
  pvs_instance_storage_config    = var.pvs_nw_instance_storage_config
  
}
```

When i want this flow where i am creating a new network and using **power-sap-instance** module ( which inturn uses, image and instnace submodule, the pvs_import_image module is hitting error because of count and depends_on attribute. 




I think this import image from catalog should happen internally in ibm_pi_instance resource itself

**Comment by surajsbharadwaj** [comment]
![image](https://user-images.githubusercontent.com/101711050/171868729-222d90a8-7301-4a6d-b6a8-05b3d4684421.png)
Below is a piece of code to import images if not present. This code is sitting in module import-image.

When i create an instance using another module, i make use of import-image module before this.
Lets assume terraform errors in some step in between in create instance module. When i run terraform apply again, it wants to destroy the image imported and the instance module.( Reason : As the image is already imported in step 1  terraform apply, the local variable image local.image is now 0 and hence resource ibm_pi_image has to be destroyed.)
Therefore i request you to handle the import images in **ibm_pi_instance** internally in go code

`locals {
  service_type          = "power-iaas"
}

data "ibm_resource_group" "resource_group_ds" {
  name = var.pvs_resource_group_name
}

data "ibm_resource_instance" "pvs_service_ds" {
  name                 = var.pvs_service_name
  service              = local.service_type
  location             = var.pvs_zone
  resource_group_id    = data.ibm_resource_group.resource_group_ds.id
}

data "ibm_pi_images" "exisiting_images_ds" {
  pi_cloud_instance_id = data.ibm_resource_instance.pvs_service_ds.guid
}

data "ibm_pi_catalog_images" "catalog_images_ds" {
  sap                  = true
  pi_cloud_instance_id = data.ibm_resource_instance.pvs_service_ds.guid
}

locals {
  image = [for x in data.ibm_pi_images.exisiting_images_ds.image_info : x if x.name == var.pvs_image_name]
  catalog_image = [for stock_image in data.ibm_pi_catalog_images.catalog_images_ds.images : stock_image if stock_image.name == var.pvs_image_name]
}

resource "ibm_pi_image" "image" {
  count                = length(local.image) == 0 ? 1 : 0
  pi_cloud_instance_id = data.ibm_resource_instance.pvs_service_ds.guid
  pi_image_id          = local.catalog_image[0].image_id
  pi_image_name        = var.pvs_image_name
  

}`

**Comment by surajsbharadwaj** [comment]
This can be closed
