### ISSUE TITLE
ibm_cloud_shell_account_settings IAM issue

### ISSUE THREAD

**Issue by jpmonge86** [IBM-Cloud/terraform-provider-ibm#3654]
### Affected Resource(s)

* ibm_cloud_shell_account_settings

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

# Data source to get account settings
data "ibm_iam_account_settings" "iam_account_settings" {
}

# Data source to get shell settings
data "ibm_cloud_shell_account_settings" "cloud_shell_account_settings" {
  account_id = data.ibm_iam_account_settings.iam_account_settings.account_id
}

variable "shell_settings_enabled" {
  description = "Enable global shell settings to all users in the account"
  type        = bool
  default     = false
}

resource "ibm_cloud_shell_account_settings" "cloud_shell_account_settings" {
  rev        = data.ibm_cloud_shell_account_settings.cloud_shell_account_settings.rev
  account_id = data.ibm_iam_account_settings.iam_account_settings.account_id
  enabled    = var.shell_settings_enabled
}
```

### Debug Output

(https://gist.github.com/jpmonge86/2fbbaac07db50a1582fa345d02c944b0)

### Expected Behavior

Shell settings get processed and applied

### Actual Behavior

An error with an unknown account is reported.

`error: GetAccountSettingsWithContext failed User 'IBMid-666000KAO3' doesn't have the account 'bac0df06b644a9cabc6e44f55b3880e
`
### Steps to Reproduce

1. `terraform apply`

**Comment by jpmonge86** [comment]
Just realized that what appears to be happening is  that shell settings is pulling an incomplete account ID, where the first character missing

Actual account ID >

`abac0df06b644a9cabc6e44f55b3880e`

What shell reports >
`bac0df06b644a9cabc6e44f55b3880e`

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.39.2

**Comment by jpmonge86** [comment]
Thanks @hkantare. Confirmed issue was fixed.
