### ISSUE TITLE
IAM Access-group support in the roadmap?

### ISSUE THREAD

**Issue by jmgalvez** [IBM-Cloud/terraform-provider-ibm#367]
Hi there,

Is it planned to add support for IAM access-group-* (including access-groups policies) in the upcoming releases? 

Thank you in advance.

**Comment by hkantare** [comment]
Yes we are planning to prioritize this item in future

**Comment by jmgalvez** [comment]
Thank you very much @hkantare for your feedback.

**Comment by hkantare** [comment]
The support for IAM access groups are provided in v0.12.0

IBM IAM Access Group (ibm_iam_access_group)
IBM IAM Access Group Members (ibm_iam_access_group_members)
IBM IAM Access Group Policy (ibm_iam_access_group_policy)

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0
