### ISSUE TITLE
Enable the end point attribute in the provider (SoftlayerRestEndpoint) in order to connect to Gov Cloud

### ISSUE THREAD

**Issue by zitroij** [IBM-Cloud/terraform-provider-ibm#368]
Hello,

We include the terraform provider for ibm cloud in Cloud Automation Manager.  We have been getting request to support IBM Cloud for Government, more specifically federal government.

Since the provider already allows for the SL username and apices, will it be possible to enable the endpoint as a provider variable, this will allow the templates to access the federal end point or update the region to include glov cloud, and combine that with the SL username/apikey.

We are getting multiple request in CAM and will like to see what is possible.

**Comment by hkantare** [comment]
@zitroij As per the requirement and slack discussion in below thread `https://ibm-cloudplatform.slack.com/archives/C2DB7A7LY/p1537386698000100` 
we will be exposing provider level argument `softlayer_api_url`  or (SL_API_URL or SOFTLAYER_API_URL enivronmental variables) which by default points to https://api.softlayer.com/rest/v3

**Comment by zitroij** [comment]
Thanks, I just wanted to formally request and log the requirement.

**Comment by hkantare** [comment]
We made the fix to enable softlayer endpoint available at provider level argument in master branch
https://github.com/IBM-Cloud/terraform-provider-ibm. You can give a try from latest master branch until we release in next provider.

**Comment by hkantare** [comment]
Fix is available as part of v0.12.0 .Can you please test with latest provider https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0
