### ISSUE TITLE
Security Group Rules IP missing

### ISSUE THREAD

**Issue by PKehnel** [IBM-Cloud/terraform-provider-ibm#3695]
Hey, 

when using the command: 
```
data "ibm_is_security_group_rules" "example" {
  security_group = ibm_is_security_group.example.id
}
```
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_security_group_rules

the `ID` is **always** empty. (- (String) The unique identifier for this security group rule)

When running the same from cli: 
`ibmcloud is security-group-rules`

the `ID` is **not** empty.

**Comment by astha-jain** [comment]
Hi @PKehnel Please help me understand what ID are you referring to in CLI which is not empty.

**Comment by PKehnel** [comment]
_id_ The unique identifier for this security group rule (as stated)

Just click on the link: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_security_group_rules:

then scroll down to find the attribute id for security group rule.

**Comment by deepaksibm** [comment]
Hi @PKehnel which version of the provider are you using ? I am able to the see the 'id' of each rule in a security group with this data source.

**Comment by PKehnel** [comment]
Ahh you are using the beta. 
If you use the normal install you dont get the beta, and yes from the changelog file it seems fixed in the Beta.
