### ISSUE TITLE
Terraform crash with connection is shut down

### ISSUE THREAD

**Issue by sshingarapu** [IBM-Cloud/terraform-provider-ibm#372]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.5

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_compute_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
https://gist.github.com/sshingarapu/2cf3f892972dd89ff5569c2c6c161c6e 

We have been observed that the terraform is getting crashed with errors: "connection is shut down" while applying terraform apply with increasing the count value in existing resource definition in ibm_compute_instance.

Few days back, we spun up machines with count=3 in the resource ibm_compute_resource. Now we would like to use the same resource definition with created terraform.tfstate and count=7. But we are getting terraform crash issue. Please find the attached debug output for the same.

**Comment by hkantare** [comment]
Can you please provide the sample configuration of VM

**Comment by sshingarapu** [comment]
Hi,

Below is the configuration using of VM

module "appnodes01" {
  source = "./modules/casaas-terraform-modules/casaas-bmx-instance"

  domain = "${var.domain_name}"


  image_name                 =  "CASaaS-Local-RedHat-7-updated-on-20180730"

  datacenter = ["dal12", "dal13"]

  hostname = "${var.hostname}"

  instance_count = "7"

  instance_group_name = "OSHNodeApp"

  flavor_key_name = "B1_2X8X100"

  network_speed = "100"

  disks = [200, 100]

  private_subnet                                    =  "${module.security_groups.app }"


  private_security_group_ids = ["${module.security_groups.security-group-ids-app }"]

          private_network_only   =  "true"

  user_data    =   "${data.template_file.appnodes01-user-data.rendered}"


}

module definition:
============

resource "ibm_compute_vm_instance" "instance" {
  count             = "${var.instance_count}"
  hostname          = "${local.full_label}-${var.instance_group_name}${count.index+1}"
  domain            = "${var.domain}"
  #os_reference_code = "${var.os_reference_code}"
  image_id = "${data.ibm_compute_image_template.image.id}"
  #datacenter        = "${var.datacenter}"
  datacenter        = "${element(var.datacenter, count.index)}"
  network_speed     = "${var.network_speed}"
  private_network_only = "${var.private_network_only}"
  #private_network_only = false
  private_subnet = "${element(var.private_subnet, count.index)}"
  local_disk = false
  flavor_key_name = "${var.flavor_key_name}"
  disks = ["${var.disks}"]
  #ssh_key_ids = ["${data.ibm_compute_ssh_key.ssh_key.id}"]
  private_security_group_ids = ["${var.private_security_group_ids}"]
  public_security_group_ids = ["${var.public_security_group_ids}"]
  user_metadata = "${var.user_data}"
  tags = ["${var.tags}"]
}

Please let me know if you need any more details.

**Comment by hkantare** [comment]
Which  version of terraform provider ibm  you are using? The resources VM is created using image <CASaaS-Local-RedHat-7-updated-on-20180730> not the os_reference_code and the image is windows or linux? Can you please share me the outptu by running
`https://api.softlayer.com/rest/v3/SoftLayer_Virtual_Guest/62348801.json?objectMask=mask[blockDevices[diskImage]]`
replace 62348801 with the id of your vm instance

**Comment by sshingarapu** [comment]
Hi,

We are using IBM Cloud Provider version 0.11.0.
The image we are using is linux image and the above resource definition has count which will create couple of machines. Also can you please tell me how to get vm ID.

**Comment by sshingarapu** [comment]
I ran the above given command for one of the instance and attaching the output of it.


[59958673.json.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/2469397/59958673.json.txt)

**Comment by hkantare** [comment]
Thanks for sharing the log,but any way we made a fix a day ago may be that should help to fix the issue. We are releasing v0.12 provider tomorrow may be you can test with that version and let us know.

**Comment by hkantare** [comment]
Can you please test with latest provider https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0

**Comment by hkantare** [comment]
closing the issue..If issue still exists please reopen it.
