### ISSUE TITLE
ibm_container_vpc_worker_pool cloud_pak entitlement does not work

### ISSUE THREAD

**Issue by Nashluffy** [IBM-Cloud/terraform-provider-ibm#3720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_container_vpc_worker_pool

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
Nash $ cat main.tf
terraform {
  required_version = "~> 1.0.0"
  required_providers {
    ibm = {
      source  = "ibm-cloud/ibm"
      version = "~> 1.36.0"
    }
  }
}
provider "ibm" {
  region = "us-south"
}

data "ibm_resource_group" "resource_group" {
  name = "..."
}

resource "ibm_container_vpc_worker_pool" "test_pool" {
  cluster          = "dev...."
  worker_pool_name = "example"
  entitlement      = "cloud_pak"
  flavor           = "c2.2x4"
  vpc_id           = "r006-....."
  worker_count     = "1"

  zones {
    name      = "us-south-1"
    subnet_id = "0717...."
  }
}
```

### Debug Output
The worker pool flavor is invalid intentionally so no resources get created, I just wanted to see the API call. 
```
2022-04-11T09:31:19.586-0400 [INFO]  Starting apply for ibm_container_vpc_worker_pool.test_pool
2022-04-11T09:31:19.586-0400 [DEBUG] ibm_container_vpc_worker_pool.test_pool: applying the planned Create change
2022-04-11T09:31:19.587-0400 [INFO]  provider.terraform-provider-ibm_v1.36.0: 2022/04/11 09:31:19 [DEBUG] setting computed for "labels" from ComputedKeys: timestamp=2022-04-11T09:31:19.587-0400

REQUEST: [2022-04-11T09:31:19-04:00]
POST /global/v2/vpc/createWorkerPool HTTP/1.1
Host: containers.cloud.ibm.com
Accept: application/json
Accept-Language: en
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: Bluemix-go SDK 0.1 / darwin
X-Auth-Refresh-Token: [PRIVATE DATA HIDDEN]
X-Auth-Resource-Account:
X-Auth-Resource-Group:
X-Original-User-Agent: terraform-provider-ibm/1.36.0

{"cluster":"dev...","entitlement":"","flavor":"c2.2x4","name":"...","vpcID":"r006...","workerCount":1,"zones":[{"id":"us-south-1","subnetID":"071...."}]}

RESPONSE: [2022-04-11T09:31:23-04:00] Elapsed: 3744ms
HTTP/1.1 400 Bad Request
```

### Expected Behavior

The entitlement field should be set to `cloud_pak` in the API call to the containers API

### Actual Behavior

The `entitlement` field in the body of the request was empty

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by hkantare** [comment]
After looking into log we see you are using 1.36.0 and it fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.38.0
