### ISSUE TITLE
Inconsistent repository path, import path

### ISSUE THREAD

**Issue by kalbasit** [IBM-Cloud/terraform-provider-ibm#373]
Hello,

This repository is clonable using the path `github.com/IBM-Cloud/terraform-provider-ibm` yet all the Go imports are using the `github.com/terraform-providers/terraform-provider-ibm` import path. Why the inconsistency here? This has many downsides:
- repo not gettable
- breaks assumptions about go repositories [example](https://github.com/NixOS/nixpkgs/blob/de39960f6f0cbfdf8224a7ce1523b3c000ec3199/pkgs/applications/networking/cluster/terraform/providers/default.nix#L9).

Thanks!

**Comment by hkantare** [comment]
we had plan to move this to github.com/terraform-providers/terraform-provider-ibm
that is where major terraform providers reside..
Hence we have stated this explicity in the `Building The Provider` in readme

**Comment by kalbasit** [comment]
I see. Is it going to be moved to terraform-providers soon? if not, will you accept a PR to fix it in the meantime?

**Comment by hkantare** [comment]
May I know why you are using go get ...to download the code .We have binaries available already to use and we also have docker image available to pull   docker pull ibmterraform/terraform-provider-ibm-docker.. `https://github.com/IBM-Cloud/terraform-provider-ibm-docker`

**Comment by kalbasit** [comment]
Sure. I'm using [NixOS](https://nixos.org) which does not adhere to the FHS that we are used to in Linux distributions, for instance, there's no /usr/lib, /usr/bin, etc... This means that most binaries compiled for Linux do not work on NixOS, even though this specific repo actually does since the binary is statically compiled without CGO linking, we still want to compile all packages from source code.

Nevertheless, Terraform providers are automatically compiled given a [template](https://github.com/NixOS/nixpkgs/blob/312c41c3c4aaa77b70ce4ce2fbaf96dc9e678e3c/pkgs/applications/networking/cluster/terraform/providers/default.nix#L5-L18) and a [list of providers](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/terraform/providers/data.nix). Unfortunately, because of this inconsistency, this provider does not fit the template and is provided [outside the list](https://github.com/NixOS/nixpkgs/blob/312c41c3c4aaa77b70ce4ce2fbaf96dc9e678e3c/pkgs/applications/networking/cluster/terraform-provider-ibm/default.nix).

Although this is not a major issue, it does confuse a lot of NixOS users, for instance, if my repository requires terraform with AWS support, I will have the following shell.nix in my repo:

```nix
let
  hostPkgs = import <nixpkgs> {};
  # Look here for information about how to generate `nixpkgs-version.json`.
  #  → https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs
  pinnedVersion = hostPkgs.lib.importJSON ./.nixpkgs-version.json;
  pinnedPkgs = import (hostPkgs.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    inherit (pinnedVersion) rev sha256;
  }) {};
in

# This allows overriding nixpkgs by passing `--arg nixpkgs ...`
{ nixpkgs ? pinnedPkgs }:

nixpkgs.mkShell {
  buildInputs = with nixpkgs; [
    (terraform.withPlugins (ps: [
      ps.aws
    ]))
  ];
}
```

Now, if I want to install the ibm provider, as a user I would expect to install it via `ps.ibm`, but instead, I have to install it via `nixpkgs.terraform-provider-ibm` as such:

```nix
let
  hostPkgs = import <nixpkgs> {};
  # Look here for information about how to generate `nixpkgs-version.json`.
  #  → https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs
  pinnedVersion = hostPkgs.lib.importJSON ./.nixpkgs-version.json;
  pinnedPkgs = import (hostPkgs.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    inherit (pinnedVersion) rev sha256;
  }) {};
in

# This allows overriding nixpkgs by passing `--arg nixpkgs ...`
{ nixpkgs ? pinnedPkgs }:

nixpkgs.mkShell {
  buildInputs = with nixpkgs; [
    (terraform.withPlugins (ps: [
      ps.aws
      nixpkgs.terraform-provider-ibm
    ]))
  ];
}
```

Fixing the import path of this repo, would help with the confusion on nixpkgs side without having to do the work to patch it on our side, and would also make the project Go-idiomatic. For instance, have you tried to go over the API of this project on [godoc.org](https://godoc.org/github.com/IBM-Cloud/terraform-provider-ibm)? None of the packages, besides main.go, are visible because it can't really see them.

**Comment by hkantare** [comment]
Thanks..for sharing the information ...If you are interested you can gohead and raise the PR .I think the movement to terraform-providers is not in near future...
