### ISSUE TITLE
ibm_is_instance docs need better description of instance_template

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3741]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_is_instance

### Docs

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance#instance_template

![image](https://user-images.githubusercontent.com/6932057/164758907-e58fc993-4787-4167-b1ec-30052c21804a.png)

This is the id of an ibm_is_instance_template:

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance_template

I could not figure this out.   The words "id of the source template" is not specific enough.

**Comment by hkantare** [comment]
Fixed in latest release

**Comment by astha-jain** [comment]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance#instance_template
