### ISSUE TITLE
Docs ibm_is_instance argument primary_network_interface is required

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3742]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_is_instance

### terraform version
```
tf2 $ tf version
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.40.1

Your version of Terraform is out of date! The latest version
is 1.1.9. You can update by downloading from https://www.terraform.io/downloads.html
```
### Docs and Diagnostics

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance#primary_network_interface

The primary network interface claims to be Optional.  But if omitted:

```
tf2 $ tfa
╷
│ Error: Missing required argument
│
│   with ibm_is_instance.onprem,
│   on onprem.tf line 46, in resource "ibm_is_instance" "onprem":
│   46:   image          = data.ibm_is_image.os.id
│
│ "image": all of `image,keys,primary_network_interface,profile,vpc,zone` must be specified
╵
```

If there is a special case where these are optional (instance_template?) then that needs to be described in the docs.  

Better diagnostics should be provided by the provider.

Expected, something like:

```
44: resource "ibm_is_instance" "onprem" {

primary_network_interface must be specified or a instance_template with a primary_network_interface must be supplied
```

Actual:

```
warning above, "imag": all of ....
```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by powellquiring** [comment]
Take a careful look at image,keys,primary_network_interface,profile,vpc,zone

**Comment by ujjwal-ibm** [comment]
#3747

**Comment by astha-jain** [comment]
Are we good to close? @powellquiring

**Comment by powellquiring** [comment]
Is this in production?  Or where can I try it out and see the docs?

**Comment by ujjwal-ibm** [comment]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance#primary_network_interface
