### ISSUE TITLE
Hostname(Name ) of the local load balancer is not set in resource

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#375]
Hi All,

The local load balancer name is not set in terraform provider. we need that name in out terraform tfstate file so.we have added it in create and read functionality in our code. please add it in your repo.

Take new parameter name as computed=true

add into resourceIBMLbCreate()
d.Set("name", loadBalancer.LoadBalancerHardware[0].Hostname)

add into resourceIBMLbRead()
d.Set("name", vip.LoadBalancerHardware[0].Hostname)

Fixed with following PR
https://github.com/gsl-broker/terraform-provider-ibm/pull/50

**Comment by M-Rushabh** [comment]
@hkantare I have fix the issue in our repo you need to add this in your code.

**Comment by hkantare** [comment]
Fix is available as part of v0.12.0 .Can you please test with latest provider https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0
