### ISSUE TITLE
ibm_pi_cloud_connection_network_attach vpc id not supported

### ISSUE THREAD

**Issue by surajssb** [IBM-Cloud/terraform-provider-ibm#3766]
Hi,

Thank you for creating this resource. Apparently it doesnt support the VPC ID to be attached to existing DLC.
Can you add an attribute to support VPC CRN to the cloud connection ?

The gui allows one to edit this
![image](https://user-images.githubusercontent.com/101711050/167618844-27de3391-b37f-49dc-83f9-8bbdcfb5fc20.png)

**Comment by yussufsh** [comment]
@surajssb as discussed before we cannot allow this with Terraform design pattern. What you see on UI or API is update of the cloud connection details. In Terraform resource update works by providing different value to the argument and running `terraform apply` again. 
If you really need the feature of exclusively adding and removing vpc then please connect with the ops or service team of PowerVS.
Closing this issue as not supported.
