### ISSUE TITLE
pi_creation_date cannot be provided - its value will be decided automatically based on the result of applying this configuration.

### ISSUE THREAD

**Issue by en-ree** [IBM-Cloud/terraform-provider-ibm#3770]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_pi_key

### Description
I'm dealing with creating Power resources now and wanted to create ssh keys. The docs say one can provide the `pi_creation_date` param (which IMO doesn't make too much sense but it can be provided). When I run `terraform init && terraform validate` on the module I encounter the following error:

```
│ Error: Value for unconfigurable attribute
│ 
│   with module.power_ssh_key.ibm_pi_key.ssh_key,
│   on ../../modules/power/power_ssh_key/main.tf line 15, in resource "ibm_pi_key" "ssh_key":
│   15:         pi_creation_date        = var.creation_date
│ 
│ Can't configure a value for "pi_creation_date": its value will be decided automatically based on the result of applying this configuration.
╵
```

The code:
```terraform
variable creation_date {
	type = string
	default = null
}

resource ibm_pi_key ssh_key {
	count = var.lookup ? 0 : 1

	pi_key_name		= var.name
	pi_cloud_instance_id	= var.power_service_id
	pi_ssh_key		= var.public_key
	pi_creation_date	= var.creation_date
}
```
So it seems this property is not writable and so the docs should not mention it IMO.

### References
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_key#pi_creation_date

* #0000

Greetings,
Enrico Reetz | IBM Cloud Solution Engineering team

**Comment by yussufsh** [comment]
@en-ree thanks for reporting this issue. We will fix the document.
