### ISSUE TITLE
Wrong attribute references for ibm_pi_network

### ISSUE THREAD

**Issue by en-ree** [IBM-Cloud/terraform-provider-ibm#3777]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_pi_network

### Description

It seems the documentation for the attribute refernces is wrong for `ibm_pi_network`:
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_network#attribute-reference

The docs mention:
* networkid
* vlanid

But Terraform says:
```
2022/05/13 13:33:47 Terraform apply | Error: Unsupported attribute
2022/05/13 13:33:47 Terraform apply | 
2022/05/13 13:33:47 Terraform apply |   on ../../modules/power/power_network/outputs.tf line 14, in output "network_id":
2022/05/13 13:33:47 Terraform apply |   14: 	value = local.result.networkid
2022/05/13 13:33:47 Terraform apply |     ├────────────────
2022/05/13 13:33:47 Terraform apply |     │ local.result is object with 11 attributes
2022/05/13 13:33:47 Terraform apply | 
2022/05/13 13:33:47 Terraform apply | This object does not have an attribute named "networkid".
2022/05/13 13:33:47 Terraform apply | 
2022/05/13 13:33:47 Terraform apply | Error: Unsupported attribute
2022/05/13 13:33:47 Terraform apply | 
2022/05/13 13:33:47 Terraform apply |   on ../../modules/power/power_network/outputs.tf line 18, in output "vlan_id":
2022/05/13 13:33:47 Terraform apply |   18: 	value = local.result.vlanid
2022/05/13 13:33:47 Terraform apply |     ├────────────────
2022/05/13 13:33:47 Terraform apply |     │ local.result is object with 11 attributes
2022/05/13 13:33:47 Terraform apply | 
```

Code:
```terraform

resource ibm_pi_network network {
	count = var.lookup ? 0 : 1

	pi_network_name      = var.name
	pi_cloud_instance_id = var.power_service_id
	pi_network_type      = var.network_type
	pi_cidr              = var.cidr
	pi_dns               = var.dns
	pi_gateway           = var.gateway

}

data ibm_pi_network lookup {
	count = var.lookup ? 1 : 0

	pi_network_name		= var.name
	pi_cloud_instance_id	= var.power_service_id
}

locals {
	result = one(concat(ibm_pi_network.network, data.ibm_pi_network.lookup))
}

# [...]

output network_id {
	value = local.result.networkid
}

output vlan_id {
	value = local.result.vlanid
}
```

Replacing the vars with `network_id` and `vlan_id` works:
```terraform
output network_id {
	value = local.result.network_id
}

output vlan_id {
	value = local.result.vlan_id
}
```

So I guess the docs are wrong and should be corrected.

### References
* https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_network#attribute-reference

Kind regards
Enrico | IBM Cloud Solution Engineering Team

**Comment by yussufsh** [comment]
Thanks @en-ree for reporting this and making our docs better.
