### ISSUE TITLE
Block Storage only support Snapshot_capacity for endurance not working for Performance Type.

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#379]
In terraform provider the snapshot_capcity applies only to endurance.Can we give support for Performance type also as Softlayer gives this option to us.?

snapshot_capacity - (Optional, integer) Applies to Endurance storage only. The amount of snapshot capacity to allocate, specified in gigabytes.

Following is link to documentation for block_storage where it is mentioned that snapshot_capacity is only applied to endurance type.

**Comment by M-Rushabh** [comment]
@hkantare  Can you please look into this?

**Comment by hkantare** [comment]
Fix is available as part of v0.12.0 .Can you please test with latest provider https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0
