### ISSUE TITLE
ibm_pi_cloud_connection_network_attach errors often

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#3798]
Hi,

This resources fails often. Terraform parallely triggers for all networks id to be attached for the attribute pi_network_id when using count.

Can you convert **pi_network_id to a list or set** so that this resource executes at once without using count ?

data "ibm_pi_cloud_connection" "cloud_connection_ds" {
  count                     = var.cloud_connection_reuse ? 1 : 0
  pi_cloud_instance_id      = data.ibm_resource_instance.pvs_service_ds.guid
  pi_cloud_connection_name  = var.cloud_connection_name
}

resource "ibm_pi_cloud_connection_network_attach" "pvs_subnet_attach" {
  count                  = var.cloud_connection_reuse ? length(var.pvs_subnet_names) : 0
  pi_cloud_instance_id   = data.ibm_resource_instance.pvs_service_ds.guid
  pi_cloud_connection_id = data.ibm_pi_cloud_connection.cloud_connection_ds.0.id
  pi_network_id          = data.ibm_pi_network.pvs_subnets_ds[count.index].id
}

Would like to convert above code **without using count** instead pass a list to **pi_network_id** attribute:
resource "ibm_pi_cloud_connection_network_attach" "pvs_subnet_attach" {
  pi_cloud_instance_id   = data.ibm_resource_instance.pvs_service_ds.guid
  pi_cloud_connection_id = data.ibm_pi_cloud_connection.cloud_connection_ds.0.id
  pi_network_id          = data.ibm_pi_network.pvs_subnets_ds.*.id
}

**Comment by surajssb** [comment]
Hi @yussufsh 

I got in touch with the network team. This is what they said: "_**attach subnet is very long running operation. if you have large number of subnets, it is hitting some teraform or API timeout**_"

**Comment by rmoralesjr** [comment]
Converting pi_network_id to a list or set would require a service broker REST api change or addition since the current add network to CC is done with only one network at a time.  BTW the timeout length is 30 minutes.

**Comment by rmoralesjr** [comment]
Maybe the config could be changed to do the attaches serially by creating a
` resource "ibm_pi_cloud_connection_network_attach"`
per network to be attached
and then using depends_on meta-argument in the second and after of these blocks so that these attaches are done one at a time?

**Comment by surajssb** [comment]
Then it wouldn't be user defined inputs and user friendly. ( he can have n number of subnets ) . How will you have dynamically n blocks ?

**Comment by rmoralesjr** [comment]
I was just trying to get your specific scenario working. I'll set up a meeting with you to discuss.

**Comment by surajsbharadwaj** [comment]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Still creating... [40s elapsed]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Still creating... [50s elapsed]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Still creating... [1m0s elapsed]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Still creating... [1m10s elapsed]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Still creating... [1m20s elapsed]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Still creating... [1m30s elapsed]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Still creating... [1m40s elapsed]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Still creating... [1m50s elapsed]
module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[0]: Creation complete after 1m57s [id=03861d04-4359-4d33-9c5f-78e7bfba446e/2e1385bc-ccd2-4491-af1b-f290e8a7bb78/79eebf13-4f77-4e83-8339-4af89caae1ff]
╷
│ Error: failed to Add Network c9d12f5a-0391-4fc7-b876-be68822c44cd to Cloud Connection 2e1385bc-ccd2-4491-af1b-f290e8a7bb78: [PUT /pcloud/v1/cloud-instances/{cloud_instance_id}/cloud-connections/{cloud_connection_id}/networks/{network_id}][500] pcloudCloudconnectionsNetworksPutInternalServerError  &{Code:0 Description:an error has occurred; please try again: error creating project 0f12a261d69f4576bb6a9572cdd7dff6 in network service Error:internal server error Message:}
│
│   with module.pvs.module.cloud-connection.ibm_pi_cloud_connection_network_attach.pvs_subnet_attach[1],
│   on ..\..\modules\power-sap-infrastructure\power-sap-vpc-pvs-cloudconnection\main.tf line 98, in resource "ibm_pi_cloud_connection_network_attach" "pvs_subnet_attach":
│   98: resource "ibm_pi_cloud_connection_network_attach" "pvs_subnet_attach" {
│
╵

**Comment by hkantare** [comment]
@yussufsh Here may be you can use the concept of Mutex where the resource internally creates the networks one after the other 
https://discuss.hashicorp.com/t/whole-provider-process-synchronization/2006/4
We do have some resources already supporting this
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/c1b6507730d20cd39aed073b7ff607ee87434504/ibm/service/vpc/resource_ibm_is_vpc_address_prefix.go

**Comment by yussufsh** [comment]
@rmoralesjr @ChaseRun @dhirendersingh19 
Could you or someone else in your team apply Mutex on `ibm_pi_cloud_connection_network_attach` to avoid the backend limitation.
This is backend limitation as mentioned here https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3798#issuecomment-1142138055.

Also @rmoralesjr please evaluate on network creation why the same vlan id is used for parallel creation?

**Comment by surajsbharadwaj** [comment]
Works after adding depends on
