### ISSUE TITLE
Problem while updating "direction" in ibm_securitygroup_rule resource.

### ISSUE THREAD

**Issue by vijaylakshmi-b** [IBM-Cloud/terraform-provider-ibm#382]
if d.HasChange("direction") {
		matchingrules[0].Direction = sl.String(d.Get("**_description_**").(string))
	}
"description" should be replaced by "direction".
we have handled this issue.

**Comment by hkantare** [comment]
Fix is available as part of v0.12.0 .Can you please test with latest provider https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.12.0
