### ISSUE TITLE
Error: failed to provision: failed to Create PVM Instance :response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404)

### ISSUE THREAD

**Issue by hamzy** [IBM-Cloud/terraform-provider-ibm#3831]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
[hamzy@hamzy-tp-p50 hamzy-installer]$ terraform/bin/terraform -v
Terraform v1.0.11
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.2.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* ibm_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Debug Output
For this terraform file:
https://gist.githubusercontent.com/hamzy/0bfb14d7fc91cba5bb5a87009b25242d/raw/c746e1ebaf4b13afca6bda2d99fa56c8aa9989b1/test-terraform.txt

[hamzy@hamzy-tp-p50 hamzy-installer]$ (cd test-terraform/; export TF_LOG=TRACE; ../terraform/bin/terraform apply "test-terraform.out")

produces this output:
https://gist.github.com/hamzy/a9d3f98d25dddfa8fe2693f752c8f05b

### Steps to Reproduce

```
[hamzy@hamzy-tp-p50 hamzy-installer]$ (export TF_VAR_ibmcloud_api_key=${IBMCLOUD_API_KEY}; export TF_VAR_ibmcloud_region="syd"; export TF_VAR_ibmcloud_zone="syd05"; export TF_VAR_pub_key=$(cat ~/.ssh/id_rsa.pub); export TF_VAR_vm_id="hamzy-test-terraform"; export TF_VAR_system_type="s922"; export TF_VAR_service_instance_id="936a587f-90db-4f7b-abe3-8b7b817d0bda"; cd test-terraform/; export TF_VAR_network_id="25315aa5-fd1c-4105-840a-81887cac97ce"; ../terraform/bin/terraform plan -out test-terraform.out)

[hamzy@hamzy-tp-p50 hamzy-installer]$ (cd test-terraform/; export TF_LOG=TRACE; ../terraform/bin/terraform apply "test-terraform.out")
```

### References

* #0000

**Comment by yussufsh** [comment]
I am not sure why POST method should throw a 404.
@hamzy could you please check with the service team on what is going on in their code that is throwing 404 without defining it in the swagger?

cc: @rmoralesjr @ChaseRun

**Comment by clnperez** [comment]
@yussufsh the service broker team? or another team?

**Comment by yussufsh** [comment]
404 was thrown in this case because of NOT FOUND on SSH key. The SSH key is retrieved during the instance create flow.

Service broker team will add the 404 error to swagger during next prod push. I will fix the SDK later and update the new version here.

**Comment by yussufsh** [comment]
This is fixed by the service broker team by adding the 404 error to the swagger. The power-go-client has been updated in the provider so you should now see proper error message.
