### ISSUE TITLE
enable coreos support for IBM Cloud Satellite location creation

### ISSUE THREAD

**Issue by bhpratt** [IBM-Cloud/terraform-provider-ibm#3838]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

IBM Cloud Satellite now support coreos host OS for control plane and worker nodes. Requires a new location.

### New or Affected Resource(s)

TBD. I think this only affects satellite location create.

* ibm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* support has been added to the go-sdk: https://github.com/IBM-Cloud/container-services-go-sdk/pull/4#issuecomment-1151096890

**Comment by bhpratt** [comment]
Looks like I can't assign users - but I'd like to take this issue.

**Comment by darrellschrag** [comment]
Also need to make sure you can get the attach CoreOS ignition script from the location once this capability has been added.

**Comment by andrewferrier** [comment]
As @darrellschrag says, I think this affects `ibm_satellite_location` resource and `ibm_satellite_attach_host_script` data source.

**Comment by andrewferrier** [comment]
Looks like the change for `ibm_satellite_location` has gone in, but the one for `ibm_satellite_attach_host_script` is still pending?

**Comment by andrewferrier** [comment]
@hkantare which version of the provider contains this change to the host attach script?

**Comment by hkantare** [comment]
We are planning for a beta release mostly by tomrrow EOD
