### ISSUE TITLE
Please import images from catalog images internally in ibm_pi_instance

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#3840]
![image](https://user-images.githubusercontent.com/101711050/171868729-222d90a8-7301-4a6d-b6a8-05b3d4684421.png)
What happens in GUI background:
When create is triggered, it checks if there is a boot image existing already under boot image section. Since it doesnt exist it will make a copy of boot image and thus a entry is seen in boot image section. Using this boot image an instance is created in chosen tier of choice.
Next time you want to create a new instance with same image:
GUi background checks if the image exists in boot images section and it finds it . it doesnt make a copy , instead uses this image and creates instance.

So steps that needs to be followed for 2 scenarios :
For green field workflow:
Pvs(make copy of required images for user for deployment)
Create_instance module (takes in image name) and creates instance
For brown field workflow (just deploy instance to exisiting PVS):
pvs_import_image(make copy of required images if not present in PVS boot images for user for deployment)
Create_instance module (takes in image name) and creates instance
So a new module pvs_import_image has to be created (check if image is present in cloud instance else make a copy from catalog image)

But the above scenario causes problem in multiple workflows.

Below is a piece of code to import images if not present. This code is sitting in module import-image.

When i **create an instance using another module**, i make use of **import-image** module before this.
Lets assume terraform errors in some step in between in create instance module. When i run terraform apply again second time, it wants to destroy the image imported and the instance module.( Reason : As the image is already imported in step 1  terraform apply, the local variable image local.image is now 0 and hence resource ibm_pi_image has to be destroyed.)
Therefore i request you to handle the import images in **ibm_pi_instance** internally in go code

```locals {
  service_type          = "power-iaas"
}

data "ibm_resource_group" "resource_group_ds" {
  name = var.pvs_resource_group_name
}

data "ibm_resource_instance" "pvs_service_ds" {
  name                 = var.pvs_service_name
  service              = local.service_type
  location             = var.pvs_zone
  resource_group_id    = data.ibm_resource_group.resource_group_ds.id
}

data "ibm_pi_images" "exisiting_images_ds" {
  pi_cloud_instance_id = data.ibm_resource_instance.pvs_service_ds.guid
}

data "ibm_pi_catalog_images" "catalog_images_ds" {
  sap                  = true
  pi_cloud_instance_id = data.ibm_resource_instance.pvs_service_ds.guid
}

locals {
  image = [for x in data.ibm_pi_images.exisiting_images_ds.image_info : x if x.name == var.pvs_image_name]
  catalog_image = [for stock_image in data.ibm_pi_catalog_images.catalog_images_ds.images : stock_image if stock_image.name == var.pvs_image_name]
}

resource "ibm_pi_image" "image" {
  count                = length(local.image) == 0 ? 1 : 0
  pi_cloud_instance_id = data.ibm_resource_instance.pvs_service_ds.guid
  pi_image_id          = local.catalog_image[0].image_id
  pi_image_name        = var.pvs_image_name
  

}```

**Comment by surajsbharadwaj** [comment]
```
main.tf:

module "import-image" {
  source                         = "./power-image-import"
  count                          = var.brownfield ? 1 : 0

  pvs_zone                       = var.pvs_zone
  pvs_resource_group_name        = var.pvs_resource_group_name
  pvs_service_name               = var.pvs_service_name
  pvs_image_name                 = var.pvs_instance_image_name
}

module "instance-sap" {
  source                         = "./power-instance"
  depends_on                     = [module.import-image]
  
  pvs_zone                       = var.pvs_zone
  pvs_resource_group_name        = var.pvs_resource_group_name
  pvs_service_name               = var.pvs_service_name
  pvs_instance_hostname          = var.pvs_instance_hostname
  pvs_sshkey_name                = var.pvs_sshkey_name
  pvs_instance_image_name        = var.pvs_instance_image_name
  pvs_instance_profile_id        = var.pvs_instance_profile_id
  pvs_instance_sys_type          = var.pvs_instance_sys_type
  pvs_instance_proc_type         = var.pvs_instance_proc_type
  pvs_instance_processors        = var.pvs_instance_processors
  pvs_instance_memory            = var.pvs_instance_memory
  pvs_instance_private_net_names = var.pvs_instance_private_net_names
  pvs_instance_storage_config    = var.pvs_instance_storage_config
}
```
The above is contents of main .tf which uses 2 internal sub modules called import-image and instance-sap. These are made into one module called power-sap-instance.


now when i use the above module in example like this where i create one new subnet and wait for it to be created and then use:
```
provider "ibm" {
  region    =   var.pvs_region
  zone      =   var.pvs_zone
  ibmcloud_api_key = var.ibmcloud_api_key != null ? var.ibmcloud_api_key : null
}

locals {
  service_type = "power-iaas"
}

data "ibm_resource_group" "resource_group_ds" {
  name = var.pvs_resource_group_name
}

data "ibm_resource_instance" "pvs_service_ds" {
  name                 = var.pvs_service_name
  service              = "power-iaas"
  location             = var.pvs_zone
  resource_group_id    = data.ibm_resource_group.resource_group_ds.id
}

resource "ibm_pi_network" "sap_net2" {
  
  pi_cloud_instance_id = data.ibm_resource_instance.pvs_service_ds.guid
  pi_network_name      = "sap_net222"
  pi_cidr              = "10.79.1.1/24"
  pi_dns               = ["127.0.0.1"]
  pi_network_type      = "vlan"
  pi_network_jumbo     = true
}

module "netweaver" {
  // source = "terraform-ibm-modules/powervs/ibm//modules/power-sap-instance"
  source = "../../modules/power-sap-instance"
  count                          = 3
  depends_on                     = [ibm_pi_network.sap_net2]
  pvs_zone                       = var.pvs_zone
  pvs_resource_group_name        = var.pvs_resource_group_name
  brownfield                     = var.brownfield
  pvs_service_name               = var.pvs_service_name
  pvs_instance_hostname          = "nw-${count.index + 1}"
  pvs_sshkey_name                = var.pvs_sshkey_name
  pvs_instance_image_name        = var.pvs_instance_image_name
  pvs_instance_sys_type          = "s922"
  pvs_instance_proc_type         = "dedicated"
  pvs_instance_processors        = "3"
  pvs_instance_memory            = "200"
  pvs_instance_private_net_names = concat(var.pvs_instance_private_net_names, formatlist("sap_net2"))
  pvs_instance_storage_config    = var.pvs_nw_instance_storage_config
  
}
```

When i want this flow where i am creating a new network and using **power-sap-instance** module ( which inturn uses, image and instnace submodule, the pvs_import_image module is hitting error because of count and depends_on attribute. 




I think this import image from catalog should happen internally in ibm_pi_instance resource itself

**Comment by surajsbharadwaj** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3642

**Comment by ChaseRun** [comment]
The Power Team is taking this suggestion into consideration. 
As of now we wont implement this proposed solution, but we are considering other ways to make importing images easier.

**Comment by surajsbharadwaj** [comment]
Hello Team, Any update on this ? Any new strategy ? Something similar to VPC side can be done ?
