### ISSUE TITLE
ibm_is_vpc docs do not list attribute default_routing_table

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_is_vpc

### Terraform Configuration Files

https://registry.terraform.io/providers/IBM-Cloud/ibm/1.17.0/docs/resources/is_vpc

Expecting description of default_routing_table:
- [ ] Add documentation for default_routing_table
- [ ]  double check the rest of the attributes in all vpc resources to verify they are documented.  Is there a test you can write for this?
```
resource "ibm_is_vpc" "spoke" {
  name                      = var.name
  tags                      = var.tags
  resource_group            = var.resource_group_id
  address_prefix_management = "manual"
}

module "spoke_zones" {
  for_each             = var.zones
  source               = "../spoke_zone"
  vpc_default_routing_table               = ibm_is_vpc.spoke.default_routing_table
...
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by astha-jain** [comment]
Good to close?
