### ISSUE TITLE
resource "ibm_pi_cloud_connection" not attaching multiple vpcs

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#3890]
Hi,

When terraform plan happens 2 vpcs crns are shown in plan which i want to attach. but after apply, only one vpc is attached and not both.

**Comment by rmoralesjr** [comment]
Which colo did this error occur?

**Comment by rmoralesjr** [comment]
Generally we want one bug report per problem and it looks like there are 2 separate problems.
In regards to the network attach failure in the error statement above that needs to be investigated by the back-end networking team so could you please open an internal support ticket.

For the not attaching multiple vpcs problem is there any error statements\logs for that? And any details on the cloud connection id and vpc ids?

btw, the network attach failure above happened in tok production colo at timestamp Jun 30 05:50:56

**Comment by rmoralesjr** [comment]
Actually this looks to be a duplicate of a known issue on the networking back-end: NOGRE DL did not work because same IP got used on the second NOGRE 10Gb DL.

**Comment by surajsbharadwaj** [comment]
Okay now we know the issue for 10GB (duplicate VRF will be fixed) what about attaching multiple VPC crns
 ?

**Comment by rmoralesjr** [comment]
The networking developer earlier this week indicated . . .
_Fixes for NOGRE Direct Linkare available in the Direct Link-TGW release.
This code base is being rolled out to DCs including TOK04._

**Comment by surajsbharadwaj** [comment]
Not valid anymore
