### ISSUE TITLE
Seeing 502 errors while trying Terraform plan and apply

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#393]
Hi,

I am using IBM cloud provider for terraform v0.11.3 with terraform v0.11.8

### Terraform Version
0.11.8

### Expected Behavior
8 out of 10 times `Terraform plan` and `Terraform apply` are failing with 502 errors.

most of the times its throwing this error 
```
ibm_org.organization: Refreshing state... (ID: 5f15100f-a10e-4ec8-becb-87e73f3c7f87)

Error: Error refreshing state: 1 error(s) occurred:

* ibm_org.organization: 1 error(s) occurred:

* ibm_org.organization: ibm_org.organization: Error retrieving billing manager in the org: Request failed with status code: 502, ServerErrorResponse: 502 Bad Gateway: Registered endpoint failed to handle the request.
```

### Actual Behavior

Both Terraform plan and apply should work as expected without these errors as we know its working atleast 1 or 2 times out of 10 tries.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  `Terraform plan` after initializing 
2. `Terraform apply`

**Comment by hkantare** [comment]
Hi 
Its an issue with the endpoint from slack channels I can see others customers are also facing same issue
https://console.bluemix.net/status/notification/16ec90ee287890a9eab3c890e6efe36f
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/24930306/46801085-40658f00-cd77-11e8-8abf-cc62faf63640.png">

**Comment by VidyasagarMSC** [comment]
Not seeing 502 error anymore. So closing this for now
