### ISSUE TITLE
Resource 'ibm_container_bind_service.bind_database' does not have attribute 'secret_name' for variable 'ibm_container_bind_service.bind_database.secret_name'

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#395]
Hi there,

While applying the plan  using `ibm_container_bind_service.bind_database`, I am seeing the following error

IBM Cloud Provider for Terraform v0.11.3

> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * local_file.output: Resource 'ibm_container_bind_service.bind_database' does not have attribute 'secret_name' for variable 'ibm_container_bind_service.bind_database.secret_name'

But when I refer the documentation for v0.11.3, I see **secret_name - The secret name. This field is removed.** - https://ibm-cloud.github.io/tf-ibm-docs/v0.11.3/r/container_bind_service.html

### Terraform Version
0.11.8

### Affected Resource(s)
Please list the resources as a list, for example:
- 'ibm_container_bind_service.bind_database

### Expected Behavior
Cluster container should bind to the database without secret_name

### Actual Behavior
Expecting a secret_name through the attribute is removed as per the documentation.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with bind

**Comment by Praveengostu** [comment]
Hi @VidyasagarMSC To bind a service the required attributes are cluster_name_id, namespace_id and service_instance_name.  The secret is a computed attribute which is removed.  Does the portal or ibmcloud cli allows to specify the secret name? Are you expecting the secret name to be exported again?

**Comment by VidyasagarMSC** [comment]
@Praveengostu Here's my entry to bind the cloudant database to my container in `main.tf` for your reference

> resource "ibm_container_bind_service" "bind_database" {
>   cluster_name_id             = "${ibm_container_cluster.cluster.id}"
>   space_guid                  = "${ibm_space.space.id}"
>   service_instance_id         = "${ibm_service_instance.database.id}"
>   namespace_id                = "default"
>   account_guid                = "${data.terraform_remote_state.global.account_guid}"
>   org_guid                    = "${data.terraform_remote_state.global.org_guid}"
>   space_guid                  = "${ibm_space.space.id}"
> }

Yes, I am expecting the secret name to be exported. Is there any way I can export? or should I go with the documentation?

**Comment by Praveengostu** [comment]
@VidyasagarMSC With the latest API specification we do not see the secret is exported https://eu-central.containers.bluemix.net/swagger-api/#!/clusters/BindServiceToNamespace The response for the post and get calls are as below
```
{
  "namespace": "string",
  "serviceid": "string",
  "servicekeyname": "string",
  "servicename": "string"
}
```
