### ISSUE TITLE
Remote State 

### ISSUE THREAD

**Issue by viveknangal** [IBM-Cloud/terraform-provider-ibm#396]
Unable to figure out how to use object storage for storing Terraform state in IBM. Actually  I want to use the IBM Object storage as a "backend" for storing the Terraform state. 
### Terraform Version
terraform -v
Terraform v0.11.7
+ provider.ibm (unversioned)

### Affected Resource(s)
- backend

### Expected Behavior
Way to define IBM object storage for storing terraform state

Please suggest how do we use remote state in IBM

**Comment by viveknangal** [comment]
@hkantare Please suggest what is the recommendation to store the state in IBM cloud.

**Comment by Praveengostu** [comment]
@viveknangal You can use the etcd as backend for terraform https://console.bluemix.net/catalog/services/compose-for-etcd 
Example:
terraform {
  backend "etcdv3" {
    endpoints = ["https://sl-us-south-1-portal.31.dblayer.com:51625", "https://sl-us-south-1-portal.32.dblayer.com:51625"]
    username  = "root:<PASSWORD>"
  }
https://www.terraform.io/docs/backends/types/etcdv3.html
Here is a standard list of backends for terraform 
https://www.terraform.io/docs/backends/types

**Comment by viveknangal** [comment]
Thanks @Praveengostu   , please suggest are there more options available which are specific to IBM Cloud. like is it possible to use IBM Object storage for managing remote state or is there something else apart from ETCD  we can use in IBM ,please suggest.
