### ISSUE TITLE
docs in is_instance_template do not cover volume_attachments completely

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#3967]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance_template

![image](https://user-images.githubusercontent.com/6932057/184235094-d824e264-27d2-4d9f-8bb4-c0d4a0b47668.png)

- [ ] The Note is empty
- [ ] The possible values for volume_prototype?  There is an example above which would indicate "general-purpose" is one example that must be listed.  What are the other possible values?:
```
  volume_attachments {
    delete_volume_on_instance_delete = true
    name                             = "example-volume-att-01"
    volume_prototype {
      iops     = 3000
      profile  = "general-purpose"
      capacity = 200
    }
  }
```

- [ ] https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance_volume_attachment
![image](https://user-images.githubusercontent.com/6932057/184241086-899f5cd0-c41b-4d47-bf70-a0a84a91c92d.png)

**Comment by powellquiring** [comment]
Maybe same as https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance_volume_attachment

Allowed values are : [general-purpose, 5iops-tier, 10iops-tier, custom].

**Comment by powellquiring** [comment]
I tried the example provided in the docs and it did not work:
```
  volume_attachments {
    delete_volume_on_instance_delete = true
    name                             = "${var.name}-template-volume-attachment"
    volume_prototype {
       iops     = 3000
      profile  = "general-purpose"
      capacity = 200

    }
  }

│ Error: [ERROR] Error creating InstanceTemplate: User defined volume IOPS is not allowed for storage tier of specified volume profile general-purpose
│ {
│     "StatusCode": 400,
```

Removed `iops = 3000` and it got further, but failed with:
```
│ Error: [ERROR] Error creating InstanceTemplate: instance template name scale01-backend-template is already in use
```

It looks like the previous error actually created the instancetemplate, but the error confused terraform. It looks like this is a condition that must be verified by the IBM provider.

**Comment by powellquiring** [comment]
Handle docs to profile same was as api spec: https://github.ibm.com/riaas/api-spec/issues/4081

**Comment by deepaksibm** [comment]
@powellquiring thanks for reporting. fix is on its way
