### ISSUE TITLE
Even though SSL Certs are provided Load balancer is not coming up with SSL Offload Enabled.

### ISSUE THREAD

**Issue by jainishshah17** [IBM-Cloud/terraform-provider-ibm#399]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v0.11.8
+ provider.ibm v0.12.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- ibm_compute_ssl_certificate
- ibm_lb

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
resource "ibm_compute_ssl_certificate" "ssl_cert" {
  certificate = "${file(var.ssl_certificate)}"
  private_key = "${file(var.ssl_certificate_key)}"
}

resource "ibm_lb" "art_lb" {
  connections = "${var.lb-connections}"
  datacenter  = "${var.datacenter}"
  ha_enabled  = false
  dedicated   = "${var.lb-dedicated}"
  security_certificate_id = "${ibm_compute_ssl_certificate.ssl_cert.id}"
}

resource "ibm_lb_service_group" "art_lb_service_group" {
  port             = "${var.lb-service-group-port}"
  routing_method   = "${var.lb-service-group-routing-method}"
  routing_type     = "${var.lb-service-group-routing-type}"
  load_balancer_id = "${ibm_lb.art_lb.id}"
  allocation       = "${var.lb-service-group-routing-allocation}"
}
```

### Debug Output
![screen shot 2018-10-16 at 11 48 57 am](https://user-images.githubusercontent.com/7799465/47039746-7faa2c00-d139-11e8-8d76-5e8bfe4951fc.png)

### Expected Behavior
What should have happened?
Load balancer should come up with SSL Offload Enabled.

### Actual Behavior
What actually happened?
Even though SSL Certs are provided Load balancer is not coming up with SSL Offload Enabled.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by hkantare** [comment]
After my investigation ssl Offload Enabled is kind of  update to loadbalancer after you create a service group with "HTTPS" protocol. User cann't enable ssl offload during creation of loadbalancer. 
User has to create loadbalncer first with certificate id , create a serivce group with HTTPS protocol  and then he can enable ssl offload
So from terraform point of view it breaks in to two steps
1) terraform apply - Create loadbalancer(ssl offload false) and loadbalancer service group with HTTPS protocol
2) terraform apply - now enable ssl_offload 
We are planing to come up with a new attribute `ssl_offload` to enable or disable

**Comment by hkantare** [comment]
After my investigation ssl_offfload can be enabled only after creating a loadbalancer with ssl and service group with HTTPS protocol. So ssl_offload is a kind of update operation on load balancer. 

From terraform view 
Add new attribute ssl_offload
1) terraform apply - create a loadbalancer(ssl_offload by default false), create a service group with HTTPS protocol
2) update ssl_offload to true and then run terraform apply
