### ISSUE TITLE
Wrong formatting or missing content?

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#4031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/kms_key

![image](https://user-images.githubusercontent.com/8414748/189925365-0c213959-f205-44c3-9775-825d2c2a6f45.png)

**Comment by kavya498** [comment]
Duplicate of https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3923
Closing this issue
Thanks
