### ISSUE TITLE
ibm_container_worker_pool_zone_attachment throwing 404 error

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#405]
Hi there,

Facing the following issue while creating an `ibm_container_worker_pool_zone_attachment`

>  Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * ibm_container_worker_pool_zone_attachment.cluster_zone: 1 error(s) occurred:
> 
> * ibm_container_worker_pool_zone_attachment.cluster_zone: Request failed with status code: 404, ServerErrorResponse: 404 page not found

### Terraform Version

v0.11.8

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_cluster
- ibm_container_worker_pool

### Debug Output
https://gist.github.com/VidyasagarMSC/9020a80d8760d9212eec40f6c65412b5

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by VidyasagarMSC** [comment]
IBM Cloud provider for Terraform v 0.12.0

**Comment by VidyasagarMSC** [comment]
The resolution mentioned in this issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/343 worked for me. But the doc needs to be updated to reflect the same.

**Comment by Praveengostu** [comment]
@VidyasagarMSC Sure will update the example and doc accordingly

**Comment by Praveengostu** [comment]
The docs are updated and available in latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.13.0

**Comment by hkantare** [comment]
closing the issue..If issue still please reopen it..
