### ISSUE TITLE
Unable to deploy the SG rule for ICMP type "8" and code "Any"

### ISSUE THREAD

**Issue by pathaknikhil87** [IBM-Cloud/terraform-provider-ibm#4051]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_is_security_group_rule

### Terraform Configuration Files

```hcl
We deploy the SG rule with type 8 and code Any

{ name = "in-icmp" , direction  = "inbound", remote = ["9.6.6.9"] , ip_version = "ipv4" , icmp = { type = 8 , code = null } },
```

### References

* It is mentioned that the accepted values for code are Integers [code](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_security_group_rule#code) - (Optional, Integer) The ICMP traffic code to allow. Valid values from 0 to 255. But the portal allows you to set it.

**Comment by astha-jain** [comment]
@SunithaGudisagarIBM Please take a look.

**Comment by SunithaGudisagarIBM** [comment]
@pathaknikhil87  Can you please provide the link to the portal, we need to check with the api backend as they support only integer values
