### ISSUE TITLE
Unable to create ibm_container_cluster without optional hardware, machine type and vlan IDs 

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#406]
Hi there,

According to v0.12.0 documentation, hardware, machine_type, public and private vlan IDs are optional values. But I am not able to `apply` without these values as its throwing 400 error.

> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * ibm_container_cluster.cluster: 1 error(s) occurred:
> 
> * ibm_container_cluster.cluster: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"19d5c508-da6e-4704-8a95-80e35332dac2","code":"E0020","description":"To create a standard cluster, you must specify values for location, machine type, public VLAN, and private VLAN. To create a free cluster, specify cluster name only.","type":"Provisioning"}

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_cluster

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Praveengostu** [comment]
Hi @VidyasagarMSC 
The private and public vlan's are conditionally optional
If this standard cluster is the first standard cluster that you create in this zone, do not include public and private vlan IDs. A private/public VLAN is created for you when the clusters is created.
If you created a standard cluster before in this zone or created a private/public VLAN in IBM Cloud infrastructure (SoftLayer) before, you must specify that private/public VLAN. 
The machine_type is made optional to allow creating free cluster from terraform where as this is required for standard cluster
The hardware and isolation are conflict with each other so made them optional but terraform ibm provider will throw error if one of them is not specified `Please set either the hardware or isolation.`
We will update the documentation let us know if that helps

**Comment by hkantare** [comment]
closing the issue..
