### ISSUE TITLE
IBM Cloud Sysdig monitoring provisioning error not exposed to end user anymore

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#4087]
When provisioning a sysdig instance using `ibm_resource_instance` (see code [here](https://github.com/terraform-ibm-modules/terraform-ibm-observability/blob/main/modules/monitoring-sysdig/main.tf)) we were getting the following error:

```
{
  "StatusCode": 502,
  "Headers": {
    "Cache-Control": [
      "max-age=0, no-cache, no-store"
    ],
    "Content-Length": [
      "583"
    ],
    "Content-Type": [
      "application/json; charset=utf-8"
    ],
    "Date": [
      "Wed, 05 Oct 2022 08:20:39 GMT"
    ],
    "Expires": [
      "Wed, 05 Oct 2022 08:20:39 GMT"
    ],
    "Pragma": [
      "no-cache"
    ],
    "Request-Id": [
      "4f716c93-1224-4872-86aa-66dfe59621b0"
    ],
    "Retry-After": [
      "0"
    ],
    "Server": [
      "istio-envoy"
    ],
    "Set-Cookie": [
      "ak_bmsc=C34B1A1ED47C57A0AEAAAFC32B129EBD~000000000000000000000000000000~YAAQrwNAF4cJoaaDAQAA2oU7pxGT/LOd/slp72/T05SIDEn8/LA/rLlzsfg+HXj4ho4ablGUzmueSxu8WYXa78+eaLY0Tsp4EBvzAQ9vwJyWIieE3pk5WfPl1yrfQnz9PDmfy+Ye7dG0YsR7KHQzy0Udlgb+fGdSoNY2yjXeMBYplVm5MZx8hiE1OlhwCzKhmi+8uU7tELm+pwuKJG4mWRg7GbGL1GF+TbqQL4fJb2A8DM+WIvkIqn8YVLbOFhDHBqzDe1ghL8kB74CvTVEKEftoQpKJJjjVJmU7YSbD5KuxN0weIN+Vd+6jl/foGoWEhGNjFvJc+vXPNGsipdJGGCQOxkTkKfzPlEuieQBmLyMYMXr3ZOmegVJElvuMqaW19iK8OfdhA6mtt2TI; Domain=.cloud.ibm.com; Path=/; Expires=Wed, 05 Oct 2022 10:20:37 GMT; Max-Age=7198; HttpOnly"
    ],
    "Strict-Transport-Security": [
      "max-age=31536000;includeSubDomains"
    ],
    "Transaction-Id": [
      "bss-02c2c4bf9de7455b"
    ],
    "X-Content-Type-Options": [
      "nosniff"
    ],
    "X-Envoy-Upstream-Service-Time": [
      "2354"
    ],
    "X-Global-Transaction-Id": [
      "bss-02c2c4bf9de7455b"
    ],
    "X-Op-Completion-Time": [
      ""
    ],
    "X-Ratelimit-Limit": [
      "100"
    ],
    "X-Ratelimit-Remaining": [
      "99"
    ],
    "X-Ratelimit-Reset": [
      "0"
    ],
    "X-Request-Id": [
      "4f716c93-1224-4872-86aa-66dfe59621b0"
    ],
    "X-Transaction-Id": [
      "bss-02c2c4bf9de7455b"
    ]
  },
  "Result": {
    "details": "{\"description\":\"Sysdig provision request return code: 500 message: Server Error\",\"dashboard_url\":\"https:\\/\\/eu-gb.monitoring.cloud.ibm.com\\/api\\/oauth\\/openid\\/IBM\\/abac0df06b644a9cabc6e44f55b3880e\\/7022b15e-5983-4610-8136-5d0844eca7de\",\"error\":\"Server Error\",\"operation\":\"Provision\"}",
    "error_code": "RC-ServiceBrokerErrorResponse",
    "message": "Please contact the Service Provider for this error. [500, Internal Server Error] Sysdig provision request return code: 500 message: Server Error",
    "status_code": 502,
    "transaction_id": "bss-02c2c4bf9de7455b"
  },
  "RawResult": null
}
```

We created a support case with IBM Cloud and they got back to us to say the root cause was that there was already a sysdig intance in the region with platform metrics enabled. They confirmed this by sending us the following error from the backend logs:

`Can't update default receiver for (accountId=abac0df06b644a9cabc6e44f55b3880e,instanceId=bf35f623-0812-4d99-b8b7-a69fbbab1239) PartnerProvisioningRequest{resourceGroupId='crn:v1:bluemix:public:resource-controller::a/abac0df06b644a9cabc6e44f55b3880e::resource-group:f5f5128caac74a8b97010b3c139fdafb', monitoringInstanceId='crn:v1:bluemix:public:sysdig-monitor:eu-gb:a/abac0df06b644a9cabc6e44f55b3880e:bf35f623-0812-4d99-b8b7-a69fbbab1239::', planId='231bb072-1b2f-4d7e-ae9e-9574d382be32', defaultConsumerInstance=true, apiTokenAuthDisabled=null, privateEndpointCommunicationOnly=null}`

In the past, such an error used to be exposed in the provider error output. For example:
```
"Result": {
  "details": "{"description":"Sysdigprovisionrequestreturncode: 400message: BadRequestresponse: {
    \"errors\":[{\"reason\":\"Bad Request\",\"message\":\"Cannot update default receiver for instance '3d377154-15b1-4501-8a93-4f0c180f877f' while it is enabled for '5bbc1f2c-0bc7-4dca-84bf-81f8a6618ff9' display name null\"}]}",
    "dashboard_url": "https:\/\/us-south.monitoring.cloud.ibm.com\/api\/oauth\/openid\/IBM\/7aa6f7b185f2e3170fac9919aa1769ee\/3d377154-15b1-4501-8a93-4f0c180f877f",
    "error": "Bad Request",
    "operation": "Provision"
  }",
```

So why are we no longer seeing this error? Does something need to be updated in the provider code in order to return correct error message? Perhaps there is a regression? Or api returns different output now?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

ibm provider version 1.45.0
terraform version 1.2.9

### Affected Resource(s)

* ibm_resource_instance

### Terraform Configuration Files

https://github.com/terraform-ibm-modules/terraform-ibm-observability/tree/main/examples/observability-complete

**Comment by hkantare** [comment]
@ocofaigh Mostly it can be regression from API end or they changed the retrun message because from Terraform https://github.com/IBM-Cloud/terraform-provider-ibm/blob/65514317be26478193610f378ea4270da8f83657/ibm/service/resourcecontroller/resource_ibm_resource_instance.go#L512
we return complete resp object.

**Comment by ocofaigh** [comment]
@hkantare Here is the response from the sysdig team:

> sysdig team confirmed we do expect to see this error message to be returned in the API.
> 
> We've also re-looked at backend logs and there is returned on sysdig side also the message of which instance ID have already the IBM Platform metrics enabled
> Can't update default receiver for (accountId=abac0df06b644a9cabc6e44f55b3880e,instanceId=bf35f623-0812-4d99-b8b7-a69fbbab1239) PartnerProvisioningRequest{resourceGroupId='crn:v1:bluemix:public:resource-controller::a/abac0df06b644a9cabc6e44f55b3880e::resource-group:f5f5128caac74a8b97010b3c139fdafb', monitoringInstanceId='crn:v1:bluemix:public:sysdig-monitor:eu-gb:a/abac0df06b644a9cabc6e44f55b3880e:bf35f623-0812-4d99-b8b7-a69fbbab1239::', planId='231bb072-1b2f-4d7e-ae9e-9574d382be32', defaultConsumerInstance=true, apiTokenAuthDisabled=null, privateEndpointCommunicationOnly=null}
> 
> Cannot update default receiver for instance 'bf35f623-0812-4d99-b8b7-a69fbbab1239' while it is enabled for 'a9508074-c620-45b9-b5c4-cdeb8789cc66'

**Comment by hkantare** [comment]
Can we enable trace TF_LOG=debug to check if API response contains the  info

**Comment by ocofaigh** [comment]
@hkantare Please see trace log attached where I reproduced the issue. The stdout error looks like this:

```
╷
│ Error: [ERROR] Error when creating resource instance: Please contact the Service Provider for this error. [500, Internal Server Error] Sysdig provision request return code: 500 message: Server Error with resp code: {
│     "StatusCode": 502,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store"
│         ],
│         "Content-Length": [
│             "583"
│         ],
│         "Content-Type": [
│             "application/json; charset=utf-8"
│         ],
│         "Date": [
│             "Sun, 16 Oct 2022 14:59:00 GMT"
│         ],
│         "Expires": [
│             "Sun, 16 Oct 2022 14:59:00 GMT"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Request-Id": [
│             "7683aa84-c779-4e61-84cb-ad1ff2e2a9e8"
│         ],
│         "Retry-After": [
│             "0"
│         ],
│         "Server": [
│             "istio-envoy"
│         ],
│         "Set-Cookie": [
│             "ak_bmsc=3F2A715C7DB7B1009E0018E78DF3A6B9~000000000000000000000000000000~YAAQBDZ6XC9EMNGDAQAAzitO4RFA8Fd8scA9FIOGcOjnWu7SD4OGvfW3jP2SA+DgSAeUX+DEg3pvyQyZgvX+G1BGIO9j8DbN3pRYsfxjEgTdQVRWjc8dwvbu9epUKrXDc5cOvo6rDehCNj38D3cZBBkDRKotbyrgKVL1paVHQqmUxxrYE94ZJmlq/79qU2FKA5p4wa6JC6vczm4wDSIKKub8C0/YQ01tjJwF96mGYUHDaMXcizabt5hAS2s4WWCyRvwQATZhHz+vRWsWFTSAMVfHOBezDx11ihooNZTrnKSN0xn629oz0OegaXWOfQRNrTGy3SRD5DQX5rXVQfyTHvZzZPaMvqPo6upm0Vf5lD9JBUnM20S4QRBmv8Hhl+O3xjAFmjmg7LGpVfONnw==; Domain=.cloud.ibm.com; Path=/; Expires=Sun, 16 Oct 2022 16:58:56 GMT; Max-Age=7196; HttpOnly"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000;includeSubDomains"
│         ],
│         "Transaction-Id": [
│             "bss-e5f9053777bb03d1"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Envoy-Upstream-Service-Time": [
│             "3186"
│         ],
│         "X-Global-Transaction-Id": [
│             "bss-e5f9053777bb03d1"
│         ],
│         "X-Op-Completion-Time": [
│             ""
│         ],
│         "X-Ratelimit-Limit": [
│             "100"
│         ],
│         "X-Ratelimit-Remaining": [
│             "99"
│         ],
│         "X-Ratelimit-Reset": [
│             "0"
│         ],
│         "X-Request-Id": [
│             "7683aa84-c779-4e61-84cb-ad1ff2e2a9e8"
│         ],
│         "X-Transaction-Id": [
│             "bss-e5f9053777bb03d1"
│         ]
│     },
│     "Result": {
│         "details": "{\"description\":\"Sysdig provision request return code: 500 message: Server Error\",\"dashboard_url\":\"https:\\/\\/eu-gb.monitoring.cloud.ibm.com\\/api\\/oauth\\/openid\\/IBM\\/abac0df06b644a9cabc6e44f55b3880e\\/1673a2dc-76e8-4b3a-8c1f-f02bdb6c68bf\",\"error\":\"Server Error\",\"operation\":\"Provision\"}",
│         "error_code": "RC-ServiceBrokerErrorResponse",
│         "message": "Please contact the Service Provider for this error. [500, Internal Server Error] Sysdig provision request return code: 500 message: Server Error",
│         "status_code": 502,
│         "transaction_id": "bss-e5f9053777bb03d1"
│     },
│     "RawResult": null
│ }
│ 
│ 
│   with module.observability.module.monitoring_instance[0].ibm_resource_instance.sysdig_instance[0],
│   on ../../modules/monitoring-sysdig/main.tf line 15, in resource "ibm_resource_instance" "sysdig_instance":
│   15: resource "ibm_resource_instance" "sysdig_instance" {
│ 
╵
```

Here is trace log:
[trace.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/9794945/trace.txt)

**Comment by ocofaigh** [comment]
Looks like this was a backend issue which they just fixed

![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/29608224/d1f98c70-c1ea-44a9-945b-22b739d7b946)
