### ISSUE TITLE
Cannot create ibm_is_vpc_routing_table_route

### ISSUE THREAD

**Issue by odaira** [IBM-Cloud/terraform-provider-ibm#4112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v1.3.2
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.46.0
```

### Affected Resource(s)

* ibm_is_vpc_routing_table_route

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "ibmcloud-api-key" {}
variable "login-region" {}

##################################################

provider "ibm" {
  ibmcloud_api_key       = var.ibmcloud-api-key
  region             	 = var.login-region
}

##################################################

resource "ibm_is_vpc" "vpc1" {
  name           = "example-vpc1"
}

resource "ibm_is_vpc_routing_table" "rtbl1" {
  vpc                           = ibm_is_vpc.vpc1.id
  name                          = "example-rtbl1"
  route_direct_link_ingress     = false
  route_transit_gateway_ingress = false
  route_vpc_zone_ingress        = false
}

resource "ibm_is_vpc_routing_table_route" "rtbl-rt1" {
  vpc             = ibm_is_vpc.vpc1.id
  routing_table   = ibm_is_vpc_routing_table.rtbl1.id
  zone            = "us-south-1"
  name            = "example-rtbl-rt1"
  destination     = "172.16.1.123/32"
  action          = "drop"
  next_hop        = "0.0.0.0"
}
```

### Expected Behavior

Should be able to create `ibm_is_vpc_routing_table_route` without any error.

### Actual Behavior

```
ibm_is_vpc.vpc1: Creating...
ibm_is_vpc.vpc1: Still creating... [10s elapsed]
ibm_is_vpc.vpc1: Creation complete after 16s [id=r006-65c00f04-548c-492a-ba9e-7a8e688ea7ab]
ibm_is_vpc_routing_table.rtbl1: Creating...
ibm_is_vpc_routing_table.rtbl1: Creation complete after 0s [id=r006-65c00f04-548c-492a-ba9e-7a8e688ea7ab/r006-24a8017a-d7f1-4df8-bff6-0020c0dd7493]
ibm_is_vpc_routing_table_route.rtbl-rt1: Creating...
╷
│ Error: /v1/vpcs/r006-65c00f04-548c-492a-ba9e-7a8e688ea7ab/routing_tables/r006-65c00f04-548c-492a-ba9e-7a8e688ea7ab/r006-24a8017a-d7f1-4df8-bff6-0020c0dd7493/routes endpoint not found
│
│   with ibm_is_vpc_routing_table_route.rtbl-rt1,
│   on bug_report_tf_route_main.tf line 25, in resource "ibm_is_vpc_routing_table_route" "rtbl-rt1":
│   25: resource "ibm_is_vpc_routing_table_route" "rtbl-rt1" {
│
╵
```

The resource path `/v1/vpcs/r006-65c00f04-548c-492a-ba9e-7a8e688ea7ab/routing_tables/r006-65c00f04-548c-492a-ba9e-7a8e688ea7ab/r006-24a8017a-d7f1-4df8-bff6-0020c0dd7493/routes` is wrong.  Why does it include the VPC ID **twice** in the path?  It should be `/v1/vpcs/r006-65c00f04-548c-492a-ba9e-7a8e688ea7ab/routing_tables/r006-24a8017a-d7f1-4df8-bff6-0020c0dd7493/routes`.

The environment is in us-south-1.  

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ujjwal-ibm** [comment]
Please change the configuration of `ibm_is_vpc_routing_table_route` to this 


```
resource "ibm_is_vpc_routing_table_route" "rtbl-rt1" {
  vpc             = ibm_is_vpc.vpc1.id
  routing_table   = ibm_is_vpc_routing_table.rtbl1.routing_table
  zone            = "us-south-1"
  name            = "example-rtbl-rt1"
  destination     = "172.16.1.123/32"
  action          = "drop"
  next_hop        = "0.0.0.0"
}
```


the part   `routing_table   = ibm_is_vpc_routing_table.rtbl1.id` is wrong

link to example and docs https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc_routing_table_route#example-usage
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc_routing_table#routing_table

**Comment by ujjwal-ibm** [comment]
Its including the id twice because `ibm_is_vpc_routing_table.rtbl1.id `is a combination of `<vpc_id>/<vpc_routing_table_id>` 

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc_routing_table#id

**Comment by odaira** [comment]
Yes, it works.  So `the routing table ID` refers not to the `id` attribute but to the `routing_table` attribute....  The design (or document) looks error-prone to me, but in any case, thank you for your help.
