### ISSUE TITLE
Schematics managing schematics fails after creation

### ISSUE THREAD

**Issue by pkluska** [IBM-Cloud/terraform-provider-ibm#4132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_schematics_workspace

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_schematics_workspace" "cos" {
  name                  = "cos"
  description           = "Schematics to manage COS"
  location              = "eu-de"
  resource_group        = "default"
  template_type         = "terraform_v1.1"
  template_git_url      = ""
  template_git_repo_url = ""
  template_git_branch   = "master"
  template_git_folder   = "cloud-object-storage"
}
```

### Debug Output
https://gist.github.com/pkluska/1b981fc7eba0d037b9d79ee108a144e4
### Expected Behavior

The Schematics should be created and managed by the schematics.

### Actual Behavior

New Schematics workspace was created. After trying to apply the changes it cannot update the schematics.

### Steps to Reproduce

1. Create schematics that manages schematics workspace
2. Wait for the job to finish
3. Try to apply the same schematics

### Important Factoids

Running in IBM Cloud Schematics Workspace

### References

* #0000

**Comment by luisarojas** [comment]
+1 Following

**Comment by somnathpathak** [comment]
I am using a terraform module to create Schematics workspaces using the [terraform schematics resource](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/schematics_workspace). 

I face the same issue on subsequent terraform runs where I try to update the above created workspaces' configuration. Please find the error below:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/6602586/207674660-865833d3-485d-4932-a5d5-c6db7ad868a0.png">
