### ISSUE TITLE
Unable to create Virtual Server instances on a VPC through Terraform  

### ISSUE THREAD

**Issue by gchelazzi-klab** [IBM-Cloud/terraform-provider-ibm#4141]
### Expected Behavior

After creating the VPC, the subnetworks, the security groups and so on, the TF provider for IBM should create the VSIs.

### Actual Behavior
The Terraform provider for IBM incurs in this error: 
ibm_is_instance.adai-controller-1: Creating...
ibm_is_instance.adai-guest-1: Creating...
╷
│ Error: Expected only one oneOf fields to be set: got 0
│ 
│   with ibm_is_instance.adai-controller-1,
│   on adai_controller_vm.tf line 55, in resource "ibm_is_instance" "adai-controller-1":
│   55: resource "ibm_is_instance" "adai-controller-1" {
│ 
╵
╷
│ Error: Expected only one oneOf fields to be set: got 0
│ 
│   with ibm_is_instance.adai-guest-1,
│   on adai_controller_vm.tf line 70, in resource "ibm_is_instance" "adai-guest-1":
│   70: resource "ibm_is_instance" "adai-guest-1" {
│ 
╵

### Steps to Reproduce

1. `terraform init && terraform plan && terraform apply`

### Important Factoids

With other resources, similar error (with more specific non-uniqueness-related output) are the sign that the resources should be unique and they're not, the name is already taken etc. But triple -checking from the API, the ibmcloud CLI, the darn UI and even importing with data blocks from terraform itself confirms that this is not the case.

### References
This issue doesn't have any reference that I can see. Googling "ibm_is_instance" "oneof" returns empty search

**Comment by ujjwal-ibm** [comment]
@gchelazzi-klab can you share your configuration ?

**Comment by sumitkumartiwari** [comment]
we don't have any further updates, closing the issue.
