### ISSUE TITLE
Update releases page to be Terraform user friendly. 

### ISSUE THREAD

**Issue by stevestrutt** [IBM-Cloud/terraform-provider-ibm#416]
The releases page https://github.com/IBM-Cloud/terraform-provider-ibm/releases does not indicate which platforms IBM supports with the IBM provider. The naming is in developer speak, i.e. Darwin, AMD64. 

The page should be clear which platforms are supported e.g. macOS, Linux and Windows. Styling should allow non-developers to download the plugin as per the style of the Terraform download page. 
https://www.terraform.io/downloads.html

**Comment by hkantare** [comment]
We are following the guidelines provided while naming the releases 
https://www.terraform.io/docs/registry/providers/publishing.html
so closing the issue
