### ISSUE TITLE
ibm_secrets_manager_secret data source region bug

### ISSUE THREAD

**Issue by jpmonge86** [IBM-Cloud/terraform-provider-ibm#4165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/ibm-cloud/ibm v1.47.1
+ provider registry.terraform.io/mastercard/restapi v1.18.0
```

### Affected Resource(s)

Data source >
* ibm_secrets_manager_secret

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Data source to retrieve username_password_secret attributes
data "ibm_secrets_manager_secret" "username_password_secret" {
  count       = var.secret_user_pass_auto_rotation == true && var.secret_username != null ? 1 : 0
  instance_id = var.secrets_manager_guid
  secret_type = "username_password" #checkov:skip=CKV_SECRET_6: does not require high entropy string as is static value
  secret_id   = local.secret_id
  depends_on  = [restapi_object.username_password_secret_rotation_policy]
}
```
Complete terraform configuration available [here](https://github.ibm.com/GoldenEye/secrets-manager-secret-module/blob/master/main.tf#L70)
### Expected Behavior

Data source fetches the details about the secret

### Actual Behavior

Secret is attempted to be read for a minute or so, then an error is returned indicating host/endpoint is not right

```
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Reading...
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [10s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [20s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [30s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [40s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [50s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [1m0s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [1m10s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [1m20s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [1m30s elapsed]
module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0]: Still reading... [1m40s elapsed]
╷
│ Error: Get "https://5ac3f5f3-7f0a-41ef-8e8a-f0f459cde7b8.us-south.secrets-manager.appdomain.cloud/api/v1/secrets/username_password/5bdfa854-e46e-bfad-3326-0cbdc6531834": dial tcp: lookup 5ac3f5f3-7f0a-41ef-8e8a-f0f459cde7b8.us-south.secrets-manager.appdomain.cloud on 192.168.1.1:53: no such host
│
│   with module.secrets_manager_user_pass_secret.data.ibm_secrets_manager_secret.username_password_secret[0],
│   on ../../main.tf line 76, in data "ibm_secrets_manager_secret" "username_password_secret":
│   76: data "ibm_secrets_manager_secret" "username_password_secret" {
```

The path shows the incorrect `region` is being used to get the secret, the SM GUID looks right but the appropriate region is `eu-gb`, the error displays `us-south`, this appears to indicate it always uses that region to fetch existing secrets regardless of the GUID passed, perhaps region needs to be added as an argument.

![SM instance](https://user-images.githubusercontent.com/51208928/201150194-38871d29-2f00-4a62-8c80-52ba9ebb616e.png)

### Steps to Reproduce

1. `terraform apply`

**Comment by hkantare** [comment]
can you set the provider region since the service is regional specific by default its us-south
provider ibm  {
region = "eu-gb"
}

**Comment by jpmonge86** [comment]
> can you set the provider region since the service is regional specific by default its us-south provider ibm { region = "eu-gb" }

Thanks Harini, I can confirm this works.
