### ISSUE TITLE
subnet error

### ISSUE THREAD

**Issue by Janilassila78** [IBM-Cloud/terraform-provider-ibm#4169]
Cant get the subnets working 

Locals and variables
locals {
   BASENAME = "test1"
   ZONE     = "eu-de"
}

data "ibm_resource_group" "example" {
  name = "jani-exp"
}

resource "ibm_is_vpc" "vpc1" {
    name = "${local.BASENAME}-vpc1"
}

resource "ibm_is_security_group" "sg1" {
    name = "${local.BASENAME}-sg1"
    vpc  = ibm_is_vpc.vpc1.id
}

# allow all incoming network traffic on port 22
resource "ibm_is_security_group_rule" "ingress_ssh_all" {
    group     = ibm_is_security_group.sg1.id
    direction = "inbound"
    remote    = "0.0.0.0/0"

    tcp {
      port_min = 22
      port_max = 22
    }
}

resource "ibm_is_subnet" "net1" {
  name                       = "${local.BASENAME}-net1"
  vpc                        = ibm_is_vpc.vpc1.id
  zone                       = local.ZONE
  total_ipv4_address_count   = 256
  resource_group             = data.ibm_resource_group.example.id
}

resource "ibm_is_ssh_key" "ssh-key" {
  name       = "ssh-key"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVZeurj6xzZpNZI5P59zGmKM8+6g8bDwu0fdy5eOgV0rj8vBnYiRMiSvpIkQyAFqtGIUtFbp/1zgDJ8DLgLQES+j1TybXYhXE3vtoENTn+POgtQa9lKTqSpBbUeiwVhBKb3vTOrqlJGY+lfn97253JpdAPH02cEVovXMDw5atN5Z0lL77KNaRivo6s5k21LRPxpyOSoeva1nxuC2ffq5599O2ryYZdmpiWlQWAB2g9BjspOlI7D7CPgaH2x8mFbgzEhxuoXHSbH36A/LgU84Dn7ZTtyjFmTKAZshN71cEtpMID18QKXSjRTYcMbb88Yo8tjURBYOw6WSlWlFIYN5vCqA8vHqreN60JfOHoyi7qkOIEixM186f3AULiIPvAFJ2+5olg2oUJsfma/5E/xzmdu5NPElJLIoLfqvUJPSgJiUREwbLC/ioosXqK+K3xyh7Clr29Cjm4msBYeJRM15pzWhdViWwULUXAqMZh9kZlhU7lL7R3Hvz6qxPXnazVq/M="
}

# creates a vm

data "ibm_is_image" "centos" {
    name = "ibm-centos-7-6-minimal-amd64-1"
}

resource "ibm_is_instance" "vsi1" {
    name    = "${local.BASENAME}-vsil"
    vpc     = ibm_is_vpc.vpc1.id
    zone    = local.ZONE
    keys    = [ibm_is_ssh_key.ssh-key.id]
    image   = data.ibm_is_image.centos.id
    profile = "cx2-2x4"

    primary_network_interface {
        subnet          = ibm_is_subnet.net1.id
        security_groups = [ibm_is_security_group.sg1.id]
    }
}

error message:

Error: [ERROR] Error while creating Subnet missing or invalid zone
│ {
│     "StatusCode": 400,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store, must-revalidate"
│         ],
│         "Cf-Cache-Status": [
│             "DYNAMIC"
│         ],
│         "Cf-Ray": [
│             "76a825ec28d6be60-CPH"
│         ],
│         "Content-Length": [
│             "172"
│         ],
│         "Content-Type": [
│             "application/json; charset=utf-8"
│         ],
│         "Date": [
│             "Tue, 15 Nov 2022 12:56:39 GMT"
│         ],
│         "Expires": [
│             "-1"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Server": [
│             "cloudflare"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000; includeSubDomains"
│         ],
│         "Vary": [
│             "Accept-Encoding"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Request-Id": [
│             "7bbb0c8d-3d5a-4b15-bfe3-9cebe5e6d0df"
│         ],
│         "X-Xss-Protection": [
│             "1; mode=block"
│         ]
│     },
│     "Result": {
│         "errors": [
│             {
│                 "code": "bad_field",
│                 "message": "missing or invalid zone",
│                 "target": {
│                     "name": "zone",
│                     "type": "field",
│                     "value": "eu-de"
│                 }
│             }
│         ],
│         "trace": "7bbb0c8d-3d5a-4b15-bfe3-9cebe5e6d0df"
│     },
│     "RawResult": null
│ }
│ 
│ 
│   with ibm_is_subnet.net1,
│   on main.tf line 33, in resource "ibm_is_subnet" "net1":
│   33: resource "ibm_is_subnet" "net1" {

**Comment by hkantare** [comment]
Zone should be something like (eu-de-1, eu-de-2, eu-de-3)
ZONE = "eu-de-1"

**Comment by Janilassila78** [comment]
thx that solved the error!
