### ISSUE TITLE
 All operations on ibm_cos_bucket fail with 403s

### ISSUE THREAD

**Issue by bigpick** [IBM-Cloud/terraform-provider-ibm#4192]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
terraform -v
Terraform v1.3.5
on darwin_arm64
```

```
registry.terraform.io/ibm-cloud/ibm -> 1.46.0 (and same issue on 1.48.0-beta0
```

```
terraform {
  required_version = ">=0.13"
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = ">=1.43.0"
    }
  }
}
```

### Affected Resource(s)

* `ibm_cos_bucket` (Resource and data source)

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_cos_bucket" "bucket1" {
  bucket_name          = "foo"
  resource_instance_id = "previously-estabished-cos-serviceinstance-id"
  region_location      = "us-south"
  storage_class        = "smart"
  endpoint_type        = "public"
  key_protect          = "key-crn-here"

  object_versioning {
    enable = true
  }

  dynamic "activity_tracking" {
    for_each = ibm_resource_instance.activity_tracker
    content {
      read_data_events  = true
      write_data_events = true
      activity_tracker_crn = activity_tracking.value.id
    }
  }

  dynamic "metrics_monitoring" {
    for_each = ibm_resource_instance.monitoring
    content {
      usage_metrics_enabled   = true
      request_metrics_enabled = true
      metrics_monitoring_crn  = metrics_monitoring.value.id
    }
  }
}

```

### Debug Output

Doesn't output any further logs pertaining to the COS bucket other than the blocks posted below.

### Expected Behavior

I should be able to `apply` / `destroy` against TF setups that contain a `ibm_cos_bucket` in them 

### Actual Behavior

I get 403s for all activities:

apply: 

```
│ Error: AccessDenied: Anonymous bucket creation not allowed.
│       status code: 403, request id: c722154b-084d-426e-8288-dfc75edf1ed3, host id:
```

destroy:

```
│ Error: AccessForbidden: GET Service not allowed for anonymous users
│       status code: 403, request id: a70fc4c3-a70a-4f7a-9d69-4b04a25da5af, host id:
```

### Steps to Reproduce

1. `terraform apply` attempting to create or destroy bucket.

### Important Factoids

The API keys I'm using are valid and work. I've tried 2 separate sets of new additional keys that are both valid with the correct permissions. 

This exact same TF code had _previously_ worked before, and nothing as far as I am aware has changed within the account that should be breaking this now, which makes me think this is somehow an error tha's due to a change in the IBM Cloud APIs (same exact code and keys have worked previously until now).

... this is being run from the account owner's perspective/API key, so yes, it has enough permissions to access/destroy COS buckets.

### References

* https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3350 
   * This issue I'm seeing is definitely not intermittent, I see it every single run and it has been blocking and usage of TF in the account for over 4 days now at this point.

**Comment by IBM-diksha** [comment]
@bigpick If you still facing the same issue can you please try with a different region like us-east or eu-de.
eg : region_location      = "us-east"

**Comment by bigpick** [comment]
Yes, still having the issue

Tried in `eu-de`, this time successfully went through there. Went back and tried again in `us-south`, still fails.

**Comment by IBM-diksha** [comment]
@bigpick Currently there is some issue with the us-south region that is why these failures are seen only for us-south endpoints once this issue gets resolved you be facing these failures. Till then if it is possible you can use the other regions.

**Comment by IBM-diksha** [comment]
This ticket can be closed as the issue with us-south has been fixed.
