### ISSUE TITLE
Feature Request : Add support for single vlan FSA firewall

### ISSUE THREAD

**Issue by priyanknarvekar** [IBM-Cloud/terraform-provider-ibm#420]
Hi there,

Please add support for 1g FSA Appliance - Hardware Firewall (Dedicated) for single vlan
https://console.bluemix.net/docs/infrastructure/fortigate-1g/getting-started.html

I have created a pull request as follows :
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/415

Thanks

**Comment by hkantare** [comment]
Hi
We reviewed the PR and provided some comments ..Can you please implement them.

**Comment by priyanknarvekar** [comment]
@hkantare thanks,
done and updated

**Comment by hkantare** [comment]
Available as part of v0.13.0 https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.13.0a
