### ISSUE TITLE
[ibm_container_vpc_cluster ] wait_till = "Normal" does not work

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#4214]
wait_till = "Normal" was added in 1.48.0 however it always fails with:
`Error: unexpected state 'critical', wanted target 'normal'. last error: %!s(<nil>)`

After reproducing locally, I checked the state of the cluster in the UI and it showed as:
![image](https://user-images.githubusercontent.com/29608224/205264239-17972715-a812-4d00-bf1c-a87b64645ea2.png)

However according to the [docs](https://cloud.ibm.com/docs/containers?topic=containers-cluster-states-reference#cluster-state-normal),  Normal is:

> All worker nodes in a cluster are up and running. You can access the cluster and deploy apps to the cluster. This state is considered healthy and does not require an action from you.

After a few more minutes, all worker nodes went green:
![image](https://user-images.githubusercontent.com/29608224/205264991-ed70035a-8c7e-4444-8ed6-c257f76359f9.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_container_vpc_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Debug Output
[trace.log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/10139949/trace.log)

### Expected Behavior

Cluster provisioning should pass in terraform

### Actual Behavior

`Error: unexpected state 'critical', wanted target 'normal'. last error: %!s(<nil>)`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ocofaigh** [comment]
Still not working correctly in 1.49.0. See https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4266

**Comment by vburckhardt** [comment]
does this need to be reopened? @ocofaigh @hkantare
