### ISSUE TITLE
ibm_iam_service_policy resource recreation after no modifications

### ISSUE THREAD

**Issue by Zalder2** [IBM-Cloud/terraform-provider-ibm#4215]
When we execute a terraform plan in a code with a ibm_iam_service_policy resource, terraform is trying to recreate the policy even we don't perform any change to the indicated resource.

 We create a new ibm iam service policy for cloud object storage to give permissions to a specific bucket.
Terraform code for policy create
```
resource "ibm_iam_service_policy" "policy" {
  iam_service_id = "ServiceId-d9a2c335-da2f-4394-9b5a-378f5958cccc"
  roles          = ["Writer"]
  description    = "IAM Service Policy"
  
   resources {
    service              = "cloud-object-storage"
    resource_instance_id = element(split(":", "5a23493a-3bb1-41e8-8bae-c78bf0696577"), 7)
    attributes = {
      "resource" = "ib-eude-prueba-pre"
    }
    }
}
```
On this plan we can see the new policy which will be added on the cloud infrastructure (which is correct).
```
Terraform will perform the following actions:
  # ibm_iam_service_policy.policy will be created
  + resource "ibm_iam_service_policy" "policy" {
      + account_management = false
      + description        = "IAM Service Policy"
      + iam_service_id     = "ServiceId-d9a2c335-da2f-4394-9b5a-378f5958cccc"
      + id                 = (known after apply)
      + roles              = [
          + "Writer",        ]
      + transaction_id     = (known after apply)
      + resources {
          + attributes           = {
              + "resource" = "ib-eude-prueba-pre"
            }
          + resource_instance_id = "5a23493a-3bb1-41e8-8bae-c78bf0696577"
          + service              = "cloud-object-storage"
        }
    }
Plan: 1 to add, 0 to change, 0 to destroy.
```
We add more policies on our Terraform code also for the  same bucket, we name the new policy as "policy1". This is the only change we will make.
```
resource "ibm_iam_service_policy" "policy" {
  iam_service_id = "ServiceId-d9a2c335-da2f-4394-9b5a-378f5958cccc"
  roles          = ["Writer"]
  description    = "IAM Service Policy"
  
   resources {
    service              = "cloud-object-storage"
    resource_instance_id = element(split(":", "5a23493a-3bb1-41e8-8bae-c78bf0696577"), 7)
    attributes = {
      "resource" = "ib-eude-prueba-pre"
    }
    }
}
resource "ibm_iam_service_policy" "policy1" {
  iam_service_id = "ServiceId-12c58e38-71d1-4642-b40b-919128def555"
  roles          = ["Writer"]
  description    = "IAM Service Policy"
  
   resources {
    service              = "cloud-object-storage"
    resource_instance_id = element(split(":", "5a23493a-3bb1-41e8-8bae-c78bf0696567"), 7)
    attributes = {
      "resource" = "ib-prueba5-pre"
    }
    }
}  
```
When we want to apply the new policy added, we can observe the plan is detecting 1 add (the new policy) and 1 modify which is not correct. Although the change on the code is only for the new policy added, the provider replaces the policy (which is already applied) for the same name.
```
Terraform will perform the following actions:
  # ibm_iam_service_policy.policy will be updated in-place
  ~ resource "ibm_iam_service_policy" "policy" {
        id                 = "ServiceId-d9a2c335-da2f-4394-9b5a-378f5958b7fc/0e90d4f5-934f-4931-8b7b-ce6e644ee113"
        # (5 unchanged attributes hidden)
      ~ resources {
          ~ attributes           = {
              + "resource" = "ib-eude-prueba-pre"
            }
          - resource             = "ib-eude-prueba-pre" -> null
            # (2 unchanged attributes hidden)
        }
    }
  # ibm_iam_service_policy.policy1 will be created
  + resource "ibm_iam_service_policy" "policy1" {
      + account_management = false
      + description        = "IAM Service Policy"
      + iam_service_id     = "ServiceId-12c58e38-71d1-4642-b40b-919128def555"
      + id                 = (known after apply)
      + roles              = [
          + "Writer",
        ]
      + transaction_id     = (known after apply)
      + resources {
          + attributes           = {
              + "resource" = "ib-prueba5-pre"
            }
          + resource_instance_id = "5a23493a-3bb1-41e8-8bae-c78bf0696567"
          + service              = "cloud-object-storage"
        }
    }
Plan: 1 to add, 1 to change, 0 to destroy.
```
This is an issue because even if we don't make any change on the policies is it detected an untrue change and makes a remplacement (on all the policies) which can lead to cuts in the correct development of the services.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

`
Initializing provider plugins...
- Finding hashicorp/null versions matching "3.1.0"...
- Finding ibm-cloud/ibm versions matching "~> 1.0"...
- Finding hashicorp/vault versions matching "~> 2.24.0"...
- Installing hashicorp/null v3.1.0...
- Installed hashicorp/null v3.1.0 (unauthenticated)
- Installing ibm-cloud/ibm v1.42.0...
- Installed ibm-cloud/ibm v1.42.0 (unauthenticated)
- Installing hashicorp/vault v2.24.0...
- Installed hashicorp/vault v2.24.0 (unauthenticated)

Terraform version 1.2.9

### Affected Resource(s)

*`ibm_iam_service_policy`

### Terraform Configuration Files

[https://github.com/terraform-ibm-modules/terraform-ibm-iam](url)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by hkantare** [comment]
As per this resource the cusotmer is sending a "resource" as part of attributes . The "resource" is not a custom attribute it already supported at the higher level in "resources" argument. If any argument which is supported at higher level is sent as part of attributes we will not update state file since its difficult to find whether its belongs to "resources" or "attributes". attributes should be used to sent any custome attribute which is not supported at "resources" level

```
resource "ibm_iam_service_policy" "policy" {
  iam_service_id = "ServiceId-d9a2c335-da2f-4394-9b5a-378f5958cccc"
  roles          = ["Writer"]
  description    = "IAM Service Policy"
  
   resources {
    service              = "cloud-object-storage"
    resource_instance_id = element(split(":", "5a23493a-3bb1-41e8-8bae-c78bf0696577"), 7)
    attributes = {
      "resource" = "ib-eude-prueba-pre"
    }
    }
}

Above needs to be changed
```
resource "ibm_iam_service_policy" "policy" {
  iam_service_id = ibm_iam_service_id.serviceID.id
  roles          = ["Writer"]

  resources {
    service              = "cloud-object-storage"
    resource_instance_id = element(split(":", "5a23493a-3bb1-41e8-8bae-c78bf0696577"), 7)
    resource             = "ib-eude-prueba-pre"

  }
}
```
