### ISSUE TITLE
Location list on ibm_database documentation is out of date

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#4242]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_database

### Description

The list of ICD locations seems to be incorrect here -> https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#location

> - [location](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#location) - (Required, String) The location where you want to deploy your instance. The location must match the region parameter that you specify in the provider block of your Terraform configuration file. The default value is us-south. Currently, supported regions are us-south, us-east, eu-gb, eu-de, au-syd, jp-tok, oslo01.

`oslo01` does not seem to be a valid region
`br-sao`, `ca-tor`, `che01`, `jp-osa` and `par01` are missing

### References

* #0000

**Comment by omaraibrahim** [comment]
@ocofaigh thank you for taking care of that and good catch!
