### ISSUE TITLE
ibm_storage_block 

### ISSUE THREAD

**Issue by viveknangal** [IBM-Cloud/terraform-provider-ibm#429]
We're  trying to automate the process of attaching endurance storage to a VM , for the same , would like to ask that how to retrieve  the Username,Password,IQN details for a machine which is authorised to connect with Endurance storage. Currently couldn't find a way do it in terraform (like Data resources)

### Terraform Version
terraform -v
Terraform v0.11.7
+ provider.ibm (unversioned)

### Affected Resource(s)
- ibm_storage_block 

### Expected Behavior
Way to retrieve  the Username,Password,IQN details of authorised  host which is attached to a endurance storage.

Please suggest what is recommended way to automate the block storage association as currently we couldn't  find any Data resources as well for block storage.

**Comment by hkantare** [comment]
We already support providing the information of Username,pwd,IQN details

https://ibm-cloud.github.io/tf-ibm-docs/v0.12.0/r/storage_block.html
```
allowed_host_info - The user name, password, and host IQN of the hosts with access to the storage.
```
1) Create VM instance
2)Create block storage by associating the VM

Sample configuration
```


resource "ibm_compute_vm_instance" "storagevm2" {
    hostname = "test-sto"
    domain = "example.com"
    os_reference_code = "DEBIAN_8_64"
    datacenter = "ams03"
    network_speed = 100
    hourly_billing = true
    cores = 1
    memory = 1024
    disks = [25]
    local_disk = false
}

resource "ibm_storage_block" "bs_endurance" {
        type = "Endurance"
        datacenter = "ams03"
        capacity = 40
        iops = 2
        snapshot_capacity = 20
        os_format_type = "Linux"
		notes = "testinfo"
		hourly_billing = true
		allowed_virtual_guest_ids = [ "${ibm_compute_vm_instance.storagevm2.id}" ]
}
```
Now we can access host info
```
 allowed_host_info.0.host_iqn 
  allowed_host_info.0.id
  allowed_host_info.0.password
  allowed_host_info.0.username
```

**Comment by viveknangal** [comment]
Thanks @hkantare , I got it now somehow missed the documentation ,my bad.

Btw, is it possible to fetch the VM instance(i.e ibm_compute_vm_instance)  root login credentials  as well using Terraform

**Comment by hkantare** [comment]
No we don't expose any login credentials of VM.

**Comment by viveknangal** [comment]
Appreciated @hkantare your quick response. Thank you as always.
