### ISSUE TITLE
Include installation instructions in README?

### ISSUE THREAD

**Issue by jthomas** [IBM-Cloud/terraform-provider-ibm#431]
This is a small documentation feedback improvement based on trying to use the provider plugin.

Could the installation instructions from [here](https://ibm-cloud.github.io/tf-ibm-docs/index.html#using-terraform-with-the-ibm-cloud-provider) be included in this repo's README? It wasn't clear to me as a user new to terraform how I would install the plugin from starting on this repository. This is well explained in the official docs but it's not clear that this is possible from scanning the README. Could that section be linked to or copied over the main README?

**Comment by jjasghar** [comment]
Seems reasonable. I’ve also put in a blogpost on how to do this from soup to nuts on getting it to work.

Do you mind putting a PR in with what you’d think the instructions should look like and we can get the team to look at it?

**Comment by jjasghar** [comment]
I did get this published. https://developer.ibm.com/tutorials/using-terraform-and-the-ibm-cloud/

**Comment by hkantare** [comment]
closing the issue
