### ISSUE TITLE
Support for accepting a transit gateway connection

### ISSUE THREAD

**Issue by vburckhardt** [IBM-Cloud/terraform-provider-ibm#4347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Scenario:
- Transit geteway used to connect VPCs located in different account
- When adding a connection to a VPC in a different account, there is a need for a user with sufficient priviledge in the target account to accept the connection. 

There is API support for accepting connection - see https://cloud.ibm.com/apidocs/transit-gateway#create-transit-gateway-connection-actions 

However, the provider is currently missing this capability.

### New or Affected Resource(s)

* ibm_tg_connection

### References

* #0000

**Comment by kennburger** [comment]
This enhancement is planned to be included in the March terraform release which is currently targeted for end of March.
