### ISSUE TITLE
Timeout on cloudant resource is not honored

### ISSUE THREAD

**Issue by vburckhardt** [IBM-Cloud/terraform-provider-ibm#4356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_cloudant

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
resource "ibm_cloudant" "cloudant_instance" {
  name     = var.instance_name
  location = var.region
  plan     = var.plan

  legacy_credentials  = var.legacy_credentials  # switch authentication between IAM legacy credentials
  include_data_events = var.include_data_events # Sends data event types to Activity Tracker with LogDNA
  capacity            = var.capacity
  resource_group_id   = var.resource_group_id
  enable_cors         = false
  tags                = var.tags
  service_endpoints   = var.service_endpoints

  timeouts {
    create = "60m" # Extending provisioning time to 60 minutes
  }
}
```

### Debug Output

[terraform-output.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/10792288/terraform-output.txt)
[terraform.log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/10792289/terraform.log)

### Expected Behavior

It should give the creation and resize at least 60 minutes to complete. Also, this will not be enough time if set to 100

### Actual Behavior

It failed after 5 minutes instead of the 60 minutes.

### Steps to Reproduce

1. Set the capacity = 25
2. terrafrom apply

### References

* #0000

**Comment by ricellis** [comment]
Thanks for the report.
The resource has been created, but the timeout occurs while waiting for a state change during the capacity update (that has a [5 minute timeout here](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/3a53b2e1de714bc1b0833cbc3687c22130b17ae0/ibm/service/cloudant/resource_ibm_cloudant.go#L548)).
We'll look into whether that timeout is unreasonable or needs to be adaptable based on other configured timeouts.

**Comment by eiri** [comment]
I've open #4414 to remediate this behavior of `ibm_cloudant` resource. We can't speed up the back-end's provisioning, but at least with this change the process will stop breaking the instance creation process. I'm not sure when the terraform team will get to review the PR, so unfortunately can't give the ETA.

**Comment by emlaver** [comment]
@vburckhardt the [v1.52.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.52.0) release contains the #4414 work.  If you can verify with this version or the latest ([v1.52.1](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.52.1)) that things are working better that would be great.

**Comment by ocofaigh** [comment]
Hi @emlaver This issue can be closed - we verified this fix works well

**Comment by emlaver** [comment]
@ocofaigh thanks for the update.  I don't have access to close this ticket.  I believe @vburckhardt or the TF team can close this out.

**Comment by ocofaigh** [comment]
Vincent is on vacation - @hkantare are you able to close please?

**Comment by hkantare** [comment]
closing the issue based on comments
