### ISSUE TITLE
Cross region Cloud Object Storage invalid check on KMS/KP key

### ISSUE THREAD

**Issue by shemau** [IBM-Cloud/terraform-provider-ibm#4359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

This has been seen on different versions on different platforms, including

    terraform -v
    Terraform v1.3.0
    on darwin_amd64

     Your version of Terraform is out of date! The latest version
     is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html
     
With IBM Provider 1.49

### Affected Resource(s)

* ibm_cos_bucket

### Terraform Configuration Files

The following was attempted with different cross_region_locations and key_protect keys from different MZR regions

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
    # module.cos_bucket2.ibm_cos_bucket.cos_bucket[0] will be created
    + resource "ibm_cos_bucket" "cos_bucket" {
        + bucket_name           = "n05-bucket-2"
        + crn                   = (known after apply)
        + cross_region_location = "eu"
        + endpoint_type         = "public"
        + force_delete          = true
        + id                    = (known after apply)
        + key_protect           = (known after apply)
        + resource_instance_id  = (known after apply)
        + s3_endpoint_direct    = (known after apply)
        + s3_endpoint_private   = (known after apply)
        + s3_endpoint_public    = (known after apply)
        + storage_class         = "standard"

        + expire_rule {
            + days    = 365
            + enable  = true
            + prefix  = (known after apply)
            + rule_id = (known after apply)
          }
      }
```

The following observations were make (key MZR, bucket cross region location)
eu-gb/eu failed
eu-gb/us failed
us-south/us passed
eu-de/eu passed
eu-de/us passed

A KMS/KP key from eu-gb should be acceptable for encrypting an eu (or other) cross regional bucket.

### Debug Output

    ╷
    │ Error: InvalidRequest: The region provided in the KMS key CRN does not provide cross region support.
    │ 	status code: 400, request id: bf027227-4cb5-4b50-bc2d-4a55cceb2dc2, host id: 
    │ 
    │   with module.cos_bucket2.ibm_cos_bucket.cos_bucket[0],
    │   on ../../main.tf line 76, in resource "ibm_cos_bucket" "cos_bucket":
    │   76: resource "ibm_cos_bucket" "cos_bucket" {
    │ 
    ╵

### Expected Behavior

An encrypted cross regional bucket should be created

### Actual Behavior

An error occurred preventing the bucket from being created.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing important, the intended is for cross regional EU buckets encrypted with a key issued in an EU zone that is not inside the eu cross regional zones.

### References

* [200](https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/200) was the trigger for the investigation that lead to this issue being raised.

**Comment by IBM-diksha** [comment]
@shemau This is not specifically related to the terraform provider , rather it is more  about the functionality support.
Also you can refer to this ,
Please see https://cloud.ibm.com/docs/key-protect?topic=key-protect-ha-dr#availability
There are three regions, us-south (located in Dallas, Texas, United States), jp-tok (located in Tokyo, Japan), and eu-de (located in Frankfurt, Germany) where Key Protect has failover support into a separate region where data is replicated into standby infrastructure.

**Comment by IBM-diksha** [comment]
Can you please go ahead and close this issue as this functionality is not supported in the regions that you mentioned. If anything is needed please open a new ticket.
Thank you

**Comment by IBM-diksha** [comment]
I will be closing this ticket.Please feel free to open a new ticket if anything is needed.
Thank you.

**Comment by IBM-diksha** [comment]
I will be closing this ticket.Please feel free to open a new ticket if anything is needed.
Thank you.
