### ISSUE TITLE
terraform ibm_cm_version category can not be specified

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#4372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
tf version
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.50.0

Your version of Terraform is out of date! The latest version
is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* ibm_cm_version

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.

resource "ibm_cm_version" "version" {
...
}
```

How does a catalog offering `category` get specified?

I made this offering with the ibm cloud console:
![image](https://user-images.githubusercontent.com/6932057/221664485-edc6e9fa-ccbd-4173-84ba-c850071f1262.png)

This is one created with terraform:

![image](https://user-images.githubusercontent.com/6932057/221664554-0e774ee6-0613-4879-a0ca-a38d8cea277d.png)

The docs argument list can be found here: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cm_offering#argument-reference

![image](https://user-images.githubusercontent.com/6932057/221664806-2d5b8e25-944b-46a0-ba68-02b2ed3c7bd9.png)

* #0000

**Comment by benbuchanan** [comment]
Hi @powellquiring , the category is set at the `ibm_cm_offering` level with the `tags` argument.  If you provide a tag that maps to a valid category ID it will show up as the offering's category.  You can run the CLI command `ibmcloud catalog offering category-options` to see valid tags or there might be a doc somewhere.

**Comment by powellquiring** [comment]
The following did work for me:
```
resource "ibm_cm_offering" "ubuntu" {
  catalog_id        = local.offering.catalog_id
  label             = local.offering.label
  name              = local.offering.name
  offering_icon_url = local.offering.offering_icon_url
  tags              = ["virtualservers"]
}
```

If this is working as designed it would be possible to resolve this issue by updating the documentation:

- [ ] Include tags in the example
- [ ] in the tags description field explain how the list of possible tags could be determined and the impact choosing a tag.
- [ ] explain how tags maps to category in the UI
