### ISSUE TITLE
ibm_database for MySQL fails to complete/refresh/import

### ISSUE THREAD

**Issue by tlnd** [IBM-Cloud/terraform-provider-ibm#4380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform: `Terraform v1.3.9 on linux_amd64`
Provider: `registry.terraform.io/ibm-cloud/ibm v1.51.0-beta0`, also tested `v1.50.0`

### Affected Resource(s)

* ibm_database

### Terraform Configuration Files

Provider config and variables
```hcl
terraform {
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = "1.51.0-beta0"
    }
  }
}

provider "ibm" {
  ibmcloud_api_key = var.ibmcloud_api_key
}

variable "ibmcloud_api_key" {
  type        = string
  sensitive   = true
  description = "IBM Cloud API key"
}

variable "resource_group_name" {
  type        = string
  description = "Name of the IBM resource group"
  default     = "default"
}
```

Database resource:
```hcl
data "ibm_resource_group" "group" {
  name = var.resource_group_name
}

resource "ibm_database" "test" {
  name              = "test"
  plan              = "standard"
  location          = "eu-de"
  service           = "databases-for-mysql"
  resource_group_id = data.ibm_resource_group.group.id
  service_endpoints = "public-and-private"
}
```

It was also tested with providing an `adminpassword` attribute and/or adding a user via `users` attribute as well as with defining resource allocation in `group` attribute.

### Debug Output

https://gist.github.com/tlnd/6ca23f8e449933ed20763afe38f6452f

### Panic Output

The `terraform apply` results in:

```
│ Error: [ERROR] Error waiting for create database instance (crn:v1:bluemix:public:databases-for-mysql:eu-de:a/xxxx:yyyy::) to complete: [ERROR] Error ICD interface not ready after create: crn:v1:bluemix:public:databases-for-mysql:eu-de:a/xxxx:yyyy:: with error [ERROR] Error getting database config for: crn:v1:bluemix:public:databases-for-mysql:eu-de:xxxx:yyyy:: with error %!s(<nil>)
│
│   with ibm_database.test,
│   on db.tf line 5, in resource "ibm_database" "test":
│    5: resource "ibm_database" "test" {
│
```

A subsequent `terraform refresh` results in:

```
│ Error: [ERROR] Error getting database config while updating adminpassword for: crn:v1:bluemix:public:databases-for-mysql:eu-de:a/xxxx:yyyy:: with error Internal Server Error
│
│   with ibm_database.test,
│   on db.tf line 5, in resource "ibm_database" "test":
│    5: resource "ibm_database" "test" {
│
```

### Expected Behavior

The database is created, terraform completes successfully and the database can be managed via TF afterwards.

### Actual Behavior

The database is created, however, `terraform` does not complete successfully. Also, refreshing the state or importing the created DB resource fails.

### Steps to Reproduce

1. `terraform apply` - already fails
1. `terraform refresh` - shows related error

### Important Factoids

n/a

### References

n/a

**Comment by omaraibrahim** [comment]
Hi @tlnd! Thanks for reaching out and thank you for providing the logs!

You're attempting to interact with a database in the `eu-de` region however from the logs we see that your Host/API endpoint is in `us-south`.

Example:
```
2023-03-01T10:53:39.331+0100 [DEBUG] provider.terraform-provider-ibm_v1.51.0-beta0: [DEBUG] REQUEST: [2023-03-01T10:53:39+01:00] GET /v4/ibm/deployments/crn:v1:bluemix:public:databases-for-mysql:eu-de:a%2F491ca4b4d40a4b97b92448319a8170a3:2569ded0-01cc-4ff7-b44a-f0364c69cf88:: HTTP/1.1
2023-03-01T10:53:39.332+0100 [DEBUG] provider.terraform-provider-ibm_v1.51.0-beta0: Host: api.us-south.databases.cloud.ibm.com
2023-03-01T10:53:39.332+0100 [DEBUG] provider.terraform-provider-ibm_v1.51.0-beta0: Accept: application/json
2023-03-01T10:53:39.332+0100 [DEBUG] provider.terraform-provider-ibm_v1.51.0-beta0: Accept-Language: en
2023-03-01T10:53:39.332+0100 [DEBUG] provider.terraform-provider-ibm_v1.51.0-beta0: Authorization: [PRIVATE DATA HIDDEN]
2023-03-01T10:53:39.332+0100 [DEBUG] provider.terraform-provider-ibm_v1.51.0-beta0: Content-Type: application/json
2023-03-01T10:53:39.332+0100 [DEBUG] provider.terraform-provider-ibm_v1.51.0-beta0: User-Agent: Bluemix-go SDK 0.1 / linux
2023-03-01T10:53:39.332+0100 [DEBUG] provider.terraform-provider-ibm_v1.51.0-beta0: X-Original-User-Agent: terraform-provider-ibm/1.51.0-beta0
```

Hence, we need to set the API endpoint to eu-de. To do so please do the following:

```
export IBMCLOUD_ICD_API_ENDPOINT=https://api.eu-de.databases.cloud.ibm.com/
export IBMCLOUD_DATABASES_API_ENDPOINT=https://api.eu-de.databases.cloud.ibm.com/v5/ibm
```

**Comment by tlnd** [comment]
Hi @omaraibrahim! Thanks for your response.

I followed your advise and the provisioning as well as importing existing databases now works as expected.

Now being aware of the root cause and checking the documentation again, I have to admit that there is indeed some related information that I should have considered upfront. Hence, closing the issue.

Thanks a lot for your kind support!

**Comment by omaraibrahim** [comment]
@tlnd happy to help 😄
