### ISSUE TITLE
Feature request: Add timeout parameter to ibm_lb_service_group resource

### ISSUE THREAD

**Issue by zenitraM** [IBM-Cloud/terraform-provider-ibm#439]
We need to setup the `timeout` value that is available on the service group API resource:
https://softlayer.github.io/reference/datatypes/SoftLayer_Network_Application_Delivery_Controller_LoadBalancer_Service_Group/

However it does not seem to be exposed by the Terraform resource, could this be added?

Thanks!

**Comment by hkantare** [comment]
Closing the issue
