### ISSUE TITLE
ibm_sm_iam_credentials_secret: fields marked as optional are actually required

### ISSUE THREAD

**Issue by Gorgonx7** [IBM-Cloud/terraform-provider-ibm#4391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
Terraform v1.2.9,  provider registry.terraform.io/ibm-cloud/ibm v1.51.0

### Affected Resource(s)

* ibm_sm_iam_credentials_secret

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_sm_iam_credentials_secret" "private_worker_pool_api_key" {
   instance_id = <some guid>
   region = local.region
   name = "<some name>"
   description = "<some description"
   service_id              = <service id, id>
   secret_group_id           = <secret group id>
# }

```

### Panic Output
```
╷
│ Error: Missing required argument
│ 
│   on main.tf line 248, in resource "ibm_sm_iam_credentials_secret" "development_cluster_api_key":
│  248: resource "ibm_sm_iam_credentials_secret" "development_cluster_api_key" {
│ 
│ The argument "ttl" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on main.tf line 248, in resource "ibm_sm_iam_credentials_secret" "development_cluster_api_key":
│  248: resource "ibm_sm_iam_credentials_secret" "development_cluster_api_key" {
│ 
│ The argument "reuse_api_key" is required, but no definition was found.
╵
```

### Expected Behavior
The documentation marks these as optional, but they seem to be required https://registry.terraform.io/providers/IBM-Cloud/ibm/1.51.0/docs/resources/sm_iam_credentials_secret

I think these should be optional 

### Actual Behavior
TF will not validate due to required variables not being present even though they are marked optional

### Steps to Reproduce
load the above tf into your env with arbitrary values and try a `tf validate`

### References

* #0000

**Comment by IdanAdar** [comment]
It was decided to close the PR. Closing ticket.
