### ISSUE TITLE
Feature Request: Update kubernetes version of worker pools

### ISSUE THREAD

**Issue by ruben-burr** [IBM-Cloud/terraform-provider-ibm#440]
Hi there,

perhaps this solved already, but I could not find out, how it works. My goal is to update the kubernetes version of a cluster and its workers without downtime for the applications in a declarative way. 

My probably too naive attempt was to just update the kube_version attribute of the cluster resource. This updated the master nodes. But the workers are still on the old version. And I did not find a way to update the workers of the worker pools attached to the cluster.

Did you consider the worker update use case already?

Greets, Ruben

**Comment by Praveengostu** [comment]
Hi Ruben, 
We will provision to update the workers version from the cluster resource. We will be enhancing the workers_info attribute to update the workers version.
ex:
```
resource "ibm_container_cluster" "cluster" {
  name       = "test1"
  datacenter = "ams03"

  kube_version    = "1.11.4"
  region          = "eu-de"
  machine_type    = "u2c.2x4"
  isolation       = "public"
  public_vlan_id  = "1764435"
  private_vlan_id = "1764491"

  workers_info = [{
    id      = "kube-ams03-cr166179849c9a469581f28939874d0c82-w1"
    version = "1.11.4"
  },
{
    id      = "kube-ams03-cr166179849c9a469581f28939874d0c82-w2"
    version = "1.11.4"
  },]
}
```
One can define the workers_info with the set of workers and the version to which they would like to update(ideally the master kube version). Let us know if it helps

**Comment by Praveengostu** [comment]
Hi @ruben-burr 
Yes the workers_info is a computed and optional field. It gets populated with all the workers of the cluster. `kube_version` is the attribute used to update the master kube version. To update all the workers when the cluster is updated we can provide a boolean `update_workers` which will update all the workers under cluster if set to true or user can use the workers_info to update the desired workers.
The null resource can be used to run the config prior to update.

**Comment by kskewes** [comment]
I believe at the moment if you upgrade all workers in a pool via UI IBM does a rolling upgrade. 
Can end up with unbalanced workloads like this as effectively shuffles pods onto remaining workers.
We create a new worker pool when upgrade and then terminate old one with use of cordon and drain.
Not using Terraform for this.

**Comment by Praveengostu** [comment]
Fix available in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.14.0

**Comment by hkantare** [comment]
closing the issue
