### ISSUE TITLE
ibm_pi_volume_attach : attaching volumes takes too long , timeout error

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#4430]
Hello,

**ibm_pi_volume_attach** used to attach volumes to instances under 3 mins before.
Now it takes around **35 mins** to attach.
default timeout is set to 15 mins.
Context deadline exceeded error.

THis happens in **syd05 , lon06 and tok04** as of now. 
in syd04 , it finishes under 3 mins.

Have attached the terraform trace logs.
[terraform.log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/11049594/terraform.log)

**Comment by dhirendersingh19** [comment]
I checked the logs and found that it took a long time for the volume to change its state from 'attaching' to 'in-use'; it took almost 30 minutes. The problem is at the host/storage level and not at the Terraform provider level.

**Comment by surajsbharadwaj** [comment]
It has been fixed
