### ISSUE TITLE
Can't create backup policy plan in specific resource group

### ISSUE THREAD

**Issue by chbk** [IBM-Cloud/terraform-provider-ibm#4438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

- Terraform v1.4.2
- ibm-cloud/ibm v1.51.0

### Affected Resource(s)

* ibm_is_backup_policy_plan

### Terraform Configuration Files

```hcl
data "ibm_resource_group" "resource_group" {
  name = "dev"
}

resource "ibm_is_backup_policy" "backup_policy" {
  name = "backup-policy"
  match_user_tags = ["snapshot:24h"]
  resource_group = data.ibm_resource_group.resource_group.id
}

resource "ibm_is_backup_policy_plan" "backup_plan" {
  name = "backup-plan"
  cron_spec = "30 00 * * *"
  backup_policy_id = ibm_is_backup_policy.backup_policy.id
}
```

### Expected Behavior

Creates a backup policy plan in the `dev` resource group.

### Actual Behavior

Attempts to create a backup policy plan in the `default` resource group.

```
module.deploy.ibm_is_backup_policy_plan.backup_plan: Creating...
```
```
│ Error: [ERROR] CreateBackupPolicyPlanWithContext failed Default Resource Group details is not found
```
```
"errors": [
    {
        "code": "backup_service_default_resource_group_not_found",
        "message": "Default Resource Group details is not found",
        "more_info": "https://cloud.ibm.com/docs/vpc?topic=vpc-baas-troubleshoot"
    }
]
```

### Steps to Reproduce

Setup a Service ID API Key with the following permissions:

| Service | Resources | Role |
| --- | --- | --- |
| VPC Infrastructure Services | dev resource group | Viewer, Operator, Editor |
| Resource group only | dev resource group | Viewer |

1. `export IC_API_KEY=...`

2. `terraform apply`

**Comment by deepaksibm** [comment]
looking at it

**Comment by deepaksibm** [comment]
Hi @chbk We tried reproducing this issue with multiple runs but it is not reproducible. Policy plan gets created with any resource group we provide.

**Comment by sumitkumartiwari** [comment]
@chbk Can you check and revert ?

**Comment by chbk** [comment]
I attempted to reproduce this with:
- Terraform v1.4.6
- ibm-cloud/ibm v1.52.1

Here is the bootstrap configuration to create:
- a resource group
- a service id with appropriate permissions and an api key
- [service-to-service authorizations for backups](https://cloud.ibm.com/docs/vpc?topic=vpc-backup-s2s-auth)

```terraform
terraform {
  required_providers {
    ibm = {
      source = "IBM-Cloud/ibm"
      version = "~> 1.52.0"
    }
  }
}

provider "ibm" {
  region = "eu-de"
}

resource "ibm_resource_group" "resource_group" {
  name = "test-backup-policy-resource-group"
}

resource "ibm_iam_service_id" "service_id" {
  name = "test-backup-policy-service-id"
}

resource "ibm_iam_service_api_key" "service_api_key" {
  name = "test-backup-policy-api-key"
  iam_service_id = ibm_iam_service_id.service_id.iam_id
  file = "service-api-key"
}

resource "ibm_iam_service_policy" "resource_policy" {
  iam_service_id = ibm_iam_service_id.service_id.id
  roles = ["Viewer"]
  resources {
    resource_type = "resource-group"
    resource_group_id = ibm_resource_group.resource_group.id
  }
}

resource "ibm_iam_service_policy" "vpc_policy" {
  iam_service_id = ibm_iam_service_id.service_id.id
  roles = ["Viewer", "Operator", "Editor"]

  resources {
    service = "is"
    resource_group_id = ibm_resource_group.resource_group.id
  }
}

resource "ibm_iam_authorization_policy" "backup_volume_authorization_policy" {
  source_resource_group_id = ibm_resource_group.resource_group.id
  target_resource_group_id = ibm_resource_group.resource_group.id
  source_service_name = "is"
  target_service_name = "is"
  source_resource_type = "backup-policy"
  target_resource_type = "volume"
  roles = ["Operator"]
}

resource "ibm_iam_authorization_policy" "backup_instance_authorization_policy" {
  source_resource_group_id = ibm_resource_group.resource_group.id
  target_resource_group_id = ibm_resource_group.resource_group.id
  source_service_name = "is"
  target_service_name = "is"
  source_resource_type = "backup-policy"
  target_resource_type = "instance"
  roles = ["Operator"]
}

resource "ibm_iam_authorization_policy" "backup_snapshot_authorization_policy" {
  source_resource_group_id = ibm_resource_group.resource_group.id
  target_resource_group_id = ibm_resource_group.resource_group.id
  source_service_name = "is"
  target_service_name = "is"
  source_resource_type = "backup-policy"
  target_resource_type = "snapshot"
  roles = ["Editor"]
}
```

Here is the configuration for the backup policy that should be managed by the service id, as posted originally:

```terraform
terraform {
  required_providers {
    ibm = {
      source = "IBM-Cloud/ibm"
      version = "~> 1.52.0"
    }
  }
}

provider "ibm" {
  region = "eu-de"
}

data "ibm_resource_group" "resource_group" {
  name = "test-backup-policy-resource-group"
}

resource "ibm_is_backup_policy" "backup_policy" {
  name = "test-backup-policy"
  match_user_tags = ["snapshot:24h"]
  resource_group = data.ibm_resource_group.resource_group.id
}

resource "ibm_is_backup_policy_plan" "backup_plan" {
  name = "test-backup-plan"
  cron_spec = "30 00 * * *"
  backup_policy_id = ibm_is_backup_policy.backup_policy.id
}
```

Steps taken:

1. Use an api key with sufficient permissions to apply the bootstrap configuration:
```bash
export IC_API_KEY=...
```

2. Apply the bootstrap configuration:
```bash
cd bootstrap
terraform init
terraform apply
```

3. Use the generated service id api key in the new `service-api-key` file:
```bash
export IC_API_KEY=...
```

4. Apply the backup policy configuration:
```bash
cd backup-policy
terraform init
terraform apply
```

At this point I get the following error:

    Error: [ERROR] Given Resource Group is not found in the account : %!s(<nil>)

If I then log into IBM Cloud and manually add permissions for the service id to view `test-backup-policy-resource-group`, the error disappears, but I get the following error instead:

    "errors": [
      {
        "code": "backup_policies_s2s_setup_not_completed",
        "message": "service-to-service authorization has not been correctly setup for account 'xxxxxxxxxxxxx'",
        "more_info": "https://cloud.ibm.com/docs/vpc?topic=vpc-baas-troubleshoot"
      }
    ]

Setting the service-to-service authorization policies manually through IBM Cloud instead gives the same error.

**Comment by SunithaGudisagarIBM1** [comment]
@chbk the error says s2s authorisation is not set properly, Can you please reverify and revert back to us?
https://cloud.ibm.com/docs/vpc?topic=vpc-backup-s2s-auth

Mean while i will check with backup policy team Lizeth Monzon on the same

Thank you

**Comment by SunithaGudisagarIBM1** [comment]
@chbk for s2s authorisation please reach out to support team.

**Comment by SunithaGudisagarIBM1** [comment]
@chbk we are closing this issue, please do revert to us if u have any issue related to the problem stated here.
