### ISSUE TITLE
Database version update fails with IBM service instance resource

### ISSUE THREAD

**Issue by psawant29** [IBM-Cloud/terraform-provider-ibm#444]
Hi there,

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- ibm_service_instance

We are using ibm_service_instance resource to provision the ibm cloud compose services
Database version is passed as parameters to this resource
Able to deploy the compose database successfully with required version 
When we modify the database version and apply again database version upgrade doesn't work through ibm_service_instance resource

But it works successfully through rest api (https://www.compose.com/articles/the-ibm-cloud-compose-api/) and bluemix UI
Rest api :  PATCH /2016-07/deployments/:id/versions

### Expected Behavior
Database upgrade should work through ibm_service_instance  resource .

### Actual Behavior
When modified the database version and run the terraform apply again
Database upgrade failed with error 
Error updating service Request failed with status code 502
"error_code" "CF-ServiceBrokerRequestRejected"

### Important Factoids
Tried upgrading compose for mongodb version from 3.2.11 -> 3.2.18 , it works through rest api , doesnot work through terraform resource

**Comment by hkantare** [comment]
We have separate resource to work with databases 
https://ibm-cloud.github.io/tf-ibm-docs/v0.21.0/r/database.html which can handle update of verison
