### ISSUE TITLE
Document the default for image_port in ibm_code_engine_app

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/terraform-provider-ibm#4440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_code_engine_app

### Description
![image](https://user-images.githubusercontent.com/8414748/227929230-5c6b28bc-e75f-4f78-845f-0f59706011c6.png)

**Comment by michael-magrian** [comment]
Can we close this? @data-henrik
