### ISSUE TITLE
resource_ibm_lb_vpx - plan issue

### ISSUE THREAD

**Issue by jkhan001** [IBM-Cloud/terraform-provider-ibm#445]
terraform provisioning is failing for version = 12.1 for resource ibm_lb_vpx
we have tried the following configuration - 
resource "ibm_lb_vpx" "testacc_foobar_vpx" {
    datacenter = "dal09"
    speed = 10
    version = "12.1"
    plan = "Standard"
    ip_count = 1
}
it fails with the following error " Error Cannot find Application Delivery Controller prices 'VPX version, speed or plan have incorrect values'."

**Comment by hkantare** [comment]
closing the issue
