### ISSUE TITLE
Service endpoint missing in data source of ibm_is_virtual_endpoint_gateway

### ISSUE THREAD

**Issue by paribiswas** [IBM-Cloud/terraform-provider-ibm#4466]
We need the service endpoint in the data source of bm_is_virtual_endpoint_gateway
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_virtual_endpoint_gateway#attribute-reference
It is missing in the code.
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateway.go

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by deepaksibm** [comment]
looking into it

**Comment by steven4ibm** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
