### ISSUE TITLE
ibm_is_bare_metal_server: change to security groups does not trigger change

### ISSUE THREAD

**Issue by sean-freeman** [IBM-Cloud/terraform-provider-ibm#4479]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/ibm-cloud/ibm v1.52.0
```

### Affected Resource(s)

* ibm_is_bare_metal_server

### Debug Output

```
  # ibm_is_bare_metal_server.bm_vpc_host1 will be updated in-place
  ~ resource "ibm_is_bare_metal_server" "bm_vpc_host1" {
        id                 = "0737-zzzz-zzzz-zzzz-zzzz-zzzzzz"
        name               = "bm1"
        tags               = []
        # (19 unchanged attributes hidden)

      ~ primary_network_interface {
            id                        = "0737-zzzz-zzzz-zzzz-zzzz-zzzzzz"
            name                      = "garment-crying-relic-month"
          ~ security_groups           = [
              - "r006-zzzz-zzzz-zzzz-zzzz-zzzzzz",
              - "r006-zzzz-zzzz-zzzz-zzzz-zzzzzz",
                # (2 unchanged elements hidden)
            ]
            # (7 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

ibm_is_bare_metal_server: change to security groups

### Actual Behavior

ibm_is_bare_metal_server: change to security groups does not trigger change

### Steps to Reproduce

Any execution of Terraform Resource `ibm_is_bare_metal_server` where Security Groups are updated

**Comment by ujjwal-ibm** [comment]
looking
