### ISSUE TITLE
access_group_policy

### ISSUE THREAD

**Issue by ethilesen** [IBM-Cloud/terraform-provider-ibm#450]
Hi there,

I'm using 0.13.0

Trying to create a access_group_policy to All Identity and Access enabled services and it fails with 

* ibm_iam_access_group_policy.policy2: Request failed with status code: 404, ServerErrorResponse: {"errorsArray":[{"code":"BXNAC12104","response":"not_found_error","message":"Not Found Service name given returned empty query. ","level":"error","statusCode":404,"description":"Service name given returned empty query. ","transactionId":"62f223573a98464f981a07990ce9b995","instanceId":"kubernetes"}]}

resource "ibm_iam_access_group_policy" "policy2" {
  access_group_id = "${ibm_iam_service_id.serviceID.id}"
  roles        = ["Administrator","Manager"]
  resources = [{
    service = "service"  ## I'm guessing here.. 
    region  = "eu-de"
  }]
}

If I create it in GUI it lokks like this...

Policy ID:   f956f49c-dd01-42ab-9838-a6449dad31a7   
Roles:       Administrator, Manager   
Resources:                            
             Service Name             
             Service Instance         
             Region                   
             Resource Type            
             Resource                 
             Service Type       service     

However can't specify and Service Type in terraform so ?

Bra,

Espen Thilesen IBM Norway - espen.thilesen@no.ibm.com

**Comment by stevestrutt** [comment]
Hi Espen, I think the error is saying that the IAM service cannot find the '**service**' you have requested to add to the Access Group Policy. Terraform is running the request that it was told to run via the IAM API. I get exactly the same error if I run the CLI command `ibmcloud iam access-group-policy-create new1 --service-name **service** --roles Administrator` 

The question is what has to be specified to create the 'All Identity and Access enabled services' via the CLI or API. This does not appear to be documented. I do not think its supported at this time. If I specify a null service name,  --service-name "" or '' I get BXNAC12105   Forbidden Access forbidden to perform action. 

I think this is a question for support or the IAM Slack channel. 

I didn't find any reference to "Service Type" in the doc or the UI. The Terraform resource implements the same keys as the [CLI](https://console.bluemix.net/docs/cli/reference/ibmcloud/cli_api_policy.html#ibmcloud_iam_access_group_policy_create) and this does not have a service type.

**Comment by ethilesen** [comment]
Tanx - will do that..

**Comment by hkantare** [comment]
To create a policy for "All Identity and Access enabled services " we should use below but I think we have some API changes recently its failing we will fix and let you know once fix is available
```
resource "ibm_iam_access_group" "accgrp" {
  name = "test-harini"
}

resource "ibm_iam_access_group_policy" "policy" {
  access_group_id = "${ibm_iam_access_group.accgrp.id}"
  roles        = ["Viewer"]
}

```

**Comment by hkantare** [comment]
We made the changes to update to IAM policy API changes...The fix is available in master branch..

**Comment by ethilesen** [comment]
Great! Tanx - works like a charm()...

**Comment by hkantare** [comment]
closing the issue
