### ISSUE TITLE
provider Version 1.53.0 ignores the state for the secrets manager integration in Kubernetes

### ISSUE THREAD

**Issue by evtimokn** [IBM-Cloud/terraform-provider-ibm#4552]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

CLI 
Terraform v1.4.6
on linux_amd64

Provider: 1.53.0
### Affected Resource(s)

ibm_container_ingress_instance

### Terraform Configuration Files

resource "ibm_container_ingress_instance" "instance" {
  cluster = var.k8s.cluster_name
  instance_crn = data.ibm_resource_instance.secrets_manager.id
  secret_group_id = "830df9d93-731b-4fd6-zzz-393ba0f611a2" # Group xyxy under secrets-manager
  is_default = true
    depends_on = [ibm_container_vpc_cluster.cluster]
```

###  Output

  # module.k8s.ibm_container_ingress_instance.instance will be created
  + resource "ibm_container_ingress_instance" "instance" {
      + cluster           = "mycluster"
      + id                = (known after apply)
      + instance_crn      = "crn:v1:bluemix:public:secrets-manager:eu-de.....:"
      + instance_name     = (known after apply)
      + instance_type     = (known after apply)
      + is_default        = true
      + secret_group_id   = "999999999-731b-4fd6-37ab-090ba0f839a2"
      + secret_group_name = (known after apply)
      + status            = (known after apply)
      + user_managed      = (known after apply)
    }

Plan: 1 to add, 1 to change, 0 to destroy.

  Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.k8s.ibm_container_ingress_instance.instance: Creating...
module.k8s.ibm_container_addons.addons1: Modifying... [id=ch9qbntf0lk57i0gnlig]
module.k8s.ibm_container_addons.addons1: Modifications complete after 1s [id=ch9qbntf0gz57i0gnlig]
╷
│ Error: Request failed with status code: 409, ServerErrorResponse: {"incidentID":"65fa0ade-a05c-4523-909b-7b2fb69ad671","code":"EICIAE","description":"The specified instance is already registered with the cluster.","type":"Cluster","recoveryCLI":"To list all the instances registered with your cluster, run 'ibmcloud ks ingress secret instance ls'."}

### Expected Behavior

During the second run with the same variables TF should have said there is nothing to do.

When I run the TF-Script w/o any changes to code or config TF still wants to create the ressource above, although it already does exist and is available in the state-file. Hence, this resource is not refreshed properly.
When you try to run the TF-Script there is an ERROR saying, that the ressource already exists, which is correct.

### Steps to Reproduce

Run `terraform apply` twice on the same script.

**Comment by hkantare** [comment]
@lcopi 
Can you please look into the issue

**Comment by theodoracheng** [comment]
@evtimokn This seems to be happening because the cluster name is being passed in, but the cluster id is being used in the state causing a mismatch. We're working to rectify this, but in the meantime, can you try using the cluster id instead?

**Comment by evtimokn** [comment]
I tested it and it seems to be working, but only if registering is done using the cluster ID instead of name (as per docu).

**Comment by theodoracheng** [comment]
@evtimokn Yes we are working on supporting both cluster name or id.
