### ISSUE TITLE
DNS Servies Linked Zone

### ISSUE THREAD

**Issue by roder** [IBM-Cloud/terraform-provider-ibm#4580]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need TF interface to create and configure a DNS Service Linked Zone.

### New  Resource(s)

* `ibm_dns_linked_zone`

### References

* https://cloud.ibm.com/apidocs/dns-svcs#list-linked-zones
* https://cloud.ibm.com/docs/dns-svcs?topic=dns-svcs-creating-linked-zone&interface=ui
* IBM Networking client 0.40.0 ([current IBM Cloud TF provider version](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/8b9bca345600408cae6af27c6aa4205be5c8465b/go.mod#LL25C1-L25C42)) [supports DNS Linked Zones](https://github.com/IBM/networking-go-sdk/blob/6872977fc6db2d3b2d7a4356805a9667a1531504/dnssvcsv1/dns_svcs_v1.go#L3749-L4162)

This would be a similar addition to Secondary Zone support:
* [Secondary Zone Resource](https://github.com/IBM-Cloud/terraform-provider-ibm/commit/6095762199b314100ecd240fba0980b2773767d5)
* [Secondary Zone Data](https://github.com/IBM-Cloud/terraform-provider-ibm/commit/bfe59dfc6044af3a3c7c8b42e12df21d41354809)

**Comment by ronandoolan2** [comment]
@roder this issue can be closed now

**Comment by roder** [comment]
Thanks for the quick turn around @ronandoolan2!
