### ISSUE TITLE
[ICD] TF subsequent applies for PITR behaviour.

### ISSUE THREAD

**Issue by Ak-sky** [IBM-Cloud/terraform-provider-ibm#4587]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Question

- Once the PITR instance is created via TF using PITR id and PITR time, after doing subesequent TF applies with new PITR id and PITR time, TF does not destroy the previosly created PITR instance and does not create the new one. It just displays `Apply complete` as below-
      <img width="1248" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/4889052/9887d142-1acc-460f-95eb-04840c0f2a54">

- Just want to enquire what is the expected behaviour on subsequent applies for PITR?

### New or Affected Resource(s) or Datasource(s)

* ibm_database

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by alexhemard** [comment]
@Ak-sky That appears to be the expected behavior - `point_in_time_recovery_time` and `point_in_time_recovery_deployment_id` are only used during Resource creation. 

The following codes in the terraform provider show this
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/database/resource_ibm_database.go#L311
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/flex/structures.go#L2390-L2395

**Comment by Ak-sky** [comment]
So that means it will only create the PITR instance once we do TF apply for the first time and say on subsequent TF apply if we give another PITR time or PITR id it will not perform any action.
