### ISSUE TITLE
ibm_code_engine_secret not expected "data" block

### ISSUE THREAD

**Issue by escabechada** [IBM-Cloud/terraform-provider-ibm#4609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform version:
Terraform v1.4.6
provider registry.terraform.io/ibm-cloud/ibm v1.53.0

### Affected Resource(s)

* ibm_code_engine_secret

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_code_engine_secret" "code_engine_secret_instance" {
  project_id = ibm_code_engine_project.code-engine_project_instance.id
  name = "my-secret"
  format = "ssh_auth"
  data {
    ssh_key = "a"
    known_hosts = "b"
  }
```

### Debug Output

Blocks of type "data" are not expected here. Did you mean to define argument "data"? If so, use the equals sign to assign it a value.

### Expected Behavior

Provides a resource for code_engine_secret.

### Actual Behavior

ERROR: Blocks of type "data" are not expected here. Did you mean to define argument "data"? If so, use the equals sign to assign it a value.

### Steps to Reproduce

1. `terraform plan`

### References

https://registry.terraform.io/providers/IBM-Cloud/ibm/1.53.0/docs/resources/code_engine_secret

**Comment by michael-magrian** [comment]
Hello @escabechada,
can this issue be closed or are you still having issues?

**Comment by hkantare** [comment]
closing the issue
