### ISSUE TITLE
ibm_sm_username_password_secret not retaining interval/unit

### ISSUE THREAD

**Issue by shemau** [IBM-Cloud/terraform-provider-ibm#4611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

terraform version not applicable
IBM Cloud provider 1.51

### Affected Resource(s)

* ibm_sm_username_password_secret
* ibm_sm_<other>_secret may also be impacted

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
resource "ibm_sm_username_password_secret" "username_password_secret" {
  region          = var.region
  instance_id     = var.secrets_manager_guid
  secret_group_id = var.secret_group_id
  name            = var.secret_name
  description     = var.secret_description
  labels          = var.secret_labels
  username        = var.secret_username
  password        = var.secret_payload_password
  rotation {
    auto_rotate = var.secret_user_pass_auto_rotation
    interval    = var.secret_user_pass_auto_rotation_interval
    unit        = var.secret_user_pass_auto_rotation_unit
  }
}

variable "secret_user_pass_auto_rotation" {
  type        = bool
  description = "Whether to configure automatic rotation. Applies only to the `username_password` secret type."
  default     = true
}
variable "secret_user_pass_auto_rotation_unit" {
  type        = string
  description = "Specifies the unit of time for rotation of a username_password secret. Acceptable values are `day` or `month`."
  default     = "day" #tfsec:ignore:general-secrets-no-plaintext-exposure
}
variable "secret_user_pass_auto_rotation_interval" {
  type        = number
  description = "Specifies the rotation interval for the rotation unit."
  default     = 90
}
```

### Expected Behavior

Overriding `secret_user_pass_auto_rotation` to false should apply and leave no pending changes

### Actual Behavior

Overriding `secret_user_pass_auto_rotation` to false should apply leaves an update in place change. No matter how many time apply is run, there is still a pending change.

```
# module.sm_up_artifactory_secret.ibm_sm_username_password_secret.username_password_secret[0] will be updated in-place
~ resource "ibm_sm_username_password_secret" "username_password_secret" {
      id                = "us-south/<instance id>/<secret-id>"
      name              = "my-secret"
      # (19 unchanged attributes hidden)

    ~ rotation {
        ~ interval    = 0 -> 90
        + unit        = "day"
          # (1 unchanged attribute hidden)
      }
  }
```
### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` applies change... but still has changes to apply
3. `terraform apply` applies change... but still has changes to apply

```
module.sm_up_artifactory_secret.ibm_sm_username_password_secret.username_password_secret[0]: Modifying... [id=us-south/<instance id>/<secret-id>]
module.sm_up_artifactory_secret.ibm_sm_username_password_secret.username_password_secret[0]: Modifications complete after 2s [id=us-south/<instance id>/<secret-id>]
```

### Important Factoids

It is possible work to around this by setting interval to 0 and unit to null. This is messy because the behaviour and/or values may change at a later date. The documentation states unit should be days or months, no mention of null.

### References

* #0000

**Comment by shemau** [comment]
This is worse than originally thought. As far as I can tell the following are invalid:

```
rotation {
  auto_rotate = false
  interval = 0
  unit = "day"
}
rotation {
  auto_rotate = false
}
rotation {
  auto_rotate = false
  interval = 0
  unit = "day"
}
rotation {
  auto_rotate = false
  interval = 0
  unit = null
}
rotation {
  auto_rotate = false
  interval = null
  unit = null
}
```
I have observed that some behaviours are different if the secret already exists (with or without rotation). In fact the only way I have found to create a secret without rotation (and that does not show changes on a subsequent apply) is to create a secret and then change the code to either
```
rotation {
  auto_rotate = false
  interval = 0
  unit = null
}
```
or
```
rotation {
  auto_rotate = false
  interval = null
  unit = null
}
```
however these not valid for creating a secret in the first place.

**Comment by IdanAdar** [comment]
The fix is now available in the latest release.
