### ISSUE TITLE
Postgresql point in time recovery to latest point in time recovery time

### ISSUE THREAD

**Issue by shemau** [IBM-Cloud/terraform-provider-ibm#4651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for `latest_point_in_time_recovery_time` (or appropriate) on the postgresql database creation with point in time recovery.
With current versions (13, 14) of the database the UI (via a radio button) and API/CLI (via a special value, a single space, in the time field) permit the new PITR instance to be created at the latest point in time saved.

This feature does not appear to be available (or documented) for the IBM provider for terraform. Specifying a time between the last point in time recovery and the current time results in a failure.

The lack of this feature hinders situations where the aim is to use the most recent recovery time.

### New or Affected Resource(s)

* ibm_database (resource)
* ibm_database_pitr (data source)

### Potential Terraform Configuration

```hcl
# Existing data source remains the same, but potentially returns latest_point_in_time_recovery_time
data "ibm_database_point_in_time_recovery" "database_pitr" {
    deployment_id = data.ibm_database.database.id
}

# Existing resource remains the same, but uses data source, or a special value
resource "ibm_database" "database_pitr" {
  ...
  point_in_time_recovery_time = data.ibm_database_point_in_time_recovery.database_pitr.latest_point_in_time_recovery_time
}
```

### References

* https://registry.terraform.io/providers/IBM-Cloud/ibm/1.54.0/docs/resources/database
* https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-pitr&mhsrc=ibmsearch_a&mhq=postgresql+point+in+time+recovery+time&interface=ui
* https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-pitr&interface=api  says `To restore to the latest available point-in-time use "point_in_time_recovery_time":" ".`

**Comment by alexhemard** [comment]
@shemau As the docs state, an empty string provided for `point_in_time_recovery_time` will use the latest available time but it appears the terraform provider doesn't send this to resource controller during provisioning 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/database/resource_ibm_database.go#L966

I will try to get fixing this issue prioritized as well as clarifying the documentation. Thank you for reporting this issue!

**Comment by Ak-sky** [comment]
With TF, this still does not work

![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/4889052/7ca1ed05-e7bb-4cd3-a33a-992134de1bd9)

**Comment by alexhemard** [comment]
@Ak-sky `latest available time` will be the latest transaction of the backup, so in some instances it will be before the current time.

See the note in the documentation: https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-pitr
