### ISSUE TITLE
ibm_container_addons: unexpected behavior >= v1.53.0

### ISSUE THREAD

**Issue by toddgiguere** [IBM-Cloud/terraform-provider-ibm#4658]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v1.4.6
+ provider registry.terraform.io/ibm-cloud/ibm v1.53.0

### Affected Resource(s)

* ibm_container_addons

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_container_addons" "addons" {
  depends_on = [ibm_container_vpc_worker_pool.pool, ibm_container_vpc_worker_pool.autoscaling_pool]

  cluster           = local.cluster_id
  resource_group_id = var.resource_group_id

  dynamic "addons" {
    for_each = local.addons
    content {
      name    = addons.key
      version = addons.value
    }
  }

  timeouts {
    create = "1h"
  }
}
```

### Expected Behavior
After deployment, with no changes, `terraform plan` should result in:
```
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior
After deployment, with no changes, `terraform plan` result:

```
Terraform will perform the following actions:

  # module.ocp_base.ibm_container_addons.addons will be updated in-place

  ~ resource "ibm_container_addons" "addons" {

        id                = "<redacted>"

      + managed_addons    = (known after apply)

        # (3 unchanged attributes hidden)

        # (2 unchanged blocks hidden)

    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
NOTE: this behavior will continue, even after another `apply`.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`
3. `terraform apply` (will always report 1 update no matter how many repeats)

### References

* Observed in source: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc

**Comment by toddgiguere** [comment]
### ERROR WHEN UPGRADE FROM <= 1.52.0 deployment to >= 1.53.0
Also, when upgrading from an existing deployment that was using provider version 1.52.0 or lower, an error occurs when upgrading to >= 1.53.0.

### Steps to Reproduce
1. `terraform apply` using provider <= 1.52.0
2. `terraform apply` on existing deployment, using provider >= 1.53.0

### Observed behavior after upgrade apply
```
Terraform will perform the following actions:

  # module.ocp_base.ibm_container_addons.addons will be updated in-place
  ~ resource "ibm_container_addons" "addons" {
        id                = "<redacted>"
      + manage_all_addons = true
      + managed_addons    = (known after apply)

        # (2 unchanged attributes hidden)

      + addons {
          + allowed_upgrade_versions = (known after apply)
          + deprecated               = (known after apply)
          + health_state             = (known after apply)
          + health_status            = (known after apply)
          + min_kube_version         = (known after apply)
          + min_ocp_version          = (known after apply)
          + name                     = "vpc-block-csi-driver"
          + options                  = (known after apply)
          + supported_kube_range     = (known after apply)
          + target_version           = (known after apply)
          + version                  = "5.0"
          + vlan_spanning_required   = (known after apply)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

module.ocp_base.ibm_container_addons.addons: Modifying... [id=<redacted>]
│ Error: Request failed with status code: 409, ServerErrorResponse: {"incidentID":"028cd319-568e-4793-8197-c5aae64afa0e","code":"E4d8b","description":"An add-on with the same name already exists. To update your existing add-on to the latest version, see '[http://ibm.biz/addon-update'.","type":"Provisioning"}](http://ibm.biz/addon-update'.%22,%22type%22:%22Provisioning%22%7D)
│
│   with module.ocp_base.ibm_container_addons.addons,
│   on ../../main.tf line 360, in resource "ibm_container_addons" "addons":
│  360: resource "ibm_container_addons" "addons" {
│
```

**Comment by hasan4791** [comment]
Fixed in #4606 
These fixes are available in current beta version
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.55.0-beta0

**Comment by hasan4791** [comment]
In stable release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.55.0

**Comment by ocofaigh** [comment]
Fix is looking good from our side. @toddgiguere do you want to close this out (I can't close the issue)

**Comment by jarrodu** [comment]
The upgrade also fixed the issue for me.

**Comment by toddgiguere** [comment]
v1.55.0 seems to have fixed this issue, I will close this.
