### ISSUE TITLE
return version of the provider with terraform version command

### ISSUE THREAD

**Issue by davetropeano** [IBM-Cloud/terraform-provider-ibm#466]
Currently you can get the provider version by executing it directly with `--help`. For example:

`~/terraform-provider-ibmcloud/terraform-provider-ibm --help`

But `terraform version` should also list the provider version and doesn't:

```
~ $ terraform version
Terraform v0.11.11
+ provider.ibm (unversioned)
+ provider.random v1.1.0
```

We are listed as `(unversioned)`

**Comment by Praveengostu** [comment]
@davetropeano The format for terraform provider is terraform-provider-<NAME>_vX.Y.Z, and Terraform uses the name to understand the name and version of a particular provider binary. In your case the binary name should have excluded the version that's the reason it prints unversioned. We package the provider with version included in the name of binary for ex:terraform-provider-ibm_v0.12.0. And when e execute terraform init
```To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.ibm: version = "~> 0.12"

Terraform has been successfully initialized!```

**Comment by kskewes** [comment]
If the `terraform-provider-ibm_v0.17.1` binary is moved into `~/.terraform.d/plugins/` it can't be found.
```
$ terraform init
                                                                                                                                                                 
Initializing the backend...   

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
                                
Provider "ibm" not available for installation.
                                            
A provider named "ibm" could not be found in the official repository.
```
```
# Provider configuration
provider "ibm" {
  version = "0.17.1"
}
```

Removing the plugin `version` constraint and renaming the binary to `terraform-provider-ibm` works but then there is no version pinning as the OP mentioned.


@Praveengostu - could you please try going through both the `build` and `install` instructions: https://github.com/IBM-Cloud/terraform-provider-ibm#building-the-provider
Then try pinning to a specific plugin version i `provider ibm {}`.
I was unsuccessful.

**Comment by hkantare** [comment]
From terraform version 13 and higher the issue has been fixed 
```
harinireddy@Harinis-MacBook-Pro ds % terraform13 version                
Terraform v0.13.5
+ provider registry.terraform.io/ibm-cloud/ibm v1.37.0

Your version of Terraform is out of date! The latest version
is 1.0.11. You can update by downloading from https://www.terraform.io/downloads.html
harinireddy@Harinis-MacBook-Pro ds % 
```
closing the issue
