### ISSUE TITLE
Provider is not throwing error if KMS details are provided with standard plan for event streams instance

### ISSUE THREAD

**Issue by maheshwarishikha** [IBM-Cloud/terraform-provider-ibm#4662]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform v1.5.1

### Affected Resource(s)

* ibm_resource_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_resource_instance" "es_instance" {
  name              = "terraform-integration-1"
  service           = "messagehub"
  plan              = "standard"
  location          = "us-south"
  resource_group_id = <resource_group_id>
  tags              = []
  timeouts {
    create = "15m"
    update = "15m"
    delete = "15m"
  }

  parameters = {
    service-endpoints = "public"
    throughput        = "150"
    storage_size      = "2048"
    key_protect_key   = <kms_key_crn>
  }
}
```

### Expected Behavior

It should give an error as KMS key encryption is not supported for standard plan.

### Actual Behavior

It creates the service instance using standard plan without KMS encryption.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kccox** [comment]
@maheshwarishikha The parameter for the key protect key is `kms_key_crn`, not `key_protect_key`.

When I try a standard plan provision with the `kms_key_crn`, terraform gives an error message:
```
 Error: [ERROR] Error when creating resource instance: Please contact the Service Provider for this error. [400, Bad Request] Set KMS root key CRN on Standard or Lite plan is not supported. with resp code: {
....
     "Result": {
         "details": "{\"description\":\"Set KMS root key CRN on Standard or Lite plan is not supported.\",\"error\":\"Bad Request\",\"incident_id\":\"782d5cd5-2a14-4b84-87ab-0eec7afbf32a\"}\n",
         "error_code": "RC-ServiceBrokerErrorResponse",
         "message": "Please contact the Service Provider for this error. [400, Bad Request] Set KMS root key CRN on Standard or Lite plan is not supported.",
         "status_code": 422,
         "transaction_id": "7374-ddaf2755f4e75231"
     },
```

**Comment by maheshwarishikha** [comment]
Thanks @kccox , `key_protect_key` to `kms_key_crn` is changed in our code almost a year back. And we had a validation in our code to check `kms_key_crn` if `standard` plan is set so we did not get a chance to verify this separately.

Today we tested that part, and its working for us. Thanks. 
Closing this issue.

**Comment by ocofaigh** [comment]
@maheshwarishikha @kccox I thought the issue was that if the user accidentally uses `key_protect_key` instead of `kms_key_crn` (like we originally did), the deployment still proceeds with provisioning an instance without any error. And the instance was not encrypted. I think for that use case, it should fail saying `key_protect_key` is not a valid paremeter instead of proceeding to create the instance.

**Comment by maheshwarishikha** [comment]
@kccox One question for you is - why dont we have a check to verify if user has provided valid params in `parameter {}`
That will be helpful to catch such errors much sooner.

Reopening this issue if it can be taken care, that would be nice.

**Comment by kccox** [comment]
Hi, @maheshwarishikha, @ocofaigh: I have created an issue to check the parameters for unknown keys and report errors. This is currently unplanned and not high priority.

**Comment by ocofaigh** [comment]
@kccox Thanks, I agree its not high priority but a nice to have. Where is the issue you created? Is it in an internal repo?
@maheshwarishikha if its tracked elsewhere, lets maybe close this issue then.

**Comment by kccox** [comment]
Yes, the issue is in an internal repo.

**Comment by maheshwarishikha** [comment]
ok, thanks.
Would be good if you just let us know once it is fixed. For time being, we can close this issue. Thanks for your help.
