### ISSUE TITLE
Event Stream services endpoints and KMS are not setting correctly.

### ISSUE THREAD

**Issue by Ak-sky** [IBM-Cloud/terraform-provider-ibm#4717]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
* Terraform v1.5.1
* Terraform IBM Provider Version v1.54.0

### Affected Resource(s)

* ibm_resource_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_resource_instance" "es_instance" {
  name              = var.es_name
  service           = "messagehub"
  plan              = var.plan
  location          = var.region
  resource_group_id = var.resource_group_id
  tags              = var.tags
  timeouts {
    create = var.create_timeout
    update = var.update_timeout
    delete = var.delete_timeout
  }

  parameters = {
    service_endpoints = var.service_endpoints
    throughput        = var.throughput
    storage_size      = var.storage_size
    key_protect_key   = var.kms_key_crn
  }
}
```

### Description

- When using service-endpoints = "private" (notice hyphen) as per [provider doc](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/resource_instance) under parameters in TF code above, ES instance is getting provisioned with private endpoint but SCC scan fails (refer issue [here](https://github.ibm.com/oneibmcloud/CD-CRA/issues/1820)) as it is trying to scan service_endpoints (notice underscore). But with service_endpoints, ES instance gets provisioned with public  endpoint (which is not expected behaviour) and SCC scan passes.

- Also we are using HPCS for encryption and setting the required kms_instance/key_protect_key and kms_key but In UI I am still seeing storage encryption as Automatic encryption and not HPCS/User-selected key

- NOTE: we are using "enterprise-3nodes-2tb" plan to provision ES instance.

### Steps to Reproduce

1. `terraform apply` on this ES FS cloud [example](https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/tree/main/examples/fscloud).

### References

* #0000

**Comment by ocofaigh** [comment]
Is `key_protect_key` a valid parameter for Event Strams can someone confirm? No mention of it here -> https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-event-streams however KMS encryption is supported by the service according to https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-managing_encryption

**Comment by Ak-sky** [comment]
> Is `key_protect_key` a valid parameter for Event Strams can someone confirm? No mention of it here -> https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-event-streams however KMS encryption is supported by the service according to https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-managing_encryption

Found the KMS parameter is `kms_key_crn` [here](https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-managing_encryption).

**Comment by Ak-sky** [comment]
> @Ak-sky Can this be closed now since you were using the wrong parameter?

Another issue I mentioned in this is with service-endpoints, which is still there.

**Comment by ocofaigh** [comment]
@Ak-sky Isn't that an issue on the SCC / CRA side? The provider doc tells us to use `service-endpoints = "private"` and this deploys a private only instance. So I don't see any issue with provider? Or have I missed something?

**Comment by Ak-sky** [comment]
Yes @ocofaigh, you are right! I saw David's comment on updating the rule, closing this.
