### ISSUE TITLE
ibm_pi_dhcps example uses the wrong ibm_pi_dhcp in the example

### ISSUE THREAD

**Issue by prb112** [IBM-Cloud/terraform-provider-ibm#4725]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_pi_dhcps

### Description

ibm_pi_dhcps example uses the wrong ibm_pi_dhcp in the example

### References

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/pi_dhcps

**Comment by michaelkad** [comment]
@prb112  I have added a PR to address this.

**Comment by prb112** [comment]
Thank you
