### ISSUE TITLE
Documentation is wrong about the ibm_database plan

### ISSUE THREAD

**Issue by lsabalo** [IBM-Cloud/terraform-provider-ibm#4740]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_database

### Description

Documentation for the plan says:

>The name of the service plan that you choose for your instance. All databases use standard. enterprise is supported only for cassandra (databases-for-cassandra) and mongodb(databases-for-mongodb)

This is not true since I had to change `plan` to `enterprise` in order to deploy the preferred version of **Elasticsearch**.

### References

* #0000

**Comment by omaraibrahim** [comment]
Thanks @lsabalo! You're correct, we'll take care of this issue ASAP!

**Comment by omaraibrahim** [comment]
The documentation has been updated in this [PR](https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4742) and the docs should be fixed in the next release 😄
