### ISSUE TITLE
Schematics tags applied as access tags when using ibm_resource_tag

### ISSUE THREAD

**Issue by MatthewLemmond** [IBM-Cloud/terraform-provider-ibm#4744]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

- terraform 1.5.4
- ibm-cloud/ibm v1.55.0

### Affected Resource(s)

* ibm_resource_tag

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
resource "ibm_resource_tag" "tag" {
  resource_id  = <resource_instance_id>
  tag_type    = "access"
  tags        = ["access-tag:valid-tag"]
}
```

### Debug Output

```
 2023/08/04 08:58:13 Terraform apply |     "Result": {
 2023/08/04 08:58:13 Terraform apply |         "errors": [
 2023/08/04 08:58:13 Terraform apply |             {
 2023/08/04 08:58:13 Terraform apply |                 "code": "GST918E",
 2023/08/04 08:58:13 Terraform apply |                 "description": "",
 2023/08/04 08:58:13 Terraform apply |                 "field": "",
 2023/08/04 08:58:13 Terraform apply |                 "httpCode": 404,
 2023/08/04 08:58:13 Terraform apply |                 "level": "error",
 2023/08/04 08:58:13 Terraform apply |                 "message": "The tag with name Schematics:us-south.workspace.globalcatalog-collection.<workspace_id> does not exist",
 2023/08/04 08:58:13 Terraform apply |                 "more_info": "",
 2023/08/04 08:58:13 Terraform apply |                 "response": "TAG_DOC_NOT_FOUND",
 2023/08/04 08:58:13 Terraform apply |                 "subCode": 0
 2023/08/04 08:58:13 Terraform apply |             }
 2023/08/04 08:58:13 Terraform apply |         ]
 2023/08/04 08:58:13 Terraform apply |     },
 2023/08/04 08:58:13 Terraform apply |     "RawResult": null
```
### Expected Behavior

Resources should be tagged using any existing access tags passed into the block when using schematics

### Actual Behavior

Tags that are automatically applied using schematics are picked up as access tags and passed into the call, this fails due to the tags not being access tags in the account.

This appears to be caused by [this section](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/c3d6f5946fb2a52dac613776726979ab19853eaf/ibm/service/globaltagging/resource_ibm_resource_tag.go#L145) in the code which automatically adds the environment tags.

### Steps to Reproduce

1. use terraform to tag a resource in an account
2. terraform works using the CLI
3. attempt in a schematics workspace

### References

* #0000

**Comment by hkantare** [comment]
closing issue based on above comments
