### ISSUE TITLE
Multiple aliased IBM providers targeting different regions don't work correctly

### ISSUE THREAD

**Issue by ashishth09** [IBM-Cloud/terraform-provider-ibm#475]
provider "ibm" {
  region = "us-south"
}

provider "ibm" {
  alias  = "london"
  region = "eu-gb"
}

data "ibm_space" "space" {
  space = "${var.space}"
  org   = "${var.org}"
}

data "ibm_space" "redis_space" {
  provider = "ibm.london"
  space    = "${var.redis_space}"
  org      = "${var.redis_org}"
}

Looks like since region is globally managed https://github.com/IBM-Cloud/terraform-provider-ibm/blob/f59fc32a8b76e72e78c3183e1fb04d2c2375d7e8/ibm/config.go#L44, whichever runs later overrides the former.

**Comment by kavya498** [comment]
closing this issue..
latest providers works as expected with multiple aliases.. thanks
