### ISSUE TITLE
Resource Name length is not checked during terraform plan

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#476]
Hi there,

### Terraform Version
C:\IBM\IMFactoryServices\ImFactory-Terraform\css\test>terraform -v
Terraform v0.11.8
+ provider.ibm v0.14.0

### Affected Resource(s)
- ibm_network_vlan
- not sure if it occurs by other resources  
### Terraform Configuration Files
resource "ibm_network_vlan" "CSS_Private_Test_Fra02" {
  name       = "CSS_Private_Test_Fra02"
  datacenter = "fra02"
  type       = "PRIVATE"
}

### Expected Behavior
The parameter name of the resource is to long (allowed are just 20 character) if I run terraform apply. 

The expected behavior will be that if I run terraform plan the provider will give me a hint that the name is to long.

### Actual Behavior
If I run terraform plan, everything is ok. But if I run terraform apply this failure occurred:

_ibm_network_vlan.CSS_Private_Test_Fra02: 1 error(s) occurred:
* ibm_network_vlan.CSS_Private_Test_Fra02: Error updating vlan: SoftLayer_Exception_InvalidDataLength: Length provided for 'name' is too long.  Provided with length of '22', maximum length is '20'. (HTTP 500)_

If this error occurred the vlan was order but without a name.. If I run it again with just 20 character name, the terraform process workes fine but it orders another vlan. **This leads to multiple costs**

I am not sure if this behavior occurs just by ordering vlans but if it occurs by ordering cost intensive bare metal server this can lead to a financial disaster.

**Comment by hkantare** [comment]
Fix is available as part of v0.16.1 and v0.16.1 releases

**Comment by hkantare** [comment]
closing the issue
