### ISSUE TITLE
[v0.4.0, v0.5.0] bare metal creation (destroyed bare metal resource remains several hours in portal, recreate the resource got issue)

### ISSUE THREAD

**Issue by lospringliu** [IBM-Cloud/terraform-provider-ibm#48]
step 1: terraform apply, cost 2 hours

- ibm_compute_bare_metal.masters: Still creating... (2h45m52s elapsed)
- ibm_compute_bare_metal.masters: Still creating... (2h46m2s elapsed)
- ibm_compute_bare_metal.masters: Still creating... (2h46m12s elapsed)
- ibm_compute_bare_metal.masters: Creation complete after 2h46m20s (**ID: 1213785**)
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

step 2: terraform destroy, cost 20 seconds

- ibm_compute_bare_metal.masters: Destroying... (ID: 1213785)
- ibm_compute_bare_metal.masters: Still destroying... (**ID: 1213785**, 10s elapsed)
- ibm_compute_bare_metal.masters: Destruction complete after 13s

Here is what shows in blue mix portal, bare metal is no longer charging

|server full name| resource type |data center|floating ip|internal ip|date|notes|
|----|----|----|----|----|----|----|
|master0.domain.com|Bare Metal Server|Washington 4|169.47.131.213|10.183.122.202|2017-10-06 | |  
 
| xcliu1.xcliu.com | Virtual Server | Toronto 1 | 158.85.106.44 | 10.115.181.66 | 2017-08-31 |   | Actions

step 3: terraform apply, cost 20 seconds 

- ibm_compute_bare_metal.masters: Still creating... (10s elapsed)
- ibm_compute_bare_metal.masters: Still creating... (20s elapsed)
- ibm_compute_bare_metal.masters: Creation complete after 21s (**ID: 1213785**)

**THE ISSUE: if I destroy my bare metal, and create it again even after several hours, the provider still returns to reuse the destroyed bare metal. But after one or two hours, a different bare metal will appear but with information loss like user metadata**

**Comment by lospringliu** [comment]
it would be more consistent if bare metal behaves like vm instance, we can create any number of vm instances with the same hostname and domain name without interfering each other.

**Comment by lospringliu** [comment]
**correction**
on the actual test, using v0.5.0, new later appeared bare metal is good anyway, no user_metadata lost

I think the same magic happen for any existing bare metal, if I apply to create a bare metal resource with the same hostname and domain name, terraform returns unreasonably fast (20-30 seconds) but actually api request were issued before this return and a new resource will appear after some time.

**Comment by ashishth09** [comment]
closed in https://github.com/IBM-Cloud/terraform-provider-ibm/pull/123
