### ISSUE TITLE
Deleted COS Bucket name reuse info missing in provider registry documentation.

### ISSUE THREAD

**Issue by umarali-nagoor** [IBM-Cloud/terraform-provider-ibm#4819]
Its been observed that many customers query about time to wait to re-use the cos bucket name after its deletion.

one of the sample customer query 

-----------------------------------------

Case Short Description:
SAP HANA Backup COS Script Error: Bucket Name already exists, even after resource deletion

Case Description:
Please provide the following information to assist with resolving your case.
We will use the information below to begin investigating your issue/question:

Trying to deploy the scripts associated with COS and keep running into an error where it says the bucket already exists - due to an earlier Schematics plan failure. I have since tried to delete the resources associated with the workspace, double checking in my Resource List that the bucket is deleted, but the error keeps persisting.

Error Message:

2023/09/19 15:16:56 Terraform apply | Error: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
2023/09/19 15:16:56 Terraform apply | status code: 409, request id: 2a864e0a-17ef-4882-a680-a7e9d3b71d5e, host id:
2023/09/19 15:16:56 Terraform apply |
2023/09/19 15:16:56 Terraform apply | with module.cos.ibm_cos_bucket.cos_bucket,
2023/09/19 15:16:56 Terraform apply | on modules/cos/cos_operations.tf line 21, in resource "ibm_cos_bucket" "cos_bucket":
2023/09/19 15:16:56 Terraform apply | 21: resource "ibm_cos_bucket" "cos_bucket" {
2023/09/19 15:16:56 Terraform apply |
2023/09/19 15:16:57 �[1m�[31mTerraform APPLY error: Terraform APPLY errorexit status 1�[39m�[0m
2023/09/19 15:16:57 �[1m�[31mCould not execute job: Error : Terraform APPLY errorexit status 1�[39m�[0m
-------------------------------------------

We have pointed out the customer to refer below doc 

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-faq#faq-reuse-name

Snippet from doc bucket name re-use

"A bucket name can be reused as soon as 15 minutes after the contents of the bucket have been deleted and the bucket has been deleted. Then, the objects and bucket are irrevocably deleted and can not be restored.

If you do not first empty and then delete the bucket, and instead [delete or schedule the Object Storage service instance for deletion](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-provision#deleting-a-service-instance), the bucket names will be held in reserve for a [default period of seven (7) days until the account reclamation process](https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud_commands_resource#ibmcloud_resource_reclamations) is completed. Until the reclamation process is complete, it is possible to restore the instance, along with the buckets and objects. After reclamation is complete, all buckets and objects will be irrevocably deleted and can not be restored, although the bucket names will be made available for new buckets to reuse."

It will be helpful to the users to include the COS bucket name re-use info both in terraform provider registry documentation & README. So that user will be aware of how to re-use bucket name.

**Comment by IBM-diksha** [comment]
The PR for this issue has been merged into the beta release for this month.
Version - v1.68.0-beta

**Comment by IBM-diksha** [comment]
Closing the ticket  as the latest release has the documentation including the reuse information of the bucket after deletion.
Version - v1.68.0
