### ISSUE TITLE
Feature add: San storage Target Address

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#482]
Hi IBM- Provider - Terraform Team,
can you enhance the ibm_storage_block with an attribute TargetAddress? 
It is not available in the current state. (just one Hostname).

Is see that the TargetAddress provides me two IP Addresses for my SAN (This is important for HA requirements). 

I just can see this Attribute with help of the SoftLayer Webconsole. The CLI Tool (ibm sl block volume-detail) did also not provide me this information.

**Comment by hkantare** [comment]
Fix is available in latest releases (v0.16.0, v0.16.1..)

**Comment by hkantare** [comment]
Fixed and availble in latest releases
