### ISSUE TITLE
Feature Request : CDN crud operations

### ISSUE THREAD

**Issue by JunaidKhan001** [IBM-Cloud/terraform-provider-ibm#483]
Hi there,

I have added a resource for Content deliver network which performs CRUD operations.
I have added test cases and the documentation as well.
The resource is verified multiple times for different parameters.
Adding the Link for PR;  https://github.com/IBM-Cloud/terraform-provider-ibm/pull/479

**Comment by hkantare** [comment]
closing the feature request.Merged the PR
