### ISSUE TITLE
How can we upgrade my IBM managed database version using Terraform?

### ISSUE THREAD

**Issue by snippzzy** [IBM-Cloud/terraform-provider-ibm#4832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Question

We currently provision our databases (MongoDB, PostgreSQL and Redis) using Terraform, but whenever we need to upgrade them, we have to manually do it using the CLI. We want to be able to automate this process using Terraform just as we can automate our cluster patching, upgrading, provisioning, etc, however there is no documentation focused on using Terraform IBM Provider,  as the only documentation provided are focused on CLI and UI.

### Terraform CLI and Terraform IBM Provider Version

IBMCloud provider version: 1.49.1
Terraform version: 1.3.7

### New or Affected Resource(s) or Datasource(s)

* ibm_database_MongoDB
* ibm_database_PostgreSQL
* ibm_database_Redis

### Potential Terraform Configuration

This is code is currently used to provision our PostgreSQL for version 12

```hcl
resource "ibm_database" "postgresql_db_instance" {
  name = "${var.project_name}_postgresql"
  plan = "standard"
  location = "eu-gb"
  service = "databases-for-postgresql"
  version = 12
  resource_group_id = data.ibm_resource_group.resource_group.id
  # members_memory_allocation_mb = 2048
  # members_disk_allocation_mb = 10240
  # members_cpu_allocation_count = 6
  group {
    group_id = "member"

    memory { 
      allocation_mb = 2048
    }

    disk { 
      allocation_mb = 10240
    }

    cpu {
      allocation_count = 6
    }
  }

  service_endpoints = "private"
  key_protect_key = data.ibm_kms_key.postgresql_rootkey.keys.0.crn
  timeouts {
    create = "60m"
    update = "60m"
    delete = "60m"
  }
  lifecycle {
    prevent_destroy = true
  }
}

resource "ibm_resource_key" "postgresql_db_secret" {
    name = "${var.project_name}_postgresql_key"
    role = "Administrator"
    resource_instance_id = ibm_database.postgresql_db_instance.id
}

```

### References

* How to upgrade your version PostgreSQL
https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-upgrading&interface=ui

* The document attached below gives detailed information about Redis upgrade. 
https://cloud.ibm.com/docs/databases-for-redis?topic=databases-for-redis-upgrading

* Please find the document attached below for more information regarding the  MongoDB upgrade:
https://cloud.ibm.com/docs/databases-for-mongodb?topic=databases-for-mongodb-upgrading&interface=ui

**Comment by omaraibrahim** [comment]
Hi @snippzzy thank you for reaching out!

In-place upgrades for major versions is not supported for `terraform`. If you would like to upgrade then you can restore a backup from old version to the new version.

Thanks and have a wonderful day 😄

**Comment by snippzzy** [comment]
Thanks for the information, do you recommend that since Terraform cannot support major version upgrades, we should therefore use only the CLI or UI to provision our IBM managed databases to prevent drift in our Terraform state-file?

**Comment by omaraibrahim** [comment]
@snippzzy Hope you had a wonderful weekend 😄 

That would be one way to prevent drift yes. I don't know the details of your system, so I won't be able to tell you what is best for your instances. You can always restore from an old version to a new version via terraform as well.

**Comment by snippzzy** [comment]
@omaraibrahim can you provide more information or send a documentation that explains the process of restoring from an old version to a new version via terraform? 

Thanks

**Comment by omaraibrahim** [comment]
@snippzzy Thanks for reaching out! In order to restore to a new version all you need to do is set your backup_id as mentioned [here](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#backup_id). Then set your desired version in the version attribute as seen [here](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#version).

Thanks!

**Comment by snippzzy** [comment]
Thanks @omaraibrahim

**Comment by uday644** [comment]
@omaraibrahim If we do database upgrade by creating a new instance from back up, how to do manage it in Terraform afterwards.

A normal DB management cycle in our project looks like : DB Creation -> Daily / On-Demand backup creation -> Restore from backup (when upgrade required or retore from backup required) -> Delete the old instance

From Terraform point of view
1. DB Creation --> Can be done using the ibm_database resource creation
2. Daily / On-Demand backup creation --> Configured in DB config when creating the DB
3. Restore from backup --> Can be done by creating a new ibm_database resource by passing the backup_id as you mentioned in earlier comment
4. Delete old instance --> Can we do this by removing the ibm_database resource script created as part of 1st step, which will destroy the old instance?

And if we have a backup retention policy of 10 backup's (for example), after 10 backup's the backup_id passed in 3rd step will be invalid, how re-running the terraform script after 10 automatic backups satisfies the idempotency of the Terraform.

What is your recommend way to manage the DB life cycle (upgrades, restoring from backups) using Terraform especially for IBM Cloud?

**Comment by uday644** [comment]
@omaraibrahim Could you help us with this issue :)

**Comment by omaraibrahim** [comment]
@uday644 Thank you for reaching out 😄

This is an specific engineering issue that I cannot advise you on. I'd recommend going through the [docs](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database).

Thanks!
