### ISSUE TITLE
private only container cluster creation hanging

### ISSUE THREAD

**Issue by n-marton** [IBM-Cloud/terraform-provider-ibm#484]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v0.11.11

### Affected Resource(s)
- ibm_container_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "ibm_container_cluster" "cluster" {
  name            = "testing"
  datacenter      = "par01"
  disk_encryption = true
  machine_type    = "u2c.2x4"
  hardware        = "shared"
  private_vlan_id = "someid"

  default_pool_size = "1"
}
```

### Expected Behavior
A cluster with only private networking should be created without error.

### Actual Behavior
A cluster is created but the terraform hangs and doesn't exits.

### Steps to Reproduce
1. `terraform apply`

### Cause
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/v0.14.1/ibm/resource_ibm_container_cluster.go#L901 

publicSubnetAdded variable is true even if I create a private network only cluster with no_subnet = false (I want a private subnet attached to my cluster automatically), so WaitForSubnetAvailable function is waiting for an ingress secret which doesn't created if there is no public alb.

### Suggestion
publicSubnetAdded should be false it no_subnet is false and there is no publicVlanID

**Comment by Praveengostu** [comment]
The issue is fixed and will be available in next release

**Comment by hkantare** [comment]
closing the issue
