### ISSUE TITLE
High Priority: ibm_pi_instance fails to create instance.

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#4905]
Hello team,
Since 18 hours all DCs are failing to create an instance.

Please treat this as high priority and fix it in PROD . it has affected all DCs

i am getting the below error for instance creation

`module.sap_system.module.pi_hana_instance.module.pi_instance.ibm_pi_instance.instance: Still creating... [12m0s elapsed]
1344
module.sap_system.module.pi_netweaver_instance[0].module.pi_instance.ibm_pi_instance.instance: Still creating... [12m10s elapsed]
1345
module.sap_system.module.pi_hana_instance.module.pi_instance.ibm_pi_instance.instance: Still creating... [12m10s elapsed]
1346
╷
1347
│ Error: failed to Update PVM Instance 476f617a-8b8f-4da2-8ae2-52acbb00999f :[PUT /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}][400] pcloudPvminstancesPutBadRequest  &{Code:0 Description:cloudInitialisation is not supported in this environment Error:bad request Message:}
1348
│ 
1349
│   with module.sap_system.module.pi_hana_instance.module.pi_instance.ibm_pi_instance.instance,
1350
│   on .terraform/modules/sap_system.pi_hana_instance/modules/pi-instance/main.tf line 9, in resource "ibm_pi_instance" "instance":
1351
│    9: resource "ibm_pi_instance" "instance" {
1352
│`

**Comment by surajsbharadwaj** [comment]
jira has been opened internally too : https://jsw.ibm.com/browse/POWERIAAS-10858

**Comment by hkantare** [comment]
@renier @rachari 
Can some from powervm team look into this

**Comment by surajsbharadwaj** [comment]
Few information from Rene:
1.It might be a create in Terraform but under the covers a PUT operation could be made to the VM somewhere during that create
2. I would guess a hot fix to address that new check in the code.
3. I am not that familiar with that new code but it looks like some code is placed in the wrong place or has wrong logic

**Comment by surajsbharadwaj** [comment]
Got some information from Laurent Dufour:


"Description:cloudInitialisation is not supported in this environment Error:bad request Message" Sounds that cloudInitialisation option is passed to the PVM modify command. That's surprising since this option is flagged as internal. I'll double check the code to see if this message could be raised unexpectedly.
--

**Comment by michaelkad** [comment]
We are pushing a fix for this internally — This not terraform related issue but power related.
It should be resolved soon. I will update once it is pushed.

**Comment by michaelkad** [comment]
@surajsbharadwaj The fix was pushed. Could you please double check?

**Comment by surajsbharadwaj** [comment]
I can confirm it is working. Thank you. Closing this issue
