### ISSUE TITLE
ibm_pi_network documentation scrape

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#4914]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_pi_network

### Description
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_network

Why is this IBM i?  Doesn't this apply to all Power OSes?

![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/6932057/8fa39d11-5702-4437-96ee-807f892b99a1)

Make a careful pass over all of the docs.

### References

* #0000

**Comment by ismirlia** [comment]
This issue should be fixed by #4969 so I'm closing. Please let me know if there are any further documentation issue that needs to be addressed.
