### ISSUE TITLE
Allow filtering of VPC instance images 

### ISSUE THREAD

**Issue by greyhoundforty** [IBM-Cloud/terraform-provider-ibm#4930]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the ability to `filter` on data sources for VPC images. Right now when you pull all images in a region there is no way to filter beyond some basics like `visibility` and `status`. For automation systems it would be handy to be able to additionally filter on the underlying OS. 

**Digital Ocean**
Here is an example from DO. The `regions` is not relevant here as we provider per region images, but being able to filter on a distro the ideal:

```hcl
data "digitalocean_images" "available" {
  filter {
    key    = "distribution"
    values = ["Ubuntu"]
  }
  filter {
    key    = "regions"
    values = ["nyc3"]
  }
  sort {
    key       = "created"
    direction = "desc"
  }
}
```

### New or Affected Resource(s)

Data source [ibm_is_images](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_images#example-usage)

### Potential Terraform Configuration

```hcl
data "ibm_is_images" "images" {
  visibility = "public"
  status = "available"
  filter {
    key    = "vendor"
    values = ["Canonical"]
 }
```

At the moment this would not work as we do not provide the `operating_system.vendor` key in the Terraform response to the data source. This is what is returned for each image currently:

```
  "access_tags" = toset([])
  "architecture" = "amd64"
  "catalog_offering" = tolist([
    {
      "managed" = false
      "version" = tolist([])
    },
  ])
  "checksum" = "ff9eae27ec75619ce01edcc04389a51e83bb8cb47d2250003bc8cb3de9e91196"
  "crn" = "crn:v1:bluemix:public:is:us-south:a/811f8abfbd32425597dc7ba40da98fa6::image:r006-aa422143-2059-4472-88e0-a15fa8fe5346"
  "encryption" = "none"
  "encryption_key" = ""
  "id" = "r006-aa422143-2059-4472-88e0-a15fa8fe5346"
  "name" = "ibm-redhat-9-2-amd64-sap-hana-1"
  "os" = "red-9-amd64-sap-hana"
  "source_volume" = ""
  "status" = "available"
  "visibility" = "public"
}
```
The response does not include the Vendor, but those keys are in the API as shown in the CLI:

```
ibmcloud is images --visibility public --output json | jq -r '.[] | select(.status=="available") | select(.operating_system.architecture=="amd64") | .operating_system.vendor' | sort | uniq -c | sort -n
   1 Rocky Linux
   2 Canonical
   2 Fedora
   2 VMware
   3 CentOS
   3 Debian
   6 Microsoft
  15 SUSE
  17 Red Hat
```

### References

* #0000

**Comment by deepaksibm** [comment]
@greyhoundforty These attributes are now available in the recent release. 
Please check and confirm if this is good to close
Thanks

**Comment by deepaksibm** [comment]
@greyhoundforty Please confirm if this is good to close. thanks.

**Comment by deepaksibm** [comment]
@greyhoundforty Closing this issue as the missing attributes are added. 

@astha-jain @sumitkumartiwari Please close this issue.

**Comment by greyhoundforty** [comment]
@deepaksibm - sorry for the delay, somehow I missed this notification 

I don't see a filter option listed for https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_images. Can you confirm this was implemented? I see a new `user_data` section but nothing related to the ability to filter by OS family 

```shell
provider "ibm" {
  region = "us-south"
}

data "ibm_is_images" "images" {
  visibility = "public"
  status     = "available"
  filter {
    key    = "vendor"
    values = ["Canonical"]
  }
}

output "images" { 
   value = data.ibm_is_images.images
}
```

**Attempt to validate**
```
% tfv 
Initializing the backend...

Initializing provider plugins...
- Finding ibm-cloud/ibm versions matching "1.68.1"...
- Using previously-installed ibm-cloud/ibm v1.68.1

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Unsupported block type
│
│   on main.tf line 9, in data "ibm_is_images" "images":
│    9:   filter {
│
│ Blocks of type "filter" are not expected here.
╵
```

**Comment by greyhoundforty** [comment]
I was able to achieve the desired result by using `locals`, but was hoping the filter would be at the data source level. 

```shell
locals {
  filtered_images = [
    for image in data.ibm_is_images.images.images :
     image if contains([for os in image.operating_system : os.vendor], "Canonical")
  ]
}


data "ibm_is_images" "images" {
  visibility = "public"
  status     = "available"
  user_data_format = ["cloud_init"]
}
```
