### ISSUE TITLE
ibm_cis_domain_settings - tf apply reduces the default min_tls_version to 1.1

### ISSUE THREAD

**Issue by iamar7** [IBM-Cloud/terraform-provider-ibm#4937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
Terraform v1.5.5

### Affected Resource(s)

* ibm_cis_domain_settings

### Terraform Configuration Files

Enabling/disabling `web application firewall(WAF)` using the ibm_cis_domain_settings resource block in the IBM CIS instance as shown below: 

```hcl
 resource "ibm_cis_domain_settings" "domain_settings" {
  cis_id    = var.cis_instance_id
  domain_id = var.domain_id
  waf       = var.waf
}
```
On `terraform apply` it enables/disables the WAF successfully but it also modifies the default `min_tls_version`.

Slack conversation for reference : https://ibm-cloudplatform.slack.com/archives/C8XKQ9FPB/p1700219365028279

### Expected Behavior
`terraform apply` should just enable/disable the WAF and does not modify the `min_tls_version`.

### Actual Behavior
`terraform apply` enables/disables the WAF but also modifies `min_tls_version`.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by arpit-srivastava-ibm** [comment]
@iamar7 
I looked into the `ibm_cis_domain_settings` resource and it seems that there is a discrepancy while handling the `min_tls_version` field. 
I will be pushing the fix today. The expected date of next release should be by end of this month. I will update the team as I have more insights on the release.

**Comment by iamar7** [comment]
After doing terraform apply on this [example](https://github.com/terraform-ibm-modules/terraform-ibm-cis/blob/main/examples/complete/main.tf) as per the changes in this [provider issue](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4937) the `min_tls_version`  was getting set to `1.2` but if we do `terraform plan`  then it tries to change the `min_tls_version` to `null` as shown in the image below which results in test failure.

<img width="1225" alt="Screenshot 2024-01-30 at 3 16 16 PM" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/20831630/2cdd730b-aaac-4539-8b61-04ff7d9d0963">

**Comment by iamar7** [comment]
> After doing terraform apply on this [example](https://github.com/terraform-ibm-modules/terraform-ibm-cis/blob/main/examples/complete/main.tf) as per the changes in this [provider issue](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4937) the `min_tls_version` was getting set to `1.2` but if we do `terraform plan` then it tries to change the `min_tls_version` to `null` as shown in the image below which results in test failure.
> 
> <img alt="Screenshot 2024-01-30 at 3 16 16 PM" width="1225" src="https://private-user-images.githubusercontent.com/20831630/301763095-2cdd730b-aaac-4539-8b61-04ff7d9d0963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTY0MjksIm5iZiI6MTcxMTAxNjEyOSwicGF0aCI6Ii8yMDgzMTYzMC8zMDE3NjMwOTUtMmNkZDczMGItYWFhYy00NTM5LThiNjEtMDRmZjdkOWQwOTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEwMTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZTZkZmI1OGJiODk3ZTE2NzU2NTQ1ZjM4YmMxMjgzYTQwZWE3NzBlZjE1MzEwMWIwNTY1ZDc0MDdhMmE0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WPwz6-8rGo-ajSVVzy25c7zEIrjUlQH4jy2fq7-3Eyc">

The solution for this issue was implemented in this PR ~> https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5136 so closing this issue.
