### ISSUE TITLE
CRITICAL : Unable to provision FREE ibm_container_cluster instance

### ISSUE THREAD

**Issue by siddharthoak** [IBM-Cloud/terraform-provider-ibm#494]
Hi there,

### Terraform Version
Terraform v0.11.7
IBM Cloud Provider version 0.14.1  

### Affected Resource(s)
- ibm_container_cluster

### Terraform Configuration Files
```
provider "ibm" {
bluemix_api_key= "TESTAPIKEY"
softlayer_username = "TESTUSER"
}
resource "ibm_container_cluster" "testacc_cluster" {
 name = "myfreeluster"
} 
```

### Debug Output
terraform apply --auto-approve -var direction=ingress
ibm_container_cluster.testacc_cluster: Creating...
  albs.#:             "" => "<computed>"
  billing:            "" => "hourly"
  datacenter:         "" => "sao01"
  default_pool_size:  "" => "1"
  disk_encryption:    "" => "true"
  hardware:           "" => "shared"
  ingress_hostname:   "" => "<computed>"
  ingress_secret:     "<sensitive>" => "<sensitive>"
  is_trusted:         "" => "false"
  isolation:          "" => "<computed>"
  kube_version:       "" => "<computed>"
  machine_type:       "" => "b2c.4x16"
  name:               "" => "luster"
  no_subnet:          "" => "false"
  region:             "" => "<computed>"
  resource_group_id:  "" => "<computed>"
  server_url:         "" => "<computed>"
  update_all_workers: "" => "false"
  wait_time_minutes:  "" => "90"
  worker_num:         "" => "0"
  worker_pools.#:     "" => "<computed>"
  workers_info.#:     "" => "<computed>"
ibm_container_cluster.testacc_cluster: Still creating... (10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.testacc_cluster: 1 error(s) occurred:

* ibm_container_cluster.testacc_cluster: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"c492a208-911c-406e-92eb-98c406414024","code":"E0020","description":"To create a standard cluster, you must specify values for location, machine type, public VLAN, and private VLAN. To create a free cluster, specify cluster name only.","type":"Provisioning"}

### Expected Behavior
Free cluster should be deployed

### Actual Behavior
Although only name is mandatory, the process fails with validation error for datacenter
When datacenter, host_type etc fields are provided the below error is returned : 
* ibm_container_cluster.testacc_cluster: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"c492a208-911c-406e-92eb-98c406414024","code":"E0020","description":"To create a standard cluster, you must specify values for location, machine type, public VLAN, and private VLAN. To create a free cluster, specify cluster name only.","type":"Provisioning"}

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Praveengostu** [comment]
Hi @siddharthoak which version of ibm provider you are using..
 Pls try the below template with the latest version https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.14.1 to create a free cluster
```
resource "ibm_container_cluster" "testacc_cluster" {
 name = "myfreeluster"
 datacenter = "dal10"
 hardware = "shared"
 machine_type = "free"
}
```

**Comment by siddharthoak** [comment]
Thanks Praveen. That helped !
