### ISSUE TITLE
Error message for adminpassword (ibm_database) length requirement is not accurate. 

### ISSUE THREAD

**Issue by rajatagarwal-ibm** [IBM-Cloud/terraform-provider-ibm#4951]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_database

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Create postgresql database
resource "ibm_database" "postgresql_db" {
  depends_on        = [ibm_iam_authorization_policy.kms_policy]
  resource_group_id = var.resource_group_id
  name              = var.name
  service           = "databases-for-postgresql"
  location          = var.region
  plan              = "standard" 
  adminpassword     = "password123"
}

```

### Debug Output

```
Error: expected length of adminpassword to be in the range (10 - 32), got null
│ 
│   with module.icd_postgres.ibm_database.postgres_database,
│   on ../../main.tf line 59, in resource "ibm_database" "postgres_database":
│   59:   adminpassword             = var.admin_pass
```
### Expected Behavior

The password requirement has been changed to a minimum of 15 characters. 

See screenshot from UI

![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/108140212/f476bbe7-f5ee-4a8c-b381-05cbcf4fee1a)

### Steps to Reproduce

Give admin password length less than 15 chars - it will fail.
Verify the same in the UI

1. `terraform apply`

### References

* #0000

**Comment by alexhemard** [comment]
@rajatagarwal-ibm This should be addressed by https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4931/
