### ISSUE TITLE
Urgent: high priority:  data ibm_schematics_workspace bug

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#4965]
Okay Found out.
Using **1.58.0 and 1.58,1 works fine,**
It is a problem with : **from 1.59.0 onwards including 1.60.0**
```
data "ibm_schematics_workspace" "schematics_workspace" {
  workspace_id = var.prerequisite_workspace_id
  location     = local.location
}
```

Need a provider fix

Error:

```
You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
╷
│ Error: GetWorkspaceWithContext failed error unmarshalling schematicsv1.WorkspaceResponse: error unmarshalling property 'catalog_ref' as schematicsv1.CatalogRef: error unmarshalling property 'service_extensions' as []schematicsv1.ServiceExtensions: error unmarshalling property 'value': json: cannot unmarshal object into Go value of type string
```

**Comment by VaishnaviGopal** [comment]
Hi @surajsbharadwaj Can you check the terraform provider version again?
check with `1.60.0` version

**Comment by surajsbharadwaj** [comment]
Thank you.

Version 1.59.1 doesnt work. 
Please provide a note somewhere hinting people to upgrade to  1.60.0 

Can confirm 1.60.0 works now. This issue can be closed @VaishnaviGopal

**Comment by surajsbharadwaj** [comment]
Hello Team,
With terraform provider version 1.60.0. This was fixed and the issue is back again,,
Not able to read a schematics workspace data.
Facing this issue:
│ Error: GetWorkspaceWithContext failed error unmarshalling schematicsv1.WorkspaceResponse: error unmarshalling property 'catalog_ref' as schematicsv1.CatalogRef: error unmarshalling property 'service_extensions' as []schematicsv1.ServiceExtensions: error unmarshalling property 'value': json: cannot unmarshal object into Go value of type string
│ {
│     "StatusCode": 200,
│     "Headers": {
│         "Cache-Control": [
(edited)
Untitled
 
│ Error: GetWorkspaceWithContext failed error unmarshalling schematicsv1.WorkspaceResponse: error unmarshalling property 'catalog_ref' as schematicsv1.CatalogRef: error unmarshalling property 'service_extensions' as []schematicsv1.ServiceExtensions: error unmarshalling property 'value': json: cannot unmarshal object into Go value of type string
│ {
│     "StatusCode": 200,
│     "Headers": {
│         "Cache-Control": [
Click to expand inline (403 lines)
