### ISSUE TITLE
ibm_sm_private_certificate_configuration_template arguments ttl and max_ttl are not documented

### ISSUE THREAD

**Issue by davesteinberg** [IBM-Cloud/terraform-provider-ibm#4977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_sm_private_certificate_configuration_template

### Description

The [documentation](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/sm_private_certificate_configuration_template) does not include the arguments `ttl` and `max_ttl`. I have verified that both arguments work with the latest version of the provider (1.60.0).

**Comment by IdanAdar** [comment]
Fixed in 1.61.
