### ISSUE TITLE
Urgent: high priority: data ibm_schematics_workspace bug

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#4990]
I deployed First solution using 1.60.0 which created a schematics workspace and deployed the solution successfully.
I am using the second solution using 1.60.0 which reads schematics data and deploys more resources...
 I also tried with 1.60.1 to read the workspace data from  schematics which was deployed using 1.60.0
 so 1.60.1 and 1.60.0 both fails to read the data from 1.60.0 workspace .
```
 
 │ Error: GetWorkspaceWithContext failed error unmarshalling schematicsv1.WorkspaceResponse: error unmarshalling property 'catalog_ref' as schematicsv1.CatalogRef: error unmarshalling property 'service_extensions' as []schematicsv1.ServiceExtensions: error unmarshalling property 'value': json: cannot unmarshal object into Go value of type string
│ {
│     "StatusCode": 200,
│     "Headers": {
│         "Cache-Control": [
```
I also tried to read the data(created using 1.60.0) using 1.58.0  and i got this error:
```
Error: The requested statefile cannot be located. Run apply action to create a statefile.
│ 
│   with data.ibm_schematics_output.schematics_output,
│   on locals_schematics_data.tf line 10, in data "ibm_schematics_output" "schematics_output":
│   10: data "ibm_schematics_output" "schematics_output" {
```
Also referencing it here: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4965

 **is 1.60.0 creating bad schematics outputs in workspace ?**

**Comment by pradeep-b** [comment]
> is 1.60.0 creating bad schematics outputs in workspace?
No. The v1.60.0 of the provider had support for server extensions. Current assessment is, server extensions has elements that can be of type other than string and that's the issue.  Since in the prior versions, server extensions itself was not processed, it didn't hit the problem. 
Vaishnavi is aware and looking into this.

**Comment by surajsbharadwaj** [comment]
Hey,
Would like to know what would be the ETA for this fix ? We have already made a DA release and its in PROD..

**Comment by VaishnaviGopal** [comment]
Hi @surajsbharadwaj ,

We are ready with the fix but we are going to make a release in the first week of January 2024.

**Comment by VaishnaviGopal** [comment]
Hi @surajsbharadwaj 
Please test with the latest version of provider. `1.61.0` . Fix has been added
