### ISSUE TITLE
[CBR] Error during TF detroy for CBR rules/zones.

### ISSUE THREAD

**Issue by Ak-sky** [IBM-Cloud/terraform-provider-ibm#4997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
Terraform Version v1.5.7
Terraform IBM Provider Version v1.57.1

### Affected Resource(s)

* ibm_cbr_zone
* ibm_cbr_rule

### Terraform Configuration Files

We have been seeing intermittent [CBR](https://github.com/terraform-ibm-modules/terraform-ibm-cbr) failures during TF destroy for the [TIM modules](https://github.com/terraform-ibm-modules/) for the CBR rules/zones.
It looks like that all the rules are not getting detroyed first before deletion starts for the zones and then it is throwing an error like this
`The network zone 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' is referenced by one or more rules and cannot be deleted.`

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Debug Output

[TF Trace logs](https://gist.github.com/Ak-sky/0f1e3eef6b8b33c27e7d0713dc67bedb)
[TF stdout text](https://gist.github.com/Ak-sky/f47b7866aaff84f4e0349e5e9d1add07)

### Expected Behavior

All the rules/zones should get deleted during the TF destroy.

### Actual Behavior

Rules/zones are not getting deleted.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ocofaigh** [comment]
CBR team have confirmed there is a proposed fix coming for this
