### ISSUE TITLE
 ibm_secrets_manager_secret terraform is not working

### ISSUE THREAD

**Issue by kpatelibm** [IBM-Cloud/terraform-provider-ibm#5028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Question

We are getting an error while running the terraform code for IBM secrets manager as follow:  we noticed this data source is deprecated in documentation. If yes, could you advise alternative to interact with ibm secret manager with terraform?

module.pre-production.ibm_iam_access_group_policy.cos_assets_public_policy: Refreshing state... [id=AccessGroupId-PublicAccess/84122da3-c611-49ce-b64c-b1c7bffc73a2]
╷
│ Error: /api/v1/secrets is not a valid access endpoint.
│ 
│   with module.pre-production.data.ibm_secrets_manager_secrets.secrets_manager,
│   on pre-production/dsce-sm.tf line 8, in data "ibm_secrets_manager_secrets" "secrets_manager":
│    8: data "ibm_secrets_manager_secrets" "secrets_manager" {
│ 
╵
╷
│ Error: Action is not authorized.
│ 
│   with module.production.ibm_cis_healthcheck.health_check,
│   on production/dsce-cis.tf line 13, in resource "ibm_cis_healthcheck" "health_check":
│   13: resource "ibm_cis_healthcheck" "health_check" {
│ 
╵
╷
│ Error: Action is not authorized.
│ 
│   with module.production.ibm_cis_domain.domain["dsce.ibm.com"],
│   on production/dsce-cis.tf line 53, in resource "ibm_cis_domain" "domain":
│   53: resource "ibm_cis_domain" "domain" {
│ 
╵
╷
│ Error: [ERROR] Error getting alert policy detail Action is not authorized., {
│     "StatusCode": 401,
│     "Headers": {
│         "Cache-Control": [
│             "no-cache, no-store, must-revalidate"
│         ],
│         "Cf-Cache-Status": [
│             "DYNAMIC"
│         ],
│         "Cf-Ray": [
│             "83fbd4c91caa084a-IAD"
│         ],
│         "Content-Length": [
│             "116"
│         ],
│         "Content-Security-Policy": [
│             "default-src 'self'"
│         ],
│         "Content-Type": [
│             "application/json; charset=UTF-8"
│         ],
│         "Date": [
│             "Wed, 03 Jan 2024 14:11:31 GMT"
│         ],
│         "Server": [
│             "cloudflare"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000; includeSubdomains"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Correlation-Id": [
│             "3fde707f-b7f4-4a08-a7a9-2f88a4e020bb"
│         ],
│         "X-Envoy-Upstream-Service-Time": [
│             "2239"
│         ]
│     },
│     "Result": {
│         "errors": [
│             {
│                 "code": 401,
│                 "message": "Action is not authorized."
│             }
│         ],
│         "trace": "3fde707f-b7f4-4a08-a7a9-2f88a4e020bb"
│     },
│     "RawResult": null
│ }
│ 
│ 
│   with module.production.ibm_cis_alert.alert,
│   on production/dsce-cis.tf line 118, in resource "ibm_cis_alert" "alert":
│  118: resource "ibm_cis_alert" "alert" {
│ 
╵
╷
│ Error: /api/v1/secrets is not a valid access endpoint.
│ 
│   with module.production.data.ibm_secrets_manager_secrets.secrets_manager,
│   on production/dsce-sm.tf line 8, in data "ibm_secrets_manager_secrets" "secrets_manager":
│    8: data "ibm_secrets_manager_secrets" "secrets_manager" {
│ 
╵
╷
│ Error: /api/v1/secrets is not a valid access endpoint.
│ 
│   with module.test.data.ibm_secrets_manager_secrets.secrets_manager,
│   on test/dsce-sm.tf line 8, in data "ibm_secrets_manager_secrets" "secrets_manager":
│    8: data "ibm_secrets_manager_secrets" "secrets_manager" {
│ 
╵
### New or Affected Resource(s) or Datasource(s)

* ibm_secrets_manager_secret

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by shemau** [comment]
From another secrets manager consumer.

Everything changed about a year ago, when secrets manager upgraded the API and enabled a more elaborate terraform ibm provider implementation. I think there was a period when v1 and v2 API were supported (server side).  The output above suggests that v1 has been removed now.

It is unclear which provider version is used above, support changed a lot in 1.51.0; although there are subsequent fixes, so I recommend something newer, the newer the better. From this version secrets have data sources starting ibm_sm_, for example [ibm_sm_arbitrary_secret](https://registry.terraform.io/providers/IBM-Cloud/ibm/1.61.0/docs/data-sources/sm_arbitrary_secret) and [ibm_sm_kv_secret](https://registry.terraform.io/providers/IBM-Cloud/ibm/1.61.0/docs/data-sources/sm_kv_secret). There are many options available in the sidebar of those links.

**Comment by IdanAdar** [comment]
```
Error: /api/v1/secrets is not a valid access endpoint.
```

API v1 has been deprecated for more than a year and it is no longer supported. Please use the v2 data sources.

**Comment by kpatelibm** [comment]
Could you provide which data source to be used for v2 data sources?

**Comment by IdanAdar** [comment]
All resources that start with `ibm_sm_...`: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs.
The two `ibm_secrets_manager_...` ones should be removed by the IBM provider maintainers. FYI @hkantare

**Comment by IdanAdar** [comment]
Files will be removed in the near future.
