### ISSUE TITLE
bulk vm issue

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#504]
Hi there,
I have a problem using the bulk VM feature on the ibm_compute_vm_instance.

I have the case that I need to implement multiple Server with exactly the same configuration. Therefore I will use a Module with the Bulk VM feature.
But if I just have one VM inside the Bulk VM list, the provider will always set the hostname and domain to an empty string after I ordered the machine.

Example: 
(Module part)
...
resource "ibm_compute_vm_instance" "AidaSpace_dc_a" {
  bulk_vms             = "${var.aida_bulk_dict_dc_a}"
  flavor_key_name      = "${var.aida_flavor_key_name}"
  hourly_billing       = true
  datacenter           = "${var.datacenter_a}"
  network_speed        = "1000"
  private_vlan_id      = "${var.private_vlan_dc_a}"
  private_network_only = true
  os_reference_code    = "WIN_2016-STD_64"
}
...

(Module call)
...
module "CapSpace" {
  source       = "../../module/CaptivaSpace"
  domain       = "${var.domain}"
  datacenter_a = "fra02"
  private_vlan_dc_a = "${ibm_network_vlan.Cap01_Priv_Test_Fra02.id}"
  aida_flavor_key_name = "BL2_4X16X100"
  
  aida_bulk_dict_dc_a = [
    {
      hostname = "Aida03"
      domain   = "${var.domain}"
    },
  ]
...

as you can see I just use one VM in the Bulk definition (aida_bulk_dict_dc_a). If I run Terraform apply, the VM will be ordered successfully. But if I run terraform plan after that I will receive this message:

Terraform will perform the following actions:

  ~ module.CapSpace.ibm_compute_vm_instance.AidaSpace_dc_a
      domain:              "Cap01.test.loc" => ""
      hostname:            "Aida03" => ""

Why? Seems to be a bug, or?

### Terraform Version
Terraform v0.11.11
provider.ibm: version = "~> 0.14"
(0.14.1)

### tfstate part

{
    "version": 3,
    "terraform_version": "0.11.11",
    "serial": 6,
    "lineage": "b2d716ce-ff54-6f98-0151-6ef78d05798c",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {
              ...
                "ibm_compute_vm_instance.AidaSpace_dc_a": {
                    "type": "ibm_compute_vm_instance",
                    "depends_on": [],
                    "primary": {
                        "id": "70618663",
                        "attributes": {
                            "block_storage_ids.#": "0",
                            "bulk_vms.#": "1",
                            "bulk_vms.706503199.domain": "Cap01.test.loc",
                            "bulk_vms.706503199.hostname": "Aida03",
                            "cores": "4",
                            "datacenter": "fra02",
                            "dedicated_acct_host_only": "false",
                            "disks.#": "0",
                            "domain": "Cap01.test.loc",
                            "file_storage_ids.#": "0",
                            "flavor_key_name": "BL2_4X16X100",
                            "hostname": "Aida03",
                            "hourly_billing": "true",
                            "id": "70618663",
                            "ip_address_id_private": "125457523",
                            "ipv4_address": "",
                            "ipv4_address_private": "10.134.217.59",
                            "ipv6_enabled": "false",
                            "ipv6_static_enabled": "false",
                            "local_disk": "true",
                            "memory": "16384",
                            "network_speed": "1000",
                            "notes": "",
                            "os_reference_code": "WIN_2016-STD_64",
                            "private_interface_id": "41594273",
                            "private_network_only": "true",
                            "private_security_group_ids.#": "0",
                            "private_subnet": "10.134.217.0/26",
                            "private_subnet_id": "1932541",
                            "private_vlan_id": "2525207",
                            "public_bandwidth_unlimited": "false",
                            "public_interface_id": "41594275",
                            "public_security_group_ids.#": "0",
                            "secondary_ip_addresses.#": "0",
                            "transient": "false",
                            "wait_time_minutes": "90"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.ibm"
                },
                
                ...
            },
            "depends_on": []
        },
        {
            "path": [
                "root",
                "CapSpace",
                "CaptivaDatabase"
            ],
            "outputs": {
                ...
            },
            "resources": {
                ...
            },
            "depends_on": []
        }
    ]
}

**Comment by Praveengostu** [comment]
bulk_vm's parameter is to used when ordering more than one vm .. So we will add a restriction to order more than one vm when using the bulk_vm option

**Comment by ThomasUllrich666** [comment]
@Praveengostu Thank you.
Can you please provide more information about the NOTE: "Update is not supported when the bulk_vms parameter is used." on https://ibm-cloud.github.io/tf-ibm-docs/v0.14.1/r/compute_vm_instance.html

What do you mean with Update?
Can I append the list of Bulk VMs later on, if I need more VMs?

**Comment by Praveengostu** [comment]
@ThomasUllrich666 The bulk vms is a ForceNew Parmeter so you can not update it later on..
Regarding the `NOTE: "Update is not supported when the bulk_vms parameter is used."` This mean tf configuration can not be updated later on when the bulk vm parameter is used

**Comment by ThomasUllrich666** [comment]
@Praveengostu thank you.
