### ISSUE TITLE
ibm_is_images documentation updates - value for status and visibility

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#5060]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_is_images

### Description
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_images

![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/6932057/b398d8ed-5ae0-42e3-913d-3f2a72ef2493)

"ibm_is_images"  
- [ ] List the possible values for the status attribute (i tried "available")
- [ ] What is the default value for visibility when the optional attribute is not provided

### References

* #0000

**Comment by ujjwal-ibm** [comment]
> List the possible values for the status attribute (i tried "available")

Status : One of  {available, deleting, deprecated, failed, obsolete, pending, unusable}

I tried this

```
data ibm_is_images this {
	  status           = "available"
	# status = "deprecated"
	# visibility = "private"

}

```
>  What is the default value for visibility when the optional attribute is not provided
There is no default value of visibility, no value means no filter on visibility
