### ISSUE TITLE
On second apply terraform wants to delete existing COS bucket using single_site_location

### ISSUE THREAD

**Issue by akocbek** [IBM-Cloud/terraform-provider-ibm#5064]
When single_site_location is used for bucket creation then `region_location` is set by ibm provider, even if we explicitly set `region_location` to `null`. Consequently on second apply terraform wants to delete existing bucket. 

terraform state file
```
"resources": [
    {
      "mode": "managed",
      "type": "ibm_cos_bucket",
      "name": "cos_bucket_test",
      "provider": "provider[\"registry.terraform.io/ibm-cloud/ibm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "abort_incomplete_multipart_upload_days": [],
            "activity_tracking": [],
            "allowed_ip": null,
            "archive_rule": [],
            "bucket_name": "ann-test-cos-bucket",
            "crn": "crn:v1:bluemix:public:cloud-object-storage:global:a/abac0df06b644a9cabc6e44f55b3880e:85341392-0057-422a-b82b-b3e34f6f4037:bucket:ann-test-cos-bucket",
            "cross_region_location": null,
            "endpoint_type": "public",
            "expire_rule": [],
            "force_delete": true,
            "hard_quota": 0,
            "id": "crn:v1:bluemix:public:cloud-object-storage:global:a/abac0df06b644a9cabc6e44f55b3880e:85341392-0057-422a-b82b-b3e34f6f4037:bucket:ann-test-cos-bucket:meta:ssl:tor01:public",
            "key_protect": null,
            "kms_key_crn": null,
            "metrics_monitoring": [],
            "noncurrent_version_expiration": [],
            "object_lock": null,
            "object_versioning": [],
            "region_location": "ca-tor",
            "resource_instance_id": "crn:v1:bluemix:public:cloud-object-storage:global:a/abac0df06b644a9cabc6e44f55b3880e:85341392-0057-422a-b82b-b3e34f6f4037::",
            "retention_rule": [],
            "s3_endpoint_direct": "s3.direct.tor01.cloud-object-storage.appdomain.cloud",
            "s3_endpoint_private": "s3.private.tor01.cloud-object-storage.appdomain.cloud",
            "s3_endpoint_public": "s3.tor01.cloud-object-storage.appdomain.cloud",
            "satellite_location_id": null,
            "single_site_location": "tor01",
            "storage_class": "standard",
            "timeouts": null
          },
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
terraform -version
Terraform v1.7.0
on darwin_arm64

IBM Cloud Provider version 1.60.1  
```

### Affected Resource(s)

* ibm_cos_bucket

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_resource_group" "resource_group" {
  name     = "ann-test-rg"
}


resource "ibm_resource_instance" "cos_instance" {
  name              = "ann-test-cos-instance"
  resource_group_id = resource.ibm_resource_group.resource_group.id
  service           = "cloud-object-storage"
  plan              = "standard"
  location          = "global"
}

resource "ibm_cos_bucket" "cos_bucket_test" {
  resource_instance_id  =  resource.ibm_resource_instance.cos_instance.id
  bucket_name           = "ann-test-cos-bucket"
  region_location       = null
  single_site_location  = "tor01"
}
```

### Debug Output

https://gist.github.com/akocbek/bc4d857452f7b3d2949e4165ef9a265c

### Expected Behavior

On second apply the existing COS bucket shouldn't delete

### Actual Behavior

On second apply the existing COS bucket is forced to delete because of `region_location      = "ca-tor" -> null`

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### References

* #0000

**Comment by ocofaigh** [comment]
Screenshot from subseqnet apply attempt below. As you can see its trying to now set region_location from `cat-tor` to `null` as this is causing the destroy. But null was passed in initial apply, but it seems provider is automatically adding `ca-tor`:
```
2024-01-19T10:54:58.082Z [WARN]  Provider "provider[\"registry.terraform.io/ibm-cloud/ibm\"]" produced an unexpected new value for ibm_cos_bucket.cos_bucket_test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .region_location: was null, but now cty.StringVal("ca-tor")
      - .hard_quota: was null, but now cty.NumberIntVal(0)
```

![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/29608224/1595ea04-0481-4162-938e-2b51a7b019b8)

**Comment by IBM-diksha** [comment]
@akocbek  We are looking into this one.

**Comment by IBM-diksha** [comment]
We looked into this one , the tor01 is no more a single site , it has been upgraded to ca-tor which is a regional location. But the endpoint is active.That is the reason this issue is seen only with tor01 ,we dont see this issue for any other single site.
Here is the list of single sites that are available that can be used instead.
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-endpoints

Or the ca-tor regional location can also be used.

**Comment by IBM-diksha** [comment]
Discussed with the customer on an internal channel , it works for all the valid single site locations according to the documentation. Also added an internal ticket to the backlog to have a validation to allow only supported single site locations.

Closing this ticket as the customer is now using one of the supported single site.
