### ISSUE TITLE
Not able to delete resource groups in Most of DCs

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#5067]
Hello team,

Terraform fails to delete the resource groups

Error: [ERROR] Error Deleting resource group: Resource groups with active or pending reclamation instances can't be deleted. Use the CLI commands "ibmcloud resource service-instances --type all" and "ibmcloud resource reclamations" to check for remaining instances, then delete the instances and try again. with response code

**Comment by ocofaigh** [comment]
@surajsbharadwaj This is not a provider issue - its a BSS backend issue, and they will be adding a fix to production is 2-3 weeks. Suggest closing this, it is being tracked internally.
