### ISSUE TITLE
changing name on boot_volume ibm_is_instance does not affect resources in IBM cloud

### ISSUE THREAD

**Issue by melwafi-youcan** [IBM-Cloud/terraform-provider-ibm#5068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```bash
$ terraform -v
Terraform v1.6.2
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.7.0. You can update by downloading from https://www.terraform.io/downloads.html
```
```bash
$ terraform providers

Providers required by configuration:
.
└── provider[registry.terraform.io/ibm-cloud/ibm] 1.61.0

Providers required by state:

    provider[registry.terraform.io/ibm-cloud/ibm]
```
### Affected Resource(s)

* ibm_is_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# main.tf
resource "ibm_is_instance" "instance" {
  name    = "instance-lon3"
  image   = data.ibm_is_image.ubuntu_18_04_6_7.id
  vpc     = data.ibm_is_vpc.VPC.id
  zone    = "${var.ibm_region}-3"
  profile = "cx2-8x16"
  tags    = flatten([var.ibm_tags, []])
  primary_network_interface {
    subnet = local.subnets[index(local.subnets.*.name, "lon3-subnet-4")].id
    security_groups = [
      local.security_groups[index(local.security_groups.*.name, "private-instances")].id,
    ]
  }

  boot_volume {
    auto_delete_volume = false
    name               = "instance-lon3-boot"
    size               = 100
  }
}

# import.tf
import {
  to = ibm_is_instance.instance
  id = "jdawd2q8dydhy8d29yd2dy2dy92d9d1uhdqd1h"
}
```

### Expected Behavior

Terraform should changes the boot volume name when `terraform apply` finished successfully

### Actual Behavior

When I ran `terraform apply` and after that I run `terraform plan` I get the same changes I applied previously 

### Steps to Reproduce

1. create a new project with same versions and same code above
2. `terraform plan`
3. `terraform apply`
4. change the name of the boot volume 
5. `terraform apply`
6. rerun `terraform plan`

**Comment by ujjwal-ibm** [comment]
looking into it

**Comment by melwafi-youcan** [comment]
@ujjwal-ibm any updates did u manage to reproduce the bug?

**Comment by ujjwal-ibm** [comment]
We're working on a fix. Once PR is up, will tag under this issue.
