### ISSUE TITLE
Feature Request: Multiple vNICs on VMs

### ISSUE THREAD

**Issue by msambrato** [IBM-Cloud/terraform-provider-ibm#511]
There doesn't appear to be any method presently of using terraform to provision a VM with multiple vNICs - being able to specify public or private IP.  If I want to create a VM through terraform there is detailed instructions available to control public or private on a single vNIC, but no documentation or apparent way to create a VM and add multiple public network interfaces as the option exists via online portal.

**Comment by stevestrutt** [comment]
Multiple vNICs are not a feature of Softlayer VSIs. One public facing vNIC and one private. A VSI can only be on two VLANs, one public, one private. The illusion of multiple vNICs can be created by assigning secondary IP addresses to the vNIC. Usage of secondary IP addresses is well documented in the SL material and is supported by the Terraform provider. 

The Terraform provider is implementing the features exposed by the underlying platform API and supported by the platform. In practice the IBM Provider supports the SL API well, especially for VSIs and baremetal.

**Comment by hkantare** [comment]
closing the issue based on above comment
