### ISSUE TITLE
`tier0` and `fixed` not supported as `pi_volume_type`

### ISSUE THREAD

**Issue by connorterech** [IBM-Cloud/terraform-provider-ibm#5117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Provider v1.56.2

### Affected Resource(s)

* ibm_pi_volume_type

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

The Power VS GUI now includes tier0 and fixed as volume types, but those types are not currently supported by the provider

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.

resource "ibm_pi_volume" "smatzek_storage_test_volume_tier1vol" {
  provider               = ibm.power_vs_dal10
  pi_cloud_instance_id   = ibm_resource_instance.power_vs_workspace_smatzek_storage_test.guid
  pi_volume_size         = 1
  pi_volume_name         = "${var.prefix}-smatzek-storage-test-tier1vol"
  pi_volume_shareable    = false
  pi_replication_enabled = false
  pi_volume_type         = "tier0"
  pi_affinity_policy     = "affinity"
  pi_affinity_instance   = ibm_pi_instance.smatzek_storage_test_workspace_instance_tier1vm.instance_id
}
```

### Expected Behavior

The power volume should be created with volume type `tier0`

### Actual Behavior

terraform apply
```
│ Error: "pi_volume_type" must contain a value from []string{"ssd", "standard", "tier1", "tier3"}, got "tier0"
│
│   with ibm_pi_volume.smatzek_storage_test_volume_tier0vol,
│   on power_volumes.tf line 77, in resource "ibm_pi_volume" "smatzek_storage_test_volume_tier0vol":
│   77:   pi_volume_type         = "tier0"
```

### Steps to Reproduce

1. `terraform apply` with the ibm_pi_volume resource as shown above.

### References

* #0000

**Comment by michaelkad** [comment]
@connorterech Those have updated in [v1.61.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.61.0), please do update you version. One thing to note is that `fixed` is `tier5k` but that will be updated to `fixed`

**Comment by connorterech** [comment]
@michaelkad Do you know when `tier5k` will be updated to `fixed`? The next release?

**Comment by michaelkad** [comment]
@connorterech Not sure, still waiting for the storage team to update us to go ahead with the change.

**Comment by smatzek** [comment]
When `tier5k` is updated to `fixed` will the `tier5k` value still be supported for backward compatibility?

**Comment by michaelkad** [comment]
@connorterech @smatzek 
The update was provided in [v1.61.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.61.0) and after talking with the storage team, `tier5k` will no be changed to `fixed`. It is called fixed only in the `UI` but the  API,CLI and Terraform will be using `tier5k`.
Let me know if you have any question.  Closing this ticket, feel free to reopen.
