### ISSUE TITLE
ibm_scc_instance_settings is always using us-south SCC endpoint

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#5131]
The `ibm_scc_instance_settings` will fail with below error if you attempt with a region that is not us-south. I tried with `eu-es` and when looking at trace logs, I can see its trying to hit the us-south endpoint, even though my provider config is set up like so:
```
provider "ibm" {
  ibmcloud_api_key = var.ibmcloud_api_key
  region           = "eu-es"
}
```

Error:
```
2024-02-13T17:19:34.228Z [INFO]  provider.terraform-provider-ibm_v1.62.0: 2024/02/13 17:19:34 [DEBUG] PATCH https://us-south.compliance.cloud.ibm.com/instances/f75c6a32-5310-44d5-b4b8-1cf358aa5873/v3/settings: timestamp=2024-02-13T17:19:34.228Z
2024-02-13T17:19:35.079Z [INFO]  provider.terraform-provider-ibm_v1.62.0: 2024/02/13 17:19:35 [Debug] Response:
HTTP/2.0 404 Not Found
Cache-Control: no-store
Cf-Cache-Status: DYNAMIC
Cf-Ray: 854ebcb0de6ebb06-MXP
Content-Type: application/json; charset=utf-8
Date: Tue, 13 Feb 2024 17:19:35 GMT
Server: cloudflare
Strict-Transport-Security: max-age=31536000; includeSubDomains
Transaction-Id: e2d78bad-a4c6-4dd9-8c47-ffe11088fcde
X-Content-Type-Options: nosniff
X-Correlation-Id: e2d78bad-a4c6-4dd9-8c47-ffe11088fcde
X-Envoy-Upstream-Service-Time: 27
X-Request-Id: c3eaf1cb-f54b-4fcd-bda6-78f9da654e2c

{"errors":[{"code":"not_found","message":"The requested resource was not found","more_info":"https://cloud.ibm.com/apidocs/security-compliance-admin"}],"status_code":404,"trace":"e2d78bad-a4c6-4dd9-8c47-ffe11088fcde"}: timestamp=2024-02-13T17:19:35.078Z
```

The SCC team have confirmed as a workaround you can set `export IBMCLOUD_SCC_API_ENDPOINT=https://eu-es.compliance.cloud.ibm.com/` however this should not be requied, as terraform should be using the value passed for region provider config.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

tf 1.6.0
ibm provider 1.62.0

### Affected Resource(s)

* ibm_scc_instance_settings

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

Run https://github.com/terraform-ibm-modules/terraform-ibm-scc/tree/main/examples/basic but target it to any other region that is not us-south

### Debug Output

[scc-trace.log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/14270145/scc-trace.log)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tyao117** [comment]
The source of the problem is scc-go-sdk did not support that region in the terraform provider yet: https://github.com/IBM/scc-go-sdk/blob/cff042fa2e9ffc46fea13e17fdc37b1af67b79e8/v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3.go#L120. I am currently creating a PR to support that region.
