### ISSUE TITLE
Failure in tests after last commit

### ISSUE THREAD

**Issue by haimsch** [IBM-Cloud/terraform-provider-ibm#5132]
After pulling from master local tests are failing:
```
        Error: InternalValidate
        
          with provider["registry.terraform.io/hashicorp/ibm"],
          on terraform_plugin_test.tf line 1, in provider "ibm":
           1: provider "ibm" {}
        
        Internal validation of the provider failed! This is always a bug
        with the provider itself, and not a user issue. Please report
        this bug:
        
        1 error occurred:
                * resource ibm_pi_network: ConflictsWith: pi_network_jumbo cannot reference
        self (pi_network_jumbo)
        
 ```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ismirlia** [comment]
I was under the impression this was fixed by: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5027

Please give more detail on how to reproduce.

**Comment by haimsch** [comment]
@ismirlia  Yes, this is not reproducible any more

**Comment by ismirlia** [comment]
Ok I will close this ticket then.
