### ISSUE TITLE
Docs fix : VPC infrastructure

### ISSUE THREAD

**Issue by geethasathyamurthy** [IBM-Cloud/terraform-provider-ibm#5182]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

    terraform ibm provider resource > ibm_is_virtual_endpoint_gateway is worngly documented.
It shows for ips{} block:
we need to provide only subnet/reserved ip ID but while deploying found name is also a required field but shown as optional in doc

*ibm_is_virtual_endpoint_gateway

### Description

 terraform ibm provider resource > ibm_is_virtual_endpoint_gateway is worngly documented.
It shows for ips{} block:
we need to provide only subnet/reserved ip ID but while deploying found name is also a required field but shown as optional in doc

--->
### References

Docs: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_virtual_endpoint_gateway

Git issue: https://github.ibm.com/ibmcloud/docs-feedback-issues/issues/1179

* #0000

**Comment by ujjwal-ibm** [comment]
looking into this
