### ISSUE TITLE
Security groups change on a VM triggers creation of a new resource

### ISSUE THREAD

**Issue by kovyrin** [IBM-Cloud/terraform-provider-ibm#519]
Hello,

We're using ibm terraform provider for managing our cloud VMs and I've noticed a very strange behavior: when I add a security group to the list of `private_security_group_ids` for a VM, terraform says `private_security_group_ids.#:       "4" => "5" (forces new resource)` and `private_security_group_ids.1319471: "" => "1319471" (forces new resource)`, which results in a destruction of the VM and the creation of a new one. I see no reason to destroy a VM to make a change in the list of its security groups and I can do that with the IBM console. This looks like a bug in the provider.

### Affected Resource(s)
- ibm_compute_vm_instance

### Terraform Configuration Files
```hcl
resource "ibm_compute_vm_instance" "web-node" {
  datacenter = "${var.datacenter}"
  hostname   = "${var.node_name}.${var.datacenter}"
  domain     = "swiftype.net"

  public_vlan_id  = "${var.public_vlan_id}"
  private_vlan_id = "${var.private_vlan_id}"

  hourly_billing = "${var.hourly_billing}"

  # New VM instance type: CPU/RAM/disk are configured via flavors
  flavor_key_name = "${var.node_flavor}"
  local_disk      = true
  network_speed   = 1000

  # Extra disk for encrypted logs, etc
  disks = [250]

   # Install CentOS 7
  os_reference_code = "CENTOS_7_64"
  ssh_key_ids       = ["${data.ibm_compute_ssh_key.swiftype_bootstrap.id}"]

  # Limit what the instance can do
  private_security_group_ids = [
    "${data.ibm_security_group.allow-icmp.id}",
    "${data.ibm_security_group.allow-ingress-ssh.id}",
    "${data.ibm_security_group.allow-egress-internal-base-services-and-monitoring.id}",
    "${data.ibm_security_group.allow-egress-internal-api.id}",
    "${data.ibm_security_group.allow-edge-web-private.id}",
  ]

  public_security_group_ids = [
    "${data.ibm_security_group.allow-icmp.id}",
    "${data.ibm_security_group.allow-egress-standard.id}",
    "${data.ibm_security_group.allow-edge-web-public.id}",
  ]
}
```

### Expected Behavior
Terraform should change the set of security groups without re-provisioning a VM.

### Actual Behavior
Terraform destroys and re-creates the VM when security groups set is changed.

### Steps to Reproduce
Create a VM with some security groups attached via `private_security_group_ids`. Then change the set (add or remove security groups) and it'll force re-creation of the resource.

**Comment by saedabdu** [comment]
@kovyrin 
You can use lifecycle under the ibm_compute_vm_instance resource
```
resource "ibm_compute_vm_instance" "web-node" {
  datacenter = "${var.datacenter}"
  hostname   = "${var.node_name}.${var.datacenter}"
  domain     = "swiftype.net"
  lifecycle {
    ignore_changes = ["public_security_group_ids", "private_security_group_ids"]
  }
```
reference 
https://www.terraform.io/docs/configuration/resources.html#lifecycle

**Comment by kovyrin** [comment]
That's cool! Didn't know about that option. But why is it re-creating VMs by default? Is there some fundamental reason I'm missing?

**Comment by hkantare** [comment]
Here in below doc we explained we cannot use update of security group on VM instances. To achieve  update use ibm_network_interface_sg_attachment

https://ibm-cloud.github.io/tf-ibm-docs/v0.14.1/r/compute_vm_instance.html

**Comment by saedabdu** [comment]
@kovyrin
Kindly close the issue as this is the best answer we could provide.

**Comment by kovyrin** [comment]
Thank you, it makes sense.
