### ISSUE TITLE
Schematics agent and agent deploy resources are recreating during second apply

### ISSUE THREAD

**Issue by VaishnaviGopal** [IBM-Cloud/terraform-provider-ibm#5216]
Schematics agent and agent deploy resources are recreating during second apply even when no changes are made to the template

**Comment by VaishnaviGopal** [comment]
[logs.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/14663897/logs.txt)

**Comment by rajatagarwal-ibm** [comment]
Is there any update on this issue?

**Comment by VaishnaviGopal** [comment]
This is not observed with latest release 1.70.0. So, closing this.
