### ISSUE TITLE
Output of kubernetes cluster config causes error 404 when the cluster does not exist

### ISSUE THREAD

**Issue by BastianVoigt** [IBM-Cloud/terraform-provider-ibm#522]
Hi there,

I discovered a bug. Outputting the kubernetes config file makes terraform fail when the cluster does not exist yet. 

### Terraform Version
0.11.11

### Affected Resource(s)
ibm_container_cluster_config
ibm_container_cluster

### Terraform Configuration Files
```hcl
provider "ibm" {
  bluemix_api_key    = "${var.ibm_bmx_api_key}"
  softlayer_username = "${var.ibm_sl_username}"
  softlayer_api_key  = "${var.ibm_sl_api_key}"
  region             = "${var.ibm_region}"
}

data "ibm_org" "orgData" {
  org = "${var.ibm_org}"
}

data "ibm_space" "spaceData" {
  org   = "${var.ibm_org}"
  space = "${var.ibm_space}"
}

data "ibm_account" "accountData" {
  org_guid = "${data.ibm_org.orgData.id}"
}

data "ibm_resource_group" "resourceGroupData" {
  name = "${var.ibm_resource_group}"
}

data "ibm_container_cluster_config" "containerClusterConfigResource" {
  cluster_name_id = "${var.clustername}"
  config_dir = "."
}

resource "ibm_container_cluster" "containerClusterResource" {
  name              = "${var.clustername}"
  datacenter        = "${var.datacenter}"
  kube_version      = "${var.kubernetes_version}"
  org_guid          = "${data.ibm_org.orgData.id}"
  space_guid        = "${data.ibm_space.spaceData.id}"
  account_guid      = "${data.ibm_account.accountData.id}"
  region            = "${var.ibm_region}"
  resource_group_id = "${data.ibm_resource_group.resourceGroupData.id}"
  default_pool_size = 1
  machine_type      = "u2c.2x4"
  billing           = "hourly"
  hardware          = "${var.hardware}"
  public_vlan_id    = "${var.public_vlan_id}"
  private_vlan_id   = "${var.private_vlan_id}"
  is_trusted        = false
  disk_encryption   = true
  wait_time_minutes = 90
}

output "config" {
  value = "${data.ibm_container_cluster_config.containerClusterConfigResource.config_file_path}"
}
```

### Debug Output
Please ask me via PM.
The dump might contain some internal information, so I cannot publish it here.

### Panic Output
n/a

### Expected Behavior
It should create a kubernetes cluster, download its config and output the config file location

### Actual Behavior
It fails during `terraform apply` when the cluster does not already exists:

    + terraform apply -auto-approve
    Acquiring state lock. This may take a few moments...

    data.ibm_org.orgData: Refreshing state...
    data.ibm_container_cluster_config.containerClusterConfigResource: Refreshing state...
    data.ibm_resource_group.resourceGroupData: Refreshing state...
    data.ibm_space.spaceData: Refreshing state...
    data.ibm_account.accountData: Refreshing state...

    Releasing state lock. This may take a few moments...

    Error: Error refreshing state: 1 error(s) occurred:

    * data.ibm_container_cluster_config.containerClusterConfigResource: 1 error(s) occurred:

    * data.ibm_container_cluster_config.containerClusterConfigResource:     
    data.ibm_container_cluster_config.containerClusterConfigResource: 
    Error downloading the cluster config [sda-testauto]: 
    Request failed with status code: 404, ServerErrorResponse: 
    {"incidentID":"7d554b50-edaf-4d3a-a8e2-9c7786ef61d1","code":"A0006","description":"The specified cluster could not be found. If you're using resource groups, make sure that you target the correct resource group.","type":"Authentication","recoveryCLI":"To list the clusters you have access to, run 'ibmcloud ks clusters'. To check the resource group ID of the cluster, run 'ibmcloud ks cluster-get \u003ccluster_name_or_ID\u003e'. To list the resource groups that you have access, run 'ibmcloud resource groups'. To target the resource group, run 'ibmcloud target -g \u003cresource_group\u003e'."}

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
None afaik.

### References
None

**Comment by hkantare** [comment]
data "ibm_container_cluster_config" "containerClusterConfigResource" {
  cluster_name_id = "${var.clustername}"
  config_dir = "."
}

Please either user depends_on = ["ibm_container_cluster. containerClusterResource] or cluster_name_id = "${ibm_container_cluster.containerClusterResource.id} in the datasource which downloads the config... 
The datasource and resource tries to run parallel and fails in datasource since the cluster is not yet created it..

**Comment by BastianVoigt** [comment]
Thanks @hkantare, this works perfectly. I'll close the issue, but maybe you can think about adding a hint to the documentation? It looks to me like it might be a common pitfall.
