### ISSUE TITLE
[CBR] Add the ability to update existing CBR rules and zones.

### ISSUE THREAD

**Issue by Ak-sky** [IBM-Cloud/terraform-provider-ibm#5235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of now there is no way to update the existing CBR [zones](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cbr_zone) and [rules](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cbr_rule) except from the UI.
We have a requirement where few of the base CBR rules/zones will be created before and later we want to update both existing zones and rules based on newly created VPCs etc.

### New or Affected Resource(s)

* ibm_cbr_zone
* ibm_cbr_rule

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by zhenwan** [comment]
@Ak-sky Besides UI, you can also update zones and rules by using [API](https://cloud.ibm.com/apidocs/context-based-restrictions), [CLI](https://cloud.ibm.com/docs/cli?topic=cli-cbr-plugin), Terraform. 
Please let me know if these are what you ask for.

**Comment by tyao117** [comment]
is this the problem where the update doesn't recognize the update from the main.tf?
<img width="1373" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/13957424/dc1ccbe8-04ba-44dc-8b1d-7cb9c97968d2">

my main.tf:
```
<img width="514" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/13957424/acb8db0e-a935-4e96-bb3d-8986b52cad5e">
```

**Comment by ocofaigh** [comment]
@zhenwan With terraform provider my understanding is its only possible to create new CBR zones or rules. We are looking for the ability to update an existing zone or rule using terraform. 
Our use case is that we may have one terraform state that creates the zones and rules, but then as more resource get created in our account (in different terraform state files) we want to ability to update the zones / rules with the new resources.
Does this make sense?

**Comment by ocofaigh** [comment]
@zhenwan @Ak-sky Should we sync up internally on this? This is blocking one of our committed AHA items for 2Q

**Comment by ocofaigh** [comment]
@zhenwan I don't think Tim's updates will cover our use case. As per above comment, our use case is that we have one terraform state that creates the zones and rules, but then as more resource get created in our account (in different terraform states) we need the ability to update the contexts of the existing zones / rules we with the new resources we created.

So for this to work, we would need a new provider resource (e.g. `ibm_cbr_rule_context`) in order to be able to update existing CBR zones / rules. Something similar to the way `ibm_is_security_group_rule` can be used to update an existing security group.

**Comment by vburckhardt** [comment]
Suggest to name the resource attach or attachment. This is conceptually the same as https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance_network_attachment or https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance_volume_attachment where objects are created, and then another resource is used to attach an object to another. This follows best practices in terraform / IaC in general around idempotency.

**Comment by LindaBat** [comment]
Hello, can you please provide an update on this issue.  Thanks.

**Comment by Ak-sky** [comment]
New TF resource `ibm_cbr_zone_addresses` has been added in this [release](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.68.0-beta0). Will going to give a try and update.

**Comment by Ak-sky** [comment]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cbr_zone_addresses is working fine as expected, closing this.
