### ISSUE TITLE
Question on usage of ibm_storage_file

### ISSUE THREAD

**Issue by jlerm** [IBM-Cloud/terraform-provider-ibm#526]
I understand general questions should be directed to the terraform.io community, however this relates to IBM types of resources.

Can anyone please provide advice on usage of IBM terraform provider, how can I provision multiple compute vm instances based on the count attribute, then create a certain number of ibm_file_storage resources?
Does ibm_file_storage support the count attribute?
And if it does, how can I implement the requirement above?
My problem is I don't want to spell out each and every instance of ibm_file_storage on a separate "resource" section
I want to make it all parameterized
I have a terraform template that creates different types of ibm_compute_vm_instance resources, each type with count attribute as an input parameter.
Example:

resource "ibm_compute_vm_instance" "hdp-datanodes" {
 count="${var.num_datanodes}"
 hostname = "${var.vm_name_prefix}-dn-${ count.index }"
 os_reference_code        = "REDHAT_7_64"
 domain                   = "${var.vm_domain}"
 datacenter               = "${var.datacenter}"
 private_vlan_id          = "${data.ibm_network_vlan.cluster_vlan.id}"
 network_speed            = 1000
 hourly_billing           = true
 private_network_only     = true
 cores                    = "${var.datanode_num_cpus}"
 memory                   = "${var.datanode_mem}"
 disks                    = "${var.datanode_disks}"
 dedicated_acct_host_only = false
 local_disk               = false
 ssh_key_ids              = [ "${ibm_compute_ssh_key.temp_public_key.id}"]
}
In the example above, I pass the number of HDP data nodes that I want to create, via ${var.num_datanodes} param.
Now, I want to create N nfs mount points as data devices for each HDP data node.
Is there a way of specifying ibm_storage_file as a nested resource?
Otherwise, is there any other way of accomplishing the above?

Thanks.

**Comment by hkantare** [comment]
Yes we can use count( ${var.num_datanodes} ) to storage provision ..I will share you an handy example of provision of `n' number of instances, storages(block) and script(https://console.bluemix.net/docs/infrastructure/BlockStorage/accessing_block_storage_linux.html#connecting-to-iscsi-luns-on-linux) which perform mount on all devices..

```
resource "ibm_compute_vm_instance" "masternode" {
  count                     = "${var.master_node_count}"
  os_reference_code         = "${var.master_os_ref_code}"
  hostname                  = "${var.master_hostname_prefix}-${var.random_id}-${var.master_hostname}-${count.index}"
  domain                    = "${var.domain}"
  datacenter                = "${var.datacenter}"
  private_network_only      = "false"
  network_speed             = 1000
  local_disk                = "false"
  flavor_key_name           = "${var.master_flavor}"
  ssh_key_ids               = ["${var.master_ssh_key_ids}"]
  private_vlan_id           = "${var.private_vlan_id}"
  public_vlan_id           = "${var.public_vlan_id}"
  public_security_group_ids = ["${ibm_security_group.openshift-master.id}"]
  private_security_group_ids = ["${ibm_security_group.openshift-master.id}"]
  hourly_billing             = "${var.hourly_billing}"
}
resource "ibm_storage_block" "masternode_block" {
  count          = "${var.master_node_count}"
  type           = "Performance"
  datacenter     = "${var.datacenter}"
  capacity       = 500
  iops           = 1000
  os_format_type = "Linux"
  hourly_billing = "${var.hourly_billing}"
  allowed_virtual_guest_ids  = ["${element(ibm_compute_vm_instance.masternode.*.id,count.index)}"]
}

locals {
  block_allowed_hosts = "${flatten(ibm_storage_block.masternode_block.*.allowed_host_info)}"
}

#################################################
# iSCSI Setup for Master node
#################################################
resource "null_resource" "iscsi_master" {
  count      = "${var.master_node_count}"
  connection {
    type     = "ssh"
    user     = "root"
    host     = "${element(ibm_compute_vm_instance.masternode.*.ipv4_address,count.index)}"
    private_key = "${file(var.master_private_ssh_key)}"
  }

  provisioner "remote-exec" {
  inline = [
    "timedatectl set-timezone UTC",
    "chmod 600 /root/.ssh/id_rsa",
    "yum install device-mapper-multipath iscsi-initiator-utils lvm2 -y",
    "echo 'InitiatorName=${lookup(local.block_allowed_hosts[count.index],"host_iqn")}' > /etc/iscsi/initiatorname.iscsi",
    "sed -i 's/.*node\\.session\\.auth\\.authmethod \\?=.*/node.session.auth.authmethod = CHAP/' /etc/iscsi/iscsid.conf",
    "sed -i 's/.*node\\.session\\.auth\\.username \\?=.*/node.session.auth.username = ${lookup(local.block_allowed_hosts[count.index],"username")}/' /etc/iscsi/iscsid.conf",
    "sed -i 's/.*node\\.session\\.auth\\.password \\?=.*/node.session.auth.password = ${lookup(local.block_allowed_hosts[count.index],"password")}/' /etc/iscsi/iscsid.conf",
    "sed -i 's/.*discovery\\.sendtargets\\.auth\\.authmethod \\?=.*/discovery.sendtargets.auth.authmethod = CHAP/' /etc/iscsi/iscsid.conf",
    "sed -i 's/.*discovery\\.sendtargets\\.auth\\.username \\?=.*/discovery.sendtargets.auth.username = ${lookup(local.block_allowed_hosts[count.index],"username")}/' /etc/iscsi/iscsid.conf",
    "sed -i 's/.*discovery\\.sendtargets\\.auth\\.password \\?=.*/discovery.sendtargets.auth.password = ${lookup(local.block_allowed_hosts[count.index],"password")}/' /etc/iscsi/iscsid.conf",
    "mpathconf --enable --with_multipathd y",
    "systemctl enable iscsi",
    "systemctl restart iscsi",
    "iscsiadm -m discovery -t sendtargets -p ${element(ibm_storage_block.masternode_block.*.hostname,count.index)}",
    "iscsiadm -m node --login",
    "sed -i 's/^SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config",
    "fixfiles restore /",
    "setenforce 1",
           ]
  }

}
```

So similar thing can be achieved for file storage...mount script need to be modified  accordingly
https://console.bluemix.net/docs/infrastructure/FileStorage/accessing-file-storage-linux.html#mounting-file-storage-on-linux

**Comment by hkantare** [comment]
closing the issue based on above comment.
