### ISSUE TITLE
Change of machine type in ibm_container_cluster destroys cluster

### ISSUE THREAD

**Issue by ruben-burr** [IBM-Cloud/terraform-provider-ibm#527]
Hi there,

we would like to change the machine type of our production cluster. This does though destroy the cluster and recreate it. In my opinion, this is not acceptable for production. 

### Terraform Version
terraform 0.11.7
ibm provider 0.11.2

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_cluster 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "ibm_container_cluster" "staging" {
  name            = "staging"
  datacenter      = "fra02"
  machine_type    = "u2c.2x4"
  hardware        = "dedicated"
  public_vlan_id  = "${var.public_non_prod_vlan_id}"
  private_vlan_id = "${var.private_non_prod_vlan_id}"

  kube_version = "1.12.6"

  subnet_id = ["${var.staging_private_portable_sn}", "${var.staging_public_portable_sn}"]
  no_subnet = true

  default_pool_size = 2

  region = "eu-de"
}
```

### Expected Behavior
New workers with the new machine type should be created first, then the old ones should be removed one by one (or configurable chunks) with a drain before to allow rescheduling of pods. 

### Actual Behavior
Cluster was destroyed completely and rebuild afterwards.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Change machine type
3. `terraform apply`

**Comment by Praveengostu** [comment]
Hi @ruben-burr the  machine_typeis declared with `Force-New` which basically means that any change in this field requires the resource to be destroyed and recreated. This is why when you try to change the machine-type it destroys and recreates the resource..
Ibm cloud cli or Api does not support updating the machine type.

**Comment by stevestrutt** [comment]
Hi @ruben-burr, to expand on @Praveengostu 's comment. Changing machine type is not supported by the Kubernetes service. The Terraform provider is exposing the same capabilities as implemented by the underlying CLI/API. I recommend entering an AHA request for enhancement of the K8 service.

**Comment by ruben-burr** [comment]
Hi @Praveengostu , hi @stevestrutt ,

thanks for the quick answers. In my opinion, the CLI and terraform should be different abstraction levels. For the CLI I could build tooling on top to achieve the desired behavior. This is not possible with terraform as I do not have a way to hook into the process. And what I described above should be possible with the CLI, just not in one command, but with a series of commands. 

Can you tell me where to file the enhancement request?

**Comment by ruben-burr** [comment]
Hi @Praveengostu , hi @stevestrutt ,

what are your thoughts on my comment regarding the abstraction level? I think it is very unlikely, that an enhancement request will be accepted because there is a rather simple workaround for the CLI. But there is basically no way around this in terraform.

**Comment by ruben-burr** [comment]
https://ibmcloud.ideas.aha.io/ideas/IDEA-I-2865

**Comment by Praveengostu** [comment]
Hi @ruben-burr terraform is more likely a infrastructure tool and the life cycle  is create,read, update and destroy but your idea is like a create a new resource and delete the old resource. The vice-versa is what we have now..We will recheck and post comments to the above link.

**Comment by stevestrutt** [comment]
@ruben-burr the Terraform resource lifecycle parameter of create_before_destroy
lifecycle {
    create_before_destroy = true
  }
may do what you require. The default Terraform action is delete before create. This option exists to implement the type of capability you are asking for to build the new servers before deleting the old servers. Though is was originally intended for VMs.  The question I do not know the answer is to whether the implementation of cluster create will allow expansion of the existing cluster with the new hardware. The action desired is to expand the pool size to 4 with the new servers and then reduce back to two. 
  Can you try it?

**Comment by davetropeano** [comment]
@ruben-burr If I am not mistaken you cannot change a worker node type in the same pool within IKS. Given that we won't directly support changing a worker type within a pool in the provider.

With what @stevestrutt said above would creating a new pool with a different type of worker node be appropriate?

**Comment by ruben-burr** [comment]
@stevestrutt just tried the create_before_destroy in the example given above. But that fails with "A cluster with the same name already exists. Choose another name." which is kind of obvious, as a new cluster with the given name cannot be created, before the old one is deleted.

**Comment by stevestrutt** [comment]
@ruben-burr You're a right, kind of obvious really. Lifecycle applies to a 'set' of cluster objects. Creating a new cluster before deleting the old. This would work if the pool workers were a distinct TF resource under the TF cluster resource when create_before_delete could be applied to workers. Virtually all parameters on the cluster resource have ForceNew=true set, which means any change will cause it to be all deleted and rebuilt. 
   @davetropeano This is going to require rework of the TF provider cluster resource. The whole lifecycle of how a cluster is upgraded to the latest hardware needs to be thought through.

**Comment by hkantare** [comment]
As stated above one solution would be 
1) first creating a new pool with a different machine_type
2) Remove the old worker pool.
Can you share us simple workaround for the CLI how you are able to achieve this ?

**Comment by hkantare** [comment]
closing the issue due to inactivity
