### ISSUE TITLE
ibm_database example should list the required `service` parameter.

### ISSUE THREAD

**Issue by ashishth09** [IBM-Cloud/terraform-provider-ibm#528]
Version: 0.15.0

Running the example at https://ibm-cloud.github.io/tf-ibm-docs/v0.15.0/r/database.html gives the error
 
"service": required field is not set

**Comment by hkantare** [comment]
Example need to be updated with service attribute..We will do it

**Comment by hkantare** [comment]
Fixed in v0.16.0
https://ibm-cloud.github.io/tf-ibm-docs/v0.16.0/r/database.html

**Comment by hkantare** [comment]
closing the issue
