### ISSUE TITLE
Broken Link in Docu

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#529]
The Documentation of the IBM Ressource Groups (https://ibm-cloud.github.io/tf-ibm-docs/v0.15.0/r/resource_group.html) refers to a broken link in the following line:
...
Argument Reference:
...
quota_id - (Required, string) The id of the quota. You can **_refer to a quota by name using a data source._** 

The Link refers to: 
https://ibm-cloud.github.io/v0.15.0/d/resource_quota.html

But it should refer to?!
https://ibm-cloud.github.io/tf-ibm-docs/v0.15.0/d/resource_quota.html

**Comment by Praveengostu** [comment]
The quota id is removed in version 0.16.0 https://ibm-cloud.github.io/tf-ibm-docs/v0.16.0/r/resource_group.html
