### ISSUE TITLE
Documentation for `ibm_scc_profile` is very confusing

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#5290]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_scc_profile

### Description

Would it possible to update the documentation for `ibm_scc_profile` so it is clear on how to use it. The current [example usage](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_profile#example-usage) is extremely hard to understand, and to be honest I think the documentation has exposed too many inputs. Things are not even relevant when creating a profile, such as `control_category`, `control_parent`, `control_description` etc. When creating a custom profile, you need to specify a control from an existing control library. So I would expect the usage to be something much more simple like:

```hcl
resource "ibm_scc_profile" "scc_profile" {
  instance_id         = "00000000-1111-2222-3333-444444444444"
  profile_description = "some profile descrption"
  profile_name        = "some profile name"
  profile_type        = "custom"
  profile_version     = "1.0.0"
  controls {
        control_library_id = "e98a56ff-dc24-41d4-9875-1e188e2da6cd"
        control_id         = "5C453578-E9A1-421E-AD0F-C6AFCDD67CCF"
  }
  default_parameters {
        assessment_type = "assessment_type"
        assessment_id = "assessment_id"
        parameter_name = "parameter_name"
        parameter_default_value = "parameter_default_value"
        parameter_display_name = "parameter_display_name"
        parameter_type = "string"
  }
}
```

--->
### References

* #0000

**Comment by ocofaigh** [comment]
Please note that the `profile_version` input seems to be missing from the docs. Link to the field but not mentioned in the docs: https://github.com/IBM-Cloud/terraform-provider-ibm/blob/ddfaf6023adb1a9c55b3d909ac83cbf8dc7a0ee8/ibm/service/scc/resource_ibm_scc_profile.go#L267

**Comment by tyao117** [comment]
@ocofaigh im working on updating the documentation. 

The current example gives very granular detail on what can be done to set a profile. Are you preferring a more basic example rather than a very verbose example?
