### ISSUE TITLE
`profile_version` parameter in `ibm_scc_profile` is not working as expected

### ISSUE THREAD

**Issue by jor2** [IBM-Cloud/terraform-provider-ibm#5292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_scc_profile

### Terraform Configuration Files

Example can be found in this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-scc/pull/58/files).

### Debug Output

````
2024-04-22T11:00:44.248+0100 [WARN]  Provider "provider[\"registry.terraform.io/ibm-cloud/ibm\"]" produced an unexpected new value for module.create_scc_profile.ibm_scc_profile.scc_profile_instance, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .profile_version: was cty.StringVal("1.0.0"), but now cty.StringVal("0.0.0")
      - .controls: block count changed from 807 to 800
module.create_scc_profile.ibm_scc_profile.scc_profile_instance: Creation complete after 16s [id=c01c4e44-0d27-43a7-855e-f491201e3074/175a0217-d44a-4260-a9c7-917428dbddf2]
````

### Expected Behavior

The `profile_version` should be set to whatever value I set it to in my terraform code.

### Actual Behavior

I specified the `profile_version` as `1.0.0` in my terraform code, but it does not take effect, and still shows as version `0.0.0` on the UI.

### Steps to Reproduce

Run this [example](https://github.com/terraform-ibm-modules/terraform-ibm-scc/pull/58/files#diff-07f337e38ed1996f30ee4f04357ab23318c254cb606aaf4745d564cbd546722d).

1. `terraform apply`

### References

* #0000

**Comment by jor2** [comment]
@ocofaigh

**Comment by tyao117** [comment]
ProfileVersion was not supported by the SCC Go SDK. Updating Release to support this.

**Comment by ocofaigh** [comment]
PR: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5332

**Comment by jor2** [comment]
@tyao117 @ujjwal-ibm I'm still receiving this error in release `v1.65.1`.
<img width="1549" alt="Screenshot 2024-05-23 at 12 49 16" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/22322183/f4b6ec54-a474-4e09-aee6-1988414d7abe">

Run the `complete` [example](https://github.com/terraform-ibm-modules/terraform-ibm-scc/pull/58/files#diff-07f337e38ed1996f30ee4f04357ab23318c254cb606aaf4745d564cbd546722d) and set profile version.v
