### ISSUE TITLE
Feature Request: Support for the vRouter 5600

### ISSUE THREAD

**Issue by greyhoundforty** [IBM-Cloud/terraform-provider-ibm#53]
I have a few customers that are interested in using Terraform to start unifying their infrastructure. This is especially important when they want to re-create an existing set up in a new Datacenter. One of their major asks is IBM Cloud Provider support for provisioning the vRouter 5600. 

Ideally this would consist of: 
- Ordering the device 
- Associating the appropriate VLANs
- Support for post install configuration (Either via the built in remote-exec terraform feature or utilizing the vRouter REST/cli API features)

**Comment by favrecr** [comment]
Initial work for this has been created here:
https://github.com/IBM-Bluemix/terraform-provider-ibm/pull/74

**Comment by ashishth09** [comment]
Closed in 86cbfbc8657d9323cf197e49ebe7b979bebb6dbd
