### ISSUE TITLE
wrong example in ibm_database documentation

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#530]
The example you provided in the ibm_database documentation (https://ibm-cloud.github.io/tf-ibm-docs/v0.15.0/r/database.html) didn't outline, that you need the required service argument to describe the database service. 

This means that the example you provided won't work.

**Comment by hkantare** [comment]
yes its know issue we already have issue open
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/528. In next release it will be fixed

**Comment by hkantare** [comment]
Fixed in v0.16.0
https://ibm-cloud.github.io/tf-ibm-docs/v0.16.0/r/database.html
