### ISSUE TITLE
Where to get ids for baremetal order

### ISSUE THREAD

**Issue by sasadangelo** [IBM-Cloud/terraform-provider-ibm#531]
Hi,

I read issues are only for bug and feature request. I joined the terraform community but I think my question is specific for this provider. I want to automate bare metal order with SL. The only doc I was able to find is this:
https://ibm-cloud.github.io/tf-ibm-docs/

I am new with Terraform and I took the baremetal.txt file from another issue on this git repository. I want to customize it to use my data. I want to order, for example:

- Dual Intel Xeon Silver 4110 16 cores 2.1 GHz
- 10 960 Gb SSD Drive configure in two groups (at the end two HD are visible) RAID 6 with one Hostspare each
- Ubuntu 16 Minimal
-500 Gb Bandwidth Allotment
- Network 10 Gbs Public & Private Redundant
- Monitor Basic Package
- Power Supply Redundant
- VLAN use the default

I understand I have to fill the fields and then give commands:

terraform init
terraform plan
terraform apply

but where I get IDs? It seems they are documented nowhere. For example:
package_key_name = "DUAL_INTEL_XEON_PROCESSOR_SCALABLE_FAMILY_4_DRIVES"

where I get the ID for the CPU I want to order? In general, where I found all possible ID used by softlayers for baremetals?

The same question for:
process_key_name = "INTEL_INTEL_XEON_6140_2_30"
os_key_name  = "OS_WINDOWS_2012_R2_FULL_STD_64_BIT"

It's not clear to me where all these IDs are documented.
Thanks

[baremetal.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/2975452/baremetal.txt)

**Comment by stevestrutt** [comment]
Hi Salvatore, to get started with Terraform there are lots of resources on the web. There is a great book, `Terraform up and running` you can find this on IBM’s Safari books account https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/IT%20Content%20Availability/page/Safari%20Books%20Online   at https://learning.oreilly.com/library/view/terraform-up-and/9781491977071/   

I see Yevgeniy also has a 3 hour video introduction on Safari books.  In terms of getting started with IBM Terraform, have a look at the Terraform/Ansible tutorials I’ve written on CloudDocs. The Terraform part of this should get you started on the IBM platform. The initial tutorial is all Softlayer IaaS. 

Softlayer IaaS parameters are all documented online, but in various places. One place is to look is the command line using  `ibmcloud sl hardware create-options`
The online docs have a lot of detail: https://ibm-cloud.github.io/tf-ibm-docs/v0.15.0/r/compute_bare_metal.html 
Also the IBM Cloud Docs: https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-about-bm#about

**Comment by sasadangelo** [comment]
Hi,

As a newbie in Terraform it is ok to give a look to the general doc on Terraform, however, I already read some stuff. I have a specific requirement to address, I am an IBM employee in Rome and I already have a look at this link https://ibm-cloud.github.io/tf-ibm-docs/v0.15.0/r/compute_bare_metal.html. The problem is that this link shows the only specific example, but do not tell you all possible ids. For example, if you look here:
    package_key_name = "DUAL_E52600_V4_12_DRIVES"
    process_key_name = "INTEL_INTEL_XEON_E52620_V4_2_10"

what is, for example, the id to order Dual Intel Xeon Silver 4110 16 cores 2.1 GHz? I can order from SL console two types of Ubuntu 16: normal and minimal, is UBUNTU_16_64 ok for a minimal install?

Above I mentioned, as an example, a machine I want to order with Terraform and I am unable to get it. Regarding "ibmcloud sl hardware create-options" as IBM employee I cannot use IBM console for our staging/production environment, I can only access them via SL console.

How I can address my issue?

**Comment by hkantare** [comment]
For your requirement Dual Intel Xeon Silver 4110 16 cores 2.1 GHz you package key name should be 
2U_DUAL_INTEL_XEON_PROCESSOR_SCALABLE_FAMILY_12_DRIVES
https://api.softlayer.com/rest/v3/SoftLayer_Product_Package/getAllObjects?objectFilter={%22type%22:{%22keyName%22:{%22operation%22:%22BARE_METAL_CPU%22}}} once you retrieve the package ID (839) 
You can retrive the IDS for os and process 
https://api.softlayer.com/rest/v3/SoftLayer_Product_Package/839/getItems?objectMask=mask[prices[id,categories[id,name,categoryCode],capacityRestrictionType,capacityRestrictionMinimum,capacityRestrictionMaximum,locationGroupId]]

For minimal os
os_key_name=OS_UBUNTU_16_04_LTS_XENIAL_XERUS_MINIMAL_64_BIT
process_key_name=INTEL_INTEL_XEON_4110_2_10

**Comment by sasadangelo** [comment]
Hi,

The command "ibmcloud sl hardware create-options" is what I need. As CPU I see the following output:

Size                                      Value   
Gold 5120 384GB 2X960GB SSD SED RAID1     DGOLD_5120_384GB_2X960GB_SSD_SED_RAID1   
Gold 5120 96GB 1X960GB SSD SED NoRAID     DGOLD_5120_96GB_1X960GB_SSD_SED_NORAID   
Gold 6140 384GB 4X960GB SSD SED RAID 10   DGOLD_6140_384GB_4X960GB_SSD_SED_RAID_10   
Silver 4110 96GB 1X960GB SSD SED NoRAID   DSILVER_4110_96GB_1X960GB_SSD_SED_NORAID   
S1270v6 16GB 1X2TB SATA NORAID            S1270V6_16GB_1X2TB_SATA_NORAID   
S1270v6 32GB 1X2TB SATA NORAID            S1270V6_32GB_1X2TB_SATA_NORAID

Now DSILVER_4110_96GB_1X960GB_SSD_SED_NORAID  seems what I need. The problem is that when I order it through SL UI (I am an IBM employee) I remove the default HDD and I add 10 SSD 960 GB disks configured as 2 RAID 6 disks with one HotSpare each.

Now Terraform allows me to define disks configuration. I can check examples to understand how to do it, however my doubt is how I tell to SL to remove the default disk associated by default to the processor  DSILVER_4110_96GB_1X960GB_SSD_SED_NORAID?

Moreover, as operating system I have the following options:
Ubuntu 14.04-32                                                             UBUNTU_14_32   
Ubuntu 14.04-64                                                             UBUNTU_14_64   
Ubuntu 16.04-64                                                             UBUNTU_16_64   
Ubuntu 18.04.1-64                                                           UBUNTU_18_64

However, if I go through the SL UI I can have two types of Ubuntu 16 OS: Normal and Minimal. Why minimal is not mentioned in the id list?

Always through SL UI I am able to select Monitor Basic package and Power Supply redundancy that are not available here. How  can I add them to my order?

Finally, is there a way to test my script without send a real order just to verify that everything is ok?

**Comment by hkantare** [comment]
For your requirement Dual Intel Xeon Silver 4110 16 cores 2.1 GHz you package key name should be
2U_DUAL_INTEL_XEON_PROCESSOR_SCALABLE_FAMILY_12_DRIVES
https://api.softlayer.com/rest/v3/SoftLayer_Product_Package/getAllObjects?objectFilter={%22type%22:{%22keyName%22:{%22operation%22:%22BARE_METAL_CPU%22}}} once you retrieve the package ID (839)
You can retrive the IDS for os and process
https://api.softlayer.com/rest/v3/SoftLayer_Product_Package/839/getItems?objectMask=mask[prices[id,categories[id,name,categoryCode],capacityRestrictionType,capacityRestrictionMinimum,capacityRestrictionMaximum,locationGroupId]]

For minimal os
os_key_name=OS_UBUNTU_16_04_LTS_XENIAL_XERUS_MINIMAL_64_BIT
process_key_name=INTEL_INTEL_XEON_4110_2_10
disk_key_names = [HARD_DRIVE_960GB_SSD_SED_5DWPD, HARD_DRIVE_960GB_SSD_SED_5DWPD]
redundant_power_supply = true

**Comment by stevestrutt** [comment]
Hi Salvatore, if I understand correctly you only have access to a SoftLayer IaaS account which is not linked to BX. You can still use the Softlayer CLI with this. SLCLI, this gives you access to all the SL IaaS commands, including bare metal. 

The questions you are asking are more appropriate for a Softlayer forum where there is more expertise in SL ordering. bx/ibmcloud  IaaS commands are the same as for the slcli. 

`slcli hardware create-options` is a summary list of options. The full list requires an understanding of SL ordering and packages. These will be accessed using `slcli order` commands. 
NAME:
   bx sl order - Gen1 infrastructure Orders
USAGE:
   bx sl order command [arguments...] [command options]

COMMANDS:
   category-list       List the categories of a package
   item-list           List package items used for ordering
   package-list        List packages that can be ordered via the placeOrder API
   package-locations   List Datacenters a package can be ordered in
   place               Place or verify an order
   place-quote         Place a quote
   preset-list         List package presets
   help, h             Show help

I think the specific command you are looking for to retrieve all the bare metal options is:
`slcli order item-list BARE_METAL_INSTANCE`

**Comment by hkantare** [comment]
closing the issue.
