### ISSUE TITLE
provider crash while destroying

### ISSUE THREAD

**Issue by erotallgeese** [IBM-Cloud/terraform-provider-ibm#537]
Hi there,

I'm using:
Terraform v0.11.11
IBM Cloud Provider version 0.14.1

I has opened an [issue 536](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/536).
After we finish our task, we destroy those VMs today. But it seems like it cause terraform-provider-ibm crash.

![圖片](https://user-images.githubusercontent.com/10495245/54739850-77788000-4bf4-11e9-9927-c2f199825c59.png)
 
I also check those VMs in portal site, and they are still running.

Here is its [crash log](https://gist.github.com/erotallgeese/b4a33baa2ac2e8cca30662e423905c06)
Here is its [terraform output](https://gist.github.com/erotallgeese/b9df9c6fb2791034e3e9169f48f0050d)

Please help.

**Comment by hkantare** [comment]
We fixed this as part of v0.15.0 release

https://github.com/IBM-Cloud/terraform-provider-ibm/commit/5fcbd554ae6b4a40bc29f0f58590828b89349d5a#diff-e4b220657319756663dd781aea77b4d0

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.15.0 should have the fix

**Comment by hkantare** [comment]
closing the issue..
