### ISSUE TITLE
"unexpected EOF" upon creating VLAN

### ISSUE THREAD

**Issue by miyamotoh** [IBM-Cloud/terraform-provider-ibm#539]
### Terraform Version
v0.11.11

### Affected Resource(s)
- ibm_network_vlan

### Terraform Configuration Files
```hcl
resource "ibm_network_vlan" "test_vlan_public" {
  name            = "test-pub-vlan"
  datacenter      = "dal13"
  type            = "PUBLIC"
}
```
(tested with 3 different datacenters, and PRIVATE as well, no joy)

### Panic Output
https://gist.github.com/miyamotoh/fbd382596f150b1f88bb77f92f1bf1d2

### Expected Behavior
Create the requested VLAN and exit without error

### Actual Behavior
Crash with "unexpected EOF" with no VLAN created

### Steps to Reproduce
1. `terraform apply` with proper API creds via `-var`

**Comment by hkantare** [comment]
Yesterday there was some issue while creating the vlan...The vlan was taking a long time to get created. Today it working fine anyways from Terraform end we fixed to throw a valid error ...instead of EOF

**Comment by miyamotoh** [comment]
Thanks for the quick response. I confirm it's been working fine since. +1 for better error!
