### ISSUE TITLE
pi_instance not consistent on reapply : version 1.66.0

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#5414]
With the new provider version, fault attribute was introduced. This causes terraform on reapply to change its attribute.

Initially fault is not present , on apply again to check the consistency , it shows that the resource below needs an update

```
 ~ resource "ibm_pi_instance" "instance" {
      + fault                          = (known after apply)
        id                             = "fbc85a58-f185-4b95-93e8-a12e77b8428f/665b31bb-6b31-48bd-a2e2-82fab7946a5e"
        # (32 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

@alexhemard @hkantare @yussufsh This needs to be fixed.

**Comment by surajsbharadwaj** [comment]
@alexhemard is this merged to main now ?

**Comment by yussufsh** [comment]
@ismirlia

**Comment by surajsbharadwaj** [comment]
It works. Can be closed @yussufsh
