### ISSUE TITLE
activity_tracking and metrics_monitoring  schemas seems out of date for `ibm_cos_bucket`

### ISSUE THREAD

**Issue by ocofaigh** [IBM-Cloud/terraform-provider-ibm#5425]
The [activity_tracking](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cos_bucket#activity_tracking) option for `ibm_cos_bucket` has the following nested schema:

```
activity_tracking {
    read_data_events     = true
    write_data_events    = true
    activity_tracker_crn = ibm_resource_instance.activity_tracker.id
  }
```

However it would seem that this is out of date. When you provision a COS bucket in the UI, I see two main differences:
1. UI has a third option `Management Data Events` which seems to be missing from the terraform schema
2. `activity_tracker_crn` no longer seems to be a required value to pass

![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/29608224/d9021e73-b2a0-4345-9fe7-c35bed24c839)

The same goes for the `metrics_monitoring` schema, it seems the UI does not ask for an instance ID
![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/29608224/1d64d3dc-c2e9-4987-b62e-78ffb37065ca)

Is the provider out of date here?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_cos_bucket

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ocofaigh** [comment]
@IBM-diksha is this something you can help confirm please?

**Comment by IBM-diksha** [comment]
Hi @ocofaigh We have updated the activity_tracking and metrics_monitoring schema to include management events and making activity_tracking_crn and metrics_monitoring_crn optional. This change is currently in the latest beta release- v1.67.0-beta, You can switch to the beta version for this one.
Thank you.

**Comment by IBM-diksha** [comment]
Closing this issue as  this has been delivered in the latest version - v1.67.0.
