### ISSUE TITLE
Datasource ibm_catalog_cm by Private Catalog Name

### ISSUE THREAD

**Issue by pauljegouic** [IBM-Cloud/terraform-provider-ibm#5434]
Hello, 

I think it would be awesome to have the ability to datasource `ibm_catalog_cm` (https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/cm_catalog) by name instead of by ID.

**Comment by benbuchanan** [comment]
@pauljegouic @hkantare Just opened a PR to allow catalog data source creation with ID or label https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5439
