### ISSUE TITLE
ibm_resource_access_tag name is not consistent

### ISSUE THREAD

**Issue by mkrudele** [IBM-Cloud/terraform-provider-ibm#5522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_resource_access_tag

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Actual Behavior

It has recently been added the possibility to create an access management tag, which is good. However, the name is inconsistent in my opinion. Let me explain why:  
There is the `ibm_resource_tag` Terraform resource that handles tag attachment with a resource. So, it models the relation between an user or access tag with a resource.
The new resource `ibm_resource_access_tag` is not modelling a relation between an access tag and a resource. Instead, it models an access tag. So, its name should have been `ibm_iam_access_tag`, as I suggested some time ago https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2608#issuecomment-1019139417.  
Who reviewed the documentation and the consistency? Was the Global Search Tagging (GhoST) team involved in the development of this new feature? GhoST is the component in the cloud that owns tagging.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by JunliWang** [comment]
as an user, I was confused about how to attach an access tag to an instance, thought `ibm_resource_access_tag` should work in the same way as `ibm_resource_tag`, but actually `ibm_resource_access_tag` does not have `resource_id` to specify the resource to attach to. it is to create access tag itself.
I would vote for the rename to avoid such confusion.

**Comment by addison-martin1** [comment]
Hi, I'm a content designer and I was asked to review this name change 🙂

For this change: `ibm_resource_access_tag` —> `ibm_iam_access_tag`

Would these be the steps to create and attach an access management tag?
1. Use `ibm_iam_access_tag` to create the access management tag
2. Use `ibm_resource_tag` to attach the access management tag to a resource

Ultimately I think this renaming makes sense 👍

I think we would need to update our documentation here: https://cloud.ibm.com/docs/account?topic=account-tag&interface=terraform#create-access-terraform — who can I contact to review this and confirm the updates needed?

**Comment by mkrudele** [comment]
@addison-martin1 You can contact me. However before updating that documentation, we need to make the code changes and update the Terraform documentation here https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/resource_access_tag.  
My team can do the change. Let's wait for the IAM team feedback before moving on.

**Comment by veetil09** [comment]
I think this rename makes sense to avoid the confusion for the end user.
