### ISSUE TITLE
Create K8s Cluster in jp-tok failed

### ISSUE THREAD

**Issue by ArielZhang** [IBM-Cloud/terraform-provider-ibm#553]
IBM Terraform Provider v0.15.1

* ibm_container_cluster.cluster: 1 error(s) occurred:

* ibm_container_cluster.cluster: Error occured while configuring MCCP service: "Post https://login.jp-tok.bluemix.net/UAALoginServerWAR/oauth/token: dial tcp: lookup login.jp-tok.bluemix.net on 168.63.129.16:53: no such host"

seems the url of https://login.jp-tok.bluemix.net/UAALoginServerWAR/oauth/token is invalid.

**Comment by ArielZhang** [comment]
tried v0.16.0, the same error

* ibm_container_cluster.cluster: 1 error(s) occurred:

* ibm_container_cluster.cluster: Error occured while configuring MCCP service: "Post https://login.jp-tok.bluemix.net/UAALoginServerWAR/oauth/token: dial tcp: lookup login.jp-tok.bluemix.net on 192.168.65.1:53: no such host"

**Comment by hkantare** [comment]
Can you please share the sample configuration

**Comment by hkantare** [comment]
closing the issue no response from long timw
