### ISSUE TITLE
ibm_scc_profile_attachment does not update attachment parameters

### ISSUE THREAD

**Issue by pauljegouic** [IBM-Cloud/terraform-provider-ibm#5535]
Hello there,

Used Terraform Provider versions:
```
- terraform.io/builtin/terraform is built in to Terraform
- Reusing previous version of ibm-cloud/ibm from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/time from the dependency lock file
- Using previously-installed hashicorp/random v3.6.2
- Using previously-installed hashicorp/time v0.12.0
- Using previously-installed ibm-cloud/ibm v1.67.1
```

When using : `ibm_scc_profile_attachment` it successfully does the creation, for the attachment parameters, but does not update the attachment_parameters value.

<img width="797" alt="image" src="https://github.com/user-attachments/assets/0c0386b7-d3b0-412e-92cb-7d1face9989b">

Expected: when I change a value of the attachment parameter, the change is applied to the attachment.

@hkantare

**Comment by ocofaigh** [comment]
cc @tyao117

**Comment by sailajaperumalla** [comment]
SCC reference ticket : https://github.ibm.com/project-fortress/pm/issues/17605

**Comment by tyao117** [comment]
@ocofaigh and @pauljegouic won't be able to start work on this issue until August 2nd.

**Comment by pauljegouic** [comment]
That's ok from my prospective.

**Comment by tyao117** [comment]
I believe to have found the source the problem. The function [hashAttachmentParameters](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/7ac9681df192c205f5b6c8eb2cbd7419ae9692a0/ibm/service/scc/resource_ibm_scc_profile_attachment.go#L239).  

@pauljegouic you can verify the link is the source of the issue using the env var TF_LOG. You will not see a PUT request.

**Comment by pauljegouic** [comment]
Not sure what you want me to do. Can't you do this debug on your side ?  @tyao117 

I can share the logs if needed on Slack, but not here. As you mentionned, there's not PUT request in my logs.

**Comment by tyao117** [comment]
Yes, i am doing debugging on my side, but i need to confirm that you are experiencing the same behavior. Delivering a fix that you are not experiencing would not be productive, would it?

Thanks for confirming the PUT request not being in the logs. The behavior aligns with what I am seeing as well.
