### ISSUE TITLE
cannot convert returned value to ClusterInfo with version 1.68.0

### ISSUE THREAD

**Issue by lionelmace** [IBM-Cloud/terraform-provider-ibm#5548]
I'm facing the following error with the tf provider version `1.68.0`. It works with 1.67.1

I use this script to test it
https://github.com/lionelmace/ibm-cloud-native/blob/main/terraform/container-openshift.tf

```
Error: [ERROR] cannot convert returned value to ClusterInfo
with ibm_container_vpc_cluster.roks_cluster
on container-openshift.tf line 137, in resource "ibm_container_vpc_cluster" "roks_cluster":
resource "ibm_container_vpc_cluster" "roks_cluster" {
---
id: terraform-40a3a1fe
summary: '[ERROR] cannot convert returned value to ClusterInfo'
severity: error
resource: ibm_container_vpc_cluster
operation: create
component:
  name: github.com/IBM-Cloud/terraform-provider-ibm
  version: 1.68.0
---
```

**Comment by z0za** [comment]
hey - thank you for reporting the issue. it looks like the `OneWorkerNodeReady` `wait_till` option has a bug, we have raised a PR to fix it. until the fix is ready, you can use the `normal` option as a workaround or use the previous provider version. sorry for the inconvenience.
