### ISSUE TITLE
IBM Cloud provider showing unversioned

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#557]
Hi there,

When I run `terraform --version` as see IBM Cloud provider as unversioned 

 Why is IBM Cloud provider version showing as unversioned?
<img width="714" alt="Screenshot 2019-04-22 at 11 12 07 AM" src="https://user-images.githubusercontent.com/6552440/56484963-9f0e8100-64ef-11e9-86d1-01227141bae9.png">

### Terraform Version
v0.11.3

### Affected Resource(s)
Not sure which version of provider I am using with this error

**Comment by Praveengostu** [comment]
@VidyasagarMSC terraform provider version you can check by running the `terraform init`. If the binary name is changed it should display the version of the provider which you are using
```Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.ibm: version = "~> 0.16"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
In the above it clearly shows the terraform version is v0.16

**Comment by Praveengostu** [comment]
@VidyasagarMSC Can we close this?
