### ISSUE TITLE
required attribute "public_key" is maked as optional in ibm_compute_ssh_key docs

### ISSUE THREAD

**Issue by pfeifferj** [IBM-Cloud/terraform-provider-ibm#5575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_compute_ssh_key

### Description

the docs state that only `label` is required and also feature this as the minimal example:

```
data "ibm_compute_ssh_key" "public_key" {
    label = "Terraform Public Key"
}
```

however, running tf validate against the example shows that `public_key` is also required

```
╷
│ Error: Missing required argument
│ 
│   on main.tf line 46, in resource "ibm_compute_ssh_key" "k8s_ssh_key":
│   46: resource "ibm_compute_ssh_key" "k8s_ssh_key" {
│ 
│ The argument "public_key" is required, but no definition was found.
╵
```

the docs should be corrected to also list `public_key` as required

### References

* https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/compute_ssh_key

**Comment by ujjwal-ibm** [comment]
seems like the error is in resource and you are looking at the documents for datasource

On this page, it is mentioned that public_key is required
>[public_key](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/compute_ssh_key#public_key)- (Required, String) The public SSH key.

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/compute_ssh_key#public_key

**Comment by pfeifferj** [comment]
you're right! sorry for the mixup
