### ISSUE TITLE
ibm_container_bind_service Fails with an error

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#558]
Hi there,

Container bind service failing with the below error 

> ibm_container_bind_service.bind_database: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"4cb61a04f483aa78-SIN","code":"Ea753","description":"The default role (Writer) could not be used to create a resource key for this instance. Specify a different role to use for the resource key and try again. Or, specify an existing resource key to bind the service.","type":"BadRequest","recoveryCLI":"To list available roles for the service, run 'ibmcloud iam roles --service \u003cservice_name\u003e' and choose one of the service roles. The service name is the name of the service in the catalog, 'ibmcloud catalog search'. To list existing service keys, for resources run 'ibmcloud resource service-keys --instance-name \u003cservice_instance\u003e' or for Cloud Foundry run 'ibmcloud cf service-keys \u003cservice_instance\u003e'."}

### Terraform Version
v 0.11.3
Provider: v0.16.0

### Affected Resource(s)
ibm_container_bind_service

### Expected Behavior
Binding should be successful

### Actual Behavior
Binding fails with key dependency

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a Kubernetes cluster
2. Create an IAM service 
3. Try binding the service to the cluster through `terraform apply` and it fails with an error

**Comment by Praveengostu** [comment]
HI @VidyasagarMSC we are working on enhancing the cluster bind resource to accept values for  key and role parameters. Thanks

**Comment by Praveengostu** [comment]
@VidyasagarMSC The issue is fixed and available in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.16.1

**Comment by VidyasagarMSC** [comment]
Thanks @Praveengostu
