### ISSUE TITLE
BUG: 1.69.0 panic when attempting to update ibm_resource_instance

### ISSUE THREAD

**Issue by willholley** [IBM-Cloud/terraform-provider-ibm#5618]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform 1.7.5
IBM Provider 1.69.0

### Affected Resource(s)

* ibm_resource_instance

### Terraform Configuration Files

```hcl
resource "ibm_resource_instance" "cloud_object_storage_dsx" {
  name              = "cloud-object-storage-dsx"
  service           = "cloud-object-storage"
  plan              = "standard"
  location          = "global"
  resource_group_id = module.resource_groups.resource_group_ids["default"]
}
```

### Panic Output

```
ibm_resource_instance.cloud_object_storage_dsx: Modifying... [id=crn:v1:bluemix:public:cloud-object-storage:global:a/xxxx:7219eeed-c4c9-406d-8b1f-acc8a784e510::]

ibm_resource_instance.cloud_object_storage_dsx: Still modifying... [id=crn:v1:bluemix:public:cloud-object-stor...7219eeed-c4c9-406d-8b1f-acc8a784e510::, 10s elapsed]

╷

│ Error: Request cancelled

│ 

│   with ibm_resource_instance.cloud_object_storage_dsx,

│   on cos.tf line 5, in resource "ibm_resource_instance" "cloud_object_storage_dsx":

│    5: resource "ibm_resource_instance" "cloud_object_storage_dsx" {

│ 

│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.

╵


Stack trace from the terraform-provider-ibm_v1.69.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x250cc2b]
goroutine 162 [running]:
github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/resourcecontroller.waitForResourceInstanceUpdate.func1()
	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/resourcecontroller/resource_ibm_resource_instance.go:904 +0x2eb

github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext.func1()
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:113 +0x1b0
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext in goroutine 111
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:86 +0x23b

Error: The terraform-provider-ibm_v1.69.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Expected Behavior

Resource should have updated.

### Actual Behavior

The plugin crashed.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5602 looks like a related change.

### References

* #0000

**Comment by hkantare** [comment]
@willholley Can you share complete steps . Does creation and update is with same binary?

**Comment by willholley** [comment]
our CI which runs terraform is quite complex - I haven't attempted to create a minimal reproduction yet.

It seems to be always failing on `cos` service instances and when updating `last_operation`.

The resources were created long ago - some are 3/4 years old and some a few months old.

**Comment by willholley** [comment]
if it's useful, we upgraded from provider version `1.66.0`

**Comment by hkantare** [comment]
May be old instances is missing to have (LastOperation) 
instance.LastOperation.Async 
@willholley can we have some nil check before accessing

**Comment by willholley** [comment]
Yes, I think that's right. Looking at https://github.com/IBM/platform-services-go-sdk/blob/main/resourcecontrollerv2/resource_controller_v2.go#L4581C2-L4581C15, LastOperation can be nil

**Comment by JunliWang** [comment]
both LastOperation and LastOperation.Async could be nil, 
adding this check in above PR.
