### ISSUE TITLE
Provider checks for cluster creation even after cluster creation is completed

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#562]
Hi there,

Using `v0.16.1` version of the provider, I tried creating a cluster. Though the cluster state is changed to `normal`, the provider continues checking for the status 

> ibm_container_cluster.cluster: Still creating... (52m41s elapsed)
> 2019-04-24T16:26:13.390+0530 [DEBUG] plugin.terraform-provider-ibm_v0.16.1: 2019/04/24 16:26:13 [TRACE] Waiting 10s before next try

### Terraform Version
0.11.3

### Affected Resource(s)
Please list the resources as a list, for example:

- ibm_container_cluster.cluster

### Expected Behavior
ibm_container_cluster.cluster should complete and move to the next object in the tf file.

### Actual Behavior
The check continues for ever

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. terraform plan
3. terraform apply

**Comment by VidyasagarMSC** [comment]
Failed with the error : ibm_container_cluster.cluster: Error waiting for initializing ingress hostname and secret: Error retrieving cluster: Request failed with status code: 522, ServerErrorResponse

**Comment by Praveengostu** [comment]
@VidyasagarMSC will forward this to ingress team

**Comment by koundinya-ac** [comment]
@VidyasagarMSC did you do a `ibmcloud cs cluster-get  <cluster-name>` to check if ingress subdomain and secret has been assigned or not for the cluster, because sometimes terraform waits for ingress cfg to be assigned

**Comment by VidyasagarMSC** [comment]
@koundinya-ac I checked and wasn't assigned. The `terraform apply` failed after running for 90 minutes. Have to destroy and re-apply to make it work.

**Comment by hkantare** [comment]
closing the issue
