### ISSUE TITLE
Add Read Replicas and Service Endpoints Support

### ISSUE THREAD

**Issue by jdmintz** [IBM-Cloud/terraform-provider-ibm#566]
All ICD services now support Service Endpoints for Private and Public connections to the database, this should be supported in Terraform. 

Databases for PostgreSQL also supports read replicas, this should also be supported.

**Comment by hkantare** [comment]
Availble in release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.19.0 and above
