### ISSUE TITLE
Feature request: Add kind for Go (Golang)

### ISSUE THREAD

**Issue by matthewrankin** [IBM-Cloud/terraform-provider-ibm#568]
### Summary

Should the kind `go:1.11` be added to `ibm_function_action` resource?

### Terraform Version

```bash
$ terraform -v
Terraform v0.11.13
+ provider.ibm v0.16.1
```

### Affected Resource(s)

- ibm_function_action

### Terraform Configuration Files
```hcl
...
resource "ibm_function_action" "hello" {
  name = "helloGo"

  exec = {
    kind = "go:1.11"
    code = "${file("hello.go")}"
  }
}
...
```

### Expected Behavior
What should have happened?

Create a Go-based IBM Cloud function using Terraform.

### Actual Behavior
What actually happened?

Received error that `go:1.11` is an invalid kind.

### Steps to Reproduce

```bash
$ terraform plan

Error: ibm_function_action.hello: "exec.0.kind" ("go:1.11") Invalid kind is provided.Supported list
of kinds of actions are (["php:7.1" "nodejs:8" "swift:3" "nodejs" "blackbox" "java" "sequence"
"nodejs:6" "python:3" "python" "python:2" "swift" "swift:3.1.1"])
```

### Important Factoids

N/A

### References

None found.

**Comment by hkantare** [comment]
Fixed in latest release..v0.17.1
