### ISSUE TITLE
ibm_database should work with the minimum configuration of 0.5 CPU & 4GB RAM 

### ISSUE THREAD

**Issue by iamar7** [IBM-Cloud/terraform-provider-ibm#5680]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_database

### Terraform Configuration Files
https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis

### Expected Behavior
The redis database should provision with the given configuration as per [this](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models&interface=ui).

### Actual Behavior

It threw the following error:- 

> Error: Attribute must be a whole number, got 0.5
│ 
│   with module.icd_redis.ibm_database.redis_database,
│   on ../../main.tf line 57, in resource "ibm_database" "redis_database":
│   57: resource "ibm_database" "redis_database" {

### Steps to Reproduce

1. Update the `cpu_count` to 0.5 in `variables.tf`
2. cd examples/advance/
3. export TF_VAR_ibmcloud_api_key="xxxxxXxxxxXxxxxxXXXXXxxxxxx"
4. terraform init
5. terraform plan

### References

* #0000

**Comment by omaraibrahim** [comment]
@iamar7 `cpu_count` does not support fraction cpu count in terraform.

To get the minimum cpu count, please set the `cpu_count` to 0.

**Comment by iamar7** [comment]
> @iamar7 `cpu_count` does not support fraction cpu count in terraform.
> 
> To get the minimum cpu count, please set the `cpu_count` to 0.

But in the cloud UI the minimum allowed configuration is 0.5 CPU, 4GB Disk, 2GB RAM as shown below:- 

<img width="1493" alt="Screenshot 2024-09-24 at 2 02 53 PM" src="https://github.com/user-attachments/assets/148e4cec-5f58-41fa-9c6e-8d99be43529b">
