### ISSUE TITLE
Load Balancer Issue

### ISSUE THREAD

**Issue by viveknangal** [IBM-Cloud/terraform-provider-ibm#570]
Issue is w.r.t lBM local load balancers, unable to create it in a provided public subnet, details mentioned below .Please suggest

### Terraform Version
terraform -v
Terraform v0.11.11
+ provider.ibm (unversioned)

### Affected Resource(s)
- ibm_lbaas

### Terraform Configuration Files
```hcl
resource "ibm_lbaas" "lbaas" {
  name        = "${var.lb_name}"
  description = "${var.lb_description}"
  subnets     = ["${var.lb_subnets}"]
 type = "PUBLIC"

  protocols = [
    {
      frontend_protocol     = "${var.frontend_protocol}"
      frontend_port         = "${var.frontend_port}"
      backend_protocol      = "${var.backend_protocol}"
      backend_port          = "${var.backend_port}"
      load_balancing_method = "${var.load_balancing_method}"
    },
  ]
}
```

### Expected Behavior
Local Load balancer should get created without any error

### Actual Behavior
Throwing below error 👎 
``` hcl
1 error(s) occurred:

* module.instance.ibm_lbaas.lbaas: 1 error(s) occurred:

* ibm_lbaas.lbaas: Error during creation of Load balancer: SoftLayer_Exception_Public: Subnet ID #1850377 is not private. Only private subnets supported. (HTTP 500)


```

### Steps to Reproduce

1. `terraform apply`

**Comment by viveknangal** [comment]
@hkantare  please suggest

**Comment by viveknangal** [comment]
We would like to create IBM Cloud load balancer in a public subnet which is provided as an input to the terraform code.

**Comment by hkantare** [comment]
For creating either public or private local load balancer the subnet should be of private not public.
https://cloud.ibm.com/docs/infrastructure/loadbalancer-service?topic=loadbalancer-service-creating-an-ibm-cloud-load-balancer

**Comment by viveknangal** [comment]
@hkantare thanks for updating , as per this documentation only i thought is there an option to select the "Public IP" from the public subnet present in our account.
