### ISSUE TITLE
datasource to obtain the credentials

### ISSUE THREAD

**Issue by surajsub** [IBM-Cloud/terraform-provider-ibm#571]
Hi there,

### Terraform Version
0.14.1
### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_compute_bare_metal

Is there a reason why the datasource for compute_bare_metal does not show the credentials that are created on the box. This would be helpful to perform an end-to-end automation.

**Comment by stevestrutt** [comment]
I cannot comment specifically why the provider does not for a bare metal server. It has been this way for years. 

The reason for not doing this is will be one of security. This scenario raises the issue about the storage and security of credentials. For a data_source Terraform writes all the information it retrieves into the state file and this would include any retrieved passwords. Unless the state file is well managed and encrypted this creates a security exposure. 

The best approach is to configure the server with your SSH keys when its created. Userids and passwords, even with SSH are not a good idea. Security should be configured at creation and the keys stored separately. It cannot be bolted on afterwards. Sorry this does not help with your existing devices using data_sources.

**Comment by surajsub** [comment]
thanks for the response @stevestrutt
