### ISSUE TITLE
ibm_is_virtual_network_interface_floating_ip: inconsistent behaviour returns null instead of error

### ISSUE THREAD

**Issue by sean-freeman** [IBM-Cloud/terraform-provider-ibm#5757]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform 1.5.5 with all Terraform Providers since this data resource was added

### Affected Resource(s)

* `ibm_is_virtual_network_interface_floating_ip`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "ibm_is_virtual_network_interface_floating_ip" "test" {
  virtual_network_interface = "xxxx"
  floating_ip = "xxxx"
}

```

### Debug Output

Return Code 0, without stderr, and all data fields incorrectly return as null:
```json
    "address": null
    "crn": null
    "deleted": null
    "floating_ip": null
    "href": null
    "id": null
    "name": null
    "virtual_network_interface": null
```

### Expected Behavior

Consistency with all other data source behaviour, such as:

- `data "ibm_resource_group"` prints to stderr `[ERROR] Given Resource Group is not found in the account`
- `data "ibm_is_ssh_key"` prints to stderr `[ERROR] No SSH Key found with name NAME_HERE`
- `data "ibm_is_vpc"` prints to stderr `[ERROR] No VPC found with name NAME_HERE`
- `data "ibm_is_subnet"` prints to stderr `[ERROR] No subnet found with name (NAME_HERE)`

In this case it should be:

stderr `[ERROR] No Virtual Network Interface to Floating IP attachment found for the resource IDs`

### Steps to Reproduce

1. `terraform apply`

**Comment by ujjwal-ibm** [comment]
looking at it
