### ISSUE TITLE
Window VM Password option

### ISSUE THREAD

**Issue by viveknangal** [IBM-Cloud/terraform-provider-ibm#580]
Please suggest how to provide the password for the "Windows"  VM that we would like to create as part of "ibm_compute_vm_instance" resource.

### Terraform Version
terraform -v
Terraform v0.11.11
+ provider.ibm (unversioned)

### Affected Resource(s)
- ibm_compute_vm_instance

### Terraform Configuration Files
```hcl
resource "ibm_compute_vm_instance" "terraform-sample-flavor" {
    hostname = "terraform-sample-flavor"
    domain = "bar.example.com"
    os_reference_code = "WIN_2016-STD_64"
    datacenter = "dal06"
    network_speed = 10
    hourly_billing = true
    local_disk = false
    private_network_only = false
    flavor_key_name = "B1_2X8X25"
    user_metadata = "{\\\"value\\\":\\\"newvalue\\\"}"
    // provide disk 3, 4, 5 and so on
    disks = [10, 20, 30]
    tags = ["collectd"]
    // It should be false
    dedicated_acct_host_only = false
    ipv6_enabled = true
    secondary_ip_count = 4
    notes = "VM notes"
}
```

### Expected Behavior
Should be able to set the password affront
### Actual Behavior
Unable to find an attribute in "ibm_compute_vm_instance" resource for setting password for windows machine as part of provisioning

```

**Comment by hkantare** [comment]
For windows to set a passowrd..We should run some script which can be part of user_data.
Sample examples...
https://github.com/greyhoundforty/IBMCloud-Terraform-Examples/tree/master/WindowsCloud-Init

**Comment by hkantare** [comment]
closing this issue based on above response
