### ISSUE TITLE
ibm_is_instance: different data structure between resource and data source

### ISSUE THREAD

**Issue by sean-freeman** [IBM-Cloud/terraform-provider-ibm#5827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `ibm_is_instance`
    - Resource: [is_instance#primary_network_attachment-1](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_instance#primary_network_attachment-1)
    - Data Source: [is_instance#primary_network_attachment-1](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_instance#primary_network_attachment-1)

#### Resource structure

- primary_network_attachment:
  - id 
  - virtual_network_interface:
      - id
      - primary_ip:  :x: `Should NOT be nested under VNI`
          - id

#### Data Source structure

- primary_network_attachment
    - id
    - virtual_network_interface:
        - id
    - primary_ip
        - id
    - subnet:
        - id

#### API data structure

`POST /instances` Create Virtual Server API Response:
https://cloud.ibm.com/apidocs/vpc/latest#create-instance

`GET /instances/{id}` Retrieve Virtual Server API Response:
https://cloud.ibm.com/apidocs/vpc/latest#get-instance

- network_attachments/primary_network_attachment - InstanceNetworkAttachmentReference
    - id
    - primary_ip - ReservedIPReference
        - id
    - subnet – SubnetReference
        - id
    - virtual_network_interface - VirtualNetworkInterfaceReferenceAttachmentContext
        - id
- network_interfaces/primary_network_interface - NetworkInterfaceContextReference
    - id
    - primary_ip - ReservedIPReference
        - id
    - subnet - SubnetReference
        - id

### Steps to Reproduce

1. `terraform apply`

**Comment by ujjwal-ibm** [comment]
looking at it
