### ISSUE TITLE
documentation suggests `user-data` for `ibm_is_instance` but code suggests it should be `user_data`

### ISSUE THREAD

**Issue by jkwong888** [IBM-Cloud/terraform-provider-ibm#584]
### Terraform Version
Terraform v0.11.11
+ provider.ibm v0.17.0
+ provider.null v2.0.0
+ provider.random v2.0.0
+ provider.tls v1.2.0

### Affected Resource(s)
- ibm_is_instance
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
                                                                              
Error: ibm_is_instance.icp-boot: : invalid or unknown key: user-data 

### Expected Behavior
documentation issue, should be `user_data`

**Comment by jkwong888** [comment]
also found a similar issue with `ibm_is_security_group_rule` and `port-max`

**Comment by hkantare** [comment]
Fixed in latest release : https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.17.1
