### ISSUE TITLE
documentation for `ibm_is_instance` suggests `security_groups` should be comma separated string when it expects a list

### ISSUE THREAD

**Issue by jkwong888** [IBM-Cloud/terraform-provider-ibm#585]
### Terraform Version
Terraform v0.11.11
+ provider.ibm v0.17.0
+ provider.null v2.0.0
+ provider.random v2.0.0
+ provider.tls v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_instance

### Debug Output
Error: ibm_is_instance.icp-boot: primary_network_interface.0.security_groups: should be a list

**Comment by hkantare** [comment]
Fixed in latest code.. Will be available in next release

**Comment by hkantare** [comment]
Fixed in latest release: https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.17.1
