### ISSUE TITLE
[ERROR] The version in your configuration file (6.0) │   does not match the version of your remote instance ()

### ISSUE THREAD

**Issue by lra** [IBM-Cloud/terraform-provider-ibm#5856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v1.10.1
on darwin_arm64
+ provider registry.terraform.io/ibm-cloud/ibm v1.72.0
```

### Affected Resource(s)

* ibm_database

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_database" "this" {
  name              = ibm_resource_group.this.name
  service           = "databases-for-mongodb"
  plan              = "standard"
  location          = var.primary_region
  resource_group_id = ibm_resource_group.this.id
  service_endpoints = "public"
  version           = "6.0"
  adminpassword     = random_password.this.result
  tags              = local.tags

  group {
    group_id = "member"

    cpu {
      allocation_count = 3
    }

    memory {
      allocation_mb = var.mongodb_memory_in_mb
    }
  }

  auto_scaling {

    disk {
      capacity_enabled             = true
      free_space_less_than_percent = 15
      io_above_percent             = 85
      io_enabled                   = true
      io_over_period               = "15m"
      rate_increase_percent        = 15
      rate_limit_mb_per_member     = 3670016
      rate_period_seconds          = 900
      rate_units                   = "mb"
    }
    memory {
      io_above_percent         = 90
      io_enabled               = true
      io_over_period           = "15m"
      rate_increase_percent    = 10
      rate_limit_mb_per_member = 114688
      rate_period_seconds      = 900
      rate_units               = "mb"
    }
  }
}

```

### Debug Output

```
╷
│ Error: ---
│ id: terraform-23dab597
│ summary: "1 error occurred:\n\t* [ERROR] The version in your configuration file (6.0)
│   does not match the version of your remote instance (). Make sure that you have the
│   same version in your configuration as the version on the remote instance. Learn
│   more about the versioning policy here: https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-versioning-policy
│   \n\n"
│ severity: error
│ resource: ibm_database
│ operation: CustomizeDiff
│ component:
│   name: github.com/IBM-Cloud/terraform-provider-ibm
│   version: 1.72.0
│ ---
│
│
│   with module.gnqa03.ibm_database.this,
│   on ../../modules/cms-ibm-database/mongodb.tf line 7, in resource "ibm_database" "this":
│    7: resource "ibm_database" "this" {
│
╵
```
### Expected Behavior

```
$ terraform plan
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

```
$ terraform plan
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: ---
│ id: terraform-23dab597
│ summary: "1 error occurred:\n\t* [ERROR] The version in your configuration file (6.0)
│   does not match the version of your remote instance (). Make sure that you have the
│   same version in your configuration as the version on the remote instance. Learn
│   more about the versioning policy here: https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-versioning-policy
│   \n\n"
│ severity: error
│ resource: ibm_database
│ operation: CustomizeDiff
│ component:
│   name: github.com/IBM-Cloud/terraform-provider-ibm
│   version: 1.72.0
│ ---
│
│
│   with module.gnqa03.ibm_database.this,
│   on ../../modules/cms-ibm-database/mongodb.tf line 7, in resource "ibm_database" "this":
│    7: resource "ibm_database" "this" {
│
╵
```

### Steps to Reproduce

1. Set the provider version to `1.72.0`
2. `terraform plan`

### Important Factoids

This happens only with 1.72.0
This works fine with 1.71.3

The database is using 6.0 but returning no version to Terraform:
![Capture d’écran 2024-12-09 à 14 14 08](https://github.com/user-attachments/assets/f8b850d7-d5d5-494e-b24d-046278fe3ed4)

### References

The problem seems to be introduced by:
* #5791

**Comment by lionelmace** [comment]
I faced the same error today after upgrading to the release 1.72.0. I had to roll back to the previous release. This is a blocking issue.

**Comment by lra** [comment]
They reverted the code in https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5859 but it still needs to be released.

**Comment by omaraibrahim** [comment]
@lionelmace @lra We've reverted the change and are working on getting it released ASAP. Thank you for bringing this to our attention @lra.

**Comment by lornakelly** [comment]
Thank you for bringing this to our attention. We just released a new version 1.72.1, please upgrade to get the fix

**Comment by lra** [comment]
Thanks, the 1.72. upgrade leads to other issues `ibm_database`, but this specific problem is fixed.

**Comment by lornakelly** [comment]
Thank @lra, please open tickets for any other issues you are experiencing

**Comment by lra** [comment]
done: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5863
