### ISSUE TITLE
security groups do not get updated for `ibm_is_instance` on `terraform apply`

### ISSUE THREAD

**Issue by jkwong888** [IBM-Cloud/terraform-provider-ibm#587]
when adding the `security_groups` in the `primary_network_interface`, of an existing `ibm_is_instance`, it seems like this is never captured and the security_groups.# stays at 0.

after a `destroy` and `apply`, the correct security groups are assigned.

### Terraform Version
Terraform v0.11.11
+ provider.ibm v0.17.0
+ provider.null v2.0.0
+ provider.random v2.0.0
+ provider.tls v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_instance

### Debug Output
```
  primary_network_interface.# = 1                                           
  primary_network_interface.0.id = 8d272999-17a6-4b39-888e-f40b8a3f9609     
  primary_network_interface.0.name = footwork-calamari-circulate-deacon     
  primary_network_interface.0.port_speed = 0                                      primary_network_interface.0.primary_ipv4_address = 10.10.0.13             
  primary_network_interface.0.security_groups.# = 0    
```

```
resource "ibm_is_instance" "icp-boot" {
  name = "${var.deployment}-boot-${random_id.clusterid.hex}"

  vpc  = "${ibm_is_vpc.icp_vpc.id}"
  zone = "${format("%s-%d", var.vpc_region, 1)}"

  keys = ["${ibm_is_ssh_key.installkey.id}"]
  profile = "${data.ibm_is_instance_profile.icp-boot-profile.name}"

  primary_network_interface = {
    port_speed = "${var.boot["network_speed"]}"
    subnet = "${element(ibm_is_subnet.icp_subnet.*.id, 0)}"
    security_groups = ["${list(ibm_is_security_group.boot_node.id, ibm_is_security_group.cluster_private.id)}"]
  }


```

**Comment by hkantare** [comment]
Primary_network_interface can't be updated once ccreated ...Please use `ibm_is_security_group_network_interface_attachment` resource to change any security group for any interface.

**Comment by jkwong888** [comment]
i did this instead, it is working, thanks
