### ISSUE TITLE
Unable to create resource as non-admin account

### ISSUE THREAD

**Issue by bryand2** [IBM-Cloud/terraform-provider-ibm#591]
Using terraform v11.14 and ibm provider plugin v17.

When using a non-admin account, terraform script is failing to create a resource. Getting error message:

Error occured while configuring Resource Management service: “Request failed with status code: 400, BXNIM0106E: Validation of property ‘response_type’ with value ‘[uaa, cloud_iam]’ failed. Valid values: ‘cloud_iam’”

Seems like it is unable to get the info on the specified resource group. *** Important piece here is if I use the ibmcloud cli with this same api key (i.e. ibmcloud login --apikey) the problem does NOT occur ... so this tells me from a IAM perspective my settings are correct and this problem is specific to terraform ***

Here's the script to reproduce:

data "ibm_resource_group" "resource_group" {
    name = "ClusterEnv"
}

provider "ibm" {
  bluemix_api_key   = "<mykey>"
}

resource "ibm_is_vpc" "vpc1" {
    name = "bryan-iamtest-vpc1"
    resource_group = "${data.ibm_resource_group.resource_group.id}"
}

**Comment by bryand2** [comment]
Haven't been able to test myself, but it seems the problem originates from the underlying bluemix-go code.  Proposed fix seems to be to edit "authentication/iam.go" and change the line:

Field("response_type", "cloud_iam,uaa") ==> Field("response_type", "cloud_iam") 

Reference: https://github.com/IBM-Cloud/bluemix-go/issues/87
Reference2: https://github.com/IBM-Cloud/bluemix-go/issues/101
Reference3: https://github.com/IBM-Cloud/bluemix-go/issues/107

Although another IBM product, the docs at https://www.ibm.com/support/knowledgecenter/en/SSQP8H/iot/platform/reference/security/cloud_iam.html seem to indicate that when using IBM Cloud API keys, the response type should just be "cloud_iam".

**Comment by sakshiag** [comment]
Thanks bryan for sharing the information.. I have tested with my api key, it seems the current code works fine.. But when I tested with the api key (which has non admin access)provided by bryan it failed with the above error. We will confirm and make the changes accordingly if required.

**Comment by bryand2** [comment]
Thanks Sakshi.  Maybe your api key has elevated access? One thing to keep in mind is I don't experience this problem when using the ibmcloud cli, so that tells me the api key I'm using should also work via terraform.

**Comment by hkantare** [comment]
@bryand2 The APIKEY which you used is an ServiceID API key?

**Comment by bryand2** [comment]
@hkantare  Thanks for your help.  yes it is.

**Comment by hkantare** [comment]
Fixed in latest release we can use serviceID APikey to provision resources

**Comment by hkantare** [comment]
closing the issue as its available in latest releases
