### ISSUE TITLE
Provider 0.17 not compatible with terraform 0.12

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#594]
Using terraform 0.12 and IBM terraform provider, I get:

```

Error: Failed to instantiate provider "ibm" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

```

**Comment by stevestrutt** [comment]
Hi @l2fprod This question is popular at the moment. Sadly Terraform 0.12 is not supported yet. It is in the plan but some months out. We have not yet looked at the size of the work. Past experience of Terraform 0.11 suggests it will be a number of patch releases before it is suitable for production usage.

**Comment by powellquiring** [comment]
Following the instructions here: https://cloud.ibm.com/docs/terraform?topic=terraform-getting-started
I ran into this problem, need to at least fix the docs #597

**Comment by powellquiring** [comment]
When googling for terraform docs the default is to now find version 0.12 docs.  For example a search for `terraform variable declaration` resulted in this top hit: https://www.terraform.io/docs/configuration/variables.html

![image](https://user-images.githubusercontent.com/6932057/65714481-01941c00-e050-11e9-8627-210c4b365701.png)

**Comment by kovyrin** [comment]
Yep, they essentially treat 0.11 as deprecated version. Not sure how IBM's product people think about it, but from a customer's point of view, IBM's (a multi-billion $ corp) inability to update the provider in time for the release (which has been in beta for a year before that) is a strong signal to the company's commitment to their cloud offering...

**Comment by athak** [comment]
Plus, 0.12 is up to 0.12.9, it's more than suitable for production usage. Between the lack of support for 0.12 and having to install the provider manually...

**Comment by davetropeano** [comment]
@athak unfortunately IBM and Hashicorp do not have a business relationship that would allow publishing the IBM Cloud provider as a main Terraform provider -- hence the need for manual installation and status as a "community" provider.

Support for 0.12.x will be coming in the coming quarter according to the roadmap (published as a GH project)

**Comment by athak** [comment]
@davetropeano I don't what kind of business relationship that would be and why all the other major (and minor) cloud providers have it and can have their "official" providers.

Glad to hear that 0.12 support is coming this year, we have entire repositories of TF code stuck in 0.11 because of the IBM provider.

**Comment by billyfoss** [comment]
Any updates on this?  
I just tried beta-v0.18.0 and the 'terraform 0.12checklist' failed with
```
After analyzing this configuration and working directory, we have identified some necessary steps that we recommend you take before upgrading to Terraform v0.12:

- [ ] Provider "ibm" may need to be upgraded to a newer version that supports Terraform 0.12. (Supported version information is not available for this provider.)

Taking these steps before upgrading to Terraform v0.12 will simplify the upgrade process by avoiding syntax errors and other compatibility problems.
```

I'm having to disable IBM Cloud support to move forward with 0.12 preparation.

**Comment by c835722** [comment]
Yep seems a little behind the time.
Here is what I did on my OSX box using brew for anyone else who stumbles down here.
```
brew uninstall terraform
brew install terraform@0.11
```

**Comment by owhc** [comment]
Please add note in README.md about "Current IBM Cloud Terraform Plugins supports terraform version 0.11.x only". Thanks.

**Comment by hkantare** [comment]
IBM cloud Terraform provider now supports v0.12.X

The releases v1.x.x have support for v0.12

**Comment by umarali-nagoor** [comment]
Hence terraform-provider-ibm plugin release v1.x.x supports terraform version 0.12, closing the issue
