### ISSUE TITLE
Documentation does not work as of terraform 0.12 release

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#597]
Following the instructions here https://cloud.ibm.com/docs/terraform?topic=terraform-getting-started a cryptic message is displayed:

```
~/github.com/IBM-Cloud/vpc-tutorials/vpc-app-deploy/tf $ terraform show

Error: Failed to instantiate provider "ibm" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

### Terraform Version
```
~/github.com/IBM-Cloud/vpc-tutorials/vpc-app-deploy/tf $ tf version
Terraform v0.12.1
+ provider.ibm v0.17.0
```

See #594

**Comment by hkantare** [comment]
Duplicate of https://github.com/IBM-Cloud/terraform-provider-ibm/issues/594

**Comment by powellquiring** [comment]
This issue was raised for the docs.  The docs have been fixed:
![image](https://user-images.githubusercontent.com/6932057/69174898-926aff00-0ab7-11ea-8c67-04dc678ef3bf.png)
