### ISSUE TITLE
ibm_is_lb_listener with default pool fails

### ISSUE THREAD

**Issue by jkwong888** [IBM-Cloud/terraform-provider-ibm#598]
i'm getting a validation error when creating lb listener, with a default pool:

### Terraform Version
```
terraform -v
Terraform v0.11.11
+ provider.ibm v0.17.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.tls v2.0.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
ibm_is_lb_listener

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "ibm_is_lb_listener" "master-8001" {
  protocol = "tcp"
  lb = "${ibm_is_lb.master.id}"
  port = 8001
  default_pool = "${ibm_is_lb_pool.master-8001.id}"
}
```

### Debug Output
```
* ibm_is_lb_listener.master-8001: 1 error(s) occurred:

* ibm_is_lb_listener.master-8001: {"errors":[{"code":"validation_failure","message":"The JSON provided did not match the expected structure.","more_info":"https://cloud.ibm.com/docs/infrastructure/vpc-on-classic?topic=vpc-on-classic-rias-error-messages#validation_failure","target":{}}],"trace":"4d5829bac971a6cf108d0715416d9616"}


```

**Comment by jkwong888** [comment]
this appears to be related to the way that pool IDs are returned, which is the format `<lb id>/<lb pool id>`.

would it be possible to simplify this somehow, or at least provide that in the example?  it seems redundant to me and non-obvious that these IDs contain the lb IDs embedded in the string.

**Comment by jkwong888** [comment]
btw with the above I fixed by basically stripping the ID after the first `/`, now my terraform works correctly.

**Comment by hkantare** [comment]
Few resource depends on some other resource in such scenario we set ID has combination of two fields.
https://github.ibm.com/blueprint/bluemix-terraform-provider-dev/issues/647
Here you can find similar discussion

**Comment by hkantare** [comment]
Fixed in latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.17.1

Even if poolID is passed without any interpolation we have take care to get poolID from lbID/poolID.
