### ISSUE TITLE
Docs: resource_group are not part of cloud foundry

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#606]
These resource_* are not part of Cloud Foundry:

![image](https://user-images.githubusercontent.com/6932057/59799577-701b4e00-9299-11e9-8ad5-84d3f5153cb5.png)

**Comment by hkantare** [comment]
Fixed in v0.18.0 docs https://ibm-cloud.github.io/tf-ibm-docs/v0.18.0/

**Comment by hkantare** [comment]
Done ...https://cloud.ibm.com/docs/terraform?topic=terraform-resource-mgmt-resources
