### ISSUE TITLE
docs for is_instance should clarify the resource_group is the id not the name

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#607]
https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/is_instance.html

> resource_group - (Optional, string) The resource group for this instance.

This is the resource group id (not the name).

**Comment by hkantare** [comment]
Fixed in https://ibm-cloud.github.io/tf-ibm-docs/v0.17.2/r/is_instance.html

**Comment by hkantare** [comment]
closing the issue
