### ISSUE TITLE
is_security_group should support a resource_group attribute

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#608]
https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/is_security_group.html

> Argument Reference
The following arguments are supported:
name - (Optional, string) The security group name.
vpc - (Required, string) The vpc id.

The cli supports a resource group:
```
~/github.ibm.com/pquiring/terraform-ibm/tstinstance $ ibmcloud is security-group-create --help
NAME:
    security-group-create, sgc - Create a security group

USAGE:
    ibmcloud is security-group-create GROUP_NAME VPC_ID [--resource-group-id RESOURCE_GROUP_ID | --resource-group-name RESOURCE_GROUP_NAME] [--json]

OPTIONS:
   --resource-group-id value    ID of the resource group. This option is mutually exclusive with --resource-group-name
   --resource-group-name value  Name of the resource group. This option is mutually exclusive with --resource-group-id
   --json                       Format output in JSON
```

**Comment by grazius** [comment]
Hello
in our company we start using terraform.

we are unable to create a security group:
```
2019/07/31 11:40:24 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
* ibm_is_security_group.sg1: unknown error (status 503): {resp:0xc420ac41b0} 
```

For information, i got the same error (status 503: {resp:0xc4201637a0}) when i try to create a vpc with ibm_is_vpc without define resource_group (which is not required > https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/d/is_vpc.html).

Thanks for your help

**Comment by powellquiring** [comment]
@grazius , 503 can be an indication of a transient network error.  Can you try again?

**Comment by hkantare** [comment]
Added support for resource_group for security group. We will make a release by tomorrow

**Comment by hkantare** [comment]
Fix is available in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.17.2
