### ISSUE TITLE
Remove "bluemix" URLs from docs

### ISSUE THREAD

**Issue by davetropeano** [IBM-Cloud/terraform-provider-ibm#609]
We need to remove the use of `bluemix` in URLs that are referenced in docs and replace with the appropriate `cloud.ibm.com` URLs. 

Example: https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/container_cluster.html

**Comment by hkantare** [comment]
Fixed in https://ibm-cloud.github.io/tf-ibm-docs/v0.17.2/
