### ISSUE TITLE
Show required credentials for each resource

### ISSUE THREAD

**Issue by Nadine2016** [IBM-Cloud/terraform-provider-ibm#611]
In https://ibm-cloud.github.io/tf-ibm-docs/ (main page), we currently do not list special variables for Cloud Foundry resources as we do in https://cloud.ibm.com/docs/terraform?topic=terraform-configure_provider#preparing-the-credentials-for-terraform

If those are still valid, could we add those to the main page? 

Also, could we add the required credentials to each resource in the docs so that people know what exactly they need to provision it?

**Comment by hkantare** [comment]
Below two are not valid arguments. They are not required for preparing the credentials for cloud foundry at provider level. The docs needs to be edited to remove those two parameters.
org_name = "<cf_org>"
space_name = "<cf_space>"

**Comment by Nadine2016** [comment]
@hkantare what credentials do I need for CF resources? Is it the IBM Cloud API key only?

**Comment by hkantare** [comment]
Yes only IBM Cloud API key is required.

**Comment by Nadine2016** [comment]
thank you!!. closing
