### ISSUE TITLE
ibm_compute_instance datacenter not respected

### ISSUE THREAD

**Issue by typekpb** [IBM-Cloud/terraform-provider-ibm#613]
### Terraform Version
```
terraform --version
Terraform v0.11.14
```
terraform IBM cloud provider plugin version: `0.17.1`

### Affected Resource(s)
`ibm_compute_instance`

### Terraform Configuration Files
```hcl
resource "ibm_container_cluster" "cluster" {
  name         = "${var.cluster_name}"
  datacenter   = "${var.ic_datacenter}"
  org_guid     = "${data.ibm_org.org.id}"
  space_guid   = "${data.ibm_space.space.id}"
  account_guid = "${data.ibm_account.account.id}"
  machine_type    = "${var.machine_type}"
  hardware        = "${var.hardware}"
}
```
where: 
```
  ic_datacenter   = "fra03"
  machine_type    = "free"
  hardware        = "shared"
```

### Expected Behavior
cluster should be created in Frankfurt datacenter

### Actual Behavior
Kubernetes cluster gets created in italian datacenter (`Milano 01`)

**Comment by Praveengostu** [comment]
When creating a free cluster the datacenter option is not considered. Free clusters are deployed within the region that you select, but you cannot choose which zone/datacenter. For control over zone, networking, and persistent storage, create a standard cluster. IBM resource for cluster is designed to have the datacenter as a required field but that is not controlled for a free cluster.

**Comment by typekpb** [comment]
@Praveengostu thank you for explanation, closing
