### ISSUE TITLE
Documentation is imprecise on whether I need to specify resource group name or ID

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#617]
When creating a VPC (https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/is_vpc.html), the `resource_group` attribute must be a resource group ID, not a name. The doc just says `resource_group - (Optional, string) The resource group where the VPC to be created` which does not help.

If I pass the name instead of the ID, I get
```
1 error occurred:
	* ibm_is_vpc.vpc: 1 error occurred:
	* ibm_is_vpc.vpc: {"errors":[{"code":"validation_failure","message":"The JSON provided did not match the expected structure.","more_info":"https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-rias-error-messages#validation_failure","target":{"name":"vpc.resource_group.id","type":"field"}}],"trace":"e95295f98a8e6270aed1b0ce723b6377"}
```

Also the behavior seems to be different for `ibm_is_instance` (https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/is_instance.html). There I have specified the resource group name and it works.

**Comment by hkantare** [comment]
Fix is available as part of master branch https://github.com/IBM-Cloud/terraform-provider-ibm. Enhanced documentation

**Comment by hkantare** [comment]
Udated docs https://ibm-cloud.github.io/tf-ibm-docs/v0.17.2
