### ISSUE TITLE
ibm_cis location field required but not documented

### ISSUE THREAD

**Issue by hassenius** [IBM-Cloud/terraform-provider-ibm#621]
### Terraform Version
0.11.14, provider 0.17.1

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_cis

### Terraform Configuration Files
```hcl
data "ibm_resource_group" "sre" {
  name = "SREREFARCH"
}

resource "ibm_cis" "multicloudapps" {
  name              = "MultiCloudApps"
  plan              = "standard"
  resource_group_id = "${data.ibm_resource_group.sre.id}"
  tags              = ["sre", "multicloud"]

  //User can increase timeouts
  timeouts {
    create = "15m"
    update = "15m"
    delete = "15m"
  }
}
```

### Debug Output
Error: ibm_cis.multicloudapps: "location": required field is not set

### Expected Behavior
Example and required fields mentioned in documentation should suffice to create an instance

### Actual Behavior
Required field was missing

### Steps to Reproduce
Follow documented example from https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/cis.html

**Comment by hkantare** [comment]
fixed in latest releases
