### ISSUE TITLE
bm_cis_origin_pool documentation missing required fields

### ISSUE THREAD

**Issue by hassenius** [IBM-Cloud/terraform-provider-ibm#622]
### Terraform Version
Terraform 0.11.14, ibmcloud provider 0.17.1

### Affected Resource(s)
- ibm_cis_origin_pool

### Terraform Configuration Files
Based on example from https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/cis_origin_pool.html
```hcl
resource "ibm_cis_origin_pool" "ingresspool" {
  cis_id = "${ibm_cis.multicloudapps.id}"
  name = "ingresspool"
  origins {
    name    = "azure"
    address = "${module.azurecloud.icp_proxy}"
    enabled = true
  }
  origins {
    name    = "aws"
    address = "${module.awscloud.icp_proxy_host}"
    enabled = true
  }
  origins {
    name    = "ibm"
    address = "${module.ibmcloud.icp_proxy_host}"
    enabled = true
  }
}
```

### Debug Output
```
Error: ibm_cis_origin_pool.ingresspool: "check_regions": required field is not set
Error: ibm_cis_origin_pool.ingresspool: "enabled": required field is not set
```

### Expected Behavior
Resource should have been provisioned

### Actual Behavior
Complained that required fields were missing

### Steps to Reproduce
Attempt to provision resource based on provided documentation and example configurations
1. `terraform apply`

**Comment by hkantare** [comment]
Fixed in latest releases
