### ISSUE TITLE
ibm_container_cluster_config should download pem files + expose host attribute

### ISSUE THREAD

**Issue by typekpb** [IBM-Cloud/terraform-provider-ibm#623]
### Terraform Version
```
terraform --version
Terraform v0.11.14
```
terraform IBM cloud provider plugin version: `0.17.1`

### Affected Resource(s)
`ibm_container_cluster_config`

### Terraform Configuration Files
The  `ibm_container_cluster_config` should download pem files and expose their names via attributes + expose host name as attirbute. As the official terraform kubernetes provider [shows](https://www.terraform.io/docs/providers/kubernetes/guides/getting-started.html#provider-setup)
```
provider "kubernetes" {
  host = "https://1.1.1.1"

  client_certificate     = "${file("~/.kube/client-cert.pem")}"
  client_key             = "${file("~/.kube/client-key.pem")}"
  cluster_ca_certificate = "${file("~/.kube/cluster-ca-cert.pem")}"
}
```
Alternatively, values of those files should be available as attributes (see google cloud example: https://container-solutions.com/propagating-configuration-from-terraform-to-kubernetes-apps/)

### Expected Behavior
There is a way to create kubernetes cluster in IBM cloud (via provider) and right afterwards to interract with the cluster (via kubernetes provider).

### Actual Behavior
no way for that (found)

**Comment by Praveengostu** [comment]
Hi @typekpb Have you tried the admin option to download the pem files
```admin - (Optional, boolean) Set the value to true to download the configuration for the administrator. The default value is false. This will retrieve administrator certificates and PEM keys.```
For more information: https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/d/container_cluster_config.html
Regarding the hostname we will check and get back to you at earliest

**Comment by typekpb** [comment]
OK, thanks for the hint, the admin flag works!

The attributes I still miss:
* as you mentioned the `hostname`
* moreover, ca-cert filename name is dynamic as well (`ca-<datacenter>-<cluster-name>.pem`). Would need to either make it static or expose it as well (as datacenter is for the free cluster randomly picked).

The other files seems to have fixed naming (`admin.pem`, `admin-key.pem`) => I can rely on reading those.

On the other hand, to prevent writing me crazy stuff like this:
```
data "ibm_container_cluster_config" "cluster_config" {
  ...
}

locals {
  container_cluster_config_path = "${replace(data.ibm_container_cluster_config.cluster_config.config_file_path, "config.yml", "")}"
  client_key = "${local.container_cluster_config_path}/admin-key.pem"
  client_certificate = "${local.container_cluster_config_path}/admin.pem"
}

output "container_cluster_config_client_certificate" {
  value = "${file(local.client_certificate)}"
}

output "container_cluster_config_client_key" {
  value = "${file(local.client_key)}"
}
```

it would be really nice if `ibm_container_cluster_config` could have all of the following attributes:
* `ca_certificate` - `ca-cert.pem` file contents
* `client_certificate` - `admin.pem` file contents
* `client_key` - `admin-key.pem` file contents
* `hostname`

What do you think?

**Comment by hassenius** [comment]
+1 from me

I'd really, really like the ibm_container_cluster_config data source to provide the actual data.

**Comment by hkantare** [comment]
Available part of latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.2
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.2

https://cloud.ibm.com/docs/terraform?topic=terraform-container-data-sources#container-cluster-config
