### ISSUE TITLE
Support taints during node creation

### ISSUE THREAD

**Issue by jfeddern** [IBM-Cloud/terraform-provider-ibm#624]
Hi there,

we would like to have the ability to add taints to a kubernetes node during the creation of a node.
Currently we have to add all taints after the kubernetes cluster is created. Which lead to some more or less complex terraform setup.

I would suggest to add this functionality to the ibm_container_worker_pool resource (https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/container_worker_pool.html)

Some other providers already support this solution (e.g. google https://www.terraform.io/docs/providers/google/r/container_cluster.html#taint)

**Comment by greglanthier** [comment]
This would be pretty handy.  Some IKS best practice documents include steps to taint edge nodes to avoid having non-networking workloads scheduled on them ([Securing Containers Workload Patterns in IKS](https://developer.ibm.com/dwblog/2018/securing-containers-iks-kubernetes/) is only one example).

It would be cool if we didn't need to run the following `kubectl` command _after_ our clusters were created:

```console
kubectl taint node -l dedicated=edge dedicated=edge:NoSchedule dedicated=edge:NoExecute
```

**Comment by hkantare** [comment]
The current version of IKS doesn't support any taint option. We will open a support ticket on IKS team for the requirement.

**Comment by sh0m1** [comment]
Since recently it is possible to taint all the nodes in a worker pool via ibmcloud cli command `ibmcloud ks worker-pool taint set`. Since there is the API support for this I would assume that there are no obstacles having terraform implementation of this in `ibm_container_vpc_worker_pool` resource?

**Comment by jfeddern** [comment]
#1646

**Comment by hkantare** [comment]
We will plan in  next upcoming sprints
