### ISSUE TITLE
ibm_service_instance - unable to create service in a resource group

### ISSUE THREAD

**Issue by mzmudziak** [IBM-Cloud/terraform-provider-ibm#625]
### Terraform Version
Terraform v0.11.14
+ provider.helm v0.9.1
+ provider.kubernetes v1.7.0
+ provider.null v2.1.2

### Affected Resource(s)
- ibm_service_instance

### Terraform Configuration Files
```hcl

provider "ibm" {
  region         = "${var.region}"
  resource_group = "${data.terraform_remote_state.cluster.resource_group_id}"
}

resource "ibm_service_instance" "service-instance" {
  name       = "${var.service_instance_name}"
  space_guid = "${data.terraform_remote_state.cluster.space_id}"
  service    = "cloudantNoSQLDB"
  plan       = "${var.plan}"

  tags = [
    "cluster-service",
    "cluster-bind",
  ]

``
}
```

### Debug Output
https://gist.github.com/mzmudziak/3c05d079ed79e5815b2819e49ff5c8a2

### Expected Behavior
A service instance should be created in a specific, specified resource group
### Actual Behavior
The service instance got created in "default" resource group.

### Steps to Reproduce
1. `terraform apply`

### Additional context
My issue is that I need to use a resource group while creating a new `cloudantNoSQLDB` service instance, however either the documentation is _not clear_ about how to achieve it, or it is bugged.
The documentation mentions that I can use a `parameters` argument to pass arbitrary parameters, and it's of map data type:
https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/service_instance.html
>parameters - (Optional, map) Arbitrary parameters to pass to the service broker. The value must be a JSON object.

I am not sure how to pass a JSON object as parameter, and given that it's a map data type i have tried what you can see above:

```hcl
  parameters = {
    "resource_group" = "${data.terraform_remote_state.cluster.resource_group_id}"
    "target"         = "${var.region}"
  }
```

It produced correct output: 
```
parameters.resource_group: "" => "8b97f027e8f3468299ed638d1f24aabd"
parameters.target:         "" => "eu-de"
```

The service instance still got created in the `default` resource group. 
The [documentation](https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-workingwith-services) for working with Services mentions that i can pass JSON values, like this:
```
cf create-service SERVICE PLAN SERVICE_INSTANCE -c '{"instance_name":"value", "resource_group":"value", "target":"value"}'
```
I have tried it using the CLI and it was created in the correct resource group in fact.

How can I achieve this using IBM provider for Terraform? It looks like it's bugged, or the documentation is unclear.

**Comment by hkantare** [comment]
Can you let us know which type of service instance you are creating..
