### ISSUE TITLE
Is provisioning to VPC gen 1 supported?

### ISSUE THREAD

**Issue by odaira** [IBM-Cloud/terraform-provider-ibm#626]
Does the IBM Cloud Provider support provisioning to VPC gen 1?  When I provisioned a VPC using `ibm_is_vpc` without any special option, it was created in the gen 2 environment.  Is there any option to specify the target, like we do with the ibmcloud command? `ibmcloud is target --gen 1`

### Terraform Version
```
$ terraform -v
Terraform v0.11.14
+ provider.ibm v0.17.1

Your version of Terraform is out of date! The latest version
is 0.12.3. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)
- ibm_is_vpc

### Important Factoids
I am using one of IBM's functional IDs assigned to our team.

**Comment by hkantare** [comment]
yes..Please export IC_GENERATION=1 or add in provider block
provider "ibm" {
generation=1
}
https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/

**Comment by odaira** [comment]
@hkantare thanks, it works!
