### ISSUE TITLE
Problem in provisioning IKS cluster using IBM terraform provider

### ISSUE THREAD

**Issue by hjweds** [IBM-Cloud/terraform-provider-ibm#628]
### Terraform Version
Terraform: v0.11.14
IBM provider: 0.17.1

### Affected Resource(s)
- ibm_container_cluster

### Terraform Configuration Files
```hcl
resource "ibm_container_cluster" "iks_cluster" {
 name                             = "${var.cluster_name}"
 datacenter                     = "${var.zone1}"
 worker_num                   = "1"
 machine_type                 = "${var.machine_type}"
 region                              = "${var.cluster_region}"
 private_vlan_id                = "${ibm_network_vlan.dal13_private.id}"
 hardware                         = "${var.hardware}"
 resource_group_id           = "${data.ibm_resource_group.bnpp_group.id}"
 public_service_endpoint  = "${var.public_service_endpoint}"
 private_service_endpoint = "${var.private_service_endpoint}"
}
```

### Problem
This terraform script provisions a cluster with an extra worker node that does not belong to any worker pool. It does not allow to put `worker_num = 0`, so there is always that extra worker node. We try removing the `worker_num` property, but it does not work as well. We do not want that extra worker node in the cluster.
![image](https://user-images.githubusercontent.com/26032834/60532293-9b9f2f00-9cc2-11e9-8f62-6ac79ae9a5d2.png)

**Comment by hjweds** [comment]
We tested again by removing the `worker_num`. It can pass through and provision a cluster without the extra worker node.
![image](https://user-images.githubusercontent.com/26032834/60545872-b2a14980-9ce1-11e9-9b83-26041e18f879.png)
Without adding the `worker_num` property manually, ibm provider will have `worker_num=0` included.
![image](https://user-images.githubusercontent.com/26032834/60545905-cba9fa80-9ce1-11e9-84de-f23de9459d46.png)

**Comment by hjweds** [comment]
Issue can be closed.

**Comment by hkantare** [comment]
closing the issue based on above comment...
