### ISSUE TITLE
is_instance is recreating resource every time plan / apply is run

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#635]
### Terraform Version
$ terraform version
Terraform v0.11.14
+ provider.ibm v0.17.1

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_instance

### Terraform Configuration Files
```hcl
resource ibm_is_instance "vsi_app" {
  count = "3"
  name  = "${var.resources_prefix}-vsi-app-${count.index + 1}"
  vpc   = "${ibm_is_vpc.vpc.id}"
  zone  = "${lookup(var.zones, "zone-${count.index + 1}")}"

  keys           = ["${data.ibm_is_ssh_key.ssh_key_1_id.id}", "${data.ibm_is_ssh_key.ssh_key_2_id.id}"]
  image          = "${data.ibm_is_image.ubuntu.id}"
  profile        = "cc1-2x4"
  resource_group = "${var.resource_group}"

  primary_network_interface = {
    subnet          = "${element(ibm_is_subnet.sub_app.*.id, count.index)}"
    security_groups = ["${ibm_is_security_group.sg_app.id}"]
  }
}
```

### Debug Output
Not applicable

### Panic Output
Not applicable

### Expected Behavior
The resource group name did not change, yet the plan indicates there is a change from `id` to `name`.  The provider seems to require the `name` of the resource group, yet the `apply` or `plan` wants to recreate the instance every time because it believes the resource group has changed. 

### Actual Behavior
The instance was recreated.  
![image](https://user-images.githubusercontent.com/11874942/60612639-189bd880-9d97-11e9-9ec0-aab78f52be9a.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### Important Factoids
none

### References
none

**Comment by dprosper** [comment]
If switching the resource group to be the id instead of the name it works:

```hcl
  # resource_group = "${var.resource_group}"
  resource_group = "${data.ibm_resource_group.group.id}"
```

**Comment by hkantare** [comment]
The resource_group which we are targeting for VPC should be the ID not the name. We are going to update the docs to specify the ID of resource group..We need to check with API team on this and get back..

**Comment by hkantare** [comment]
Updated the docs
