### ISSUE TITLE
Unable to create volume using example

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#636]
Attempting to create a volume fails with status 409.  

# Terraform Version
$ terraform version
Terraform v0.11.14
+ provider.ibm v0.17.1

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_volume

### Terraform Configuration Files
```hcl
resource "ibm_is_volume" "vsi_database_volume" {
  count = "3"
  name     = "data-${count.index + 1}"
  profile  = "10iops-tier"
  zone     = "${lookup(var.zones, "zone-${count.index + 1}")}"
  iops     = 10000
  capacity = 100
  resource_group = "${data.ibm_resource_group.group.id}"
}
```

### Panic Output
not applicable

### Expected Behavior
Volume should be created as the example is followed.

### Actual Behavior
What actually happened?
```sh
ibm_is_instance.vsi_app[2]: Creation complete after 2m13s (ID: e7d6cc7e-dfd9-4bd3-8019-630d8edcdc7a)
ibm_is_instance.vsi_app[1]: Creation complete after 2m14s (ID: 55d41e90-5f92-4223-8b44-cf38db23137c)
ibm_is_floating_ip.fip_1: Still creating... (10s elapsed)
ibm_is_floating_ip.fip_1: Creation complete after 16s (ID: f8d001d7-ebd9-46ab-9d75-fd5c46587243)

Error: Error applying plan:

3 errors occurred:
        * ibm_is_volume.vsi_database_volume[0]: 1 error occurred:
        * ibm_is_volume.vsi_database_volume.0: unknown error (status 409): {resp:0xc04294c240}


        * ibm_is_volume.vsi_database_volume[1]: 1 error occurred:
        * ibm_is_volume.vsi_database_volume.1: unknown error (status 409): {resp:0xc0429b0120}


        * ibm_is_volume.vsi_database_volume[2]: 1 error occurred:
        * ibm_is_volume.vsi_database_volume.2: unknown error (status 409): {resp:0xc0429b01b0}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Creating in VPC

**Comment by hkantare** [comment]
When user specifies the profile `profile  = "10iops-tier"` then custom iops value can be provided..
resource "ibm_is_volume" "vsi_database_volume" {
  count = "3"
  name     = "data-${count.index + 1}"
  profile  = "10iops-tier"
  zone     = "${lookup(var.zones, "zone-${count.index + 1}")}"
  capacity = 100
  resource_group = "${data.ibm_resource_group.group.id}"
}

or 
resource "ibm_is_volume" "vsi_database_volume" {
  count = "3"
  name     = "data-${count.index + 1}"
  profile  = "custom"
  zone     = "${lookup(var.zones, "zone-${count.index + 1}")}"
  iops     = 6000
  capacity = 100
  resource_group = "${data.ibm_resource_group.group.id}"
}

**Comment by dprosper** [comment]
thank you, can the docs be updated (this was copied from the example provided).  In addition, is it possible to reference other documentation describing what the available values for profile and iops can be.
