### ISSUE TITLE
Feature Request: http port

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#637]
When configuring a pool for a tcp port, the health check needs to be http.  There is no way it seems in the pool resource to specify a port for the http health check port, i.e. 

An example of a configuration is: round-robin to TCP port 2554, but the health port is http on port 8080.

**Comment by dprosper** [comment]
This is really needed to match the capabilities available in the CLI today.  Possible to get an update on this?

**Comment by hkantare** [comment]
We are looking into the request..

**Comment by hkantare** [comment]
Fix is available as part of master branch https://github.com/IBM-Cloud/terraform-provider-ibm

**Comment by dprosper** [comment]
Does this mean that I need to compile to use? not clear on what this means now that it is in master.  Will you be producing a release for use?

**Comment by hkantare** [comment]
Presently we don't have exact plan of release date...
If the fix is needed immediately you can just clone and build the provider as per README

**Comment by hkantare** [comment]
Fix is available as part of latest releases

**Comment by hkantare** [comment]
closing the issue
