### ISSUE TITLE
Support for namespaces for Functions resources

### ISSUE THREAD

**Issue by davetropeano** [IBM-Cloud/terraform-provider-ibm#642]
IBM Ckoud Functions recently moved from an org/space model to an IAM controlled namespaces model for all associated objects like actions, triggers, etc. 

The associated terraform resources in the provider should support creating namespaces and relating an action to a namespaces etc.

**Comment by benoj** [comment]
+1

**Comment by khayama** [comment]
+1

**Comment by powellquiring** [comment]
IAM is required for IBM's `secure to the core` strategy.  The GUI is suggesting it:
![image](https://user-images.githubusercontent.com/6932057/71682981-1c101c80-2d46-11ea-99ac-d8f56b4eead3.png)

**Comment by khayama** [comment]
+1

**Comment by davetropeano** [comment]
This is related to #837 and both have not been addressed. It is unclear how https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-function-cloudant-trigger would work as well given all this.

**Comment by cncook001** [comment]
+1

**Comment by pheuberger** [comment]
+1

**Comment by benoj** [comment]
Just for FYI on people recently +1'ing this. I ended up migrating to AWS because of this issue (and the other pains I had as we were testing out the IBM platform) I suggest you do the same if possible

**Comment by khayama** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/837#issuecomment-662864183
