### ISSUE TITLE
ibm_is_lb_pool_member timeout does not seem to match documentation

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#645]
### Terraform Version
$ terraform -v
Terraform v0.11.14
+ provider.ibm v0.17.1
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

-  ibm_is_lb_pool_member

### Expected Behavior
According to the documentation the default timeout is 60 minutes.  Yet the apply was errored out after 10 minutes of waiting.... 

### Actual Behavior
Error: Error applying plan:

1 error occurred:
        * ibm_is_lb_pool_member.database-pool-members[0]: 1 error occurred:
        * ibm_is_lb_pool_member.database-pool-members.0: Error checking for load balancer (0114030a-a037-4050-8e2b-e25a28ff3783) is active: timeout while waiting for state to become 'done' (last state: 'provisioning', timeout: 10m0s)

**Comment by dprosper** [comment]
Debug output provided in RIAS repo issue: 2331

**Comment by hkantare** [comment]
Its  a Documentation issue we will fix ..It by default set to 10 min.Can you please increase timeout and try again

**Comment by dprosper** [comment]
The assumption is the request was made to add the pool member to the load balancer and the provider was only waiting for the request to complete.  Checking the load balancer after 8 hours shows that the member was never added, so I believe there is something additional that went wrong, can you review the logs?

**Comment by dprosper** [comment]
@deepaksibm no I have not seen this again, so feel free to close.
