### ISSUE TITLE
containter_cluster with openshift causes incorrect update cycle

### ISSUE THREAD

**Issue by hassenius** [IBM-Cloud/terraform-provider-ibm#647]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```$ terraform -v
Terraform v0.11.14
+ provider.ibm v0.17.1
+ provider.kubernetes v1.8.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_cluster

### Terraform Configuration Files
```hcl
resource "ibm_container_cluster" "testacc_cluster" {
  name            = "hktest"
  datacenter      = "lon06"
  kube_version    = "3.11.104_openshift"
  machine_type    = "u3c.2x4"
  hardware        = "shared"
  public_vlan_id  = "2651191"
  private_vlan_id = "2651193"
  #subnet_id       = ["1154643"]
  region          = "eu-gb"
  resource_group_id = "${data.ibm_resource_group.refarch.id}"

  default_pool_size      = 1
}


```

### Debug Output
  ~ ibm_container_cluster.testacc_cluster
      kube_version:                "3.11.104" => "3.11.104_openshift"

### Expected Behavior
Rerunning `terraform apply` should not generate a changed config

### Actual Behavior
Every `terraform apply` generates an in-place upgrade which will fail with the message
```
 {"incidentID":"4f6b1a8222d6a699-DUB","code":"E0120","description":"The master is already up to date for the specified version.","type":"Versions"}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### Important Factoids
This line https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_container_cluster.go#L597 explicitly strips the `_openshift` part of the version number when storing the `kube_version`. This leads to the current problem.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by hkantare** [comment]
Thanks for opening the issue..AS a temporary work around we can terraform ignore life_cycle changes
```
resource "ibm_container_cluster" "cluster" {
  name              = "${var.cluster_name}${random_id.name.hex}"
  datacenter        = "${var.datacenter}"
  default_pool_size = 3
  machine_type      = "${var.machine_type}"
  hardware          = "${var.hardware}"
  kube_version      = "${var.kube_version}"
  public_vlan_id    = "${var.public_vlan_id}"
  private_vlan_id   = "${var.private_vlan_id}"
  lifecycle {
    ignore_changes = ["kube_version"]
  }
}
```
until the issue get fixed..

**Comment by hkantare** [comment]
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.17.3
