### ISSUE TITLE
Resource Key Parameter Issue

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#649]
If I try to add a new Resource Key to my Cloud Object Storage Account, I have some problems regarding the HMAC = True Parameter inside the ibm_resource_key Object.

'terraform apply' works perfectly. But If I do a 'terraform plan' afterwards, Terraform wants to create a new ibm_resource_key instance because it did not recognizance the HMAC Parameter.

### Terraform Version
Terraform v0.11.14
+ provider.ibm v0.17.1

### Affected Resource(s)
-ibm_resource_key
-ibm_resource_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "ibm_resource_instance" "CloudObjectStorage" {
  name              = "COS_${var.clientName}_${var.env}"
  service           = "cloud-object-storage"
  plan              = "standard"
  resource_group_id = "${ibm_resource_group.group.id}"
  tags              = ["${lower(var.env)}"]
  location          = "global"
}

resource "ibm_resource_key" "CloudObjectStorage_Resource_Key" {
  name                 = "COS_Resource_Key"
  role                 = "Writer"
  resource_instance_id = "${ibm_resource_instance.CloudObjectStorage.id}"

  parameters = {
    "HMAC" = true
  }
}

### Expected Behavior
ibm_resource_key Parameters are been recognized by terraform

### Actual Behavior
terraform plan
...
Terraform will perform the following actions:

-/+ module.FactoryServices.ibm_resource_key.CloudObjectStorage_Resource_Key (new resource required)
      id:                   "crn:v1:bluemix:public:cloud-object-storage:global:a/235fae059dcb4941b6c90303077b49c5:ae5aa0e9-cd4b-4d4a-878f-3a9679bbb3d8:resource-key:25c12a27-12ee-476d-99cb-80110a3368d3" => <computed> **(forces new resource)**
      credentials.%:        "9" => <computed>
      name:                 "COS_Resource_Key" => "COS_Resource_Key"
      **parameters.%:         "0" => "1" (forces new resource)
      parameters.HMAC:      "" => "1" (forces new resource)**
      resource_instance_id: "crn:v1:bluemix:public:cloud-object-storage:global:a/235fae059dcb4941b6c90303077b49c5:ae5aa0e9-cd4b-4d4a-878f-3a9679bbb3d8::" => "crn:v1:bluemix:public:cloud-object-storage:global:a/235fae059dcb4941b6c90303077b49c5:ae5aa0e9-cd4b-4d4a-878f-3a9679bbb3d8::"
      role:                 "Writer" => "Writer"
      status:               "active" => <computed>

### Steps to Reproduce
1. use the snippings from above
2. terraform apply
3. terraform plan

**Comment by VaishnaviGopal** [comment]
When the HMAC parameter is given for creating a resource key, 
1. The code works fine and creates the resource key but
2. the API call for getting that resource key is not showing that parameter.
3. So, the state file has no record of the HMAC parameter.
4. Hence when the terraform plan is ran for the second time, terraform wants to create a new ibm_resource_key instance as there is a difference in the parameters of the earlier created, and this instance.

**Will check with the API team and get back to this issue**

**Comment by aMozejko1** [comment]
hey there, 
i just pulled and built version 0.17.2 which seems to have fixed this issue which i was seeing in 0.17.1.
i'm using terraform 11.13
