### ISSUE TITLE
Feature request: ID compatibility between ibm_container_worker_pool and ibm_container_worker_pool_zone_attachment

### ISSUE THREAD

**Issue by kingpong** [IBM-Cloud/terraform-provider-ibm#657]
### Terraform Version
v0.11.13

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_container_worker_pool
- ibm_container_worker_pool_zone_attachment

### Terraform Configuration Files
```hcl
resource "ibm_container_worker_pool" "edge" {
  worker_pool_name = "edge"
  // ...
}

resource "ibm_container_worker_pool_zone_attachment" "edge-zone1" {
  // DOESN'T WORK
  worker_pool = "${ibm_container_worker_pool.edge.id}" 
  // ...
}
```

### Expected Behavior
I expected to be able to use the `id` attribute of the ibm_container_worker_pool resource as the worker_pool ID in the ibm_container_worker_pool_zone_attachment resource.

### Actual Behavior
```
* ibm_container_worker_pool_zone_attachment.edge-zone1: 1 error(s) occurred:

* ibm_container_worker_pool_zone_attachment.edge-zone1: Request failed with status code: 404, ServerErrorResponse: 404 page not found
```

The ibm_container_worker_pool.id contains more information than is apparently required/accepted by ibm_container_worker_pool_zone_attachment.

The [recommended fix](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/343) for this has been to split the id on / and take the first element, e.g.
```hcl
"${element(split("/",ibm_container_worker_pool.edge.id),1)}"
```

This is surprising behavior, because:
1. The worker pool is advertising that its ID is X
2. The zone attachment [is documented](https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/container_worker_pool_zone_attachment.html) to take a worker pool ID
3. The zone attachment will not accept X as a worker pool ID

### Possible fixes
- If `ibm_container_worker_pool.id` contains more information than is useful or required, maybe it could be abridged?
- Otherwise, if `ibm_container_worker_pool_zone_attachment` doesn't care about anything after the slash, maybe it could ignore everything after the slash?

### References
- #343

**Comment by hkantare** [comment]
Now we have worker_pool_id to dorectly refer the workerpool id instead of element and spliting https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_worker_pool#worker_pool_id
