### ISSUE TITLE
Support of IKS on VPC

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#658]
https://containers.cloud.ibm.com/swagger-api/#/beta

**Comment by grazius** [comment]
Hello
today there no way to create an IKS on VPC without implementation of this API ?

**Comment by hkantare** [comment]
No v0.17.3  don't support yet IKS on VPC..
We need to support in future will update the issue once we have finalized the plan

**Comment by hkantare** [comment]
We released initial support for IKS on VPC
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.19.0
