### ISSUE TITLE
data source resource_key

### ISSUE THREAD

**Issue by hajmsta** [IBM-Cloud/terraform-provider-ibm#664]
When I try to get resource instance and resource key, the following error message is displayed.
  malformed CRN: Error parsing JSON
Looks like the provider ibm has a bug.

terraform version 0.11.14
provider ibm version 0.17.1
---main.tf---
provider "ibm" {
  ibmcloud_api_key   = "${var.ibmcloud_bx_api_key}"
  softlayer_username = "${var.ibmcloud_sl_api_user}"
  softlayer_api_key  = "${var.ibmcloud_sl_api_key}"
}
data "ibm_resource_group" "group" {
  name = "${var.ibmcloud_rg_name}"
}
data "ibm_resource_instance" "assistant" {
  name              = "${var.assistant_name}"
  service           = "${var.assistant_service}"
  resource_group_id = "${data.ibm_resource_group.group.id}"
}
data "ibm_resource_key" "assistantKey" {
  name                  = "${var.assistant_key_name}"
  resource_instance_id  = "${data.ibm_resource_instance.assistant.id}"
}
---variables.tf---
variable "ibmcloud_bx_api_key" {
    default = "xxxxxxxxx"
}
variable "ibmcloud_sl_api_user" {
    default = "xxxxxxxxx"
}
variable "ibmcloud_sl_api_key" {
    default = "xxxxxxxxx"
}
variable "ibmcloud_rg_name" {
    default = "default"
}
variable "assistant_name" {
    default = "test-assistant"
}
variable "assistant_service" {
    default = "conversation"
}
variable "assistant_key_name" {
    default = "test-credential"
}
---messages---
terraform plan
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.ibm_resource_group.group: Refreshing state...
data.ibm_resource_instance.assistant: Refreshing state...
data.ibm_resource_key.assistantKey: Refreshing state...


Error: Error refreshing state: 1 error occurred:
        * data.ibm_resource_key.assistantKey: 1 error occurred:
        * data.ibm_resource_key.assistantKey: data.ibm_resource_key.assistantKey: malformed CRN: Error parsing JSON
```

-----

**Comment by VaishnaviGopal** [comment]
can you tell what type of service you are creating?

**Comment by hajmsta** [comment]
Watson assistant "conversatioin" but fixed. 
The service seems to have fixed it with credentials.
