### ISSUE TITLE
Loading config file in k8s provider panics

### ISSUE THREAD

**Issue by arielsalvo** [IBM-Cloud/terraform-provider-ibm#668]
Hi!

I tried what's described in GH-316 but I get a `panic: Error reading level config: strconv.ParseBool`

### Terraform Version
```
Terraform v0.11.14
+ provider.external v1.2.0
+ provider.ibm v0.17.1
+ provider.kubernetes v1.8.1
+ provider.vault v1.9.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- data.ibm_container_cluster_config
- provider.kubernetes

### Terraform Configuration Files
```hcl
data "ibm_container_cluster_config" "cloud_tools" {
  cluster_name_id   = "cloud-tools"
  config_dir        = "/tmp"
  region            = "us-east"
  resource_group_id = "${data.ibm_resource_group.cloud_tools.id}"
}
data "ibm_resource_group" "cloud_tools" {
  name = "cloud-tools"
}
provider "kubernetes" {
  load_config_file = "${data.ibm_container_cluster_config.cloud_tools.config_file_path}"
}
data "kubernetes_service" "test" {
  metadata {
    name = "kubernetes"
  }
}
```

### Panic Output
See this [GIST](https://gist.github.com/arielsalvo/26b8bf33e72031f432a6656c681f046f)

### Expected Behavior
Result shown in GH-316

### Actual Behavior
Panic parsing an unspecified bool field
The only workaround we found is parsing the yaml with externals and loading the k8s provider with actual values.

### Steps to Reproduce
1. `terraform apply`

### References
- GH-316

**Comment by hkantare** [comment]
We tried as per in this issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/316..We were successfully able to connect to kubenernetes cprovider

**Comment by hkantare** [comment]
```
data "ibm_container_cluster_config" "testacc_ds_cluster" {
  cluster_name_id = "${ibm_container_cluster.cluster.id}"
}

provider "kubernetes" {
  config_path = "${data.ibm_container_cluster_config.testacc_ds_cluster.config_file_path}"
}

resource "kubernetes_namespace" "example" {
  metadata {
    annotations {
      name = "example-annotation"
    }

    labels {
      mylabel = "label-value"
    }

    name = "terraform-example-namespace"
  }
}

```

**Comment by arielsalvo** [comment]
OK, @hkantare 
I see where I went wrong: I used `load_config_file` instead of `load_config`
That change seems to have worked.

I will close this ticket now

Thanks!
    --Ariel
