### ISSUE TITLE
`ibm_database` does not support `parameters` argument to supply additional params

### ISSUE THREAD

**Issue by poojitha-bikki** [IBM-Cloud/terraform-provider-ibm#681]
Hi there,

### Terraform Version
Terraform v.0.11.13
* provider.ibm: version = "~> 0.17"

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_database

### Expected Behavior
The resource `ibm_database` if is created to provision ICD instances, it should support all possible parameters like `key_protect_key` , `backup_id` etc...

### Actual Behavior
The resource doesn't allow addition of other parameters even through `parameters` map

### Additional Info
On the other hand, `ibm_resource_instance` can be used to provision ICD instances 
Source: https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=cloud-databases-provisioning#provisioning-with-terraform
Using the above, we can leverage some of the additional params like `key_protect_key` and `backup_id` but if I want to add additional users or white list few IP's, the `parameters` block of `ibm_resource_instance` does not take a json as value to it's keys. It only takes in primitive values (But, `users` and `whitelist` should be supplied as json/map)

**Comment by jfeddern** [comment]
Our team needs this feature as well. Would be great to see this in the near future.

**Comment by jmgalvez** [comment]
Yes, same here.

**Comment by HaddadJoe** [comment]
We need the option to create a private DB
Specifying `service-endpoints="private"` does not work either and returns `invalid or unknown key: service-endpoints`

```
Terraform v0.11.14
+ provider.ibm v0.17.3
+ provider.local v1.3.0
```

**Comment by hkantare** [comment]
Availble in release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.19.0 and above
https://ibm-cloud.github.io/tf-ibm-docs/v0.21.0/r/database.html
