### ISSUE TITLE
IBM Cloud Functions namespace support

### ISSUE THREAD

**Issue by davetropeano** [IBM-Cloud/terraform-provider-ibm#682]
Current provider has basic support for IBM Cloud Functions as a service. New support for namespaces is missing (see https://ibm-cloudplatform.slack.com/archives/C2DB7A7LY/p1565118777069600)

**Comment by khayama** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/837#issuecomment-662864183
>https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.9.0
>This release support creating the cloud functions for both CF and IAM namespace
