### ISSUE TITLE
is_security_group_rule field "remote" should not be required

### ISSUE THREAD

**Issue by dlarson04** [IBM-Cloud/terraform-provider-ibm#684]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

root@terraform-vsi:~/git/ng-terraform-master# tf -v
Terraform v0.11.14
+ provider.ibm v0.17.2
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)
Please list the resources as a list, 

- ibm_is_security_group_rule

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
```
# allow incoming ping network traffic
resource "ibm_is_security_group_rule" "egress_all" {
  group     = "${ibm_is_security_group.sg1.id}"
  direction = "egress"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should have successfully created rule

### Actual Behavior
Received
```
Error: ibm_is_security_group_rule.ingress_ping: "remote": required field is not set
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by ashishth09** [comment]
@dlarson04 
Please read the documentation here. https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/is_security_group_rule.html. `remote` is a required field as the error points out.

**Comment by dlarson04** [comment]
I received a notice from github that pointed to
https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/is_security_group_rule.html
that shows `remote` is a required field. I agree that is what the documentation says but the RIAS API  doesn't require it so it is not a required field.

See the following:  

I want to allow inbound traffic on port 80 for any address

root@riaas-api:~# IBMCLOUD_TRACE=true bx is sg-rulec 2d364f0a-a870-42c3-a554-000001596977 inbound tcp --port-min 80 --port-max 80


Creating rule for security group 2d364f0a-a870-42c3-a554-000001596977 under account IBM as user larsond@us.ibm.com...


REQUEST: [2019-08-12T11:24:17Z]
POST /v1/security_groups/2d364f0a-a870-42c3-a554-000001596977/rules?generation=1&version=2019-06-04 HTTP/1.1
Host: eu-de.iaas.cloud.ibm.com
Accept: application/json
Accept-Language:
Accept-Language:
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: vpc-infrastructure 0.4.3 / linux

{"direction":"inbound","ip_version":"ipv4","port_max":80,"port_min":80,"protocol":"tcp"}

RESPONSE: [2019-08-12T11:24:20Z] Elapsed: 2746ms
HTTP/1.1 201 Created
Content-Length: 132
Cf-Ray: 505215016dafcf20-IAD
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 12 Aug 2019 11:24:20 GMT
Server: cloudflare
Transaction-Id: c8e7a73c8b305b1a7b693a9835d95b15
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Request-Id: c8e7a73c8b305b1a7b693a9835d95b15
X-Xss-Protection: 1; mode=block

{"id":"b597cff2-38e8-4e6e-999d-000005880904","direction":"inbound","ip_version":"ipv4","protocol":"tcp","port_min":80,"port_max":80}

**Comment by hkantare** [comment]
We need to make changes to move to optional as per latest API

**Comment by hkantare** [comment]
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.17.3

**Comment by hkantare** [comment]
closing the issue
