### ISSUE TITLE
Building latest asks for access to github.ibm.com

### ISSUE THREAD

**Issue by arielsalvo** [IBM-Cloud/terraform-provider-ibm#685]
Hi!

From what I gathered, github.ibm.com is part of IBM's intranet:
```
[...]
fetch "github.ibm.com/Bluemix/riaas-go-client"
Username for 'https://github.ibm.com':
```

I was able to track this as far as GH-574

Is it no longer possible for non-IBM employees to build and/or contribute code?

Thanks!
    --Ariel

**Comment by hkantare** [comment]
Yes, we have vendored an IBM internal version of riaas-go-client - in this current build / release of IBM Cloud  Provider for Terraform.
Once, a official / public version of riaas-go-client is ready, we will change & vendor the code again; until then non-IBMer will not be able to contribute code to riaas-go-client.  You should be able to contribute code to the rest of the provider code

**Comment by arielsalvo** [comment]
Ok, is there a doc of how to get dependencies and build ignoring riaas-go-client?

**Comment by ashishth09** [comment]
How are you building it? I was able to follow the README in the repo to build it. You don't need access to IBM's github to pull riaas-go-client. It is already vendored in this repo.

A simple `go get github.com/IBM-Cloud/terraform-provider-ibm` also should be enough to get you the plugin installed in the bin directory.

**Comment by arielsalvo** [comment]
I keep getting this:
```
$ make build
==> Checking that code complies with gofmt requirements...
go vet .
go tool: no such tool "vet"
go install
vendor/github.com/hashicorp/go-getter/decompress_tar.go:4:2: cannot find package "archive/tar" in any of:
        /home/asalvo/dev/go/src/github.com/IBM-Cloud/terraform-provider-ibm/vendor/archive/tar (vendor tree)
        /home/asalvo/bin/src/archive/tar (from $GOROOT)
        /home/asalvo/dev/go/src/archive/tar (from $GOPATH)
[...]
```
So I assumed I needed to get the dependencies; I was able to get them all until I reached riaas-go-client.

I'm quite new in GO development and I'd never bumped into this one before. I didn't have this issue when I started with GH-549 and I was giving it another try now that the bug I opened in softlayer-go was merged.

I appreciate any tips

Thanks!
    --Ariel

**Comment by ashishth09** [comment]
What is your go version?
Issue `go version` to find it.

**Comment by arielsalvo** [comment]
Found the issue.... $GOROOT was pointing to the incorrect directory.

Thanks!
    --Ariel
