### ISSUE TITLE
Documentation issue: ibm_database datasource doesn't list `resource_group_id`. 

### ISSUE THREAD

**Issue by ashishth09** [IBM-Cloud/terraform-provider-ibm#686]
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.ibm_database.icdredis: Refreshing state...

Error: Error refreshing state: 1 error occurred:
	* data.ibm_database.icdredis: 1 error occurred:
	* data.ibm_database.icdredis: data.ibm_database.icdredis: No resource instance found with name [XXXX]
If not specified please specify more filters like resource_group_id if instance doesn't exists in default group, location or database

Looking into the code it is a supported field.

**Comment by hkantare** [comment]
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.17.3

**Comment by hkantare** [comment]
closing the issue
