### ISSUE TITLE
Feature Request: resource "ibm_app" path variable: please support git

### ISSUE THREAD

**Issue by snowch** [IBM-Cloud/terraform-provider-ibm#70]
### Feature Request: 

It would make deployments much simpler if the `resource "ibm_app"` path supported support git urls, e.g.

`https://[user:password@]mygit.com/myrepo.git[#tag-or-branch-or-commit-hash]`

See [orange-cloudfoundry/terraform-provider-cloudfoundry](https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry#applications) for an implementation example

### Affected Resource(s)

- `resource "ibm_app"`

**Comment by ashishth09** [comment]
Thanks for this feature request 👍
 At this point the same can be achieved via `provisioners`.

https://github.com/IBM-Bluemix/terraform-provider-ibm/blob/master/examples/ibm-app/main.tf#L1-L17 in the [example](https://github.com/IBM-Bluemix/terraform-provider-ibm/tree/master/examples/ibm-app) deployment of an app

**Comment by snowch** [comment]
Perfect, thanks!

There are also a bunch of other parameters that I need like these:

```
  health_check_type = "port"
  health_check_http_endpoint = ""
  health_check_timeout = ""
  no_route = ""
```
At some point, I will also probably need `docker_image = ""` as well.

Do you have a workaround to allow me to set the above parameters and also deploy using blue-green deployments?

**Comment by ashishth09** [comment]
Unfortunately there is no work-around for the parameters which are not supported at this point. They necessarily have to be part of the schema; they are not. We will take these as additional requirements.

Blue-green deployments can be done following the usual steps. There is no in-built support for it.
By adding routes resource and deleting them once done in the terraform configuration file you should be able to achieve the end result. Let me know if you have any questions on this process.

**Comment by snowch** [comment]
> We will take these as additional requirements.

Hmm.  IBM Cloud Schematics was looking interesting up until this.

**Comment by snowch** [comment]
> Blue-green deployments can be done following the usual steps. There is no in-built support for it.  By adding routes resource and deleting them once done in the terraform configuration file you should be able to achieve the end result. Let me know if you have any questions on this process.

Is it possible to provide an example of this in the documentation?

**Comment by ashishth09** [comment]
I don't think I would like to put that in documentation. Since this is a very common deployment we will provide you the same information by some other medium. The draft is being worked upon.

**Comment by ashishth09** [comment]
We plan to share with larger audience. Thanks for the request.

**Comment by hkantare** [comment]
@snowch here is the link to the blog where I explained how you can achieve this
https://medium.com/@hkantare/terraform-driven-blue-green-deployment-of-cloud-foundry-application-on-ibm-cloud-7b6499111a9e

**Comment by snowch** [comment]
Thanks @hkantare

**Comment by hkantare** [comment]
closing the issue.
