### ISSUE TITLE
Feature Request: resource "ibm_app" support more parameters

### ISSUE THREAD

**Issue by snowch** [IBM-Cloud/terraform-provider-ibm#71]
### Feature Request: 

It would make deployments much simpler if the `resource "ibm_app"` path supported more parameters:

```
  health_check_type = "port"
  health_check_http_endpoint = ""
  health_check_timeout = ""
  no_route = ""
  docker_image = "" 
```

See [orange-cloudfoundry/terraform-provider-cloudfoundry](https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry#applications) for an implementation example

### Affected Resource(s)

- `resource "ibm_app"`

See also: https://github.com/IBM-Bluemix/terraform-provider-ibm/issues/70 for natively supporting git paths.

**Comment by hkantare** [comment]
Closing this issue..We already supported 
   health_check_type = "port"
  health_check_http_endpoint = ""
  health_check_timeout = ""
https://ibm-cloud.github.io/tf-ibm-docs/v0.17.1/r/app.html
