### ISSUE TITLE
iam_access_group_policy doc update

### ISSUE THREAD

**Issue by van-ibm** [IBM-Cloud/terraform-provider-ibm#716]
The iam_access_group_policy documentation has the following guidance:

```
service - (Optional, string) Service name of the policy definition. You can retrieve the value by running the ibmcloud catalog service-marketplace or ibmcloud catalog search command in the IBM Cloud CLI.
```

However there is also the ability to specify account management policies.  For that you need to know the account management service IDs.  This is not so easily found.  I applied them manually using the UI and then inspected the policy with the CLI to figure them out.  They are:

All Enterprise resources - enterprise
All Global Resource Catalog resources- globalcatalog
All Support Center resources - support
All User Management resources - user-management
All IAM Access Groups Service resources- iam-groups
All Billing resources - billing

I've raised a doc defect to get these added to the documentation better; however, it may be worth list the service names in the docs alongside existing guidance.

**Comment by kavya498** [comment]
Link provide [here](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/iam_access_group_policy#roles) gives details of service and its roles..

Kindly reopen this issue and tag this issue, if issue still persists..
Closing this issue..
Thanks
