### ISSUE TITLE
Feature Request:  provide support blue/green deployments directly in the `resource "ibm_app"` 

### ISSUE THREAD

**Issue by snowch** [IBM-Cloud/terraform-provider-ibm#72]
### Feature Request: 

It would make deployments much simpler if the `resource "ibm_app"` supported blue/green deployments.

See [orange-cloudfoundry/terraform-provider-cloudfoundry](https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry#applications) for an implementation example

### Affected Resource(s)

- `resource "ibm_app"`

**Comment by hkantare** [comment]
closing this issue..We shared a blog on how to achieve 
https://medium.com/@hkantare/terraform-driven-blue-green-deployment-of-cloud-foundry-application-on-ibm-cloud-7b6499111a9e
