### ISSUE TITLE
Feature Request: Support cluster addons

### ISSUE THREAD

**Issue by barlock** [IBM-Cloud/terraform-provider-ibm#721]
Provide a native mechanism to configure cluster add-ons.

Equivalent of "ibmcloud ks cluster-addons-*" 

### Terraform Version
0.11.x

### Affected Resource(s)
n/a

**Comment by barlock** [comment]
Likely depends on bluemix-go support https://github.com/IBM-Cloud/bluemix-go/issues/148

**Comment by somaya10** [comment]
👍 in need of this feature!

**Comment by maristgeek** [comment]
:+1: especially with Cluster Autoscaler moving from a helm chart to an addon.

**Comment by hkantare** [comment]
The support for addons is released in latest  v1.2.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.12.0
Docs :https://cloud.ibm.com/docs/terraform?topic=terraform-container-resources#container-addon

**Comment by ifs-pauljegouic** [comment]
@hkantare , not working on other resource_group !=Default

```hcl
provider "ibm" {
    region = "eu-de"
    generation = 2
}

data "ibm_container_vpc_cluster" "cluster" {
  name  = "paul-dataplatform-cluster"
  resource_group_id = "40469f682f5a48ee8f5060da1959d111"
}

resource "ibm_container_addons" "addons" {
  cluster = data.ibm_container_vpc_cluster.cluster.name
  addons {
    name    = "cluster-autoscaler"
    version = "1.0.1"
  }
}


output "cluster" {
  value = data.ibm_container_vpc_cluster.cluster
}

```

```hcl
➜  tmp2 terraform apply --auto-approve
data.ibm_container_vpc_cluster.cluster: Refreshing state...
ibm_container_addons.addons: Creating...

Error: Request failed with status code: 404, ServerErrorResponse: {"incidentID":"5d93a32861e3b7ab-CDG","code":"G0004","description":"The specified cluster could not be found. If applicable, make sure that you target the correct account and resource group.","type":"General","recoveryCLI":"To list the clusters you have access to, run 'ibmcloud ks cluster ls'. To list the resource groups that you have access to, run 'ibmcloud resource groups'. To target the resource group, run 'ibmcloud target -g \u003cresource_group\u003e'."}

  on main.tf line 12, in resource "ibm_container_addons" "addons":
  12: resource "ibm_container_addons" "addons" {
```

Please add support for property `resource_group_id`

**Comment by ifs-pauljegouic** [comment]
@kavya498 Please fix this feature

**Comment by mailtokun** [comment]
> @hkantare , not working on other resource_group !=Default
> 
> ```terraform
> provider "ibm" {
>     region = "eu-de"
>     generation = 2
> }
> 
> data "ibm_container_vpc_cluster" "cluster" {
>   name  = "paul-dataplatform-cluster"
>   resource_group_id = "40469f682f5a48ee8f5060da1959d111"
> }
> 
> resource "ibm_container_addons" "addons" {
>   cluster = data.ibm_container_vpc_cluster.cluster.name
>   addons {
>     name    = "cluster-autoscaler"
>     version = "1.0.1"
>   }
> }
> 
> 
> output "cluster" {
>   value = data.ibm_container_vpc_cluster.cluster
> }
> ```
> 
> ```terraform
> ➜  tmp2 terraform apply --auto-approve
> data.ibm_container_vpc_cluster.cluster: Refreshing state...
> ibm_container_addons.addons: Creating...
> 
> Error: Request failed with status code: 404, ServerErrorResponse: {"incidentID":"5d93a32861e3b7ab-CDG","code":"G0004","description":"The specified cluster could not be found. If applicable, make sure that you target the correct account and resource group.","type":"General","recoveryCLI":"To list the clusters you have access to, run 'ibmcloud ks cluster ls'. To list the resource groups that you have access to, run 'ibmcloud resource groups'. To target the resource group, run 'ibmcloud target -g \u003cresource_group\u003e'."}
> 
>   on main.tf line 12, in resource "ibm_container_addons" "addons":
>   12: resource "ibm_container_addons" "addons" {
> ```
> 
> Please add support for property `resource_group_id`

I got same error. Please support resource_group_id

**Comment by mailtokun** [comment]
opened an issue for tracking : https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1920

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.13.0
