### ISSUE TITLE
Failed to import existing `ibm_database`

### ISSUE THREAD

**Issue by ganhuang** [IBM-Cloud/terraform-provider-ibm#734]
### Terraform Version
Terraform v0.11.11
+ provider.ibm v0.17.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_database

### Terraform Configuration Files
```
resource "ibm_database" "jms" {
  name              = "${var.prefix}-${var.env}-${var.location}-jms-postgresql-${var.postgresql_count}"
  plan              = "standard"
  location          = "us-east"
  service           = "databases-for-postgresql"
  resource_group_id = "${data.ibm_resource_group.group.id}"
  version           = "${var.postgresql_version}"

  adminpassword              = "${random_string.postgres_admin_password.result}"
  members_disk_allocation_mb = 128000

  whitelist = {
    address     = "10.0.0.0/28"
    description = "test"
  }
}
```

### Debug Output
https://gist.github.com/ganhuang/4fb7cb4ac7912692fc87cae59de00c10

### Actual Behavior

```
Error: ibm_database.jms (import id: crn:v1:bluemix:public:databases-for-postgresql:us-east:a/xxxxxxxxxxxxxxxxxxxx::): 1 error(s) occurred:

* import ibm_database.jms result: crn:v1:bluemix:public:databases-for-postgresql:us-east:a/xxxxxxxxxxxxxxxxxxxxxx::: ibm_database.jms: Error getting database groups: Request failed with status code: 404, ServerErrorResponse: {"errors":"not_found"}
```

### Steps to Reproduce
Import an existing `databases-for-postgresql` resource on IBM
1. `terraform import ibm_database.jms crn:v1:bluemix:public:databases-for-postgresql:us-east:a/xxxxx:xxxxxx::`

**Comment by ganhuang** [comment]
@hkantare I didn't export the variable, still no luck after exported the variable, same error.

> More info can be found under here under import section
https://ibm-cloud.github.io/tf-ibm-docs/v0.17.3/r/resource_instance.html

hmm, I can't find any section about `import`, anything I missed?

**Comment by hkantare** [comment]
sorry by bad...I have pasted wrong link...https://ibm-cloud.github.io/tf-ibm-docs/v0.17.3/r/database.html

**Comment by ganhuang** [comment]
@hkantare Thanks for your help, now it succeeded to import the resource once adding `region = "us-east"` to `provider.tf`.
