### ISSUE TITLE
GHE code in public repository

### ISSUE THREAD

**Issue by davetropeano** [IBM-Cloud/terraform-provider-ibm#737]
We have GitHub Enterprise code in this repository. This prevents external parties from compiling their own version of the provider. Going forward we need to verify that the provider can be built as-is only from opensource.

Example file: https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/config.go

**Comment by kavya498** [comment]
Closing this..as we removed all GHE code..
thanks..
