### ISSUE TITLE
softlayer_username and softlayer_api_key should be deprecated

### ISSUE THREAD

**Issue by davetropeano** [IBM-Cloud/terraform-provider-ibm#738]
Replace provider params `softlayer_api_key` and `softlayer_username` with `iaas_api_key` and `iaas_username` or other more suitable name

**Comment by hkantare** [comment]
The fields are deprecated and used iaas_classic api_key and iaas_classic_username
https://ibm-cloud.github.io/tf-ibm-docs/v0.18.0/
