### ISSUE TITLE
Feature Request: remove Bulk_VM minimum limitation

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#740]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.14
+ provider.ibm v0.17.3

### Affected Resource(s)
- ibm_compute_vm_instance

### Problem
currently the bulk_vm option for the ibm_compute_vm_instance need at least a minimum of 2 VMs (bulk_vms - (Optional, list) List of hostname and domain of the computing instance. The minimum number of vm’s to be defined is 2)

I have written a terraform module which orders expensive VMs. My problem is that some solutions just require to order 1 vm and not more. Can you please remove the minimum of 2 VMs limitation? Very important when you write modules!

**Comment by ThomasUllrich666** [comment]
any Updates to this?

**Comment by hkantare** [comment]
We made a limit of 2 because we will not able to distinguish between whether we used hostname/domain or bulk_vms property to provision instances

**Comment by ThomasUllrich666** [comment]
Don't get it. 
If hostname && domain =="" then use bulk_vms  ?

Any other Idea how I can solve my problem? In my dev and test environment, one VM is enough for my purposes (the VM is very expensive). But in my prod Environment I need at least 3 of them.

**Comment by ThomasUllrich666** [comment]
@hkantare any updates here?

**Comment by hkantare** [comment]
IF we remove limit on  bulk_vms then when we use import scenario when user pass id then it will be difficult decide whether it should update hostname and domain or bulk VMS. If we keep a limit and when user run terrafrom import ibm_compute_vm_instance.go.test id1|id2.....then it indicates it should be updated for bulk_vm.

terrafrom import ibm_compute_vm_instance.go.test id then it should set hostname and domain

**Comment by hkantare** [comment]
instead of using bulk_vm please use the concept of terraform count to provision the VMS?
https://www.terraform.io/intro/examples/count.html

```
resource "ibm_compute_vm_instance" "infranode" {
  count                     = "${var.infra_node_count}"
  os_reference_code         = "${var.infra_os_ref_code}"
  hostname                  = "${var.infra_hostname_prefix}-${var.random_id}-${var.infra_hostname}-${count.index}"
  domain                    = "${var.domain}"
  datacenter                = "${var.datacenter}"
  private_network_only      = "false"
  network_speed             = 1000
  local_disk                = "false"
  flavor_key_name           = "${var.infra_flavor}"
  ssh_key_ids               = ["${var.infra_ssh_key_ids}"]
  private_vlan_id           = "${var.private_vlan_id}"
  public_vlan_id           = "${var.public_vlan_id}"
  public_security_group_ids = ["${var.infra_node_pub_sg}"]
  private_security_group_ids = ["${var.infra_node_prv_sg}"]
  hourly_billing             = "${var.hourly_billing}"
}
```

**Comment by ThomasUllrich666** [comment]
@hkantare. Thank you for the information!! I didn't know that this works. (maybe you can add it to the documentation with this example above) 

Thank you Very much.
