### ISSUE TITLE
Multizone cluster creation - avoid default_pool_size

### ISSUE THREAD

**Issue by jmgalvez** [IBM-Cloud/terraform-provider-ibm#741]
Hi there,

We are trying to create a **multizone** cluster in 3 different zones, same region. Documentation of the latest available version says:

_default_pool_size - (Optional,int) The number of workers created under the default worker pool which support Multi-AZ._

**### Terraform Version**
- Terraform v0.11.14

**### Affected Resource(s)**
- ibm_container_cluster (provider.ibm v0.17.3)

### Expected Behavior
We would like to avoid this parameter, because it is not useful for us. We have used the  _ibm_container_worker_pool_ and _ibm_container_worker_pool_zone_attachment_  resources in order to define the desired worked nodes and zones attachments.

### Actual Behavior
If you do not specify this argument, the cluster is created with a worker node in the default worker pool. Please check the first line in the following output.

```
ID                                        Public IP Private IP      Flavor          State   Status  Zone    Version   
kube-b...g0-anotherk8s-default-0000011f   158.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra02   1.15.3_1517   
kube-b...g0-anotherk8s-edge-00000251      158.xxx   10.xxx   b2c.4x16.encrypted    normal   Ready   fra02   1.15.3_1517   
kube-b...g0-anotherk8s-edge-000003e6      158.xxx   10.xxx   b2c.4x16.encrypted    normal   Ready   fra02   1.15.3_1517   
kube-b...g0-anotherk8s-edge-00000718      161.xxx   10.xxx   b2c.4x16.encrypted    normal   Ready   fra04   1.15.3_1517   
kube-b...g0-anotherk8s-edge-0000084c      161.xxx   10.xxx   b2c.4x16.encrypted    normal   Ready   fra04   1.15.3_1517   
kube-b...g0-anotherk8s-edge-00000c9c      149.xxx   10.xxx   b2c.4x16.encrypted    normal   Ready   fra05   1.15.3_1517   
kube-b...g0-anotherk8s-edge-00000dcb      149.xxx   10.xxx   b2c.4x16.encrypted    normal   Ready   fra05   1.15.3_1517   
kube-b...g0-anotherk8s-worker-000004f4    149.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra05   1.15.3_1517   
kube-b...g0-anotherk8s-worker-00000574    149.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra05   1.15.3_1517   
kube-b...g0-anotherk8s-worker-00000651    149.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra05   1.15.3_1517   
kube-b...g0-anotherk8s-worker-00000951    161.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra04   1.15.3_1517   
kube-b...g0-anotherk8s-worker-00000a5e    161.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra04   1.15.3_1517   
kube-b...g0-anotherk8s-worker-00000b09    161.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra04   1.15.3_1517   
kube-b...g0-anotherk8s-worker-00000e99    158.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra02   1.15.3_1517   
kube-b...g0-anotherk8s-worker-00000f91    158.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra02   1.15.3_1517   
kube-b...g0-anotherk8s-worker-00001001    158.xxx   10.xxx   c2c.16x32.encrypted   normal   Ready   fra02
```

### References

There was a similar issue reported on [github#344](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/344) "It should be possible to create a ibm_container_cluster with default_pool_size = 0", but was closed abruptly.

**Comment by hkantare** [comment]
Its a restriction from cluster API if user doesn't provide any value it creates a 1 worker in worker pool. it is not possible in the IBM Cloud to create a Kubernetes cluster with only a master node and no worker nodes. 
So the requirement should go to container API team.

**Comment by ruben-burr** [comment]
@hkantare,  do you think it would be possible for you to forward this request internally to the right people?

**Comment by grazius** [comment]
+1 on this request

**Comment by hkantare** [comment]
When we create a cluster by default it creates with one worker in default worker pool. Ref: https://cloud.ibm.com/docs/containers?topic=containers-cli-plugin-kubernetes-service-cli#cs_cluster_create
****
The number of worker nodes that you want to deploy in your cluster. If you do not specify this option, a cluster with one worker node is created. 
****

We will open a ticket on IKS API for the requirement

**Comment by hkantare** [comment]
Issue IKS : https://github.ibm.com/alchemy-containers/armada-api/issues/4218

**Comment by kavya498** [comment]
Similar to #2949 
Kindly track using #2949..

Closing this issue..
Thanks
