### ISSUE TITLE
modifying block storage sizes causes replacement of blockstorage

### ISSUE THREAD

**Issue by davem-git** [IBM-Cloud/terraform-provider-ibm#743]
### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_storage_block

Ihttps://github.com/IBM-Cloud/terraform-provider-ibm/blob/e948868b5f39d421c2292139fbbde77b70b9e365/ibm/resource_ibm_storage_block.go#L43

modifying block storage volume size causes the creation of new block storage. This doesn't make sense for cases of increasing size. We can modify it 

ibmcloud sl block volume-modify <ID> --new-size 80

**Comment by hkantare** [comment]
Update support is available as part of https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.21.0
