### ISSUE TITLE
resource 'ibm_container_cluster.cluster' config: unknown resource 'random_id.name' referenced in variable random_id.name.hex

### ISSUE THREAD

**Issue by AnishAnil** [IBM-Cloud/terraform-provider-ibm#744]
I'm using the code provided out of the box from the link below

https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-cluster-update

On running terraform plan it fails with the below error

terraform init

Error: resource 'ibm_container_cluster.cluster' config: unknown resource 'random_id.name' referenced in variable random_id.name.hex

terraform plan

Error: resource 'ibm_container_cluster.cluster' config: unknown resource 'random_id.name' referenced in variable random_id.name.hex

Could you please suggest on the way forward

**Comment by hkantare** [comment]
Can you please let me know what terraform version you are using. 
Can you run terraform init command and share us the o/p

**Comment by hkantare** [comment]
The  configuration is missing random resource here https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-cluster-update/main.tf 
please add
```
resource "random_id" "name" {
  byte_length = 4
}
```
We will update the example

**Comment by AnishAnil** [comment]
terraform --version
Terraform v0.11.14

We are using IBM Cloud so the latest supported one for testing is the above version only
Post Adding the resource it works ti initiate.
Thank you

**Comment by hkantare** [comment]
closing the issue
