### ISSUE TITLE
Add parameter subnet_id to resource ibm_container_worker_pool_zone_attachment

### ISSUE THREAD

**Issue by jfeddern** [IBM-Cloud/terraform-provider-ibm#747]
Hi there,

currently it is not possible to add specific subnet_id's during the worker pool zone attachment.
We would like to have the possibility to add the subnet_id as well.

### Terraform Version
- Terraform v0.11.14

### Affected Resource(s)
- ibm_container_worker_pool_zone_attachment

### Expected Behavior
Same behavior as during the cluster creation with Terraform resource ibm_container_cluster.
Beside of the VLAN we would like to add multiple subnet_id's during the worker pool zone attachment.

### Actual Behavior
Worker pool is attached to the provided VLAN but not to a subnet. We have to add the new worker pools to the subnets manually.

Kind regards,
Jan

**Comment by hkantare** [comment]
In the current version of IKS, the v1 API does *not* support subnet_id during creation of classic worker-pool zone attachment.  It accepts only VLAN Id's
Ref: https://containers.cloud.ibm.com/global/swagger-global-api/#/clusters/AddWorkerPoolZone

In the newer version of IKS on VPC; the v2 API support subnet_id for VPC cluster worker-pool zone attachment.  Ref: 
https://containers.cloud.ibm.com/global/swagger-global-api/#/v2/vpcCreateWorkerPoolZone.

We are developing a new terraform resource for the IKS cluster on VPC (using the v2 API).  This feature will be available in the Nov release of IBM Cloud Provider.

**Comment by hkantare** [comment]
closing the issue
