### ISSUE TITLE
Feature Request: CRUD operations for routes in VPC

### ISSUE THREAD

**Issue by CosmicQ** [IBM-Cloud/terraform-provider-ibm#773]
Please add the ability to create and delete routes for VPC.

Currently the ability exists, but only via the API:

_(https://cloud.ibm.com/apidocs/vpc-on-classic#create-a-route-on-your-vpc)_

This would be a huge benefit when creating (non-IBM, like openswan) VPN connections between multi-zone VPCs.

**Comment by hkantare** [comment]
Available as part of v0.18.0 release https://ibm-cloud.github.io/tf-ibm-docs/v0.18.0/r/is_vpc_route.html
