### ISSUE TITLE
Feature request: have "label" property in "ibm_container_cluster"

### ISSUE THREAD

**Issue by hjweds** [IBM-Cloud/terraform-provider-ibm#775]
A client wants to have "labels" property in "ibm_container_cluster", so that they can set the label of worker nodes in the default pool when they provision the cluster, similar to the "labels" property in "ibm_container_worker_pool".

**Comment by krakel** [comment]
also we need this feature

**Comment by allen-servedio** [comment]
Agreed - we also need this feature @hkantare so that we can use the labels within Kubernetes as well as for billing purposes.

**Comment by mschenk42** [comment]
I need this feature too.  It would be great to have this.

**Comment by shveik** [comment]
yup, +1
