### ISSUE TITLE
Unable to deploy free IKS cluster using Terraform

### ISSUE THREAD

**Issue by vknemanavar** [IBM-Cloud/terraform-provider-ibm#785]
Hi there,

### Terraform Version
Terraform v0.11.8
+ provider.ibm v0.17.6

### Affected Resource(s)
ibm_container_cluster

### Terraform Configuration Files
resource "ibm_container_cluster" "vk_test_cluster" {
  name         = "vktest-free"
  machine_type = "free"
  hardware     = "shared"
  datacenter   = "dal10"
}
```


### Expected Behavior
It should provision free IKS cluster

### Actual Behavior
Getting error "bm_container_cluster.vk_test_cluster: The targeted resource group could not be found. Make sure you have required permissions to access the resource group"
Though resource group is not mandatory field and also I am able to deploy the cluster from the UI without mentioning the resource group name

### Steps to Reproduce
1. `terraform apply`

**Comment by ossm1db** [comment]
I am able to create free IKS clusters with Terraform. You must explicitly be granted access to [Resource Groups](https://cloud.ibm.com/account/resource-groups) in Manage --> Users --> You --> Access policies.

**Comment by hkantare** [comment]
closing the issue based on above comment
