### ISSUE TITLE
mac catalina permission problems

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#790]
The latest OS update from mac - Catalina is raising some potential security issues and warnings.  I was messing about quite a bit while getting this working but here is the general flow after Catalina

1. Executing terraform failed,  Followed the instructions here: https://github.com/hashicorp/terraform/issues/23033#issuecomment-539736692

2. Executing the terraform apply using the ibm plugin failed
![image](https://user-images.githubusercontent.com/6932057/66773781-b150f280-ee74-11e9-9916-9bc3bbbda138.png)

Fixed it in preferences:

![image](https://user-images.githubusercontent.com/6932057/66773794-be6de180-ee74-11e9-85ff-442c39f9107c.png)

Then ran terraform again and still needed to click open:
![image](https://user-images.githubusercontent.com/6932057/66773830-d7769280-ee74-11e9-9de6-efc563ee77de.png)

3. Copied a new plugin into the .terraform/plugins directory and then back in the terraform configuration:
```
rm -rf .terraform
terraform init
terraform apply
```

Had the problem again.   So every plugin download seems likely to hit this problem.

### Expected
In order of desirability:
1. ibm plugin would be in the standard terraform place and automatically work
2. downloaded plugin would work with no security dialogs

**Comment by ZVilusinsky** [comment]
Confirming this on v1.2.3 and it's quite annoying.

**Comment by l2fprod** [comment]
this is still there on the latest release. An option is to run `xattr -r -d com.apple.quarantine terraform-provider-ibm_v1.7.1` on the command line (https://developer.apple.com/developer-id/).

**Comment by hkantare** [comment]
We are working on process of making the binary notarization

**Comment by hkantare** [comment]
We are done with mac notarization process availble from last couple of releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.21.1
