### ISSUE TITLE
Require paramter for ibm_lbaas to choose public IP pool

### ISSUE THREAD

**Issue by hjweds** [IBM-Cloud/terraform-provider-ibm#792]
When I provision a public-to-private load balancer, there is an option to choose public IPs from either IBM system pool or a public subnet within my account:
![image](https://user-images.githubusercontent.com/26032834/66910785-88189980-f00f-11e9-9dfa-e53e42d328c9.png)
But in terraform `ibm_lbaas`, there is no such parameter to specify my choice: https://ibm-cloud.github.io/tf-ibm-docs/v0.17.6/r/lbaas.html.
It is crucial to include that parameter in terraform

**Comment by hkantare** [comment]
Fixed in v0.18.0 Release https://github.com/IBM-Cloud/terraform-provider-ibm/releases

**Comment by hkantare** [comment]
closing the issue
