### ISSUE TITLE
Schematics IAM access segmentation per workspace

### ISSUE THREAD

**Issue by paribiswas** [IBM-Cloud/terraform-provider-ibm#805]
Schematics does not support workspace level access control. An user in an account has access to all the workspaces in the account. The customer, BNPP-BP2I, wants to implement a solution where they would like to give access specific workspace(s) to users of a project team.

The ask for this user story is to provide IAM access control for Schematics at the workspace level, not at account level

**Comment by stevestrutt** [comment]
Workspace level IAM policy controls are under active development and the tentative plan is they will be available in the next 2-4 weeks.

**Comment by hkantare** [comment]
closing this issue its handles in schematics
