### ISSUE TITLE
Terraform to support database parameters in ibm_database block

### ISSUE THREAD

**Issue by paribiswas** [IBM-Cloud/terraform-provider-ibm#806]
In IBM Cloud Provider for Terraform, does not support the following attributes in ibm_database block.
- version
- members_cpu_allocation_count
- service-endpoints
- key_protect_key
- backup_id

These are supported in the ibm_resource_instance block (as parameters). However, the ibm_resource_instance block does not provide support to set admin password, new user name and password, whitelist IPs, etc.
Our client, BNPP, would like to have these parameters (arguments) supported in the ibm_database block.

**Comment by hkantare** [comment]
Fixed in v0.18.0 relelase
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/dev-v0.18.0
