### ISSUE TITLE
ibm_database for postgres whitelist is more restrictive than the API

### ISSUE THREAD

**Issue by arielsalvo** [IBM-Cloud/terraform-provider-ibm#811]
Hi

I have a whitelist, added via the panel, for a /16 subnet but when I try to import it in TF I get an error saying: `expected "whitelist.0.address" to contain a network CIDR with between 24 and 32 significant bits, got: 16`

### Terraform Version
Terraform v0.11.14
+ provider.ibm v0.17.2
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.vault v1.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_database

### Terraform Configuration Files
```hcl
resource ibm_database test {
  name              = "test-01"
  plan              = "standard"
  location          = "us-east"
  service           = "databases-for-postgresql"
  resource_group_id = "${ibm_resource_group.test.id}"
  adminpassword                = "4dm1nP4$$w0rd"
  members_memory_allocation_mb = 2048
  members_disk_allocation_mb   = 10240
  users = {
    name     = "testusr"
    password = "t3stP4$$w0rd"
  }
  whitelist = [
    {
      address     = "172.30.0.0/16",
      description = "Kubernetes pod subnet",
    }
  ]
}
```

### Expected Behavior
The whitelist should be allowed since the admin panel allows it.

### Actual Behavior
`expected "whitelist.0.address" to contain a network CIDR with between 24 and 32 significant bits, got: 16`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by hkantare** [comment]
Fixed in latest releases v0.18.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/dev-v0.18.0
