### ISSUE TITLE
data.ibm_cos_bucket.bucket: Provider doesn't support data source: ibm_cos_bucket

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#817]
New Feature

data should be provided for ibm_cos_bucket that will allow other resources to use an existing bucket id in their configuration.  Buckets should be fundamental to the ibm cloud.  That said I do not have a use case for this today.

```
variable region {
  default = "us-south"
}
variable ibmcloud_api_key {}

provider "ibm" {
  region             = "${var.region}"
  ibmcloud_api_key = "${var.ibmcloud_api_key}"
}

data "ibm_cos_bucket" "bucket" {
}

```

### Terraform Version
```
~/tmp/tfbugs/tfcosbucketdata $ tf version
Terraform v0.11.14
+ provider.ibm v0.18.0
```

### Affected Resource(s)
```
~/tmp/tfbugs/tfcosbucketdata $ tfa

Error: data.ibm_cos_bucket.bucket: Provider doesn't support data source: ibm_cos_bucket

```

**Comment by n-marton** [comment]
the problem with this, that only from the bucket name and resource id, it is not possible to determine which S3 api to use 

it would be possible but it would require almost every attribute to be filled, I don't know if this way the data source is even worth using

**Comment by powellquiring** [comment]
@n-marton , I think you are saying this resource should be removed from the provider, right?  If so can you create the pull request to remove it?

**Comment by n-marton** [comment]
I don't get it, what do you think should be removed?

ibm_cos_bucket.bucket as a resource is a must have
ibm_cos_bucket.bucket as a data source does not exist

**Comment by powellquiring** [comment]
Whoops, sorry, I was confused.  See #816

**Comment by n-marton** [comment]
then it is closable :)

**Comment by powellquiring** [comment]
Whoops, 😐 again. This is a new feature request.  Why would it required more parameters then the creation of the bucket?

**Comment by n-marton** [comment]
not more, but almost the same amount, to get a bucket you need the bucket name and the cos instance id, which are alright, but you also need to pass information about if that bucket is a single site / region / cross regional, and also need to pass the region, that information is all required to select the correct s3 api

**Comment by n-marton** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/834

**Comment by n-marton** [comment]
feature added with 0.19.0, this can be closed
