### ISSUE TITLE
0.18.0 documentation is not correctly indented

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#826]
Go to https://ibm-cloud.github.io/tf-ibm-docs/v0.18.0/

See how the Power resources are incorrectly nested under Cloud Object Storage:

![image](https://user-images.githubusercontent.com/12746550/67694849-14ad4b00-f972-11e9-9e00-5ee443ae0bad.png)

**Comment by hkantare** [comment]
Fixed now https://ibm-cloud.github.io/tf-ibm-docs/v0.18.0/
