### ISSUE TITLE
terraform apply hangs after nodes were provisioned

### ISSUE THREAD

**Issue by Zman94** [IBM-Cloud/terraform-provider-ibm#839]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
 ~/P/t/l/softlayer   master  tf11 -v
Terraform v0.11.13
+ provider.ibm (unversioned)
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
```
I can't use tf 12 because it is incompatible with this version of the provider 

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_storage_block.infranode_block
- ibm_storage_block.appnode_block
- ibm_storage_block.bastionnode_block
- ibm_storage_block.masternode_block

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
If required, I'll have to upload a zip file

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

Small debug output 
```
2019-11-04T15:58:54.058-0500 [DEBUG] plugin.terraform-provider-ibm: 2019/11/04 15:58:54 [DEBUG] Request URL:  GET https://api.softlayer.com/rest/v3/SoftLayer_Account/getNetworkStorage.json?objectFilter=%7B%22networkStorage%22%3A%7B%22billingItem%22%3A%7B%22orderItem%22%3A%7B%22order%22%3A%7B%22id%22%3A%7B%22operation%22%3A%2248276830%22%7D%7D%7D%7D%7D%7D&objectMask=mask%5Bid%2CbillingItem.orderItem.order.id%5D

2019-11-04T15:58:54.325-0500 [DEBUG] plugin.terraform-provider-ibm: 2019/11/04 15:58:54 [DEBUG] Parameters:

2019-11-04T15:58:54.449-0500 [DEBUG] plugin.terraform-provider-ibm: 2019/11/04 15:58:54 [DEBUG] Status Code:  200

2019-11-04T15:58:54.449-0500 [DEBUG] plugin.terraform-provider-ibm: 2019/11/04 15:58:54 [DEBUG] Response:  []

2019-11-04T15:58:54.450-0500 [DEBUG] plugin.terraform-provider-ibm: 2019/11/04 15:58:54 [TRACE] Waiting 10s before next try
```
This is repeated for all 4 nodes

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
Program should've exited gracefully because all nodes have been deployed

### Actual Behavior
What actually happened?
Program hangs here repeating every 10 seconds

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by hkantare** [comment]
Can you please upload the configuration and the output log after exporting TF_LOG=debug

**Comment by Zman94** [comment]
Hello. This is with TF_LOG=DEBUG

**Comment by hkantare** [comment]
can you upload to https://gist.github.com/ the log and share us the link

**Comment by Zman94** [comment]
It looks like the issue had to do with the storageclass object. I removed those resources and now the script is completing fine
