### ISSUE TITLE
The provider provider.ibm does not support resource type "ibm_pi_key".

### ISSUE THREAD

**Issue by aklyachkin** [IBM-Cloud/terraform-provider-ibm#840]
### Terraform Version
terraform -v
Terraform v0.12.12
+ provider.ibm v1.0.0

### Affected Resource(s)
ibm_pi_key
ibm_pi_network

### Terraform Configuration Files
```hcl
resource "ibm_pi_key" "andrewk_ssh" {
  pi_key_name          = "andrewk-ssh"
  pi_ssh_key           = "ssh-rsa ..."
  pi_cloud_instance_id = "${var.pi_cloud_id}"
}

resource "ibm_pi_network" "aix_net" {
  pi_network_name      = "aix_net"
  pi_network_type      = "vlan"
  pi_dns               = ["8.8.8.8"]
  pi_cidr              = "10.0.0.0/24"
  pi_cloud_instance_id = "${var.pi_cloud_id}"
}
```

### Expected Behavior
...
ibm_pi_network.aix_net: Creating...
  pi_cidr:              "" => "10.0.0.0/24"
  pi_dns.#:             "0" => "1"
  pi_dns.2609393598:    "" => "8.8.8.8"
  pi_network_name:      "" => "aix_net"
  pi_network_type:      "" => "vlan"
  pi_networkid:         "" => "<computed>"
  pi_vlan_id:           "" => "<computed>"

### Actual Behavior
Error: Invalid resource type

  on common.tf line 8, in resource "ibm_pi_key" "andrewk_ssh":
   8: resource "ibm_pi_key" "andrewk_ssh" {

The provider provider.ibm does not support resource type "ibm_pi_key".

Error: Invalid resource type

  on common.tf line 14, in resource "ibm_pi_network" "aix_net":
  14: resource "ibm_pi_network" "aix_net" {

The provider provider.ibm does not support resource type "ibm_pi_network".

### Steps to Reproduce
1. `terraform plan`

**Comment by hkantare** [comment]
Terraform ibm provider version v1.0.0 is only for VPC (terraform version v0.12) its a per-release 

Please use https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.18.0 for power instance support (terraform v0.11.x)
