### ISSUE TITLE
Crash creating ibm_pi_key resource

### ISSUE THREAD

**Issue by aklyachkin** [IBM-Cloud/terraform-provider-ibm#842]
### Terraform Version
Terraform v0.11.14
IBM provider v0.18.0

### Affected Resource(s)
ibm_pi_key

### Terraform Configuration Files
```hcl
resource "ibm_pi_key" "andrewk_ssh" {
  pi_key_name          = "andrewk-ssh"
  pi_ssh_key           = "ssh-rsa ..."
  pi_cloud_instance_id = "${var.pi_cloud_id}"
}
```

### Panic Output
https://gist.github.com/aklyachkin/2c52fab1ede0a0a4e05721fef9f262ad

### Expected Behavior
Key is created, no errors

### Actual Behavior
Key is created, I see it in the web console, but terraform produces the error:
```
Error: Error applying plan:

1 error occurred:
	* ibm_pi_key.andrewk_ssh: 1 error occurred:
	* ibm_pi_key.andrewk_ssh: unexpected EOF
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Mac OS X

**Comment by surajsub** [comment]
Code has been updated and fixed in the latest release of the provider

**Comment by aklyachkin** [comment]
Thanks for the answer. I built the latest commit, it doesn't crash anymore, but if the key already exists, it produces the error even if the key was created by terraform:

```
ibm_pi_key.andrewk_ssh: Refreshing state... (ID: a1491883-109f-8992-5a5b-a590172e7a4e)
ibm_pi_key.andrewk_ssh: Creating...
...
	* ibm_pi_key.andrewk_ssh: 1 error occurred:
	* ibm_pi_key.andrewk_ssh: {"description":"andrewk-ssh sshkey name already exists; duplicate names are not allowed","error":"Conflict"}
```

**Comment by surajsub** [comment]
Will take a look at this.

**Comment by hkantare** [comment]
Can you please try with latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.2
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v10.24.2

**Comment by hkantare** [comment]
Can you please try with latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.2
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v10.24.2

**Comment by aklyachkin** [comment]
ssh key works now! No crashes, it is discovered correctly at the next run, looks good! Thank you.
