### ISSUE TITLE
Cannot add a label to an existing ibm_container_worker_pool

### ISSUE THREAD

**Issue by pnagleIBM** [IBM-Cloud/terraform-provider-ibm#857]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
terraform -v
Terraform v0.11.14

### Affected Resource(s)
- ibm_container_worker_pool

### Expected Behavior
When I alter the TF module that describes the worker pools in my cluster to add a label, then the label should get added.

### Actual Behavior
The label did not get added

### Steps to Reproduce
Create an ibm_container_worker_pool via TF with no `label` variable in the module
Next edit the module to include a `label`
Notice that no label gets added

**Comment by wderezin** [comment]
Also, need the ability to change the value of label that is already added.

**Comment by kavya498** [comment]
Closing this issue
Available in [1.18.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.18.0) and above versions
Thanks
