### ISSUE TITLE
Support for k8s version in resource ibm_container_cluster

### ISSUE THREAD

**Issue by bonifaido** [IBM-Cloud/terraform-provider-ibm#86]

**Comment by IBMRob** [comment]
👍 This would really help us as it would save us having to upgrade the cluster as a first action

**Comment by marchmallow** [comment]
It would be nice also if a new version comes up to have terraform drive update/downgrade to a different version if one changes after the first apply (probably downgrade less critical but could need it too)

**Comment by ashishth09** [comment]
@marchmallow  Absolutely 👍 , we will do that as part of this and should be available in the next release of the provider.

**Comment by TheSamSmith** [comment]
@ashishth09 do you know when the next release will be?

**Comment by ashishth09** [comment]
@TheSamSmith ,last week of Jan (tentative)

**Comment by Praveengostu** [comment]
Looking at this

**Comment by TheSamSmith** [comment]
@Praveengostu @ashishth09 Any updates on this?

**Comment by vkalangu** [comment]
The implementation is being reviewed internally

**Comment by ashishth09** [comment]
@TheSamSmith ,  https://github.com/IBM-Cloud/terraform-provider-ibm/pull/119 is in progress

**Comment by Praveengostu** [comment]
@TheSamSmith @bonifaido @marchmallow  , PR review is in progress.. and all tests have passed, could you please see if this is going to help you. Introduced a kube_version attribute, during the creation the master and workers are created with the same kube version. During update user has to take care of updating the worker nodes by specifying the version of each worker.  And for updating versions the user has to take care of after/before updates to cluster/worker via the provisioner resource.
