### ISSUE TITLE
Problems creating vpc cluster and worker pool using terraform and VPC

### ISSUE THREAD

**Issue by blm849** [IBM-Cloud/terraform-provider-ibm#865]
I was running terraform plan, using the main.tf here, and I received these errors:

Error: ibm_container_vpc_cluster.cluster: Provider doesn't support resource: ibm_container_vpc_cluster
Error: ibm_container_vpc_worker_pool.cluster_pool: Provider doesn't support resource: ibm_container_vpc_worker_pool

Running:
Terraform v0.11.14
+ provider.ibm v0.18.0
+ provider.random v2.2.1

Once I created the VPC using terraform, I was able to manually add a cluster to it.

**Comment by hkantare** [comment]
Please use latest release v0.19.0 .
We added support for cluster VPC in v0.19.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.19.0

The docs will be hosted shortly

**Comment by hkantare** [comment]
Sample example can be referred here
https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-cluster/vpc-classic-cluster
