### ISSUE TITLE
"ServiceEndpointDoesnotExist: UAA endpoint doesn't exist for region: \"jp-tok\""

### ISSUE THREAD

**Issue by bert2002** [IBM-Cloud/terraform-provider-ibm#878]
### Terraform Version
```
# terraform version
Terraform v0.11.14
+ provider.ibm v0.19.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_image

### Terraform Configuration Files
```hcl

provider "ibm" {
  ibmcloud_api_key   = "SECRETKEY"
  generation         = 1
  region             = "${var.region}"
  iaas_classic_username 	= "USERNAME"
  iaas_classic_api_key  	= "APIKEY"
}

data ibm_is_image "debian" {
  name = "ubuntu-18.04-amd64"
}
```

### Debug Output
```
Error: Error refreshing state: 1 error occurred:
	* data.ibm_is_image.debian: 1 error occurred:
	* data.ibm_is_image.debian: data.ibm_is_image.debian: Error occured while fetching auth key for vpc: "ServiceEndpointDoesnotExist: UAA endpoint doesn't exist for region: \"jp-tok\""
```

https://gist.github.com/bert2002/69204f4770bf6e7bdfca04b259b316f3

### Expected Behavior
- create vpc and one server (not visible in the configuration, because it already fails when running `plan`)

### Actual Behavior
- UAA endpoint error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
- VPC does not exist yet (not sure if that is important)

Any idea why this is failing with `ibm_is_image`?

**Comment by hkantare** [comment]
It a known issue already fixd in master . We will be releasing a v0.19.1 soon

**Comment by bert2002** [comment]
Anytime soon @hkantare? 

Wanted to build it from source and followed the Readme, but where can I find the provider after running `make build`?

**Comment by hkantare** [comment]
its will be under your GOPATH/bin folder

**Comment by hkantare** [comment]
Next week early we will have a minor relelase

**Comment by bert2002** [comment]
Found it. Thanks a lot.
