### ISSUE TITLE
Upgrade IBM Cloud Terraform provider to v0.12 

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#886]
Upgrade IBM cloud terraform provider to support v0.12 terraform version

**Comment by ankursri1** [comment]
This one is needed

**Comment by MalarvizhiK** [comment]
@SukeshPrabhakar @hkantare We need this provider support for Terraform 0.12 for our product as early as possible. Terraform 0.11 has many limitations.

**Comment by hkantare** [comment]
This will be availble in couple of weeks(early Jan 2020) we already have pre-releases which support v0.12.

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.0.0

Please try out the above release

**Comment by hkantare** [comment]
closing we upgraded to Terraform v0.12 from last couple of releases

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.1.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.0.0
