### ISSUE TITLE
ibm_container_cluster.workers attribute doesn't get re-read when the cluster is updated

### ISSUE THREAD

**Issue by bonifaido** [IBM-Cloud/terraform-provider-ibm#89]
The attribute is not available on the `cls` struct I think: https://github.com/IBM-Bluemix/terraform-provider-ibm/blob/master/ibm/resource_ibm_container_cluster.go#L319

**Comment by ashishth09** [comment]
That's right. They are set in the update method https://github.com/IBM-Bluemix/terraform-provider-ibm/blob/master/ibm/resource_ibm_container_cluster.go#L410,  but not read back and that means we lose some validation. But the state file still should have the workers when they are updated via terraform. As a larger picture, there is an open issue where we are re-considering the proper roll out of the workers. The container cluster API has also changed and the newer ones might support a better resource management.

**Comment by ashishth09** [comment]
Mostly its the worker name which was managed locally that can't be verified from the API

**Comment by Praveengostu** [comment]
Hi,We have deprecated the workers attribute from cluster in the latest release. Please use worker_num to define the number of workers to be added in the cluster ...
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.0
