### ISSUE TITLE
Support IKS on VPC NextGen 

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#893]
Support for provisioning IKS cluster on VPC NextGen

**Comment by y0zg** [comment]
@hkantare considering IKS VPC NextGen is release please provide an update https://www.ibm.com/cloud/blog/announcements/ibm-cloud-kubernetes-service-on-vpc-gen2

**Comment by hkantare** [comment]
@y0zg I'm not clear what update you require....The latest release v1.7.1 will helps you provision IKS on Nextgen

**Comment by hkantare** [comment]
This feature is available from last couple of releases

**Comment by y0zg** [comment]
@hkantare Isn't Nextgen is Gen2 which is mentioned in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.4.0

 _For creating either vpc-classic (generation=1) or **vpc-gen2 (generation=2) IKS cluster**, generation parameter needs to be set either in provider block or export via environment variable “IC_GENERATION”. By default the generation value is 2_

**Comment by hkantare** [comment]
@y0zg yes IKS Nextgen is Gen2

**Comment by y0zg** [comment]
@hkantare  Shouldn't we close this issue then as IKS VPC NextGen support is included in v1.4.0 ? Or there is something still needs to be done?
I'm researching whether terraform IKS nextgen (gen2) option is production ready or there are still some open issues, so asking such stupid questions :)

**Comment by hkantare** [comment]
Yes it can be closed...Thanks
