### ISSUE TITLE
Extend ibm_container_cluster_config with extra attributes

### ISSUE THREAD

**Issue by alexandrsemak** [IBM-Cloud/terraform-provider-ibm#895]
We faced issue that you can't use kubernetes provider when provisioning cluster from scratch. 
But until it not resolved can you extend ibm_container_cluster_config for getting [host, token, cluster_ca_certificate] which you can get in config.yaml but as terraform attribute.
for example:
```
host                             = "${data.ibm_container_cluster_config.cluster.host}"
token                           = "${data.ibm_container_cluster_config.cluster.token}"
cluster_ca_certificate = "${data.ibm_container_cluster_config.cluster.cluster_ca_certificate}"
```

Thank you.

**Comment by hkantare** [comment]
Added extra attributes and update doc with different section of examples
https://cloud.ibm.com/docs/terraform?topic=terraform-container-data-sources#container-cluster-config

**Comment by hkantare** [comment]
Fix a available in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.2
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.2

**Comment by alexandrsemak** [comment]
cool, thanks
