### ISSUE TITLE
Feature Request: Add Port to ibm_cis_healthcheck

### ISSUE THREAD

**Issue by somaya10** [IBM-Cloud/terraform-provider-ibm#901]
Provide `port` support to ibm_cis_healthcheck

https://ibm-cloud.github.io/tf-ibm-docs/v0.19.1/r/cis_healthcheck.html

Terraform Version
0.19.x

Affected Resource(s)
n/a

**Comment by jeremiaswerner** [comment]
That would be a great feature. I would need that as well :-)

**Comment by kavya498** [comment]
[available in](https://github.com/IBM-Cloud/terraform-provider-ibm/commit/1e655b82fc3dab0db4528b699c9daa20f916d920l)

**Comment by kavya498** [comment]
available in the commit https://github.com/IBM-Cloud/terraform-provider-ibm/commit/1e655b82fc3dab0db4528b699c9daa20f916d920l
