### ISSUE TITLE
I have the same problem as this closed issue #649

### ISSUE THREAD

**Issue by nicolas2lee** [IBM-Cloud/terraform-provider-ibm#913]
I have the same problem as this closed issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/649
If I try to add a new Resource Key to my Cloud Object Storage Account, I have some problems regarding the HMAC = True Parameter inside the ibm_resource_key Object.

'terraform apply' works perfectly. But If I do a 'terraform plan' afterwards, Terraform wants to create a new ibm_resource_key instance because it did not recognizance the HMAC Parameter.

# Terraform Version
Terraform v0.12.13

terraform-provider-ibm_v1.0.0
# Affected Resource(s)
-ibm_resource_key
-ibm_resource_instance

# Terraform Configuration Files
data "ibm_resource_group" "cos_group" {
  name = "Default"
}

resource "ibm_resource_instance" "cos_instance" {
  name              = "streaming-demo-cos"
  resource_group_id = "${data.ibm_resource_group.cos_group.id}"
  service           = "cloud-object-storage"
  plan              = "lite"
  location          = "global"
}

resource "ibm_cos_bucket" "standard-my-custom-demo-bucket" {
  bucket_name = "zt-a-standard-my-custom-demo-bucket"
  resource_instance_id = "${ibm_resource_instance.cos_instance.id}"
  #bucket_type = "cross_region_location"
  cross_region_location = "eu"
  storage_class = "standard"
}

resource "ibm_cos_bucket" "standard-my-custom-demo-bucket2" {
  bucket_name = "zt-a-standard-my-custom-demo-bucket2"
  resource_instance_id = "${ibm_resource_instance.cos_instance.id}"
  #bucket_type = "cross_region_location"
  cross_region_location = "eu"
  storage_class = "standard"
}

resource "ibm_resource_key" "cos_service_credential" {
  name = "cos_service_credential"
  role = "Writer"
  resource_instance_id = "${ibm_resource_instance.cos_instance.id}"

  parameters = {
    "HMAC" = true
  }
}
# Expected Behavior
ibm_resource_key Parameters are been recognized by terraform

# Actual Behavior
Terraform plan
  # ibm_resource_key.cos_service_credential will be created
  + resource "ibm_resource_key" "cos_service_credential" {
      + credentials          = (sensitive value)
      + crn                  = (known after apply)
      + id                   = (known after apply)
      + name                 = "cos_service_credential"
      + parameters           = {
          + "HMAC" = "true"
        }
      + resource_instance_id = "crn:v1:bluemix:public:cloud-object-storage:global:a/c59fc5efd8e74c9894c4ca42c2ceebcc:24043dde-eca5-49ca-acfe-4ad2552a7335::"
      + role                 = "Writer"
      + status               = (known after apply)
    }
# Result
But when I verify in ibm cloud web console, the below part is not generated,
  "cos_hmac_keys": {
    "access_key_id": "<access-key>",
    "secret_access_key": "<secret-key>"
  },

**Comment by umarali-nagoor** [comment]
Hi, 
      Please execute the scenario with following latest v0.12 plugin 

                   https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.0.0

**Comment by nicolas2lee** [comment]
Hi,

@umarali-nagoor I have followed your advice, test with the latest v0.12 plugin 
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.0.0

It works well.
