### ISSUE TITLE
Scaling ibm_database disk space

### ISSUE THREAD

**Issue by sashanka-kandala** [IBM-Cloud/terraform-provider-ibm#921]
Hi,

An issue in scaling members_disk_allocation_mb more than 1TB. Getting below error when giving 2097152 mb as a value to  members_disk_allocation_mb.

used ibm_database resource to provision the Postgres database.
Error: expected members_disk_allocation_mb to be in the range (2048 - 1048576), got 2097152
version:
Terraform v0.11.14
+ provider.ibm v0.17.5

**Comment by hkantare** [comment]
Fixed in  v0.20.0 release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.20.0

**Comment by sashanka-kandala** [comment]
working with v0.20.0
