### ISSUE TITLE
Feature Request: IBM Cloud Schematics - Add Environment Variables

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#922]
Hi there,
can you please add a way to setup environment variables to a Workspace. There are multiple scenarios where it can be very helpful:

######Scenario 1 - Azure Backend
If I want to setup a different Backend for my terraform state file I choose Azure. Due to the fact that I don't want to insert the credentials in the code I like to use the ARM_ACCESS_KEY how it is described in https://www.terraform.io/docs/backends/types/azurerm.html#access_key (to use a terraform variable is not allowed in a backend section)

######Scenario 2 - External Module - S3
In the case that I want to use an own written external module which is deployed on a S3 Storage it make sense to put the credentials in an environment variable. https://www.terraform.io/docs/modules/sources.html#s3-bucket

I think that there are many other cases in which it can be very useful!!

BTW: Please implement a sensitive checkbox to hide the content of the environment variable .

**Comment by hkantare** [comment]
closing the issue ...Schematics already support settign the env values while creaitng workspace
