### ISSUE TITLE
Feature Request: IBM Cloud Schematics - Add support for migrating terraform statefiles

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#923]
Hi there,
currently I have multiple Terraform projects. I like to have a way to implement migrate a terraform statefile into the new terraform backend. (maybe with help of the ibmcloud cli? 

e.g.
entrypoint: ibmcloud terraform statefile 
commands: 
show <workspace> - displays the current terraform state file of the workspace <workspace>
update <workspace> <tfStateFile> - update the terraform state file of workspace <workspace> with help of local statefile <tfStateFile>

**Comment by hkantare** [comment]
closing this its a schematic requirements ..Please open the issue on schematics
