### ISSUE TITLE
Feature Request - ibm_iam_user_policy - Plz enhance account management services

### ISSUE THREAD

**Issue by hweith** [IBM-Cloud/terraform-provider-ibm#931]
Hi there,
i'd like to configure account management services using terraform but it seems there's no way to grant permissions in ibm_iam_user_policy at the same level of granulatity as in the cloud.ibm gui.
I am missing the ability to define services like Support Center or Billing etc. It seems to work at "All account management services" level only.
Could you please add this feature?
Thanks.

**Comment by hkantare** [comment]
We are working to enhance this resource in phases..To support all different policies

**Comment by hkantare** [comment]
We already support creating policy for billing..
resource "ibm_iam_access_group_policy" "policy2" {
 access_group_id = "${ibm_iam_access_group.accgrp.id}"
 roles        = ["Administrator"]
 resources = [{
  service = "billing"
}]
May be we can try same thing for user_policy
