### ISSUE TITLE
ibm_is_subnet is missing a resource_group parameter

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#951]
VPC Subnets can be created in a resource group.

![image](https://user-images.githubusercontent.com/12746550/70835654-529bec80-1dc3-11ea-8ad0-609917663bc4.png)

Currently ibm_is_subnet does not expose this capability

![image](https://user-images.githubusercontent.com/12746550/70835633-44e66700-1dc3-11ea-9e89-ee6ffd51f273.png)

It should be added

**Comment by hkantare** [comment]
Released in latest Terraform releases
v1.0.0 and v0.22.0

**Comment by dprosper** [comment]
@hkantare fyi: I am looking at the docs for latest and I don't see resource_group described as an option: https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#subnet-input

**Comment by hkantare** [comment]
Its doc issues update in IBM  Cloud
https://ibm-cloud.github.io/tf-ibm-docs/v1.2.4/r/is_subnet.html
We will follow with doc team

**Comment by hkantare** [comment]
The docs are now updated 
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#subnet
