### ISSUE TITLE
Feature request: Import ibm_compute_vm_instance resource 

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#955]
Hi there,

can you please offer a way to import a Softlayer/IBM Cloud classic infrastructure VM?

I have an IBM Cloud account that uses many Softlayer VMs that needs to be part of a Terraform Script.
Therefore I want to import them as a ibm_compute_vm_instance resource

**Comment by hkantare** [comment]
We already have support for terraform import for vm
terraform import ibm_compute_vm_instance.test 88205074

**Comment by ThomasUllrich666** [comment]
Nice can you please describe this in the Documentation :-) I didn't found it there

**Comment by hkantare** [comment]
Updated the documentation to add import section
https://ibm-cloud.github.io/tf-ibm-docs/v1.1.0/r/compute_vm_instance.html
