### ISSUE TITLE
Feature Request: Add Terraform Support for Private DNS Service

### ISSUE THREAD

**Issue by lipingsh** [IBM-Cloud/terraform-provider-ibm#958]
Add Terraform Support for Private DNS Service, which went public Beta on Dec 13th, 2019, and is targeting GA in 1Q20.

Release note: https://ibm-cloudplatform.slack.com/archives/CGRJCF8MP/p1576251081001400

If needed, we can schedule a Webex or Slack thread to discuss the design details.

**Comment by csulrong** [comment]
Here is the golang client for Private DNS Services. 

https://github.ibm.com/NetworkTribe/pdns-go

**Comment by hkantare** [comment]
The terraform provider is a open source...Can this goclient can be open sourced presently its in GHE

**Comment by csulrong** [comment]
@hkantare I will update here once I get confirmative answer from our stakeholder for the open source.

**Comment by csulrong** [comment]
@hkantare We will prepare the open up of the pdns-go client code. Should we create the repo under this `IBM-Cloud` organization?

**Comment by hkantare** [comment]
It can be in any public organization. We maintained our sdk in  IBM-Cloud organization?

**Comment by hughhuangzh** [comment]
@hkantare Hi,  Private DNS service SDK is ready in public repo: https://github.com/IBM/dns-svcs-go-sdk, Please check.

**Comment by lipingsh** [comment]
@hkantare Pls let us know if there's anything else needed from our side. If not, would you plan this feature request in your roadmap? Thanks~

**Comment by ankursri1** [comment]
update on this task,
Now I could provision/unprovision p-DNS instance resources using Terraform. improvements planned in terms of input and update operations, will update once done.

Do you want to perform these actions?
 Terraform will perform the actions described above.
 Only 'yes' will be accepted to approve.
 Enter a value: yes
ibm_resource_instance.pdns-1: Creating...
ibm_resource_instance.pdns-1: Still creating... [10s elapsed]
ibm_resource_instance.pdns-1: Still creating... [20s elapsed]
ibm_resource_instance.pdns-1: Creation complete after 23s [id=crn:v1:bluemix:public:dns-svcs:global:a/ddb341a840bc42a2aee2e7a15152dbd6:ee69ae9e-697e-47da-bdbb-3262da1a3f82::]
ibm_dns_zone.pdns-1-zone: Creating...
ibm_dns_zone.pdns-1-zone: Creation complete after 6s [id=ee69ae9e-697e-47da-bdbb-3262da1a3f82/test.com:da482e6d-98c7-4043-9055-e483fc04fcb4]
ibm_dns_permitted_network.pdns-1-permitted-network: Creating...
ibm_dns_permitted_network.pdns-1-permitted-network: Creation complete after 5s [id=ee69ae9e-697e-47da-bdbb-3262da1a3f82/test.com:da482e6d-98c7-4043-9055-e483fc04fcb4/r006-8b232360-7ad1-4aed-92aa-08a272f6d949]
ibm_private_dns_record.pdns-1-records: Creating...
ibm_private_dns_record.pdns-1-records: Creation complete after 4s [id=ee69ae9e-697e-47da-bdbb-3262da1a3f82/test.com:da482e6d-98c7-4043-9055-e483fc04fcb4/A:f22eb8e2-40bd-478e-92a2-909e306612e9]
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

@sakthishanmugam02

**Comment by lipingsh** [comment]
@sakthishanmugam02 from @ankursri1's team is working on PDNS Terraform provider.

**Comment by sakthishanmugam2ibm** [comment]
Private DNS resource related changes merged to terraform. Below are links to respective PR's.

Examples can be found here: 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-private-dns/main.tf

**Zone:** 
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/1280

**Permitted Network:**
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/1290

**Resource Record:**
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/1305
