### ISSUE TITLE
Feature request: icd_database PostgreSQL instance as read-only replica

### ISSUE THREAD

**Issue by tpolekhin** [IBM-Cloud/terraform-provider-ibm#960]
Add support to provision Databases-for-PostgreSQL read-only replica instance using `icd_database` terraform resource.
Currently available only with `ibm_resource_instance` with `parameters` block:
```
resource "ibm_resource_instance" "psql-read-replica" {
  name = "read-only-replica"
  location = "us-south"
  service = "databases-for-postgresql"
  plan = "standard"
  resource_group_id = "<resource-group-id>"

  parameters = {
    remote_leader_id = "<psql-leader-instance-id>"
  }
}
```

**Comment by VaishnaviGopal** [comment]
Hi @tomwganem , if available, can you share any docs about this parameter `remote_leader_id`? and please share If there is any working example with this parameter.

**Comment by allen-servedio** [comment]
@VaishnaviGopal - not sure if this is what you were looking for, but there is this: https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=databases-for-postgresql-read-only-replicas

**Comment by tomwganem** [comment]
> Hi @tomwganem , if available, can you share any docs about this parameter `remote_leader_id`? and please share If there is any working example with this parameter.

@VaishnaviGopal I'm assuming you didn't mean to tag me, yeah?

**Comment by VaishnaviGopal** [comment]
> > Hi @tomwganem , if available, can you share any docs about this parameter `remote_leader_id`? and please share If there is any working example with this parameter.
> 
> @VaishnaviGopal I'm assuming you didn't mean to tag me, yeah?

>yeah.. i am sorry

**Comment by allen-servedio** [comment]
So @VaishnaviGopal - was that the documentation you were looking for (https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=databases-for-postgresql-read-only-replicas) - or were you looking for something else?
