### ISSUE TITLE
Feature request:  datasource to retrieve subnet using name

### ISSUE THREAD

**Issue by jaysonjs** [IBM-Cloud/terraform-provider-ibm#968]
Can we have a datasource to retrieve subnet using name so that we don't need to hardcoding subnet id in the code?
The following is how to fetch subnet details;
https://ibm-cloud.github.io/tf-ibm-docs/v0.21.0/d/is_subnet.html

CS1466858

**Comment by srtarch** [comment]
I need this feature as well.  Personally I see it as a bug that a subnet can't be retrieved by name.  Please give this some consideration.

**Comment by hkantare** [comment]
This feature is released and available in latest releases
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_subnet
