### ISSUE TITLE
data "ibm_function_package" "bridgepy" complains about Namespace

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#972]
Trying to use the function package as described here:
https://ibm-cloud.github.io/tf-ibm-docs/v0.21.0/d/function_package.html

I've also tried to create a function package:
https://ibm-cloud.github.io/tf-ibm-docs/v0.21.0/r/function_package.html

Both with similar results.  Complaining about Namespace which I can not find a reference to in the docs.

```
(bridgepy) ~/github.com/powellquiring/bridgepy/functions $ cat main.tf
variable ibmcloud_api_key {}
variable resource_group_name {
  default = "default"
}

variable "ibmcloud_timeout" {
  description = "Timeout for API operations in seconds."
  default     = 900
}

variable region {
  default = "us-south"
}

provider ibm {
  region           = "${var.region}"
  ibmcloud_api_key = "${var.ibmcloud_api_key}"
  ibmcloud_timeout = "${var.ibmcloud_timeout}"
}


data "ibm_function_package" "bridgepy" {
  name = "acme_dev"
}

(bridgepy) ~/github.com/powellquiring/bridgepy/functions $ tfa
data.ibm_function_package.bridgepy: Refreshing state...

Error: Error refreshing state: 1 error occurred:
	* data.ibm_function_package.bridgepy: 1 error occurred:
	* data.ibm_function_package.bridgepy: data.ibm_function_package.bridgepy: Namespace is (), it must be of the form <org>_<space>, provider can't find the auth key if you use _ as well

```

### Terraform Version
```
(bridgepy) ~/github.com/powellquiring/bridgepy/functions $ tf version
Terraform v0.11.14
+ provider.ibm v0.21.0

Your version of Terraform is out of date! The latest version
is 0.12.18. You can update by downloading from www.terraform.io/downloads.html
```
### Expected Behavior
Docs to describe the Namespace.  This also seems to be referencing cloud foundry org/space and functions also support the IAM.
The error message: `Namespace is (), it must be of the form <org>_<space>, provider can't find the auth key if you use _ as well` does not help me out.

I think the following needs to be done
- Explain the need for function_namespace in the provider, include a link to the provider section
- Change the error message to something like: The `provider ibm` must include a `function_namespace` argument and it must be in the format <org>_<space> ...
- Make the necessary changes to the docs to support IAM in addition to cloud foundry <org>_<space>.

Maybe the above are 3 different issues?

**Comment by hkantare** [comment]
For function provider argument function_namespace is a required parameter. 
Presently we have support for org_space namespace..We don't have support yet for IAM support
We have feature request issues 

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/642

**Comment by hkantare** [comment]
closing this issue since we support IAM based namespaces also now
