### ISSUE TITLE
Unable to configure geo routes for CIS

### ISSUE THREAD

**Issue by ganhuang** [IBM-Cloud/terraform-provider-ibm#985]
Hi there,

### Affected Resource(s)
- ibm_cis_global_load_balancer

In the documentation, https://ibm-cloud.github.io/tf-ibm-docs/v0.21.0/r/cis_global_load_balancer.html it appears that IBM terraform provider doesn't support to configure CIS geo routes, this could be done via IBM cloud portal.

**Comment by hkantare** [comment]
supported in latest release v1.12.0
