### ISSUE TITLE
Feature Request: Resizing of VPC clusters on IKS

### ISSUE THREAD

**Issue by somaya10** [IBM-Cloud/terraform-provider-ibm#993]
Provide a native mechanism to resize the VPC clusters and worker pools.

Terraform Version
0.11.x

Affected Resource(s)
n/a

**Comment by hkantare** [comment]
Availablein latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.2.0
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.24.0
